### ISSUE TITLE
Survey Creator V1 - Items editor - Item titles data loss

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#1006]
1. Drop radiogroup
2. Open choices editor -> fast entry mode
3. Inplace edit item title (or value)
4. Switch from fast entry to form entry
5. Entered on step 3 text is lost (overridden by fast entry tab content)

**Comment by JaneSjs** [comment]
Reproduced in a Survey Creator V1 https://surveyjs.io/survey-creator/examples/free-nps-survey-template/knockoutjsv1


https://github.com/surveyjs/survey-creator/assets/22372972/313162a8-12bf-4896-8470-65f93435cc9e
