### ISSUE TITLE
Rating items adorner crashes after adding custom rate values

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-creator#1011]
1) Go to https://surveyjs.io/create-survey
2) Add rating question
3) Add custom rate value in Rate Values section
4) ???
5) Items adorner of rating is broken in designer

![image](https://user-images.githubusercontent.com/30930391/99276007-3effce00-283d-11eb-9059-799f6f09f2d3.png)

**Comment by koni1234** [comment]
Hi @andrewtelnov are there any news about resolution of this bug?
Currently on my project I have updated the library to the last version 1.8.45 and I noticed that there are other new regressions :-(

When i try to edit. a value from the survey designer box all widgets values "disappear" and there is a JS errors


<img width="808" alt="Schermata 2021-04-28 alle 22 59 05" src="https://user-images.githubusercontent.com/6827908/116473664-c1be9780-a877-11eb-8660-e5f4a70a6ac6.png">

This error is also reproducible on the survey creator demo visible at the page https://surveyjs.io/create-survey

<img width="557" alt="Schermata 2021-04-28 alle 20 29 51" src="https://user-images.githubusercontent.com/6827908/116473899-13ffb880-a878-11eb-8935-126a3e17e2c9.png">
<img width="457" alt="Schermata 2021-04-28 alle 20 30 00" src="https://user-images.githubusercontent.com/6827908/116473910-16621280-a878-11eb-8d73-df14365b67bc.png">

Thank you in advance

**Comment by tsv2013** [comment]
@koni1234  I'll take a look.

**Comment by tsv2013** [comment]
Fix will be available in the nearest minor update

**Comment by koni1234** [comment]
@tsv2013 thank you very much
