### ISSUE TITLE
Creator tab change resets window location hash

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#1012]
See the https://surveyjs.answerdesk.io/ticket/details/t5675/creator-tab-change-kills-url thread for more details

**Comment by agustinparamio** [comment]
@tsv2013 can you copy the thread here? I can't access a private ticket. I think I have the same issue

**Comment by tsv2013** [comment]
@agustinparamio I can't share a private tickets here. I hope the issue title is enough. The issue is simple and describable in one sentence.
