### ISSUE TITLE
Suggestion/Question UX

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-creator#1023]
### Are you requesting a feature, reporting a bug or ask a question?
Suggestion/Question

### What is the current behavior?

When we are editing a question/options/row... on clicking on tab key we should go to the next editable input, not the default behavior

### What is the expected behavior?

When i press tab key we should go to the next editable input

Image 1 : Im editing
![image](https://user-images.githubusercontent.com/30509391/100872302-84f19e80-3499-11eb-9f3e-b5c3f919b256.png)
image 2 : i press tab
![image](https://user-images.githubusercontent.com/30509391/100872344-93d85100-3499-11eb-8d87-f7216d14c111.png)
image 3  : this is what im extecing to happen
![image](https://user-images.githubusercontent.com/30509391/100872383-a488c700-3499-11eb-9857-079d7ae68206.png)

* browser:
* editor version:

**Comment by tsv2013** [comment]
In this case delete button will not be accissible
