### ISSUE TITLE
Dynamic update survey model in survey Creator from my own component.

### ISSUE THREAD

**Issue by bershek** [surveyjs/survey-creator#1051]
### Are you requesting a feature, reporting a bug or ask a question?
Question.
Hi. I`m trying to dynamically add my prefilled templates of questions in survey Creator. Instead of filling all the components from the beginning, I have few json templates that I want to add to survey Creator json model from my own component.
Is it possible to listen to current json model state? Maybe there is a method to listen for updates in Survey Create Model?

This an example what i am trying to do
```
surveyCreator = new SurveyJSCreator.SurveyCreator('surveyCreatorContainer', options);
creator.current.addEventListener('some listener to watch a current state',  setSurveyJsonModel});
```

**Comment by andrewtelnov** [comment]
@bershek You question is general. What do you want to listen?
creator has survey property, `creator.survey` it is a current editing survey that you see on the design surface in "design" mode.
You can probably use [creator.onModified](https://surveyjs.io/Documentation/Survey-Creator?id=surveycreator#onModified) event.

Thank you,
Andrew

**Comment by bershek** [comment]
Thank you @andrewtelnov
