### ISSUE TITLE
Set active page in survey Designer

### ISSUE THREAD

**Issue by bershek** [surveyjs/survey-creator#1054]
### Are you requesting a feature, reporting a bug or ask a question?
Question.
Is it possible to set an active page number when I work with Survey Creator? When I`m trying to update a SurveyModel, from the second page, the component rerenders, and I see the first page active by default. https://prnt.sc/wg1w9b Is it possible to set the second page active in Survey Creator ?

**Comment by andrewtelnov** [comment]
@bershek `creator.survey.currentPageNo = 1;`

Thank you,
Andrew

**Comment by bershek** [comment]
@andrewtelnov, sorry this field don't changed data in surveyCreator model, I have every time in  `surveyCreator.survey.currentPageNo` = 0;  https://prnt.sc/wgluse
` surveyCreator = new SurveyJSCreator.SurveyCreator('surveyCreatorContainer', options);
   surveyCreator.survey.currentPageNo = surveyCreator.survey.PageCount;
`

**Comment by bershek** [comment]
Hi @andrewtelnov  I cannot setup current page, here in example i am showing this case: https://codepen.io/Bersh/project/editor/ZdkyWP#

**Comment by andrewtelnov** [comment]
@bershek Right, here is the corrected code:
`creator.selectedElement = creator.survey.pages[1];`
Here is [the example](https://plnkr.co/edit/rbnFoceyurxPrRMy).

Thank you,
Andrew

**Comment by bershek** [comment]
Thank's @andrewtelnov
