### ISSUE TITLE
Changing question name in Modal window doesn't update expressions (visibleIf/enableIf...)

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-creator#1055]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?
When i have the property grid disabled, when we edit a question , its opens a modal with the information of question , if we rename a question inside of this modal , dont have the same behavior (my visibleifs of all my questions are not renamed)
Example
question 1
question 2 visbleif : {question1} = OUI
question 3
/////////////////////////// AFTER RENAME
food_enviroment_available
question 2 visbleif : {question1} = OUI
question 3
### What is the expected behavior?
Independent for a property grid, being active or not(modal) , its must works on same way
Example : 
question 1
question 2 visbleif : {question1} = OUI
question 3
/////////////////////////// AFTER RENAME
food_enviroment_available
question 2 visbleif : {food_enviroment_available} = OUI
question 3
### How would you reproduce the current behavior (if this is a bug)?
If you create questions and set on any question a visible if that depends from another, and do the rename, this events never happens

### Specify your

* browser:chrome
* editor version:last (i test on your site also)

**Comment by andrewtelnov** [comment]
@jmar1998 Fixed by the commit above.

Thank you,
Andrew
