### ISSUE TITLE
Making non-breaking changes to a survey

### ISSUE THREAD

**Issue by nathan-at-jisc** [surveyjs/survey-creator#1063]
Currently we have a service that uses/will be using SurveyJS.

The process is that a survey can be edited. Once the survey has been launched, it cannot be edited.

However, we want to only be able to make non-breaking changes to a survey.

Is there a way to make sure that when editing a survey, we can only do non-breaking changes (i.e things that won't break the analytics, so title changes etc).

If there's no way to do this, I imagine we will need to allow the user to edit a survey, and compare any changes they make to a saved version and check for breaking changes. Ideally we'd like to grey things out that user's can't change.

**Comment by andrewtelnov** [comment]
@nathan-at-jisc You disable operations and make only several properties non read-only.
Here is [the example](https://plnkr.co/edit/2GOxmeIPCdZTM66T?preview).

Thank you,
Andrew

**Comment by tsv2013** [comment]
You can make page editor read only via the following code:
```JS
creator.pagesEditorModel.readOnly = true;
```

Here is the updated plunker - https://plnkr.co/edit/lb5rsM2oIE1WZj9a

**Comment by nathan-at-jisc** [comment]
Perfect, thanks both. This looks fantastic, nice one!
