### ISSUE TITLE
showDesignTab: false not working

### ISSUE THREAD

**Issue by RixBai** [surveyjs/survey-creator#1067]
### What is the current behavior?
showDesignTab: false not displaying form

### What is the expected behavior?
We just want to display test survey form.
To do this I set all the other options `false` except `showTestSurveyTab`.
Then it shows me the form is not available.
It was working on the previous version. 1.7.4
We are migrating to latest version and encountered this problem.

#### Provide the test code and the tested page URL (if applicable)

Test code

```
  const surveyOptions = {
    showJSONEditorTab: false,
    showLogicTab: false,
    showTestSurveyTab: true,
    showDesignerTab: false,
    readOnly: true,
  };

  const surveyLogicViewer = new SurveyJSCreator.SurveyCreator(
    'formLogicViewerContainer',
    surveyOptions
  );

```

**Comment by RixBai** [comment]
<img width="876" alt="image" src="https://user-images.githubusercontent.com/43899212/105518783-4b216500-5c9e-11eb-894e-57d7d88f4beb.png">
This is what I am getting when setting `showDesignerTab: false`

**Comment by RixBai** [comment]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/43899212/105518978-87ed5c00-5c9e-11eb-82e0-5ad9a06605ea.png">
This is what I am getting when setting `showDesignerTab: false`.

**Comment by andrewtelnov** [comment]
@RixBai I can see that @tsv2013 has investigate the issue and mark it as a bug. We will work on the fix and come back to you.

Thank you,
Andrew

**Comment by RixBai** [comment]
Thank you Andrew!

**Comment by tsv2013** [comment]
I've fixed the issue.
