### ISSUE TITLE
onElementNameChanged event is not fired on editing element in modal window

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-creator#1068]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

Error when we are triggering the following events
onElementNameChanged
onPropertyAfterRender
when the showPropertyGrid is false
idk what others events are not working
### What is the expected behavior?
Trigger events normally
### How would you reproduce the current behavior (if this is a bug)?
https://plnkr.co/edit/2FustyniUAd9NsZO
### Specify your

* browser:
* editor version: last

**Comment by jmar1998** [comment]
hello @andrewtelnov any info about this issue ??

**Comment by andrewtelnov** [comment]
@jmar1998 Do you mean that we do not call these events?
`onPropertyAfterRender` fires after a property editor is rendered for the first time - you do not have property grid, you do not have a property editor and as result this event can't be fired.
The same story with `onElementNameChanged` event. It calls when an element name is changed. You do not change the element name, commonly change name property in property grid, and as result this event is not fired.

Thank you,
Andrew

**Comment by jmar1998** [comment]
@andrewtelnov , but when we dont have the property grid, we got a property modal i suppose that the events should trigger also on this case, because we can change properties + name of question on this modal

**Comment by jmar1998** [comment]
im talking about this modal 
![image](https://user-images.githubusercontent.com/30509391/105862785-1851d680-5fe8-11eb-838f-9801e55436df.png)

**Comment by andrewtelnov** [comment]
@jmar1998 Indeed, forgot about this functionality. We will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@jmar1998 I have fixed the issue with "onElementNameChanged" event. "onPropertyAfterRender" event works fine in non plunker enviroment. Do you have issues with "onPropertyAfterRender" in your enviroment?

Thank you,
Andrew

**Comment by jmar1998** [comment]
@andrewtelnov , yes i got the same issue on my enviroment/plunker, even on the folder example inside the survey creator package (i clone the repo to have more info), let me show you
 This is without showPropertyGrid
![image](https://user-images.githubusercontent.com/30509391/105960903-c2c40b00-6075-11eb-961e-7e1b6568c2aa.png)
![image](https://user-images.githubusercontent.com/30509391/105960987-da02f880-6075-11eb-81cc-327bcdf99798.png)

**Comment by jmar1998** [comment]
@andrewtelnov this is with the property active
![image](https://user-images.githubusercontent.com/30509391/105961276-3403be00-6076-11eb-8e51-58514d436113.png)

**Comment by andrewtelnov** [comment]
@jmar1998 I got the following errors in plunker: "Blocked autofocusing on a <input> element in a cross-origin subframe". This is a common error when you are using iFrame.
Do you use IFrame in your app?

Thank you,
Andrew

**Comment by jmar1998** [comment]
@andrewtelnov i dont use an i frame, the code its on my main view, and i also test on the example that you provide on your repository and i got  the same issue, this is the code of index.js
`if (!window["%hammerhead%"]) {
  //   var titleAdorner = {
  //     getCss: () => {
  //       return "mu_title";
  //     },
  //     afterRender: (domEl, model) => {
  //       var decoration = document.createElement("div");
  //       decoration.innerHTML = "";
  //       domEl.appendChild(decoration);
  //     }
  //   };

  //   SurveyCreator.registerAdorner("title", titleAdorner);

  // SurveyCreator.editorLocalization.currentLocale = "fr";

  // SurveyCreator.removeAdorners(["mainRoot"]);

  // Survey.Survey.cssType = "bootstrap";
  // Survey.defaultBootstrapCss.navigationButton = "btn btn-green";
  // SurveyCreator.editorLocalization.currentLocale = "hu";
  // SurveyCreator.StylesManager.applyTheme("winter");

  //color customization
  var mainColor = "#0065FF";
  var mainHoverColor = "#60C5FB";
  var textColor = "#4a4a4a";
  var headerColor = "#4a4a4a";
  var headerBackgroundColor = "#4a4a4a";
  var bodyContainerBackgroundColor = "#f8f8f8";

  var defaultThemeColorsSurvey = Survey.StylesManager.ThemeColors["default"];
  defaultThemeColorsSurvey["$main-color"] = mainColor;
  defaultThemeColorsSurvey["$main-hover-color"] = mainHoverColor;
  defaultThemeColorsSurvey["$text-color"] = textColor;
  defaultThemeColorsSurvey["$header-color"] = headerColor;
  defaultThemeColorsSurvey["$header-background-color"] = headerBackgroundColor;
  defaultThemeColorsSurvey[
    "$body-container-background-color"
  ] = bodyContainerBackgroundColor;

  var defaultThemeColorsEditor =
    SurveyCreator.StylesManager.ThemeColors["default"];
  defaultThemeColorsEditor["$primary-color"] = mainColor;
  defaultThemeColorsEditor["$secondary-color"] = mainColor;
  defaultThemeColorsEditor["$primary-hover-color"] = mainHoverColor;
  defaultThemeColorsEditor["$primary-text-color"] = textColor;
  defaultThemeColorsEditor["$selection-border-color"] = mainColor;

  Survey.StylesManager.applyTheme();
  SurveyCreator.StylesManager.applyTheme();
  //
  
  SurveyCreator.SurveyJSONEditor.aceBasePath = "https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.10/";


  var options = {
    questionTypes: [
      "text",
      "checkbox",
      "radiogroup",
      "dropdown",
      "comment",
      "rating",
      "imagepicker",
      "boolean",
      "html",
      "file",
      "expression"
    ],
    pageEditMode: "single",
    showPropertyGrid: false,
  };
  var creator = new SurveyCreator.SurveyCreator("editorElement", options);
  creator.showToolbox = "right";
  creator.rightContainerActiveItem("toolbox");
  creator.toolbarItems.splice(2, 5);
  creator.placeholderHtml = `
    <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); text-align: center;">
      <img src="./drag-image.svg"/>
      <div style="font-size: 16px; max-width: 210px;">
        Drag and drop a question to start designing your form
      </div>
    </div>`;
  creator.onPropertyAfterRender.add(function(){
    alert('hey');
  })
  creator.saveSurveyFunc = function(saveNo, callback) {
    alert("ok");
    callback(saveNo, true);
  };

  window.creator = creator;
}`

**Comment by jmar1998** [comment]
@andrewtelnov  i got the same behavior on my enviroment and on that example enviroment
to run the env i sue
npm run build_dev
npm run start

**Comment by andrewtelnov** [comment]
@jmar1998 What error do you have? I can't reproduce it locally :(
Could you please check your console tab in DevTools?

Thank you,
Andrew

**Comment by jmar1998** [comment]
@andrewtelnov im not getting any error on console just an unexpected behavior i record a video for you , i hope is useful for you
https://vimeo.com/505147982

**Comment by andrewtelnov** [comment]
@jmar1998 I see. We will take a look. Probably fixing issue in plunker will solve the issue.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@jmar1998 I have just checked and it works in v1.7.27. Here is [the updated example](https://plnkr.co/edit/OBbyY0VAM3gjR6o5).

Thank you,
Andrew
