### ISSUE TITLE
Error on visible if on matrix questions when it is located in panel dynamic

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-creator#1072]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?

When the matrix questions are inside of a panel dynamic question , the logic builder have a different behavior, and got a exception

![image](https://user-images.githubusercontent.com/30509391/105860750-d45dd200-5fe5-11eb-9cc4-0b69942b439a.png)

### What is the expected behavior?

![image](https://user-images.githubusercontent.com/30509391/105861210-61a12680-5fe6-11eb-9f5c-29e602c626ee.png)

### How would you reproduce the current behavior (if this is a bug)?
If you create all the matrix type questions inside of surveyjs and try to create a visible if condition through the builder , you got this wrong behavior 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/VpqGPpofMb26h4JD

### Specify your

* browser: last
* editor version: last

**Comment by andrewtelnov** [comment]
@jmar1998 We will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@jmar1998 Fixed by the commit above.

Thank you,
Andrew
