### ISSUE TITLE
Unable to switch pages in Test Survey

### ISSUE THREAD

**Issue by jmlopezo** [surveyjs/survey-creator#1073]
### Are you requesting a feature, reporting a bug or ask a question?

In the current version it does not work to change pages in test survey tab

### Specify your

* browser:
  - Safari macOS Big Sur
  - Chrome 88 Windows 10
* editor version:
  - 1.8.27

**Comment by andrewtelnov** [comment]
@jmlopezo How could we reproduce the issue?

Thank you,
Andrew

**Comment by jmlopezo** [comment]
Hi Andrew,

here an example in plunker, go to the Test Survey tab and try to change the page.

https://plnkr.co/edit/kReRoAruPucJLVVL

**Comment by andrewtelnov** [comment]
@jmlopezo Yes, indeed. Interesting, how it could pass our 2E2 tests. We will fix it ASAP.

Thank you,
Andrew

**Comment by jmlopezo** [comment]
@andrewtelnov Ok, Thanks.

**Comment by tsv2013** [comment]
I've fixed the issue and updated site.
