### ISSUE TITLE
Error on translation tab when we use dataList Property

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-creator#1075]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?
Im getting an exception , when i fill the datalist property
![image](https://user-images.githubusercontent.com/30509391/106598345-81d56600-654f-11eb-8949-e66e024f9a10.png)

### What is the expected behavior?
datalist should be translatable

### How would you reproduce the current behavior (if this is a bug)?

1) Create one question type text or comment
2) Edit dataList attribute
3) Go to translation tab

### Specify your

* browser: Chrome/Firefox
* editor version: Last

**Comment by andrewtelnov** [comment]
@jmar1998 Could we reproduce the issue on our website?

Thank you,
Andrew

**Comment by jmar1998** [comment]
Hello @andrewtelnov  , yes i could , i also create a plunker for you
https://plnkr.co/edit/2QK37idJuLpnMeCO
i got an error on console
i notice it , because on our enviroment we dont allow any kind of js exception and stop any user interaction

**Comment by jmar1998** [comment]
this is the error output on surveyjs site
![image](https://user-images.githubusercontent.com/30509391/106620208-3e87f100-6569-11eb-9a53-3ef2e50bd8f4.png)

**Comment by andrewtelnov** [comment]
@jmar1998 Fixed by commits above and by implementing [this functionality](https://github.com/surveyjs/survey-library/issues/2643).

Thank you,
Andrew

**Comment by jmar1998** [comment]
@andrewtelnov thanks alot :) :+1:
