### ISSUE TITLE
How can i save active tab?

### ISSUE THREAD

**Issue by bershek** [surveyjs/survey-creator#1081]
Hi, could you help me save active tab, I need save "translation" tab as active tab and after reload browser page "translation" tab  should be as active.
<img width="1440" alt="img" src="https://user-images.githubusercontent.com/11584269/107956431-d218e300-6fa7-11eb-8b11-36265c335630.png">

**Comment by andrewtelnov** [comment]
@bershek You can use [creator.onActiveTabChanged](https://surveyjs.io/Documentation/Survey-Creator?id=surveycreator#onActiveTabChanged) event to know a new active tab and you can use [creator.makeNewViewActive](https://surveyjs.io/Documentation/Survey-Creator?id=surveycreator#makeNewViewActive) function to change the current active tab.

Thank you,
Andrew
