### ISSUE TITLE
Inconsistent typing in matrix values

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#1088]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

Our users are seeing inconsistent types in the JSON when they enter numeric values for matrix questions:
```
{
    "type": "matrix",
    "columns": [
        {
            "value": "1",
            "text": "Windows",
        },
        {
            "value": 2,
            "text": "Android",
        }
    ]
```

### What is the expected behavior?

I'd expect that input via the graphical editor is consistently typed, so all numeric strings become integers, or none of them do. 

### How would you reproduce the current behavior (if this is a bug)?

1. Create a matrix question type
2. Remove all rows
3. Add 1 row, the default text shows `Row 1`, changes this to `1`
4. Switch to json editor, see that the value is a string `"1"`
5. Switch to graphical editor
6. Add 1 row, the default text shows `2`.
7. Switch to json editor, see that the value is an integer `2`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/create-survey

### Specify your

* browser: Brave latest, tested on multiple browsers
* editor version: latest

**Comment by andrewtelnov** [comment]
@SamMousa I will mark this issue as a bug. However, to be honest I do not know how to fix it yet. We will comeback to it when we will fix bugs for SurveyJS Creator V2.

Thank you,
Andrew

**Comment by novikov82** [comment]
We just checked your scenario on the latest version of Creator V1 - https://surveyjs.io/create-survey
It works OK for us. Could you check it on your side?

**Comment by novikov82** [comment]
We also checked it in Creator V2 - https://surveyjs.io/Examples/Survey-Creator?id=options&platform=ReactjsV2

**Comment by SamMousa** [comment]
I will retest as soon as I can, will be early October.

**Comment by SamMousa** [comment]
Can confirm that any editing now changes it to a string!
