### ISSUE TITLE
'english' String Localization/Replacement

### ISSUE THREAD

**Issue by SaraaAwwad** [surveyjs/survey-creator#1090]
### Are you requesting a feature, reporting a bug or ask a question?
[Question]

### What is the current behavior?
Default ('english') is written with lowercase E.

### What is the expected behavior?
I want to write 'english' as 'English', I have all the keys that is provided so I can change/localize Survey Strings but I cant find where english is written. Is there any available key for it?
![Screenshot (81)](https://user-images.githubusercontent.com/29264144/109169310-562d5080-7788-11eb-9a94-8d9a965a00cb.png)

**Comment by andrewtelnov** [comment]
@SaraaAwwad Please the following code:
`Survey.surveyLocalization.localeNames["en"] = "English";`

Thank you,
Andrew

**Comment by SaraaAwwad** [comment]
It worked as wanted, thank you. :)
