### ISSUE TITLE
Changing locale for the survey designer doesn't load the questions in the specified locale

### ISSUE THREAD

**Issue by HamzaETTH** [surveyjs/survey-creator#1098]
### Are you requesting a feature, reporting a bug or ask a question?
Bug/Feature

### What is the current behavior?
The survey designer will be loaded in the specified locale (SurveyCreator.localization.currentLocale) but not the questions

### What is the expected behavior?
Have the questions load in the specified locale.

### How would you reproduce the current behavior (if this is a bug)?
I edited the example from here https://surveyjs.io/Examples/Survey-Creator/?id=multiplelanguages and added the following line:

SurveyCreator.localization.currentLocale = "de";

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/IIpblwZLZPkWvUAX

### Specify your

* browser: Firefox
* editor version: latest? surveycreator 1.8.32

**Comment by andrewtelnov** [comment]
@HamzaETTH In the survey JSON you have the `locale: "en"`. Please remove it and you will get the default locale, that 'de' in your example.

Thank you,
Andrew

**Comment by HamzaETTH** [comment]
> 
> 
> @HamzaETTH In the survey JSON you have the `locale: "en"`. Please remove it and you will get the default locale, that 'de' in your example.
> 
> Thank you,
> Andrew

Thanks, but this change only made the choices shows the german strings but not the row text (e.g. Zootopia/Zoomania).

**Comment by andrewtelnov** [comment]
@HamzaETTH It shows strings from "default" locale. 
```js
text: {
 default: "Zootopia",
  de: "Zoomania"
}
```
You would need to change it to:
```js
text: {
 default: "Zoomania",
  en: "Zootopia"
}
```
This is what you would have if your default locale was "de" on creating the survey.

Thank you,
Andrew

**Comment by HamzaETTH** [comment]
What I'm trying to do is load a survey creator with already defined questions in two languages (english and chinese for example).

I'd like for the survey creator to completely render (including the questions) in english OR chinese depending on the user language. In my case, there no default language since the surveycreator could be created and loaded in either english or chinese.

Is that possible?

**Comment by andrewtelnov** [comment]
@HamzaETTH Sure, you can change the default locale for survey and Creator.
```js
Survey.surveyLocalization.defaultLocale = "cn";
SurveyCreator.editorLocalization.defaultLocale = "cn";
```
and hide the localization property from the property grid as:
```js
Survey.Serializer.findProperty("survey", "locale").visible = false;
```
You chines users will have everything in "cn" locale it will not be able to change it.
For your english speaking users, you can hide the locale property only, "en" is the default locale, be default.

Thank you,
Andrew

**Comment by HamzaETTH** [comment]
This is not exactly what I'm looking for. What I want is to be able to load the same surveycreator **completely** (the surveu creator itself and the questions) in either chinese or english without removing the ability to translate.

When a user settings are in english. Load the surveycreator in English 
`var locale = en; SurveyCreator.localization.currentLocal ="en";`
and show the question in english locale. 

If the same user change his settings (in my website) to Chinese
`var locale = cn; SurveyCreator.localization.currentLocal ="cn";`
and show the question in chinese.

So the surveycreator by itself load in the language I want just fine (en/cn) but not question. I just want a way for this:
 
![image](https://user-images.githubusercontent.com/73552421/110489270-42091d80-80bd-11eb-8329-d94d37e8bfc6.png)

to automatically be changed to chinese when the user language settings are in chinese.

**Comment by HamzaETTH** [comment]
I'm still having trouble with this, maybe there something I don't understand. I've made a new test page here [https://plnkr.co/edit/NghzyBskBi4Wwbjj](https://plnkr.co/edit/NghzyBskBi4Wwbjj)

I'm simply trying to load everything in DE without changing the json structure. Right now, the creator UI is in DE but it's loading the questions in english  **default: "1 (the worst)"** instead of **de: "1 (Das Schlechteste)"** .

How do I achieve that?

**Comment by andrewtelnov** [comment]
@HamzaETTH You set default to "de", but your default strings are in english. You should do opposite. You should have default strings in Deutsch and "en" for English strings.

Thank you,
Andrew

**Comment by HamzaETTH** [comment]
Ok here we go: https://plnkr.co/edit/yJX4fbxzT2G0mCyD .

I get what defaultLocale does but it's still not what I want. I want to load questions in Deutsch even though the default locale is english (without changing the json).

I basically want what happen when this is selected on load; [https://i.imgur.com/FBNTD9H.png](https://i.imgur.com/FBNTD9H.png)

**Comment by andrewtelnov** [comment]
@HamzaETTH There are two options.
1) set survey locale to "de" for your last example. Here is the [updated version 1](https://plnkr.co/edit/sZLo2aBn9gAU1s51) or set the default locale to "de" and switch your default/de strings [updated version 2](https://plnkr.co/edit/je6YSPnncg1YoVS3?preview).

Thank you,
Andrew

**Comment by HamzaETTH** [comment]
thank you, the locale line was what I needed.
