### ISSUE TITLE
Ranking question does not show up in test survey

### ISSUE THREAD

**Issue by prashanthsridhar** [surveyjs/survey-creator#1100]
### Are you requesting a feature, reporting a bug or ask a question?
i think it's a bug,but it maybe a question.
Has anyone faced a similar problem and if so please suggest a solution

### What is the current behavior?

![image](https://user-images.githubusercontent.com/11289456/110361127-997b9f00-8065-11eb-83c4-2b1a642be644.png)
when selected it does not show up in the test survey

### What is the expected behavior?
it should show up

Test code

```
    this.creatorRef.text = JSON.stringify(data)
    this.creatorRef.showToolbox = 'right';
    this.creatorRef.showPropertyGrid = 'right';
    this.creatorRef.rightContainerActiveItem('toolbox');

```

### Specify your

* browser:chrome
* editor version:88.0.4324.150

**Comment by andrewtelnov** [comment]
@prashanthsridhar I could not reproduce this issue. Here is the [example](https://plnkr.co/edit/7ZKqFSK6U2DQWzHh).
Please provide us an example in plunker or Sandbox, so we can reproduce the issue.

Thank you,
Andrew

**Comment by prashanthsridhar** [comment]
@andrewtelnov This was because we were using an older version, resolved after update.
