### ISSUE TITLE
Implement items (choices, rows, text items) reordering via drag/drop for Creator V2

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#1109]
Since we already implemented items drag/drop functionality I think we can start to implement a general way of items reordering for all survey elements:
- [ ] select base question choices
- [ ] images of the image picker
- [ ] matrix rows
- [ ] multiple text items

Then all it will be implemented we need to do the same for the
- [ ] matrix columns
- [ ] items in multicolumn mode

It should be generalized approach with the touch devices support

**Comment by tsv2013** [comment]
It probably can be general helper/component wrapper that can be used for any survey elements (pages, questions) re-ordering

**Comment by dmitrykurmanov** [comment]
Closed in favor of #1145
