### ISSUE TITLE
Implement UI testing infrastructure for Creator V2

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#1110]
Right now we're having quite a big portion of the Creator V2 functionality. But UI part frequently becomes broken due to the intensive development process. We need to set up functional tests to ensure we're working. It should include testing pipeline for the every commit, functional tests and probably snapshot tests for creator components.

**Comment by gologames** [comment]
Were set up functional testing infrastructure for Creator V2 via following commits:
https://github.com/surveyjs/survey-creator/commit/3c90e2590893cf87fb1b76e421c0792ab0de00c8
https://github.com/surveyjs/survey-creator/commit/5af15839fc63cf46bf76179531d6b87feb661879
https://github.com/surveyjs/survey-creator/commit/52be872b9b7016bd3c45eb58224c1b3d7d4a2e29
https://github.com/surveyjs/survey-creator/commit/2fafefa091170e871f662bbb9689bfb223b7f039

**Comment by gologames** [comment]
Implemented testcafe commands in creator-knockout and creator-react via [this](https://github.com/surveyjs/survey-creator/commit/cb1a0ad97dc52e3fed440ef5aae291f2ac772203) and [this](https://github.com/surveyjs/survey-creator/commit/d9d0be6768feda46bad5d57f5984155f9be25439) commits
