### ISSUE TITLE
Bug on create a custom question (panel question) from toolbox

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-creator#1126]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?

When i add a panel question on the toolbox the event onQuestionAdded is not being triggered , and im getting 2 different behaviors when i drag the question or when i click it
1) When i drag it duplicates the name created from the original question, and no event is triggered
2) When i click on the element im getting the default behavior of new question added (its changing the name), and no event is triggered

### What is the expected behavior?

When i add a panel question on the toolbox the event onQuestionAdded must be triggered.
1) When i drag the question , change the name of the question and trigger the event onQuestionAdded
2) When i click on the element, change the name of the question and trigger the event onQuestionAdded

### How would you reproduce the current behavior (if this is a bug)?
1) Add a new panel question
2) Add any question inside of this panel
3) Add it to toolbox
4) And click or drag it, into your survey

### Specify your

* browser: n/a
* editor version: 1.8.37

**Comment by tsv2013** [comment]
>When i add a panel question on the toolbox the event onQuestionAdded must be triggered.
onQuestionAdded event is being triggered only if you add a question to the survey
You need to use the https://surveyjs.io/Documentation/Survey-Creator?id=surveycreator#onCustomElementAddedIntoToolbox or the https://surveyjs.io/Documentation/Survey-Creator?id=surveycreator#onCustomElementAddingIntoToolbox event if you want to track items added to toolbox

I've checked your scenario on our site https://surveyjs.io/create-survey and in both cases (adding from toolbox via drag or click) the panel name has been changed. As for the inner elements - then yes, their names are still the same. We'll discuss this behavior  with the team. @andrewtelnov

**Comment by jmar1998** [comment]
Hello guys @andrewtelnov @tsv2013 , any news about this issue??

**Comment by imbf98** [comment]
Hello guys ! Any news about this issue? i got the same behaviour on my environment ! 
Thanks @andrewtelnov @tsv2013

**Comment by andrewtelnov** [comment]
I have fixed it by the commit above.

Thank you,
Andrew
