### ISSUE TITLE
Checkbox selects multiple boxes if first or fourth box is checked. 

### ISSUE THREAD

**Issue by sjburwell** [surveyjs/survey-creator#1132]
### Are you requesting a feature, reporting a bug or ask a question?
Possible bug in "Test Survey", whereby multiple boxes are checked if one of a certain range of boxes

### What is the current behavior?
Currently, if I select either the first box or the 4th-Nth box(es), *all* 1 and 4-n boxes become checked.  

![image](https://user-images.githubusercontent.com/34345358/113517455-ac3ea200-9545-11eb-8853-0ade9d5b6bb0.png)

### What is the expected behavior?
Only the selected boxes should be checked.

![image](https://user-images.githubusercontent.com/34345358/113517526-17887400-9546-11eb-98bd-bc4f62eacc21.png)

### How would you reproduce the current behavior (if this is a bug)?
Use the "Survey Designer" and create more than the default 3 boxes. Select either one of the 1st or 4th, 5th, 6th, etc. box and observe the behavior. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@sjburwell The behavior is correct. We have a bug introduced in v1.8.39 that I have already fixed in v1.8.40, [Next value functionality stops working for choices, matrix dropdown rows and rates](https://github.com/surveyjs/survey-creator/issues/1131).
In your example you have several items with the same values. In fact the question value will be the same: ["item1"].
We will release the next version tomorrow-aftertomorrow and the issue will go away.

Thank you,
Andrew

**Comment by sjburwell** [comment]
The same thing happens when the items do not match (i.e., when not all are "item1", please see below), but as long as you have identified the issue and a bug fix is coming, I'm happy! Thank you. 

![image](https://user-images.githubusercontent.com/34345358/113631429-14b57e00-962f-11eb-8edf-519a97be14f0.png)

**Comment by tsv2013** [comment]
@sjburwell Could you share your survey JSON to reproduce the issue?

**Comment by sjburwell** [comment]
Now that I viewed the JSON I realized that while the TEXT for each item was different, the item's VALUE was identical across the different options it was multi-selecting. There is no issue - the code works as intended. Thank you for leading me towards the solution!
