### ISSUE TITLE
Error saving choices from web on classic mode (Modal Question Property Editor)

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-creator#1143]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

When i try to change any property from choices from web tab on modal question editor, i get an exception error

### What is the expected behavior?

Being able to save my question without problem

### How would you reproduce the current behavior (if this is a bug)?
a video explaining the situation
https://streamable.com/u90ci4

**Comment by andrewtelnov** [comment]
@jmar1998 I have fixed the issue.

Thank you,
Andrew
