### ISSUE TITLE
> ```js

### ISSUE THREAD

**Issue by kumbhagirishiva** [surveyjs/survey-creator#1147]
> ```js
> SurveyEditor.SurveyQuestionEditorDefinition.definition["checkbox@choices"] = {properties: ["text"] };
> ```

I tried this , but it not working to me, please can you share any live example

_Originally posted by @kumbhagirishiva in https://github.com/surveyjs/survey-creator/issues/429#issuecomment-824020033_

**Comment by tsv2013** [comment]
What task are you trying to solve?
