### ISSUE TITLE
Limit number of choices or itemValues

### ISSUE THREAD

**Issue by judith-ale** [surveyjs/survey-creator#1149]
### Are you requesting a feature, reporting a bug or ask a question?

Ask a question

### What is the current behavior?
(two questions)
1. Is there a way to limit the the number of itemValues or choices in a question?
I don't know if it works like `onQuestionAdded` and if there is something similar to `options.question.delete()` but for `onItemValueAdded`.

**`onQuestionAdded`**
![imagen](https://user-images.githubusercontent.com/62565005/115774395-2315d080-a377-11eb-903b-21799729e483.png)

I came with an idea but doesn't work properly:

**`onItemValueAdded`**
![imagen](https://user-images.githubusercontent.com/62565005/115774950-d7175b80-a377-11eb-813f-81806d91a3c0.png)

It seems like the new value is added before the function so `pop()` removes the choice before the one added, and even if I wait some time to pop the lastvalue with `setTimeout()` it only works if I add the value from this place:

![imagen](https://user-images.githubusercontent.com/62565005/115775801-eea31400-a378-11eb-93d2-b410f0fc377d.png)

But no from the propiety grid, because in the first one `options.itemValues` is an array with the choices (the objects) but for the array returned if I add a new choice on propiety grid is an array of the name of the choices, so that doesn't erase the object.

2. If there is a way, then how can I limit the number of choices based on the type of question? 
For example, the limit of options to add for checkbox questions is 20 and the limit of options to add for radiogroup questions is 10.

**Comment by andrewtelnov** [comment]
@judith-ale Unfortunately, we do not have this functionality. We are going to introduce it in V2.

Thank you,
Andrew

**Comment by judith-ale** [comment]
Thanks
