### ISSUE TITLE
Duplicate Question Name

### ISSUE THREAD

**Issue by joshuagoldmeier** [surveyjs/survey-creator#116]
### Are you requesting a feature, reporting a bug or ask a queation?
Reporting a bug

### What is the current behavior?
Whenever a name for a question is repeated for a different question later in the survey, only the results of one of the questions is stored in the Results JSON and consequentially all other results pertaining to other questions with the same name is lost.

### What is the expected behavior?
Either the user should be able to store unique results for question even when questions have the same name or there should be some data validation enforcing the user to assign unique names to each question

### How would you reproduce the current behavior (if this is a bug)?
Create a survey -> create two questions with the same name -> answer the survey -> notice data is lost

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@joshuagoldmeier I would not call it a bug or an unexpected behavior. 
There are two scenarios. For example, you want to ask your end-user to write their e-mail address, at the beginning or the survey and at the of survey. You may want:
a) Ask an end-user check their e-mail one more time
b) Ask them to provide alternative e-mail, if they have it.
In both cases you want to show the initially entered e-mail in the second input. However, in (a) you want to have one value in the result and in (b) two values.
It is logical have the same name "email" for the question in (a) and different name "alternativeemail" for (b). You may copy the data from "email" to "alternativeemail" on survey.onValueChanged event.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@joshuagoldmeier We have the valueName property now. If it is set, then the value is stored using this property and not name. It means that we may add validation on question/panel names.
It is in our TODO list now.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
question name validation has been added some times ago.
