### ISSUE TITLE
Creator v2 Release Date?

### ISSUE THREAD

**Issue by bernardworthy** [surveyjs/survey-creator#1163]
Great work with this library and the SurveyJS Library as a whole. We've been tracking the progress with the SurveyJS Creator re-design using React and wondering if you had a projected release date for that project?

**Comment by tsv2013** [comment]
We don't have the exact release date for Creator V2. We want to release a good, solid and stable product. We'll work on it as long as it will be required. But I can tell you right now that we're planning to release a beta version somewhere in the end of this May.

You can track the progress here - https://github.com/surveyjs/survey-creator/projects/3

**Comment by bernardworthy** [comment]
Thanks!
