### ISSUE TITLE
Possible to create a "custom widget" that extends an existing question type, but as a new question type?

### ISSUE THREAD

**Issue by scottadamsmith** [surveyjs/survey-creator#1164]
### Are you requesting a feature, reporting a bug or ask a question?

Ask a question.

### What is the expected behavior?

I was wondering if it is possible to "extend" an existing question type when creating a custom widget. For example, if I wanted to make a custom version of the radiogroup question type, without having to completely create a new custom widget. I'd like to get all the built-in behavior of the radiogroup in the creator, but customize a few aspects and register it as a new question type. I do not want to override radiogroup though, I want to retain the generic radiogroup question type. Do you know if this is possible?

**Comment by andrewtelnov** [comment]
@scottadamsmith It depends what you are going to do. You can use the default rendering and just correct the widget DOM after it renders. Another option is to use [component approach](https://surveyjs.io/Documentation/Survey-Creator?id=Build-Component-Questions).
There is another option that will come with Creator V2, but it depends on JavaScript framework you use, and V2 is not even in Beta yet.

Thank you,
Andrew

**Comment by scottadamsmith** [comment]
Thank you for the response. I will give the component API a try and see where that gets me.

**Comment by scottadamsmith** [comment]
This approach is looking promising. Do you know if there is a way to implement "Custom css" similar to what is documented here?

https://surveyjs.io/Examples/Library?id=survey-customcss&platform=jQuery&theme=bootstrap#content-js

For example, I have created a component that renders a single "rating" question type, but would like to add some bootstrap classes to render the rating items vertically. 

As an aside, if this issue is not the preferred venue for questions like this, please let me know and I'd be happy to pursue an answer via another mechanism. Thanks!

**Comment by andrewtelnov** [comment]
@scottadamsmith In this case you can simply add a property into existing "rating" question:
`Serializer.addProperty("rating", {name: "starStyles", choices: ["default", "bootstrap1", "bootstrap2"], category: "general"});`
Then using [survey.onQuestionAfterRender](https://surveyjs.io/Documentation/Library?id=surveymodel#onUpdateQuestionCssClasses) or [survey.onAfterRenderQuestionInput(]https://surveyjs.io/Documentation/Library?id=surveymodel#onAfterRenderQuestionInput) events update CSS classes or update DOM based on "starStyles" property value.

Thank you,
Andrew

**Comment by scottadamsmith** [comment]
So I was able to get the custom component to work (somewhat) in the creator, but I am struggling with the values not serializing now. I thought it might be related to them being the same as the default (for this element, we set rateMin/rateMax/rateValues explicitly and they cannot be changed), but even trying to change them in an onQuestionAdded callback does not seem to get them into the serialized JSON. Is it possible there is an alternative approach that needs to be used for custom components like this? I have tried the "onCreated" callback as well, but could not get that to work with either. If that ends up being the right option though, I'll have to understand how to tell the difference between when a question is newly added versus just an existing element that is just being rendered. 

Here is a codesandbox with my issue: https://codesandbox.io/s/stoic-cannon-chibc

If you add a "Likert Scale 7" element to the survey, and then look at the JSON editor, you will see that the rateMin/rateMax/rateValues are never present. Any help would be greatly appreciated.

**Comment by andrewtelnov** [comment]
@scottadamsmith Hm, Please review the [following example](https://surveyjs.io/Examples/Survey-Creator?id=modifysurveys), I would go with this approach, as I suggested early.
You will need to set your css classes instead of rendering an "info" button.

Thank you,
Andrew
