### ISSUE TITLE
Implement survey title/description/logo editor

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#1168]

**Comment by gologames** [comment]
Related commit https://github.com/surveyjs/survey-creator/commit/23b84acbab7b8a60e43daad6706b08f2a5fd70cf

**Comment by gologames** [comment]
The diagram of survey's title rendering pipeline in SurveyCreator Knockout designer tab:

![image](https://user-images.githubusercontent.com/30930391/118101876-c12e1100-b3e0-11eb-9ccd-c748d3f4dce0.png)


![Untitled Diagram](https://user-images.githubusercontent.com/30930391/118101752-99d74400-b3e0-11eb-8858-45b3cedb6a58.png)

**Comment by gologames** [comment]
Implemented with following behavior:

1) Before editing, survey title is empty, placeholder is visible
![image](https://user-images.githubusercontent.com/30930391/118250464-2f410980-b4af-11eb-8e6f-47dbd97f2d1d.png)

2) Click on survey title, placeholder is visible, caret is visible at the beggining
![image](https://user-images.githubusercontent.com/30930391/118250647-5ac3f400-b4af-11eb-9c5c-367e3f4f8f7a.png)

3) Type text, placeholder is hidden, text is visible, you can change caret position
![image](https://user-images.githubusercontent.com/30930391/118250703-69121000-b4af-11eb-9010-5a641418db70.png)

4) After editing, placeholder is hidden, text is visible
![image](https://user-images.githubusercontent.com/30930391/118250762-76c79580-b4af-11eb-8ba1-124bc753c047.png)

**Comment by gologames** [comment]
Question. Should we show page title/description editor for new page?

![image](https://user-images.githubusercontent.com/30930391/118794853-aa852f80-b8a2-11eb-8999-27fc319abcf9.png)

**Comment by gologames** [comment]
Resulted view

Placeholders:
![image](https://user-images.githubusercontent.com/30930391/120300714-d9ed6080-c2d4-11eb-9622-938069aeb46b.png)

Filled title and description:
![image](https://user-images.githubusercontent.com/30930391/120300632-c8a45400-c2d4-11eb-8070-0ca0e7a8c29f.png)

Chosen logo:
![image](https://user-images.githubusercontent.com/30930391/120300442-985cb580-c2d4-11eb-8d11-d48cf39e9747.png)
