### ISSUE TITLE
Cells editor setup action show modal window in incorrect position

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#1187]
Buttons "Cancel" and "Apply" renders out of the screen.
Question matrix, property editor "Cells".

**Comment by tsv2013** [comment]
Now it seems ok for me
![image](https://user-images.githubusercontent.com/3013415/123239995-96a79b80-d4e8-11eb-8d7c-038edadfa3d0.png)

Do I miss something?
