### ISSUE TITLE
Color picker does not respect default value

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#1198]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Add a custom property of type `color` with a default value.

### What is the expected behavior?
The color picker should show the default color, instead it always shows black (until the user picks a different color)

### How would you reproduce the current behavior (if this is a bug)?
Add a property to any question:
```js
{
    name: "hoverBorderColor",
    type: "color",
    default: "#0000FF"
},
```

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: N/A

### Specify your

* browser: brave (chrome)
* editor version: 1.8.47

**Comment by andrewtelnov** [comment]
@SamMousa I have just checked it works fine to me. Here is [the example](https://plnkr.co/edit/ZaHYz5lZmycQixqr).

Thank you,
Andrew

**Comment by SamMousa** [comment]
I'm sorry, maybe I was unclear.
I'm not talking about the colorpicker question type.

The issue appears when there is a custom question property of type color. 
![image](https://user-images.githubusercontent.com/547021/118493001-ee502b80-b720-11eb-9dcd-e39c04f1c9d3.png)

These properties are define like this:
```js
Survey.Serializer.addClass("test", [
                {
                    name: "borderColor",
                    type: "color",
                    default: "#FF0000"
                },
                {
                    name: "selectedBorderColor",
                    type: "color",
                    default: "#00FF00"
                },
                {
                    name: "hoverBorderColor",
                    type: "color",
                    default: "#0000FF"
                },
], null, "checkbox");
```

**Comment by andrewtelnov** [comment]
@SamMousa The following code will work.
`Survey.Serializer.addProperty("question", {name: "backColor:color", default: "#ff0000", category: "general"});`.
Here is [the example](https://plnkr.co/edit/ZaHYz5lZmycQixqr). 
I will check the the issue with addClass. Likely we create a new property and do not return the default value.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SamMousa Unfortunately, I can't fix the issue, since there is a code that has `null` object creator for some base absctract classes, but it has defined properties in these classes. There is no way to find out if these properties are custom and need to be defined or they are not.
Please use the following code:
```js
Survey.Serializer.addClass("test", [], null, "checkbox");
Survey.Serializer.addProperty("test", {
                    name: "borderColor",
                    type: "color",
                    default: "#FF0000"
                });

```
`Survey.Serializer.addProperty` - is a pure custom property and we define it on object creation.

Thank you,
Andrew
