### ISSUE TITLE
How to setup survey complete trigger in survey creator ?

### ISSUE THREAD

**Issue by naveenvignesh5** [surveyjs/survey-creator#1245]
### Are you requesting a feature, reporting a bug, or asking a question?
Question

### What is the current behavior?
There is no way to set up a complete trigger in the survey creator dashboard.

### What is the expected behavior?
Require a solution to set up a complete trigger for questions when creating the survey without manipulating the JSON definition.

This is the complete trigger demo mentioned on the official website- https://surveyjs.io/Examples/Library/?id=trigger-complete&platform=jQuery&theme=modern

But there is not way on how to set up the same during survey creation using the creator dashboard. If so kindly give me the instructions.

**Comment by tsv2013** [comment]
Probably this helps you
![image](https://user-images.githubusercontent.com/3013415/120200465-08176580-c22d-11eb-8260-476c0a8ff72c.png)

**Comment by naveenvignesh5** [comment]
@tsv2013 Thanks. This solved my issue.
