### ISSUE TITLE
V2: Should disable "Title Editor" for the ghost new page

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-creator#1281]
`svc-string-editor__controls` exists on hover at ghost new page

![Screenshot 2021-06-04 111233](https://user-images.githubusercontent.com/22315929/120769497-db619780-c525-11eb-9a73-9fadba7b4735.png)

**Comment by tsv2013** [comment]
We need to show page titles according design concept in order to make users understand the "ghost" (new) page on design surface

**Comment by andrewtelnov** [comment]
@dmitrykurmanov @tsv2013 We create a new page on changing title and description now.

Thank you,
Andrew
