### ISSUE TITLE
 Creator status code modified

### ISSUE THREAD

**Issue by jmlopezo** [surveyjs/survey-creator#1343]
### Are you requesting a feature, reporting a bug or ask a question?

Question:

How can you change the state of the creator when modifying the JSON via code?

I have tried with:

creator.JSON = {} and creator.changeText (JSON.stringify ({}))

and does not show that it was modified

### Specify your

* browser: Safari
* editor version: 1.8.51

**Comment by andrewtelnov** [comment]
@jmlopezo We reset modified state to unchanged on changing the creator JSON property. Commonly it uses on loading a survey definition or resetting the editing survey to initial start.
What do you want to do? 

Thank you,
Andrew

**Comment by jmlopezo** [comment]
@andrewtelnov, One of the features that I want to implement is reset button, and another is to import the json from a file.

**Comment by andrewtelnov** [comment]
@jmlopezo Please use the following code:
`creator.setModified();`

Thank you,
Andrew

**Comment by jmlopezo** [comment]
thanks @andrewtelnov, it worked!

**Comment by SamMousa** [comment]
I believe this can be closed. But there's a new issue related to it.

**Comment by tsv2013** [comment]
@SamMousa Thank you!
