### ISSUE TITLE
Don't understand question types

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#1365]
![image](https://user-images.githubusercontent.com/14936841/122536740-88133d00-d02d-11eb-9513-415b105ba947.png)

**Comment by OlgaLarina** [comment]
Question type should be display near "Convert to" button.
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=3449%3A36876
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=2693%3A74990
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=4341%3A39516

**Comment by tsv2013** [comment]
We added placeholders and write question type instead of "Convert to" text. Since closing.
