### ISSUE TITLE
Survey Preview: page selector don't display page title and don't updated after switch

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#1368]
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=601%3A17739
![image](https://user-images.githubusercontent.com/14936841/122552111-9158d580-d03e-11eb-8631-2d8616b583d1.png)

**Comment by gologames** [comment]
Current issue is related to [this issue](https://github.com/surveyjs/survey-creator/issues/1389). When set up new SurveyJSON then switching pages in test tab works fine

**Comment by gologames** [comment]
Page names shown by default instead page titles. You can change this behavior with [showObjectTitles property](https://github.com/surveyjs/survey-creator/blob/3b25c4a5b50bbecc6ed3b93c1d176d2989ee3eea/packages/survey-creator-core/src/creator-base.ts#L579) of creator

**Comment by gologames** [comment]
Issue is not reproducing after fix of [this issue](https://github.com/surveyjs/survey-creator/issues/1389), but I found [this new issue](https://github.com/surveyjs/survey-creator/issues/1427)
