### ISSUE TITLE
Matrix (multiple choice): Editors go beyond question borders if type is Boolean or Rating

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#1382]
![image](https://user-images.githubusercontent.com/14936841/122571755-b99ffe80-d055-11eb-8803-4ddc89632f57.png)
![image](https://user-images.githubusercontent.com/14936841/122571778-c3c1fd00-d055-11eb-82ea-4cf941689248.png)

**Comment by tsv2013** [comment]
We need to show horizontal scroll
