### ISSUE TITLE
Knockoutjs: New added columns in Matrix (multiple choice) & matrix (dynamic rows) are empty

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#1384]
![OfaBTWkDoW](https://user-images.githubusercontent.com/14936841/122575635-9e36f280-d059-11eb-91f6-53b608c9fbf0.gif)

**Comment by andrewtelnov** [comment]
The fix was done in library. v1 has the same issue. Unit test was added.

Thank you,
Andrew
