### ISSUE TITLE
React: Throw errors after page was removed in property grid

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#1393]
![8YFRl7pnJq](https://user-images.githubusercontent.com/14936841/122886244-77720800-d348-11eb-8846-61a56d75c838.gif)

**Comment by andrewtelnov** [comment]
@OlgaLarina Fixed by fixing [this issue](https://github.com/surveyjs/survey-library/issues/2998).

Thank you,
Andrew
