### ISSUE TITLE
React: Throw warning after a new item was added in collection editor of the Logic group

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#1394]
![WCbAKGpoWm](https://user-images.githubusercontent.com/14936841/122886679-d768ae80-d348-11eb-862f-f29375a1c997.gif)

**Comment by andrewtelnov** [comment]
@OlgaLarina I was not able to reproduce in the latest version. I have added a functional test.

Thank you,
Andrew
