### ISSUE TITLE
The direction of splitter is not working properly in right to left forms 

### ISSUE THREAD

**Issue by monaseyf** [surveyjs/survey-creator#1403]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by monaseyf** [comment]
in forms with right to left style, when I drag a splitter to the right hand side, it goes to the left.

**Comment by tsv2013** [comment]
Fix will be available in 1.8.54
