### ISSUE TITLE
Custom Property Editor re-render issue with HTML duplicating

### ISSUE THREAD

**Issue by dcods22** [surveyjs/survey-creator#1409]
### Are you requesting a feature, reporting a bug or asking a question?
Custom Property Editor does not trigger autosave

### What is the current behavior?
When changing the example provided for a custom property editor, the onValueUpdated method is never called and the creator does not trigger an autosave.  Also when I fetch the JSON with a custom property in it and pass it to the survey it no longer appears in the JSON editor tab and the value does not persist, but I know it is there when I pass it to the survey creator

### What is the expected behavior?
The Survey creator allows for the custom property to be passed to it, and changing any property triggers autosave

### How would you reproduce the current behavior (if this is a bug)?

Use a basic survey and the custom proprety renderer https://surveyjs.io/Examples/Survey-Creator/?id=custompropertyeditor&theme=bootstrap#content-result if you pull that example down and see it wont do an auto sacve and if you persist the custom property and pass it down it wont return back in the survey when passed to it

your_code_here

render: (editor, htmlElement) => {
    var input = document.createElement("input");
    input.className = "form-control svd_editor_control test";
    input.type = "text";
    input.maxLength = 5;
    input.style.width = "100%";
    htmlElement.appendChild(input);
    //@ts-ignore
    input.onchange = () => {

      editor.koValue(input.value);
    }
    //@ts-ignore
    editor.onValueUpdated = (newValue) => {
      input.value = editor.koValue() || "";
    }
    input.value = editor.koValue() || "";
  }

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.8.51

**Comment by andrewtelnov** [comment]
@dcods22 I have just tried it and it works fine. Here is [the example](https://plnkr.co/edit/EpJ9K0Tvhh4VFksy).
Please check the console logs.

**Comment by dcods22** [comment]
@andrewtelnov I was able to get it to render and update the JSON, but when I fetch the JSON from our backend service and set it as the JSON the editor does not have the value that is stored in the survey object in it so I cannot render the property again

**Comment by dcods22** [comment]
When i fetch the JSON and set it to the survey by doing `surveyCreator.text = survey;` it seems the custom properties are ignored and not in the JSON editor but I see them before setting them

**Comment by dcods22** [comment]
Oh I see now I need to add the proprety to the survey JSON object

**Comment by dcods22** [comment]
My custom property is an array of objects, which I made my renderer be an array of inputs which works properly, but I have an add button to add another input field. How do I get the component to refresh, if I manually call my render function when the input changes it renders multiple objects, but if I close and collapse the section in the property panel it renders again properly.  Is there a way to get the custom property renderer to refresh?

**Comment by dcods22** [comment]
@andrewtelnov Is there a way to force the custom property to rerender when a value is updated?
