### ISSUE TITLE
Survey Creator React Custom Adorner Doesnt work

### ISSUE THREAD

**Issue by dcods22** [surveyjs/survey-creator#1410]
### Are you requesting a feature, reporting a bug or ask a question?

Survey Creator React Custom Adorner Doesnt work
https://codesandbox.io/s/cool-chatterjee-pnruy 

### What is the current behavior?
On this example KO is not found and when i try the example without the KO options locally, things render twice 

### What is the expected behavior?
how to import KO into a react project or the location of those KO functions.  I am using Knockout for my other creator functions

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

https://codesandbox.io/s/cool-chatterjee-pnruy

* browser:
* editor version: 1.8.51

**Comment by andrewtelnov** [comment]
@dcods22 You have to include knockout into this example.
Here is [the correct example](https://codesandbox.io/s/bold-mcclintock-hvhzm).

Thank you,
Andrew

**Comment by dcods22** [comment]
@andrewtelnov it still renders twice for me, it seems to call after render twice is that expected?

**Comment by dcods22** [comment]
This is my survery creator component

`
import React, { useEffect, useLayoutEffect } from "react";
import { addReviewComments, removeReviewComments } from "./SurveyConfiguration";
import * as SurveyJSCreator from "survey-creator";
import * as SurveyKo from "survey-knockout";
import * as ko from "knockout";
import { useAuth } from "../../context/AuthContext";

const CommentsRenderer = {
  //@ts-ignore
  render: (editor, htmlElement) => {
    var input = document.createElement("input");
    input.className = "form-control svd_editor_control test";
    input.type = "text";
    input.maxLength = 5;
    input.style.width = "100%";
    htmlElement.appendChild(input);
    //@ts-ignore
    input.onchange = () => {

      editor.koValue(input.value);
    }
    //@ts-ignore
    editor.onValueUpdated = (newValue) => {
      input.value = editor.koValue() || "";
    }
    input.value = editor.koValue() || "";
  }
}

const questionStartWithNewLineAdorner = {
  //@ts-ignore
  getMarkerClass: function (model) {
    return "question_startWithNewLine";
  },
  //@ts-ignore
  getElementName: function (model) {
    return "mainRoot";
  },
  //@ts-ignore
  afterRender: function (elements, model, editor) {
    var decoration = document.createElement("div");
    // decoration.className = "svda-question-startWithNewLine";
    decoration.innerHTML = "<div>Test This Out</div>";
    console.log("t");
    elements[0].appendChild(decoration);
    ko.applyBindings({
      model: model,
      editor: editor
    }, decoration);
    ko
      .tasks
      .runEarly();
    editor.onAdornerRenderedCallback(model, "question-startWithNewLine", decoration);
  }
};

export interface SurveyCreatorProps {
  survey: string;
  setSurvey: (survey: string) => void;
  inReview?: boolean;
  setActiveTab?: (value: string) => void;
  editable?: boolean
}

const SurveyCreator: React.FC<SurveyCreatorProps> = ({
  survey,
  setSurvey,
  inReview = false,
  setActiveTab = () => {
    console.log("active");
  },
  editable = true,
}) => {
  const { isQuestionnaireAuthorAdvanced } = useAuth();
  const options = {
    questionTypes: [
      "text",
      "checkbox",
      "radiogroup",
      "dropdown",
      "multipletext",
      "boolean",
      "rating",
      "ranking",
      "matrix",
      "matrixdropdown",
      "matrixdynamic",
    ],
    allowControlSurveyTitleVisibility: false,
    showSurveyTitle: "never",
    isAutoSave: true,
    showState: true,
    showJSONEditorTab: true,
    showDesignerTab: true,
  };
  const surveyCreator: SurveyJSCreator.SurveyCreator = new SurveyJSCreator.SurveyCreator(null, options);

  SurveyJSCreator.SurveyPropertyEditorFactory.registerCustomEditor("comments", CommentsRenderer)

  SurveyJSCreator.registerAdorner("review-comments", questionStartWithNewLineAdorner);

  let propertyStopList = [
    "requiredIf",
    "titleLocation",
    "descriptionLocation",
    "bindings",
    "defaultValueExpression",
    "columnsVisibleIf",
    "rowsVisibleIf",
    "hideIfChoicesEmpty",
    "choicesVisibleIf",
    "choicesEnableIf",
    "calculatedValues",
    "triggers",
    "focusFirstQuestionAutomatic",
    "focusOnFirstError",
    "locale",
    "completeText",
    "nextPageText",
    "prevPageText",
    "isSinglePage",
    "showTitle",
    "showCompletedPage",
    "checkErrorsMode",
    "goToNextPageAutomatic",
    "showPageNumbers",
    "showPageTitles",
    "textUpdateMode",
    "sendResultOnPageNext",
    "storeOthersAsComment",
    "showQuestionNumbers",
    "questionDescriptionLocation",
    "questionTitlePattern",
    "questionDescriptionLocation",
    "questionErrorLocation",
    "questionsOrder",
    "questionDescriptionLocation",
    "questionTitleLocation",
    "questionTitleTemplate",
    "maxTextLength",
    "maxOthersLength",
    "questionStartIndex",
    "questionRequiredSymbol",
    "pagePrevText",
    "pageNextText",
    "previewText",
    "editText",
    "startText",
    "startSurveyText",
    "showNavigationButtons",
    "showPrevButton",
    "firstPageIsStarted",
    "goNextPageAutomatic",
    "progressBarType",
    "showProgressBar",
    "requiredText",
  ];

  if( !isQuestionnaireAuthorAdvanced ) {
    propertyStopList = [...propertyStopList, "isRequired"];
  }

  //Hide properties contained in the black list, show all other properties
  surveyCreator.onShowingProperty.add(function(sender, options) {
    options.canShow = propertyStopList.indexOf(options.property.name) == -1;
  });

  const saveMySurvey = () => {
    if (surveyCreator?.text) {
      setSurvey(surveyCreator?.text);
    }
  };

  useEffect(() => {
    if (!!surveyCreator) {
      surveyCreator.text = survey;
    }
  }, [survey]);

  //@ts-ignore
  const TabChanged = (sender, options) => {
    setActiveTab(options.tabName);
  };

  //not sure if this works in preview mode
  const goToFirstPage = () => {
    SurveyKo.SurveyModel.prototype.currentPageNo = 1;
  };

  const goToLastPage = () => {
    SurveyKo.SurveyModel.prototype.currentPageNo = SurveyKo.SurveyModel.prototype.pageCount;
  };

  useEffect(() => {
    setActiveTab("designer");
  }, []);

  const renderSurvey = (editable: boolean) => {
    surveyCreator.toolbarItems.splice(3, 1);
    surveyCreator.saveSurveyFunc = saveMySurvey;
    surveyCreator.onActiveTabChanged.add(TabChanged);
    surveyCreator.showDesignerTab = editable;
    surveyCreator.render("surveyCreatorContainer");
  }

  useLayoutEffect(() => {
    surveyCreator.toolbarItems.splice(3, 1);
    surveyCreator.saveSurveyFunc = saveMySurvey;
    surveyCreator.onActiveTabChanged.add(TabChanged);
    surveyCreator.showDesignerTab = editable;
    surveyCreator.render("surveyCreatorContainer");
  }, []);

  useEffect(() => {
    if( editable !== surveyCreator.showDesignerTab ) {
      renderSurvey(editable);
    }
  }, [editable]);

  useEffect(() => {
    if (inReview) {
      addReviewComments();
    } else {
      removeReviewComments();
    }
  }, [inReview]);

  return (
    <div>
      <div id="surveyCreatorContainer" />
    </div>
  );
};

export default SurveyCreator;

`

**Comment by dcods22** [comment]
I was able to get my adorner to render proprely, but it seems when I move questions around it renders the element again so it appears twice is there something I can do to prevent this from happening?

**Comment by dcods22** [comment]
I was able to get it not render twice by checking the element for an existing class name and if it contains it to then not add the HTML
