### ISSUE TITLE
Unable to change view in V2 using makeNewViewActive

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1444]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug.

### What is the current behavior?
On changing view using makeNewViewActive creates an error.

### What is the expected behavior?
The view should be changed successfully.

### How would you reproduce the current behavior (if this is a bug)?
Providing the plunker example.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  https://plnkr.co/edit/evwbarOLzLDB2PM7

Test code

```
var changeView = function(view) { creator.makeNewViewActive(view) }

```

### Specify your

* browser: chrome 91
* editor version: 1.8.53-alpha.1

#### Before-
![image](https://user-images.githubusercontent.com/37444378/124073822-2d7fd500-da60-11eb-9ae9-a711212eab79.png)

#### After clicking external test button-
![image](https://user-images.githubusercontent.com/37444378/124073985-6f108000-da60-11eb-80b4-b610ffa39b05.png)
![image](https://user-images.githubusercontent.com/37444378/124074025-80f22300-da60-11eb-95c1-c589f305ffe1.png)

**Comment by andrewtelnov** [comment]
@vikkrantxx7 You have to do it in react way.
Here is [the workign example](https://plnkr.co/edit/BaGb7vE8BE6QiWqo).

**Comment by vikkrantxx7** [comment]
This is now working fine.
