### ISSUE TITLE
JSON tab is hidden in fullscreen CreatorV2 

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-creator#1446]
![image](https://user-images.githubusercontent.com/30930391/124092003-12f92c00-da5f-11eb-8f36-4f5eb4a927d2.png)

Related functional tests failed:
https://dev.azure.com/SurveyJS/SurveyJS%20Integration%20Tests/_build/results?buildId=25414&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=572d5538-c966-539a-02ce-1a3031dff36d

![image](https://user-images.githubusercontent.com/30930391/124092081-260bfc00-da5f-11eb-8f1d-5ff2aa2fcfd0.png)

**Comment by dk981234** [comment]
Fixed via https://github.com/surveyjs/survey-creator/commit/90c2990168e197d220ae0994a5b8b256c728885c
