### ISSUE TITLE
When custom saveSurveyFunc fails to save an exception occurs

### ISSUE THREAD

**Issue by snerte** [surveyjs/survey-creator#1447]
### Are you requesting a feature, reporting a bug or ask a question?
I am reporting a bug.

### What is the current behavior?
When a custom method is used to save a survey, and that method reports to the callback the save has failed, an error is shown in console and the saving loader persists.

### What is the expected behavior?
A notification is shown and loader doesn't persist

### How would you reproduce the current behavior (if this is a bug)?
https://plnkr.co/edit/UaU5wJydANLp2KIu
Click save in above example

### Workaround
Disabling the error when save fails.

```js
            var options = {
                showErrorOnFailedSave: false
            };

            var creator = new SurveyCreator.SurveyCreator("creatorElement", options);
```

**Comment by andrewtelnov** [comment]
@snerte I have fixed the issue by the commit above. We will include the fix into [v1.8.55](https://surveyjs.io/WhatsNew#v1.8.55).

Thank you,
Andrew
