### ISSUE TITLE
Page list in test tab doesn't update after changes in survey pages visibility

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-creator#1455]
SurveyJSON to reproduces:

```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1",
     "isRequired": true
    }
   ]
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "text",
     "name": "question2",
     "visibleIf": "{question1} = 'a'"
    }
   ]
  },
  {
   "name": "page3",
   "elements": [
    {
     "type": "text",
     "name": "question3"
    }
   ]
  },
  {
   "name": "page4",
   "elements": [
    {
     "type": "text",
     "name": "question4",
     "visibleIf": "{question1} = 'a'"
    }
   ]
  }
 ]
}
```

1) Set JSON
2) Open test tab
3) Type `a` to first question
4) ???
5) Visibility of second question hadn't changed in page list selelctor

![image](https://user-images.githubusercontent.com/30930391/124158617-cfc0ac80-daa2-11eb-89ca-5a15b1536212.png)

**Comment by andrewtelnov** [comment]
@gologames It has been fixed. Invsible pages now disable like in V1. There was a bug in V1 that doesn't disabled invisible pages. It was introduced after moving to actions. It is fixed as well.

Andrew
