### ISSUE TITLE
Console Error in Creator React V2 when opening designer Page and collapsing General Section in property Grid

### ISSUE THREAD

**Issue by AbhishekKS** [surveyjs/survey-creator#1483]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a Bug

### What is the current behavior?

When I open the Creator Designer Page in React V2 version the first time without any pages and questions and then collapse the General section in the property grid, I see an error in console.

### What is the expected behavior?
No error in console.

### How would you reproduce the current behavior (if this is a bug)?
1) Open Designer page for React V2 on dev-test website without and pages and questions.
2) Collapse the General section in the property grid **OR** Drap and drop a question on the page.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser: Chrome 91.0.4472.124 version
* editor version:
<img width="862" alt="ConsoleError" src="https://user-images.githubusercontent.com/13827554/125251569-16b96800-e315-11eb-92fb-19fd8865861b.PNG">

**Comment by andrewtelnov** [comment]
@AbhishekKS I am changing this code, re-writting it a little bit. It should be fine with a new release, but I will recheck it today. I will be back.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@AbhishekKS It works locally. We have an issue with an Azure pipeline that updates surveyjstests. We are working on fixing it. However, I am pretty sure that issue has been fixed.
I will check it when website will be updated to the latest version.

Thank you,
Andrew

**Comment by AbhishekKS** [comment]
Thanks Andrew!! Yes, it seems to work fine with the latest npm release version (1.8.55). It's just that I see this on your dev website.

Thanks
Abhishek

**Comment by andrewtelnov** [comment]
@AbhishekKS It is quite opposite. It works in v1.8.55, but I have broke it on Friday in devs builds. This site gets the latest devs builds. It works now again. You can check the link. We use this website for e2e testing as well. Our e2e tests were broken for couple days and we have fixed it today.

Thank you,
Andrew
