### ISSUE TITLE
Duplicate and Delete Page options on newly added pages do not appear unless we switch tabs: v2

### ISSUE THREAD

**Issue by AbhishekKS** [surveyjs/survey-creator#1484]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a Bug

### What is the current behavior?

When I start adding new pages with questions by clicking on the '**Add Question**' button, **Delete** and **Duplicate** options on the top right corner on each page don't appear unless I switch tabs.

### What is the expected behavior?
Delete and Duplicate options should appear on each page as soon as we click on the '**Add Question**' button which adds a page along with.

### How would you reproduce the current behavior (if this is a bug)?
1) Open Designer page for React V2 on dev-test website without and pages and questions.
2) Try adding few pages by clicking on the 'Add Question' button.
3) 'Delete' and 'Duplicate' page options do not appear on new pages unless I switch tabs and come back again.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser: Chrome 91.0.4472.124 version
* editor version:
![image](https://user-images.githubusercontent.com/13827554/125255533-2b97fa80-e319-11eb-8775-dc8e6c15ef7f.png)

**Comment by andrewtelnov** [comment]
@AbhishekKS Yes, I was able to reproduce the issue.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@AbhishekKS I have fixed it by the commit above.

Thank you,
Andrew
