### ISSUE TITLE
Triggers

### ISSUE THREAD

**Issue by MohabElgammal** [surveyjs/survey-creator#149]
### Are you requesting a feature, reporting a bug or ask a queation?
Feature

### What is the current behavior?

when adding a trigger on a question,there is no indication that shows there is a trigger on a question .  

### What is the expected behavior?

show an indication that there is a trigger on that question.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:chrome latest version
* editor version:editor 0.12.23

**Comment by andrewtelnov** [comment]
@MohabElgammal We have Survey Logic tab in the Survey Creator and this is what you needed.

Thank you,
Andrew
