### ISSUE TITLE
React Creator V2 - Vertical scrollbars for Toolbox, Property Panel and Page Layout Panel appear differently in Firefox

### ISSUE THREAD

**Issue by AbhishekKS** [surveyjs/survey-creator#1491]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?
For React Creator V2 - Vertical scrollbars for Toolbox, Property Panel, and Page Layout Panel appear differently in Firefox. Seems to appear fine in Chrome and Edge browsers.

### What is the expected behavior?
Vertical Scrollbars should be in sync across supported browsers -Chrome, Firefox, Edge, etc.

### How would you reproduce the current behavior (if this is a bug)?
Open test website in Firefox (Version 89.*.*). Scrollbars appear differently in comparison to Chrome and Edge.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser: Firefox 89.0.2 (64-bit)
* editor version:

![image](https://user-images.githubusercontent.com/13827554/125438110-6406f539-8b73-4d00-a522-996c86b78210.png)

**Comment by dk981234** [comment]
Hello, 
We've fixed the issue via this [pull request](https://github.com/surveyjs/survey-creator/pull/1805).

Thanks,
Dmitry
SurveyJS Team
