### ISSUE TITLE
Non unique entries possible through fast entry when itemValues are set unique in V2.

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1497]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug.

### What is the current behavior?

Able to enter non-unique values via fast entry even if itemValues are set to be unique.

### What is the expected behavior?

Non-unique values should not be allowed.

### How would you reproduce the current behavior (if this is a bug)?

Providing the plunker example.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/YfIJUyLvXcCII9Fk

Test code

```
Survey.Serializer.findProperty('itemValue', 'value').isUnique = true

```

### Specify your

* browser: chrome 91
* editor version: 1.8.55-alpha.1

![image](https://user-images.githubusercontent.com/37444378/125508045-d6656c6f-436a-4965-8b18-6132ae469afe.png)

![image](https://user-images.githubusercontent.com/37444378/125508082-301989e1-3c42-48f1-bd60-00e627b5578b.png)

**Comment by andrewtelnov** [comment]
@vikkrantxx7 Yes, it is in our TODO list. I will pick-up this item.

Thank you,
Andrew

**Comment by ST-1580** [comment]
@vikkrantxx7 We've fixed this issue.

Thank you, 
Yaroslav
