### ISSUE TITLE
Can we add tooltip for survey questions?

### ISSUE THREAD

**Issue by RupaliPatwa** [surveyjs/survey-creator#150]
Can we add tooltip for survey questions?
If yes where can we add that in json?

**Comment by andrewtelnov** [comment]
@RupaliPatwa Where do you want to show this tooltip? on question.title?
PS: We have added a description property into the question

Thank you,
Andrew

**Comment by RupaliPatwa** [comment]
I was not able to see tooltip coming up with description property.
I am using version  - survey-react@^0.12.15

following is json
 type: "checkbox",
  name: "taxonomyPersonalData",
  title: "What car are you driving?",
description : "What car are you driving? ",
...

**Comment by andrewtelnov** [comment]
@RupaliPatwa There is no tooltip property. I have just asked the question. Where do you want to show the tooltip, over the question title?

Thank you,
Andrew

**Comment by RupaliPatwa** [comment]
Hi,
I want to show tooltips for checkbox text.I want to show additional information about each text of choices element.So How do I do that? If I do mouseover on checkbox text tooltip should appear with additional information.


Following is json
type: "checkbox",
name: "data",
title: "What car are you driving?",
description : "What car are you driving? ",
choices: [
                        {
                            value: "A",
                            text: "A"
                        },
                        {
                            value: "B",
                            text: "B"
                        },

**Comment by andrewtelnov** [comment]
@RupaliPatwa Do you want to show the same tooltip on all choices or different a tooltip for every choice?

Thank you,
Andrew

**Comment by RupaliPatwa** [comment]
No not same tooltip. I have 4 checkbox values/text in choices array and I want to set separate tooltip for each text. 
This should be generic. There are many components like matrix, checkbox where choices ,rows array is used. So I  should be able to set different tooltips where ever required.

**Comment by ashygk** [comment]
Is the solution available for adding tool tips to survey questions? 
I would like to add on each column for matrix.

**Comment by cliewdevelop** [comment]
Hi @andrewtelnov!
Echoing same need, if it helps you prioritize 
But for now, description property should work. (although a little cluttered if description is long)

**Comment by sandesh-dsouza** [comment]
Hi @andrewtelnov 
First of all a big cheers for such a great tool. Tooltip will be of big help in the survey we are building. Please see if this can be prioritized?

**Comment by andrewtelnov** [comment]
@cliewdevelop @sandesh-dsouza @RupaliPatwa We have added this functionality. Here is [the example](https://plnkr.co/edit/pyXH5wUSylJ391JYONq5?p=preview)

**Comment by mimperiali-mega** [comment]
@andrewtelnov I took a look at the example but I'm confused. The original request was being able to define tooltips on every possible answer of a given question. I'm adding a quick mock-up to provide a better example: basically when the user hovers on one of the possible answers, a tooltip should be displayed to provide additional info.
When I take a look at the provided example, I see instead a functionality which allows to define tooltips on question types instead... Am I missing something?

![image](https://user-images.githubusercontent.com/59057609/136218861-a044bc32-70ad-46ed-bbb7-69011c9c06e3.png)
![image](https://user-images.githubusercontent.com/59057609/136219241-63945407-f6ff-471e-a244-e214bd1db747.png)
