### ISSUE TITLE
Is it possible to change the "related question types" on the actions adorners?

### ISSUE THREAD

**Issue by fredrodriguesof** [surveyjs/survey-creator#1504]
### Are you requesting a feature, reporting a bug or ask a question?
Ask a question.

### What is the current behavior?
Today in question actions adorners a dropdown is displayed showing the types that I can change to, is it possible to change this list of related types, deleting some items and adding others? If yes how do I change it?

![relatedTypes](https://user-images.githubusercontent.com/14821887/125606407-acfcbbee-f6b0-46a2-a5f3-ecba066855ec.png)

**Comment by tsv2013** [comment]
I think you can patch the `SurveyCreator.QuestionConverter.convertInfo` static object containing compatible types.

**Comment by fredrodriguesof** [comment]
> I think you can patch the `SurveyCreator.QuestionConverter.convertInfo` static object containing compatible types.

Perfect, that's exactly what I needed!
