### ISSUE TITLE
Progress Bar does not work/appear correctly on Designer Page in Creator V2 React version

### ISSUE THREAD

**Issue by AbhishekKS** [surveyjs/survey-creator#1507]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?

Progress Bar does not work/appear correctly on Designer Page in Creator V2 React version!! Seems to work fine in the Knockout V2 version.

### What is the expected behavior?

The behavior of the Show progress bar in React V2 should be similar to that in the Knockout V2 version.

### How would you reproduce the current behavior (if this is a bug)?
1) On the designer page, select Show Progress Bar as "**top**" under the Navigation section in the properties grid.
2) Add few pages with questions.
3) Check the behavior of how the progress bar appears in react vs knockout. Screenshot attached for reference.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  1) Knockout V2 Version URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=KnockoutjsV2&theme=modern
2) React V2 version URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser: Chrome 91
* editor version: 

 **In knockout V2:**
<img width="950" alt="KnockoutV2" src="https://user-images.githubusercontent.com/13827554/125672594-0c9112e5-f4e3-45ac-a03e-76dc7bf1e5c4.PNG">

**In React V2:**

<img width="960" alt="ReactV2" src="https://user-images.githubusercontent.com/13827554/125672611-9845987b-2da2-4a80-8d9a-946119c16a54.PNG">
1.8.56

**Comment by AbhishekKS** [comment]
Also see a warning in the browser console, as I select a value for 'Show Progress Bar' in the property grid.

![image](https://user-images.githubusercontent.com/13827554/125673722-98be4b0d-fb0b-433a-aab9-f9c3cec095ad.png)

**Comment by andrewtelnov** [comment]
@AbhishekKS I was able to reproduce the issue. We will work on the fix.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@AbhishekKS I have fixed it by the commit above.

Thank you,
Andrew

**Comment by AbhishekKS** [comment]
Hi Andrew,
Just wanted to bring to your notice as I see this bug marked as fixed and closed. I checked on your dev env, and the fix looks good in React V2, but still, the progress bar does not grow or shrinks on different page selections on the designer page. Once I switch the tab it works fine. It works fine in the Knockout V2 version though.

Please note that I'm not pressing here to look at it on an urgent basis as such. I somewhat got misunderstood earlier, so you can prioritize and take a look at your convenience as it's a small issue for us. I just wanted to bring this to your notice.

Thanks
Abhishek

**Comment by andrewtelnov** [comment]
@AbhishekKS Got it. Indeed, we do not react on currentPage property. I have added the fix.
It is fine to report bugs. We appreciate it. It let us make a product better. It is correct to mention that it is important for you.
My previous post was about priorities we have in our work and that we can't make everything at once and we have to delay some stuff to work on other functionality.

This issue is fresh to me and the fix took about 10 minutes, since I know how and where to chage the code.

Thank you,
Andrew
