### ISSUE TITLE
Empty panel dynamic does not allow dropping questions from the Toolbox

### ISSUE THREAD

**Issue by JeffKulon** [surveyjs/survey-creator#1508]
Issue #1002 resolved a problem with adding question to an empty panel, but a similar issue exists for Panel Dynamic 

### What is the current behavior?
After adding a Panel Dynamic to a page, there is no text which reads "Please drop a question here from the toolbox", and it is not possible to drop Toolbox items into the panel dynamic.

Similarly, when a Panel Dynamic containing elements loads, and all of those elements are removed, there is no "Please drop a question here from the toolbox", and the Panel Dynamic no longer accepts drops from the toolbox.

### What is the expected behavior?
An empty panel dynamic should render the "Please drop a question here from the toolbox" text, and allow Toolbox items to be added.

### How would you reproduce the current behavior (if this is a bug)?
The current behavior is currently reproducible on using the Surveyjs.io  SurveyCreator demo.
1. Start with a blank page
2. Drag and drop a Panel Dynamic to the page
3. Note there is no "Please drop a question here from the toolbox" text within the panel dynamic
4. Attempt to drag and drop any Toolbox item into the Panel Dynamic.
5. This will not be possible.

### Specify your

* browser:  Firefox v 89,  Chrome v 91
* editor version: v 1.8.55  ( just tested with v1.8.56 and the issue remains )

**Comment by andrewtelnov** [comment]
@JeffKulon Thank you for reporting it. We will take a look.

Andrew

**Comment by dmitrykurmanov** [comment]
Fixed via the https://github.com/surveyjs/survey-library/commit/8cb81aa8a3cc5de1c6e160d81c19829872439a63

**Comment by JeffKulon** [comment]
Thanks, everyone, for the prompt attention to this.

**Comment by andrewtelnov** [comment]
@JeffKulon You are very welcome!

Andrew

**Comment by JeffKulon** [comment]
Can it be estimated when this fix might be released?  If not soon, is there a preview / release-candidate we could use for testing our application?

**Comment by andrewtelnov** [comment]
@JeffKulon 
We will likely release today. However, we can delay on one day and release tomorrow.
We make a new release every week, commonly Tuesday. You can take a look at our [Whats new page](https://surveyjs.io/WhatsNew).  

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@JeffKulon FYI: We have released v1.8.57.

Thank you,
Andrew
