### ISSUE TITLE
survey creator data/question to be populated dynamically to surveys froms

### ISSUE THREAD

**Issue by abdilatifbashir** [surveyjs/survey-creator#1509]
### Are you requesting a feature, reporting a bug or ask a question?
I ask Question
How can  I can populate,the survey-creator questions to my surveys 
dynamcally without copying Json manually
` <Survey.Survey 
        json = {json}
        onComplete = {(data) => console.log(data.valuesHash)}
       }
        />
`
currently am copying and pasting Json format of questions to my react app from survey-creator .Is there away i can populate 
questions from survey-creator to my surveys dynamically without copying pasting of json data.

### What is the current behavior?
currently am copying and pasting Json format of questions to my react app from survey-creator

### What is the expected behavior?
can populate 
questions from survey-creator to my surveys dynamically without copying pasting of json data.

### How would you reproduce the current behavior (if this is a bug)?
I will get hookup with codebase and check those forms that create surveys on surveys-creator

#### Provide the test code and the tested page URL (if applicable)
Url of what i s was trying https://github.com/abdilatifbashir/msurveyjs

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:chrome
* editor version:

**Comment by andrewtelnov** [comment]
@abdilatifbashir I am not sure I understand you correctly.
You can take a look at [this examples](https://surveyjs.io/Examples/Service) and read [this document](https://surveyjs.io/Documentation?id=Integration-with-Backend).

Thank you,
Andrew

**Comment by abdilatifbashir** [comment]
@andrewtelnov  thanks for the quick response .i have setup react app ,added survey-creator and survey library .my issue connected the survey creator to survey library unless i do manual json pasting .what i mean is data flow between survey-creator[https://github.com/surveyjs/survey-creator] and surveys itself[https://github.com/surveyjs/survey-library].

**Comment by abdilatifbashir** [comment]
@andrewtelnov  is there any github repo that implemented something like this,https://surveyjs-nodejs.herokuapp.com/ with reactjs ?
Thanks

**Comment by andrewtelnov** [comment]
@abdilatifbashir We do not have it, but it is a pretty basic functionality. You need to get the data from your database based on id of your survey JSON. This task is not even related to SurveyJS libraries, but rather to react and working with databases. I believe you can google this question.

Thank you,
Andrew

**Comment by tsv2013** [comment]
You can check this repo - https://github.com/tsv2013/surveyjs-django
But it uses Python backend

**Comment by abdilatifbashir** [comment]
@andrewtelnov  @tsv2013  in surrvey creator can it support nexted questions ,where i have question inside another one?.Thanks

**Comment by andrewtelnov** [comment]
@abdilatifbashir Are you talking about a [Panel](https://surveyjs.io/Examples/Library?id=questiontype-panel)? 

Thank you,
Andrew

**Comment by abdilatifbashir** [comment]
@andrewtelnov in the current survey creator i did't nested surveys where one question is inside another question.A question depends on other one ....nesting.

**Comment by andrewtelnov** [comment]
Sorry, I am not sure I am follow you.
Are you talking about [components](https://surveyjs.io/Documentation/Survey-Creator?id=Build-Component-Questions)?

Thank you,
Andrew

**Comment by abdilatifbashir** [comment]
![creator](https://user-images.githubusercontent.com/32511513/126122615-8d21af0d-5332-4de9-818d-a3bcedef01e5.png)
am talking of survey designer ,is there a way i can next question ,question within a question? @andrewtelnov 
Thanks.

**Comment by abdilatifbashir** [comment]
@andrewtelnov sorry for many question i was doin research on the surveyjs library and builder before we implement into our systems.Here is where i am stucked to get an answer :Does the survey-creator allow to create nested questions where i have one question inside the other one.

**Comment by andrewtelnov** [comment]
@abdilatifbashir [Components](https://surveyjs.io/Examples/Survey-Creator?id=component-fullname) and panels do what you need.

Thank you,
Andrew

**Comment by abdilatifbashir** [comment]
@andrewtelnov do you guys have slack community that i can join ?

**Comment by abdilatifbashir** [comment]
@andrewtelnov @SamMousa @andrewtelnov @mkopinsky `{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1",
     "title": "where you live"
    },
    {
     "type": "radiogroup",
     "name": "question3",
     "title": "how can you rate ajua services",
     "choices": [
      {
       "value": "item1",
       "text": "janja"
      },
      {
       "value": "item2",
       "text": "msurvey"
      }
     ]
    }
   ],
   "title": "cust details"
  }
 ]
}`  survey creator defination i am trying to post to relational db [mysql] ,how can i json non relational document can be established on relational db ?
