### ISSUE TITLE
Hiding hasOther and hasNone doesn't hide them in question for V2

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1520]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug.

### What is the current behavior?

Even after hiding hasOther and hasNone they still show up in question and aren't visible in the property panel.

### What is the expected behavior?

They should be invisible.

### How would you reproduce the current behavior (if this is a bug)?

Providing the plunker example.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  https://plnkr.co/edit/EbjLOdgm5jr4YAfm

Test code

```
Survey.Serializer.findProperty('radiogroup', 'hasOther').visible = false
Survey.Serializer.findProperty('radiogroup', 'hasNone').visible = false

```

### Specify your

* browser: chrome 91
* editor version: 1.8.56-alpha.1

![image](https://user-images.githubusercontent.com/37444378/126021625-64614623-9f94-4607-9fe3-f3dc879e7ce5.png)

![image](https://user-images.githubusercontent.com/37444378/126021632-1576f833-4a9b-4dc5-a8e1-9cefd6ffc853.png)

**Comment by andrewtelnov** [comment]
@vikkrantxx7 We render them in absolutely different way as we do in the first version. I have fixed the issue in the library. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/3100).

Thank you,
Andrew
