### ISSUE TITLE
When showSimulatorInTestSurveyTab is false then the devices selector in Test Survey tab is disabled instead of hidden in creator V2

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1524]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug.

### What is the current behavior?

When showSimulatorInTestSurveyTab is false then the devices selector in the Test Survey tab is disabled instead of hidden.

### What is the expected behavior?

The devices selector in the Test Survey tab should be hidden.

### How would you reproduce the current behavior (if this is a bug)?

Providing the plunker example.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/7YnxjeCGY9SBhHUM

Test code

```
let options = {
    showSimulatorInTestSurveyTab: false
};
var creator = new SurveyCreator.SurveyCreator(options);

```

### Specify your

* browser:  chrome 91
* editor version: 1.8.56-alpha.1

![image](https://user-images.githubusercontent.com/37444378/126045833-5a50a828-d180-4695-9a88-c89e20248b97.png)

**Comment by andrewtelnov** [comment]
@vikkrantxx7 I have fixed it by the commit above.

Thank you,
Andrew
