### ISSUE TITLE
When the question is marked as collapsed then the expand/collapse icon button is disabled in the Test Survey tab in creator V2.

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1525]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug.

### What is the current behavior?

When the question is marked as collapsed then the expand/collapse icon button is disabled in the Test Survey tab.
The same thing happens in Translation Tab.

### What is the expected behavior?

The icon button should expand/collapse the section.

### How would you reproduce the current behavior (if this is a bug)?

Providing the plunker example.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  https://plnkr.co/edit/7YnxjeCGY9SBhHUM

Test code

```
No Code is required. Just make a question collapsible.

```

### Specify your

* browser: chrome 91
* editor version: 1.8.56-alpha.1

![image](https://user-images.githubusercontent.com/37444378/126045956-1824a6d0-90ab-4861-92d7-07f88dc9e153.png)

**Comment by andrewtelnov** [comment]
@vikkrantxx7 It is an issue in the current version of the library. We will discuss it. You can click on any part of question1 title, including this icon and the content will be collapsed/expanded. We disabled it to remove tabstop focus.
We are going to add tabOrder or disableTabStop property into action and enabled the action again.
I will be back.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@vikkrantxx7 I have introduced [disableTabStop property in Action](https://github.com/surveyjs/survey-library/issues/3102) and make the  expand/collapse action enabled but with disableTabStop set to true.

Thank you,
Andrew

**Comment by vikkrantxx7** [comment]
Thanks @andrewtelnov
