### ISSUE TITLE
Make it possible to override Creator V2 toolbox/property grid with custom components

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#1531]
This will allow to override default creator components and add custom behavior (e.g. collapse/expand)
[Here is the plunker example for React to override Toolbox and Property Pane react components](https://plnkr.co/edit/ucDhZuC7HeXNQbOV?preview).

**Comment by tsv2013** [comment]
Sample toolbox wrapper code for survey-creator-react:
``JS
class CustomToolboxWrapper extends React.Component {
    constructor(props) {
        super(props);
        this.state = { collapsed: false }
    }
    toggle() {
        this.setState({ collapsed: !this.state.collapsed });
    }
    render() {
        return <div style={{position: "relative"}}>
            <div
                style={{position: "absolute", left: "100%", top: 0, padding: "16px", cursor: "pointer"}}
                title={this.state.collapsed ? "Show toolbox" : "Hide toolbox"}
                onClick={() => this.toggle()}>
                {this.state.collapsed ? ">>" : "<<"}
            </div>
            {
                this.state.collapsed ? null : <SurveyCreator.SurveyCreatorToolbox creator={this.props.creator}></SurveyCreator.SurveyCreatorToolbox>
            }
        </div>;
    }
}

SurveyReact.ReactElementFactory.Instance.registerElement("svc-toolbox", (props) => {
    return React.createElement(CustomToolboxWrapper, props);
});
```

**Comment by andrewtelnov** [comment]
Sample property grid wrapper:
```js
class CustomPropertyGridWrapper extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    const myClick = () => {
      alert("Hello World!");
    };
    return (
      <div>
        <div>Here is the title</div>
        <div>
          <button type="button" onClick={myClick}>
            Click me
          </button>
        </div>
        <SurveyCreator.PropertyGridComponent
          model={this.props.model}
        ></SurveyCreator.PropertyGridComponent>
      </div>
    );
  }
}

SurveyReact.ReactElementFactory.Instance.registerElement(
  "svc-property-grid",
  (props) => {
    return React.createElement(CustomPropertyGridWrapper, props);
  }
);

```

**Comment by tsv2013** [comment]
Here is the live plunker sample - https://plnkr.co/edit/ucDhZuC7HeXNQbOV

Property grid updated wrapper code:
```JS
class CustomPropertyGridWrapper extends React.Component {
    constructor(props) {
        super(props);
    }
    click() {
        alert("Button clicked");
    }
    render() {
        return <div style={{position: "relative", height: "100%", display: "flex", flexDirection: "column"}}>
            <div
                style={{padding: "16px", height: "100px"}}
                >
                <div>{"Custom button area"}</div>
                <button onClick={() => this.click()} >Custom button</button>
            </div>
            <div
                style={{display: "flex", height: "calc(100% - 100px)"}}
                >
            <SurveyCreator.PropertyGridComponent model={this.props.model}></SurveyCreator.PropertyGridComponent>
            </div>
        </div>;
    }
}

SurveyReact.ReactElementFactory.Instance.registerElement("svc-property-grid", (props) => {
    return React.createElement(CustomPropertyGridWrapper, props);
});
```
