### ISSUE TITLE
add css classes in controls and Render on HTML Page.  

### ISSUE THREAD

**Issue by abhishek1503** [surveyjs/survey-creator#154]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@abhishek1503 Unfortunately I could not understand the issue :-(

Thank you,
Andrew

**Comment by abhishek1503** [comment]
@andrewtelnov  i need to add class like
<input type="text" class="txtcls" />

OR
<div class="clsdiv">
</div>

**Comment by dmitrykurmanov** [comment]
Sorry for the late answer. Please describe your use case in greater details.


Also please check examples: https://surveyjs.io/Examples/Library/?id=survey-customcss&platform=jQuery&theme=default and https://surveyjs.io/Examples/Library/?id=survey-cssclasses&platform=jQuery&theme=default
