### ISSUE TITLE
Different behavior of choice name editor in property grid in Creator Knockout and Creator React: V2

### ISSUE THREAD

**Issue by ST-1580** [surveyjs/survey-creator#1541]
Creator Knockout behavior:
1) Run Creator Knockout example
2) Add checkbox question
3) Open choices section in property grid
4) Edit any choice name
5) Press enter button
6) ?
7) Choice name updated in designer area

Creator React behavior:
1) Repeat steps 1-5 from Knockout instruction
2) ?
3)  Choice name **did not** update in designer area

![image](https://user-images.githubusercontent.com/15248977/126476285-2bc08a84-93fc-48c8-8f6d-01b230bfb07b.png)

**Comment by dmitrykurmanov** [comment]
reproduced in library:
https://plnkr.co/edit/?p=preview&preview

type something and press "enter"

**Comment by dmitrykurmanov** [comment]
fixed https://github.com/surveyjs/survey-library/issues/3384
