### ISSUE TITLE
default language not showing when defaultLocale is set to the only locale provided.

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1542]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug.

### What is the current behavior?

default language not showing when defaultLocale is set to the only locale provided.

### What is the expected behavior?

default language should be visible

### How would you reproduce the current behavior (if this is a bug)?

Providing the plunker example.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/oSCKOlyJQK8CxPcE

Test code

```
Survey
    .surveyLocalization
    .defaultLocale = 'en'

Survey
    .surveyLocalization
    .supportedLocales = ['en']

```

### Specify your

* browser: chrome
* browser version: 91
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.8.57

![image](https://user-images.githubusercontent.com/37444378/126470052-6b63720f-7c42-48fd-a1ca-b37af46089ff.png)

**Comment by andrewtelnov** [comment]
@vikkrantxx7 We may take a look, but it doesn't make sense to show this property for one language.
You can add one more locale, 
`Survey.surveyLocalization.supportedLocales = ['en', 'fr'];`
or hide locale property
`Survey.Serializer.findProperty("survey", "locale").visible = false;`

Thank you,
Andrew

**Comment by vikkrantxx7** [comment]
@andrewtelnov what if we wan't to show the property but make it readOnly but that is also not working.
![image](https://user-images.githubusercontent.com/37444378/126480730-101c3397-c008-4ab3-b66c-e9d1b58724bd.png)

Even when there are multiple locales, in readOnly mode there is an empty input shown. Shouldn't it show the default option selected in readOnly?
![image](https://user-images.githubusercontent.com/37444378/126480662-3284dbe3-446a-4a3a-ae54-2fc36d83c484.png)

**Comment by andrewtelnov** [comment]
@vikkrantxx7 OK, I will take a look. We render a simple div for read-only dropdown. It is very likely do not pick-up a value from choices, since the value is undefined or empty value and doesn't check if there is a choice with empty value.
I mean there is an issue in the library.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@vikkrantxx7 There are two different issues. 
1) We do not show dropdown question for property editor with zero choices. I have fixed it by the commit above. We always use dropdown question to edit locale property.
2) displayValue is always empty if question has an empty value. I have changed it as well, by commit above and adding [new functionality](https://github.com/surveyjs/survey-library/issues/3124) into the library.
It means that you can remove all supported languages and you can make it optionally read-only. It will work in all scenarios.

Thank you,
Andrew
