### ISSUE TITLE
React build error

### ISSUE THREAD

**Issue by DaiYz** [surveyjs/survey-creator#1544]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* editor version: 1.8。57
* Works fine at http://localhost:3000, I got an error when I built it 。
* 
![image](https://user-images.githubusercontent.com/28336215/126583369-f054a193-434d-495f-863e-9509d0809ba5.png)

**Comment by andrewtelnov** [comment]
@DaiYz I believe you have included survey-knockout and survey-core+survey-knockout-ui.
You need survey-knockout only. survey-knockout = survey-core+survey-knockout-ui.
We had to split survey on core and platform libraries for [SurveyJS Creator V2](survey-knockout-ui) that you can try out know, but it is not even in beta.
For V2 you need: survey-core, survey-react-ui and survey-creator-react. Creator V2 react renders in react and don't use knockout.

Thank you,
Andrew

**Comment by DaiYz** [comment]
thanks

**Comment by DaiYz** [comment]
just import survey-creator
