### ISSUE TITLE
Duplicating a page does nothing until the tabs are changed in V2

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1547]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

The duplicated pages don't show up

### What is the expected behavior?

The duplicated pages should be visible

### How would you reproduce the current behavior (if this is a bug)?

Just duplicate any page and it is not rendered until the tabs are changed.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  https://surveyjstest.azurewebsites.net/Examples/Survey-Creator?id=addproperties&platform=ReactjsV2&theme=bootstrap#content-result

Test code

```
Not required

```

### Specify your

* browser: chrome 91
* editor version:  1.8.57

**Comment by andrewtelnov** [comment]
@vikkrantxx7 I have fixed it by the commit above.

Thank you,
Andrew
