### ISSUE TITLE
Invisible pages are not disabled in page selector in Test tab

### ISSUE THREAD

**Issue by jackwingsam** [surveyjs/survey-creator#1567]
### Are you requesting a feature, reporting a bug or ask a question?
Requesting a old feature that used to exist.

### What is the current behavior?
When I set some pages to visible and others to invisible, all of the names of the pages appear in the Test Tab's pulldown list as the same colour.

### What is the expected behavior?
I was using a version of the survey creator from the 2018/2019 era. In this old version, in the Test Tab's invisible pages were greyed out while visible pages were black.

This feature was very useful for me to quickly check the actions on my current page would render invisible pages to visible. I could quickly click the pulldown tab and see that page names have switched from grey to black.

<img width="518" alt="test_pulldown_old" src="https://user-images.githubusercontent.com/26177911/127393632-1bc808b7-8cad-4c40-91a8-136c7f0ffc72.png">

We recently upgraded to v.1.8.52 and noticed this feature was gone. I also notice that v.1.8.57 on https://surveyjs.io/create-survey does the same thing as v.1.8.52. 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: https://surveyjs.io/create-survey
* editor version: v.1.8.57

**Comment by andrewtelnov** [comment]
@jackwingsam I have fixed it by the commit above.

Thank you,
Andrew

**Comment by jackwingsam** [comment]
Thanks @andrewtelnov 🙏🏻
