### ISSUE TITLE
Survey Title in Creator

### ISSUE THREAD

**Issue by aldwnesx** [surveyjs/survey-creator#1571]
![image](https://user-images.githubusercontent.com/52225831/127626782-673f02fe-c330-4599-aa6e-4ef5ee261eec.png)

How do i disable page title and description on the creator library?

I have tried a few e.g     Survey.settings.allowShowEmptyTitleInDesignMode = false;
from https://surveyjs.io/Examples/Survey-Creator?id=titleadorner&theme=bootstrap#content-js

but it's still showing.

I am also trying to get the survey title via javascript, to check whether it's empty or now. Is this supported?

**Comment by tsv2013** [comment]
What exactly do you want to achieve? To hide survey title completely? Or hide the empty title only? Or to disable survey title editing?

>I am also trying to get the survey title via javascript, to check whether it's empty or now. Is this supported?
You can get/set the `creator.survey.title` property

**Comment by aldwnesx** [comment]
> What exactly do you want to achieve? To hide survey title completely? Or hide the empty title only? Or to disable survey title editing?
> 
> > I am also trying to get the survey title via javascript, to check whether it's empty or now. Is this supported?
> > You can get/set the `creator.survey.title` property

I am trying to require user to enter a survey title before they can save it

**Comment by JaneSjs** [comment]
Please visit the following support thread how to ensure that users specify form settings: [T16915 - Make sure the question title will have a value](https://surveyjs.answerdesk.io/internal/ticket/details/T16915).
