### ISSUE TITLE
Prepend translation export with UTF-8 BOM

### ISSUE THREAD

**Issue by mkopinsky** [surveyjs/survey-creator#1577]
Related in a sense to #910 .

### Are you requesting a feature, reporting a bug or ask a question?

Requesting a feature

### What is the current behavior?

When you export translations to CSV containing UTF-8 characters, by default they display wrong in MS Excel. You can get around this by going to Data -> Get Data -> From Text -> select file -> select UTF-8 encoding -> complete wizard but that's a lot of steps for a user.

According to https://stackoverflow.com/a/155176/299313, if you prepend the output with a UTF-8 byte order mark, most versions of Excel will behave properly. Software that doesn't recognize the UTF-8 BOM will just display the characters `ï»¿` at the start of the file.

I tested adding the UTF-8 BOM to the file (via `sed -i '1s/^/\xef\xbb\xbf/' survey_translation.csv` thanks to [this post](https://stackoverflow.com/a/12533430/299313)) and it worked in Excel for Mac 16.51.

### How would you reproduce the current behavior (if this is a bug)?

Simple survey schema:
```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1",
     "title": {
      "default": "Question Name",
      "es": "nombre de la pregunta en español"
     }
    }
   ]
  }
 ]
}
```

By default, when I open that in Excel it looks like this:
![image](https://user-images.githubusercontent.com/591435/127715619-e1662c45-d58c-4cb4-9f83-70201eefef85.png)

With the added BOM it looks like this in Excel:
![image](https://user-images.githubusercontent.com/591435/127716016-e713d170-62d8-4b0a-a702-3c906e055397.png)

I also made some modifications to the translations in the BOM-prepended file and imported, and Import did work despite the BOM. ✅ 

### Specify your

* browser: Chrome 91 on MacOS Big Sur
* editor version: latest at https://surveyjs.io/create-survey (1.8.58 per the top left of the page)

**Comment by mkopinsky** [comment]
Would a PR be accepted for this? If so, would that need to be into `survey-creator`, `survey-creator-core` or both? Would that PR need to include test coverage?

* https://github.com/surveyjs/survey-creator/blob/master/packages/survey-creator/src/tabs/translation.ts#L731
* https://github.com/surveyjs/survey-creator/blob/master/packages/survey-creator-core/src/components/tabs/translation.ts#L1086

**Comment by andrewtelnov** [comment]
@mkopinsky Sorry, I have not time to look at it yet. I hope to be back today/tomorrow.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@mkopinsky I have created PR and I hope my colleagues approve and merge it shortly.
You will have to add the following line of code:
`SurveyCreator.settings.traslation.exportPrefix ="\xef\xbb\xbf";`.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@mkopinsky @andrewtelnov  I've merged it

**Comment by tsachinn07** [comment]
Hi Andrew,

We tried the same thing but its not working in excel as expected.
https://plnkr.co/edit/g3MPWK8Rn4mQ2BNy

Is anything we are missing out here?

Thanks,
Sachin Tiwari

**Comment by andrewtelnov** [comment]
@tsachinn07 I have just tried your plunker and your prefix is in the exported Excel file. As I understand, it is needed mostly for linux OS.

Thank you,
Andrew

**Comment by mkopinsky** [comment]
For some reason, @andrewtelnov 's code snippet doesn't work. Looking at the output file in hexdump, the CSV file is prepended with `c3 af c2 bb c2 bf`.

What does work is
```js
    SurveyCreator.settings.traslation.exportPrefix = "\uFEFF";
```

This causes the file to be prepended with `ef bb bf` (looking in hexdump)

This is something to do with how javascript handles string escaping. You can see the same behavior in a shell - javascript's `\xef\xbb\xbf` becomes `c3 af c2 bb c2 bf` in hex 
```
$ node -e "process.stdout.write('abcdefg')"|hexdump
0000000 61 62 63 64 65 66 67                           
0000007
$ node -e "process.stdout.write('\xef\xbb\xbf')"|hexdump
0000000 c3 af c2 bb c2 bf                              
0000006
$ node -e "process.stdout.write('\uFEFF')"|hexdump
0000000 ef bb bf                                       
0000003
```
