### ISSUE TITLE
question title to left not working in designer V2

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1582]
### Are you requesting a feature, report a bug, or ask a question?

Reporting a bug

### What is the current behavior?

Title not shifting to the left

### What is the expected behavior?

The title should align left

### How would you reproduce the current behavior (if this is a bug)?

Align question title to left

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net/Examples/Survey-Creator?id=addproperties&platform=ReactjsV2&theme=bootstrap#content-result

Test code

```
Not required

```

### Specify your

* browser: chrome 92
* editor version: 1.8.58

**Comment by OlgaLarina** [comment]
@vikkrantxx7 This issue is fixed in the next version 1.8.59.

Thank you,
Olga

**Comment by AbhishekKS** [comment]
Hi @OlgaLarina  - Is this appearance fine on moving question title to left in V2? Does not seems well-aligned though.

![image](https://user-images.githubusercontent.com/13827554/128137741-38c5fed8-0831-4867-b55f-2ceadd1d9cff.png)

In V1 it seems to be properly aligned.

![image](https://user-images.githubusercontent.com/13827554/128137853-6629b748-8cbc-4440-926d-f356250b7f76.png)


Thanks
Abhishek

**Comment by OlgaLarina** [comment]
@AbhishekKS Fixed by the commit above.

Thank you,
Olga

**Comment by AbhishekKS** [comment]
Thanks, @OlgaLarina 

Thanks
Abhishek
