### ISSUE TITLE
Conditions and Actions text don't appear after creation on Logic Tab in V2

### ISSUE THREAD

**Issue by AbhishekKS** [surveyjs/survey-creator#1583]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
After creating logic conditions and on save, I don't see the condition(s) and action(s) text appearing on the logic tab in V2. Don't know if that would be fixed along with the new logic tab design, but just wanted to bring this to notice.

![image](https://user-images.githubusercontent.com/13827554/127980484-a27d4f79-9c34-450d-8bbf-353a0c292066.png)

### What is the expected behavior?
Conditions(s) and Action(s) text should appear once created and saved in V2

### How would you reproduce the current behavior (if this is a bug)?
1) Go to Logic Tab
2) Create a condition and an action.
3) Click on Save And Return
4) Condition(s) and Action(s) text don't appear.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser: Chrome 92
* editor version: 1.8.58 and above.

**Comment by AbhishekKS** [comment]
Sorry, I was just going through the new logic tab design pushed on the dev environment. 

URL - https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

I notice that on the click of the **edit** tab, the build and edit tabs disappear. Is it as per the new design? How to return back to the build tab again in such a case, only by 'save and return' or 'return without saving'? Also, the expression text area is also not available on the edit tab? Is it as per the new design?

![image](https://user-images.githubusercontent.com/13827554/128026025-01eb788c-74d1-4cea-8169-26bff00a1256.png)

Thanks
Abhishek

**Comment by AbhishekKS** [comment]
Also on occasion when I'm on the build tab, and I again click on build tab link, I see below error in the console.

![image](https://user-images.githubusercontent.com/13827554/128031145-cb2e95c2-61c5-4f58-9b30-edbb1284daff.png)

**Comment by tsv2013** [comment]
@AbhishekKS Could you please create a separate issues? Otherwise we can miss it.

**Comment by AbhishekKS** [comment]
Thanks, @tsv2013... I'll create a separate issue for the last posted comments.

Thanks
Abhishek
