### ISSUE TITLE
Console error on new logic tab design in V2

### ISSUE THREAD

**Issue by AbhishekKS** [surveyjs/survey-creator#1588]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
I see a console error when I click on the '**Add New**' button on Logic Tab and then click on the Build tab link.

![image](https://user-images.githubusercontent.com/13827554/128035595-ca0949d1-a758-4c26-91e7-beaafe1d5261.png)

### What is the expected behavior?

No console error.

### How would you reproduce the current behavior (if this is a bug)?
1) Go to Survey Logic tab.
2) Click on the 'Add New' button.
3) Click on the Build Tab link.
4) I see error in console.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser: Chrome 92
* editor version: 1.8.59

**Comment by andrewtelnov** [comment]
@AbhishekKS Fixed by the commit above.

Thank you,
Andrew
