### ISSUE TITLE
V2 Logic Tab: Console warning when I click on 'Save And Return' after creating a logic condition!!

### ISSUE THREAD

**Issue by AbhishekKS** [surveyjs/survey-creator#1589]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?
Getting console warning when I 'Save And Return' a condition on Logic Tab. The recording is attached for reference.

https://user-images.githubusercontent.com/13827554/128038720-6440c709-5ebb-4108-957f-f282430d4337.mp4

### What is the expected behavior?
No invalid react state update on an unmounted component warning should appear in the console.

### How would you reproduce the current behavior (if this is a bug)?

Recording is attached for reference.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser: Chrome 92
* editor version: 1.8.59

**Comment by andrewtelnov** [comment]
@AbhishekKS I have fixed it in the library. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/3170).

Thank you,
Andrew
