### ISSUE TITLE
Logic Tab V2: Build And Edit Tabs along with Expression Text Area disappear when I edit an already created logic condition!!

### ISSUE THREAD

**Issue by AbhishekKS** [surveyjs/survey-creator#1590]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

Build And Edit Tabs along with Expression Text Area disappear when I edit an already created logic condition!!
Recording attached here for reference.

https://user-images.githubusercontent.com/13827554/128040512-237707a8-e5a4-4d37-8fe6-84acca11e70e.mp4

### What is the expected behavior?
Build and Edit Tabs along with Expression Text Area should not disappear.

### How would you reproduce the current behavior (if this is a bug)?

The recording is attached for reference.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser: Chrome 92
* editor version: 1.8.59

**Comment by andrewtelnov** [comment]
@AbhishekKS I could not reproduce the issue. I beleive I have fixed it during the fix [this issue](https://github.com/surveyjs/survey-creator/issues/1600).

Thank you,
Andrew
