### ISSUE TITLE
Readonly is not working in V2

### ISSUE THREAD

**Issue by tsachinn07** [surveyjs/survey-creator#1621]
### Are you requesting a feature, reporting a bug or ask a question?
Yes its a bug

### What is the current behavior?
Readonly is not working in V2

### What is the expected behavior?
In Readonly creator inputs should be readOnly.

### How would you reproduce the current behavior (if this is a bug)?
For readonly, we do pass readOnly: true in options but for our creator V2 its not working.
https://plnkr.co/edit/pPiqFWtgjduCOY6Z
https://plnkr.co/edit/AVPju5SUrS9jE0Dd

Error: Cannot read property 'toJSON' of undefined
    at SurveyCreator../src/creator-base.ts.CreatorBase.getSurveyTextFromDesigner

Experiencing this issue in 59.

And for test website, we need to update the urls as well.
<script src="https://unpkg.com/survey-react-ui@1.8.59/survey-react-ui.js"></script>
<script src="https://unpkg.com/survey-creator-react@1.8.59-alpha.1/survey-creator-react.js"></script>
<link href="https://unpkg.com/survey-creator-react@1.8.59-alpha.1/survey-creator-react.css" type="text/css" rel="stylesheet"/>

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
You can set
```JS
creator.readOnly = true;
```
If you are talking about the option, then we'll support it.
