### ISSUE TITLE
Survey Title does not retain on UI after adding question properties 

### ISSUE THREAD

**Issue by swatiukg** [surveyjs/survey-creator#1627]
### Are you requesting a feature, reporting a bug or ask a question?

reporting a bug

### What is the current behavior?

1. Create a new survey 
2. Add survey title to it 
3. Then add question
4. Come back to survey properties
5. Value in title does not retain.

### What is the expected behavior?
Value in title should retain.

### How would you reproduce the current behavior (if this is a bug)?

1. Create a new survey 
2. Add survey title to it 
3. Then add question
4. Come back to survey properties
5. Value in title does not retain.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
I've just checked your scenario on our site - https://surveyjs.io/create-survey - and unfortunately haven't managed to reproduce the issue. Can you share the exact steps to reproduce?

**Comment by swatiukg** [comment]
This can be reproduce in any browser. For this 
1. Add new survey
2. Add its title, don't click anywhere in between
3. Then add a question from toolbox only.
4. Add question name 
5. And then go to survey properties title doesn't retain.

**Comment by AbhishekKS** [comment]
I guess here is the case when we change Survey Title from the property panel in V2 without losing focus on the title editor and then immediately perform toolbox operation (click/drag-drop).

**Comment by tsv2013** [comment]
Please mark questions related to V2 with corresponding tag. Yes I see the issue - title is lost if you start drag drop immediately after title editing in property grid. It looks like onBlur doesn't processed properly.
