### ISSUE TITLE
V2: Condition and Action are not getting Saved on click of Save and Return

### ISSUE THREAD

**Issue by tsachinn07** [surveyjs/survey-creator#1632]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug.

### What is the current behavior?
It still shows the same values for Condition and Action. Only when you click on some other tab and come back, the new values are reflected

### What is the expected behavior?
1. Condition and Action should get updated with new values

### How would you reproduce the current behavior (if this is a bug)?
STR-
1. Create a new logic.
2. Edit the logic
3. Change condition and Action
4. Click on Save and Return

Expected Result-
1. Condition and Action should get updated with new values

Actual Result-
It still shows the same values for Condition and Action. Only when you click on some other tab and come back, the new values are reflected

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@tsachinn07 I have fixed it by the commit above. PR is waiting for approve.

Thank you,
Andrew
