### ISSUE TITLE
Translations are not working for Survey Logic keywords

### ISSUE THREAD

**Issue by tsachinn07** [surveyjs/survey-creator#1636]
### Are you requesting a feature, reporting a bug or ask a question?
It is a bug.

### What is the current behavior?
If, then and Rule keywords don't translate as per users locale.

### What is the expected behavior?
If, then and Rule keywords should translate as per users locale.

### How would you reproduce the current behavior (if this is a bug)?
https://plnkr.co/edit/Utmt2QddUgVVHcEJ

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/Utmt2QddUgVVHcEJ

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@tsachinn07 We will need to remove "p" section from V2 completely. It is for old property grid that we do not have in V2. We have two properties grids in V1, new, the default one, and the old one. Most people don't use it.
Please use 
```j
    pe: {
        isRequired: "Wird benötigt"
    }
```
Additionally, there are other erros in your plunker. I did not fix them. You are showing french locale, but changed deutsch.

Thank you,
Andrew

**Comment by tsachinn07** [comment]
Hi Andrew,

I have the current locale set as "Fr", but some keywords are not getting updated as per locale.

![image](https://user-images.githubusercontent.com/16122986/129860533-4cef2fc8-ca13-4290-8edd-130f355de0d9.png)

Thanks,
Sachin Tiwari

**Comment by andrewtelnov** [comment]
@tsachinn07 Please refer to [this issue](https://github.com/surveyjs/survey-creator/issues/1640).

Thank you,
Andrew
