### ISSUE TITLE
How can I only show the delete/edit button on collection items for certain items.

### ISSUE THREAD

**Issue by BeeFrog** [surveyjs/survey-creator#1642]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
Within the designer I would like to prevent someone from editing or deleting certain options within a radio or check list. I can prevent them deleting using the onCollectionItemDeleting event but I can't find a way to disable the edit and delete buttons in the editor for only a subset of items with the collection.

### What is the expected behavior?
I'd like to be able to chain into an event much like you can for an element to allow a field to be edited/deleted.

### How would you reproduce the current behavior (if this is a bug)?
Create a checkbox type question and try to disable the delete and edit buttons on a single item within the collection.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* editor version: 1.8.55

**Comment by andrewtelnov** [comment]
@BeeFrog You can try the following code:
```js
creator.onGetPropertyReadOnly.add((sender, options) => {
    if(!options.parentObj ||!options.parentProperty || options.parentProperty.name !== "choices") return;
    var index = options.parentObj.choices.indexOf(options.obj);
    options.readOnly = index == 1;
});
```

Thank you,
Andrew

**Comment by BeeFrog** [comment]
@andrewtelnov Thank you, This kind of works. It's prevents you from editing it within the properties window but the designer still allows you to edit and delete the item. Is there any reason why these two work differently? I've seen a few places within the designer where there are inconsistencies like this.

I'm guessing most people will use the graphical designer rather than the properties window.
I'm happy to help contribute if that helps push this feature along.

**Comment by andrewtelnov** [comment]
@BeeFrog We are working on Creator V2 right now. You can find examples [here](https://surveyjstest.azurewebsites.net/Examples/Survey-Creator?id=options&platform=ReactjsV2). We are trying to solve these issues here.

Thank you,
Andrew

**Comment by BeeFrog** [comment]
@andrewtelnov Thank you for the feedback the V2 does look a lot better. I'm still getting the same results as V1 and the inconsistencies between the question designer and the properties.

Is there any way I can help out on this issue?

**Comment by andrewtelnov** [comment]
@BeeFrog Let me take a look. I will be back.

Thank you,
Andrew

**Comment by BeeFrog** [comment]
@andrewtelnov Thank you. I really appreciate it.

**Comment by andrewtelnov** [comment]
@BeeFrog I have added a new create.onCollectionItemAllowOperations event, here is [the related issue](https://github.com/surveyjs/survey-creator/issues/1727).
It will be available in 1.8.66 on the next week. Please let me know if it suites you.

Thank you,
Andrew

**Comment by BeeFrog** [comment]
@andrewtelnov I've tried to implement the new event and it looks like it's being called but it's not working for me.
I've put a copy of my code here so you can see it in action: https://jsfiddle.net/p6ju14s9/1/
When you select question 2 the first 2 items should be disabled but you can edit then in place but the properties box on the side it greyed out. Also you can delete them too.

Am I doing something wrong?

**Comment by BeeFrog** [comment]
@andrewtelnov just wanted to check if there has been any progress on this and if there is anything I can do to help.

**Comment by andrewtelnov** [comment]
@BeeFrog I remember that I have added at least one unit test on this regard and fix it.
I tried [your example](https://jsfiddle.net/surveyjs/oz06Ltsm/3/) for v1.8.76 and it seems to be working.

Thank you,
Andrew

**Comment by BeeFrog** [comment]
Thank you, I'll test this out now

**Comment by BeeFrog** [comment]
I've just checked it on 1.8.76 and 1.8.77 and it's not working I'm afraid.

below is a screen shot of what I'm seeing:
![image](https://user-images.githubusercontent.com/7447534/140965281-5b4eb653-4f14-4656-ad5a-fc348f8f25dc.png)

I can still edit the title of the choice in the designer GUI but cannot in the Choices properties UI

**Comment by andrewtelnov** [comment]
@BeeFrog Yes, we do not implement this functinality for choices adorners. As well as matrix adorners as well. We will discuss the implementation.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@novikov82 Alex, please look at this issue. We have discussed it with you today. We need to disable deleting/editing if the operation is not allowed for adorners: choices, single matrix (column/rows) and for columns in dropdown/dynamic matrices.

Thank you,
Andrew

**Comment by BeeFrog** [comment]
@tsv2013 I'm still getting the issue. It looks like DropDown lists kind of work but check lists do not.
On both I can still edit the text in the designer.

Here's some screenshots to help:
![image](https://user-images.githubusercontent.com/7447534/142837755-2ee34af5-89bb-4373-91fc-e05016287585.png)

![image](https://user-images.githubusercontent.com/7447534/142837805-d054e447-72a7-4b52-bb64-f974312b91d4.png)

**Comment by BeeFrog** [comment]
On line 56 of 
Of packages/survey-creator-core/src/components/item-value.ts
has this:
```
if (this.allowItemOperations.allowDelete === undefined) {
      this.allowItemOperations.allowDelete = allowQuestionOperations.**allowEdit**;
}
```
But shouldn't it be:
```
if (this.allowItemOperations.allowDelete === undefined) {
      this.allowItemOperations.allowDelete = allowQuestionOperations.**allowDelete**;
}
```
Also it looks like only the creator.onElementAllowOperations function affects the UI as the example above was only different because one had allowQuestionOperations.allowDelete set to true and the other was false.

**Comment by BeeFrog** [comment]
@novikov82 here's a Jsfiddle link: https://jsfiddle.net/p6ju14s9/2/
When you click on question1 you can still edit the text of item1 and item2 even though allowEdit is disabled.
The delete does not exist which is good

However looking at Question 2, you can edit and delete item 2 when it's not allowed to.

The properties box on the right hand side behaves as it should.
I hope this helps explain the issue.

**Comment by novikov82** [comment]
@BeeFrog 
We fixed some bugs and I updated your fiddle:
https://jsfiddle.net/trdwLn13/2/

I updated libraries versions to 1.9.4 (and added "defaultV2.css" - now some styles are extracted in separated file) 

What can I see now:
for question1:
item1 and item2 can not be deleted and edited (because they have issystem=true)
for question1:
item2 text can not be edited because it has index == 1
but it still can be deleted, because you procecced onGetPropertyReadOnly event for item _properties_ not for item itself.

![image](https://user-images.githubusercontent.com/29385489/147748145-72c29bb5-597e-4b59-9bf8-045b6c9db9ff.png)

To make item2 in question2 undeletable you need to extend your onCollectionItemAllowOperations event handler:
```js
    creator.onCollectionItemAllowOperations.add(function (sender, options) {
        //console.log(options.obj, options, sender);    
        console.log("onCollectionItemAllowOperations",  !options.obj, options.item);
        if(options.item && options.item.issystem) {
            
            options.allowDelete = !options.item.issystem;        
            options.allowEdit = !options.item.issystem;
        }
        if(options.obj.choices.indexOf(options.item) == 1){
        	options.allowDelete = false;
        }
    });
```
Working example is here:
https://jsfiddle.net/trdwLn13/4/

![image](https://user-images.githubusercontent.com/29385489/147749239-1b6be06e-c304-419b-8c9f-a339d743c48f.png)

**Comment by BeeFrog** [comment]
@novikov82 Thank you for fixing this. It's working beautifully.
There is one refresh item which doesn't affect my use but when you change a property to make it read only the designer doesn't hide the delete icon until you refresh the page. 
This doesn't affect our usage but thought it may be worth mentioning in case you want to raise it as a low priority backlog item.

Once again thank you so much for fixing this.
