### ISSUE TITLE
onQuestionAdded modify the survey value

### ISSUE THREAD

**Issue by dcods22** [surveyjs/survey-creator#1685]
### Are you requesting a feature, reporting a bug or ask a question?
I am trying to modify a value in the survey whenever a survey question is added.  We are tracking if the translations are complete in a custom property we added to the survey.  When a new question is added we want to update the value of that custom property so we know the survey translations are now no longer complete.  I had it working but using the onQuestionAdded to add a function.  then updating the value of the surveyJson by calling `sender.text = newSurveyJson` but this refreshes the survey.  If we were on the second page of the survey it will return us to the first page of the survey.  Is there a proper way to do this type of functionality?

### What is the current behavior?
updating the survey text via the first param of the onQuestionAdded function it moves the user back to the first page.

### What is the expected behavior?
It keeps the user where they are and the context they have selected

### How would you reproduce the current behavior (if this is a bug)?
```
const OnQuestionAdded = (sender, options) => {
    const surveyJson = JSON.parse(surveyCreator.text);
    surveyJson.translationComplete = false;
    sender.text = JSON.stringify(surveyJson);
  };

  surveyCreator.onQuestionAdded.add(OnQuestionAdded);

```

### Specify your

* browser: Chrome
* editor version: 1.8.52

**Comment by andrewtelnov** [comment]
@dcods22 You should not modify JSON. You have to modify the survey model and based on that SurveyJS Creator will deserialize the survey model into JSON and if you are using auto save functionality, offer to save it in the database. 
Here is the code you have to write:
1) Before creating Survey Creator add a new invisible property into survey:
```js
Survey.Serializer.addProperty("survey", {name: "translationComplete:boolean", visible: false });
```
2) Modify it on adding new question:
```js
const OnQuestionAdded = (sender, options) => {
   sender.survey.translationComplete = false;
};
surveyCreator.onQuestionAdded.add(OnQuestionAdded);
```

Thank you,
Andrew
