### ISSUE TITLE
Creator V2 : Build and Edit links change position on click of Edit link on logic tab

### ISSUE THREAD

**Issue by AbhishekKS** [surveyjs/survey-creator#1696]
### Are you requesting a feature, reporting a bug or ask a question?
Question/Bug

### What is the current behavior?
When I click on the Edit link on the logic tab, the build and edit links change position. Is this the correct behavior or a bug?

![image](https://user-images.githubusercontent.com/13827554/131820670-3cdf600e-e9a3-4226-9ac4-136bc6f7847c.png)

### How would you reproduce the current behavior (if this is a bug)?
On the logic tab, click on Add New link first. Then click on the edit link.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser: Chrome - Version 92
* editor version: 1.8.64

**Comment by dk981234** [comment]
Hello,

It's a bug. We will fix the issue to the next 1.8.65 version.

Thanks,
Dmitry
SurveyJS Team

**Comment by AbhishekKS** [comment]
Hi All,
Just FYI...

Today when I see the DEV website the Survey logic UI seems more broken even without clicking the edit link.

![image](https://user-images.githubusercontent.com/13827554/131961973-2715ea40-daa8-45bd-9f3a-683d4b5a1676.png)

Thanks
Abhishek

**Comment by andrewtelnov** [comment]
@AbhishekKS Thank you! We will take a look.

Andrew

**Comment by andrewtelnov** [comment]
@dk981234 I will look the last issue. The question on the right has `undefined`  "startWithNewLine" property. All unit tests are good in the library. There is something with this particular question. 
Andrew
