### ISSUE TITLE
Creator V2: Designer page becomes blank when making selection under navigation section in property panel

### ISSUE THREAD

**Issue by AbhishekKS** [surveyjs/survey-creator#1702]
### Are you requesting a feature, reporting a bug or ask a question?
Bug. Seems recently introduced with some commit in the current dev version.

### What is the current behavior?
On designer page -> open navigation section under the property panel -> Change the value for **Show navigation buttons (default navigation)** property OR change the value for **Show progress bar** property. -> Designer page turns blank. If we switch tabs it reappears. I am not sure if it's a case from other places as well while properties selection.

![image](https://user-images.githubusercontent.com/13827554/132035128-38da70c0-9afe-4c85-8e1f-b776faf4f65c.png)

![image](https://user-images.githubusercontent.com/13827554/132035188-d1c81a7a-6d49-4f91-91ec-4116530ed893.png)

### What is the expected behavior?

The designer page should not turn blank.

### How would you reproduce the current behavior (if this is a bug)?
On designer page -> open navigation section under the property panel -> Change the value for **Show navigation buttons (default navigation)** property OR change the value for **Show progress bar** property. -> Designer screen turns blank. If we switch tabs it reappears.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser: Chrome 92
* editor version: current dev version (~1.8.65)

**Comment by andrewtelnov** [comment]
@AbhishekKS I have tried the latest version and it works fine right now. 

Thank you,
Andrew

**Comment by AbhishekKS** [comment]
Hi Andrew,
I can still see this issue on your dev website? Is it an old build running there?

Thanks
Abhishek

**Comment by andrewtelnov** [comment]
@AbhishekKS Dev site should be updated in several minutes. We have red functional tests for Creator V2 and dev website triggers when all our pipelines are green, for all libraries.

Thank you,
Andrew

**Comment by AbhishekKS** [comment]
Hi @andrewtelnov  - I just checked out this pointing to 1.8.65-beta.1 version (unpkg CDN), now the page does not turn blank, but the whole designer page shifts upwards resulting in a big blank space at the bottom and a long vertical scrollbar. Could you please check out this plunker and replicate the use case here? Maybe I am missing something here? I can see this same behavior on your dev platform as well.

https://plnkr.co/edit/iQ45FsWZcmFsD3H1

Thanks
Abhishek

**Comment by andrewtelnov** [comment]
@AbhishekKS I can see it in plunker, but not on my local example. We will take a look.

Thank you,
Andrew

**Comment by OlgaLarina** [comment]
@AbhishekKS, I reproduced this issue, we will fix it.

**Comment by OlgaLarina** [comment]
@AbhishekKS , I have fixed it by the commit above.

Thank you,
Olga

**Comment by AbhishekKS** [comment]
Thanks, @OlgaLarina

Thanks
Abhishek
