### ISSUE TITLE
V2 Property Sections missing in current dev version. (1.8.66)

### ISSUE THREAD

**Issue by tsachinn07** [surveyjs/survey-creator#1738]
### Are you requesting a feature, reporting a bug or ask a question?
Question
Property sections are missing in Property Panels in the V2 Dev site.
We are planning to upgrade to 66 version, but on dev site noticed it. Just want to make sure you are aware of it.

### What is the current behavior?
Property sections are missing in Property Panels in the V2 Dev site.

### How would you reproduce the current behavior (if this is a bug)?
https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

![image](https://user-images.githubusercontent.com/16122986/133086567-a6056df2-c226-4897-876a-c7dca2de9f63.png)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by AbhishekKS** [comment]
Other observation(s) as well in 1.8.66 dev current version. I hope it's temporary and would be resolved before release.

1) Language Selector is also not visible in the Translation tab? Adaptive issue?
![image](https://user-images.githubusercontent.com/13827554/133097361-c6715b1e-fb8f-458b-acb8-319f393939bd.png)

Please, a request here, can we make sure that the V2 release version 1.8.66 is as stable as 1.8.65? We are planning to use 1.8.66 for our production release as it has a few bugs resolution earlier reported by us.

Thanks
Abhishek

**Comment by OlgaLarina** [comment]
@AbhishekKS , We've fixed the issue via thehttps://github.com/surveyjs/survey-library/commit/eb5ac228e772530008d77c70981594cb4dd5245e commit. Fix will be available in the nearest minor update.  
Thank you,
Olga
