### ISSUE TITLE
Skip "Enter" in Translation Tab editors

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#1739]
We will skip all entered "Enter" ("Carriage return") symbols.

User question - https://surveyjs.answerdesk.io/ticket/details/t7713/behavior-of-fields-is-different-on-designer-tab-and-translation-tab

**Comment by tsachinn07** [comment]
Hello Everyone,

As we have disabled enter in translation for input fields, so how users are allowed to enter dataLists through translations. As it takes all the options as a single string.

Thanks,
Sachin

**Comment by tsv2013** [comment]
Can you check the current state of thing on our test site - https://surveyjstest.azurewebsites.net/Examples/Survey-Creator?id=options&platform=ReactjsV2 and create a separate issue if any?
