### ISSUE TITLE
Creator v2: Items editing is available when choices property is readonly

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#1794]
https://plnkr.co/edit/u4TXIa6KjaHM87mG
Need to take a look at:
- property editor
- in-place editor

![image](https://user-images.githubusercontent.com/29385489/133792476-175de17f-b8ef-48d5-9afb-c875ae3a42b7.png)

**Comment by andrewtelnov** [comment]
I need to disable drag&drop now for read-only matrixes.
