### ISSUE TITLE
Combination of 'show all pages' and 'show all strings' breaking in V2

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1820]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

when the surveyJSON is reset being on the translation tab, show all pages is selected and show all strings is toggled then the translation strings are breaking. But when the tab is changed and then translation tab is selected the strings are showing properly.

Same scenario is with logic tab too. After resetting the survey the logic conditions are gone. When the tab is changed and back to logic it appears.

### What is the expected behavior?

The strings and conditions should work as expected.

### How would you reproduce the current behavior (if this is a bug)?

Click on the reset survey button while on the translation or logic tab and follow the above instructions.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/dXTB26lionrCcEBZ

### Specify your

* browser: chrome 93
* editor version: 1.8.68

**Comment by vikkrantxx7** [comment]
Please check if this fixes both logic and translation tab

**Comment by tsv2013** [comment]
@vikkrantxx7 I've created a separate issue
