### ISSUE TITLE
Translation tab latency issue in V2

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1822]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

For around 15 or more radio questions there is a significant lag while switching to translation tab and importing the translation makes the page unresponsive.

### What is the expected behavior?

The latency should not be present.

### How would you reproduce the current behavior (if this is a bug)?

Providing plnkr

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/lcTVCW5bCw5eQyGa

### Specify your

* browser: chrome 93
* editor version: 1.8.68

translation file-
[survey_translation(3).csv](https://github.com/surveyjs/survey-creator/files/7208157/survey_translation.3.csv)

**Comment by vikkrantxx7** [comment]
And can some sort of loading status be updated while uploading the translations so that we can show some loader?

**Comment by andrewtelnov** [comment]
@vikkrantxx7 We need to try to fix the performance issue first.

Thank you,
Andrew

**Comment by AbhishekKS** [comment]
Hi @andrewtelnov,
Sorry, just wanted to check the update on this, please. As this being a high priority for us at the moment. Can we plan the fix for this at the earliest?

Thanks
Abhishek

**Comment by andrewtelnov** [comment]
@AbhishekKS Serge has fixed the issue with autoGrow comment, by making it async.
We want to check the perfomance on large surveys and that is why we do not close the issue.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@AbhishekKS @vikkrantxx7 We have improve performance for translation tab by locking updates on adding elements into tranlation Survey and by setting lazyRendering for this survey.
It opens in less than 1 second for >1000 questions survey now.

Thank you,
Andrew

**Comment by AbhishekKS** [comment]
Hi @andrewtelnov,
With lazy rendering now, with more pages and questions (in plnkr shared above 5 pages and 33 questions), and with a filter set as 'Show All Pages', the scrolling on the translation tab stops after the initial few pages. With this users cannot see lower pages and questions fields on the translation tab with scrolling. Also, can we see if there is any scope of improvement when importing translations in V2? Importing translations seems faster in V1 compared to the V2 version for the same JSON structure. I checked this comparison for the translations CSV file shared above.

Thanks
Abhishek

**Comment by andrewtelnov** [comment]
@AbhishekKS I have created a [separate issue regarding importing perfomance](https://github.com/surveyjs/survey-creator/issues/1902).
About scrolling and lazy rendering. We are discussing to render a question skeleton. A styled div without content inside and content will be shown when the question becomes visible. It should solve the issue with scrolling, while keep the perfomance about at the same level.

Thank you,
Andrew

**Comment by tsv2013** [comment]
I've added skeleton for invisible translation item lines. Now scroller should look ok. @AbhishekKS you can check it after it will be merged and published on test site
