### ISSUE TITLE
CV2: String editor - add colored hover and remove done button

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#1836]
Preferred design:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/29385489/134519467-0b518de0-5a8a-47a9-b6bd-d9d9852e0413.png)

Rejected design:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/29385489/134481847-07d16bb3-d783-427a-9fb4-c292ddf786cb.png)

**Comment by novikov82** [comment]
![image](https://user-images.githubusercontent.com/29385489/134516203-51c0bf61-f785-4572-a477-ee7949cf165e.png)
![image](https://user-images.githubusercontent.com/29385489/134516241-1f0a059b-ddf4-44a2-b3d2-537085a99fb7.png)
![image](https://user-images.githubusercontent.com/29385489/134516281-5bb65f32-b5f3-4d41-84b6-121c58a7436a.png)
![image](https://user-images.githubusercontent.com/29385489/134516306-c6106866-0542-4791-a853-952195d8531b.png)

**Comment by AbhishekKS** [comment]
With this change, now if I copy-paste a sentence from a different source into the string editors and then on removing it without blur, the string editor disappears in the designer.

Example:
**On copying text into Survey Title:**

![image](https://user-images.githubusercontent.com/13827554/134743525-7c86db59-a2c2-43f4-a26d-f51706700dd9.png)

**On removing text from survey title:**

![image](https://user-images.githubusercontent.com/13827554/134743770-263d8fb1-3b84-47ee-84e9-35a48039d471.png)

Thanks
Abhishek
