### ISSUE TITLE
Layout error while using bootstrap 5

### ISSUE THREAD

**Issue by f-starace** [surveyjs/survey-creator#1859]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
<img width="1187" alt="Schermata 2021-09-24 alle 14 56 41" src="https://user-images.githubusercontent.com/64803153/134677989-36ed2f9f-1942-48e2-bb31-7a3c87ed8d8a.png">

### What is the expected behavior?
.svd_editors should occupy the whole width of the parent's row

### How would you reproduce the current behavior (if this is a bug)?
Bug appears while using the latest available version from bootstrap

### Specify your

* browser: Chrome
* browser version: 93.0.4577.82
* surveyjs platform (angular or react or jquery or knockout or vue): knockout
* surveyjs version: 1.8.68

**Comment by kefivitch** [comment]
Same issue with Vue 3
![image](https://user-images.githubusercontent.com/10982211/134681791-574a4698-6724-498b-9cdc-bcd88ec493c0.png)

**Comment by kefivitch** [comment]
All you need is to delete the `row` class from the div with `svd_survey_designer` class or simply execute the next script on the page
```
$(document).ready(function () {
   $(".svd_survey_designer").removeClass("row");
});
```
@f-starace would you mark this issue as closed and do a quick fix ?

**Comment by ST-1580** [comment]
Hello, @f-starace, @kefivitch 

We've fixed this bug via the commit above. The problem of your solution is changing the layout. It can fix that bug but it also can produce other bugs. So we changed css selectors to make them higher priority than bootstrap styles. This functionality will be available in the nearest update.

Thanks, Yaroslav
SurveyJS Team
