### ISSUE TITLE
Is there a way to hide specific fields in the translation tab and/or disable the 'show all pages' dropdown?

### ISSUE THREAD

**Issue by JosephBrooksbank** [surveyjs/survey-creator#1863]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
When the 'show all pages' option is selected rather than a specific page, the title of the survey is editable
![image](https://user-images.githubusercontent.com/6687530/134739195-c1900725-4976-47ae-8d93-5d2bd71ea7e7.png)
If 'page1' is selected, the title field no longer appears: 
![image](https://user-images.githubusercontent.com/6687530/134739254-76ab2f8c-e77e-4c7f-8478-e0d14744a984.png)

We currently change the titles of the surveys as part of a different process, and do not want the title to be editable in the Survey Creator. Is there either: 

A way to set 'show all pages': false in config, and hide the dropdown

or 

A way to hide specific fields in the translation tab? 

Thanks

**Comment by OlgaLarina** [comment]
@JosephBrooksbank 
You can use the new event onTranslationStringVisibility to hide the survey title on the Translation tab. This event will be available in the next version v1.8.79. An example of using an event.
`creator.onTranslationStringVisibility.add((sender, options) => {
    if (options.obj.getType() == "survey" && options.propertyName === "title") {
      options.visible = false;
    } else {
      options.visible = true;
    }
  });`
