### ISSUE TITLE
Page Name Uniqueness

### ISSUE THREAD

**Issue by tsachinn07** [surveyjs/survey-creator#1882]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
When we duplicate a page, the Page name works fine Page 1 and Page 2. But after that when we add a question in a new page let suppose Page3, then the new page takes name as Page 2.

### What is the expected behavior?
Page name should be unique.

### How would you reproduce the current behavior (if this is a bug)?
Duplicate/copy a page. And then try to add new questions on the new page. Then page name doesn't remains unique.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsachinn07** [comment]
Hello,

Any update on this?

**Comment by tsv2013** [comment]
Sorry, we've missed this. I've added this task to our incoming queue.

**Comment by novikov82** [comment]
@tsachinn07 issue is fixed and waiting for release
