### ISSUE TITLE
Knockout Logic tab: Questions are not displayed in the trigger action

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#1885]
![image](https://user-images.githubusercontent.com/14936841/135048141-1def4ac3-1cf1-42cb-ade2-d2f897752189.png)

**Comment by andrewtelnov** [comment]
It was fixed by refactoring knockout row rendering [this issue](https://github.com/surveyjs/survey-library/issues/3400).

Thank you,
Andrew
