### ISSUE TITLE
TestSurvey page switcher should contain page titles intead of Page names

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#1892]
Exisiting design:
![image](https://user-images.githubusercontent.com/29385489/135080282-3b350a29-8879-469f-80b1-6906835f70a0.png)

Maybe it is useful to set "(3 of 12)"

**Comment by andrewtelnov** [comment]
@novikov82 Page titles could be long and it could look weird. Developer can change the display title and selected page title using   [creator.onGetObjectDisplayName event](https://github.com/surveyjs/survey-creator/issues/1864).

Thank you,
Andrew
