### ISSUE TITLE
MaxLength in designer Tab fields, doesn't work for Translation tab

### ISSUE THREAD

**Issue by tsachinn07** [surveyjs/survey-creator#1905]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
We have specified a maxLength for the title field of questions, survey, and Page. Due to which we are not able to type any more characters in it.  But in the translations tab, as we have textarea for every field, we are able to type more characters in the title.

So is it possible to have consistency in the Designer and translation tab for maxLength property of the fields.

### What is the expected behavior?
There should be consistency between fields in both tabs. If maxlength is set on designer tab then user should not be able to add more characters in the same field on translation tab as well.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@tsachinn07 Yes, we did not set it. We will fix it.

Thank you,
Andrew
