### ISSUE TITLE
Cannot Delete Ranking Question

### ISSUE THREAD

**Issue by Adityagrao** [surveyjs/survey-creator#1908]
### Are you requesting a feature, reporting a bug or ask a question?
Once we add a Ranking Question, Not able to delete it which is blocking the entire survey

### How would you reproduce the current behavior (if this is a bug)?

Add A Ranking Question and Try to Delete it

Screenshots 

![image](https://user-images.githubusercontent.com/11465032/135245828-8869bc7d-eb54-4033-9e20-1ba86e207c8a.png)

Where in other Questions have the option to delete that question 

![image](https://user-images.githubusercontent.com/11465032/135245945-f1054f82-86e2-4a15-b469-03252106abb5.png)

**Comment by dmitrykurmanov** [comment]
We've fixed the bug. Fix will be available in the 1.8.70. We will make new release with the fix as soon as possible.
