### ISSUE TITLE
V2: Update all pages on changing survey locale in designer

### ISSUE THREAD

**Issue by AbhishekKS** [surveyjs/survey-creator#1918]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
If I provide translations for Survey, Page, Question, and Choice level properties in multiple languages. Now when I switch language from the property section on the designer page, only the top page translations along with Survey properties get updated immediately. whereas for down pages, it gets updated only when I click on those pages explicitly or when I revisit the designer page again.

**Video attached for reference:**
https://user-images.githubusercontent.com/13827554/135318985-be03783d-5502-4556-aad2-5a04a12475e6.mp4

### What is the expected behavior?
All translations should be updated immediately on language switch in the property section.

### How would you reproduce the current behavior (if this is a bug)?
1) Add three pages with questions on each page.
2) Provide translations for Survey, Page, and Question level properties in multiple languages from the translation tab.
3) On the designer page, change the language from the default language selector. Only the top page along with the survey title and survey desc gets updated immediately.
4) Lower pages translations get fully translated only when I click on those pages on the designer or when I revisit the designer page again.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser: Chrome 93
* editor version: 1.8.69 or even in earlier versions as well.

**Comment by andrewtelnov** [comment]
@AbhishekKS Indeed, we update the current page only. We should update all pages in design-time for CreatorV2.

Thank you,
Andrew
