### ISSUE TITLE
Logic tab: the question selector is empty if the rule is reopened

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#1946]
Once I create logic on the logic tab, and when I reopen the logic without changing tabs, the question is not coming as selected in the IF condition.
![image](https://user-images.githubusercontent.com/14936841/135819812-b4e19931-d639-4e78-8924-201eee0d99ee.png)

**Comment by AbhishekKS** [comment]
I am not sure, but it seems this fix or some other code change has now removed the edit toggle (expand/collapse) for the logic created. 

Thanks
Abhishek
