### ISSUE TITLE
Creator V2: Translation Input fields not appearing on adding new language in translation tab

### ISSUE THREAD

**Issue by AbhishekKS** [surveyjs/survey-creator#1960]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?

If I go to the translation tab and add a new language, input fields for the new language column don't appear. When I select to show all strings it appears. It seems some recent code change broke this.

![image](https://user-images.githubusercontent.com/13827554/136167434-4d8c8283-658c-4540-8722-a680a90624ed.png)

### What is the expected behavior?
Translation input fields should appear immediately on adding a new language.

### How would you reproduce the current behavior (if this is a bug)?
Go to the translation tab, add a new language. Column for new language appears, but input fields are not coming for the new language.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser: Chrome 94
* editor version: 1.8.71 (current dev version)

**Comment by andrewtelnov** [comment]
@AbhishekKS Yes, I have just fixed it via [this commit](https://github.com/surveyjs/survey-creator/commit/ed184a6d95d9637c9634f4c02475c924218e8567). I introduced it during performance optimization.

The most of our functional tests for V2 were turn off for several days. We find out it yesterday before releasing. We have the e2e test on this functionality and it was red. My commit fixed it.
There are still two red functional tests on drag&drop. We will make all tests green and release a new version, hopefully today. 

Thank you,
Andrew
