### ISSUE TITLE
V1: Horizontal Scroll is not working properly with dynamic matrix 

### ISSUE THREAD

**Issue by iyamus** [surveyjs/survey-creator#2049]
### Are you requesting a feature, reporting a bug or asking a question?
In SurveyJS Creator, the horizontal scroll in dynamic matrix does not work properly. 

### What is the current behavior?
Even though the horizontal scroll option is displayed in the layout, it is not functioning properly. 
![image](https://user-images.githubusercontent.com/39981992/136993567-e37fb2ac-067b-408d-b05d-767e842ee2c6.png)

### What is the expected behavior?
Horizontal scroll is working properly with adding more columns.

### How would you reproduce the current behavior (if this is a bug)?
`{
 "pages": [
  {
   "name": "test",
   "elements": [
    {
     "type": "matrixdynamic",
     "name": "test",
     "valueName": "test1",
     "columns": [
      {
       "name": "column1"
      },
      {
       "name": "column2"
      },
      {
       "name": "column3"
      },
      {
       "name": "column4"
      },
      {
       "name": "column5"
      },
      {
       "name": "column6"
      },
      {
       "name": "column7"
      },
      {
       "name": "column8"
      },
      {
       "name": "column9"
      },
      {
       "name": "column10"
      },
      {
       "name": "column11"
      },
      {
       "name": "column12"
      },
      {
       "name": "column13"
      },
      {
       "name": "column14"
      }
     ],
     "horizontalScroll": true,
     "choices": [
      {
       "value": "Yes",
       "text": "Yes"
      },
      {
       "value": "No",
       "text": "No"
      }
     ],
     "allowAddRows": false,
     "allowRemoveRows": false,
     "rowCount": 3
    }
   ]
  }
 ],
 "showQuestionNumbers": "off"
}`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:Firefox
* browser version:93.0
* surveyjs platform (angular or react or jquery or knockout or vue):react
* surveyjs version:^1.8.67

**Comment by dmitrykurmanov** [comment]
It the creatorV1 it is "by design" feature and doesn't supposed to work.

Please try ourV2 (but it is still in alpha for now): https://surveyjstest.azurewebsites.net/Examples/Survey-Creator?id=real-nps&platform=ReactjsV2
