### ISSUE TITLE
Custom property can't depend on choices

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#2164]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
It seems setting `dependsOn` to a choices property does not fire the callback.

### What is the expected behavior?
I'd expect it to fire based on this example: https://surveyjsio.azurewebsites.net/Examples/Survey-Creator?id=dependsonproperties

### How would you reproduce the current behavior (if this is a bug)?
Create a dependent property that depends on the choices in a select base question:
```
Survey.Serializer.addProperty("selectbase", {
        name: "example",
        type: "string",
        dependsOn: ["choices"],
        choices: (obj, callback) => {
            debugger;
        },
        default: "",
        category: "Statistics & analytics",
    });
``` 

Note that I've confirmed that the above sample works fine when using `dependsOn: ["title"]`. I guess it has to do with the fact that choices is an object. I've manually tested using `obj.registerFunctionOnPropertyValueChanged("choices", () => { debugger; });`, which does fire.

**Comment by andrewtelnov** [comment]
@SamMousa We have to react on array change event to handle this. I will take a look.

Thank you,
Andrew

**Comment by SamMousa** [comment]
The same goes for column in matrix question type.

**Comment by andrewtelnov** [comment]
Yes, it is the same story, changing the array property.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SamMousa I have fixed the issue. However, if you change the choices in designer itself, and not in property grid and will not work. Unfortuantely, I did not come to a solution how to fix it in Creator V1.
I add a test into Creator V2 and it works out of box. We have a different approach in V2.

Thank you,
Andrew

**Comment by SamMousa** [comment]
Should have just left for V2 then! I post these issues so you're aware, usually I'll have a workaround so it doesn't block me. Thanks though for the prompt fixes! :smiley:
