### ISSUE TITLE
Panel reference displaying empty string in SurveyCreator

### ISSUE THREAD

**Issue by seeker25** [surveyjs/survey-creator#2192]
Hello there with this link:
https://surveyjs.io/Examples/Survey-Creator#content-result
or 
https://surveyjs.io/Survey/Builder/

Used the following JSON:
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question4"
    },
    {
     "type": "paneldynamic",
     "name": "question1",
     "templateElements": [
      {
       "type": "text",
       "name": "question3"
      },
      {
       "type": "text",
       "name": "question2",
       "title": "How are you {panel.question3}? How are you {question4}?"
      }
     ]
    }
   ]
  }
 ]
}
```

![image](https://user-images.githubusercontent.com/3484109/141597855-04c3694d-9a57-4356-b13c-1f4b46a1cea8.png)

You'll notice in the survey editor the {panel.question3} -> becomes "" but yet {question4} is still shown as "{question4}".

This makes it a bit tricky when filling out a survey using the designer, as it appears How are you ? shows up instead of How are you {panel.question3}?

When you run the test the survey it's as expected, both are blank obviously:

![image](https://user-images.githubusercontent.com/3484109/141597880-f5273c1b-60e7-4291-8362-1f0041d182d7.png)

**Comment by tsv2013** [comment]
Fixed via https://github.com/surveyjs/survey-library/pull/3879 PR in library
