### ISSUE TITLE
CV2: VisibleIf and dropdown property editor doesn't work in choices property editor

### ISSUE THREAD

**Issue by schmalliee** [surveyjs/survey-creator#2203]
### Are you requesting a feature, reporting a bug or asking a question?
bug

### What is the current behavior?
Adding a new property with visibleIf does not change the visibility within choices

### What is the expected behavior?
Item should not be visible unless condition is met

### How would you reproduce the current behavior (if this is a bug)?
```
SurveyKo.Serializer.addProperty('itemvalue', {name: 'extrasType:dropdown', choices: ['fixed-price', 'hourly']});
SurveyKo.Serializer.addProperty('itemvalue', {
    name: 'proPay:number',
    dependsOn: ['extrasType'],
    visibleIf: function(obj) {
      return obj.extrasType == 'fixed-price';
    }
  });
SurveyCreator.SurveyQuestionEditorDefinition.definition['itemvalue[]@choices'].properties.push('proPay');
```

### Specify your

* browser: Chrome
* browser version: 94
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: 1.8.68

**Comment by andrewtelnov** [comment]
@schmalliee It works for me. Here is [the example](https://plnkr.co/edit/EWxQETDlPNtze1CQ).

Thank you,
Andrew

**Comment by schmalliee** [comment]
@andrewtelnov it doesn't change the visibility if I select hourly within extrasType

**Comment by andrewtelnov** [comment]
@schmalliee Indeed, I did not notice the 4th column. Unfortunately, we do not support this functionality in the matrix view for Creator V1. You can show these properties or "proPay" property in the edit form only:
```js
Survey.Serializer.addProperty('itemvalue', {
    name: 'proPay:number',
    dependsOn: ['extrasType'],
    showMode: "form",
    visibleIf: function (obj) {
        return obj.extrasType == 'fixed-price';
    },
});
```

We can consider to implement this functionality in Creator V2.

Thank you,
Andrew

**Comment by schmalliee** [comment]
@andrewtelnov I'm not sure what you mean by "in the edit form only", adding that `showMode` doesn't seem to work either. Regardless, it would be super helpful. We have many use cases that we'd love to use it for (as well as being able to set visibility based on other properties, e.g. itemvalue choice value visibility based on whether a general question has an answer)

**Comment by andrewtelnov** [comment]
@schmalliee Here is the [updated example](https://plnkr.co/edit/zHOIvXxs7FWSA5hr) with :showMode". Regarding Creator V2, we will take a look and comeback to you.

Thank you,
Andrew
