### ISSUE TITLE
React warning about pure "render" function

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-creator#2215]
[get currentPage](https://github.com/surveyjs/survey-library/blob/7884d6af4216998240ab776aacbad2c7b4c0e6f2/src/survey.ts#L2589) getter has side effects which caused react warning: 

> Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function...

```js
  public get currentPage(): any {
    if (this.currentPageValue != null) {
      if (!this.isPageInVisibleList(this.currentPageValue) || this.pages.indexOf(this.currentPageValue) < 0) {
        if (
          !this.onContainsPageCallback ||
          !this.onContainsPageCallback(this.currentPageValue)
        ) {
          this.currentPage = null;
        }
      }
    }
    if (this.currentPageValue == null && !!this.firstVisiblePage) {
      this.currentPage = this.firstVisiblePage;
    }
    return this.currentPageValue;
  }
```

could be reproduced by drag drop question from the toolbox to the first position (the page should contain some questions before it)

**Comment by andrewtelnov** [comment]
The bug was fixed in library. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/3622).

Thank you,
Andrew
