### ISSUE TITLE
Add small fixies in defaultV2 desktop theme

### ISSUE THREAD

**Issue by dk981234** [surveyjs/survey-creator#2218]
- [x] fix paddings for the paneldynamic panels without the remove button
- [x] fix survey's progress bar bottom
- [x] change remove button in the matrixdynamic on icon
- [x] fix imagepicker styles for video items 
- [x] signature pad issue (see below)
- [x] fix boolean in Vue:
 ![image](https://user-images.githubusercontent.com/21283706/142584044-61b14c1a-95b6-4659-9b1d-78e65b56f49e.png)
- [x] fix ios issues:
   - [x] fix multipletext alignment
   - [x] fix tooltip error box styles
   - [x] fix imagepicker gap between items

**Comment by tsv2013** [comment]
Signature pad looks ugly in defaultV2 theme:
![image](https://user-images.githubusercontent.com/3013415/142439784-8a6e272b-1823-467a-8293-6cc23f764bc5.png)
