### ISSUE TITLE
Toolbox - Add search option for toolbox items (suppose if the elements in toolbox is more than 100 and need to search how do we acheive)

### ISSUE THREAD

**Issue by Neeraja-Reddy-1** [surveyjs/survey-creator#2231]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
Unfortunately SurveyJS Creator doesn't have such an option. You can group toolbox items in categories as shown in this example on our site - https://surveyjs.io/Examples/Survey-Creator?id=toolboxcategories&theme=bootstrap

**Comment by Neeraja-Reddy-1** [comment]
okay thank you.
Is there any event on clicking "Add to Toolbox" of a question in creator container

**Comment by tsv2013** [comment]
You can use the https://surveyjs.io/Documentation/Survey-Creator?id=surveycreator#onQuestionAdded event

**Comment by Neeraja-Reddy-1** [comment]
Can we add a property (addProperty) for each question of type array and select mutiple choices.
And can we add a question to multiple category.

**Comment by tsv2013** [comment]
>Can we add a property (addProperty) for each question of type array and select mutiple choices.
Yes, here is the example - https://surveyjs.io/Examples/Survey-Creator?id=addproperties&theme=bootstrap
>And can we add a question to multiple category.
No, you cann't

**Comment by JaneGaid** [comment]
From [T10568 - Programatically load question in survey designer](https://surveyjs.answerdesk.io/internal/ticket/details/T10568)
> Is there a way to get a search box? a way to filter the toolbox that's near it? similar to what you have in the type selector dropdown on the question elements themselves?

**Comment by novikov82** [comment]
Also we need to think about alternative names for questions. For example, search query "Single" could find "Single-choice matrix", and "Single input" -  and "Radiogroup", and "Dropdown" because they are single choice questions.

**Comment by mikeamelin** [comment]
Design — https://www.figma.com/file/SSMZUWJve1zuMSeA5E5YpA/CTR--%3E-Creator-Preview?type=design&node-id=2210-56105&mode=design
