### ISSUE TITLE
Question with Image 

### ISSUE THREAD

**Issue by jungsoo827** [surveyjs/survey-creator#2233]
### Are you requesting a feature, reporting a bug or ask a question?

Yes ( improvement) 

### What is the current behavior?

Image is seperately added among different questions.

### What is the expected behavior?

Below question title and description, image must be displayed within the question

### How would you reproduce the current behavior (if this is a bug)?

It seems like it is not possible to do that right now

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* editor version:  v2

**Comment by tsv2013** [comment]
Right now you can subscribe the https://surveyjs.io/Documentation/Library?id=surveymodel#onAfterRenderQuestion event and add necessary content to the DOM

Here is the example on our site (it adds button) - https://surveyjs.io/Examples/Library?id=survey-afterrender&platform=Knockoutjs&theme=modern
