### ISSUE TITLE
Creator V2: Change default language in V2

### ISSUE THREAD

**Issue by asemsa** [surveyjs/survey-creator#2262]
### Are you requesting a feature, reporting a bug or ask a question?
question

//Make french locale active
SurveyCreator.editorLocalization.currentLocale = "fr";

How it is done with v2?

**Comment by andrewtelnov** [comment]
@asemsa We do our best to keep the same API for V2, also the most code is re-written completely.
Here is [the example](https://surveyjs.io/Examples/Survey-Creator?id=localization&platform=ReactjsV2) in V2. As you see we use the same code.
Please read more in our [migration guide](https://surveyjs.io/Documentation/Survey-Creator?id=Migrate-from-V1-to-V2).

Thank you,
Andrew

**Comment by asemsa** [comment]
Thank you Andrew your example was helpful.
