### ISSUE TITLE
Creator V2: Unable process binding error if using survey-creator-knockout in a Vue 3 app

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#2279]
See the https://surveyjs.answerdesk.io/ticket/details/t8281/error-after-update thread for more details

**Comment by frankinedinburgh** [comment]
Im using Survey Creator V1 with React ^17 and am getting this error regularly. Below are the version I have installed 
```
"survey-core": "^1.9.2",
"survey-creator": "^1.9.2",
"survey-creator-core": "^1.9.1-beta.1",
"survey-creator-react": "^1.8.71-beta.1",
"survey-pdf": "latest",
"survey-react": "^1.9.2",
"survey-react-ui": "^1.9.2",
"surveyjs-widgets": "^1.9.2",
```

**Comment by tsv2013** [comment]
@frankinedinburgh  In your case you don't use the `survey-creator-knockout` package  in a Vue 3 app. The `survey-creator-knockout` package is not listed in your packages. And you are in a React application. Could you create a separate ticket with the steps to reproduce your issue or share a minimal live sample illustrating it?
