### ISSUE TITLE
Creator V2: page navigator design

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#2285]

**Comment by AbhishekKS** [comment]
Hi @tsv2013 ,
It seems post this change, the page selector is not working on the designer page when we click on individual pages (say page1, page 2, etc icons). When I use the Select Page option to select the page it works fine. Could you please check? It can be reproduced on your test website. One more thing I notice is that, when I select a page using page selector, the property grid selector is set to Survey.

Thanks
Abhishek

**Comment by tsv2013** [comment]
@AbhishekKS Indeed it is the designed behavior of the page navigator: page navigator should scroll to the corresponding page but not to select it (don't change selection). Our chief designer asked us to implement exactly this behavior.

I left an ability to select page via dropdown menu, that it inconsistent. But us for me - this gives a chance to select page via page navigator.

As for 
> One more thing I notice is that, when I try to select a page using page selector, the property grid selector is set to Survey.

we will fix it - https://github.com/surveyjs/survey-creator/issues/2297#issuecomment-990948231
