### ISSUE TITLE
Drag and Drop styling

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#2288]
- [x] check and fix style for dragged element (fig. 1)
- [x] reset selection from question after drag start
- [x] insert indicator (orange line) should move the bottom question (see #2411)
- [x] add pressed state for toolbox items when adding a question https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=10177%3A82188
- [x] while dragging from the toolbox, page and the dragging element should have an orange border https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=2050%3A8666

Current design:
![image](https://user-images.githubusercontent.com/29385489/144242882-031fb6f9-3750-4691-9e89-0d789a16ae0f.png)
![image](https://user-images.githubusercontent.com/29385489/144243097-15123136-4278-492f-bb6a-b9605ff45015.png)

Needed design:
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=9927%3A76581

**Comment by dmitrykurmanov** [comment]
https://www.figma.com/proto/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?page-id=11503%3A94985&node-id=11503%3A94997&viewport=449%2C48%2C1&scaling=min-zoom&starting-point-node-id=11503%3A94997
