### ISSUE TITLE
Select, not remove current item from Question converter popup

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#2290]
![image](https://user-images.githubusercontent.com/29385489/144246700-c1844b77-3a2f-4cad-be5a-855c8ca4ac1b.png)

**Comment by andrewtelnov** [comment]
@novikov82 @mikeamelin I will make it disable.

**Comment by mikeamelin** [comment]
> @novikov82 @mikeamelin I will make it disable.

Selected state should be better way.

**Comment by andrewtelnov** [comment]
@mikeamelin Remove disabled state and make it active.

Thank you,
Andrew
