### ISSUE TITLE
Implement empty survey page

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#2296]
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=2050%3A7046
![image](https://user-images.githubusercontent.com/29385489/144414678-cc42f7d4-1055-43d9-b895-05c0a8e75846.png)

**Comment by OlgaLarina** [comment]
To return the old behavior, use the following code:
`SurveyCreator.settings.defaultNewSurveyJSON = { pages: [{ name: "page1" }] };`
