### ISSUE TITLE
V2: Matrix Droptown Vertical Columns caption works incorrectly

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#2303]
![image](https://user-images.githubusercontent.com/29385489/144570120-e752445c-9d72-4c23-8d64-5f97112de107.png)

**Comment by andrewtelnov** [comment]
@novikov82 I could not reproduce the issue on the current build.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@novikov82 Table rendering is correct. However, on editing "Row 1", "Column 1" will be edited actiually. It is incorrect.
