### ISSUE TITLE
Make dynamic matrix Add/Delete buttons DISABLED

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#2315]
![image](https://user-images.githubusercontent.com/29385489/144595103-310e6b27-31d1-484f-be76-a4274f70c089.png)

**Comment by andrewtelnov** [comment]
@novikov82 @mikeamelin How Creator user will be able to understand does he/she turn off Add new rows and/or removes rows functionality or not?

Thank you,
Andrew

**Comment by mikeamelin** [comment]
> @novikov82 @mikeamelin How Creator user will be able to understand does he/she turn off Add new rows and/or removes rows functionality or not?
> 
> Thank you, Andrew

Well, let's try using disabled states. My point was... to make the view a bit lighter removing unnecessary objects, and not confuse users with wrong actions. But I agree with you about ability to understand.

**Comment by novikov82** [comment]
> Well, let's try using disabled states. My point was... to make the view a bit lighter removing unnecessary objects, and not confuse users with wrong actions. But I agree with you about ability to understand.

Bu the way, there is an inplace editor for "Add row" button text. Think that we should continue support this ability.

**Comment by novikov82** [comment]
Decision: make buttons Disabled, waiting for design.
