### ISSUE TITLE
Implement design for DnD of items/choices/rows in property grid

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#2320]
Current:

![image](https://user-images.githubusercontent.com/3013415/144613495-39a47fcb-9f7f-4c0a-9919-d7220ab8e16f.png)

Expected:

https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=10957%3A97388

**Comment by dmitrykurmanov** [comment]
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=10957%3A97388
