### ISSUE TITLE
Image import

### ISSUE THREAD

**Issue by thalhamerb** [surveyjs/survey-creator#238]
### Are you requesting a feature, reporting a bug or ask a question?
requesting a feature

### What is the current behavior?
no image imports

### What is the expected behavior?
Be able to import an image that can be used along with the question text.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@thalhamerb Have you seen the [markdown example](https://surveyjs.io/Examples/Library/?id=survey-markdown-radiogroup)?

Thank you,
Andrew
