### ISSUE TITLE
Hiding properties in custom widgets (API)

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#2394]
### Are you requesting a feature, reporting a bug or ask a question?
Question / feature

### What is the current behavior?
Currently there are several ways to remove / hide properties.
1. Hide them on the global serializer
2. Remove them from the class in the global serializer
3. Hide them in an event listener on the creator

### What is the expected behavior?
When I define a custom widget class I should be able to hide properties, just like I'm able to add them:
```js
 init() {
            Survey.Serializer.addClass("tiereditemvalue", [
                {
                    name: "tier",
                    choices: ["primary", "secondary", "tertiary"]
                }, {
                    name: "text"
                }
            ], null, "itemvalue");
},

```
Here I can't remove a property on a parent class (which is not suppported). So my only option is to hide the property, but to do that I need a reference to the editor; which I don't have at this point.

One workaround is to use the `afterRender` function:
```js
afterRender(question, el) {
     const editor = question.getSurvey().getEditor();
     editor.onShowingProperty.add(...);

},

```
The issue with this approach is that for every extra question of the same type we'll get another event listener; or I have to keep track of which editor has already registered such an event handler... this is complicated.

## Proposed solution
I propose adding a function to the widget API:
```
onShowingProperty(name) {

}
```
This leads to clean custom widgets as well as a simple API to implement. The editor could then call this for each property just like it does now with the `onShowingProperty` callback. Only in this case it'll already be scoped to the question, so all we need to do is a simple string match to make our decision.

**Comment by tsv2013** [comment]
Can you hide the property during class registration?
```JS
Serializer.addClass(
  "choicesByUrl",
  [
    "url",
    "path",
    "valueName",
    "titleName",
    {
      name: "imageLinkName",
      visibleIf: function(obj: any) {
        return !!obj && !!obj.owner && obj.owner.getType() == "imagepicker";
      },
    },
    { name: "allowEmptyResponse:boolean", default: false },
    { name: "attachOriginalItems:boolean", default: false, visible: false }, // This propoerty will be invisible in creator
  ],
  function() {
    return new ChoicesRestful();
  }
);
```

**Comment by SamMousa** [comment]
Not sure what caused me to pose this question. I think the `visibleIf` actually solved the problem. Thanks!
