### ISSUE TITLE
Editing translations in Creator V2 for other than default language does not trigger saving or any event

### ISSUE THREAD

**Issue by vitexikora** [surveyjs/survey-creator#2414]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
See attached gif image that shows it clearly
![survey-creator-v2-bug](https://user-images.githubusercontent.com/14636323/146653674-895ed4c4-fdc7-46b5-b3dc-285eb88b7f64.gif)

### What is the expected behavior?
Editing the english language would trigger events just like editing the default one

### How would you reproduce the current behavior (if this is a bug)?
Create similar setup like in the image

#### Provide the test code and the tested page URL (if applicable)

Test code

```ts
import { SurveyCreatorComponent, SurveyCreator } from 'survey-creator-react'
import { settings, surveyLocalization } from 'survey-core'

settings.allowShowEmptyTitleInDesignMode = false
settings.allowShowEmptyDescriptionInDesignMode = false
surveyLocalization.supportedLocales = ['cs', 'en']
surveyLocalization.defaultLocale = 'cs'

const creatorOptions: any = {
      showToolbox: 'right',
      showPropertyGrid: 'right',
      showPageToolbox: false,
      showPageNavigator: false,
      showTranslationTab: true,
      showLogicTab: true,
      pageEditMode: 'single',
      haveCommercialLicense: true,
      isAutoSave: true,
      showState: false
}

creator = new SurveyCreator(creatorOptions)

return <SurveyCreatorComponent creator={creator} />
```

### Specify your

* browser: Firefox 95.0 (64-bit)
* editor version: survey-creator-react 1.9.2-beta.1, survey-core 1.9.2

**Comment by andrewtelnov** [comment]
@vitexikora Thank you for reporting the issue. We will take a look.

Andrew

**Comment by andrewtelnov** [comment]
@vitexikora The issue has been fixed in SurveyJS Library. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/3800).

Thank you,
Andrew
