### ISSUE TITLE
How to open properties grid of respective question on the right container onclick of question wrapper?

### ISSUE THREAD

**Issue by noddycha** [surveyjs/survey-creator#2418]
### Question
In the create-survey DEMO page on website ([https://surveyjs.io/create-survey](https://surveyjs.io/create-survey)), I see that clicking on the wrapper of the question opens up the properties grid. How is this implemented?

### Current behaviour
In my implementation of SurveyJS Creator in my project, I currently see a border on hovering this wrapper div. but, clicking it doesn't trigger properties grid

**Comment by tsv2013** [comment]
Answered here - https://surveyjs.answerdesk.io/ticket/details/t8405/how-to-open-properties-grid-of-respective-question-on-the-right-container-onclick-of
