### ISSUE TITLE
Why is JSONEditorTab available only when pageEditMode !== 'single' in Survey Creator React V2 ?

### ISSUE THREAD

**Issue by vitexikora** [surveyjs/survey-creator#2442]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
JSONEditorTab available only when pageEditMode !== 'single' 
See this code from compiled survey-creator-react:
![obrazek](https://user-images.githubusercontent.com/14636323/147125170-3da3aa51-693e-42e7-8a14-15c0c967ede1.png)

### What is the expected behavior?
JSONEditorTab should be always available

editor version: survey-creator-react 1.9.3-beta.1

**Comment by tsv2013** [comment]
In the `pageEditMode !== 'single' ` SurveyJS Creator removes the PagesEditor component. If you create multiple pages in JSON (via direct text typing) then all pages except the first one will not be available in creator.

**Comment by vitexikora** [comment]
Well, that is okay (expected), but why is the JSON editor disabled?

**Comment by tsv2013** [comment]
Because through JSON editor you can get inconsistent JSON - survey creator content will not be the same as you will see when run survey.

**Comment by vitexikora** [comment]
I understand, however it is really useful when you need to copy one survey definition to another, that is the primary usage.

**Comment by tsv2013** [comment]
You can get the `creator.text` or `creator.JSON` value

**Comment by Akkora** [comment]
I am facing the same issue in surveyjs-creator-knockout V2.

My requirements are to enable the Tab, but disable the the textarea like described here: https://surveyjs.answerdesk.io/ticket/details/t2301/disable-json-editor

I get why you want the editor to be not visible in single page edit mode, but when a dev configures it like this it should behave like this in my opinion:

```
pageEditMode: 'single',
showJSONEditorTab: true,
```

Also the [minimalistic configuration ​example](https://surveyjs.io/Examples/Survey-Creator?id=singlepage&platform=KnockoutjsV2&theme=modern#content-js) on the website says `// Show Designer, Test Survey, JSON Editor and additionally Logic tabs` but then hides the json editor.

**Comment by tsv2013** [comment]
See above commit. I've added an ability to ovveride this behavior. The `options.showJSONEditorTab === true` will show JSON editor tab in the single page mode
