### ISSUE TITLE
multi text question expand to the end of the page

### ISSUE THREAD

**Issue by alshehrio** [surveyjs/survey-creator#2472]
### Are you requesting a feature, reporting a bug or ask a question?
reporting a bug

### What is the current behavior?
when I add a multi-text question and click "Preview", all survey elements expands themself to the end of the page

### What is the expected behavior?
survey elements should have the same size as seen on the survey editor page

### How would you reproduce the current behavior (if this is a bug)?
1. add a multi-select question to any survey
2. go to the "Preview tab"
3. all elements should be expanded to the end of the page

#### Provide the test code and the tested page URL (if applicable)
[multi-select-bug.zip](https://github.com/surveyjs/survey-creator/files/7781159/multi-select-bug.zip)

Tested page URL:
[multi-select-bug.zip](https://github.com/surveyjs/survey-creator/files/7781159/multi-select-bug.zip)

Test code
[multi-select-bug.zip](https://github.com/surveyjs/survey-creator/files/7781159/multi-select-bug.zip)

### Specify your

* browser: chrome Version 96.0.4664.110 (Official Build) (64-bit) , firefox 95.0.1 (64-bit)
* editor version: survey-creator-react 1.9.3-beta.1

**Comment by tsv2013** [comment]
I've opened your example and it works ok for me:
![image](https://user-images.githubusercontent.com/3013415/154099329-f906992e-46ff-4310-91e0-7ea87124a296.png)

Do I miss something?

**Comment by dk981234** [comment]
Hello, 

We are currently unable to reproduce the issue. Here is an [example](https://plnkr.co/edit/JCkGJouUT3DNUw1m) that works fine.

Thanks,
Dmitry
SurveyJS Team
