### ISSUE TITLE
Disable pages in V2

### ISSUE THREAD

**Issue by Akkora** [surveyjs/survey-creator#2493]
### Are you requesting a feature, reporting a bug or ask a question?

I want to use the survey creator in single page mode only. So deleting a page, adding one or creating a duplicate should be hidden. I tried it with multiple properties, but all are not available in the V2 (survey-creator-knockout).
I got these properties from the documentation at the following two urls:
https://surveyjs.io/Documentation/Survey-Creator
https://surveyjs.io/Documentation/Survey-Creator?id=surveycreator

How can I disable the page functionality?

#### Test code

```
SurveyCreator({
      // all of these properties aren't working
      showPagesToolbox: false,
      pageEditMode: 'single',
      allowModifyPages: false
});

```

### Version

"survey-creator-knockout": "1.9.3-beta.1"

**Comment by andrewtelnov** [comment]
@Akkora Please review [the following example](https://surveyjs.io/Examples/Survey-Creator?id=singlepage&platform=KnockoutjsV2). It does what you need.

Thank you,
Andrew

**Comment by Akkora** [comment]
Thanks, so the solution is `pageEditMode: "single"`.
It just wasn't working for `1.9.3-beta.1`. After upgrading to `1.9.4-beta.1` it is working now. Thank you @andrewtelnov!
