### ISSUE TITLE
[V2] Creator checkbox UX

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#2499]
### Are you requesting a feature, reporting a bug or ask a question?
Bug / bad UX

### What is the current behavior?
![image](https://user-images.githubusercontent.com/547021/148555221-8ed7e8d0-be95-4da0-9726-a4aca76f1368.png)

This is not proper UX for a checkbox that enables something.
It is unclear what the current state is (obviously in the image the checkbox is not checked, but does that mean it is showing or hiding the title?)

### What is the expected behavior?
For booleans a toggle switch is way more intuitive. If a checkbox is used, the text should be affirmative so that it is clear what checking it does:
![image](https://user-images.githubusercontent.com/547021/148555692-54070190-c8c4-4636-b707-d9b9006dfc0e.png)
Still this UX is not the best.

Alternatively, just use the same UX you use for the width mode:
![image](https://user-images.githubusercontent.com/547021/148555418-96931ce3-9be4-4827-9078-d1b86232cb99.png)

**Comment by tsv2013** [comment]
We'll discuss this issue next week

**Comment by tsv2013** [comment]
We've discussed this proposal with the chief designer and decided not to change current behavior. Probably we'll return to this question after Creator V2 release.

**Comment by SamMousa** [comment]
I think this can be closed; since at least the text in my example has been updated:
![image](https://user-images.githubusercontent.com/547021/188080560-f66cc5c2-9959-4711-978a-944de52929e8.png)
