### ISSUE TITLE
[V2] Choices editor missing column headers

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#2501]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
![image](https://user-images.githubusercontent.com/547021/148559556-e540ffa1-8912-4f4d-bf47-486e08a3ddbe.png)

In v2 the choices editor no longer has columns header. While one could argue that for those 2 columns it is logical that it's `value | label`, this quickly breaks down when using a custom itemvalue type:

![image](https://user-images.githubusercontent.com/547021/148559726-46e93fca-7dd5-4d27-a48e-a976706e48e1.png)

### What is the expected behavior?
I'd expect to see column headers for clarity.

**Comment by tsv2013** [comment]
THis is the designed behaviour. We'll discuss it with out chief designer @mikeamelin

**Comment by tsv2013** [comment]
We've discussed this case and decided to implement the following behavior: if there are no custom columns, headers will not be shown; if collection editor has custom columns, headers will be visible. We'll implement this behavior after design will be created.

**Comment by tsv2013** [comment]
Design: https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=10957%3A97389
