### ISSUE TITLE
[V2] Add custom validator type in Creator panel

### ISSUE THREAD

**Issue by mhrabiee** [surveyjs/survey-creator#2502]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
It currently shows possible validation based on question type
![image](https://user-images.githubusercontent.com/600483/148637400-cf84b8b4-0777-4cd1-bd27-7ec7ef05ad40.png)

### What is the expected behavior?
Need to add some custom validation as built-in validation rules
![image](https://user-images.githubusercontent.com/600483/148637423-b184ac35-353c-4f96-a0fa-406f52aa95c9.png)

### Specify your
* editor version: v2 React

**Comment by andrewtelnov** [comment]
@mhrabiee You have to modify Survey.settings global variable, [Survey.settings.supportedValidators](https://github.com/surveyjs/survey-library/blob/master/src/settings.ts#L161).

Thank you,
Andrew

**Comment by mhrabiee** [comment]
> 

Thanks for quick response can you give me an example? I mean how can I register a function as a validator?

**Comment by andrewtelnov** [comment]
@mhrabiee You probably need "expression" validator with a [custom function](https://surveyjs.io/Documentation/Library#custom-functions).

Thank you,
Andrew
