### ISSUE TITLE
all the features will be disabled when disabling `allowEdit` for a question.

### ISSUE THREAD

**Issue by amira133** [surveyjs/survey-creator#2529]
### Are you requesting a feature, reporting a bug or ask a question?
BUG

can not Copy Question or Delete or ... when `allowEdit` is disabled.
you can replace my code with source code in this [example ](https://plnkr.co/edit/eTtZU98vcgqAhZLi?preview)

Test code

```
creator.onElementAllowOperations.add(function(sender, options) {
    if(options.obj.name === "question1") {
        options.allowDelete = true;
        options.allowEdit = false; //->>>>>>>>>>>>>>>>this is false ,others are true!!!!!!!!!!!!!!!!!!!!!
        options.allowCopy = true;
        options.allowAddToToolbox = true;
        options.allowDragging = true;
        options.allowChangeType = true;
        options.allowChangeRequired = true;
        options.allowShowHideTitle = true;
    }
});

```

### Specify your

* browser: Chorome :97.0.4692.71
* editor version: Vscode :lastest

**Comment by tsv2013** [comment]
The `allowEdit` here means that you can't change object properties. But copying or deleting ii are the other operations.

**Comment by amira133** [comment]
This means that it is not possible to move or delete the question if ‍‍‍‍`allowEdit` is disabled,
In other words, other properties depend on this value.

Therefore, if we want to disable the possibility of editing properties for the user, we must use `readOnly` It is true? 

`

     creator.onGetPropertyReadOnly.add(function(sender, options) {

        if(options.obj.name === "question1") {
    
            options.readOnly = true;
    
        }

    });
`

**Comment by tsv2013** [comment]
This means that it is allowed to move or delete the question if ‍‍‍‍allowEdit is false.

**Comment by amira133** [comment]
@tsv2013 but it seems they are disabled when `allowEdit` is false. see this gif:

![exmaple](https://user-images.githubusercontent.com/27830573/149779814-ef0596e7-f890-4f88-9510-c55962fae2ca.gif)

**Comment by tsv2013** [comment]
We'll check it

**Comment by tsv2013** [comment]
@amira133 Can you describe the exact business case you are trying to implement? Or you just want to inform us about some inconsistencies?

**Comment by amira133** [comment]
I just wanted to let you know about this problem. And I think this is a bug.
In fact, I was testing your product when I found this problem.

**Comment by amira133** [comment]
Do you have any plan to fix this bug?

**Comment by tsv2013** [comment]
As I wrote before - it is allowed to move or delete the question if ‍‍‍‍allowEdit is false.
Creator works this way since this functionality was inmplemented. I don't see any problems with it so do other our customers.
Thus this in not a bug and needn't to be fixed.

If I miss something please describe your issue in greater details or describe your business case.

**Comment by amira133** [comment]
@tsv2013  As you can see in the image below, all features are disabled after disabling `allowEdit`, including the ability to `delete` and `copy`.
The difference between `question 1` and `question 2` is that `allowEdit` is inactive and none of the operational icons (delete, copy, etc.) related to question 2 are displayed for question 1.


![image](https://user-images.githubusercontent.com/27830573/155853473-d05a74e8-d6cd-4ee4-9379-5e1c865b6bce.png)

**Comment by tsv2013** [comment]
Earlier question properties were edited in popup dialog. This popup dialog was shown if one press "Edit" button. The `allowEdit` option controlled this "Edit" button behavior. Now there is no popup properties window - you are using property grid instead. Thus the `allowEdit` option was left in favor of compatibility and does nothing in this moment.

**Comment by tsv2013** [comment]
I was wrong - allowEdit option disables all inline actions but property grid still allowed. This is an obsolete option and shouldn't be used right now.

**Comment by amira133** [comment]
Thanks tsv2013
Therefore, this feature should not be used.
You may update the documentation so that other people can use it.
Thanks
