### ISSUE TITLE
Creator window adaptivity to screen width

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#2534]
Let's imagine that we expanded creator window to full screen.
And we start to decrease the width of the window. Creator should change its view in following order:

1. Hide toolbox captions
2. Hide property grid
3. Hide toolbox icons
4. Decrease the width of survey
(now step 4 appears between 1 and 2 that is not correct)

Also we need to store the reason of property-grid collapse.
If property grid was collapsed by setting window width, it should be expanded if window ciome back to screen-wide size.
If property grid was collapsed by youser it should stay collapsed in any cases until user expand it manually.

And we need to center design surface without regard to the toolbox and page navigator

- [x] survey resise priority
- [x] property-grid collapsing states

separete issues created for:
-  #2549
-  #2548

**Comment by SamMousa** [comment]
@novikov82 is this issue also for this bug? 
![output](https://user-images.githubusercontent.com/547021/149932362-e5e60f3b-8dd9-4c47-9d29-5f4595596f48.gif)

**Comment by novikov82** [comment]
@SamMousa 
Thank you, we will keep in mind your message fixing this issue!
