### ISSUE TITLE
onAfterRenderPage callback does not have right HTML when adding new page in SurveyCreator

### ISSUE THREAD

**Issue by ZachIngle** [surveyjs/survey-creator#2541]
https://github.com/surveyjs/survey-library/commit/a433bfe66c9a3d7792451b8682016d73a46ba8cd

### Are you requesting a feature, reporting a bug or asking a question?

Bug

### What is the current behavior?

When adding a new a page in the SurveyCreator, I expect the page title element to exist in the `htmlElement` parameter of the callback to add some styling to it. As the page title does exist, styling cannot be added. The page element does exist after letting the callback run through and inspecting the page

### What is the expected behavior?

The page title element to exist when adding a new page and for it to exist in the `htmlElement` parameter of the `onAfterRenderPage` callback.

This behaviour changed when we upgraded from 1.8.55 to 1.8.78. I suspect this [commit](https://github.com/surveyjs/survey-library/commit/a433bfe66c9a3d7792451b8682016d73a46ba8cd) to be the issue

### How would you reproduce the current behavior (if this is a bug)?

With a SurveyCreator that has an `onAfterRenderPage` callback on the survey in the `onDesignerSurveyCreated` callback, add a new page to the Survey.

Test code

```
creator.onDesignerSurveyCreated.add((editor, options) => {
  options.survey.onAfterRenderPage.add((sender, { htmlElement }) => {
    htmlElement.querySelector('.sv_page_title').style.color = 'red';
  });
});
```

### Specify your

* browser: Chrome
* browser version: 97.0
* surveyjs platform (angular or react or jquery or knockout or vue): Knockout
* surveyjs version: 1.8.78

**Comment by andrewtelnov** [comment]
@ZachIngle We changed the way we edit Page title several versions ago. The correct code will be the following:
```js
creator.onDesignerSurveyCreated.add((editor, options) => {
  options.survey.onAfterRenderPage.add((sender, { htmlElement }) => {
    htmlElement.querySelector('.title_editable').style.color = 'red';
  });
});
```
Here is [the example](https://plnkr.co/edit/OZDJ7FimDMfZTxfQ).

If you need to change the style only, then the better approach to use CSS rules:
```css
.svd_page h4 {
  color: red;
}
```
Here is [the example](https://plnkr.co/edit/iTePRdvjqwRW21mS).

Regarding V2. I would suggest to check SurveyJS Creator V2 for React. It doesn't mean that you have to move immediately of course. We believed V2 is way better technically and from UI point of view.  

Thank you,
Andrew
