### ISSUE TITLE
Choices items alignment and drag icon color

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#2556]
- [x] drag-drop icon should be gray, not green (see https://github.com/surveyjs/survey-creator/issues/2556#issuecomment-1017266625)
- [x] red-iconed None/Other/SelectAll items should be correctly aligned
- [x] create screenshot test!

![image](https://user-images.githubusercontent.com/29385489/150183075-3af21adb-0f72-41ab-ad1d-d4f6afe03678.png)

**Comment by dmitrykurmanov** [comment]
in fact we have two colors for drag icon:

- green (ranking): https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=3430%3A38002
- gray (creator choices dnd):  https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=3430%3A38004
