### ISSUE TITLE
License banner adjust

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#2557]
Maybe best option is to make banner be added to bottom without covering ather creator items.

![image](https://user-images.githubusercontent.com/29385489/150184328-662b48dc-184e-43b7-a7a0-8bc51d1049d3.png)
![image](https://user-images.githubusercontent.com/29385489/150184347-f5a5f74c-986b-4541-833f-1b1b8b5399cd.png)
![image](https://user-images.githubusercontent.com/29385489/150184383-8a111046-25a1-4e1a-a261-b6bcd6ad2fae.png)

Matrixdynamic in preview tab and license footer #2592

**Comment by tsv2013** [comment]
Take in account mobile layout
See the https://surveyjs.answerdesk.io/ticket/details/t8676/hide-toast-notification-snackbar-info-of-surveyjs-creator
@dk981234  Please check the case
