### ISSUE TITLE
Strange behaviour of Rate Values edit button

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#2562]
![image](https://user-images.githubusercontent.com/29385489/150190816-c11569fe-bab4-447d-91e7-cc6ee1d50aac.png)

**Comment by OlgaLarina** [comment]
Add placeholder

**Comment by novikov82** [comment]
@RomanTsukanov 
I implemented it with placeholder, what do you think about this solution?
![image](https://user-images.githubusercontent.com/29385489/151006659-c7bd1a6d-f566-4179-af15-177a3bcb1d6d.png)

**Comment by RomanTsukanov** [comment]
@novikov82 Looks fine
