### ISSUE TITLE
CV2: ImageLink property should be for image picker only in ChoicesByUrl object

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#2564]
There is an opinion that _Image link name_ doesn't make sense for _Choices_
![image](https://user-images.githubusercontent.com/29385489/150289761-0d7d40de-1a92-4d54-bc6c-5706afb46b00.png)

**Comment by tsv2013** [comment]
SurveyJS Creator V2 doesn't respect "visibleIf" property from metadata.

**Comment by tsv2013** [comment]
The `onQuestionCreated` (https://github.com/surveyjs/survey-creator/blob/master/packages/survey-creator-core/src/property-grid/index.ts#L466-L493) method is not called for the inner questions of a composite question created for the `choicesByUrl` property (`choicesRestful` object)
