### ISSUE TITLE
"Default Value" not reflecting changes to question element on property change from question editor modal.

### ISSUE THREAD

**Issue by KishorMandve** [surveyjs/survey-creator#2596]
Survey creator version = 1.8.78

I have added Default value property to my survey as survey js does not provide it directly.
I have added this property using
Survey.Serializer.addProperty method

But when I edit a question element from question editor modal and click ok then changes made for default value are reflecting to the survey JSON.
But question element shows old default value.

After this when I open modal again then question element shows the new default value.

So is there any way to change default value for question element just after click OK or APPLY from question editor modal ?

Please help....

**Comment by tsv2013** [comment]
Can you share a minimal working example illustrating the issue?

**Comment by KishorMandve** [comment]
Hi @tsv2013, 

Issue is very simple.

I have added a "default value" custom property to question element as mentioned in this documentation :- https://surveyjs.io/Documentation/Survey-CreatorSinglePage?id=Build-Component-Questions#add-property-example

And this property is working fine and reflecting Default value changes in JSON.

To eloborate issue here is an instance,
1. I have added a new single input question.
2. Clicked on question element and then clicked on edit icon.
3. Then question editor modal will appear.
4. I have set default value(custom property) and clicked OK button of modal.
5. When I have checked JSON editor i found new default value.
6. But same time my question element showing value as blank.
7. Then again I have opened question editor modal and found that question element is showing default value as value attributes of input tag.


So, whenever I change the default value it is changing in modal and JSON but not changing in question element. 

Question element value is updating when I click on edit question icon.

So, is there any way to update question element value as I change default value in question editor modal?

Thanks

**Comment by dmitrykurmanov** [comment]
Could you please open the creator from site's examples in CodeSandbox/plunker and modify it to reproduce the problem?

Here the codesandbox example: https://codesandbox.io/s/g8eul also

**Comment by KishorMandve** [comment]
Please find below plunker example link:-
https://plnkr.co/edit/bYWQWRamDXWoWVkx

I have added "defaultValue" as custom property.

but when I change default value from question editor modal it's not changing on survey designer after closing modal.

but when I open question editor modal it is updating default value for question element in survey designer.

please help if I am missing any thing.

**Comment by dmitrykurmanov** [comment]
we will check it asap

**Comment by dmitrykurmanov** [comment]
it seems that the problem in the typo, after the switching `surveyCreator.on...` with the `creator.on` it looks ok.

here is [the updated example](https://plnkr.co/edit/5EqkipydoOYpxBjd)

PS I would suggest you to use our default `defaultValue` because it is [a bit more complex](https://github.com/surveyjs/survey-library/blob/0ee0635d93bbe0ac182f07168d9e7889d5b4602f/src/question.ts#L1220) than just property
