### ISSUE TITLE
How to correctly update existing property

### ISSUE THREAD

**Issue by pelshen** [surveyjs/survey-creator#2599]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
I want to update the visibleIf function for the `choices` property as I am adding a new property to be used instead of the `choicesFromQuestion` property; so if my new property is used, I want the `choices` property to be invisible. I'm able to do this by using
```
var choices = Survey.Serializer.getProperty("dropdown", "choices");
choices.visibleIf = <new function>;
choices.addDependedProperty("<new property>");
```
However just the first line of this causes the choices property to break. The visibleIf actually does work correctly though. In the plunker I've just put the getProperty line to shown the minimum required to break the choices proeprty. I've tried using `addProperty` instead, but this causes the same issue.
```
Survey
  .Serializer
  .addProperty("dropdown", {
    name: "choices",
    dependsOn: ["<new property>"],
    visibleIf: <new function>
  });
```

### What is the expected behavior?
That updating an existing property wouldn't cause that property to render incorrectly. But perhaps there is a different to update properties?

### How would you reproduce the current behavior (if this is a bug)?
See plunker.
`var choices = Survey.Serializer.getProperty("dropdown", "choices");` is all that's needed.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/WhuECcLrZE45AYvI?preview

Test code
see plunker

### Specify your

* browser: Chrome
* editor version: 1.9.7-beta.1

**Comment by tsv2013** [comment]
You need to remove the original property first:
```JS
Survey.Serializer.removeProperty("class", "propertyName");
```

**Comment by pelshen** [comment]
But I don't want to lose all the existing configuration for choices, I just want to change the `visibleIf` and `dependsOn`. If I removed it first, wouldn't all that be lost?
Also, surely it's a bug that just calling `getProperty` causes the display to mess up?

**Comment by novikov82** [comment]
@pelshen 
It seems like that `getProperty` function looses the type definition for property. We are going to fix it, but I found a workaround:
You just need to add 
```js
choicesQuestion.type = "itemvalues";
```
and correct editor will be back.

Full example is here - https://plnkr.co/edit/yeqAZgaUo9Olsek9

**Comment by novikov82** [comment]
@pelshen
Another option is to set isArray field of the property
```js
choicesQuestion.isArray= true;
```
I made a pullrequest for it, you can track it if you want. After merge it will be available in release.

**Comment by pelshen** [comment]
My code is now working, by using `addProperty`, as above. Once your change is in, I might switch back to getting the property and updating it that way. Thanks for fixing the underlying issue here.
