### ISSUE TITLE
How to register another property editor

### ISSUE THREAD

**Issue by pelshen** [surveyjs/survey-creator#2607]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
I want a property to refer to another question, basically, exactly like the `choicesFromQuestion` property in existing `selectbase` questions, but in this case I want the list to be of just matrixdynamic questions. In the code I found `packages/survey-creator/src/propertyEditors/propertyEditorFactory.ts` and wanted to create my own editor class like the ` SurveyQuestionSelectBasePropertyEditor`, which I would also extend from `SurveyQuestionPropertyEditor`, but can't work out how to import the latter in my code to do this. I've tried like this, but I get a `Uncaught TypeError: Class extends value undefined is not a constructor or null` from it.
```
import * as SurveyCreator from 'survey-creator-react';

export class SurveyQuestionMatrixDynamicPropertyEditor extends SurveyCreator.SurveyPropertyEditorBase {
  get editorType() {
    return "question_matrixdynamic";
  }
  getQuestions(survey) {
    var questions = survey.getAllQuestions();
    var res = [];
    for (var i = 0; i < questions.length; i++) {
      if (questions[i] === this.object) continue;
      if (this.isMatrixDynamicQuestion(questions[i])) {
        res.push(questions[i]);
      }
    }
    return res;
  }
  isMatrixDynamicQuestion(question) {
    return question.getType() === "matrixdynamic";
  }
}
```

Maybe this example https://surveyjs.io/Examples/Survey-Creator?id=ckeditorpropertyeditor&platform=ReactjsV2&theme=bootstrap#content-js is relevant, but I can't quite work out how, as what I've got above feels quite simple.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* editor version: 1.9.7-beta.1 (React)

**Comment by novikov82** [comment]
@pelshen 

Unfortunatly classes that implements property-grid editors are not exported to package and can not be overriden in your application.

I don't know your exact goals but I tried to do it this way:
https://plnkr.co/edit/zXZAD6k2C5Q2Pb2X

```js
// add new property
Survey.Serializer
    .addProperty("selectbase", {
        name: "choicesFromQuestionFiltered",
        type: "question_selectbase_filtered",
        category: "choices"
    });

// clone property editor
var oldEditor = SurveyCreator.PropertyGridEditorCollection.getEditor(Survey.Serializer.findProperty("selectbase", "choicesFromQuestion"));
const newEditor = Object.create(oldEditor);

// patch editor functions
newEditor.fit = function (prop) {
    return prop.type == "question_selectbase_filtered";
  }
newEditor.getQuestions = function (survey) {
    var questions = survey.getAllQuestions();
    var res = [];
    for (var i = 0; i < questions.length; i++) {
      if (questions[i] === this.object) continue;
      if (questions[i].getType() === "matrixdynamic") {
        res.push(questions[i]);
      }
    }
    return res;
}

// register new editor
SurveyCreator
    .PropertyGridEditorCollection
    .register(newEditor);
```

**Comment by pelshen** [comment]
This exactly does what I need, thank you!
