### ISSUE TITLE
CKEDITOR as property editor

### ISSUE THREAD

**Issue by dipen211** [surveyjs/survey-creator#2625]
### Are you requesting a feature, reporting a bug or ask a question?
question:- I want to add custom created template in ckeditor default templates, i am using it in surveycreator but not able to add this in surveycreatorv2

### What is the current behavior?
ckeditor templates
![image](https://user-images.githubusercontent.com/46180692/151954659-16ad596f-8d40-498a-a10d-9d44899a7268.png)

### What is the expected behavior?

![image](https://user-images.githubusercontent.com/46180692/151955250-08dabac1-62d9-4e29-80c9-4fb2588116b6.png)

**Comment by tsv2013** [comment]
Can you share a minimal example illustrating the issue?

**Comment by dipen211** [comment]
https://codesandbox.io/s/amazing-platform-oz3vl

this created from surveycreator..

![image](https://user-images.githubusercontent.com/46180692/152355149-75d45756-f89b-4a62-ac0c-84f26e3c3b7d.png)

in this screenshot you can see template with name completed page.

how can i implement this in surveycreatorv2.

**Comment by andrewtelnov** [comment]
@dipen211 Here is the [working example](https://codesandbox.io/s/amazing-driscoll-6qw40?file=/src/SurveyCreatorComponent.jsx).

Thank you,
Andrew

**Comment by dipen211** [comment]
Thank you @andrewtelnov for your response

but what i am asking is all about ckeditor template.
in this example you show how add ckeditor as editor...

but what my question is how add custom template

**Comment by tsv2013** [comment]
>But what my question is how add custom template like below in ckeditor template

CKEDITOR is a 3rd party product not related to SurveyJS. You need to ask questions related to CKEDITOR functionality on the appropriate resorces (CKEDITOR official site, support forum etc.)

**Comment by dipen211** [comment]
yes @tsv2013  thank you for response....

we can add custom created template in ckeditor template 

but what my question is..... how...???

in your old survey creator version we have way to add template in ckeditor, we have option for that by change of few line of code...
here i put snapshot of code for explaining my question 
in below ss i addtemplate and by that variable CkEditor_ModalEditor i can add it in ckeditor in surveycreator....
is there any way with v2...?? we can create somthing like this variable and implement ckeditor template in surveycreator editor ..?

![image](https://user-images.githubusercontent.com/46180692/154075445-b75dcd92-a727-4c28-ab0c-37ddc4ca5dfd.png)


Thank you..

**Comment by dipen211** [comment]
Solved..
