### ISSUE TITLE
v2 - Translation tab still interactive in readOnly mode

### ISSUE THREAD

**Issue by dsimon-onventis** [surveyjs/survey-creator#2653]
### Are you requesting a feature, reporting a bug or ask a question?

Bug report for v2

### What is the current behavior?

When setting `readOnly` to `true`, I'm still able to work with the Translation tab, e.g. add new languages or maintain translations.

### What is the expected behavior?

When setting `readOnly` to `true`, no changes can be made in the Translation tab.

### How would you reproduce the current behavior (if this is a bug)?

1. enable translation tab
2. enable readOnly mode

### Specify your

* browser: Chrome 98
* editor version: 1.9.8-beta.1

**Comment by dsimon-onventis** [comment]
@andrewtelnov This issue is not fixed, the translation tab is still interactive in 1.9.10-beta.1. Could you re-open?

**Comment by andrewtelnov** [comment]
@dsimon-onventis It works for me. Here is [the example](https://codesandbox.io/s/fervent-leaf-407j9?file=/src/SurveyCreatorComponent.jsx).

Thank you,
Andrew

**Comment by dsimon-onventis** [comment]
@andrewtelnov I enabled the translation tab and it is interactive. https://codesandbox.io/s/cool-tesla-d5y4k?file=/src/SurveyCreatorComponent.jsx

![image](https://user-images.githubusercontent.com/68286501/153205157-9d19893e-c620-4f41-84d4-c87c458dc851.png)
