### ISSUE TITLE
survey-creator-knockout 1.9.9-beta.1 npm package install fails

### ISSUE THREAD

**Issue by dsimon-onventis** [surveyjs/survey-creator#2664]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

`npm install survey-creator-knockout@1.9.9-beta.1` fails with:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for survey-creator-core@^1.9.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

`survey-creator-core` doesn't exist in a stable version, so `^1.9.0` can not be fulfilled.

**Comment by dmitrykurmanov** [comment]
we are working on the fix and will release a new version as soon as possible.

Thanks

**Comment by dmitrykurmanov** [comment]
the fix https://github.com/surveyjs/survey-creator/commit/7e6b5d59f9bb5a043a2f79174572bbb9ed5904f9

**Comment by dmitrykurmanov** [comment]
@dsimon-onventis `npm install survey-creator-knockout@1.9.10-beta.1` works now
