### ISSUE TITLE
V2: Improve usability of inline edit

### ISSUE THREAD

**Issue by Akkora** [surveyjs/survey-creator#2675]
### Are you requesting a feature, reporting a bug or ask a question?

Feature improvement

### What is the current behavior?

When inline editing in creator V2, it is hard to jump to a special place in string with the mouse. This is handy for fixing a typo or changing the field in general. Only when using the keyboard I succeeded.
I made a little screen record of that.

https://user-images.githubusercontent.com/10886924/153589626-a6bada9c-c692-417f-bbae-5dd0cbda7a41.mp4

### What is the expected behavior?

Click on a field should enable inline edit and select the content. A second click should jump at the position in the string, where you click.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/create-survey-v2

### Specify your

* browser: Chrome 98
* editor version: 1.9.12

**Comment by andrewtelnov** [comment]
@Akkora The common scenario, when a user want to change the current title text with the new one. To fix typo, a user has to go to edit mode for a title and then click one more time to the symbol she wants to change, or use keyboard.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Akkora It looks like a bug to me. It works for [react version](https://surveyjs.io/Examples/Survey-Creator?id=real-nps&platform=ReactjsV2&theme=bootstrap), where I have checked, but it doesn't work for [knockout version](https://surveyjs.io/Examples/Survey-Creator?id=real-nps&platform=KnockoutjsV2).

Thank you,
Andrew
