### ISSUE TITLE
V2: Empty configuration window style

### ISSUE THREAD

**Issue by Akkora** [surveyjs/survey-creator#2696]
### Are you requesting a feature, reporting a bug or ask a question?

style improvement

### What is the current behavior?

If the configuration tab contains no messages, the text is there without padding

![image](https://user-images.githubusercontent.com/10886924/154444787-2510fe84-1747-4a1d-8ede-e909ed3e9664.png)

### What is the expected behavior?

Padding should be added to the text.

In this example, I added 16px of padding to the `spg-body--empty` class.

![image](https://user-images.githubusercontent.com/10886924/154444978-5d130f7f-f5df-474d-9254-6bc330ca2dbd.png)

### How would you reproduce the current behavior (if this is a bug)?

1. Open SurveyJS Creator with [minimalistic example](https://surveyjs.io/Examples/Survey-Creator?id=singlepage&platform=KnockoutjsV2&theme=bootstrap)
2. Add a question
3. Change menu top right to page1

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Examples/Survey-Creator?id=singlepage&platform=KnockoutjsV2&theme=bootstrap

### Specify your

* browser: Chrome 98
* editor version: 1.9.13

**Comment by dmitrykurmanov** [comment]
fixed via the https://github.com/surveyjs/survey-creator/commit/701a7ccf9327e87f62dc0e89d1723c4307ee73c4
