### ISSUE TITLE
Logic tab issues

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#2717]
- [x] padding between actions & conditions
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=7994%3A51953
![image](https://user-images.githubusercontent.com/21283706/155681477-3fc4afc5-6123-4544-9737-1e9e14613f66.png)
- [x] "Add new rule" button disabled if new rule doesn't saved
- [x] hover & focus states of expand buttons conflict with each other

**Comment by wb-ts** [comment]
When I integrate SurveyJs to React web application , I can't see the "Add New Rule" button to customize the flow of the survey even clicked Logic which was shown on the top bar.
https://prnt.sc/ITBNjpKjET5L
