### ISSUE TITLE
V2: fix popup styles in toolbox  

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#2727]
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SurveyJS?node-id=9414%3A51795

- [ ] fix shadow
- [ ] fix corner rounding
- [ ] check styles in safari

**Comment by dk981234** [comment]
![image](https://user-images.githubusercontent.com/21283706/159689463-9a1d393e-d1fa-4078-8f20-2331204095b7.png)
Corners are not rounded
