### ISSUE TITLE
Bundle size is too large when importing.

### ISSUE THREAD

**Issue by conor-lacey** [surveyjs/survey-creator#2731]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
I think that the development files and not the `.min.js` files are being imported from 'survey-react' and 'survey-creator-react'.

### What is the expected behavior?
That only the relevant `*.min.js` files are imported by default.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/s/epic-hill-2py3ks
The closest I can get to replicating this in an online example is in a Codesandbox, check the network tab at the below URL and sort by file size. The largest is around 19mb.

Test code

```
import {
  SurveyCreatorComponent,
  SurveyCreator
} from 'survey-creator-react';

import { Survey, Model } from 'survey-react';
```

### Specify your

* browser: N/A
* browser version: N/A
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.9.0

**Comment by tsv2013** [comment]
In v1.9.9 we extracted localization texts from survey-core and survey-creator-core. Also survey survey-creator-core was extracted from survey-creator-react bundle. Please check the latest version 1.9.18

**Comment by conor-lacey** [comment]
@tsv2013 Thanks, I updated the [CodeSandbox](https://codesandbox.io/s/dreamy-shtern-dcoym9) to use 1.9.18 and the largest file size is now around 11mb, but that is still quite large.

Could you confirm that using `import { SurveyCreatorComponent } from 'survey-creator-react';` imports the minified versions?

**Comment by dmitrykurmanov** [comment]
@conor-lacey I think it is just how CodeSandbox works. Please check our real bundle sizes at unpkg:

https://unpkg.com/browse/survey-creator-core@1.9.18/
https://unpkg.com/browse/survey-creator-react@1.9.18/

our libs are quite big but not 10-20mb.

Please also check the CodeSandbox network:
![image](https://user-images.githubusercontent.com/22315929/155705396-5d02b488-8b23-4cab-8afd-8b9f5c2257a0.png)

![image](https://user-images.githubusercontent.com/22315929/155705630-f15538bb-433a-4dee-b48e-73ee9db41d5e.png)

it seems that it is not our bundle in fact

**Comment by dmitrykurmanov** [comment]
But probably you are right about importing minified version by default. We will investigate it and write back as soon as possible.

**Comment by dmitrykurmanov** [comment]
Here the [SO question](https://stackoverflow.com/questions/48673408/should-javascript-npm-packages-be-minified) about it. So the common answer that npm package `main` section shouldn't link to minified file:

> For consumption through a dev environment that uses a bundler in its build pipeline your package is best not minified. In most cases package consumers do implement their own minification process as part of their builds. Moreover, when providing your package in a module format for example:

**Comment by tsv2013** [comment]
@Some bundlers can't process minified code files e.g. when they minify your bundle. That's why we don't want to do it by default.

**Comment by conor-lacey** [comment]
Hi @tsv2013,  @dmitrykurmanov, I'm trying to update my local setup to use v1.9.18 as recommended, but I'm getting the following error when I try to import `SurveyCreatorComponent` and `SurveyCreator`:

`survey_core__WEBPACK_IMPORTED_MODULE_1__.SvgRegistry is undefined`

I checked the webpack output, and I can see this error:
`[build:css] Error: Failed to find 'survey-creator-react/survey-creator-react.min.css'`

I have `"survey-creator-react": "1.9.18"` listed in my package.json, so I checked the node_modules directory but there's no CSS file there, and I can see there's no CSS files listed in [unpkg](https://unpkg.com/browse/survey-creator-react@1.9.18/), is this missing from the build or do I import it from somewhere else?

**Comment by conor-lacey** [comment]
Looks like the CSS file was available in https://unpkg.com/browse/survey-creator-react@1.9.8-beta.1/ but removed in later versions.

**Comment by tsv2013** [comment]
@conor-lacey Please check this example - https://codesandbox.io/s/w74lut?file=/src/SurveyCreatorComponent.jsx

**Comment by conor-lacey** [comment]
Hi @tsv2013, I've checked those examples and I'm using the same versions (1.9.18). I've added those 3 additional imports, although they show up as unused.

The error I'm getting is 
```
TypeError: survey_core__WEBPACK_IMPORTED_MODULE_1__.SvgRegistry is undefined
    doRender survey-react-ui.js:3453
```
The corresponding line 3453 in `survey-react-ui.js` is 
```
Survey.prototype.doRender = function () {
        survey_core__WEBPACK_IMPORTED_MODULE_1__["SvgRegistry"].renderIcons();
```
FWIW, here are some screenshots of the error:

| Console error        | survey-react-ui.js:3453  |
| ------------- |:-------------:|
|   ![Screenshot 2022-02-28 at 08 50 29](https://user-images.githubusercontent.com/31271520/155953588-83511866-1bf4-4d63-8ab4-869c8efe6e86.png)   | ![Screenshot 2022-02-28 at 08 51 09](https://user-images.githubusercontent.com/31271520/155953646-0d8d70f5-bb46-4f34-82c4-4a6f4bbda432.png) |


The error with the CSS file is resolved, we were importing it in a local CSS file but if it's no longer necessary then we can remove it.

**Comment by tsv2013** [comment]
Can you fork the https://codesandbox.io/s/w74lut?file=/src/SurveyCreatorComponent.jsx example to illustrate the issue?

**Comment by jburghardt** [comment]
I think this is still relevant, in production the minified version should be imported.

the main file, for example, in the creator-core-react links to

`"main": "survey-creator-react.js"`

if we have a look at the react package, the main file links to an index.js which exports the min file dependening on the enviornment. 

```
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react.production.min.js');
} else {
  module.exports = require('./cjs/react.development.js');
}
```

see https://github.com/facebook/react/blob/main/packages/react/package.json

maybe this can be implemented to drastically reduce size ?
