### ISSUE TITLE
Translations ​​have disappeared in version 1.9.18

### ISSUE THREAD

**Issue by KilianCalmedica** [surveyjs/survey-creator#2750]
### Are you requesting a feature, reporting a bug or ask a question?
A bug

### What is the current behavior?
Only EN language is usable in v. 1.9.18

### What is the expected behavior?
I want to set the creator to FR, but only EN translation is working.

### How would you reproduce the current behavior (if this is a bug)?
`Survey.surveyLocalization.defaultLocale = 'fr';` throw an error

### Specify your

* browser: Google Chrome

**Comment by andrewtelnov** [comment]
@KilianCalmedica Please add into import localization strings:
```js
import "survey-core/survey.i18n.js";
import "survey-creator-core/survey-creator-core.i18n.js";
```
We moved localization strings from the package before making the final release of Creator V2.

Thank you,
Andrew

**Comment by KilianCalmedica** [comment]
Thanks, it's work with these imports.
