### ISSUE TITLE
V2: Survey Creator HTML field - text overflows editing box

### ISSUE THREAD

**Issue by cnaum** [surveyjs/survey-creator#2795]
### Are you requesting a feature, reporting a bug or ask a question?

Bug.

### What is the current behavior?

When creating/editing an HTML field in the V2: survey creator the text expands outside the container.  Please see attached images

### What is the expected behavior?

Text contained in editing and viewing box.

### How would you reproduce the current behavior (if this is a bug)?

Create a new survey using SurveyJS site i.e. - https://www.surveyjs.io/Service/EditSurvey

Create HTML field

Type a long text field. i.e. - Example of HTML that expands outside of box in V2: Survey creator. Example of HTML that expands outside of box in V2: Survey creator. etc.....

#### Provide the test code and the tested page URL (if applicable)

https://www.surveyjs.io/Service/EditSurvey/777e0514-1020-4ff9-a831-b8f9dfa7d4eb

Tested page URL:

https://www.surveyjs.io/Service/EditSurvey/777e0514-1020-4ff9-a831-b8f9dfa7d4eb

Test code

```
{
 "logoPosition": "right",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "html",
     "name": "question1",
     "html": "Example of HTML that expands outside of box in V2: Survey creator.    Example of HTML that expands outside of box in V2: Survey creator"
    },
    {
     "type": "text",
     "name": "question2"
    }
   ]
  }
 ]
}
```

### Specify your

* browser: Edge (latest)
* editor version:

Edit View overflow...
<img width="622" alt="Screenshot 2022-03-11 084917" src="https://user-images.githubusercontent.com/65997208/157902430-132e7a72-1672-4a88-844c-7c39d5af1a5f.png">

Preview View overflow...
<img width="803" alt="Screenshot 2022-03-11 085021" src="https://user-images.githubusercontent.com/65997208/157902458-ea2bdad0-b0da-4746-b4db-eb2de8329ed5.png">

Run survey renders correctly....
<img width="316" alt="Screenshot 2022-03-11 085101" src="https://user-images.githubusercontent.com/65997208/157902472-7fe287ee-f7fb-44a8-8346-b5f9b1d9eaf4.png">

**Comment by novikov82** [comment]
fixed with https://github.com/surveyjs/survey-library/pull/4115
