### ISSUE TITLE
Bug : onQuestionAdded callback firing when moving a question SurveyCreator V2

### ISSUE THREAD

**Issue by qcnguyen** [surveyjs/survey-creator#2803]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug.

### What is the current behavior?
When you drag a question to reorder it in a page, the onQuestionAdded callback is fired. Even if technically, you didn't add a question but only move one.

### What is the expected behavior?
The callback shouldn't be fired. 

The problem is that right now I use this callback to perform some actions that shouldn't occur when a question is moved.

Thanks!

How would you reproduce the current behavior (if this is a bug)?
See pen below.
https://plnkr.co/edit/wvBo04G8dGoJkuTh

**Comment by novikov82** [comment]
Fixed via this issue - https://github.com/surveyjs/survey-library/issues/4151
