### ISSUE TITLE
Creator V2: showState property doesn't have an effect

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#2805]
In [README](https://github.com/surveyjs/survey-creator/blob/master/packages/survey-creator-knockout/README.md#use-with-vue), we mention a not-yet-documented `showState` property. Changing it doesn't have an effect:

https://codesandbox.io/s/confident-hill-m25q9y?file=/src/SurveyCreatorComponent.jsx

**Comment by andrewtelnov** [comment]
@RomanTsukanov I have removed this property. It is obsolete in V2.

Thank you,
Andrew

**Comment by RomanTsukanov** [comment]
`showState` is removed from the docs (#2816). I'm closing this issue.
