### ISSUE TITLE
V2: Categorized items become unreachable after the toolbox switches to compact mode

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#2838]
[Screencast](https://devexpress-my.sharepoint.com/:v:/p/roman_tsukanov/ETP-wOECAlpAtIDZWDsvuisBxs613Rmqhfpi9XQhqgv_RQ?e=Tbc41x)
[Test project](https://github.com/surveyjs/survey-creator/files/8362530/categorized-toolbox-adaptability-issue.zip)

**Comment by OlgaLarina** [comment]
https://github.com/surveyjs/survey-creator/pull/2862
