### ISSUE TITLE
Warning: Cannot update during an existing state transition

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#2847]
https://codesandbox.io/s/hidden-wind-qhh3vb

Steps to reproduce:

1. Open the console
1. Click the Add New Survey button
1. Click Add Question in Survey Creator

**Comment by andrewtelnov** [comment]
@tsv2013 You need to remove emptySurveyJSON constant and the following line:
`this.creator.JSON = !!json ? json : emptySurveyJSON;` should be `this.creator.JSON = json;` to reproduce the issue.

Thank you,
Andrew
