### ISSUE TITLE
Logic tab: Dropdown editors display items that cannot be selected

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#2896]
For instance, the following screencast shows a numeric `nps_score` question that doesn't accept `contains` and some other operations. It makes sense because these operations are valid only for string question, but in this case why are they on the list? We need to filter the drop-down values.

https://www.screencast.com/t/vXoQM4qe

**Comment by OlgaLarina** [comment]
replace the editor when this [issue ](https://github.com/surveyjs/survey-library/issues/3840)was implemented.
