### ISSUE TITLE
Dropdown: Move new Items (React only)

### ISSUE THREAD

**Issue by JanUlrichR** [surveyjs/survey-creator#2898]
### Are you requesting a feature, reporting a bug or ask a question?
This is a bug report, noticed in dropdowns in surveys in the creator v2.

### What is the current behavior?
You can not move new Items in a dropdown added by clicking on the green plus sign until you switch tabs back and fourth. Also, when another item is moved to the space of the newly created item, it can also not be moved. 

### What is the expected behavior?
You can move newly created items

### How would you reproduce the current behavior (if this is a bug)?

1. Open a new survey in creator v2 for example: [https://www.surveyjs.io/Examples/Survey-Creator#content-result](https://www.surveyjs.io/Examples/Survey-Creator#content-result)
2. Add a dropdown question
3. Add new item by clicking on the green plus sign
4. Try to move the new created item like the other ones. (This is not possible, but should)
5. (Move another item to the space of the new item)
6. (Try to move the item on the space of the new item, this is also not possible)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://www.surveyjs.io/Examples/Survey-Creator#content-result

### Specify your

* browser: firefox
* editor version: 98.0.2

**Comment by andrewtelnov** [comment]
@dmitrykurmanov Please take a look to this one.

Thank you,
Andrew
