### ISSUE TITLE
Separate model, platform independent code, from knockout. 

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#29]
Refactor code, to allow implement the react version of editor.

**Comment by ppatel890** [comment]
Hi, I was wondering what timeline you guys were thinking of for releasing a react version of surveyjs editor? Thank you for continuing to updating both libraries, they have been great to use!

**Comment by andrewtelnov** [comment]
@ppatel890 I have spent couple days on this task. I understood that it would take more than I have expected and decided to postponed this task for a while.
Do you have any issue with including the current version into your project?

Thank you,
Andrew

**Comment by tsv2013** [comment]
You can check SurveyJS Creator V2 beta live demo on our site - https://surveyjs.io/Examples/Survey-Creator?id=options&platform=ReactjsV2
