### ISSUE TITLE
MacOS: Chrome: Icons Quality Issue

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-creator#2936]
actual:
![image](https://user-images.githubusercontent.com/22315929/164197223-0cefb535-d93e-4883-9328-22120c3dc75f.png)

etalon(windows): 
![image](https://user-images.githubusercontent.com/22315929/164197613-eab7a462-d84a-485d-8288-bafab523d6f9.png)

**Comment by mikeamelin** [comment]
Looks like nobody care about it. Many sites have the same issue.
