### ISSUE TITLE
How to change the Text property localization text for a choice in Image Picker

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#2939]
![image](https://user-images.githubusercontent.com/18551316/164223206-107d5eac-f391-4897-920c-33c2e4260565.png)

**Comment by andrewtelnov** [comment]
@RomanTsukanov You can do it in Translation tab or you can change the survey locale and then start to edit text properties.
For example if you change the survey locale to "de", all changes will be in JSON as the following:
```js
text: {
 default: "Your text in English",
 "de": "Your text in Deutsch"
}
```
If there is no text for other locale except default, then the JSON will be: `text: "Your text in English"`.

Thank you,
Andrew
