### ISSUE TITLE
plan for Angular project to independent of  `Knockout`?

### ISSUE THREAD

**Issue by amira133** [surveyjs/survey-creator#2943]
Hello
What is your team's plan to make the Angular project independent of  `Knockout` like React Version?

Thank you

**Comment by tsv2013** [comment]
Yes, we have plans to implement the "survey-angular-ui" library with the "native" Angular components in the nearest half-year but I can't promise anything here. We already perform some investigations.

**Comment by amira133** [comment]
Thank you

**Comment by amira133** [comment]
@tsv2013 There is no new news in this regard?
We want to plan in this regard.
thanks

**Comment by JaneSjs** [comment]
Hello @amira133,
In recent versions, you can enable native Angular integration for SurveyJS Library and Creator. 
For more information, check this post:

You can also find examples and integration guides at:
* [Demos: Form Library](https://surveyjs.io/form-library/examples/nps-question/reactjs)
* [Documentation: Form Library](https://surveyjs.io/form-library/documentation/get-started-angular)

* [Documentation: Creator](https://surveyjs.io/survey-creator/documentation/get-started-angular)
* [Demos: Creator](https://surveyjs.io/survey-creator/examples/free-nps-survey-template/reactjs)

Let us know if you have any questions or require further assistance.

**Comment by amira133** [comment]
excellent
Can you please tell me which version of surveyJs, Angular is supported nativly?

**Comment by JaneSjs** [comment]
Hello @amira133,
For Survey Library, native Angular integration is supported with v1.9.44. For Survey Creator, use v1.9.56 and newer.
For the record: please ensure that you use the same version of the Form Library and Creator in your application.

Should you have any questions or require further assistance, we are here to help.

**Comment by amira133** [comment]
Thanks @JaneSjs 
I do not have a specific question.
Thanks again for your team's efforts
