### ISSUE TITLE
Ability to control order of items in Logic dropdown

### ISSUE THREAD

**Issue by leksinteractive** [surveyjs/survey-creator#2989]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question.

### What is the current behavior?
The order of the items in the question selection dropdown seems to be based on the question name, not actual order of the questions in the survey. I'm referring to the dropdown in the Logic tab, which allows you to select a question to target (see screenshots below)

### What is the expected behavior?
Let's say for example that I have 3 questions in a survey... question1, question2 and question3, in that order. Then if I drag question2 to be first, the order of the questions in the survey is now question2, question1, question3. I would expect that the dropdown in the Logic section to reflect this order, otherwise it's actually quite confusing which question is first. The dropdown will still display the original order which is not correct.

### How would you reproduce the current behavior (if this is a bug)?
Not a bug, but wondering if it's possible for the dropdown to reflect the actual order of the questions in the survey?

#### Provide the test code and the tested page URL (if applicable)

<img width="1361" alt="Screen Shot 2022-05-11 at 11 23 51 pm" src="https://user-images.githubusercontent.com/3906239/167861533-ad9b9470-7760-49b3-8cb8-30205245ab85.png">
<img width="1220" alt="Screen Shot 2022-05-11 at 11 29 55 pm" src="https://user-images.githubusercontent.com/3906239/167861623-a0d806f3-0604-47ee-b808-a43aa6055de8.png">

### Specify your

* browser:
* editor version:

**Comment by leksinteractive** [comment]
Hi @andrewtelnov 

Thanks for that, it does solve the problem I had, partly. However, the app I am working on is in a "legacy" state, so we have quite an old version of the survey-creator (v1.0.53) and this option is not available. We are planning to use the creator in a new version, we're slowly migrating it. Is there any other options we may have to achieve this functionality?

Also, just to elaborate on why this solves the problem partly. The order of the items in the dropdown is actually still based on an alphabetic ordering of either the name or title of the question. Instead what I think makes sense is to have the order of the questions in the dropdown match the order of the questions in the survey. Hope that makes sense?

Many thanks 🙏

**Comment by andrewtelnov** [comment]
@leksinteractive v1.0.53 is very old and it doesn't have a lot of functionality. I am afraid I can't provide a work-around for you for this version.
We have already Creator V2 and I suggest to move to this version.

Thank you,
Andrew

**Comment by leksinteractive** [comment]
Thanks for the quick reply @andrewtelnov 👍 

Closing issue, but the question/request for the ordering still applies for the new version IMO.

Please let me know if you'd like me to open a feature request ticket for this.
