### ISSUE TITLE
V2, Bug: text of the items of the non-default localised Survey in Designer Tab

### ISSUE THREAD

**Issue by dk981234** [surveyjs/survey-creator#3016]
Steps to reproduce:
1. Set survey locale to non-default locale via property grid
2. Add boolean question: on this step Yes/No labels are localised correctly
3. Click on Preview Tab
4. Click on Designer Tab
5. boolean localised labels are reset to labels with default Yes/No

**Comment by andrewtelnov** [comment]
The bug is fixed on the survey level. Here is the related issue in [survey library repository](https://github.com/surveyjs/survey-library/issues/4351).

Thank you,
Andrew
