### ISSUE TITLE
Page navigation shows wrong

### ISSUE THREAD

**Issue by shahidcodes** [surveyjs/survey-creator#3034]
### Are you requesting a feature, reporting a bug or ask a question?

BUG

### What is the current behavior?

Page ordering shows wrong

### What is the expected behavior?

Page ordering must match with the UI

### How would you reproduce the current behavior (if this is a bug)?

- create a new survey
- add two pages (1, 2)
- duplicate page 1
- check page navigation, ordering is - 1, 3, 2
- try to navigate to pages if you click page3, it takes to page2 and if you click page2 it tasks page3

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://4scfiu.csb.app/

Test code

```
import { Component, Fragment } from "react";
import { SurveyCreatorComponent, SurveyCreator } from "survey-creator-react";
import "survey-core/defaultV2.min.css";
import "survey-creator-core/survey-creator-core.min.css";

export default class AddSurvey extends Component {
  state = {
    
  };
  constructor(props) {
    super();
    // Instantiate Survey Creator
    this.creator = new SurveyCreator({
      showLogicTab: false,
      showJSONEditorTab: false,
      forceCompact: false,
      haveCommercialLicense: true,
      questionTypes: [
        "text",
        "checkbox",
        "radiogroup",
        "dropdown",
        "comment",
        "rating",
        "ranking"
      ]
    });
  }

  render() {
    return (
      <Fragment>
        <SurveyCreatorComponent creator={this.creator} />
      </Fragment>
    );
  }
}

```

### Specify your

* Browser: Chrome
* editor version: 1.9.31

**Comment by andrewtelnov** [comment]
@shahidcodes I guess, you are talking about place holders for page titles. They are rendering based page index in survey and not on page name. Otherwise, it would look strage to have titles as: Page 1, Page 3, Page 2.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
You can set page titles and see the how it works.

Thank you,
Andrew

**Comment by shahidcodes** [comment]
> @shahidcodes I guess, you are talking about place holders for page titles. They are rendering based page index in survey and not on page name. Otherwise, it would look strage to have titles as: Page 1, Page 3, Page 2.
> 
> Thank you, Andrew

Yes, it would be good if both the page navigation dropdown and the page placeholder itself has the same index ordering but now it differs. 

![image](https://user-images.githubusercontent.com/17620737/170042038-7db68743-5f4a-46a4-993d-5e59037dd590.png)
![image](https://user-images.githubusercontent.com/17620737/170042092-4e4d5cd1-620c-4a9a-be57-534ceff6796b.png)
