### ISSUE TITLE
Translation Tab Issues.

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#3069]
1. Structure
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SJS-Creator?node-id=11285%3A94754

2. Side Panel Design
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SJS-Creator?node-id=8366%3A38542

**Comment by OlgaLarina** [comment]
Thanks for the request, but these issues have already been reported and they will be fixed when our team leader schedules them.

https://github.com/surveyjs/survey-creator/issues/2740
https://github.com/surveyjs/survey-creator/issues/2351
