### ISSUE TITLE
direction RTL not supported

### ISSUE THREAD

**Issue by DevAhmad7** [surveyjs/survey-creator#3071]
#### Example:

![Screenshot (191)](https://user-images.githubusercontent.com/55281583/171429708-c07de8b5-9a96-4503-9db4-e0909b3453fd.png)

![Screenshot (190)](https://user-images.githubusercontent.com/55281583/171429692-08a0eab6-e122-44b9-b764-59a1b87a4b92.png)

**Comment by tsv2013** [comment]
Could you explain - what's wrong on this picture?

**Comment by DevAhmad7** [comment]
> Could you explain - what's wrong on this picture?

#### Yes, in the first picture:
In RTL mode is not supported
#### In the second picture
This is the edit I made
I want the edit to be in RTL mode from you
### This will be better

**Comment by tsv2013** [comment]
@DevAhmad7 Can you share the exact steps to reproduce the issue, the actual result and the expected result?

**Comment by DevAhmad7** [comment]
### When setting the RTL dir page for Arabic
I'm adding a new multiple-choice question

#### The actual result is the text attached to the icons, as shown by the green arrow
![Screenshot (191)](https://user-images.githubusercontent.com/55281583/171429708-c07de8b5-9a96-4503-9db4-e0909b3453fd.png)


### expected result
![Screenshot (190)](https://user-images.githubusercontent.com/55281583/171429692-08a0eab6-e122-44b9-b764-59a1b87a4b92.png)

**Comment by tsv2013** [comment]
If you type an RTL text in an item editor - is it typed correctly?

**Comment by DevAhmad7** [comment]
> If you type an RTL text in an item editor - is it typed correctly?

#### yes it typed correctly
But I'm not talking about the text inside in an item editor
### I'm talking about the padding between items like...

![prob](https://user-images.githubusercontent.com/55281583/172025836-5cf3b14e-5c63-4569-9c48-4b337b0c3289.PNG)

### It should be like this

![Screenshot (190)](https://user-images.githubusercontent.com/55281583/172025894-9d19595f-1ce4-43a3-aa83-4518377d8d8a.png)

**Comment by tsv2013** [comment]
Thank you for the clarifications. It's a bug indeed. I pup it into our task queue.
