### ISSUE TITLE
How to lift the project in heroku

### ISSUE THREAD

**Issue by franjogordillo** [surveyjs/survey-creator#31]
Hi Andrew,

Please im trying to lift the project in heroku with angular/typescript add on, but it does not work. Please tell me what i need to lift the service.

Best regards ,

Francisco.

**Comment by andrewtelnov** [comment]
@franjogordillo We are working right now on support Angular2 and jQuery for surveyjs library. We are going to make it available shortly.
The Editor is an another story. The code is currently tightly bind with the knockout. We have to do what we have done with the surveyjs library before: separate logic from knockout model, then create the react version. After that we may use [preact](https://preactjs.com/) to add Angular and jQuery support, using preact style rendering.
This work is on our radar, but it is not what we have on another week :-(

Thank you,
Andrew
