### ISSUE TITLE
Property Grid matrix blinks while dragging

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#3118]
Also there is not accurate cursor positioning.
https://user-images.githubusercontent.com/29385489/173786333-0c305a29-2b03-45b2-8c09-6adf7a51c0c4.mov

**Comment by dmitrykurmanov** [comment]
can't reproduce at aurveyjs.io
https://user-images.githubusercontent.com/22315929/177029559-55d52f3b-98bb-4991-a667-b07d0d32f099.mp4

**Comment by novikov82** [comment]
@mikeamelin I can not reproduce it too. Could you check it once again?

**Comment by mikeamelin** [comment]
Seems like the issue's gone.
