### ISSUE TITLE
Fix popups design

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#3120]
- [ ] question width and height should be the same as in designer
- [ ] surveyjs/survey-library#4546

![image](https://user-images.githubusercontent.com/29385489/173788602-d72a86f7-cf0d-48a6-9c66-f8dd38f6bcaf.png)
![image](https://user-images.githubusercontent.com/29385489/173788656-723f8d4d-6af9-4850-bd32-f49804f5989b.png)

**Comment by mikeamelin** [comment]
Talked to Alexey
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SJS-Creator?node-id=9623%3A67804
