### ISSUE TITLE
Width and alignment of object selector

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#3127]
- [x] Popup should be wider
- [x] triangle pointer should be in the center of button

![image](https://user-images.githubusercontent.com/29385489/174030820-0dd93035-c3db-4d4b-aa2d-52b5acddf7ae.png)

**Comment by dk981234** [comment]
pointer position was fixed via this [pull request](https://github.com/surveyjs/survey-library/pull/4330)
