### ISSUE TITLE
Remove empty page after deleting all questions

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#3128]
(if no title and description of page entered)
![image](https://user-images.githubusercontent.com/29385489/174031855-72c0f5f0-4485-4028-8132-fe1b7471f863.png)

**Comment by andrewtelnov** [comment]
It can be done if:
1) The page is the last
2) If there is no any property set in the page object

If the page is not the last one and there is any property value is different from a default value, we should not delete it.

**Comment by mikeamelin** [comment]
Looks like nothing's changed.

**Comment by tsv2013** [comment]
@mikeamelin we'll re-check base cases and the "Clear" button click case

**Comment by andrewtelnov** [comment]
@mikeamelin We do not delete the only page. We do not a page if it is not the last page. We do not the page if any property, for example page title is changed from the default value.
We delete the page if: it is the last page, there is no any changes in this page and it is not the only page.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@mikeamelin If a survey was not empty then the first page is not delete. If it was empty initially, then the first page is deleted as well.
