### ISSUE TITLE
V2: JSON with matrix columns with matching name and title, title property is removed

### ISSUE THREAD

**Issue by benmoses-equineregister** [surveyjs/survey-creator#3140]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a Bug

### What is the current behavior?
Loading a survey with JSON where you have columns with matching name and title. When it's loaded the JSON and Creator shows no title property.
JSON Loaded: 
```
...
columns: [{
  name: 'foo', 
  title: 'bar'
}, {
  name: 'foo', 
  title: 'foo'
}]
...
```
JSON shown

```
...
columns: [{
  name: 'foo', 
  title: 'bar'
}, {
  name: 'foo'
}]
...
```
### What is the expected behavior?
The initial data should be loaded with no changes

### How would you reproduce the current behavior (if this is a bug)?
https://plnkr.co/edit/Zv5bF7IymytaznSB

#### Provide the test code and the tested page URL (if applicable)
[
Tested page URL: ](https://plnkr.co/edit/Zv5bF7IymytaznSB)

### Specify your

* browser: Chrome
* editor version: 1.9.35

**Comment by andrewtelnov** [comment]
@benmoses-equineregister SurveyJS Creator consider the default value for column/question/page/panel title a column/question/page/panel name. SurveyJS doesn't realized the default property value. I mean it is a way it works.
Why do you want to change this behavior?

Thank you,
Andrew

**Comment by benmoses-equineregister** [comment]
@andrewtelnov Could you point me in the right direction where the `creator.json = mySurvey` gets intialised from JSON to survey models and where the title field is being cleared?

**Comment by benmoses-equineregister** [comment]
@andrewtelnov Could you point me to where the title property is being removed on initialisation? I plan on disabling it so that if a column has {"name": "foo", "title": "foo"} both values are kept, and the survey-creator shows them in the editing.

Thanks

**Comment by andrewtelnov** [comment]
@benmoses-equineregister It is a JavaScript and we are a library. You can correct JSON before sending it to your server/database. It is a dozen lines of code and not all functionality should be in our code. You can customize behavior of our libraries as you need.
Here is the code that updates the json and [working example](https://plnkr.co/edit/e8FlIqzvnQ2zJzni).
```js
function updateJSON(json) {
  if(typeof json !== "object") return;
  for(var key in json) {
    if(key === "columns") {
      const columns = json["columns"];
      if(Array.isArray(columns)) {
        for(var i = 0; i < columns.length; i ++) {
          const col = columns[i];
          if(!!col.name && !col.title) {
            col.title = col.name;
          }
        }
      }
    } else {
      updateJSON(json[key]);
    }
  }
}
```

Thank you,
Andrew

**Comment by benmoses-equineregister** [comment]
Sorry Andrew,

I meant where in the SurveyJS code is the JSON being edited to remove the title property? I also want the creator to show the title as filled in and not show it as empty so fixing it before submitting wouldn't really work for me, as the inputs in the creator always look empty (no title, but has the name showing as a placeholder value)

**Comment by andrewtelnov** [comment]
@benmoses-equineregister Our designer said that it should be done any way. So we will implement placeholder for question and matrix column titles. Here is [the related issue](https://github.com/surveyjs/survey-creator/issues/3253).

Thank you,
Andrew
SurveyJS Team
If you like our products, please take a moment to share your experience with our company by contributing a short review for [SurveyJS page at g2.com](https://www.g2.com/products/surveyjs/reviews).
As we’re building our business, every review helps build credibility for future customers and your feedback would be greatly appreciated.

**Comment by benmoses-equineregister** [comment]
Hi Andrew, 

So the reason I wanted it to not lose the title property. In the Survey-Creator, if there is no title property the name is shown as placeholder in the properties grid under the column section. If there is a title property then it's shown as black text, and editable. 

![image](https://user-images.githubusercontent.com/97945881/177812867-cef8f04f-2300-4283-a6aa-58650801a021.png)

See the screenshot. The first Column is showing "however" greyed out as if it's not been filled in, but it's was filled in, it's filled in by me last time I edited it. I save and then reload the page and it's greyed out again. 

I don't think the change you're designed suggested would resolve this bug? I'm happy to test once it's available, do you think it will work? 

Many thanks,
Ben

P.S. I added a review, top marks because you guys have been great, however that review service G2 was exhausting. It was about a million questions, all shown one after the other and no idea of how many questions it was. I also managed to lose my progress when I alt-tabbed away. If possible please move to a different review service 😉 (joking)

**Comment by andrewtelnov** [comment]
@benmoses-equineregister At first thank you for your kind words.
Regarding your case, let us discuss this case.
I was talking about a screen, when you click on a column header and column properties shows as a separate objects.
We will definitely add placeholder for question/column title.
Your case is different. I will be back.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@benmoses-equineregister The functionality you have asked has been released. Question and columns placeholders will be set equal to name from v1.9.41. Here is [the related issue](https://github.com/surveyjs/survey-creator/issues/3253).

Thank you,
Andrew
SurveyJS Team
If you like our products, please take a moment to share your experience with our company by contributing a short review for SurveyJS page at [g2.com](https://www.g2.com/products/surveyjs/reviews) or at [Trustpilot.com](https://www.trustpilot.com/evaluate/surveyjs.io]).
As we’re building our business, every review helps build credibility for future customers and your feedback would be greatly appreciated.

**Comment by benmoses-equineregister** [comment]
Brilliant, thank you Andrew for your support with this and the fix!
