### ISSUE TITLE
Need to disable logic popups in case on no questions

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#3162]
![image](https://user-images.githubusercontent.com/29385489/174618811-4fc03580-4e77-4406-8294-1b05e224f6d1.png)

**Comment by andrewtelnov** [comment]
@novikov82 Unfortunately there is no easy way to find out if a question list will be empty or not.
It depends on context (survey, question, column, dynamic panel) and events.
We will probably should show a different view with text: "There is no questions to build the expression" on opening modal window.
It would be easy to implement and UI probably will be better.

Thank you,
Andrew

**Comment by novikov82** [comment]
I'm absolutely sure that message "There is no questions to build the expression" is better than just not clickable, unclear "Choose..." button.
But I can not understand, if you can determine that "there is no question..." ON opening modal window, why you can not to run the same code and use the same algorithm BEFORE opening modal window and disable the Logic panel in property grid, or write the same message in this panel. But maybe it requers a lot of code and tests, I don't know exactly...

So, your suggestion can be good first step to the best UI.

**Comment by andrewtelnov** [comment]
@novikov82 [Here is the code](https://github.com/surveyjs/survey-creator/blob/master/packages/survey-creator-core/src/property-grid/condition-survey.ts#L606). It can take a time to execute.
Having another view is a simple solution. If this function returns false on opening modal then show the text.
If you don't disagree then we need to contact Mike to get an UI for it.

Thank you,
Andrew

**Comment by novikov82** [comment]
@andrewtelnov 
As for me, deal to performance, we could combine both approachs.
First we check if logic is enabled for question with the simple condition `survey.getAllQuestions().length > 1`. In case of false we should show in Property Grid Logic panel something like "Logic can be used when only one question presents in survey". In any case we need contact Mike for design and Roman for text.

Can `createAllConditionQuestions` function return empty array if _survey.getAllQuestions().length > 1_? If yes, we need to do the second check you talking about and show the text in the modla popup.

@mikeamelin what is your opinion?

**Comment by mikeamelin** [comment]
Showing the message in the property grid section is good enough, I think.

**Comment by andrewtelnov** [comment]
@novikov82 @novikov82 After the latest changes, I believe this issue becomes irrelevant.

Thank you,
Andrew

**Comment by mikeamelin** [comment]
I'm okay with current behaviour.



![Image](https://github.com/surveyjs/survey-creator/assets/17025812/0328c697-e628-40e3-82b7-6687f89383d5)
