### ISSUE TITLE
Categories in Property Panel (base, advanced, custom)

### ISSUE THREAD

**Issue by marc0n3** [surveyjs/survey-creator#317]
### Are you requesting a feature, reporting a bug or ask a question?

Question

Can I group properties in property panel on the right like you do for the toolbox on the left in:
https://surveyjs.io/Examples/Editor/?id=toolboxcategories

**Comment by andrewtelnov** [comment]
@marc0n3 Yes, it has been asked before and it is in our TODO list.
However, right now we are concentrating on inplace editing in the elements and better elements Editor, a modal window showing on clicking the button "Edit".
On our usabilities tests show that non-technical users prefer do not use property grid at all.
The most are trying inplace editing at first and then they go to the elements Editor.

Thank you,
Andrew

**Comment by tsv2013** [comment]
We've implemented it. You can check it in our samples - https://surveyjs.io/Examples/Survey-Creator?id=options&theme=default
