### ISSUE TITLE
Need to have Panel in Type converter

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#3170]
![image](https://user-images.githubusercontent.com/29385489/174630577-f8b2b73d-d9f2-47f1-a386-d5da406cd7c6.png)

**Comment by andrewtelnov** [comment]
@novikov82 We allow to convert panel dynamic into panel and panel into panel dynamic.

Thank you,
Andrew

**Comment by novikov82** [comment]
This is @mikeamelin 's issue. I remember that your opinion differs from him. Mike offers to add "question to panel" conversion here. You need to discuss it once again and make the decision. Maybe later.

**Comment by mikeamelin** [comment]
I still don't see a problem to do it.
