### ISSUE TITLE
Survey creator rateMax and rateMin can overlap

### ISSUE THREAD

**Issue by benmoses-equineregister** [surveyjs/survey-creator#3198]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a Bug

### What is the current behavior?
If you set your rate min to 3, rate max to 4. You can then change rate max to 3, then to 2, then to 1 etc. None of these changes are applied to the JSON and the change should just be ignored?

### What is the expected behavior?
Ignore invalid property changes. Ideally with an error.

### How would you reproduce the current behavior (if this is a bug)?
Go to https://plnkr.co/edit/eci8DQOj916e9Mws
Select Question 1
Open properties grid
Rate values
Change Max Rate from 4 to -1. Anything below the rate min is not applied and the survey-creator UI should reflect this.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/eci8DQOj916e9Mws

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* editor version: 1.9.37

**Comment by andrewtelnov** [comment]
@benmoses-equineregister I have fixed the issue in library. Here is [the related issue](https://github.com/surveyjs/survey-library/issues/4526).
The fix will be available in the next minor update.

Thank you,
Andrew
