### ISSUE TITLE
CodeSandbox: An empty space in the Complete page 

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#3200]
[Example](https://codesandbox.io/s/d81vfp?file=/src/index.js)

![image](https://user-images.githubusercontent.com/18551316/175480024-186d7c3f-2121-4ef6-8bf5-fb4dbc34ad11.png)

**Comment by novikov82** [comment]
This is already fixed with correct CodeSandbox index.html file
