### ISSUE TITLE
Repo cloning issue

### ISSUE THREAD

**Issue by Saqib-Sattar** [surveyjs/survey-creator#3215]
I get a clone from this repo and try to run it locally, but got webpacks related errors, plz attach a Readme file to show the steps for running this repo

**Comment by babaralishah** [comment]
I am also facing the same issue, can anyone tell that how this repo can cloned in a better way with either of below mentioned frameworks:
1- Angular
2- React
3- Vue

**Comment by tsv2013** [comment]
You need to clone the https://github.com/surveyjs/survey-library and the https://github.com/surveyjs/survey-creator repositories side by side and then run the https://github.com/surveyjs/survey-creator/blob/master/run-dev-server-react.bat batch file
