### ISSUE TITLE
Need guidance to clone the repo, as being facing the issues

### ISSUE THREAD

**Issue by babaralishah** [surveyjs/survey-creator#3216]
I would not call it a bug but need a little guidance...

I just want to run this repo for understanding its workflow, so the framework would doesn't matter to me.
Any of these below frameworks would be accepted:
- Angular
- React
- Vue

Currently when I am running it in the angular environment,
on running the 'ng serve' command after the 'npm i' command I get this below error:
`This repo is not of angular, command should run in angular directory`
![image](https://user-images.githubusercontent.com/37935603/176412489-ad53f414-cbfd-42c8-b9e1-59ea1988a7e0.png)
![image](https://user-images.githubusercontent.com/37935603/176412512-da43d2c8-9b1d-4bf5-946e-52c6e232bae2.png)

On running in React Environment:
After Npm i and npm start:
I get the error:
`all the errors are related to the webpack versioning issues`

![image](https://user-images.githubusercontent.com/37935603/176412192-3c895c6d-268f-4c95-baf0-5afdc96472ce.png)
![image](https://user-images.githubusercontent.com/37935603/176412225-2c79c30c-3050-4db8-9f3a-1405bdb05e9b.png)
![image](https://user-images.githubusercontent.com/37935603/176412322-cd733008-317e-4c86-9108-6b415d1552e6.png)

**Comment by andrewtelnov** [comment]
@babaralishah Our repo do not have angular code right now. You will need to compile survey-creator-core and then survey-creatir-knokout packages and use them in your angular application.
We are working on Angular version, but it will take a time.

Thank you,
Andrew

**Comment by babaralishah** [comment]
> @babaralishah Our repo does not have angular code right now. You will need to compile survey-creator-core and then survey-creator-knockout packages and use them in your angular application. We are working on the Angular version, but it will take time.
> 
> Thank you, Andrew

@andrewtelnov 
Thank you so much for your response, can you please tell me what steps should i follow to run this as a react project?

**Comment by andrewtelnov** [comment]
For react project you can use packages: survey-creator-core and survey-creator-react.

Thank you,
Andrew

**Comment by babaralishah** [comment]
@andrewtelnov 
Okay!
And am I supposed to use this same repo for react by adding the above-mentioned packages?

**Comment by andrewtelnov** [comment]
All packages are located [here](https://github.com/surveyjs/survey-creator/tree/master/packages)

Thank you,
Andrew

**Comment by tsv2013** [comment]
You need to clone the https://github.com/surveyjs/survey-library and the https://github.com/surveyjs/survey-creator repositories side by side and then run the https://github.com/surveyjs/survey-creator/blob/master/run-dev-server-react.bat batch file

**Comment by babaralishah** [comment]
> You need to clone the https://github.com/surveyjs/survey-library and the https://github.com/surveyjs/survey-creator repositories side by side and then run the https://github.com/surveyjs/survey-creator/blob/master/run-dev-server-react.bat batch file

@tsv2013 
Is there some easy scenario for this?
without running the two repos.

**Comment by babaralishah** [comment]
> You need to clone the https://github.com/surveyjs/survey-library and the https://github.com/surveyjs/survey-creator repositories side by side and then run the https://github.com/surveyjs/survey-creator/blob/master/run-dev-server-react.bat batch file

I have cloned the two Repos but unable to run them, getting error when running this command
`npm start`
![image](https://user-images.githubusercontent.com/37935603/176700121-f0bacfa2-8174-4b40-943f-0c1e607995fa.png)

**Comment by babaralishah** [comment]
@andrewtelnov 
The survey-library is running fine with the react environment, but survey creator is not running in the react.
i am getting the following error, can u please guide...

![image](https://user-images.githubusercontent.com/37935603/176833503-e4bb4428-de0f-41fc-8c5c-fef7d6168024.png)

**Comment by tsv2013** [comment]
@babaralishah survey-creator repo requires survey-library repo to be cloned aside. Also before the "npm start" command you almost always need to run "npm i" command. All these commands are listed in the https://github.com/surveyjs/survey-creator/blob/master/run-dev-server-react.bat file
