### ISSUE TITLE
V2: Cannot deselect "Copy choices from the following question" dropdown

### ISSUE THREAD

**Issue by benmoses-equineregister** [surveyjs/survey-creator#3218]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
In Survey-creator with 2 checkbox questions. Second question > Choices tab > Copy choices > Select "Question 1". It is now not possible to "break" this connection. 

### What is the expected behavior?
The dropdown should have a "None" option? or a cross to disable copy choices?

### How would you reproduce the current behavior (if this is a bug)?
Go to https://plnkr.co/edit/rXkI4peTG02iZ6AZ (Survey-Creator with 2 checkboxes, question 2 set to copy from question 1)
Select Question 2 > Settings > Choices > Copy choices dropdown cannot be deselected.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:https://plnkr.co/edit/rXkI4peTG02iZ6AZ

### Specify your

* browser: Chrome
* editor version: 1.9.38

**Comment by benmoses-equineregister** [comment]
Note: I'm not sure if "None" option is the best fix? or if a cross to the right of the dropdown is the correct fix? Or perhaps an additional property copy choices which is a boolean?

**Comment by andrewtelnov** [comment]
@OlgaLarina I believe it is a bug in our new dropdown rendering. optionsCaption is set, but it is not rendered as the first item.

Thank you,
Andrew
