### ISSUE TITLE
How to run the surveyjs-creator repo

### ISSUE THREAD

**Issue by babaralishah** [surveyjs/survey-creator#3223]
hi all
can anyone please guide me about the surveyjs creator repo, how can i run this on my system locally.

i am trying to run this on the react environment

i have installed the node modules then i ran the command
`npm start`
but gives me this error:

![image](https://user-images.githubusercontent.com/37935603/176841158-8fb1eaf2-948c-40b2-aded-5382b6200e2f.png)

Please help me out, it will be a great favor to me

regards
babar ali shah

**Comment by babaralishah** [comment]
@andrewtelnov 
Alright, Andrew!
As you said.
Lemme do that...
Thank you!

**Comment by babaralishah** [comment]
@andrewtelnov 
i have installed the node mudules,
now I am getting this while running `npm start`

![image](https://user-images.githubusercontent.com/37935603/176844248-6c78da76-29a7-41c2-855c-4e8405d48e5c.png)

**Comment by babaralishah** [comment]
On installing 
`npm install -g webpack-dev-server`
i am getting this

![image](https://user-images.githubusercontent.com/37935603/176844472-971b5dd4-f4db-4acc-97a6-52c18a643174.png)

**Comment by babaralishah** [comment]
![image](https://user-images.githubusercontent.com/37935603/176847876-f50b28d4-ccbd-4cea-8609-3e56c4f59609.png)

**Comment by Saqib-Sattar** [comment]
@andrewtelnov  I've go to survey-creator/packages/survey-creator-vue/ and run it, it stuck there
<img width="630" alt="vue-err" src="https://user-images.githubusercontent.com/90828155/176850510-77fbe3fe-933a-4f80-90d7-03a300184986.PNG">

**Comment by andrewtelnov** [comment]
@babaralishah As @tsv2013 wrote in another your ticket you will need to clone survey-library and survey-creator into the same directory.
Then go to survey-library and in console run:
`npm install`
`npm run build_core`
`npm run build_react_ui`
After that go to survey-creator/package/survey-creator-core and run:
`npm install`
`npm run build`
After that you can go into survey-creator/package/survey-creator-react and run:
`npm install`
`npm run build`
`npm run start`

Thank you,
Andrew

**Comment by tsv2013** [comment]
We haven't implemented survey-creator-vue, it's just a stub

**Comment by Saqib-Sattar** [comment]
> @babaralishah As @tsv2013 wrote in another your ticket you will need to clone survey-library and survey-creator into the same directory. Then go to survey-library and in console run: `npm install` `npm run build_core` `npm run build_react_ui` After that go to survey-creator/package/survey-creator-core and run: `npm install` `npm run build` After that you can go into survey-creator/package/survey-creator-react and run: `npm install` `npm run build` `npm run start`
> 
> Thank you, Andrew

@andrewtelnov  firstly, I go to survey-library and then run all the commands that you've written here and it's working fine, after that, I go to survey-creator/package/survey-creator-core and run the commands that you've mentioned above but when I go into survey-creator/package/survey-creator-react and run the command `npm run build`, it throws me this error
<img width="572" alt="error" src="https://user-images.githubusercontent.com/90828155/176895685-c7897af3-96d0-4205-8a1c-5290e9c61092.PNG">
