### ISSUE TITLE
Can I add a checkbox column in a matrixdynamic field with dynamic options (based on another input field value) without using custom widgets?

### ISSUE THREAD

**Issue by bappajubcse05** [surveyjs/survey-creator#323]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the expected behavior?

Can I add a checkbox column in a matrixdynamic field with dynamic options (based on another input field value) without using custom widgets?

For example - 
Field1 (type - text):  
Field2: matrixdynamic with one column (suppose column x) with cellType: "checkbox"

field2 is visible when field1 is having some value.
When I enter some value in field1,

available check box options should be -

`[]a-<entered text> []b-<entered text> []c-<entered text> []select all`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@bappajubcse05 the matrix cell has visibleIf property, you may use it "{Field1} notempty"
To support select all you have to use [survey.onMatrixCellValueChanged](https://surveyjs.io/Documentation/Library/?id=surveymodel#onMatrixCellValueChanged) event.

Thank you,
Andrew

**Comment by bappajubcse05** [comment]
Hello @andrewtelnov 
Does surveyJS support checkbox column with dynamic values in a matrixdynamic field?

**Comment by andrewtelnov** [comment]
@bappajubcse05 You may use [survey.onMatrixCellCreated](https://surveyjs.io/Documentation/Library/?id=surveymodel#onMatrixCellCreated) to create an intial editor you want, even different editor type in one column.
You may change what ever you want in any question, or any matrix cell on survey.onValueChanged event.
If you are ok, to write some code, you may do what ever you want.
SurveyJS is a flexible and extendable library.

Thank you,
Andrew
