### ISSUE TITLE
V2: Adding a question to an empty survey from the toolbox does not use the `translations.ed.newPageName` property

### ISSUE THREAD

**Issue by benmoses-equineregister** [surveyjs/survey-creator#3273]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
When you add a question to an empty survey form the toolbox. It will auto-create the first page with the name "page1" even if you set the translations property.

Adding via drag drop of toolbox, or the ghost page button works as expected. 

### What is the expected behavior?
The toolbox should name pages using the translations property

### How would you reproduce the current behavior (if this is a bug)?
1. Open https://plnkr.co/edit/xNnI1L4enxVsUizq
2. Increase width of preview to show the toolbox
3. Insert single input question. 
4. Select the page the single input was inserted into. It's name is "page1". [Bug]
---
5. Delete the page and insert using drag drop from the toolbox, or using the ghost page's add question button.
6. Select the Page > Settings. It is named "Page 1". [Expected behaviour]

### Specify your

* browser: Chrome
* editor version: 1.9.40

**Comment by andrewtelnov** [comment]
@benmoses-equineregister I believe we trunk the string. If you put another string it will work.
Do you need it with spaces?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@benmoses-equineregister Here is [your updated example](https://plnkr.co/edit/EYkPSsGnjNgD358o).

Thank you,
Andrew

**Comment by benmoses-equineregister** [comment]
![page1](https://user-images.githubusercontent.com/97945881/178747128-22f5df0c-1658-4b58-bfa8-a3b1c415c5ab.gif)
It's still showing the bug in your updated example. 

See the attached gif for clearer steps.

**Comment by andrewtelnov** [comment]
@benmoses-equineregister Is your code the following?
```js
const translations = SurveyCreator.localization.getLocale('');
translations.ed.newPageName = 'MyPage';
translations.ed.newQuestionName = 'MyQuestion';
var creator = new SurveyCreator.SurveyCreator(options);


ReactDOM.render (<React.StrictMode>
  <SurveyCreator.SurveyCreatorComponent creator={creator}/>
</React.StrictMode>, document.getElementById("creatorElement"));
```
In your code, you create the Creator model, then update the translation. However, the initial page was created when you create the model and changing translation is too late.

Thank you,
Andrew

**Comment by benmoses-equineregister** [comment]
Yes, in my Gif I was following you're link. I just double checked and it matches your quoted code exactly.

**Note:** If I add the question via drag and drop. Or using the add question button on screen. It works perfectly no issues. **Only** if I click to insert the question, does it get inserted with the wrong name "page1".

**Comment by andrewtelnov** [comment]
@benmoses-equineregister Indeed, I was able to reproduce the issue. We will take a look.

Thank you,
Andrew
