### ISSUE TITLE
onModified event not firing after json property is set to empty

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#3283]
```
  const creatorOptions = {};
  const creator = new SurveyCreator(creatorOptions);
  creator.JSON = {};
  creator.onModified.add((sender, options) => {
    console.log('IS MODIFIED')
  });
```

To reproduce:
Add a question and on the console you will see a "modified" string signifying that the event was triggered. After this, change the Survey Title and you'll see that the event does not get fired.

https://surveyjs.answerdesk.io/ticket/details/t10050/survey-creator-issues
https://surveyjs.answerdesk.io/ticket/details/t10042/onmodified-doesn-t-get-triggered-when-survey-title-is-changed-after-adding-a-question

**Comment by andrewtelnov** [comment]
It is likely is fixed in [this issue](https://github.com/surveyjs/survey-creator/issues/3272). They are related.

Thank you,
Andrew
