### ISSUE TITLE
Start working on animations design and implement some

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#3284]

**Comment by JaneSjs** [comment]
@mikeamelin have you considered adding the animation to automatically focus the next question? An example: https://www.16personalities.com/free-personality-test.

https://github.com/surveyjs/survey-creator/assets/22372972/51ef366a-fd1d-40f0-b722-0a487b1aa540

This feature was requested at https://github.com/surveyjs/survey-library/issues/4907.
