### ISSUE TITLE
List UX -UX improvement of list filling is required (keyboard navigation).

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#3296]
UX improvement of list filling is required (keyboard navigation). 

This applies to the following questions
- check-box
— radio group
- drop-down
— rating
— ranking
- boolean
- matrix
- multiple text

- [x] #3489

- [x] #3479
Focus question title when create a question
At the moment of creating a question, immediately focus the text field of the question (input is activated).
SelectBase items Keyboard editing
Enter does not end input, but shifts focus to the next input field.
You can finish entering by Ctrl (Cmd) + Enter, mouse click “in milk”, or ESC, but with the cancellation of changes, if any.
By pressing Enter, the focus is “transferred” to the input fields (within one question).
If there are no more input fields, then Enter adds a new item.
In questions where there is nothing to fill in, Enter simply ends the input after entering the question text.
At the time of adding a new item, the input field is focused.
- [x] #3497
- [x] Keyboard interactivity for ranking (already resolved in #3479 )
- [x] #3513
- [x] #3514
- [x] #3515
For matrix it would be possible to create a new column/row using Enter.

- [x] #3480
- [x] #3516
Moreover, if the user went up by tabulation at the bottom, then the focus should be left on the item, which is higher, if the user went down from above, then on the item, which is lower.
- [x] #3517
- [x] #3518

**Comment by novikov82** [comment]
all subtasks completed
