### ISSUE TITLE
Creator Drop-Down List Design

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#3297]
Not same as survey drop-down list...
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SJS-Creator?node-id=2018%3A15859

**Comment by OlgaLarina** [comment]
Property grid

**Comment by novikov82** [comment]
The prototype is not available. Issue could be solved in https://github.com/surveyjs/survey-creator/issues/4517
