### ISSUE TITLE
Property Grid Search Option

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-creator#3308]
user's suggestion

Sometimes it might be hard to find the needed property. Probably it would be great to have the "search bar" for this purpose.

**Comment by mikeamelin** [comment]
![Image](https://github.com/surveyjs/survey-creator/assets/17025812/7686a1e1-a4fd-483c-b120-5edce850b09d)



Design — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=174-242871&mode=design

**Comment by mikeamelin** [comment]
I think we could try a way with same painting as focus frame, but another color — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=174-259737&mode=design&t=zjHvOtoauzyFn37j-4
