### ISSUE TITLE
Ranking. Sorting Issue

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#3311]
It happens when use keyboard and remove items.

![Screenshot 2022-07-27 at 10 33 13](https://user-images.githubusercontent.com/17025812/181183412-d77c8329-eb63-459e-aa6b-80d99617220a.png)
![Screenshot 2022-07-27 at 10 33 33](https://user-images.githubusercontent.com/17025812/181183417-631a8259-043d-4cd9-b3f2-2c17f018ef81.png)

**Comment by novikov82** [comment]
fixed via https://github.com/surveyjs/survey-library/issues/4972
