### ISSUE TITLE
Matrix / Column Selection

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#3313]
We shouldn't select the question panel during column selection.
![Screenshot 2022-07-27 at 10 54 35](https://user-images.githubusercontent.com/17025812/181185083-973663e1-8674-48ed-a191-d5914b9618ad.png)

**Comment by tsv2013** [comment]
It's not a a selection, it's a hover

**Comment by mikeamelin** [comment]
Well, not sure. Are there two hovers?

![Screenshot 2022-07-27 at 11 49 31](https://user-images.githubusercontent.com/17025812/181192435-e6eed43f-446a-40dc-babb-8cd96eaffdde.png)

**Comment by tsv2013** [comment]
>Well, not sure. Are there two hovers?

Not sure as well, unless you have two mouse pointers on your screen

:serious: we'll fix it
