### ISSUE TITLE
Survey Creator Custom Options - Cannot show Help Description for a custom Boolean option

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-creator#3351]
I created a custom Boolean property and want to show help description for it. However, the following code doesn't work - a help icon isn't shown for a custom Boolean property.
```js
Survey.Serializer.addProperty(
  "survey", 
   {
     name: "sampleProp:boolean",
     category: "Watermark"
  }
);
const translations = SurveyCreator.localization.getLocale("");
debugger;
translations.pehelp.sampleProp = "Sample tip here";
```
![image](https://user-images.githubusercontent.com/22372972/184609628-b7c1b4b2-37af-4bfc-8ed5-e14ad4a9e6b6.png)

The issue has been reported at https://surveyjs.answerdesk.io/ticket/details/T10340.

**Comment by andrewtelnov** [comment]
Implemented in Library. Label title supports title actions and description now.
