### ISSUE TITLE
survey creator tagbox property does not save all questions changes

### ISSUE THREAD

**Issue by hekin1** [surveyjs/survey-creator#3352]
### Are you requesting a feature, reporting a bug or ask a question?
reporting a bug

### What is the current behavior?
When adding a tagbox property to question in survery creator, GUI will only save the latest tagged question, and removes the previous tagged questions that was done before.

### What is the expected behavior?
All edited questions that gets tagged with tagbox should keep their tags repectively

### How would you reproduce the current behavior (if this is a bug)?
Add a tagbox property to the creator instance like so:

```js
Survey.Serializer.addProperty("question", {
            name: "tagbox:set",
            choices: ["one", "two", "three"],
            category: "general"
});
```
Then try to edit a question and add a tag to the question from the general tab in right property pane of the question, and without saving continue to add a tag to another question , then inspect the JSON preview, only the last edited question gets a tagbox property.

![Screenshot_7](https://user-images.githubusercontent.com/14329635/184681929-29c0367a-0762-4bee-be70-6458ec7d4f04.png)

Here is a plunker: https://plnkr.co/edit/qighGGf3uvvIxais

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/qighGGf3uvvIxais

Test code

```
Survey.Serializer.addProperty("question", {
            name: "tagbox:set",
            choices: ["one", "two", "three"],
            category: "general"
});
```

### Specify your

* browser: Firefox and chrome
* editor version: latest

**Comment by andrewtelnov** [comment]
@hekin1 The bug is fixed on the library level. Here is [the related issue on GitHub](https://github.com/surveyjs/survey-library/issues/4717). The fix will be available in [v1.9.46](https://surveyjs.io/WhatsNew#v1.9.46).

Thank you,
Andrew
