### ISSUE TITLE
onConditionQuestionsGetList has a forced questions list sorting

### ISSUE THREAD

**Issue by messyjoes1** [surveyjs/survey-creator#3353]
onConditionQuestionsGetList event allows us to modify the questions list appearing in logic panel, but after callback the creator has a hardcoded list.sort which can't be avoided.
To deal with this scenarion, a new attribute "options.sortOrder" has been added. It has two options: "asc" (default) and "none". Change it to "none", if you don't want to sort your condition list`.

**Comment by andrewtelnov** [comment]
@messyjoes1 I can't implement it in the way you are asking. It will break the flow and provides another result.
Sorting should be done after collecting all data.
I can create a new event "onElementSorting" it will have an array of items to be sorted, a name to understand what elements you are going to sort, a boolean "processed" attribute that has to be set to true to avoid a default sorting and a function that sorts an array with start, end indices to avoid sorting full array.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@messyjoes1 From the next version 1.9.49 you can add the following code into the event.
`options.sortOrder = "none"`.

Thank you,
Andrew
