### ISSUE TITLE
V2: Support survey.width property

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#3368]
Apply survey width property on designer surface and check css classes for preview.

**Comment by mikeamelin** [comment]
Some changes are needed.
Field _Width_ have to be inactive for _Auto_ and _Responsive_ and have to be active for _Static_ only.
Also I'd like to consider mentioning "px" for _Width_ field.

  
![Screenshot 2022-09-09 at 15 15 00](https://user-images.githubusercontent.com/17025812/189346802-06a33349-adeb-4c23-9410-5ae03d8965b0.png)
