### ISSUE TITLE
Text Issue in Logic Dialog

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#3379]
I'd like to see Select question... as placeholder text.

![Screenshot 2022-08-25 at 10 26 36](https://user-images.githubusercontent.com/17025812/186591635-c4373df9-708a-4bf3-9d31-1886ea0585f4.png)

**Comment by andrewtelnov** [comment]
@mikeamelin We have change it and it will be fine in the next minor update. The default text is "Select..." now.
