### ISSUE TITLE
Survey Creator doesn't prevent users from specifying the same name for question items thus producing incorrect question results

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-creator#3385]
In Survey Creator, it is possible to specify identical names for items or columns/rows for the following question types:
- Single-Choice Matrix
- Drop-down
- Radiogroup
- Checkbox

This produces incorrect results. Refer to the example below.
Single-Choice Matrix setup:
![image](https://user-images.githubusercontent.com/22372972/186923192-7d710fd1-61e5-4214-bb4e-aa0e1bea736b.png)
The result:
![sameColumnNameIssue](https://user-images.githubusercontent.com/22372972/186923600-42075dbd-7f1c-48ce-9b45-75927faee5d4.gif)

Check [this sample](https://plnkr.co/edit/N3pNnmFk64EU8VA0).

The creator should prevent uses from specifying identical names for these items. For example, this is how it's done for Multiple-Choice Matrix:
![image](https://user-images.githubusercontent.com/22372972/186922887-4333b1af-f43b-468b-a79f-100a7e94854d.png)

**Comment by andrewtelnov** [comment]
@JaneGaid It works for single matrix: rows and columns and for matrix dropdown rows.
I did not make it for choices in radiogroup, checkbox and dropdown. It can breack some code. We need to discuss it.
To make it work, it will needed to add this line of code:
`Survey.Serializaer.findProperty("selectbase", "choices").uniquePropertyName = "value";`

Thank you,
Andrew
