### ISSUE TITLE
Columns in translation tab are not refreshed when a new Survey is loaded to the Creator

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-creator#3401]
Please run this [example](https://plnkr.co/edit/6AsE098Hm7tXE7Qu) and activate the Translation tab. Add some languages. Uncheck them to exclude them from the survey definition. Click the 'Reset' button: it will load a default JSON to the creator:
```
creator.JSON = defaultJSON
```
Notice that the Translation tab keeps displaying custom translations checked. 
https://user-images.githubusercontent.com/22372972/188459543-aad73f70-ebdf-4c99-91f3-6a797c2fc0ad.mp4

Expected behavior: the Translation tab doesn't display unchecked translations when resetting the survey.

**Comment by andrewtelnov** [comment]
I could not reproduce the issue in the unit test, commited above and then in [the real example](https://codesandbox.io/s/optimistic-cohen-chsyj6?file=/src/SurveyCreatorComponent.jsx).

Thank you,
Andrew
