### ISSUE TITLE
Knockout V1 - Reorder questions using drag&drop changes property box element to Survey  

### ISSUE THREAD

**Issue by jpardocimo** [surveyjs/survey-creator#3402]
### Are you requesting a feature, reporting a bug or ask a question?

BUG 

### What is the current behavior?

**V1 Knockout - survey creator:
1. Add at least 3 questions. 

2. Choose one and reorder it (using drag&drop) -> See Drop-Down elements > Selected element changed to Survey (in the property box dropdonw elements)
 
3. Click on another question

4. Click on the question that you dragged 

5 . When selecting the question you dragged, the property box does not update and the user changes the survey property thinking they are changing the question.**

### What is the expected behavior?

Reorder the question using drag and drop > when clicking on the question you dragged, the property box should show the properties for that question.

### How would you reproduce the current behavior (if this is a bug)?

**V1 Knockout - survey creator:
1. Add at least 3 questions. 

2. Choose one and reorder it (using drag&drop) -> See Drop-Down elements > Selected element changed to Survey (in the property box dropdonw elements)
 
3. Click on another question

4. Click on the question that you dragged 

5 . When selecting the question you dragged, the property box does not update and the user changes the survey property thinking they are changing the question.**

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

[Survey Creator V1](https://surveyjs.io/survey-creator/examples/free-nps-survey-template/knockoutjsv1)

Test code

```
your_code_here

```

### Specify your

* browser: EDGE and Chrome
* editor version: Survey Creator - V1

**Comment by JaneGaid** [comment]
Hello,
Thank you for reporting this issue. We will research it and post updates if any.

**Comment by andrewtelnov** [comment]
@jpardocimo @JaneGaid The bug has to be fixed in the library. Here is [the related issue in form-library repo](https://github.com/surveyjs/survey-library/issues/4814).
We need different behavior for Creator V1 and Creator V2.

Thank you,
Andrew
