### ISSUE TITLE
Page Description is not applied in a non-default locale if the Description is empty in the Default locale

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-creator#3403]
If the Default Translation doesn't contain a page description, the description for other languages isn't applied eigher.
To reproduce the issue, switch to the Preview and change a language in the top right corner. The page doesn't show the description.
Expected behavior: the page description appears with the value defined in the Translation tab.
https://user-images.githubusercontent.com/22372972/188571830-2f0a0274-8b22-452d-b1a7-bcaf1b1e1d88.mp4

[Example](https://plnkr.co/edit/5HTfr7Cmg1dJwfvR)

**Comment by andrewtelnov** [comment]
I could not reproduce it on [this example](https://codesandbox.io/s/focused-jones-uw66gl?file=/src/SurveyCreatorComponent.jsx:611-681).

Thank you,
Andrew
