### ISSUE TITLE
Cannot enter a white space to the Property Grid editors

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3439]
I want to set a title to a white space, however, the Title property resets to default (the `name` value) if I enter a white space in the Property Grid:
https://user-images.githubusercontent.com/22372972/190340210-a12b3b2a-0e51-4100-8991-2fd90cc02a11.mp4
![image](https://user-images.githubusercontent.com/22372972/190340414-e7f86264-4553-4c6b-b657-7ea3acaa1d82.png)

**Comment by novikov82** [comment]
This is the duplicate issue. Now "Title" editor supports the whitespace.
