### ISSUE TITLE
disable/enable ability to add new pages

### ISSUE THREAD

**Issue by mkgn** [surveyjs/survey-creator#344]
### Are you requesting a feature, reporting a bug or ask a question?

A feature

### What is the expected behavior?

An option to enable/disable the ability to Add new page to survey

I could only find a way to fully customize the toolbox items. But couldn't find a way to stop users from adding a new page. I think this should go as an option.

**Comment by tsv2013** [comment]
Could you please specify your scenario? Whether your users be able to create a single page survey only? Or they will be able to create a survey with limited number of pages? Whether users will be able to remove a page?

**Comment by andrewtelnov** [comment]
@mkgn There is an option, showPagesToolbox. You should set it to false. But it would show only one current page in this case. Do you want to allow your users to create one page survey?
editor = new SurveyEditor.Editor("editorElementId", {showPagesToolbox: false});

Thank you,
Andrew

**Comment by mkgn** [comment]
Excellent. yes I wanted to limit users to 1 page surveys. This option did it! thanks!
