### ISSUE TITLE
Expand/collapse the hierarchy/tree in the JSON Editor

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-creator#3447]
Support expand/collapse JSON nodes in JSON Editor:
![image](https://user-images.githubusercontent.com/22372972/190704779-836771bc-747d-485c-9430-9ed559b7e7ae.png)

**Comment by tsv2013** [comment]
One need to set the `aceBasePath` for language models as described here - https://github.com/surveyjs/survey-creator/issues/797

```JS
SurveyCreatorCore.AceJsonEditorModel.aceBasePath = "https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.10/";
```

Here is the working plunker example - https://plnkr.co/edit/rE2rQ1toMDlr2xbp
