### ISSUE TITLE
Add tabs/panels to Survey Editor

### ISSUE THREAD

**Issue by rlandrigan** [surveyjs/survey-creator#345]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the expected behavior?
Was curious if there was an easier method to add a tab to the Survey Editor -in addition to the Designer, JSON Editor, etc tabs - to allow for an application specific panel. Before I start making changes that will make upgrades a tad complicated:) wanted to check to see if there was an easier path to follow.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
Unfortunately there is no built-in way to accomplish this task.

**Comment by andrewtelnov** [comment]
@rlandrigan We have added this functionality some times ago.
Here is [the example](https://surveyjs.io/Examples/Survey-Creator/?id=tabscustomization).

Thank you,
Andrew
