### ISSUE TITLE
V2 bug - Logic editor always uses default translation for choice items, ignoring current locale

### ISSUE THREAD

**Issue by messyjoes1** [surveyjs/survey-creator#3460]
### Are you requesting a feature, reporting a bug or ask a question?
BUG

### What is the current behavior?
When having translated choice like
{ "text": {
  "sv": "label translated",
  "default": "label default"
}
the survey editor itself will correctly print "label translated", but logic edit dialog when listing choices will incorrectly print "label default"

#### Provide the test code and the tested page URL (if applicable)
https://plnkr.co/edit/vZ2dZBCpUNuyCRRr

^ Select first question, add a 'visible if' rule which references the second question

**Comment by andrewtelnov** [comment]
@messyjoes1 It is a designed behavior. It assumes that you are English speaking survey designer and it is better to show default language for you.
If you add this line into your example:
`SurveyCreator.localization.currentLocale = "sv";`
Then it will show item from "sv" locale.

Thank you,
Andrew
