### ISSUE TITLE
How to disable/remove 'fast entry' button

### ISSUE THREAD

**Issue by messyjoes1** [surveyjs/survey-creator#3463]
### Are you requesting a feature, reporting a bug or ask a question?
question

Is it possible to disable/remove 'fast entry' button for Choices completely ? Button seems to get disabled after logic relation are added to question, and only after survey page is reloaded. Non-skilled users can mess up logic relations when using it.

**Comment by JaneSjs** [comment]
Hi @messyjoes1,
To hide a Fast Entry option for a `choices` and `rateValues` property grid editors, handle the [creator.onSetPropertyEditorOptions](https://surveyjs.io/survey-creator/documentation/api-reference/creatorbase#onSetPropertyEditorOptions) options and disable the `options.editorOptions.allowBatchEdit` option.
```js
creator.onSetPropertyEditorOptions.add((sender, options) => {
    if (options.propertyName === "choices" || options.propertyName === "rateValues") {
      options.editorOptions.allowBatchEdit = false;
    }
});
```
[View Demo](https://codesandbox.io/s/musing-shannon-p6q8qn?file=/src/SurveyCreatorComponent.jsx)
