### ISSUE TITLE
Why is my custom (survey object) property not included on save?

### ISSUE THREAD

**Issue by ubuntux** [surveyjs/survey-creator#347]
### Are you requesting a feature, reporting a bug or ask a question?

**Question**

### What is the current behavior?

I created a new property `section` having a default value of _"Main Section"_. When I click on **Save Survey** button, the mentioned property **is NOT included** on the JSON data.

### What is the expected behavior?

The (custom) property **should be** included on the JSON data. 

#### Provide the test code and the tested page URL (if applicable)

Test URL: http://plnkr.co/edit/JRW09hbgkDsxnTbgboiD

### Specify your

* browser: Google Chrome (Mac) v 66.0.3359.181
* editor version: 1.0.23

**Comment by tsv2013** [comment]
The default value is not saved in the JSON. If you choose another one, it is saved ok for me. I've tested your plunk with `showJSONEditorTab: true`.

**Comment by ubuntux** [comment]
Is there a way to save default values in JSON?

**Comment by andrewtelnov** [comment]
@ubuntux I have looked at the code. Right now, there is no way to avoid the check that do not serialized the default value.
Is any particular reason for saving the default value into JSON?
the survey.section would return "Main Section". It will happen if you create a survey object without loading it from json:
```
var survey = new Survey.SurveyModel();
var val = survey.section; //val will be equal to "Main Section".
```
survey.section is a common JavaScript property. I believe it is the expected behavior.

Thank you,
Andrew

**Comment by ubuntux** [comment]
I understand... what if I want to check the value provided on a specific property? Let's say I want to validate the value? is that possible?

**Comment by andrewtelnov** [comment]
@ubuntux I have missed this question. You may use the [following event](https://surveyjs.io/Documentation/Survey-Creator/?id=surveycreator#onPropertyValidationCustomError).

```js
creator.onPropertyValidationCustomError.add(function(sender, options) {
  if(options.propertyName !== "section") return;
  if(options.value == "bad value") {
   options.error = "Please correct the value"; //show the error
  }
});
```

Thank you,
Andrew
