### ISSUE TITLE
I become very angry when popup disappears after scrolling reaches it's limit.

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#3477]
![Image](https://user-images.githubusercontent.com/17025812/192710535-60ade3b5-654f-4d73-8f37-35af0993f9fa.png)

**Comment by dk981234** [comment]
We need to use this property https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior, which is supported from 16.0 version of safari

**Comment by mikeamelin** [comment]
I guess it was fixed.
