### ISSUE TITLE
Add Question button. Can we hide system focus frame and use ours?

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#3501]
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SJS-Creator?node-id=554%3A357476

![Image](https://user-images.githubusercontent.com/17025812/193816505-4c347d44-abc1-4770-9075-0285de946d0d.png)

**Comment by tsv2013** [comment]
White outline border in Chrome
