### ISSUE TITLE
Ranking. Drag-n-Drop issue (keyboard navigation).

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#3504]
During the dragging item keeps its absolute position. It's not good. The better way it is to keep page position (no scrolling).

![Image](https://user-images.githubusercontent.com/17025812/193822597-6029e1fb-60c8-4435-ba2c-9e71bd7d8c33.png)

**Comment by novikov82** [comment]
fixed via https://github.com/surveyjs/survey-library/issues/4972
