### ISSUE TITLE
How to set matrix default values  for survey editor

### ISSUE THREAD

**Issue by NikolaMalezanoski** [surveyjs/survey-creator#352]
### Are you requesting a feature, reporting a bug or ask a question?
Will be good if we can set default values for  Columns and Rows  for matrix question. 

### What is the current behavior?
We can't set default values for matrix question, and odd option when  we add matrix question in survey editor values to be preset as we setup before.

### What is the expected behavior?
Pre set default value  before question has been add in survey editor

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
SurveyEditor.SurveyQuestionEditorDefinition.definition` = {
 matrix: {
                    tabs: [
                            { name: 'columns', index: 10 },
                            { name: 'rows', index: 11 }
                        ],
                    default: {
                        columns: [
                            'Bad',
                            'Slow',
                            'Good'
                        ],
                        rows: [
                            'product',
                            'service'
                        ]
                    }
                },
}


```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@NikolaMalezanoski Yes this feature: defaultRowValue and defaultPanelValue for panel dynamic is on our radar. It has been requested for several times last couple weeks.
We will very likely implement it this month. 

Thank you,
Andrew

**Comment by NikolaMalezanoski** [comment]
Hi @andrewtelnov , Thanks for your time to respond to my request 

Can you please let me know :
 - are we going to have and defaultColumnValue?
 - are we going to  have an option to setup key: value pair (test: value) for Rows Columns defaults 
 - are we going to have an option to customErrorValidate each Row/Column in the term to allow the only integer for values 

Kind Regards
Nikola

**Comment by andrewtelnov** [comment]
@NikolaMalezanoski I was thinking about defaultRowValue as:
`{columnName1: columnValue, columnName2: columnValue2}`.
The builder will show the matrix dynamic with one row, hidden addRow/deleteRow, with [vertical columns](https://surveyjs.io/Examples/Library/?id=questiontype-matrixdynamic-vertical) property on.
Could you please explain the customErrorValidate options?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@NikolaMalezanoski We have implemented [defaultRowValue](https://github.com/surveyjs/surveyjs/issues/1166). It is available in today release.
We are looking for a good example right now, to put it on our site. Do you have any real survey/form and data that we could use for an example?

Thank you,
Andrew
