### ISSUE TITLE
Cannot drop a question between two side-by-side question rows

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3539]
The Creator doesn't allow inserting an element between two rows of multiple questions:
![image](https://user-images.githubusercontent.com/22372972/195078473-87ed0b7e-66c6-46de-8c7b-21fea568d8da.png)

[Example](https://plnkr.co/edit/8WX4dsQxQ6bN9twZ).

**Comment by dmitrykurmanov** [comment]
I'll investigate the problem and write back ASAP, thanks

**Comment by JaneGaid** [comment]
Upon some research, it appears that fix would require significant change on Creator drag-drop functionality. We put this issue to our backlog and will look into it in the future.

For now, to insert a question between two multi-question rows, I suggest that you drop a question to the end of a first line:
![image](https://user-images.githubusercontent.com/22372972/196124428-4ea485bd-b859-4e77-ba13-8d986433fd67.png)
and enable its `Display the question on a new line` option:
![image](https://user-images.githubusercontent.com/22372972/196124455-3eb37c33-e4a1-4a1a-a544-352ac12326e1.png)

**Comment by JaneSjs** [comment]
Customer issue: T12283 - Drag&Drop SurveyCreator V2
https://surveyjs.answerdesk.io/internal/ticket/details/T12283
