### ISSUE TITLE
Creator creates broken JSON in some cases

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#3556]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
In some scenarios the creator accepts syntactically valid, but semantically invalid JSON and the mangles it to become even more invalid.

### What is the expected behavior?
It should throw errors or leave things as is, not make existing situations worse.

### How would you reproduce the current behavior (if this is a bug)?

1. Go to https://surveyjs.io/create-free-survey
2. Go to JSON Editor
3. Paste the example below, note the missing `value` key for the first row:

4. Switch back to the designer, you get no indicator that the `value` key is missing so maybe it's optional?
5. Switch back to the json editor, now you see the `value` key with value: `{"text": "row1"}`.
6. If you preview the survey and look at the saved data, it tries to serialize the object to a string and your data looks like this:
```json
{
    "question2": {
        "r2": "Column1",
        "[object Object]": "Column1"
    }
}
```

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/create-free-survey

Test code

```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "matrix",
     "name": "question2",
     "columns": [
      "Column1"
     ],
     "rows": [
      {
       "text": "row1"
      },
      {
       "value": "r2",
       "text": "row2"
      }
     ]
    }
   ]
  }
 ]
}
```

### Specify your

* browser: Brave latest
* editor version: latest

**Comment by andrewtelnov** [comment]
@SamMousa It has been fixed in [library repo](https://github.com/surveyjs/survey-library/issues/5049).

Thank you,
Andrew
