### ISSUE TITLE
An option to hide the Add New Question button

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3591]
Create an option to hide the Add New Question from survey pages in creator.
Usage scenario - the `read-only mode` for the creator where users cannot add new survey elements.

Source ticket: [T10981 - How can we hide "Add New Question" button from each page in survey creator on button click](https://surveyjs.answerdesk.io/internal/ticket/details/T10981).

**Comment by AkaHanshan** [comment]
Hi @andrewtelnov  I want to know now in V2, there are any solutions to config to hide the add question button in a panel or a page? thanks !

**Comment by andrewtelnov** [comment]
@AkaHanshan You can find this code in [this example](https://surveyjs.io/survey-creator/examples/setup-for-content-manager):
```js
// Hide the "Add Question" button from the design surface
settings.designer.showAddQuestionButton = false;
```

Thank you,
Andrew
