### ISSUE TITLE
A property with dependsOn doesn't display a Clear button although `null` is added as a legitimate value

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#3608]
You can see the problem in this demo: https://surveyjs.io/survey-creator/examples/dependsonproperties/

1. Open Property Grid -> Geo Location.
2. Select a Region.
3. Select a Country.

Expected result: You can reset Country using a Clear button.
Actual result: No clear button.

**Comment by andrewtelnov** [comment]
The issue has been fixed by [this PR](https://github.com/surveyjs/survey-creator/pull/3611).

Thank you,
Andrew
