### ISSUE TITLE
Logic Tab - Prevent users from leaving the Logic tab when a Logic Rule was not saved

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3609]
I created a new Logic Rule in the Logic Tab. I didn't save the rule, and switched to another creator tab. The Creator didn't show any warning messages and the rule simply vanished.

Suggestions: 
- [ ] Highlight a draft rule
- [ ] Do not allow users to leave the Logic tab without an unsave rule
- [ ] Display a confirmation message on an attempt to close the Logic tab with an unsaved rule.

https://user-images.githubusercontent.com/22372972/197581422-dec86b4f-061b-4d2b-acc9-221edee5c4c9.mp4

**Comment by JaneSjs** [comment]
Issue:
I create a logic rule in the Logic Tab:
![image](https://user-images.githubusercontent.com/22372972/229059071-ba22b556-bb7c-4966-9827-2e34f610fe2b.png)

I do not click Done and try to move away from the Logic tab. Even though the logic rule is correct, an error notification appears at the bottom of a page and I cannot move away from the Logic page:
![image](https://user-images.githubusercontent.com/22372972/229058930-a3c4f868-bbdc-4267-9875-7b7b30f64a5a.png)

Suggestions:
- [ ] Make it more clear that a user should click DONE to save the Logic rule:
![image](https://user-images.githubusercontent.com/22372972/229059364-fd6fbdb9-ad07-4484-890c-dc55a8c4aab6.png)

- [ ] If a rule is incorrect, make it more clear that a user should correct or Remove the logic rule:
![image](https://user-images.githubusercontent.com/22372972/229059646-01d8014d-bee1-4fd3-aca0-94569613ab28.png)

**Comment by mikeamelin** [comment]
Design — https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=16975-394016&t=KzvdzReUILsM1uCT-4

**Comment by andrewtelnov** [comment]
Implemented in this [ticket](https://github.com/surveyjs/survey-creator/issues/3948).

Thank you,
Andrew
