### ISSUE TITLE
The Mobile preview switcher tooltip always shows 'Landscape'

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-creator#3613]
Run the preview and enable mobile mode for the creator ([demo](https://surveyjs.io/survey-creator/examples/free-nps-survey-template/reactjs)). Observe the orientation switcher always shows 'Landscape'. It should be changed to 'Portrait' / 'Landscape'
![image](https://user-images.githubusercontent.com/22372972/197756926-ba2372da-5e46-48d1-81d9-38229dca9b4c.png)

**Comment by novikov82** [comment]
I think that better solution is to set constant hints for three buttons:
"Select device type"
"Switch orientation"
"Show invisible elements"

@RomanTsukanov could you suggest correct texts for this buttons?

**Comment by RomanTsukanov** [comment]
I think these buttons are not 100% intuitive. For example, how does an arrow indicates orientation? I wouldn't get it without a hint. So I suggest dynamic hints.

"Select device type"
"Switch to portrait orientation" / "Switch to landscape orientation"
"Show invisible elements" / "Hide invisible elements"
