### ISSUE TITLE
TypeError: Object(...) is not a function at Popup2.createModel

### ISSUE THREAD

**Issue by spencerjsmall** [surveyjs/survey-creator#3615]
### Are you requesting a feature, reporting a bug or ask a question?
I am experiencing this error when trying to render the boilerplate SurveyCreator in my Remix React app.

### What is the current behavior?
According to the log, the error occurs in the second line of the function
```
private createModel(): void {
    this.popup = createPopupViewModel(this.props.model, undefined);
    this.popup.initializePopupContainer();
  }
```
in survey-core's popup.tsx. 

"Object(survey_core__WEBPACK_IMPORTED_MODULE_2__["createPopupViewModel"]) is not a function."

### What is the expected behavior?
The boilerplate survey-creator should render as expected. I've had no issues with rendering surveyJs surveys in my app, but am struggling with adding creator.

### How would you reproduce the current behavior (if this is a bug)?
Because my app uses Remix, it may have to do with SSR. From my test code below, you can see how I instantiate the survey creator upon mount so the object has access to the document.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
import { useEffect, useState } from "react";

import "survey-core/defaultV2.min.css";
import "survey-creator-core/survey-creator-core.min.css";

import { SurveyCreator, SurveyCreatorComponent } from "survey-creator-react";

const creatorOptions = {
  showLogicTab: true,
  isAutoSave: true,
};

export default function SurveyCreatorWidget() {
  const [creator, setCreator] = useState<SurveyCreator>();
  useEffect(() => {
    var creatorObj = new SurveyCreator(creatorOptions);
    creatorObj.saveSurveyFunc = (saveNo, callback) => {
      //window.localStorage.setItem("survey-json", creator.text);
      callback(saveNo, true);
    };
    console.log(creatorObj);
    setCreator(creatorObj);
  }, []);
  if (creator && creator != null) {
    return <SurveyCreatorComponent creator={creator} />;
  } else {
    return <h1>error</h1>;
  }
}

```

### Specify your

* browser: Brave (chromium)
* editor version:

**Comment by spencerjsmall** [comment]
Downgraded survey-core, survey-creator-react, and survey-react-ui to 1.9.47 and it now works

**Comment by andrewtelnov** [comment]
@spencerjsmall The problem does not go away. We would like to see what we can do here.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@spencerjsmall Could you please check that you are using the same versions Creator and Library in your app by checking the version in "node_modules"?

Thank you,
Andrew

**Comment by spencerjsmall** [comment]
@andrewtelnov The issue was that the versions were different. I can't remember now which, but one of the surveyjs packages had survey-core@1.9.47 as a peer dependency, so having the whole suite at 1.9.52 caused the issue. Downgrading the suite to 1.9.47 fixed the issue.

**Comment by andrewtelnov** [comment]
@andrewtelnov Hm we require to have the same versions in our packages in the latest versions. The current version is 1.9.55.
You can try it.

Thank you,
Andrew
