### ISSUE TITLE
No custom property in Survey Creator

### ISSUE THREAD

**Issue by otebos** [surveyjs/survey-creator#3622]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
No custom property in Survey Creator

### What is the expected behavior?
Custom property visible :)

### How would you reproduce the current behavior (if this is a bug)?
I'm trying to add custom property in form builder but it fails.
I know I'm missing something but I cannot find what.
I've looked at 10+ different threads about this, but nothing works for me.
I'm using **Angular 14**. All examples are for **AngularJS**, but I don't think it should matter.

Should I import some another package to set property for Creator?

Code works (no errors) but there is no effect:
1. Custom property is not visible
2. When adding custom property in JSON editor shows an error of unknown property

#### Provide the test code and the tested page URL (if applicable)

```
import * as Survey from 'survey-angular';
import * as Creator from 'survey-creator-knockout';

Survey.StylesManager.applyTheme('modern');

Survey.Serializer.addProperty('question', {
  name: 'code',
  category: 'general',
  visibleIndex: 2,
});
@Component({
  selector: 'app-custom-form-builder',
  templateUrl: './custom-form-builder.component.html',
  styleUrls: ['./custom-form-builder.component.scss'],
})
export class CustomFormBuilderComponent implements OnInit, OnDestroy {

```

### Specify your

* browser: Chrome
* editor version: 1.9.55

**Comment by andrewtelnov** [comment]
@otebos You are using the wrong library to add your property. It should be
`import * as Survey from 'survey-core';`
We are going to release SurveyJS Creator for Angular that uses Angular rendering and it doesn't have knockout code. 
You can review [the following CodeSandbox](https://codesandbox.io/s/strange-roman-u2nwip?file=/package.json)

Thank you,
Andrew

**Comment by otebos** [comment]
Yes, I switched today to Angular-based version and it works :)
