### ISSUE TITLE
Survey doesn't scroll in page?

### ISSUE THREAD

**Issue by JosephBrooksbank** [surveyjs/survey-creator#3639]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?
If you add enough questions to a survey, you must scroll down to see the other questions. In the example on the survey-js website, the middle survey body portion has it's own scrollbar. In my instance of SurveyCreator, the whole page scrolls, so the toolbox and the survey settings are no longer accessible.

### What is the expected behavior?
The 'survey body' scrolls independently of the current page

### How would you reproduce the current behavior (if this is a bug)?
Add `survey-creator` and `survey-react` from npm version 1.9.55, create surveycreator instance, add questions until scrolling must occur.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://codesandbox.io/s/practical-villani-2g4l8d?file=/src/App.tsx

### Specify your

* browser: Chrome
* editor version: 1.9.55

**Comment by JaneGaid** [comment]
Hello @JosephBrooksbank,
Please update your sample and specify the height CSS attribute for your Survey Creator DIV element.
```
<div id="root" style="height: 100vh;"></div>
```

The [updated sample](https://codesandbox.io/s/heuristic-raman-dy1h4r?file=/public/index.html:1170-1214).

Let me know if it works for you.
