### ISSUE TITLE
Accessibility Issue for a Required Checkbox:  Ensures every ARIA input field has an accessible name

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3649]
Open [this demo](https://plnkr.co/edit/Q3KXhbPvP7DaugWT) and run the Fast Pass Check with the Accessibility Insights for Web checker. The following error appears:
![image](https://user-images.githubusercontent.com/22372972/200804358-ca9f656b-1ec2-4a3f-bbe2-63e40ea9ad90.png)

[FastPass_20221109_NPSSurveyQuestionSur.zip](https://github.com/surveyjs/survey-creator/files/9969876/FastPass_20221109_NPSSurveyQuestionSur.zip)

**Comment by dmitrykurmanov** [comment]
https://github.com/surveyjs/survey-library/commit/fa62656bcfe8c108db8e5edd4e50b149e13734c8
