### ISSUE TITLE
Use local fonts for the defaultV2 theme

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3654]
The defaultV2 theme uses Google fonts. Provide an option to manually supply fonts for the defaultV2 theme.

Original issue: [T11219 - Stop loading fonts from google](https://surveyjs.answerdesk.io/internal/ticket/details/T11219)

**Comment by dmitrykurmanov** [comment]
example of using:

```html
    <link rel="stylesheet" href="https://unpkg.com/browse/survey-core/defaultV2.fontless.css" />
    <style>
      @font-face {
        font-family: 'Dancing Script';
        src: url("DancingScript-VariableFont_wght.ttf");
      }

      :root {
        --font-family: 'Dancing Script', cursive;
      }
    </style>
````

**Comment by dmitrykurmanov** [comment]
need more info from @tsv2013  for the Creator

**Comment by dmitrykurmanov** [comment]
[lib + creator example (local css)](https://plnkr.co/edit/ETSASTTlMcsXpUVy)
