### ISSUE TITLE
Add new tool to toolbox with function call

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#366]
Cloned from the https://github.com/surveyjs/surveyjs/issues/1205

### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
I´m unable pass arguments  in a function. This function is inside a new tool (i add this tool to toolbox).
My tool have 3 questions. I pretend make the 3th question visible if  --> {question2} = ["obs"] or {question1} = 8. I´m trying using a function because the question name is always unique so i never know the name of the 1st or 2nd question name.

### What is the expected behavior?
Pass the name of the 2nd element of the JSON, with this i want to check if is true the "comment" became visible.   
I found this good example: https://surveyjs.io/Examples/Library/?id=condition-customfunctions&platform=jQuery&theme=default 
In this example they can call a function inside the json, the function "rowsWithValue".
I´m trying do the same but for a new tool. I´m using this example from "toolbox customization": https://surveyjs.io/Examples/Builder/?id=toolboxcustomization&theme=bootstrap 

#### Provide the test code and the tested page URL (if applicable)
My_code:

      function getPreviousName(currentName) {
        console.log(currentName); //When i run this code, in console show null
        return true;
        }

     Survey
        .FunctionFactory
        .Instance
        .register("getPreviousName", getPreviousName);

    Survey
        .JsonObject
        .metaData
        .addProperty("questionbase", "tag");

    SurveyEditor
        .editorLocalization
        .locales["pt"] = portugueseTranslation;

    SurveyEditor
        .SurveyQuestionEditorDefinition
        .definition["questionbase"]
        .properties = [
        "title",
        "name", {
            name: "tag",
            title: "Tag"
        }, {
            name: "visible",
            category: "checks"
        }, {
            name: "isRequired",
            category: "checks"
        }
    ];

    SurveyEditor
        .SurveyQuestionEditorDefinition
        .definition["questionbase"]
        .tabs = [
        {
            name: "visibleIf",
            index: 1
        }
    ];

    SurveyEditor.editorLocalization.currentLocale = "pt";

    var editorOptions = {
        questionTypes: ["rating", "comment", "radiogroup", "file", "panel"]
    };
    var editor = new SurveyEditor.SurveyEditor("editorElement", editorOptions);

    editor
        .toolbox
        .addItem({
            name: "AV",
            isCopied: true,
            iconName: "icon-default",
            title: "YN",
            category: "Evaluation",
            json: {
                type: "panel",
                name: "painel1",
                elements: [
                    {
                        type: "rating",
                        name: "question1",
                        isRequired: true,
                        titleLocation: "hidden",
                        rateValues: [
                            {
                                value: 1,
                                text: "Yes"
                            },
                            {
                                value: 2,
                                text: "No"
                            },
                            {
                                value: 8,
                                text: "Not rated"
                            },
                            {
                                value: 7,
                                text: "Not observed"
                            }
                        ]
                    },
                    {
                        type: "checkbox",
                        name: "question2",
                        title: "Add",
                        titleLocation: "hidden",
                        choices: [
                            {
                                value: "obs",
                                text: "Add comment"
                            }
                        ]
                    },
                    {
                        type: "comment",
                        name: "question3",
                        visibleIf: "getPreviousName({question2}) = \"obs\" or getPreviousName({question1}) = 8, //I pretend do this --> {question2} = ["obs"] or {question1} = 8, but with a function because the question name is allways unique so i never know the name of the 1st or 2nd question name
                        title: "Comment",
                        isRequired: true,
                        rows: 2,
                        placeHolder: "Add your comment"
                    }
                ],
                title: "New Tool"
            }
        });

    editor.saveSurveyFunc = function () {
        //save the survey JSON
        var jsonEl = document.getElementById('surveyJSON');
        jsonEl.value = editor.text;

        alert(jsonEl.value);
    }

### Specify your

* browser:Google Chrome
* browser version: 67.0.3396.99
* surveyjs platform (angular or react or jquery or knockout or vue):jquery
* surveyjs version:v1.0.16

**Comment by tsv2013** [comment]
@AxMM Let's dicuss it here

**Comment by tsv2013** [comment]
SurveyJS Builder has the [onQuestionAdded](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onQuestionAdded) event. In it's handler you can customize the elements have been added.

**Comment by AxMM** [comment]
ok, thanks. Can you show me same example how can i do that? 
So the main point is when the user double click on an element from the toolbox i manage the event handler to get the 2nd question name (my tool have 3 questions. I need the name of the 2nd to check the option of the user and do this for the question3: visibleIf: {question2} = ["obs"] or {question1} = 8), rigth?

**Comment by tsv2013** [comment]
Please check this plunk - https://plnkr.co/edit/Kv2fiqW8ZUF8R5xwyLUl?p=preview
You are adding complex panel and I've used the  the [onPanelAdded](https://surveyjs.io/Documentation/Builder/?id=surveyeditor#onPanelAdded) event.

**Comment by AxMM** [comment]
Thank you very much, problem solved 

`
options.panel.questions[2].visibleIf = "{"+options.panel.questions[1].name+"} = [\"obs\"]";
`
