### ISSUE TITLE
An option to hide the Add Question button

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3664]
It may be required to turn the Survey Creator into a read-only state while allowing some specific operations. Hence, the creator's `readOnly` option won't work. Instead, it is necessary to use the special events ([creator.onGetPropertyReadOnly](https://surveyjs.io/survey-creator/documentation/surveycreator#onGetPropertyReadOnly), [onElementAllowOperations](https://surveyjs.io/Documentation/Survey-Creator?id=surveycreator#onElementAllowOperations) to prevent and allow certain operations). It is also possible to hide the Toolbox (creator.toolboxLocation = "none"). However, there is no option to hide the Add Question button.

**Comment by OlgaLarina** [comment]
"showAddQuestionButton" property should be used
`settings.designer.showAddQuestionButton = false;`
[V2: Allow to hide "Add New Question" button on design surface #2970](https://github.com/surveyjs/survey-creator/issues/2970)
