### ISSUE TITLE
Creator Question Settings boolean text invisible

### ISSUE THREAD

**Issue by spencerjsmall** [surveyjs/survey-creator#3673]
With my boilerplate React survey creator component, I'm unable to see the text associated with boolean properties in a question's settings. This is what I see:
<img width="385" alt="Screen Shot 2022-11-15 at 1 20 29 PM" src="https://user-images.githubusercontent.com/61337412/202028111-4237b9ca-c282-4017-b8fb-f702da125c65.png">
It appears as though the spg_question flex-row element only contains the boolean toggle and no text element. 
<img width="921" alt="Screen Shot 2022-11-15 at 1 27 32 PM" src="https://user-images.githubusercontent.com/61337412/202028834-4f962b03-fa1e-459b-8f60-67250ac5026a.png">

Any advice to get this working? Thanks!

**Comment by JaneSjs** [comment]
Hello,
You can assosiate Boolean question values and corresponding labels using the following settings:
* [valueTrue]() and [labelTrue](https://surveyjs.io/form-library/documentation/questionbooleanmodel#labelTrue)
* [valueFalse ](https://surveyjs.io/form-library/documentation/questionbooleanmodel#valueFalse) and [labelFalse](https://surveyjs.io/form-library/documentation/questionbooleanmodel#labelFalse)

Please let me know if this what you need.

**Comment by spencerjsmall** [comment]
@JaneSjs thanks for the response. My issue occurs in the Property Grid of Survey Creator. I believe the resources you attached are for Survey Library. The boolean properties I'm referencing are default properties of survey questions, and they all appear to not have labels.

**Comment by spencerjsmall** [comment]
Resolved! survey-react-ui and survey-core had different versions (since survey-react-ui requires "*" survey-core... bad practice, no?). Had to add a `yarn` resolution to set survey-core at the same version as react-ui.
