### ISSUE TITLE
Property Grid - An empty cell remains in the Image Choices table when hiding an Image Link property from the table

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3683]
I removed the `Image or Video URL` property from the list view:
```
Survey.Serializer.getProperty("imageitemvalue", "imageLink").showMode = "form";
```
An empty cell remains:
![image](https://user-images.githubusercontent.com/22372972/202739009-bef4060c-2c68-4d74-9e1a-f43e2cf7d74e.png)

[Example](https://plnkr.co/edit/S28zfsrDNL1KRWq2)

**Comment by andrewtelnov** [comment]
@JaneSjs You will need to move to form Alt text as well:
```js
Survey.Serializer.getProperty("imageitemvalue", "imageLink").showMode = "form";
Survey.Serializer.getProperty("imageitemvalue", "text").showMode = "form";
```
[Example](https://plnkr.co/edit/lO6mmJk28uyUKsuf).

Thank you,
Andrew
