### ISSUE TITLE
Display Current/Maximum Allowed Characters when maxLength is defined for a survey property

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3694]
The `maxLength` property is defined for survey elements. For example:

* Survey and question titles
   - [T11363 - Showing the maxLength for question titles](https://surveyjs.answerdesk.io/internal/ticket/details/t11363)
   - [T11269 - Title inputs don't respect maxLength when copy pasted in the Survey directly (in place edits)](https://surveyjs.answerdesk.io/internal/ticket/details/T11269)
   - [T9290 - How to put a max length limit to the title of any question in the survey creator?](https://surveyjs.answerdesk.io/internal/ticket/details/T9290)
   - [T7333 - maxLength not working in creator V2](https://surveyjs.answerdesk.io/internal/ticket/details/T7333)
* Question Description
   - [T7849 - Description property validation](https://surveyjs.answerdesk.io/internal/ticket/details/T7849)

* Choice items
   - [T11365 - Showing the number of allowed characters for Radiogroup and Checkbox questions](https://surveyjs.answerdesk.io/internal/ticket/details/T11365)
   - [T8707 - Indicating radiogroup/checkbox/dropdown options value characters length](https://surveyjs.answerdesk.io/internal/ticket/details/T8707)

* The 'Other' option's caption:
   - [T7948 - Set the number of characters that can be entered in "other" of "checkBox"](https://surveyjs.answerdesk.io/internal/ticket/details/T7948)

* Any text input in Creator:
   -  [T7333 - maxLength not working in creator V2](https://surveyjs.answerdesk.io/internal/ticket/details/T7333)
   
Suggestion: inform users while typing about the number of remaining characters: for example, `5/10`.
![image](https://user-images.githubusercontent.com/22372972/204564950-d15d6a09-7db6-4013-a7b2-5d4721173aac.png)

**Comment by mikeamelin** [comment]
Design — https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SJS-Creator?node-id=15561%3A122420

**Comment by mikeamelin** [comment]
Design for Property Grid's editors.
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/SJS-Creator?node-id=15578%3A129634&t=JuUTH1bvrEraz6DP-4
