### ISSUE TITLE
Some translations of language strings overlap

### ISSUE THREAD

**Issue by rendaforstmane** [surveyjs/survey-creator#3703]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

The current creator language is set as ru (Russian), which is also visible in the attached image.
But I have also added the translation tab and the default language is set as lv (Latvian).
The creator's language must be as ru, but in some places I see lv (Latvian) as well, attached image.

### What is the expected behavior?

Translations into Latvian should not appear

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

https://codesandbox.io/s/surveyjs-creator-vue-forked-i9vwvk?file=/src/components/SurveyCreatorComponent.vue

### Specify your

* editor version: 1.9.61
![Screenshot 2022-12-05 at 09 56 55](https://user-images.githubusercontent.com/84146240/205587788-e282e4dc-ac30-49d8-aff7-34a23a58a7a3.png)
![Screenshot 2022-12-05 at 09 59 23](https://user-images.githubusercontent.com/84146240/205587799-5bbc858f-6c1d-4edc-a1ba-b7c1e9cf4264.png)
![Screenshot 2022-12-05 at 10 21 23](https://user-images.githubusercontent.com/84146240/205588336-7fc1ec18-7974-471c-aca5-8eab455d39cf.png)

**Comment by JaneSjs** [comment]
Hello @rendaforstmane,
We are working on this issue. Please stay tuned.

**Comment by JaneSjs** [comment]
Hello @rendaforstmane,
Thank you for your patience. 

You've enabled the `ru` localization for the Creator. However, not all strings may have their Russian translation. Therefore, when the localization doesn't contain a corresponding string, the Creator uses a string from a default localization. By default, it is Engligh, however, you've changed the `default` locale to `lv` (Latvian). Therefore, (Latvian) strings apprear when localizataion is missing for this string in the `ru` locale.

As an option, you can modify the localization and add missing strings: [russian.ts](https://github.com/surveyjs/survey-creator/blob/master/packages/survey-creator-core/src/localization/russian.ts).
Check the [To update the existing localization](https://github.com/surveyjs/survey-creator/tree/master/packages/survey-creator-core/src/localization#to-update-the-existing-localization) instructions for more information on how to update a localization.

Please drop me a line if you have any questions.

**Comment by JaneSjs** [comment]
Hi,
They come from the survey-library localization: [latvian.ts](https://github.com/surveyjs/survey-library/blob/master/src/localization/latvian.ts).

**Comment by JaneSjs** [comment]
Hello @rendaforstmane,
I closed this issue as completed. Should you have any questions or require further assistance, please feel free to reactivate this thread.
