### ISSUE TITLE
'SurveyCreatorComponent' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by Enflow-io** [surveyjs/survey-creator#3715]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
I'm trying to use SurveyCreatorComponent. React "react": "^18.2.0"
"survey-core": "^1.9.62",
"survey-creator-react": "^1.9.62",
"survey-react-ui": "^1.9.62",

```
function SurveyPage() {
    const options = {
        showLogicTab: true
    };
    const creator = new SurveyCreator(options);

    return <MainLayout>
        <SurveyCreatorComponent  creator={creator} />
    </MainLayout>

}
```

I get error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

### What is the expected behavior?
no error

### How would you reproduce the current behavior (if this is a bug)?
install last react and survey js, try to render component

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
import React from 'react';
import MainLayout from '../Layout/Layout';
import 'survey-core/defaultV2.min.css';
import { StylesManager } from 'survey-core';
import { SurveyCreator, SurveyCreatorComponent } from "survey-creator-react";
import "survey-creator-core/survey-creator-core.css";
import "survey-core/survey.i18n.js";
import "survey-creator-core/survey-creator-core.i18n.js";
import "survey-core/defaultV2.css";
StylesManager.applyTheme("defaultV2");
function SurveyPage() {
    const options = {
        showLogicTab: true
    };
    const creator = new SurveyCreator(options);
    return <MainLayout>
        <SurveyCreatorComponent creator={creator} />
    </MainLayout>

}

export default SurveyPage;


```

### Specify your

* browser: chrome
* editor version:

**Comment by JaneSjs** [comment]
Hello @Enflow-io,
You can run the following code sandbox and see how the Survey Creator component is registered in a React app: https://codesandbox.io/s/jolly-sea-5qgo17.

Also, I would suggest that you find more about the error on the Internet: perhaps, it doesn't directly related to the survey creator component. 

Should you have any question or require further assistance, please feel free to share a problematic example reproducing the issue.

**Comment by JaneSjs** [comment]
@Enflow-io,
Unfrortunately, I didn't get any information from you so far. Please feel free to reactivate this thread if you have further questions or require assistance.

Thanks
