### ISSUE TITLE
Custom actions are missing in the bottom toolbar on smaller screens

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3716]
Add a custom action and decrease the screen size. The bottom toolbar appears with default actions, but the custom action is missing:
![image](https://user-images.githubusercontent.com/22372972/206399904-9e3a99da-4e66-49cf-ae14-8f26500b8c29.png)
[Example](https://plnkr.co/edit/oNLJmX6EykzPe00O).

Original issue: [T11413 - Element menu customization - newly added element disappear](https://surveyjs.answerdesk.io/internal/ticket/details/T11413).

**Comment by OlgaLarina** [comment]
In order for the button to appear in the footer toolbar, you need to add it there yourself.
`creator.footerToolbar.actions.push(new Survey.Action({ ... }));`
