### ISSUE TITLE
The error message is showing under the panel

### ISSUE THREAD

**Issue by huyen-nguyenst** [surveyjs/survey-creator#3717]
Step:

Open Setting of a question 

View some detailed setting

Apply without selecting anything

Act: 

The error message is showing under the panel 

The user only sees this error message when scrolling down to the bottom of the setting

**Comment by JaneSjs** [comment]
Hello @huyen-nguyenst,
Would you please illustrate the issue with a demo screecast / screenshots? Please also specify the library version.

I look forward to your reply.

**Comment by JaneSjs** [comment]
@huyen-nguyenst,
Unfortunately, I didn't get a reproducible demo so far. Please feel free to reactivate this thread if you manage to share a problematic sample. We'll be happy to look into it.

Thanks
