### ISSUE TITLE
In 'byPage' edit mode, deleting a page in the `onPageAdded` event doesn't delete a page and a new page is disfunctional

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3726]
Run this [Example](https://plnkr.co/edit/e1JxOVlzohgWU0sJ). Add a new question to page 2. A confirmatino appears: click Cancel. Notice a new page is added, however, it doesn't conain the Add Question button and it is impossible to add a new element to it.
![image](https://user-images.githubusercontent.com/22372972/207536789-cbf84ffe-fdf8-4252-b8a5-1bf87b7773ba.png)

**Comment by tsv2013** [comment]
We desided with @JaneSjs to move it in Backlog for a while.
