### ISSUE TITLE
No options are displayed in the Visible If logic editor if a question uses choices of the other question

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3744]
I created two Radiogroup questions. For the second question, I and copied choices from the first question.
![image](https://user-images.githubusercontent.com/22372972/209338936-da0cd4ef-6d09-4a76-a082-ef01b411cc34.png)
Now, I'd like to use the second question in the Visible If expression, however, the editor doesn't display any available option:
![image](https://user-images.githubusercontent.com/22372972/209338688-51180e85-cf02-4438-bbf8-4be35a85dea1.png)

[Example](https://plnkr.co/edit/SJfWnz3toIY3AlAk).

**Comment by andrewtelnov** [comment]
@JaneSjs It has been fixed sometimes ago.

Thank you,
Andrew
