### ISSUE TITLE
Buttons in popup window are not translated and use english text

### ISSUE THREAD

**Issue by rendaforstmane** [surveyjs/survey-creator#3761]
Hello, @JaneSjs!
Still have some issues/confusion.

Same example, different languages. If I understood correctly, then: 

1. if localization contains those strings, then localization uses a string from `localization.currentLocale`. if not, then =>
2. localization use `SurveyKO.surveyLocalization.defaultLocale` 

Do I understand correctly?

I enabled the Creator with the `lv' language. This means that all strings (if they contain) must be translated into Latvian, otherwise, the strings change to English. But as you can see in the example, the pop-up action buttons are in English. And I know those buttons have an lv translation.
![Screenshot 2022-12-22 at 14 34 01](https://user-images.githubusercontent.com/84146240/209138489-24675b80-03ca-4810-8206-b1e15716b3c4.png)

And if I change the `default` language to `lv` those buttons translate into `lv`
![Screenshot 2022-12-22 at 14 50 25](https://user-images.githubusercontent.com/84146240/209138509-c176dc4c-0803-4910-86a9-a92857d19123.png)

Thank you!

_Originally posted by @rendaforstmane in https://github.com/surveyjs/survey-creator/issues/3703#issuecomment-1362804697_

**Comment by andrewtelnov** [comment]
@rendaforstmane It sounds as a bug. We will take a look.

Thank you,
Andrew
