### ISSUE TITLE
Wrong button UI once choose an option in more icon

### ISSUE THREAD

**Issue by PhuHoaframgia** [surveyjs/survey-creator#3763]
### Are you requesting a feature, reporting a bug or ask a question?

Report a bug

### What is the current behavior?

pls see my image

### What is the expected behavior?

this issue will be fixed

### How would you reproduce the current behavior (if this is a bug)?

![error-UI-option](https://user-images.githubusercontent.com/23466462/210371144-a087147e-1867-4b23-ac0a-fb72b6a9de34.gif)

I found this issue when i installed then use it
i re-checked on demo page but still same that issue

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

https://surveyjs.io/survey-creator/examples/customize-survey-creator-user-interface/reactjs

### Specify your

* browser:
Version 108.0.5359.124 (Official Build) (x86_64)

**Comment by andrewtelnov** [comment]
@PhuHoaframgia I am sorry, could you write what is wrong?
I can't find a wrong behavior here. You are changing the type and the "Add button" react accordingly.
The default type is "text" question. You can change it in your application.

Thank you,
Andrew

**Comment by PhuHoaframgia** [comment]
hi @andrewtelnov 
you can see once i choose an question in 3 dot option
the button will changed to "Add + type of that question"

how can we set it is always "Add question"? which config can i use?
Thanks

**Comment by PhuHoaframgia** [comment]
hi @andrewtelnov 
you can see once i choose a question in 3 dot option
the button will changed to "Add + type of that question"

how can we set it is always "Add question"? which config can i use?
Thanks

**Comment by andrewtelnov** [comment]
@PhuHoaframgia You simply override the creator string:
```js
// Override individual translations in an existing locale
const enLocale = SurveyCreatorCore.localization.getLocale("en");
enLocale.ed.addNewTypeQuestion = "Add question";
```
Here is [the example](https://plnkr.co/edit/0e6ZOpQZPhsmSHv8).

Thank you,
Andrew

**Comment by PhuHoaframgia** [comment]
@andrewtelnov 
Beside,
for now, the new question added will be the same with the question added before
is there any option that we can alway add new question is "text" type When click "add question"?

i try to use this 

```
SurveyCreator.settings.designer.defaultAddQuestionType = 'text';
```

But it seems just effect for first question added

Thank you

**Comment by JaneSjs** [comment]
Hello @PhuHoaframgia,
From what I gather, you wish so that the Add Question button always add a new Text question; you don't want to allow users to modify the type of added question and remove the question type selector (the ... button). Is that correct?

**Comment by PhuHoaframgia** [comment]
hi @JaneSjs @andrewtelnov 
i just want once i choose any question type in '...' on button
Please don't change "Add question" button to something else and alway add text question for me

i have an example
actually, i saw it works on my dev environment here (correct)

![11](https://user-images.githubusercontent.com/23466462/211828187-b6e35652-aeb9-437a-b34f-a7b2d2998300.gif)

but it is wrong my wish, when i build the code and deploy it 
on live (incorrect)

![12](https://user-images.githubusercontent.com/23466462/211828551-f7bd853e-876e-4971-a8a7-a01cb5318764.gif)

i hope it runs the same with dev environment

**Comment by JaneSjs** [comment]
Hello @PhuHoaframgia,
Thank you for the update. 

The `...` button is the question type selector button. As it name implies, it allows users to specify which question type will be added by default by clicking the Add Question button. When a user changes the default question type, the button's caption is updated correspondingly, for example, Add Rating.
![image](https://user-images.githubusercontent.com/22372972/212043101-90b28e32-fc2a-4236-9a1d-85b148f7fbc0.png)

In the first video you've shared, this button doesn't work as expected. We may reseach this issue further. Please specify the version of survey creator library.

If you don't want to allow users to change the default question type, you can hide it with CSS ([example](https://codesandbox.io/s/adoring-sound-xkqz53)).
```
.svc-page__question-type-selector {
    display: none
}
```
Please let me know if this is an option.
In this case, users will always add the default question type (e.g., Text questions), and can change a question type later on using the drop-down editor:
![image](https://user-images.githubusercontent.com/22372972/212044216-1e0b613b-4536-4875-8b0a-11244a24a0fa.png)

I look forward to your reply.

**Comment by PhuHoaframgia** [comment]
Thank you @JaneSjs 
you said: "In the first video you've shared, this button doesn't work as expected. "
but i want such a feature 😄 
i hope you will do it in the feature

"We may reseach this issue further. Please specify the version of the survey creator library."
ok, this is my enviroment

```
  "dependencies": {
    "@emotion/react": "11.10.5",
    "@emotion/styled": "11.10.5",
    "@hookform/error-message": "2.0.1",
    "@mui/lab": "5.0.0-alpha.113",
    "@mui/material": "5.11.1",
    "@mui/x-date-pickers": "5.0.12",
    "@reduxjs/toolkit": "1.9.1",
    "axios": "1.2.1",
    "bootstrap": "3.3.7",
    "bootstrap-datepicker": "1.9.0",
    "jquery": "3.6.3",
    "jquery-ui-dist": "1.12.1",
    "lodash": "4.17.21",
    "moment": "2.29.4",
    "notistack": "2.0.8",
    "plotly.js": "2.17.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-helmet-async": "1.3.0",
    "react-hook-form": "7.41.0",
    "react-icons": "4.7.1",
    "react-qr-code": "2.0.11",
    "react-query": "3.39.2",
    "react-redux": "8.0.5",
    "react-router": "6.5.0",
    "react-router-dom": "6.5.0",
    "redux": "4.2.0",
    "survey-analytics": "1.9.65",
    "survey-core": "1.9.65",
    "survey-creator-core": "1.9.65",
    "survey-creator-react": "1.9.65",
    "survey-pdf": "1.9.65",
    "survey-react-ui": "1.9.65",
    "surveyjs-widgets": "1.9.65",
    "universal-cookie": "4.0.4",
    "usehooks-ts": "2.9.1",
    "xlsx": "0.18.5"
  },
  "devDependencies": {
    "@types/jquery": "3.5.14",
    "@types/lodash": "4.14.191",
    "@types/node": "18.11.17",
    "@types/react": "18.0.26",
    "@types/react-dom": "18.0.9",
    "@types/react-router-dom": "5.3.3",
    "@typescript-eslint/eslint-plugin": "5.47.0",
    "@typescript-eslint/parser": "5.47.0",
    "@vitejs/plugin-react": "3.0.0",
    "eslint": "8.30.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-import-resolver-typescript": "3.5.2",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-prettier": "4.2.1",
    "eslint-plugin-unused-imports": "2.0.0",
    "husky": "8.0.2",
    "lint-staged": "13.1.0",
    "prettier": "2.8.1",
    "rollup-plugin-copy": "3.4.0",
    "typescript": "4.9.3",
    "vite": "4.0.0"
  }
}
```

**Comment by JaneSjs** [comment]
Hello @PhuHoaframgia,
Thank you for the update. 

Please let me clarify once again: the `...` button is designed exactly for this purpose: to allow customers to modify the type of a question which will be added by the Add Question button. If you don't want to modify the question type, simply do not use this button 😄

Have you considered hiding this button as it is demonstrated by my example above? Will it work for you?

**Comment by PhuHoaframgia** [comment]
it's ok @JaneSjs 
Thank you
i closed this issue
