### ISSUE TITLE
Handle Drag & Drop Events - No information about source, dragged, and target elements

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3767]
Usage scenario: to initiate events when a survey element is dragged and dropped: either from within the same page/panel or to a different page/panel altogether. Source ticket: [T11641 - Dragging and Dropping Elements](https://surveyjs.answerdesk.io/internal/ticket/details/T11641).

Suggestion: enhance the [onBeforeDrop](https://github.com/surveyjs/survey-creator/blob/master/packages/survey-creator-core/src/creator-base.ts#L1667)/[onAfterDrop](https://github.com/surveyjs/survey-creator/blob/master/packages/survey-creator-core/src/creator-base.ts#L1668) events and add information about:
* The source element: the parent element - where we drag an element from;
* A dragged element;
* A drop target.

Plus - consider the scenario when users drag and drop entire panels ([T11718 - Dragging a panel only recognizes the last element in the panel and dragging Pages is not recognized](https://surveyjs.answerdesk.io/internal/ticket/details/T11718)).

**Comment by dmitrykurmanov** [comment]
- [ ] add unit test `survey.onQuestionCreated` for panel. [The test](https://github.com/surveyjs/survey-library/blob/674302d50f0e035d2250bac9c050b88f74465871/tests/surveytests.ts#L12252).
- [ ] add `this.survey.questionCreated(this);` call to [the correspondent method](https://github.com/surveyjs/survey-library/blob/674302d50f0e035d2250bac9c050b88f74465871/src/panel.ts#L308)
- [ ]

**Comment by dmitrykurmanov** [comment]
```js
  creator.onAfterDrop.add((sender, options) => {
    const fromElement = options.fromElement;
    const draggedElement = options.draggedElement;
    const toElement = options.toElement;

    const parent = draggedElement.parent;
    const index = parent.elements.indexOf(draggedElement);

    console.log("Drag question: " + (draggedElement && draggedElement.name) + " to element: " + (toElement && toElement.name) + " at index: " + index + " from element: " + (fromElement && fromElement.name))
  });
```
