### ISSUE TITLE
How get total score for the quiz using matrix?

### ISSUE THREAD

**Issue by calintwf** [surveyjs/survey-creator#379]
Hello,

I have trouble building a simple quiz using matrix that use numbers as values (likert scale) and the submit should return the total score of the quiz! (like any mental health quiz)

Here is an [example to reproduce](https://psychology-tools.com/test/gad-7).

How can this be done? 
Can you build it using builder as demo for learning purposes?
Why there is no such example there? (mental health quiz are quite popular after all)

Note: my experimets gets me to a result with a list of answers instead of simple total score... 

Thanks!

**Comment by andrewtelnov** [comment]
@calintwf We simply do not have this functionality out of the box yet.
You can implement it. How do you use the survey? Do you need to work it in run-time only?

Thank you,
Andrew
