### ISSUE TITLE
Image Question - Display a plus / upload icon instead of a missing image icon

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3796]
- [x] surveyjs/survey-library#5731

![image](https://user-images.githubusercontent.com/22372972/214116082-e330243d-c211-4d29-85b5-66977a324073.png)

Suggestion: display an upload / plus button instead - for example, how it's done for Image Picker:
![image](https://user-images.githubusercontent.com/22372972/214116166-50e596d4-79ba-4c46-ba0e-5daf3abc6609.png)

Original issue: [T10823 - The missing image icon in the static image question](https://surveyjs.answerdesk.io/internal/ticket/details/T10823)

**Comment by mikeamelin** [comment]
Need to discuss.

**Comment by mikeamelin** [comment]
Design — https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=16481%3A262108

**Comment by JaneSjs** [comment]
FYI: In the following thread, a customer wants to display nothing when an image was not loaded: T12793 - onUploadFile error handling
https://surveyjs.answerdesk.io/internal/ticket/details/T12793.
