### ISSUE TITLE
How to set value of custom properties

### ISSUE THREAD

**Issue by rabberbock** [surveyjs/survey-creator#380]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
Currently, I can add a new property to a survey following the docs at https://surveyjs.io/Examples/Builder/?id=addproperties.

The docs do not mention the proper way of setting this value programmatically. What is the proper way of doing that given an element? Is it just `element.new_property = value`. Doing it this way does not seem to include that value in the serialized json.

* browser:
* editor version: 1.0.32

**Comment by andrewtelnov** [comment]
@rabberbock You may set value directly as you wrote. You may have the default value as well:
Here is the [full docs](https://surveyjs.io/Documentation/Builder/#addproperties)
Please show your code, so we can find the problem.

Thank you,
Andrew

**Comment by rabberbock** [comment]
Hi @andrewtelnov, thanks for the link!

I am first adding the property like this:
 ```
SurveyReact.JsonObject.metaData.addProperty(className, {
    name: 'customSettings'
  });
```

And then I set it like this:
`element.customSettings= JSON.stringify(settings);`

However when I retrieve the survey with `editor.text`, It does not return those settings.
Am I missing a step?

Thanks!

**Comment by andrewtelnov** [comment]
@rabberbock What is className? Do you mean "survey"?

Thank you,
Andrew

**Comment by rabberbock** [comment]
Yep, I have an array like so, `['survey', 'panel']` and iterate and add the custom type for each one

**Comment by andrewtelnov** [comment]
@rabberbock What for me. Here is [the example](https://plnkr.co/edit/PUlcjoy1GkJwnvfOt4fd?p=preview)
I guess the issue with SurveyReact.
You should use the knockout version of SurveyJS library for Builder(Editor) and SurveyReact for running SurveyJS Library.

Thank you,
Andrew

**Comment by rabberbock** [comment]
Yep, that is exactly what it was. Thanks! Was Survey React supposed to be used the way I was using it before?

**Comment by rabberbock** [comment]
Thanks so much for the quick response! Much appreciated! It works great.

**Comment by IngWARP** [comment]
Hi Andrew
I tried your example with some small changes 
```
Survey.JsonObject.metaData.addProperty("question", {
   name: "uuid",
   type: "text",
 });
 
var editorOptions = {};
var editor = new SurveyEditor.SurveyEditor("editorElement", editorOptions);

editor.survey.uuid= "My Settings";
```
And can't get it work, What am I missing?

**Comment by andrewtelnov** [comment]
@IngWARP Because you have added a new property into "question" and assign it into "survey".
Here is the working code.
```
Survey.JsonObject.metaData.addProperty("survey", {
   name: "uuid",
   type: "text",
 });
 
var editorOptions = {};
var editor = new SurveyEditor.SurveyEditor("editorElement", editorOptions);

editor.survey.uuid= "My Settings";
```
And here is [the documentation](https://surveyjs.io/Documentation/Builder/#addproperties)

**Comment by Thippeshbethur** [comment]
how to get the Property value?

**Comment by tsv2013** [comment]
@rabberbock @Thippeshbethur  Andrew answered in this comment - https://github.com/surveyjs/survey-creator/issues/380#issuecomment-475722954
You can access the `uuid` property of designed survey via the `editor.survey.uuid`
