### ISSUE TITLE
Logic Editor / Tab - The First Row/Panel entry is displayed in a list of available elements

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3803]
Original issue: [T11790 - Choose names to display for question in visibleIf statements](https://surveyjs.answerdesk.io/internal/ticket/details/T11790).
***
I have a Panel Dynamic / Matrix Dynamic questions. I want to configure a logic expression using these questions.

In Logic Editor, a list of available elements contains the first row / first panel:
![image](https://user-images.githubusercontent.com/22372972/214549437-fb9731dc-7b39-4517-8ff9-8a2bf2cd0fd0.png)

In Logic tab: it is different. A list of available elements contains the panel/row element (e.g., question1.panel.question2) and also a question instance of the first panel/row (e.g., question1[0].question2). The same applies to Matrix Dynamic:
![image](https://user-images.githubusercontent.com/22372972/214549923-5dd764e8-8464-4694-b824-f6c377b574ee.png)

I see the following issues with this approach:
* Questions are literally duplicated.
* If Matrix Dynamic contains more rows (e.g., 5 rows), these rows are not displayed in a Logic Editor - Why?
* If I remove question1[0] entried from a list using [creator.onConditionQuestionsGetList](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onConditionQuestionsGetList) function, it will be ok in the Logic tab:
![image](https://user-images.githubusercontent.com/22372972/214559080-25c6efda-7df8-4f5a-8859-b0b5e50f86c4.png) 
However, I won't see any question1 (Panel Dynanic) questions in the Visible If expression editor: because all items will be filtered out:
![image](https://user-images.githubusercontent.com/22372972/214559223-98f5f34c-a036-4d42-b038-6f73d633e346.png)

[Example](https://codesandbox.io/s/young-cache-7chl6s?file=/src/SurveyCreatorComponent.jsx).

**Comment by andrewtelnov** [comment]
@JaneSjs From the v1.9.76 the following code can be added to hide these elements:
```js
Survey.settings.matrixMaxRowCountInCondition = 0;
Survey.settings.panelDynamicMaxPanelCountInCondition= 0;
```

Thank you,
Andrew
