### ISSUE TITLE
Multiple Text Questions - Impossible to add items from a design surface

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3806]
For choice-based questions, it is possible to add an item using the plus sign:
![image](https://user-images.githubusercontent.com/22372972/215129615-87c4b4fe-9edf-473b-9c5a-6a94fd89ee83.png)

For Multiple Text question, items can be added from a property grid only.
![image](https://user-images.githubusercontent.com/22372972/215129794-dbb3aa06-4008-48f4-aecb-fee0a53c5577.png)
 
Suggestion: allow adding Multiple Text items from a design surface.

**Comment by andrewtelnov** [comment]
@JaneSjs Here is [the duplicated issue](https://github.com/surveyjs/survey-creator/issues/2313).

Thank you,
Andrew
