### ISSUE TITLE
The event which is raised when reordring Property Grid item collections (e.g., pages, choices)

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3848]
Original issue: https://surveyjs.answerdesk.io/internal/ticket/details/t11721.

The `creator.onAfterDrop` event is not raised when a user reorders pages or choices in a property grid: [example](https://codesandbox.io/s/nervous-lumiere-ybs91z?file=/src/SurveyCreatorComponent.jsx).
Expected behavior: the `creator.onAfterDrop` event is raised and contains information about the dropped item.

@RomanTsukanov  Proposal we will have three DnD event types:

1. `creator.onAfterDrop` - for survey elements on Design Surface - **legacy! we can't change it**
2. `creator.onChoicesAfterDrop` - for "choices" reordering
3. `Survey.onMatrixRowAfterDrop` - for matrices dnd

**Comment by dmitrykurmanov** [comment]
wating for @JaneSjs review
