### ISSUE TITLE
I can't add New logic when create new survey.

### ISSUE THREAD

**Issue by wb-ts** [surveyjs/survey-creator#3856]
When I integrate SurveyJs to React web application , I can't see the "Add New Rule" button to customize the flow of the survey even clicked Logic which was shown on the top bar.

I integrated the SurveyJs in my React Application like this.

```
import "survey-core/defaultV2.css";
import "survey-creator-core/survey-creator-core.css";
import { SurveyCreator, SurveyCreatorComponent } from "survey-creator-react";

const options = {
  haveCommercialLicense: true,
  showLogicTab: true
};
export default function SurveyComponent() {
  const creator = new SurveyCreator(options);
  return <SurveyCreatorComponent creator={creator} />;
}
```

https://prnt.sc/ITBNjpKjET5L

**Comment by JaneSjs** [comment]
Hello @wb-ts,
I tested the following Code Sandbox React application on the latest version but didn't get any issue adding a new logic rule: [Example](https://codesandbox.io/s/agitated-mclaren-3ckgzf).
![image](https://user-images.githubusercontent.com/22372972/221490976-ae93dd3d-c40c-4532-8aad-aed5a7b687cf.png)

I don't see any issues with your code. Which version do you use?
Could you please also check to see if there is any errors in a browser console?

I look forward to your reply.

**Comment by wb-ts** [comment]
Did you try without setting creator.JSON as default?

**Comment by JaneSjs** [comment]
Hello,
I updated my sample and reset the initial survey JSON: [example](https://codesandbox.io/s/agitated-mclaren-3ckgzf?file=/src/SurveyCreatorComponent.jsx).

Please clarify how to reproduce the issue.
