### ISSUE TITLE
Managing calculatedValues from UI

### ISSUE THREAD

**Issue by rudyp321** [surveyjs/survey-creator#3857]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question

### What is the current behavior?

Is it possible to have the end user define and edit the calculated values of a survey without having to go into the JSON Editor tab to do so?

**Comment by JaneSjs** [comment]
Hello @rudyp321,
Yes, of cource. Calculated values are available in the Logic property grid category of a survey:
![image](https://user-images.githubusercontent.com/22372972/221490097-d22ec727-8555-442e-b85b-e1ca2098bb20.png)

Please let me know if you have any questions or require further assistance.
