### ISSUE TITLE
I can't start up the project

### ISSUE THREAD

**Issue by Plusuan** [surveyjs/survey-creator#3858]
Hello, i would like to know if i am doing something wrong!

I cloned the proyect and i'm trying to start it. I follwed the documentation but i think it has a problem with webpack dependency cause' i can't see it on my browser (on localhost).

Have you any suggsestion or anothers steps to follow? Maybe the documentation hasn't been updated?

Cheers, ty!

**Comment by JaneSjs** [comment]
Hello @Plusuan,
Would you please clarify whether you got any built errors? Could you please share some screenshots/output illustrating the result?
