### ISSUE TITLE
Property Grid doesn't show error on entring empty value

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3864]
Original issue:
[T12213 - How to add required validation on survey title and description](https://surveyjs.answerdesk.io/internal/ticket/details/T12213)

[Example](https://codesandbox.io/s/surveyjs-angular-forked-fuoh9j?file=/src/app/components/creator.component.ts).

I set a `survey.title` property as required, and specified default title & description. However, the creator still allows me to leave empty values: 
```
import { Serializer } from "survey-core";

Serializer.getProperty('survey', 'title').isRequired = true;
...
creator.survey.title = "Sample Survey Title";
creator.survey.description = "Sample Survey Description";
```
![image](https://user-images.githubusercontent.com/22372972/222386279-115b7fd0-f25e-4b82-8198-77c92fedb803.png)

**Comment by andrewtelnov** [comment]
@JaneSjs Property Grid doesn't allow to enter an empty value, but it doesn't show an error. I have fixed the issue by PR above.

Thank you,
Andrew
