### ISSUE TITLE
Removing the runexpressiontrigger class throws an error on an attempt to add a survey trigger

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3872]
[Example](https://codesandbox.io/s/quirky-blackburn-y47je3?file=/src/SurveyCreatorComponent.jsx)
[Original issue](https://surveyjs.answerdesk.io/internal/ticket/details/T12241)

Task: to remove the Run Expression trigger from a list of available trigger types.
The following code works for a complete trigger:
```
import { Serializer } from "survey-core";

Serializer.removeClass("completetrigger");
```
![image](https://user-images.githubusercontent.com/22372972/222750991-a52d4efc-b847-442f-a45b-fb15bbe47ba1.png)

However, if you run the following code, the `Cannot read properties of null (reading 'getType')` exception is thrown on an attempt to add a trigger.
```
import { Serializer } from "survey-core";

Serializer.removeClass("runexpressiontrigger");
```

**Comment by andrewtelnov** [comment]
@JaneSjs @OlgaLarina The issue can be disapparead after this implementing this [PR](https://github.com/surveyjs/survey-library/pull/5745).
We will stop render choices if they closed.

Thank you,
Andrew
