### ISSUE TITLE
Inserting a previous answer into the text of a subsequent question

### ISSUE THREAD

**Issue by AlanJKDuval** [surveyjs/survey-creator#388]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
n/a

### What is the expected behavior?
Is there a way to insert the text of an answer from one question into the text of a subsequent question? I want to be able to reference back to the answer of one particular question in several later questions, e.g. What value do you place on <item selected above>? 

### How would you reproduce the current behavior (if this is a bug)?
n/a

#### Provide the test code and the tested page URL (if applicable)
n/a
Tested page URL:
n/a
Test code
n/a
```
your_code_here
n/a
```

### Specify your

* browser: Chrome Version 68.0.3440.106
* editor version: 1.0.37

**Comment by AlanJKDuval** [comment]
Thanks. I don't think that quite does what I'm looking to achieve.

Here's a further example to help clarify:

Q1: Do you prefer Apples or Bananas?
A1: Apples
A2: Bananas

Q2: How much would you expect to pay for Bananas?

So the word Bananas is inserted into the question text because the respondent selected it in the previous question.

Thanks

Alan

**Comment by AlanJKDuval** [comment]
Thanks. I'll read up, and see if I can make sense of it.

**Comment by benirose** [comment]
I believe you can also use expressions to do this. If you set Q2 text to be `How much would you expect to pay for {Q1}`, it should dynamically use the answer from Q1 in the question text for Q2.
