### ISSUE TITLE
Allow to edit question and panel descriptions on designer surface - Description Placeholder doesn't appear for newly added questions

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#3889]
If the description is empty for questions and panels, then the only way to enter the text is to use to the proprety grid. 
Suggestion: allow users to enter the description for questions and panels from the design surface, like it's done for a survey and pages:
![image](https://user-images.githubusercontent.com/22372972/224926968-2ed5aab1-ec95-4e57-8043-c513b55f684d.png)

***
Source issue: [T12334 - Allow descriptions to be added to fields and panels in-line](https://surveyjs.answerdesk.io/internal/ticket/details/T12334)

**Comment by andrewtelnov** [comment]
The following code is working for showing panel title and question description:
```js
Survey.Serializer.findProperty("question", "description").placeholder = "Enter question description";
Survey.Serializer.findProperty("panel", "title").placeholder = "Enter panel title";
```

**Comment by JaneSjs** [comment]
+1 
T14525 - Display question description with placeholder inline in Creator
https://surveyjs.answerdesk.io/internal/ticket/details/T14525

**Comment by JaneSjs** [comment]
@andrewtelnov, undortunately, the above code doesn't work for newly added questions.
![image](https://github.com/surveyjs/survey-creator/assets/22372972/c95fff6b-02c4-4283-ab55-306e44d42318)

https://codesandbox.io/s/brave-breeze-gkyzwr?file=/src/SurveyCreatorComponent.jsx

**Comment by andrewtelnov** [comment]
The issue is fixed by [this PR](https://github.com/surveyjs/survey-library/pull/6923) in the library.

Thank you,
Andrew
