### ISSUE TITLE
Portuguese Translation Keys

### ISSUE THREAD

**Issue by tiagofranciscosta** [surveyjs/survey-creator#3893]
###Question

What are the keys that translates these elements in the designer? I've updated the portuguese translation file and everything got translated except for these ones:

![image](https://user-images.githubusercontent.com/43204804/225042810-9f6050c7-500c-48e2-ac3a-288babdaaada.png)

>> QuestionTitle

![image](https://user-images.githubusercontent.com/43204804/225042857-a3e0cb6c-deda-42e9-bb48-a432b63beb64.png)

>> Select All, None, Other (describe)

![image](https://user-images.githubusercontent.com/43204804/225043002-cca64f41-97ba-4c86-a04f-e1b53f2f3591.png)

>> No, Yes

![image](https://user-images.githubusercontent.com/43204804/225043055-ae9b81e5-dd34-499b-8b24-c73d056c279e.png)

>> Drop a file here or click the button below to load the file., Choose File

Can't figure it out if I missed some translations or the elements are not simply being translated.
Thanks in advance.

**Comment by JaneSjs** [comment]
Hello @tiagofranciscosta,
I created the following demo and applied the `pt` locale to a survey: [Example](https://codesandbox.io/s/red-field-hos2yp?file=/src/survey_json.js:39-41).

I checked it with your screenshots, and configmed that all those text are translated. Please review the demo and let me know if it helps.

**Comment by tiagofranciscosta** [comment]
Hi @JaneSjs.

Thanks for your reply. I've been checking it and can't find the problem at our end.

I've isolated and created also a demo here: [Demo](https://codesandbox.io/s/nifty-dubinsky-j57zm2). They don't seem to be translated. Can you please give a quick check?

Thanks in advance.

**Comment by tiagofranciscosta** [comment]
Hi @JaneSjs. Did you had the chance to look at this demo? Or should we open a new question? Many thanks.

**Comment by JaneSjs** [comment]
Hi @tiagofranciscosta,
Thank you for sharing the demo. I'll check it and get back to you shortly.

**Comment by JaneSjs** [comment]
Hello @tiagofranciscosta,
Please accept my apologies for the delayed reply. 
The Question Title Pattern is translated based on a survey's `locale` property value:
![image](https://user-images.githubusercontent.com/22372972/228858251-4ce6be6a-8749-47be-b5d6-36b5f8cfd451.png)

To get this property translated, set the `survey.locale` property to `pt`.
```
creator.JSON = {
  locale: "pt",
...
}
```
![image](https://user-images.githubusercontent.com/22372972/228859365-2c347784-f10d-44c2-82e8-3d1f6aba8815.png)

Please refer to the following demo: https://codesandbox.io/s/cool-joliot-b2tjjy?file=/src/index.js:438-470.

For the record: SurveyJS translation is community-based. This means that some items may not be translated. You may wish to modify or add missing translations. Please refer to our guides for more information:
* [Form Library: Localization](https://surveyjs.io/form-library/documentation/survey-localization)
* [Survey Creator: Localization](https://surveyjs.io/survey-creator/documentation/localization)

Please feel free to reactivate this thread if you have any questions.
