### ISSUE TITLE
[Question] is there any option to edit logo position?

### ISSUE THREAD

**Issue by HoaDevDn** [surveyjs/survey-creator#3903]
### Are you requesting a feature, reporting a bug or ask a question?

Proposal feature: Edit logo position

### What is the current behavior?

i saw these texts on localization file, but i don't see any action on survey UI

```
    logoPosition: 'Logo position',
    addLogo: 'Add logo...',
    changeLogo: 'Change logo...',
    logoPositions: {
      none: 'Remove logo',
      left: 'Left',
      right: 'Right',
      top: 'On the top',
      bottom: 'In the bottom',
    },
```

![image](https://user-images.githubusercontent.com/23466462/226152775-4a692a5f-2b98-42f6-a4b2-c977e2b0de62.png)

### What is the expected behavior?

I hope you can add "Edit logo position" option  so that i can edit logo position

Tested page URL: https://surveyjs.io/survey-creator/examples/free-nps-survey-template/reactjs

**Comment by JaneSjs** [comment]
Hello @HoaDevDn,
Thank you for your suggestion. I forwarded it to the development team for further consideration. In the meantime, you can edit a survey JSON model and specify the [survey.logoPosition](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#logoPosition) property.
```
{
 "title": "Survey Title&Logo demo",
 "description": "Please take look at the survey title and logo. Test the settings on the right panel ->",
 "logo": "https://surveyjs.io/favicon.ico",
 "logoWidth": "60px",
 "logoHeight": "60px",
 "logoPosition": "right"
...
```
Please let me know if you have any questions.

**Comment by JaneSjs** [comment]
Hello @HoaDevDn,
Please use the following code to display the `Survey | Logo Position` property in the `Property Grid | Logo` category:
```
const logoPositionProp = Survey.Serializer.findProperty("survey", "logoPosition");
logoPositionProp.category = "logo";
logoPositionProp.visible = true;
```
[Example](https://plnkr.co/edit/SsE6anzb9AmOoe8V)

Please feel free to reactivate this thread if you have further questions.

**Comment by SamMousa** [comment]
Why is this specific property hidden by default?
