### ISSUE TITLE
Warning in console in React Codesandbox for any Creator example

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#3908]
Here is the warning text:
"Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
    at SurveyActionBar (https://hcsy4n.csb.app/node_modules/survey-react-ui/survey-react-ui.js:1729:28)"

**Comment by grerealadvisor** [comment]
Yes i have it locally
I'm using version 1.9.78
and react 18.2.0

**Comment by andrewtelnov** [comment]
I don't see that vite has something to deal with this error.
I have the following packages:
```json
    "react": "latest",
    "react-dom": "latest",
    "survey-core": "latest",
    "survey-creator-core": "latest",
    "survey-creator-react": "latest",
    "survey-react-ui": "latest"
```
We will continue to investigate. 

Thank you,
Andrew

**Comment by tsv2013** [comment]
It looks like I've fixed the issue. We'll check it after release.

**Comment by tsv2013** [comment]
I've checked our examples, they looks ok.
