### ISSUE TITLE
Ranking question css breaking in preview tab

### ISSUE THREAD

**Issue by thomasguittonneau** [surveyjs/survey-creator#3915]
A bug or a changement seems to be introduce in version 1.9.66
ranking input doesn't works anymore into preview tab

**in 1.9.65 <**
![image](https://user-images.githubusercontent.com/5966888/226932743-9fc9bda7-bfd0-4ec5-8b80-cbc64c063a0e.png)

**in 1.9.66 >**
![image](https://user-images.githubusercontent.com/5966888/226932254-7e1c4d09-4cdb-42cc-bd6e-80e2d55ef0db.png)

### Specify your

* browser: Chrome/firefox
* editor version: 1.9.79 react

**Comment by JaneSjs** [comment]
Hello @thomasguittonneau,
I didn't reproduce this issue in the latest version of our libraries. I tried it with our online demos: https://surveyjs.io/survey-creator/examples/free-nps-survey-template/reactjs.
![image](https://user-images.githubusercontent.com/22372972/227271971-38f38985-1cf2-4c84-ae54-24945dc5bda9.png)

Please clarify how to reproduce the issue.
