### ISSUE TITLE
Survey Creator V1 - A Custom Widget Stops working with v1.9.71 and newer

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3920]
A custom `datepicker` widget no longer works after updating Survey Creator V1 to the latest version (v1.9.79)
Original issue: T12476 - Problems with custom widgets
https://surveyjs.answerdesk.io/ticket/details/T12476

**Comment by andrewtelnov** [comment]
@JaneSjs The previous approach with "htmlTemplate" + default rendering was supported by knockout only.
This task can be implemented for all frameworks with the following code in the latest version. It hides all properties except properties in the base question type and shows a standard date-picker:
```js
import { ComponentCollection } from "survey-core";

ComponentCollection.Instance.add({
      //Unique component name. It becomes a new question type. Please note, it should be written in lowercase.
      name: "datepicker",
      //The text that shows on toolbox
      title: "Date Picker",
      //The actual question that will do the job
      questionJSON: {
        type: "text",
        inputType: "date"
      }
    });
```

Thank you,
Andrew
