### ISSUE TITLE
Modify event to prevent users from adding or removing choices from a design surface.

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3923]
[Original Thread](https://surveyjs.answerdesk.io/internal/ticket/details/T12479)

The `creator.onSetPropertyEditorOptions` prevents users from adding or removing choices in a property grid; however, it doesn't work for a design surface.
[Example](https://plnkr.co/edit/dR2viw3KBlfNRezv)
```
 creator.onSetPropertyEditorOptions.add(function(sender, options){
        if(options.propertyName === 'choices'){
            options.editorOptions.allowAddRemoveItems = false;
            options.editorOptions.allowRemoveAllItems = false;
            options.editorOptions.showTextView = false;    
        }
    })
```
Property Grid - OK
![image](https://user-images.githubusercontent.com/22372972/227472705-726b9c54-1bad-4d40-857d-6d2990908a3f.png)

Design Surface - Can still add and remove choices
![image](https://user-images.githubusercontent.com/22372972/227472776-d0b6504f-2031-4966-b242-ab30e9ce2d39.png)

**Comment by novikov82** [comment]
We are going to modify `onCollectionItemAllowOperations` event.
`allowAdd` option will help
