### ISSUE TITLE
Customize survey settings html editor in react

### ISSUE THREAD

**Issue by rabberbock** [surveyjs/survey-creator#393]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
I am trying to customize the html editor that is shown in the survey settings. I have found this https://surveyjs.io/Examples/Builder/?id=ckeditorpropertyeditor example very useful.

However, I am using surveyJs in react and was wondering if there is a better react way of doing this. I would like to use a react component as the display for a widget. Is there a way I would be be able to do this? Or do I need to interact with the actual html elements on the page?

Thanks,

Raffi

**Comment by andrewtelnov** [comment]
@rabberbock our SurveyJS Builder (Editor) is written in knockout. It lives perfectly with react, but you have to customize the Editor in pure JavaScript mostly.
What react component do you want to use? We will take a look.

Thank you,
Andrew

**Comment by rabberbock** [comment]
I was looking to use something like https://www.froala.com/wysiwyg-editor/docs/framework-plugins/react.

Thanks!

**Comment by tsv2013** [comment]
You can use the Froala editor as a JavaScript control similalar the https://surveyjs.io/Examples/Builder/?id=ckeditorpropertyeditor example

**Comment by rabberbock** [comment]
Yep you can do that! 

So then there is no way yet to use a react component? Is that right?

Thanks!

**Comment by tsv2013** [comment]
Absolutely right. I think it's not a good idea to inject a react wrapper over the vanilla control inside the knockout component :-)
