### ISSUE TITLE
Design Surface: Required validation for Survey Title and Description

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#3938]
[Example](https://codesandbox.io/s/surveyjs-angular-forked-fuoh9j?file=/package.json).

If a survey's Title and Description settings are mandatory/required, the validation message appears as follows:
![image](https://user-images.githubusercontent.com/22372972/222665198-6c8618a4-2dbb-4075-b777-297693f613e4.png)
![image](https://user-images.githubusercontent.com/22372972/225241144-fb41b2a1-c30a-49b2-8c0b-7efae39b1208.png)

@mikeamelin please check this.

design for "Publication case"
Prototype — https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=16682-359474&t=wKJo4a1KhVFc5RjN-4

**Comment by mikeamelin** [comment]
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=16965-385022&t=c9a3dLfDM12f8Bvh-4
