### ISSUE TITLE
SurveyJS Library: Visibleif on a panel still renders empty panel

### ISSUE THREAD

**Issue by rabberbock** [surveyjs/survey-creator#395]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
If you have a survey with two pages, and the second page has a panel with a visible if that depends on the value from a question on the first page, the panel will still be rendered when taking the survey even if the user has not selected a value to make the visible if true. (The question will be hidden though)

### What is the expected behavior?
I would expect that the second page should be disabled until the visible if is true.

### How would you reproduce the current behavior (if this is a bug)?
```
{
 locale: "es",
 title: {
  es: "jjns"
 },
 pages: [
  {
   name: "page2",
   elements: [
    {
     type: "panel",
     name: "panel3",
     elements: [
      {
       type: "dropdown",
       name: "question2",
       choices: [
        "item1",
        "item2",
        "item3"
       ]
      }
     ]
    },
    {
     type: "panel",
     name: "panel1",
     elements: [
      {
       type: "checkbox",
       name: "question1",
       choices: [
        "item1",
        "item2",
        "item3"
       ]
      }
     ],
     visibleIf: "{question2} = \"item1\""
    }
   ],
   title: {
    es: "hello\n"
   }
  },
  {
   name: "page1",
   elements: [
    {
     type: "panel",
     name: "panel2",
     elements: [
      {
       type: "text",
       name: "question3"
      }
     ],
     visibleIf: "{question2} = \"item1\""
    }
   ]
  }
 ],
 showTitle: false,
 showPageTitles: false
}
```

Thanks,

Raffi

**Comment by andrewtelnov** [comment]
@rabberbock Yes, the button should be "Complete" by default on the first page, for all values except "item1". We will work on the fix.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@rabberbock The bug has been fixed with [this commit](https://github.com/surveyjs/surveyjs/commit/4bcebd85ce06e0e8e4e738d9677a13e3b4ce72cc). Unit test has been added.
The fix will be available in the next minor release on the next week.
As a current workaround, please set the visibleIf to the "question3". 

Thank you,
Andrew
