### ISSUE TITLE
Creator in read-only mode - Allow users to view the Correct question Answer 

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3957]
T12631 - Need ability to view correct answer when Survey Creator is in read-only mode
https://surveyjs.answerdesk.io/internal/ticket/details/T12631

[Example](https://plnkr.co/edit/Xw6VxyxtzWpW186O)
Issue: in read-only mode, it is impossible to view a question's correct answer.

Suggestion: allow users to view correct answers in read-only mode of a survey creator. For instance, activate a link which brings up a correct answer popup, but without an option to edit the answer.
![image](https://user-images.githubusercontent.com/22372972/230570767-8cc0c03b-3103-4822-99f5-d238db007554.png)
![image](https://user-images.githubusercontent.com/22372972/230570927-1eb9669f-4486-4d7e-bae7-3f402943483a.png)

**Comment by andrewtelnov** [comment]
@andrewtelnov We need the third state for link property editor: "empty", "has value" and "read-only"
If it is read-only we need to change "Set default value" to "Default value" and show the value. If there is no enough space for it, then the full value will be shown in tooltip.

Thank you,
Andrew

**Comment by mikeamelin** [comment]
I think this way is good enough.
Please pay attention on actions in the popup.

Only one thing... I'm not too happy with read-only mode. Now it looks like disabled. But it is another story.

![Image](https://user-images.githubusercontent.com/17025812/231361804-a75cf27e-0668-46a7-9ac3-6fa755b7644a.png)
