### ISSUE TITLE
Select Question Type button styles

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#3977]
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=17313-397068

![Image](https://user-images.githubusercontent.com/17025812/231216251-fab8b1ee-15ce-4b7c-a279-1c419bdd8264.png)

**Comment by novikov82** [comment]
![Image](https://user-images.githubusercontent.com/29385489/233926452-aaba0128-4276-4030-bbbc-b343d3143721.png)



![Image](https://user-images.githubusercontent.com/29385489/233926487-e7c64b4b-6bf2-4908-a984-efcebd4e1bad.png)
