### ISSUE TITLE
Change the default logic operator for Multi-select choice based questions (e.g., Checkbox,Tagbox)

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3995]
The Equal operator appears by default when creating a logic rule:
![image](https://user-images.githubusercontent.com/22372972/232009773-4599bdee-3658-41f4-a5e1-40c2f776ba82.png)

However, for some questions, it makes sence to use the `contains` operator by default.
Suggestion: when creating a new rule for multi-select choice-based questions, such as Checkbox, and Tagbox, change the default logic operator to `contains`.
![image](https://user-images.githubusercontent.com/22372972/232011151-de87d129-829e-465f-bbd0-843883f99fb0.png)

**Comment by andrewtelnov** [comment]
@JaneSjs I have decided to change it to "allof". It works similar to equal, but it doesn't requre to set the same value as "equal" does.

Thank you,
Andrew
