### ISSUE TITLE
Does validator works for Chinese characters? 

### ISSUE THREAD

**Issue by xuyanMax** [surveyjs/survey-creator#401]
### Are you requesting a feature, reporting a bug or ask a question?

Yeah, I am asking a question.

### What is the current behavior?

For single input question, it did not work for regex for Chinese characters, like ^ [\u4E00-\u9FA5]$.
But after Test Survey, it changed to something like this ^[一-龥]$.

### What is the expected behavior?

Identify the correct regular expression for Chinese Characters.

### How would you reproduce the current behavior (if this is a bug)?

Add a question in type of single input, and modify validators.
Add a regular expression, [\u4E00-\u9FA5], go to Test Survey and go back to JSON Editor.
You will see the regex changes to 
 ^[一-龥]$
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
population.chgc.sh.cn/survey
All in Chineses however.
Test code
Don't know what code
```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@xuyanMax When I tried to follow your steps, the "regex" property becomes: "[\\u4E00-\\u9FA5]". Is it incorrect as well?

Thank you,
Andrew

**Comment by xuyanMax** [comment]
Thanks for you quick reply. I did not realize the notifications on Github, soo sorry. 

When regex becomes  "[\u4E00-\u9FA5]", which is correct now. 

However, when you go the Test Survey, and type Chinese Characters for example "中国", the regular expression mechanism just shows what "text" property is and does not believe what I type is Chinese.

Thanks, 

Xu Yan

**Comment by andrewtelnov** [comment]
@xuyanMax Could you please provide us with JSON that you believe works incorrectly and what exactly should we enter into question to see the problem.
I am sorry, but it is really difficult to reproduce the issue here, since none of us really understand what should we do to reproduce and fix the issue.

Thank you,
Andrew
