### ISSUE TITLE
The Leave the logic tab confirmation dialog appears with incorrect styling

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4017]
The issue is reproduced in a React CodeSandbox demo: [Example](https://codesandbox.io/s/amazing-lake-51fmty)

Current result:
![image](https://user-images.githubusercontent.com/22372972/232872663-7436dfac-d39d-40ec-8caa-a115e77c8be3.png)

Expected result:
![image](https://user-images.githubusercontent.com/22372972/232872905-8fad8f61-57e6-4895-9d20-9d21e7f69e53.png)

**Comment by OlgaLarina** [comment]
https://github.com/surveyjs/survey-library/pull/6059
