### ISSUE TITLE
creator.onItemValueAdded doesn't modify property grid editor correctly

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#4022]
The following code and [example](https://plnkr.co/edit/OHIyUuNSrjQL93Em?preview) doesn't work correctly.
cell editor for text column has the old empty value.
```js
    creator.onItemValueAdded.add((sender, options) => {
      const item = options.newItem;
      if(!!item && !item.locText.text) {
        item.text = item.value.toString();
      }
    });
```

**Comment by JaneSjs** [comment]
We require additional clarification regarding the overall usage scenario behind this issue. We are waiting for user clarification at https://surveyjs.answerdesk.io/internal/ticket/details/T12725.
