### ISSUE TITLE
Add a remove logo option to the design surface

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4068]
Original issue: T12847 - Survejs V2 migration - Logo in survey title - Remove
https://surveyjs.answerdesk.io/internal/ticket/details/T12847

Survey Creator V1 has a delete logo option in a design surface:
![image](https://user-images.githubusercontent.com/22372972/235701587-4896fc25-f133-4398-852a-ea3debcaeb59.png)

However, Survey Creator V2 doesn't:
![image](https://user-images.githubusercontent.com/22372972/235701769-e0cbff58-1223-4ee3-a87f-ba1a43e64341.png)

It is possible to only remove a logo in a Property Grid.

Suggestion: add an option to remove a logo to the survey creator design surface.

**Comment by mikeamelin** [comment]
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?type=design&node-id=18175-396328
