### ISSUE TITLE
Question: Adding title property for html question type

### ISSUE THREAD

**Issue by leksinteractive** [surveyjs/survey-creator#407]
Hi @andrewtelnov,

I wanted to explain this question more, because it's a bit specific to my requirements.

In our product we allow the user to create a question library which they can then use in surveyjs. The way we integrated this question library is by adding another toolbar button in surveyjs, and when you click it it brings up a modal with all the questions in the library you previously created and then you can simply add it to the survey builder as you would any other question from the toolbox. 

So basically the reason we rely on the 'title' property is to list all the questions that were created in our question library. On top of that we're using surveyjs to add the questions to our library in the first place (we're just limiting the editor to allow for addition of one question at a time when they're doing this.) As mentioned before we are able to add the title property in the question edit modal but doesn't get displayed in the panel as below.

![screen shot 2018-09-08 at 4 08 20 pm](https://user-images.githubusercontent.com/3906239/45251975-c14cf780-b381-11e8-873e-ac99d06a41ef.png)

This is what I tried, but this just adds it in the modal. 
(I was hoping the second line would make it show up but no luck)

```
SurveyKo.JsonObject.metaData.addProperty('html', { name: 'title', default: 'Title test' });
SurveyKo.JsonObject.metaData.findProperty('html', 'title').visible = true;
```

I know it's quite a specific requirement so I appreciate you investigating.

Hope that makes sense.

Thank you!

**Comment by leksinteractive** [comment]
I just want to mention, I think you are right not to have the title property for the html question type in most cases. Because typically you wouldn't want to display it, 99% of the time maybe.  So I'm not saying it should be there all the time like the other questions. Instead it seems the ideal solution would be if we had the option to decide to show it, as in our case. Cheers 👍

**Comment by tsv2013** [comment]
I've checked our code. The html question is derived from the `QuestionBase`. In order to has title infrastructure (title, locTitle, hasTitle, titleLocation, hasTitleOnTop, ... and other properties used in title rendering) we need to change inheritance. The html question should be inherited from the `Question` object. In this case html will got the `value` property, that dramatically changes current html question behaviour. Or we need to move the title infractructure in the `QuestionBase` object. @andrewtelnov what do you think?

**Comment by andrewtelnov** [comment]
@leksinteractive @tsv2013 Lets discuss it on the next week (I am in the business trip this week). I personally want to remove "questionbase" class completely and leave "question" only. We have properties that allows us to hide title now. We may have another default value for titleLocation property for html question.
"questionbase" class, a question without value and title, makes the code worse and do not provide any value, IMHO.
I would do this refactoring. We should make sure that the code with using "questionbase" class continiue to work, so we do not break anything in our users code. I beleive we will be able to do it.

Thank you,
Andrew

**Comment by leksinteractive** [comment]
Thanks for the detailed responses 👍

**Comment by andrewtelnov** [comment]
@leksinteractive questionbase class will be removed in the next update on the next week. Here is [the issue](https://github.com/surveyjs/surveyjs/issues/1357)

Thank you,
Andrew
