### ISSUE TITLE
Sometimes text inputs with RegEx validation get stuck in error state after the answer was corrected

### ISSUE THREAD

**Issue by d3n13** [surveyjs/survey-creator#4081]
### Are you requesting a feature, reporting a bug or ask a question?

Bug report

### What is the current behavior?

Text inputs with RegEx validation sometimes get stuck in error state when user first types in invalid format, and then corrects their answer.

### What is the expected behavior?

When user corrects their answer to match the RegEx after previously typing in an invalid format, the question should always exit an error state.

### How would you reproduce the current behavior (if this is a bug)?

1. Open the Preview tab
2. Type in an invalid answer, like `G g`
3. Attempt to Complete the survey. The question is in an error state
4. Correct your answer: `G G`. The answer matches the regex
5. If reproduced, the question is still in an error state, and user is unable to Complete the survey
6. Repeat until reproduced. 

https://user-images.githubusercontent.com/46310638/236446509-d556b144-ddbc-4b5f-a8a3-a63be7e5cf00.mov

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/s/reproduce-survey-creator-regexp-answer-validator-bdss60?file=/package.json:226-258

Test code

```
import { SurveyCreatorComponent, SurveyCreator } from "survey-creator-react";
import "survey-core/defaultV2.min.css";
import "survey-creator-core/survey-creator-core.min.css";

const creator = new SurveyCreator();
creator.JSON = {
  logoPosition: "right",
  pages: [
    {
      name: "page1",
      elements: [
        {
          type: "text",
          name: "question1",
          title: "Name and Surname",
          description:
            "Type in your Name and Surname (2 capitalized words in English)",
          validators: [
            {
              type: "regex",
              text:
                "Invalid format. Please type in your Name and Surname (2 capitalized words in English)",
              regex: "^[A-Z][a-z]*\\s[A-Z][a-z]*$"
            }
          ]
        }
      ]
    }
  ]
};

export default function App() {
  return <SurveyCreatorComponent creator={creator} />;
}
```

### Specify your

* browser: Google Chrome Version 113.0.5672.63 (Official Build) (arm64)
* editor version: `survey-creator-react v1.9.79`

**Comment by JaneSjs** [comment]
Hello @d3n13,
Thank you for comprehensive explanation and a sample code. Please upgrade your SurveyJS Creator library to the latest version (v1.9.98) to resolve the issue. The updated demo is available at https://codesandbox.io/s/reproduce-survey-creator-regexp-answer-validator-forked-k7jkf2?file=/package.json:23-29.

Let me know if you have any questions.

Thanks

P.S. Please note that Survey Creator is available under a [commercial developer license](https://surveyjs.io/pricing).
