### ISSUE TITLE
Building SurveyJS Editor from sources

### ISSUE THREAD

**Issue by andrewhartwig** [surveyjs/survey-creator#409]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug.

### What is the current behavior?

Building for production (or dev) is leaving "knockout" js module as undefined.

![image](https://user-images.githubusercontent.com/42554343/45447922-07b29700-b69f-11e8-9816-976dec5eab34.png)

```typescript
import * as ko from "knockout";
import * as Survey from "survey-knockout";
import { SurveyHelper } from "./surveyHelper";

console.log('Test!');
console.log(ko);
console.log(Survey);
if (!!ko.options) {
  ko.options.useOnlyNativeEvents = true;
}
```

The console logs result in 

![image](https://user-images.githubusercontent.com/42554343/45447944-1c8f2a80-b69f-11e8-96ea-08577d875c11.png)

### What is the expected behavior?

Imports should work as expected.

### How would you reproduce the current behavior (if this is a bug)?

All I did was clone the repository, npm install, run the build dev/prod commands.

npm: v5.6.0
node: v8.11.3

**Comment by tsv2013** [comment]
If you check the https://github.com/surveyjs/editor/blob/master/webpack.config.js#L186-L199 file,
you can see that KnockoutJS and survey-knockout libraries are marked as external:
```JS
    externals: {
      knockout: {
        root: "ko",
        commonjs2: "knockout",
        commonjs: "knockout",
        amd: "knockout"
      },
      "survey-knockout": {
        root: "Survey",
        commonjs2: "survey-knockout",
        commonjs: "survey-knockout",
        amd: "survey-knockout"
      }
    },
```

This mean that these libraries ane not included in the bundle and should be loaded separately

**Comment by andrewhartwig** [comment]
Oh okay, thanks! I've used CRA for so long I forget all about webpack :P
