### ISSUE TITLE
Knockout: Question name's renaming issue

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#4091]
https://user-images.githubusercontent.com/17025812/236821730-d469ae3a-0beb-4d2d-8ffd-7129caf302f3.mov

**Comment by andrewtelnov** [comment]
The issue is happen in Knockout version only.

**Comment by tsv2013** [comment]
Moved to backlog until users will complain this case.

**Comment by tsv2013** [comment]
Can't reproduce right now.
