### ISSUE TITLE
Editing "Select All", "None", "Other" in the inline editor should enable the option

### ISSUE THREAD

**Issue by benmoses-equineregister** [surveyjs/survey-creator#4093]
### Are you requesting a feature, reporting a bug or ask a question?
Requesting a feature or perhaps a bug? 

### What is the current behavior?
When editing the label for Select all, None, Other it allows you to edit, and doesn't enable the option. 
When attempting to edit an option that is not enabled, e.g. "Option 4" the inline text editor is disabled, so you have to enable it then edit. 

### What is the expected behavior?
I would expect them all to be consistent, i.e. all label editing should be disabled until the user enables the option. 

I would ideally like it so if I edit it, on submit of the label edit it also enables the option.

### How would you reproduce the current behavior (if this is a bug)?
1. Go to https://plnkr.co/edit/BYUPj0ODanDKa2SD
2. Add Checkbox question
3. Attempt to change the label of "Select All", "Item4", "None" and "Other". Item4 is disabled, the others are "editable" but after editing they are not "enabled".

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/BYUPj0ODanDKa2SD

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* editor version: (Latest) 1.9.35 but also occurs on latest version on the demo page https://surveyjs.io/survey-creator/examples/free-nps-survey-template/reactjs

**Comment by andrewtelnov** [comment]
@benmoses-equineregister Please use the latest version. It works as expected. Your version is very old. The current version is v1.9.89.

Thank you,
Andrew

**Comment by benmoses-equineregister** [comment]
HI @andrewtelnov, 

I was sure I tested it on your demo page 2 weeks ago, but you're right it's been fixed for a while! 

Sorry about the time wasted 👍

**Comment by andrewtelnov** [comment]
@benmoses-equineregister No problem at all.

Thank you,
Andrew
