### ISSUE TITLE
Multiple-Choice Matrix Column Editor - Columns disappear if you drag them outside the editor

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4095]
In Property Grid, if you drag a Multiple-Choice Matrix column outside the editor, it disappears. Please refer to the following video:

https://github.com/surveyjs/survey-creator/assets/22372972/657139f9-a014-41d5-a6ee-88679748a575

**Comment by tsv2013** [comment]
Fixed via https://github.com/surveyjs/survey-library/pull/6268
