### ISSUE TITLE
No indication that a question is conditionally hidden

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4101]
Issue: 
> Right now, There is no indication that display logic has been applied on a question unless you actually click on the logic tab for the question. Is there any way to show that a particular question has any logic applied?

T13065 - Indication if logic has applied on any question
https://surveyjs.answerdesk.io/internal/ticket/details/T13065
***
A survey element (page/panel/question) has the following settings which manage element visibility: 

**The `Visible` property (Yes/No)**
The Visible property is located in the General tab and can be checked or unchecked indicating that a question is visible or not.
![image](https://github.com/surveyjs/survey-creator/assets/22372972/05d83439-98d9-4496-86b7-4b0030ad5c6c)

**The VisibleIf setting (Expression)**
Also, question visibility can be set through a logic expression. Activate the Logic tab and locate the Visible If property:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/e66de837-8594-4a8e-8d24-66efd6479565)

At this point, even if the Visible option is set to True, a question may be actually hidden because the expression evaluates to False:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/87cc8dec-afa5-4a07-8b40-42ebfb65250d)

However, if we just look at the question's General tab, we cannot clearly understand what's happening because the Visible property is set to true. An experienced user may figure out that an expression is actually applied. But - it is better to help users understand why a question is invisible.
***
Suggestion: visually indicate that a question has expressions set for the **Visible**, **Read Only** and **Required** properties. For instance, display a formula sign besides the property checkbox:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/1469158a-e121-4a9c-9129-d9cee487db87)

**Comment by mikeamelin** [comment]
https://github.com/surveyjs/private-tasks/issues/220
