### ISSUE TITLE
Display a loading indicator while images are being uploaded

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4108]
User requests:
* [T12726 - Display a loading indicator while a survey logo is uploaded](https://surveyjs.answerdesk.io/internal/ticket/details/T12726)
* [T13055 - How to add loader while image upload is in progress ?](https://surveyjs.answerdesk.io/internal/ticket/details/T13055)

**Comment by andrewtelnov** [comment]
@novikov82 Have we already implemented it?

Thank you,
Andrew

**Comment by novikov82** [comment]
I checked for Logo and image, and image picker. It's ok. Closing.
![image](https://github.com/surveyjs/survey-creator/assets/29385489/873b5db6-e220-4684-a76f-942be7bf9c10)
![image](https://github.com/surveyjs/survey-creator/assets/29385489/56c4c318-3b0c-4db3-a20d-7e24e84bb486)
