### ISSUE TITLE
How to create custom models and actions that can be used to define behaviors after survey completion?

### ISSUE THREAD

**Issue by catchpablohealth** [surveyjs/survey-creator#4110]
### Are you requesting a feature, reporting a bug or ask a question?
I am asking a question

----------------------------------------
We have 3 entities (or models) in our product, i.e: "questionnaire", "service", and "menu".
Once users complete surveys, we want to be able to open to a questionnaire page, or a service page, or a menu page, or a custom external URL.
And we want to be able to configure this in the logic tab.

I attached the design below:

![image](https://github.com/surveyjs/survey-creator/assets/130686682/af962d4d-6605-4702-bbb0-9b9330df8812)

1. Custom model:
For e.g, if "Go to a service" is selected, we want to say "Select service" and show a dropdown of available services.
Likewise, if "Go to a Menu" is selected, we want to say "Select menu" and show a dropdown of available menus.
This means we want to add new models, i.e, "Service" and "Menu" to the logic tab.
2. Custom action:
If "Go to a new questionnaire" is selected, nothing else should be displayed.
i.e, this is a custom action that tells us that we should open the new questionnaire.
For both 1 and 2, we want to be able to capture the custom action or model value once the survey is complete, i.e, onComplete callback.

Please let me know how we can achieve this.
Thanks!

**Comment by JaneSjs** [comment]
Hi @catchpablohealth,
This question seems to be a duplication of the following Help Desk thread: [T13062 - How to create custom models and actions that can be used to define behaviors after survey completion](https://surveyjs.answerdesk.io/internal/ticket/details/T13062).

Please feel free to reactivate this thread if you have additional questions.

Thanks
