### ISSUE TITLE
Readonly property can't add translation

### ISSUE THREAD

**Issue by AkaHanshan** [surveyjs/survey-creator#4112]
### Are you requesting a feature, reporting a bug or ask a question?
reporting a bug

### What is the current behavior?
if a question/panel/page title setted readOnly, it can't add translation 

### What is the expected behavior?
it can be add translation for readOnly property

### How would you reproduce the current behavior (if this is a bug)?
use Serializer.findProperty('panel', 'title').readOnly = true to set the title of panel readOnly, and then I can't add translation and no title in translation tab

* browser: Chrome
* editor version: survey-creator-react: 1.9.84

**Comment by andrewtelnov** [comment]
@AkaHanshan We use surveys in all our forms in Creator V2.
Why do you want to make panel title read-only?

Thank you,
Andrew

**Comment by AkaHanshan** [comment]
Hi @andrewtelnov ,we set a preset survey template for our user, but we don't want it too flexible to config.
So we set so type of question title or choices read-only, but when we rollout to other region, they may need add translation by their own

**Comment by andrewtelnov** [comment]
@AkaHanshan Please use [creator.onGetPropertyReadOnly](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onGetPropertyReadOnly) event.
It will be applied for survey on the designer surface only.

Thank you,
Andrew

**Comment by AkaHanshan** [comment]
Hi @andrewtelnov  I try the [creator.onGetPropertyReadOnly](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onGetPropertyReadOnly) but it seems can't meet my need
I want the default translation can't be edit (readonly) but for some property or situation,the extra local translation can be edit

**Comment by andrewtelnov** [comment]
@AkaHanshan Could you please create a plunker or CodeSandbox project example that shows the issue?

Thank you,
Andrew

**Comment by AkaHanshan** [comment]
@andrewtelnov  I create a basic example https://codesandbox.io/s/wandering-river-hmvr33?file=/src/survey.ts
and what I want is the next:
<img width="972" alt="image" src="https://github.com/surveyjs/survey-creator/assets/48984202/363b8787-ae0b-4427-8392-ac0d22065e21">

**Comment by andrewtelnov** [comment]
@AkaHanshan We use survey in all our forms in Creator V2.  You can use the following code:
```js
  creator.onSurveyInstanceCreated.add((sender, options) => {
    if (options.reason === "translation_strings") {
      options.survey.onMatrixCellCreated.add((sender, options) => {
        if (options.columnName.indexOf("default") > -1) {
          options.cellQuestion.readOnly = true;
        }
      });
    }
```

PS: Do you have a commercial license? If you do you can use our support forum.
If you don't then you don't have rights to remove a text about non-commercial use.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
The [forked working example](https://codesandbox.io/s/mystifying-lichterman-ee5znv?file=/src/App.tsx:712-1025).

Thank you,
Andrew

**Comment by AkaHanshan** [comment]
@andrewtelnov  yes, we have bought the Pro license, your example is useful, thank you!

**Comment by AkaHanshan** [comment]
Hi @andrewtelnov ,I found that this example cannot solve such a scenario: After setting title as readOnly, this title can be displayed in the translation tab, and the default translation cannot be edited, but it is possible to add and edit custom translations.
Still the same example:https://codesandbox.io/s/wandering-river-hmvr33?file=/src/App.tsx

<img width="559" alt="image" src="https://github.com/surveyjs/survey-creator/assets/48984202/4df3a628-de33-43db-adb6-49d227fa5aa0">

Thank you

**Comment by andrewtelnov** [comment]
@AkaHanshan To fix the first issue, please update to the latest version and remove this line:
`Serializer.findProperty("page", "title").readOnly = true;`.
Regarding the second quetion, it will likely work in the latest version.
If it is not, please create an issue in [our support forum](https://surveyjs.io/support).

Thank you,
Andrew
