### ISSUE TITLE
Survey Creator Page design element - Implement the Action Bar and Add an option to add a custom action after the Add Question button

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4128]
Original issue: T13004 - Add Buttons in the creator in each page
https://surveyjs.answerdesk.io/internal/ticket/details/T13004

Related ticket: https://github.com/surveyjs/survey-creator/issues/4127.

Usage Scenario: Register a custom button and display it after the Add Question button:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/716998f3-46d4-402b-a1cc-20f2b095ab14)

Current w/a ([React Demo](https://codesandbox.io/s/cranky-boyd-kj07j9?file=/src/SurveyCreatorComponent.jsx))
Override the `CreatorSurveyPageComponent` class and render a button at the footer area:
```
class CreatorSurveyPageComponentEx extends CreatorSurveyPageComponent {
  renderFooter() {
    const prev = super.renderFooter();
    return (
      <div>
        {prev}
        <button>My Custom Button</button>
      </div>
    );
  }
}
```
Suggestion: implement an action bar container at the bottom of a page and add an option (e.g. an event) to add custom actions.

**Comment by dk981234** [comment]
https://codesandbox.io/s/surveyjs-angular-forked-vhu7o1?file=/src/app/components/creator.component.ts
