### ISSUE TITLE
Provide some build docs

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#4131]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
There is no documentation on building the creator.

### What is the expected behavior?
It should either jus work, or there some be some docs describing what the requirements are for building the survey-creator packages.

**Comment by RomanTsukanov** [comment]
@SamMousa 
You can now find build instructions in README files distributed with our packages:

- [Build the Survey Creator Model from Sources](https://github.com/surveyjs/survey-creator/tree/master/packages/survey-creator-core#build-the-survey-creator-model-from-sources)
- [Build Survey Creator / Form Builder for Angular from Sources](https://github.com/surveyjs/survey-creator/tree/master/packages/survey-creator-angular#build-survey-creator--form-builder-for-angular-from-sources)
- [Build Survey Creator / Form Builder for React from Sources](https://github.com/surveyjs/survey-creator/tree/master/packages/survey-creator-react#build-survey-creator--form-builder-for-react-from-sources)
- [Build Survey Creator / Form Builder for Knockout from Sources](https://github.com/surveyjs/survey-creator/tree/master/packages/survey-creator-knockout#build-survey-creator--form-builder-for-knockout-from-sources)

Roman,
SurveyJS Team
