### ISSUE TITLE
Property Grid - The Required property validation error message does not disappear when a single character remains

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4136]
[Example](https://plnkr.co/edit/bJE3xcyPShmelw2S)

Issues with the Required validation:
- [ ] The validation message does not disappear when a single char remains:

https://github.com/surveyjs/survey-creator/assets/22372972/510fcd16-2c21-4c87-a87f-77e6acde1fb7

- [ ] I cannot clear the field - a single character is always presented.
![image](https://github.com/surveyjs/survey-creator/assets/22372972/31745448-2266-478f-a9ba-5970a0ec4438)

**Comment by andrewtelnov** [comment]
Requried text editor has text input mode equals to "onBlur" instead of "onTyping" that we have before.

Thank you,
Andrew
