### ISSUE TITLE
Limitations on Multilingual Translations for Properties in Data Modeling

### ISSUE THREAD

**Issue by AkaHanshan** [surveyjs/survey-creator#4137]
https://codesandbox.io/s/crazy-almeida-osolxm

In choices, identical translations for multilingual objects will be combined into a string. However, it is not possible to add multilingual translations for properties like readOnly or visible = false.

like
```
        choices: [
              {
                value: "+852",
                text: {
                  default: "+852",
                  "zh-tw": "+852"
                }
              },
              {
                value: "+86",
                text: {
                  default: "+86",
                  "zh-tw": "+86"
                }
              }
            ]
```
in json editor, It becomes 
```
     "choices": [
      "+852",
      "+86"
     ]
```
how can I avoid this?

**Comment by JaneSjs** [comment]
Hi @AkaHanshan,
It seems that we handled a similar issue earlier at https://github.com/surveyjs/survey-creator/issues/1240.
Accordong to this thread, elements which initially have translation should be available in a Translation tab.

I'll discuss this issue with our developers.

**Comment by AkaHanshan** [comment]
@JaneSjs  Thanks,
[Survey.settings.storeDuplicatedTranslations](https://surveyjs.io/form-library/documentation/api-reference/settings#storeDuplicatedTranslations) seems what I want.
I chose a neat way to realize that the readonly field cannot be edited in the default of the translation tab, and the local language can be edited
I have a demo about the solution :https://codesandbox.io/s/beautiful-andras-p7hjlq?file=/src/SurveyCreatorComponent.jsx

**Comment by JaneSjs** [comment]
Hello @AkaHanshan,
Thank you for the update. I'm happy to hear that you've found the solution. Please feel free to contact us if you have any questions or require further assistance.
