### ISSUE TITLE
Undo Issue

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#4157]
1 — Select all text in the Title field.
2 — Delete it
3 — Undo

![Image](https://github.com/surveyjs/survey-creator/assets/17025812/fb96dae4-3b8f-4b75-9289-4ef36d27eb76)

**Comment by andrewtelnov** [comment]
@mikeamelin I can't reproduce it.

Thank you,
Andrew

**Comment by mikeamelin** [comment]
I guess I forgot to mention Safari...

https://github.com/surveyjs/survey-creator/assets/17025812/f962d4b6-ec5c-424b-9f88-50111a51802c
