### ISSUE TITLE
Remove ace-builds from peer dependencies

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#4232]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
The packages `survey-creator-core` and `survey-creator-knockout` have `ace-builds` listed in their `peerDependencies`.
However it is not a peer dependency, it is an optional dependency.

In our code base where we import ace via `ace-code` which provides ESM compatible definitions; we now have `ace-builds` as well as `ace-code` in our `node_modules` because of this misconfiguration.

### What is the expected behavior?
It should be listed as an optional dependency.

It could possibly be both: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#peerdependenciesmeta

**Comment by tsv2013** [comment]
In npm versions 3 through 6, peerDependencies were not automatically installed. As of npm v7, peerDependencies are installed by default.

optionalDependencies (https://docs.npmjs.com/cli/v9/configuring-npm/package-json#optionaldependencies) are recommended to be used if a dependency can be used, but you would like npm to proceed if it cannot be found or fails to install. It's not looks like our case.

I think the best solution will be to add a peerDependenciesMeta for the `ace-builds` package.
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#peerdependenciesmeta

**Comment by tsv2013** [comment]
@SamMousa Ping

**Comment by SamMousa** [comment]
Yeah I agree, the smiley was signalling my agreement!

**Comment by tsv2013** [comment]
Super! We'll do it :-)
