### ISSUE TITLE
Conditional logic: Questions with copied choices are empty in "Visible if", "Enabled if", "Required if" dialog windows

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#4237]
https://plnkr.co/edit/0k838MO5lfWuy3Ud

![image](https://github.com/surveyjs/survey-creator/assets/18551316/0c8defb9-9a29-4d98-bd76-da987d67ae33)

Steps to reproduce:

1. Select question1.
2. Edit its Visible if property.
3. Select question2 in a condition.

Expected result: question2 displays items.
Current result: question2 is empty.

**Comment by andrewtelnov** [comment]
@RomanTsukanov The issue is fixed. Here is [the duplicated issue](https://github.com/surveyjs/survey-creator/issues/4243).

Thank you,
Andrew
