### ISSUE TITLE
Bug in Next JS regarding ReactElementFactory

### ISSUE THREAD

**Issue by mujtabaaliawan** [surveyjs/survey-creator#4241]
#Bug 
#user issue

The new survey tab can not be accessed in NEXTJS. The issue is in this line.
	ReactElementFactory.Instance.registerElement('costumCreatorTab', (props) => {
		return QuestionLibraryComponent(creator, props)
	})
ReactElementFactory is perhaps not working in NEXT JS like it is supposed to be. I have tried all available online appraoches, including the react code in your online sample for tab customization, but it does not work beyond this point. Kindly guide.

The expected behavior should be i should be able to display something, or do something on the new tab.

My code:

```
import QuestionLibrary from 'components/app/QuestionLibrary'
import { ReactElementFactory } from 'survey-react-ui'
import { SurveyCreator, SurveyCreatorComponent } from 'survey-creator-react'
import { ISurveyCreatorOptions } from 'components/types'
import 'survey-core/defaultV2.min.css'
import 'survey-creator-core/survey-creator-core.min.css'
import 'survey-creator-core/survey-creator-core.i18n'
import 'survey-core/survey.i18n'

const SurveyCreatorWidget = ({
	surveySchema,
	creatorOptions,
}: {
	surveySchema: {}
	creatorOptions: ISurveyCreatorOptions
}) => {

	const creator = new SurveyCreator(creatorOptions)



	//Add plug-in.
	ReactElementFactory.Instance.registerElement('costumCreatorTab', () => {
		return QuestionLibrary(creator)
	})

	const costumPlugin = {
		activate: () => {},
		deactivate: () => {
			return true
		},
		model: creator,
	}

	if (sidebar?.selected?.isEditable)
		creator.addPluginTab(
			'Library',
			costumPlugin,
			'Library',
			'costumCreatorTab',
			1
		)

	creator.JSON = surveySchema
	return <SurveyCreatorComponent creator={creator} />
}

export default SurveyCreatorWidget

```
* platform: NEXT JS
* browser: firefox
* editor version: "survey-creator-react": "^1.9.87",

**Comment by mujtabaaliawan** [comment]
#Bug  #User Issue

**Comment by JaneSjs** [comment]
Hello @mujtabaaliawan,
I would appreciate it if you share a runnable sample so that I can test it on my end. Please share the problematic sample for research.

This would save time for us both.

Thanks

**Comment by mujtabaaliawan** [comment]
Thanks Jane. The issue was due to old versions of survey js and survey
creator and was resolved on moving them to latest versions. Thanks.

**Comment by JaneSjs** [comment]
Hello @mujtabaaliawan,
Thank you for the confirmation. I'm happy to hear that you resolved the issue.

Thank you
