### ISSUE TITLE
Can't prevent tab switching

### ISSUE THREAD

**Issue by brianh20** [surveyjs/survey-creator#4262]
### Are you requesting a feature, reporting a bug or ask a question?

Yes

### What is the current behavior?

When you click on a tab you navigate to it

### What is the expected behavior?

When you click on a tab you can cancel the action programatically if a condition is not met.

Use case:
I added a new custom tab and if the information in the new tab is not valid I don't want the user to be able to navigate away from the tab

**Comment by andrewtelnov** [comment]
@brianh20 Here is [the working example](https://plnkr.co/edit/Pz3FSRPQgeO7R8Ur). It disable to leave designer tab if there is no any question in the designed survey:
```js
    creator.onActiveTabChanging.add((sender, options) => {
      if(creator.activeTab === "designer" && creator.survey.getAllQuestions().length === 0) {
        alert("Please drop at least one question!");
        options.allow = false;
      }
    });

```

Thank you,
Andrew

**Comment by brianh20** [comment]
Appreciate it!
