### ISSUE TITLE
Ability to disable value field for itemvalue rows

### ISSUE THREAD

**Issue by leksinteractive** [surveyjs/survey-creator#429]
Hi team,

Feature request: would be great if we have the ability to disable the 'value' field for the itemvalue rows. 

For example we autogenerate these values (simply sequential numeric values via onItemValueAdded) so we don't need to allow the user to edit it. If that's a bit too much, how could we simply hide the field but make sure to retain any auto generated values?

Many thanks,
Aleks

**Comment by tsv2013** [comment]
I'm working on it. It should be possible but I faced some issues.

**Comment by tsv2013** [comment]
@leksinteractive  We're talking about the matrixdropdown question rows property, right?

**Comment by tsv2013** [comment]
```JS
SurveyEditor.SurveyQuestionEditorDefinition.definition["matrixdropdown@rows"] = {properties: ["text"] };
```

**Comment by leksinteractive** [comment]
Hi @tsv2013,

Thanks for the matrixdropdown code, however I was actually meaning for the itemvalue rows for questions such as checkbox, radio (selectbase i believe).

**Comment by tsv2013** [comment]
Thanks for the clarification. Here it is:
```JS
SurveyEditor.SurveyQuestionEditorDefinition.definition["checkbox@choices"] = {properties: ["text"] };
```

**Comment by tsv2013** [comment]
I've commited necessary changes. It will work in the next update.

**Comment by leksinteractive** [comment]
Awesome, thank you @tsv2013

**Comment by kumbhagirishiva** [comment]
> ```js
> SurveyEditor.SurveyQuestionEditorDefinition.definition["checkbox@choices"] = {properties: ["text"] };
> ```

I tried this , but it not working to me, please can you share any live example
