### ISSUE TITLE
Improve error positions when editing the json

### ISSUE THREAD

**Issue by mpcaddy** [surveyjs/survey-creator#4294]
### Are you requesting a feature, reporting a bug or ask a question?
Bug / Feature Improvement

### What is the current behavior?
Currently implementing a Monaco Editor version of the JSON editor tab to be consistent with the rest of our application. Which works but the error handling leaves a lot to be desired because the the errors returned seem to be very limited in terms of the reported positioning.

When editing the json most of the errors come out with a pos with both start and end being -1. 

For a small survey this is probably fine and for larger ones you are probably editing the bit that has the error anyway so you will know where it is, but if you paste a large survey in which has an error with only the description of the error it may take you a while to find. So I would like to be able to put the markers around the correct portion of the json.

### What is the expected behavior?
That the position in the error is the actual position in the json that the error occurs. 

For the example below I'd expect pos to be 127 to 221 and for position start to be row 7 column 17 and probably a position end with row 10 column 18.

### How would you reproduce the current behavior (if this is a bug)?
Use an invalid json below in the editor and inspect the errors

#### Provide the test code and the tested page URL (if applicable)

```
{
    "logoPosition": "right",
    "pages": [
        {
            "name": "page1",
            "elements": [
                {
                    "type": "text",
                    "title": "Account"
                }
            ]
        }
    ]
}

```

This will error with 

```
[{
    "pos": {
        "start": -1,
        "end": -1
    },
    "text": "The property 'name' is required in class 'text'.",
    "position": {
        "start": {
            "row": 0,
            "column": 0
        }
    }
}]
```

### Specify your

* browser: chrome
* editor version: 1.9.95

**Comment by andrewtelnov** [comment]
@mpcaddy We are going to work on errors handling in JSON editor. It is hard to find and fix errors right now. We want to improve it radically. I will be back to this issue as soon as we have a progress on our task.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@mpcaddy I have fixed the issue by the PR above. Error is now a class, not a json object, and it has columnAt and rowAt properties.
It fixes the issue with Ace Editor. It shows error correctly now.
We will work on Errors tab in JSON Editor tab.

Thank you,
Andrew

**Comment by mpcaddy** [comment]
Hi, sorry for the late reply only now getting around to looking at this. 
Thanks for the quick implementation.
It is much better, although I'm getting some incorrect positioning for the unknownproperty error if the property name appears somewhere else in the question. I think it should probably have a search for `"{propertyname}"` with the quotes surrounding it as at the moment it will find it anywhere in the element.

`{
  "logoPosition": "right",
  "pages": [
    {
      "name": "inititalPage",
      "elements": [
        {
          "type": "radiogroup",
          "name": "caller",
          "title": "Are you a professional or a member of the public?",
          "choices": [
            "Professional",
            "Public"
          ],
          "professional": ""
        }
      ]
    }
  ]
}`

For example here the error is marked as line 10 in the ace editor when the extra property is line 15.
