### ISSUE TITLE
The options.newValue within the creator.onModified event returns an empty object when a user reorders choices

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4296]
UPDATED:
onModified with type equals to "PROPERTY_CHANGED" will not be fired on changing an order of an element in an array.
Instead Creator will call onModified with type "ELEMENT_REORDERED". Please refer to [this issue for more info](https://github.com/surveyjs/survey-creator/issues/4302).

User Issue: T13773 - Event for choice delete
https://surveyjs.answerdesk.io/internal/ticket/details/T13773
***
Usage scenario: The `creator.onModified` event is used to track user actions.
When a user deletes a choice, the following code allows to log this action:
```
creator.onModified.add((sender, options) => {
    if (
      options.type === "PROPERTY_CHANGED" &&
      options.name === "choices" &&
      Object.keys(options.newValue).length === 0
    ) {
      console.log("choice deleted");
    }
});
```
[View Demo](https://codesandbox.io/s/lingering-haze-kglyg8?file=/src/SurveyCreatorComponent.jsx)

However, the `if` expression is also evaluated to `true` when a user reorders choices. In this case, the `options.newValue` also returns an empty object, even though a user doesn't actually remove a choice but changes the choice's position.

Suggestion: allow track choice reordering using the creator.onModified event and clearly determine that a user reordered choices.

**Comment by JaneSjs** [comment]
FYI: To handle choice reordering, use the `creator.onAfterDrop` function. Its `options` argument contains information about the processed objects.

* `options.fromElement` - a source element the current element was dragged from;
* `options.draggedElement` - the dragged element;
* `options.toElement` - a target element to which the element was dropped.

To handle choice removal, use the [creator.onCollectionItemDeleting](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onCollectionItemDeleting) event.

**Comment by andrewtelnov** [comment]
It is fixed in [this issue](https://github.com/surveyjs/survey-creator/issues/4302).

Thank you,
Andrew
