### ISSUE TITLE
The `showCommentArea` disappears when category is changed

### ISSUE THREAD

**Issue by kmhigashioka** [surveyjs/survey-creator#4306]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
The `showCommentArea` property does not appear when the category is changed.

### What is the expected behavior?
The `showCommentArea` property should appear under the assigned category.

### How would you reproduce the current behavior (if this is a bug)?
Please see Test code below.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://9npf3z.csb.app/

Test code

```
import { Serializer } from "survey-core";

Serializer.addProperties("rating", [
  {
    name: "title",
    category: "questionSetting"
  },
  {
    name: "showCommentArea",
    category: "questionSetting"
  }
]);
```
For reference this is what it looks like:
![image](https://github.com/surveyjs/survey-creator/assets/5535475/e3288c76-fff6-42c0-b7c1-951d92aa0fc0)

### Specify your

* browser: Firefox 111.0.1
* editor version: 1.9.93

**Comment by andrewtelnov** [comment]
@kmhigashioka "showCommentArea" is defined in the "rating" question. You can't define it twice.
Please use the following code:
```js
Survey.Serializer.addProperty("rating", { name: "title",  category: "questionSetting"});
Survey.Serializer.findProperty("rating", "showCommentArea").category = "questionSetting";
```
Here is [the example](https://plnkr.co/edit/vvMtjDlHHi8nbKM0).

Thank you,
Andrew

**Comment by kmhigashioka** [comment]
I see. Thanks for the prompt reply @andrewtelnov ! :bow:
