### ISSUE TITLE
Add Errors section into JSON Editor tab

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#4313]
We need to show the list of errors similar to Error tabs in Code IDEs.
There should be a fix button and ability to navigate to an error in text editor.

**Comment by mikeamelin** [comment]
Error panel design — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=162-230729&mode=design

**Comment by andrewtelnov** [comment]
@dk981234 I have implemented the "survey-creator-core", "survey-creator-react" & "survey-creator-knockout",
I have modified two functional tests in json.ts: "Check show/hide errors list visibility" & "Goto line from error".
We need implementation in "survey-creator-angular" + design.
We should not forget about removing old errors implementation in "survey-creator-core". I left this code for now, to make sure "survey-creator-angular" can be compiled.

Thank you,
Andrew
