### ISSUE TITLE
How to create a panel based custom qustion.

### ISSUE THREAD

**Issue by Emalios** [surveyjs/survey-creator#4319]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
I have a custom question with my 'path' property. But it's a basic question not a panel based one.
I tried to check in the documentation, so I found this page https://codesandbox.io/s/dtl93l?file=/src/SurveyCreatorComponent.jsx:200-277. 
I also tried to make my custom class to extends to ModelPanelBase instead of Question but this did'nt work too.

### What is the expected behavior?
I want to add questions inside my custom component.

#### Provide the test code and the tested page URL (if applicable)

This is my SurveyCreator component inside my React App.

Test code

```ts
import React, {useEffect} from 'react';
import 'survey-core/modern.min.css';
import {localization, SurveyCreator, SurveyCreatorComponent} from "survey-creator-react";
import "survey-core/defaultV2.min.css";
import "survey-creator-core/survey-creator-core.min.css";
import { ElementFactory, Question, Serializer} from "survey-core";
import {ReactQuestionFactory, SurveyQuestionElementBase} from "survey-react-ui";

const CUSTOM_QUESTION_TYPE = "videoquestions";

// A model that extends the Question class and inherits all its properties and methods
export class VideoQuestionsModel extends Question {
    constructor(name: string) {
        super(name);
        // Create a `LocalizableString` object for the `caption` property
        //this.createLocalizableString("caption", this);
    }
    getType() {
        return CUSTOM_QUESTION_TYPE;
    }
    get path() {
        return this.getPropertyValue("path");
    }
    set path(val) {
        this.setPropertyValue("path", val);
    }
}

// A class that renders a Descriptive Text question
export class SurveyVideoQuestions extends SurveyQuestionElementBase {
    get question() {
        return this.questionBase;
    }
    renderElement() {
        return (
            <></>
        );

    }
}

const creatorOptions = {
    showLogicTab: true,
    isAutoSave: true
};

const CustomSurveyCreatorComponent: React.FC = () => {
    const creator = new SurveyCreator(creatorOptions);

    useEffect(() => {
        // Register `DescriptiveTextModel` as a constructor for the "descriptivetext" question type
        ElementFactory.Instance.registerElement(CUSTOM_QUESTION_TYPE, (name) => {
            return new VideoQuestionsModel(name);
        });

        // Configure JSON serialization and deserialization rules for the custom properties
        Serializer.addClass(
            CUSTOM_QUESTION_TYPE,
            [
                {
                    name: "path",
                    category: "general",
                    visibleIndex: 2,
                }
            ],
            function () {
                return new VideoQuestionsModel("");
            },
            "question"
        );

        // Change default values for inherited properties
        Serializer.getProperty(CUSTOM_QUESTION_TYPE, "hideNumber").defaultValue = true;
        Serializer.getProperty(CUSTOM_QUESTION_TYPE, "titleLocation").defaultValue = "hidden";

        // Register `SurveyQuestionDescriptiveText` as a class that renders the Descriptive Text question type
        ReactQuestionFactory.Instance.registerQuestion(
            CUSTOM_QUESTION_TYPE,
            (props) => {
                return React.createElement(SurveyVideoQuestions, props);
            }
        );

        // Specify captions to display on the design surface and in Property Grid
        const locale = localization.getLocale("");
        locale.qt[CUSTOM_QUESTION_TYPE] = "Video questions";
        locale.pe.path = "Path";
    }, [])

    return (
        <SurveyCreatorComponent creator={creator} />
    )
};

export default CustomSurveyCreatorComponent;
```

### Specify your

* browser: Chrome
* browser version: latest
* surveyjs platform : React TS
* surveyjs version: 
```json
    "survey-creator-react": "^1.9.95",
    "survey-react": "^1.9.96",
    "survey-react-ui": "^1.9.95"
```

Thanks you for any suggestions!

**Comment by andrewtelnov** [comment]
@Emalios Please review the following documentation:
[Create specialized question types](https://surveyjs.io/form-library/documentation/customize-question-types/create-specialized-question-types) and [Create composite question types](https://surveyjs.io/form-library/documentation/customize-question-types/create-composite-question-types).

Thank you,
Andrew

**Comment by Emalios** [comment]
> @Emalios Please review the following documentation: [Create specialized question types](https://surveyjs.io/form-library/documentation/customize-question-types/create-specialized-question-types) and [Create composite question types](https://surveyjs.io/form-library/documentation/customize-question-types/create-composite-question-types).
> 
> Thank you, Andrew
Hello Andrew, thank you for your suggstion!

First, the composite question types is the closest thing to what i want. But I can't modify it dynamically in the survey creator like a panel. So I tried to create a specialized question types like the code bellow but in the survey creator the question 'country' did not appear. And even if it had appeared I don't think I can change the 'type' in the questionJSON to 'panel' because I saw in your [documentation](https://surveyjs.io/form-library/documentation/api-reference/panel-model) that a Panel is not a Question. 
```ts
import React, {useEffect} from 'react';
import 'survey-core/modern.min.css';
import {SurveyCreator, SurveyCreatorComponent} from "survey-creator-react";
import "survey-core/defaultV2.min.css";
import "survey-creator-core/survey-creator-core.min.css";
import { ComponentCollection } from 'survey-react';

const creatorOptions = {
    showLogicTab: true,
    isAutoSave: true
};

const CustomSurveyCreatorComponent: React.FC = () => {
    const creator = new SurveyCreator(creatorOptions);

    useEffect(() => {
        ComponentCollection.Instance.add({
            //Unique component name. It becomes a new question type. Please note, it should be written in lowercase.
            name: "country",
            //The text that shows on toolbox
            title: "Country",
            //The actual question that will do the job
            questionJSON: {
                type: "dropdown",
                placeholder: "Select a country...",
                choicesByUrl: {
                    url: "https://surveyjs.io/api/CountriesExample",
                },
            },
        });

        creator.JSON = {
            elements: [
                {
                    type: "country",
                    name: "question1"
                }
            ]
        };
    }, [])

    return (
        <SurveyCreatorComponent creator={creator} />
    )
};

export default CustomSurveyCreatorComponent;
```

**Comment by andrewtelnov** [comment]
@Emalios You can modify it dynamically by adding [new properties](https://surveyjs.io/form-library/documentation/customize-question-types/create-composite-question-types#override-base-question-properties) into it. Based on these properties you can change your content questions and/or add/delete content questions.

Thank you,
Andrew

**Comment by Emalios** [comment]
> 

Do you mean I can add a Panel property into the question to be able to drag n drop questions inside it into the survey creator? And I still have th issue of my component who is not showing in the toolbox. 

Thank you.

**Comment by Emalios** [comment]
Do you mean I can add a panel property to my component so I will be able to drag n drop questions inside in the survey creator? And I stilldon't understand why my custom component is not showing in the toolbox. 

Thank you for your response.

**Comment by Emalios** [comment]
I have solved my problems by adding a property inside the base Panel component.
