### ISSUE TITLE
Theme Builder suggestions

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#4320]
## Renamings

1. Transfer all setting names from Title Case to Sentence case.
2. Theme -> Color scheme
3. Light / Dark - Add the setting name: Color mode.
4. Panels / Lightweight - Rename to Regular / Compact and add the setting name: Size mode
5. transparency -> opacity
6. ~Categories: General / Advanced -> Base Settings / Advanced Settings~ There will be more categories
7. Question Panel -> Panel background and corner radius
8. Question Panel Border / Shadow -> Shadow effects
9. Add More Shadow Effect -> Add Shadow Effect
11. Editor -> Input field
12. Editor Border / Shadow -> Input field shadow effects
13. Editor font -> Input field font
14. Lines Major / Minor -> Minor line colors Darker / Lighter
15. "Semi-bold" doesn't fit into the default width of Property Grid. Turn into a drop-down menu?

## Hide irrelevant settings

For example, there are no panels in compact size mode, therefore panel settings may be hidden. The same thing with survey title settings, which are not needed when there's no survey title. There may be other cases.

## CSS Editor

Add a capability to preview, copy, and paste the customization results, like in JSON Editor.

## Undo buttons for individual editors

Add an Undo button for each editor in Property Grid.

**Comment by AndOne1974** [comment]
I would appreciate it if the JSON would be stored within the JSON survey and thus be permanently linked to the survey. The export option is nice, but shouldn't be tied to the code to use a theme. Normal users / users of the editor cannot change the code or need a place in the creator where they can do this per survey.

**Comment by RomanTsukanov** [comment]
This issue is separated into four different issues and is no longer needed.

**Comment by JaneSjs** [comment]
Hello @AndOne1974,

Thank you for sharing your idea.

When developing the concept of survey themes, we decided not to directly associate themes with surveys. We approached this by considering a many-to-many relationship between themes and surveys. This implies that a single theme could be applied to multiple surveys, and conversely, a single survey could be associated with multiple themes. Consequently, we designed a JSON definition for themes, which is created and stored independently from the JSON definition of surveys.

If you intend to connect a specific theme with a particular survey, you can achieve this within the context of your application. For example, you can establish an internal key-value pair that establishes a link between a survey and its corresponding theme.

Should you have any further questions, please don't hesitate to reach out. We are always here to assist you.
