### ISSUE TITLE
Behaviour of fields which are not visible

### ISSUE THREAD

**Issue by leksinteractive** [surveyjs/survey-creator#433]
Hi team,

Are you able to confirm if fields that are marked as `isRequired=true` and `visible=false` would get submitted with the response answers?

At the moment they don't get submitted? Does it mean that a field that is not visible regardless of the isRequired value will never get submitted?

Thanks,
Aleks

**Comment by tsv2013** [comment]
This behavior is controlled by the [clearInvisibleValues](https://surveyjs.io/Documentation/Library/?id=surveymodel#clearInvisibleValues) property of a survey.
THis question is related to the https://github.com/surveyjs/surveyjs repo

**Comment by leksinteractive** [comment]
Thanks for the quick response @tsv2013,

Are you able to confirm if i'm setting that property correctly?
Here's a plunkr and in this example it's still not coming through?

https://next.plnkr.co/edit/pPGIdLTWdRBxSdLi

**Comment by tsv2013** [comment]
The 'none' is the right setting. But your first question in plunker is hidden initially and has no data.
