### ISSUE TITLE
Allow to hide/show operators in condition editor based on question

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#4346]
A new creator event is added to control operators on a question level:
```js
  /**
   * Use this event to change the visibility of operators in a condition editor by question.
   *- sender the survey creator object that fires the event.
   *- options.questionName - the question name for that condition operator is showing.
   *- options.operator - the condition operator.
   *- options.isEnabled - change it to show/hide the condition operator for this question.
   */
   public onConditionOperatorEnabled: CreatorEvent = new CreatorEvent();

```

**Comment by souareas** [comment]
Good morning,

I updated survey-creator from version 1.9.57 to 1.9.126 but I noticed that functions of type CreatorEvent for example (onActiveTabChanged: CreatorEvent) that I do not have the add() method.

And I have to type any (for example => (creator.onActiveTabChanged as any).add((_, options) => {}))) to make it work.
