### ISSUE TITLE
Inplace Editing - Question actions appear incorrectly when a question's design area  

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4354]
[View Demo](https://plnkr.co/edit/lat38dv790nqLazX)
To reproduce the issue, decrease the width of a question so that actions cannot fit into the action bar:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/0b89184f-e83e-4601-99a8-ea422526e782)

The following issues appear:

- [ ] A question's menu popup diesn't display item captions:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/7db2276b-7df9-4b51-9246-849f1765126b)

- [ ] A question type selector dropdown arrow is duplicated and appears at an incorrect position:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/416f7668-d9c9-44c6-b55e-b7f1ccdbc198)

**Comment by mikeamelin** [comment]
Related issues — https://github.com/surveyjs/private-tasks/issues/250

**Comment by mikeamelin** [comment]
Prototype — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=423-337200&mode=design
