### ISSUE TITLE
Drag-n-Drop Issue (Safari only)

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#4356]
Every time scroll position changes.

https://github.com/surveyjs/survey-creator/assets/17025812/88fd5a5f-9019-48ea-b66d-724cb5e178d1

**Comment by dmitrykurmanov** [comment]
@mikeamelin need exact steps to reproduce the problem. Let's discuss it.

**Comment by tsv2013** [comment]
We need to re-check it after drag/drop extra rows rebuild was fixed

**Comment by mikeamelin** [comment]
@tsv2013 
Looks like the issue has gone.
