### ISSUE TITLE
Theme Builder: An option to embed a theme in the survey JSON

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#4366]
From https://github.com/surveyjs/survey-creator/issues/4320#issuecomment-1635793586

> I would appreciate it if the JSON would be stored within the survey JSON and thus be permanently linked to the survey. The export option is nice, but shouldn't be tied to the code to use a theme. Normal users / users of the editor cannot change the code or need a place in the creator where they can do this per survey.

**Comment by JaneSjs** [comment]
Followed-up with a customer in the original thread: https://github.com/surveyjs/survey-creator/issues/4320#issuecomment-1693293983.
