### ISSUE TITLE
Theme builder/Preview : strange resulting page

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#4371]
![image](https://github.com/surveyjs/survey-creator/assets/14936841/f4033ab7-8bd2-4ea1-aabc-fda0ac7bcc6a)

**Comment by mikeamelin** [comment]
Need to discuss.
https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=101-10&mode=design

@OlgaLarina 
@novikov82

**Comment by mikeamelin** [comment]
Prototype — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=1005-237608&mode=design
