### ISSUE TITLE
No documentation for the onAfterDrop function

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4379]
https://github.com/surveyjs/survey-creator/blob/49273054b6bb04d9c27e4700eda513014905ffb4/packages/survey-creator-core/src/creator-base.ts#L1800C10-L1800C21

The onAfterDrop function is raised when an element was dropped to the design surface. For instance, when a user reorders questions within a survey/page/panel, or when a user reorders choices within a choice-based question. Within this event, use the `options` argument to get information about the processed objects.

* options.fromElement - a source element the current element was dragged from;
* options.draggedElement - the dragged element;
* options.toElement - a target element to which the element was dropped.

**Comment by RomanTsukanov** [comment]
`onAfterDrop` has been renamed to `onDragEnd`: https://github.com/surveyjs/survey-creator/issues/3832

**Comment by JaneSjs** [comment]
The API doc for the `onDragEnd` event: https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onDragEnd.
