### ISSUE TITLE
"showOtherItem" and the "showCommentArea" combined give false Survey Results

### ISSUE THREAD

**Issue by dasboe** [surveyjs/survey-creator#4396]
There is an inconsitency when using the "showOtherItem" and the "showCommentArea" in a "radiogroup".

The Following JSON definiton of a Survey Creator

```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question1",
     "showCommentArea": true,
     "choices": [
      "Item 1",
      "Item 2"
     ],
     "showOtherItem": true
    }
   ]
  }
 ]
}
```

will create this form

<img width="714" alt="Bildschirmfoto 2023-07-31 um 12 09 02" src="https://github.com/surveyjs/survey-creator/assets/119371/1123e5da-03b1-4275-a0e7-1a47c6587068">

First I think it's strange that the default text for "showCommentArea" is "Other (descripe)". Souldn't it be just "Comment"?

But there is also a problem in the Survey Result JSON:

```json
{
    "question1": "Text Other",
    "question1-Comment": "Text Description"
}
```

I would have expected this instead:

```json
{
    "question1": "other",
    "question1-Other": "Text Other",
    "question1-Comment": "Text Description"
}
```

This is because without the "showCommentArea" option the output is as expected

```json
{
    "question1": "other",
    "question1-Other": "Text Other"
}
```

Is this a bug or is there a reasoning behind this behaviour?

**Comment by andrewtelnov** [comment]
@dasboe Unfortuantely, this change will break a lot of projects and we can't impelment it. The easy solution is to add a comment question with a hidden question number index.

Thank you,
Andrew
