### ISSUE TITLE
Question: How to add inline link to File upload question type for the template download

### ISSUE THREAD

**Issue by jithureddy** [surveyjs/survey-creator#4400]
### Are you requesting a feature, reporting a bug or ask a question?
I wanted to add file upload question into my survey with an option to download the template. How to add this?

### What is the current behavior?
There is a Description option for each question, Can we use this to add custom html

### What is the expected behavior?
<img width="1027" alt="image" src="https://github.com/surveyjs/survey-creator/assets/5911189/abc00292-8bdd-4d21-92ae-842d5614c75d">

**Comment by JaneSjs** [comment]
Hello @jithureddy,
You can use Markdown formatting to add custom HTML and display a link in a question's title. 

Consider this demo: [View Demo](https://plnkr.co/edit/c4kpMwYSuorlNh5J).
```
const json = {
  "elements": [
    {
      "type": "file",
      "title": "Please upload your files <a style='color:red' href='a-link-to-download-a-file'>Download a Template</a>",
      "name": "files",
      "storeDataAsText": false,
      "waitForUpload": true,
      "allowMultiple": true,
      "maxSize": 102400,
      "hideNumber": true
    }
  ]
};

 const converter = new showdown.Converter();
    survey.onTextMarkdown.add(function (survey, options) {
        // Convert Markdown to HTML
        let str = converter.makeHtml(options.text);
        // Remove root paragraphs <p></p>
        str = str.substring(3);
        str = str.substring(0, str.length - 4);
        // Set HTML markup to render
        options.html = str;
});
```

For more information on how to enable Markdown formatting for surveys, refer to our online demo: [Convert Markdown to HTML with Showdown](https://surveyjs.io/form-library/examples/edit-survey-questions-markdown/reactjs).

I hope this demo helps. Please feel free to reactivate this thread if you have any questions or require further assistance.
