### ISSUE TITLE
Markdown Formatting - The text contains an additional less-than sign < when creating a bullet-in list

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4401]
User Issue: T14082 - Bullet point issue with CK editor 
https://surveyjs.answerdesk.io/internal/ticket/details/T14082
***
As you can see in the following demo, a title text doesn't actually contain the less-than sign. However, the inplace editor displays a less-than sign < within the text:
```
 "title": "<p>Title</p><ul><li>Item 1</li><li>Item 2</li></ul>",
```
![image](https://github.com/surveyjs/survey-creator/assets/22372972/8f6fea31-9817-4525-b105-07ca117587ea)

**Comment by tsv2013** [comment]
The code in the `doMarkdown` function is responsible for removing root paragraph tag. In your case there is no root paragraph tag. The `doMarkdown` should looks as following:
```JS
function doMarkdown(survey, options) {
  //convert the Markdown text to html
  let str = converter.makeHtml(options.text);
  options.html = str;
}
```
This will keep HTML as it was designed by rich text (HTML) editor. Or you need to implement more complex algorithm for unnecessary tags stripping. Here is the updated example - https://codesandbox.io/s/snowy-hill-dsw7rf?file=/src/SurveyCreatorComponent.jsx

**Comment by JaneSjs** [comment]
@tsv2013 but now, since we do not programmatically remove paragraphs, texts are misalined.
![image](https://github.com/surveyjs/survey-creator/assets/22372972/0ef958ce-8dd8-4ef0-83c5-ecf6333c58b0)

**Comment by tsv2013** [comment]
Of course "P" element can have built-in margins or padding. And it is necessary to reset them. This issue is related to HTML mфrkup generated by editor. Or make markdown converter more smart:
```JS
function doMarkdown(survey, options) {
  let str = converter.makeHtml(options.text);
  str = str.replaceAll("<p>", "<p style='margin: 0'>");
  options.html = str;
}
```

**Comment by tsv2013** [comment]
@JaneSjs  All the issues related to markdown generated by 3rd party tools should be resolved via a custom code.

**Comment by JaneSjs** [comment]
@tsv2013 Thanks, this is better. Would you please also review the video and let me know whether this issue relates to the original one?


https://github.com/surveyjs/survey-creator/assets/22372972/88b57a26-3adb-41d1-910c-8f98ff32fdc5

**Comment by JaneSjs** [comment]
This happens because the following option is enabled:
```
creator.inplaceEditForValues = true;
```
This means that when a user uses inplace editing, a choice's value is edited instead of Text. However, values do not support Markdown.
To resolve the issue, disable the `creator.inplaceEditForValues` option.
