### ISSUE TITLE
Theme Builder - A survey title color is not updated when modifying the Accent foreground color

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4413]
User Issue: T14102 - Change color of Survey Title
https://surveyjs.answerdesk.io/internal/ticket/details/T14102.
***
The survey title color should be modified by the Accent foreground color. However, this doesn't work: a survey title color is not updated.
![image](https://github.com/surveyjs/survey-creator/assets/22372972/2b79a4a5-1efa-4f8e-940b-23a1dde8a255)

**Comment by OlgaLarina** [comment]
Fixed https://github.com/surveyjs/survey-library/commit/b4cbbc7e31e6cd36beabb6558ddd87dde3f42f2c
