### ISSUE TITLE
Display a loading indicator while an image is being uploaded in Survey Creator

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4435]
* T12565 - Logo uploading: add uploading state and prevent multiple fire
https://surveyjs.answerdesk.io/internal/ticket/details/T12565
* T14152 - How to add a loader while image is uploading to your backend service
https://surveyjs.answerdesk.io/internal/ticket/details/T14152

Suggestion: add an option to visually indicate long upload operations when users upload images to a Survey Creator (for a surey logo, Image, and Image Picker quesitons).

For instance:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/d7526693-8dbd-422e-a2ce-5dcb73687973)

**Comment by mikeamelin** [comment]
**Creator** 

Logo — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=778-275323&mode=design&t=diuL2Au3GS4q4yiz-4

Image Picker — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=778-276304&mode=design&t=diuL2Au3GS4q4yiz-4

Image — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=778-276746&mode=design&t=diuL2Au3GS4q4yiz-4

**Library**

File — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=778-1378315&mode=design&t=diuL2Au3GS4q4yiz-4


May be we should to discuss failed uploading.
