### ISSUE TITLE
Add the ability to reset the value to default.

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#4467]
The placeholder property of dropdown.

https://www.figma.com/file/i6Lpc7zkjHtso2oXZV97fo/SurveyJS-Libraries?type=design&node-id=14288-113853&mode=design&t=bIpVcfJZ95RWkc3E-4

It should work for property editor for string and text (question type text (inputType=text) and comment). object should return hasDefaultPropertyValue(propertyName) true for these properties. To reset the value, please call obj.resetPropertyValue().

**Comment by mikeamelin** [comment]
Prototype — https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=757-111034&mode=design
