### ISSUE TITLE
Can I add a date picker property to surveyjs/nodejs project ?

### ISSUE THREAD

**Issue by ReemAlmuhimeed** [surveyjs/survey-creator#448]

**Comment by ReemAlmuhimeed** [comment]
I want it to be a property not a data picker question.

**Comment by tsv2013** [comment]
Could you specify - what do you mean? Property of what object?

**Comment by ReemAlmuhimeed** [comment]
On the right side there's a list of properties for the survey editor. I checked the documentation there's multiple types but date is not one of them.

**Comment by tsv2013** [comment]
Here is the plunker example how to create a custom property editor with select2 widget - https://plnkr.co/edit/udPGDKsEWWvfY9bnLJjH?p=preview

**Comment by tsv2013** [comment]
Here is the plunker example of a custom property editor for short text - https://plnkr.co/edit/Fj91svQRP97au3RTCJdG?p=preview

You can extend these samples with a date picker
