### ISSUE TITLE
The creator.onPropertyValidationCustomError is not raised when a property receives an invalid value

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4480]
User Issue: T14336 - How to capture the event of invalid question field
https://surveyjs.answerdesk.io/internal/ticket/details/T14336
***
The [creator.onPropertyValidationCustomError](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onPropertyValidationCustomError) is not raised when a property error occurs. For instance, a question has an empty/duplicate name: [View Demo](https://codesandbox.io/s/surveyjs-angular-forked-5xmlc5?file=/src/app/components/creator.component.ts).

**Comment by andrewtelnov** [comment]
The user got the solution by handing property grid survey events related to custom question errors.
I am closing the issue without changing the code.
