### ISSUE TITLE
Memory leak when changing tabs within Survey Creator

### ISSUE THREAD

**Issue by tjmurray** [surveyjs/survey-creator#4484]
### Are you requesting a feature, reporting a bug or ask a question?

Bug - memory leak

### What is the current behavior?

Every time you switch tabs in the survey creator, e.g. back and forth between 'Designer' tab and 'Preview' tab, the app leaks memory continuously after every change. My current tab where I have been editing a form is using over 1GB of memory due to this leak. Other tabs ('Logic' and 'JSON Editor') may also be affected but I am not sure.

### What is the expected behavior?

No memory leak when switching tabs.

### How would you reproduce the current behavior (if this is a bug)?

Create a form of decent length (the higher the form length/complexity, the higher the memory leaking), then while in the survey creator, open Chrome memory profiler and observe the memory leak accumulate as you toggle back and forth between 'Designer' tab and 'Preview' tab. Toggle quickly back and forth to see the memory rise especially quickly.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: No public URL available

Test code: for brevity I have included only a short/simple form example below, but this issue gets dramatically worse with larger forms. With this example you should see the memory leak by a few MB every time the tab is toggled, but for a larger form it is 10s of MBs.

```
{
 "title": "Application for Leave",
 "description": "Apply for leave for maternity, study, medical, etc",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "start_date",
     "title": "Start date requested",
     "isRequired": true,
     "inputType": "date"
    },
    {
     "type": "text",
     "name": "end_date",
     "title": "End date requested",
     "isRequired": true,
     "inputType": "date"
    },
    {
     "type": "dropdown",
     "name": "reason",
     "title": "Reason for leave",
     "isRequired": true,
     "choices": [
      {
       "value": "Item 2",
       "text": "Maternity"
      },
      {
       "value": "Item 3",
       "text": "Study"
      },
      {
       "value": "Item 4",
       "text": "Medical"
      }
     ],
     "showOtherItem": true,
     "otherPlaceholder": "Please specify"
    },
    {
     "type": "comment",
     "name": "additional_details",
     "title": "Any additional details/information (optional)"
    },
    {
     "type": "file",
     "name": "supporting_doc",
     "title": "Any supporting document"
    }
   ]
  }
 ]
}
```

### Specify your

* browser: Chrome 
* editor version: 1.9.100

### Screenshot of issue

Screenshot of Chrome profiler after toggling tabs ~100 times. Started at ~20MB and ended at 377MB:

<img width="1728" alt="Screenshot 2023-08-23 at 14 19 05" src="https://github.com/surveyjs/survey-creator/assets/30073348/e6de8070-3747-477b-a4a3-681e30fe1954">

**Comment by JaneSjs** [comment]
Hello @tjmurray,
Thank you for contacting us and thank you for sharing a survey JSON. To help me reproduce the issue quicker, would you please specify your JavaScript development platform?

**Comment by tjmurray** [comment]
Vue 3

**Comment by tsv2013** [comment]
Unfortunately there is no SurveyJS Creator for Vue3. Could you please check - what survey-creator library are you using and what is the version of this library?

**Comment by tjmurray** [comment]
"survey-creator-knockout": "1.9.100",
"survey-knockout-ui": "1.9.100",
