### ISSUE TITLE
Theme Tab - No tooltip for the Reset theme button

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4488]
The following button resets theme settings to their initial values:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/400ead4f-9364-4b6d-bae9-31383cdaafc8)

However, this button doesn't have a tooltip, and it may be confused with the Undo action.
Suggestion: please add a tooltip to the Reset theme button.

**Comment by RomanTsukanov** [comment]
"Reset theme settings to default"
