### ISSUE TITLE
The color editor can have an empty value

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#4489]
Needed for the signature pad properties "Pen color" & "Background color"

![image](https://github.com/surveyjs/survey-creator/assets/14936841/e6a16621-abcc-4ee8-b7c1-34a0d637794e)

**Comment by mikeamelin** [comment]
We already have this state in the design project — https://www.figma.com/file/i6Lpc7zkjHtso2oXZV97fo/SurveyJS-Libraries?type=design&node-id=16638-311659&mode=design&t=p6BWuNoSrL0lxMxE-4
