### ISSUE TITLE
Survey creator styling broken causing sidebar to appear at the bottom

### ISSUE THREAD

**Issue by iromanro** [surveyjs/survey-creator#4492]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Broken css styling because of a calculation on a flex

### What is the expected behavior?
Styling shouldn't break

### How would you reproduce the current behavior (if this is a bug)?
Follow setup steps here: https://surveyjs.io/survey-creator/documentation/get-started-react
Open survey creator, notice the sidebar appears at the bottom instead of at the side
https://jumpshare.com/v/wOW4F4MldLTr1z0V0CNr

Commenting out line 4807 in survey-creator-core.css fixes the issue.

### Specify your

* browser: Chrome and Firefox

**Comment by JaneSjs** [comment]
Hello @iromanro,
Thank you for reaching out to us. Please refer to the following demo: [View Demo](https://codesandbox.io/s/bold-sunset-9gm63j?file=/package.json:76-211).

It shows a sample example on how to integrate a Survey Creator into a React app. Please review the creator to confirm that a sidebar appears correctly:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/58e67e53-f646-4f21-bb61-cd97fd5397ea)

Please ensure that you correctly installed the following packages, and that they have the same version:
```
"survey-core": "1.9.105",
"survey-creator-core": "1.9.105",
"survey-creator-react": "1.9.105",
"survey-react-ui": "1.9.105"
```
If the issue remains, please share a problematic demo for research.

I look forward to your reply.

**Comment by ajithberlin** [comment]
I am also Facing this issue,
![image](https://github.com/surveyjs/survey-creator/assets/35306746/a2391b5c-e63d-4238-9197-8647504330eb)
![image](https://github.com/surveyjs/survey-creator/assets/35306746/96234e9b-6491-466f-93a8-0bc8d0a94b12)

**Comment by JaneSjs** [comment]
Hi @ajithberlin,
Thank you for a follow-up. Unfortunately, I couldn't produce this issue on my end.
Please share a reproducible demo for research.

**Comment by JaneSjs** [comment]
Hi @ajithberlin,
Unfortunately, I didn't receive a problematic demo from your end. Should you require further assistance, please feel free to reactivate this thread.
