### ISSUE TITLE
SurveyJS : Usage Detail

### ISSUE THREAD

**Issue by psaini2018** [surveyjs/survey-creator#450]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@psaini2018 SurveyJS Builder (Editor) is free for non-commercial use. Please go to the license page for [more details](https://surveyjs.io/Home/Licenses)
Here is the [docs for storing/loading survey definition into/from database](https://surveyjs.io/Documentation/Builder/#loadsavesurvey).

Thank you,
Andrew

**Comment by psaini79** [comment]
@andrewtelnov  Thanks for the reply. I want to know the procedure correctly:
1) Survey Editor to build the survey and using save callback method, it cab be saved inside the DB.
2) Using Survey JS/form library, it can be pulled from DB and consumer fill the survey.

Or we can user Survey Editor for both i.e. building survey and link can be shared with a user to fill the survey where  he will see the final survey?

**Comment by andrewtelnov** [comment]
@psaini2018 You will find the examples of services for different platforms with our libraries [on this page](https://surveyjs.io/Examples/Service/).
We are saving the data in the database in the WordPress plugin. For others platforms we are using in-memory data. However, you should get a clear idea where to put your code to store/load the data into/from database.

Thank you,
Andrew
