### ISSUE TITLE
Properties in multilang

### ISSUE THREAD

**Issue by lukasmedia** [surveyjs/survey-creator#451]
### Are you requesting a feature, reporting a bug or ask a question?

Question, but maybe a feature :-)

### What is the current behavior?

I can add custom propertjes to the questionbase. See: https://surveyjs.io/Examples/Builder/?id=addproperties
This works fine.

### What is the expected behavior?

If i change the locale to another language and change the property value i just added, the value is overwritten and not added as a new value for that language / property.

Mabye its an idea to add another type for custom properties for example
`
.addProperty("survey", "tag:translation");
`

Tested page URL:

https://surveyjs.io/Examples/Editor/?id=questioneditor
See tab "JSON editor". "Tag" is not translated.

### Specify your

* browser: any
* editor version: 1.0.58

**Comment by tsv2013** [comment]
You need to declare this property the following way:
```
    {
      name: "propertyName",
      serializationProperty: "locPropertyName"
    },

```

The question is more related to the SurveyJS library - https://github.com/surveyjs/surveyjs

**Comment by lukasmedia** [comment]
I tried several possible solutions, so far i have this:
`
Survey.JsonObject.metaData.addProperty("questionbase", { name: "altTitle", serializationProperty: "altTitle" });
`

But this results in: TypeError: e[this.serializationProperty] is undefined

**Comment by tsv2013** [comment]
`locPropertyName` means `locAltTitle` in your case:

`Survey.JsonObject.metaData.addProperty("questionbase", { name: "altTitle", serializationProperty: "locAltTitle" });`
