### ISSUE TITLE
Broken drop-down menu-2.

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#4517]
- [ ] we should use another drop-down-popup (creator style) for Logic
- [ ] no top padding

https://www.figma.com/file/SSMZUWJve1zuMSeA5E5YpA/Creator-Preview?type=design&node-id=101-221275&mode=design&t=Q7r5wdGuz8PmbBN7-4
![Image](https://github.com/surveyjs/survey-creator/assets/17025812/017fdd37-812e-4e17-a492-96589ff4c665)

![Image](https://github.com/surveyjs/survey-creator/assets/17025812/20fbf77f-f45d-4dd1-aed1-d70da446f86c)

**Comment by novikov82** [comment]
Not correct styles in Logic
