### ISSUE TITLE
Exit JSON Editor tab when JSON contains errors

### ISSUE THREAD

**Issue by taylordardono** [surveyjs/survey-creator#4518]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

On survey creator v2, if I switch to the JSON Editor tab and the JSON contains errors, I cannot switch back to any other tab until I fix the errors in the JSON object itself.

Is there a way to switch back to any other tab after entering the JSON Editor tab and it cotains any errors? This errors are for example required properties from a question type that are missing, not JSON errors like a missing comma, or bracket.

### How would you reproduce the current behavior (if this is a bug)?

In the survey creator:

1. Go to the JSON Editor tab
2. Create a JSON error/ Cotains a JSON error in the content there
3. Try to switch back to Designer tab or any other tab
4. Cannot change tab

### Specify your

* browser: `116.0.5845.110`
* editor version:
```
    "@angular/cdk": "~15.1.1",
      ...
    "survey-angular-ui": "1.9.104",
    "survey-core": "1.9.104",
    "survey-creator-angular": "1.9.104",
    "survey-creator-core": "1.9.104",
```

I could not find anything in the docs regarding this.

Thanks for your time

**Comment by JaneSjs** [comment]
Hello @taylordardono,
Thank you for sharing your usage scenario. Unfortunately, at the moment, it is impossible to dismiss validation errors and proceed from the JSON Editor tab without addressing the errors.

We will consider an option that allows developers to choose whether to ignore validation errors or not. We will keep you informed about any progress.

Thank you for your input.

**Comment by andrewtelnov** [comment]
@taylordardono @JaneSjs You will be able to use the following code from version 1.9.106
```js
  creator.onActiveTabChanging.add((sender, options) => {
    if(creator.activeTab === "editor") {
      options.allow = true;
    }
  });
```
If JSON has errors that allows us to build a model, then Creator will call onActiveTabChanging with `options.allow` attribute equals to `false`. You can change it to `true` to allow to exit JSON editor.

Thank you,
Andrew
