### ISSUE TITLE
How can I make property in the survey builder to be read-only

### ISSUE THREAD

**Issue by NikolaMalezanoski** [surveyjs/survey-creator#452]
Hi @andrewtelnov

How can I make property in the survey builder to be read-only base of custom added property?

I try to use onCanShowProperty event and works for "General" tab but not for "Choices" Tab.

editor.onCanShowProperty .add(function(editor, options) {
            if ( !options.obj.isEditable ) {
              options.property.readOnly = true;
            }
        });

https://plnkr.co/edit/0SHvbuEybUmDimdsN2Vw?p=preview

I don't have a problem with the properties in the  "General" tab.
I can't make "Choices" (values, text and custom field) to be read-only 

![survey editor](https://user-images.githubusercontent.com/10244738/49420554-fcb36280-f7c6-11e8-9f2b-ca8eed25e9ef.gif)

**Comment by andrewtelnov** [comment]
@NikolaMalezanoski Please use the following code:
`Survey.JsonObject.metaData.findProperty('itemvalue', "value").readOnly = true;`

I will update [the documentation](https://surveyjs.io/Documentation/Builder/#addproperties)

Thank you,
Andrew

**Comment by NikolaMalezanoski** [comment]
Thanks @andrewtelnov 

The question was how I can set up property to be read-only for the specific questions base of the custom property of the question. 
Please have a look into this example https://plnkr.co/edit/0SHvbuEybUmDimdsN2Vw?p=preview

I add the custom property 
` 
Survey.JsonObject.metaData.addProperty('question', {
                name: 'isEditable:boolean',
                default: true
            });
`
 base of that property value i want to make question to be editable or not

**Comment by andrewtelnov** [comment]
@NikolaMalezanoski We do not have this functionality at the moment.  I will add it into our TODO list. We support dynamic visibility only right now. Please ping on the next week.

Thank you,
Andrew

**Comment by NikolaMalezanoski** [comment]
Thanks @andrewtelnov , I will remind you next week

**Comment by NikolaMalezanoski** [comment]
hi @andrewtelnov 
Do you have any update on this ticket?

**Comment by andrewtelnov** [comment]
@NikolaMalezanoski I was trying to implement it sometimes ago and I spent about 20 minutes. I  understood that it would require several hours of coding, rollback my changes, I put it in our TODO list.
Since you did not comeback, I believed it was not so important.

Thank you,
Andrew

**Comment by NikolaMalezanoski** [comment]
Hi @andrewtelnov 

I appreciate your effort, but I don't want to disturb you during the holidays.
If it is possible, can you please try to find the time and put on the top of your TODO list 

Kind regards
Nikola

**Comment by andrewtelnov** [comment]
@NikolaMalezanoski  I have added a new method: editor.onGetPropertyReadOnly
```js
  /**
   * The event is called on setting a readOnly property of the property editor. By default the property.readOnly property is used.
   * You may changed it and make the property editor read only or enabled for a particular object.
   * <br/> sender the survey editor object that fires the event
   * <br/> options.obj the survey object, Survey, Page, Panel or Question
   * <br/> options.property the object property (Survey.JsonObjectProperty object). It has name, className, type, visible, readOnly and other properties.
   * <br/> options.readOnly a boolean value. It has value equals to options.readOnly property by default. You may change it.
   */
  public onGetPropertyReadOnly: Survey.Event<
    (sender: SurveyEditor, options: any) => any,
    any
  > = new Survey.Event<(sender: SurveyEditor, options: any) => any, any>();
```
Thank you,
Andrew

**Comment by NikolaMalezanoski** [comment]
Thanks @andrewtelnov 
you are the best
