### ISSUE TITLE
How to bind a custom component for a custom property in the survey creator property grid

### ISSUE THREAD

**Issue by taylordardono** [surveyjs/survey-creator#4525]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

I want to bind a custom component to a custom property for the survey creator property grid. This was previously achieved in V1 with the survey ko

```
SurveyEditor.SurveyPropertyEditorFactory.registerCustomEditor('propertyType', customComponent);
```
Now on switching to the V2, as far as I understand, we have to register the custom property type in the `PropertyGridEditorCollection` like so

```
PropertyGridEditorCollection.register({
        fit: function (prop) {
          return prop.type === 'propertyType';
        },
        getJSON: function (
          obj: QuestionCustomModel,
          prop: JsonObjectProperty,
          options: SurveyCreatorModel
        ) {
          return { type: 'propertyType' }
        },
      });
```
And the getJSON property should handle the render of the custom property in the survey creator property grid.
I followed the guide here https://surveyjs.io/survey-creator/examples/add-custom-property-editor/angular# , registering the `'propertyType'` custom property as a custom widget, and then in the `getJSON` set the return as `{type: 'propertyType}` but I could not make it work

This component I want to use for the custom property is an angular component created by ourselves

### Specify your

* browser: Chrome 116.0.5845.110
* editor version:
```
    "survey-angular-ui": "1.9.104",
    "survey-core": "1.9.104",
    "survey-creator-angular": "1.9.104",
    "survey-creator-core": "1.9.104",
```

Thanks for your support

**Comment by taylordardono** [comment]
Solved in our side, sorry for the inconvenience

**Comment by taylordardono** [comment]
I have to reopen this one, what we exactly want to achieve is in an specific property grid category, add a custom component that would be use **only** as a property editor in the grid for an added custom property
![image](https://github.com/surveyjs/survey-creator/assets/79921564/5de42adc-295a-440e-86ff-d6ebab0ee269)

Case: Add a new property in the custom questions category(no problem with that) but we want to use our custom angular component for that added custom property.

Could you provide us a quick overview on this one in order to achieve this?

What are the exact properties we should add in the `Serializer` in order to link the added `custom-property` to our `custom-angular-component`?
```
Serializer.addProperty('question-name', {
        name: 'custom-property',
        category: 'Custom Questions',
        type: 'custom-angular-component', ====> angular selector ? name registered in the AngularFactoryComponent instance ? any other option
        ...,
        what else is missing?
 });
```

How should the `PropertyGridEditorCollection` register work according to the added `custom-property`?

Thanks a lot for your time and the survey tool

KR, Unai

**Comment by JaneSjs** [comment]
Hello @taylordardono,
Please accept my apologies for the delayed reply. It seems that I have missed your question. If you wish to register a custom Angular component and use it as a custom property grid editor, please follow this tutorial: [Integrate Third-Party Angular Components](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-angular).

The main idea is to register a custom question type and use an Angular component to render a custom question.

To use a custom Angular component as a custom property editor, set the property's type to some custom value and use the `PropertyGridEditorCollection.register` function to register a custom editor where the Angular component will be used as an editor's definition:
```
PropertyGridEditorCollection.register({
  fit: function (prop) {
    return prop.type === "customPropType";
  },
  getJSON: function () {
    return {
      type: "your-custom-question-type-here",
      //...
    };
  }
});
```
In the [Use the Custom Component as an Editor in the Property Grid](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-angular#use-the-custom-component-as-an-editor-in-the-property-grid) section, you'll learn how to use a custom editor for a custom property of type 'color'.

If you do not want to make a custom question available in a toolbox, use the [creator.toolbox.removeItem](https://surveyjs.io/survey-creator/documentation/api-reference/questiontoolbox#removeItem) function.

For the record: SurveyJS Creator requires a [commercial developer license](https://surveyjs.io/licensing). With a developer license, please feel free to reach out to us at [Help Desk](https://surveyjs.answerdesk.io/ticket/list?preset=mytickets). The response time in Help Desk is usually less than 24 hours.

Thanks
