### ISSUE TITLE
Preview Tab | Page Navigator - Page remains unactive/grayed out even though it is made visible

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4536]
User issue: T14350 - Html content is showing in bottom table of contents
https://surveyjs.answerdesk.io/internal/ticket/details/T14350
***
To reproduce the issue, run [this demo](https://codesandbox.io/s/fancy-cloud-2q346w?file=/src/survey_json.js) and enter 'YES' to the first question. Page 2 is visible now, and it is available within TOC. However, the page remains unactive within the bottom page navigator:

![image](https://github.com/surveyjs/survey-creator/assets/22372972/36b212d4-8137-49aa-ac30-fdbcf73f61d9)

**Comment by JaneSjs** [comment]
@andrewtelnov, I'm reactivating this issue. I discussed it with @tsv2013.
The creator's Preview tab allows survey editors to validate the survey. Therefore, this page navigator should not prevent survey editors from accessing survey pages. 
The page selector should not act like a survey table of contents or a navigation element. 
This page selector should allow a survey editor to navigate to any survey page regardless of page visibility or conditional logic/branching configured for a survey.

Therefore, even though a page is invisible, a page selector should display this page within a list and a survey creator should be able to navigate to it. 
***
To validate survey logic, it is necessary to use a navigation element specifically designed to that purpose: a [table of content](https://surveyjs.io/form-library/examples/table-of-contents/reactjs) of [buttons progress bar](https://surveyjs.io/form-library/examples/configure-form-navigation-with-progress-indicators/reactjs#).

**Comment by andrewtelnov** [comment]
@JaneSjs @tsv2013 I have added `TestSurveyTabViewModel.enableInvisiblePages = true;` static boolean property for now.
If somebody needs to revert the behavior then it should be set as:
`TestSurveyTabViewModel.enableInvisiblePages = false;`.

Thank you,
Andrew
