### ISSUE TITLE
Mobile: Do not set focus on title span on creating new question/panel

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#4540]
It triggers showing keyboard on the bottom and reduce the space.

**Comment by ma-sommer** [comment]
Is there any way to prevent this on desktop too, via an option of the survey-creator?

**Comment by JaneSjs** [comment]
Hello @ma-sommer,
You can fix a toolbox so that it doesn't scroll when you add a new question. For this, apply the following styles to a survey creator's container.
```html
<div id="surveyCreatorContainer" style="position: absolute; height: 100%; width: 100%"></div>
```
[View Demo](https://codesandbox.io/p/sandbox/thirsty-gwen-87c56s?file=%2Fpublic%2Findex.html%3A6%2C1-8%2C1)

**Comment by ma-sommer** [comment]
Thank you @JaneSjs that works!
