### ISSUE TITLE
Mobile: Wrong drag&drop icon position

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#4546]
Drag&Drop icon position in choices is wrong.
![image](https://github.com/surveyjs/survey-creator/assets/5655108/7ec14044-4057-4dba-ab25-913fc9be8bde)

**Comment by dmitrykurmanov** [comment]
https://www.figma.com/file/jcuAUsN02n2yJerx39mqf9/Previews?type=design&node-id=892-109972&mode=design

**Comment by mikeamelin** [comment]
We have to change a bit paddings for mobile view
![Screenshot_2023-09-07_at_16 48 26](https://github.com/surveyjs/survey-creator/assets/17025812/97bdff94-ac4d-4741-8afc-8a28aff55938)

**Comment by dmitrykurmanov** [comment]
still wrong on IPAD:

![image](https://github.com/surveyjs/survey-creator/assets/22315929/3d4f4d27-0797-4405-801f-c7aa7769aa44)

**Comment by dmitrykurmanov** [comment]
- [ ] ![image](https://github.com/surveyjs/survey-creator/assets/22315929/09bd744a-9d6e-4f8f-8751-3dd8f3619735)

**Comment by mikeamelin** [comment]
- [ ] no icons for Drop-Down and TagBox at all (iPad / iPhone)
- [ ] ranking

![Screenshot 2023-09-14 at 20 12 25](https://github.com/surveyjs/survey-creator/assets/17025812/421fc546-a17c-4ef0-a64f-45da15697233)

**Comment by mikeamelin** [comment]
- [ ] broken hover
![Screenshot 2023-09-15 at 13 02 55](https://github.com/surveyjs/survey-creator/assets/17025812/306ba9c0-e283-4d5d-9cb8-1487e0f4853f)

**Comment by dmitrykurmanov** [comment]
- [ ] no icons for Drop-Down and TagBox at all (iPad / iPhone)
