### ISSUE TITLE
Impossible to drop a question side-by-side to other questions located within a nested Dynamic Panel survey element

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4566]
User Issue: T14541 - Drag and drop bug
https://surveyjs.answerdesk.io/internal/ticket/details/T14541

https://github.com/surveyjs/survey-creator/assets/22372972/b87edddc-3894-437e-9334-936f75670ded

**Comment by JaneSjs** [comment]
@tsv2013 Additionally, the following issues take place:
[The same demo](https://codesandbox.io/s/sharp-field-c2jqqx)

* After replacing the **Fiziniai** dynamic panel (`pareiskejo_dalyvavimo_kitu_subjektu_valdyme_fiziniai`) with **Juridiniai** (`pareiskejo_dalyvavimo_kitu_subjektu_valdyme_juridiniai`), it is no longer possible to drop questions within the **Fiziniai** panel.
​
* If you create a copy of a **Fiziniai** panel, it is also impossible to drop questions inside the copy.
​

Uploading 2023-09-11_22-38-03.mp4…

**Comment by andrewtelnov** [comment]
@JaneSjs @tsv2013 Questions names are not unique in this examples and it brings the issue.
I have created two other issues: [Duplicate action issue](https://github.com/surveyjs/survey-creator/issues/4604) and [Unique name for questions in panel dynamic template](https://github.com/surveyjs/survey-creator/issues/4605).

Thank you,
Andrew

**Comment by JaneSjs** [comment]
Those issues were fixed in 1.9.108.
