### ISSUE TITLE
A custom theme entry is multiplied within the Themes list

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4571]
[View Demo](https://codesandbox.io/s/musing-silence-l4dl3f?file=/src/SurveyCreatorComponent.jsx)

![image](https://github.com/surveyjs/survey-creator/assets/22372972/8e4c468c-c11f-495b-a2c8-7c291248258a)

**Comment by tsv2013** [comment]
This is caused by CodeSandbox HMR. To check it can be added console log:
```JS
console.log('PredefinedThemes.push("custom")');
PredefinedThemes.push("custom");
```
