### ISSUE TITLE
Rating values for matrix

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#4583]
- [ ] no ability to set global settings for Rating question for all columns

![Image](https://github.com/surveyjs/survey-creator/assets/17025812/11e07eff-ba4b-4cb8-8b8a-7c5449a6e018)

**Comment by JaneSjs** [comment]
I checked this with v1.12.15 and confirmed that the Rating Scale settings are available for an individual matrix column:
![Image](https://github.com/user-attachments/assets/1c691579-72e4-4e6c-ba10-6d181c69f773)
![Image](https://github.com/user-attachments/assets/df59009a-70ba-4f56-85bd-cb9ca72cc583)
