### ISSUE TITLE
Customizing UI on setting up logic

### ISSUE THREAD

**Issue by kmhigashioka** [surveyjs/survey-creator#4624]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
Setting up of logic only caters to created questions. 
![image](https://github.com/surveyjs/survey-creator/assets/5535475/0bad5504-df40-426b-a3cc-47a02e2c2b84)

### What is the expected behavior?
We would like to check if we can extend/customize the "Select" and "Equals" buttons. E.g. we want to include a variable and this will be available on the selection. Once the user selects this variable, we can provide set of operators that the user can select from. Sample screenshots:
![image](https://github.com/surveyjs/survey-creator/assets/5535475/1f93b8c3-c86c-494c-aa23-1c41dbf98a80)
![image](https://github.com/surveyjs/survey-creator/assets/5535475/3dac3933-5066-40ff-82d1-b42a843962c9)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by JaneSjs** [comment]
Hello @kmhigashioka,
The Select... dropdown displays questions and calculated values available within a survey. The second dropdown displays a list of logic operators available for the selected question. Would you please clarify how exactly you wish to customize these popup lists?

P.S. Please also clarify whether you have a [commercial developer license](https://surveyjs.io/licensing).

Thanks
