### ISSUE TITLE
Custom condition property not displaying the value on textbox

### ISSUE THREAD

**Issue by kmhigashioka** [surveyjs/survey-creator#4628]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
The value is not displayed on the textbox when setting a logic on a custom property with `type: condition`.

https://github.com/surveyjs/survey-creator/assets/5535475/08425181-4ccd-4109-85b4-2df72cea5a76

### What is the expected behavior?
The expression will be displayed on the textbox.

### How would you reproduce the current behavior (if this is a bug)?
1. Create custom widget. (https://surveyjs.io/survey-creator/examples/custom-colorpicker-property-editor/reactjs#)
2. Define the custom property with `condition` as type.
3. Set the conditions on "Custom visible if" property.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://fnj9d3.csb.app/

Test code
https://codesandbox.io/s/friendly-cannon-fnj9d3?file=/src/SurveyCreatorComponent.jsx
```
Serializer.addClass(
  CUSTOM_TYPE,
  [
    {
      name: "colorPickerType",
      default: "Slider",
      choices: ["Slider", "Sketch", "Compact"],
      category: "general",
      visibleIndex: 2 // After the Name and Title
    },
    {
      name: "disableAlpha:boolean",
      dependsOn: "colorPickerType",
      visibleIf: function (obj) {
        return obj.colorPickerType === "Sketch";
      },
      category: "general",
      visibleIndex: 3 // After the Name, Title, and Color Picker type
    },
    {
      name: "customVisibleIf:condition",
      category: "logic"
    }
  ],
  function () {
    return new QuestionColorPickerModel("");
  },
  "question"
);

```

### Specify your

* browser: Brave 1.57.57
* editor version: 1.9.109

**Comment by andrewtelnov** [comment]
@kmhigashioka Please add this proprety into your model:
```js
  get customVisibleIf() {
    return this.getPropertyValue("customVisibleIf");
  }
  set customVisibleIf(val) {
    this.setPropertyValue("customVisibleIf", val);
  }

```
Here is [the working example](https://codesandbox.io/s/inspiring-minsky-rd7sr2).

Thank you,
Andrew

**Comment by kmhigashioka** [comment]
Ahh yes, it works. Thanks @andrewtelnov ! :bow:
