### ISSUE TITLE
Bug in RegEx Validation documentation

### ISSUE THREAD

**Issue by tjmurray** [surveyjs/survey-creator#4648]
### Are you requesting a feature, reporting a bug or ask a question?

Bug in RegEx Validation documentation / live example

### What is the current behavior?

On the [documentation page for Form Validation](https://surveyjs.io/form-library/examples/javascript-form-validation/reactjs#), the example it gives for regex uses a regex that is wrapped with '/', which means that the regex doesn't work (both on this example page and when I try to use it on my own instance). Clearly there was a change in the SurveyJS implementation which means that it no longer expects wrapping characters.

### What is the expected behavior?

The documentation / example form should NOT wrap regex with '/' (or any other character).

In other words, the example regex should be: `(?=.*d)(?=.*[a-z])(?=.*[A-Z])(?!.*s)(?=.*[!-@#$*])`
Instead of: `/(?=.*d)(?=.*[a-z])(?=.*[A-Z])(?!.*s)(?=.*[!-@#$*])/`

### How would you reproduce the current behavior (if this is a bug)?

Go to the [documentation page for Form Validation](https://surveyjs.io/form-library/examples/javascript-form-validation/reactjs#), then provide a valid input for the "RegEx Validator" example in the form, e.g. Ab1$, and you will see that the RegEx validation always returns false even though the input is valid.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: [documentation page for Form Validation](https://surveyjs.io/form-library/examples/javascript-form-validation/reactjs#)

### Specify your

* browser: Chrome
* editor version: 1.9.110

**Comment by JaneSjs** [comment]
Hello @tjmurray,
Thank you for reporting this issue. We'll validate our documentation and demo and fix the issue.

Thank you
***
Test string: `Aa1*bcdef`
A [demo](https://surveyjs.io/form-library/examples/javascript-form-validation/reactjs#) shows an error:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/7616bc5c-2731-4179-a5cf-3d5655713245)

The following regex works correctly: `"regex": "(?=.*d)(?=.*[a-z])(?=.*[A-Z])(?!.*s)(?=.*[!-@#$*])"`
[View Demo](https://plnkr.co/edit/rukQQ489E7mtfi2s)

**Comment by RomanTsukanov** [comment]
Hi, @tjmurray!

As you correctly pointed out, the regular expression doesn't need to start and end with a forward slash, but this is not the main issue here. It turns out that the expression is stuck in an infinite loop because it contains only lookaheads. Another issue is that backward slashes need to be escaped. Taking all this into account, the correct expression should look as follows:

`(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\\s)(?=.*[@$!%*?&])[\\da-zA-Z@$!%*?&]+`

We've added this fix to the demo. It will be available with the next update of our website.

Thanks!

**Comment by tjmurray** [comment]
Great stuff, thanks for sorting it and being so responsive. P.S. I think an easy way to get around the issue of "it contains only lookaheads" is to leverage  ```^``` and ```$``` , for example my working RegEx for a particular string verification is ```^(?=[a-zA-Z0-9]{8}$)(?!.*[oOlLiIuU])``` (must be 8 alphanumeric characters and not contain certain letters). Perhaps this doesn't help for your case though, not sure
