### ISSUE TITLE
no defaultLocale property on editorLocalization

### ISSUE THREAD

**Issue by jburghardt** [surveyjs/survey-creator#4653]
To set a default locale on the creator instance, the docs mention the following snippet in https://surveyjs.io/survey-creator/documentation/survey-localization-translate-surveys-to-different-languages

`editorLocalization.defaultLocale = "fr";
`

but the editorLocalization has no defaultLocale prop. is this an error ?

**Comment by JaneSjs** [comment]
Hello @jburghardt,
If you wish to modify a survey creator locale, you can change the [editorLocalization.currentLocale](https://github.com/surveyjs/survey-creator/blob/d063593435e048b4c294f3cafdc3fa387e569cad/packages/survey-creator-core/src/editorLocalization.ts#L7) property. Also, you can update the [creator.locale](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#locale) property.

Regarding the `editorLocalization.defaultLocale` property usage: we'll validate our documentation in this regard.

Thank you.
