### ISSUE TITLE
reduce size by allowing only required locales to be imported

### ISSUE THREAD

**Issue by jburghardt** [surveyjs/survey-creator#4654]
### Are you requesting a feature, reporting a bug or ask a question?

Feature request

### What is the current behavior?

There is no way to import only a selected few languages from the creator. This leads to a big bundle size.
Current size of Creator + Survey Forms

- without languages - ~ 5.25MB
- with languages - ~ 6.54MB

![image](https://github.com/surveyjs/survey-creator/assets/10438767/4d262550-da9d-4872-87c3-8a9c4cc5c9fe)

### What is the expected behavior?

Dont bundle all Languages in one File, and let the user decide what languages to use by importing them.

**Comment by jburghardt** [comment]
i think this is also n open problem https://github.com/surveyjs/survey-creator/issues/2731

**Comment by tsv2013** [comment]
We'll consider to ship a set of localization files with the package.
