### ISSUE TITLE
Translation. Naming Issue

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#4660]
The first column must be used for a type of strings. 

![Image](https://github.com/surveyjs/survey-creator/assets/17025812/3f63b1ec-7354-4990-9df3-d5f6feb625a0)

**Comment by JaneSjs** [comment]
Everything works as expected - the first column lists choice values:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/e2222ab7-243f-45ce-9684-777a24d8dc38)
