### ISSUE TITLE
Extending rating scale question

### ISSUE THREAD

**Issue by kmhigashioka** [surveyjs/survey-creator#4661]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
Hi! I would like to check if this is doable, I'm trying to create a new question type which is enps. In our use-case, the enps behaves the same as Rating scale question but there can only be one instance of enps question and the user should be able to select that question from "Add question" selection dropdown. I tried to create a custom widget and inherit the rating scale model and use the React UI. However, the display is different. 
![image](https://github.com/surveyjs/survey-creator/assets/5535475/2a2eefec-0d1d-41af-9983-d7328467323c)

### What is the expected behavior?
Expecting to see the same UI as rating scale question.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/s/flamboyant-sun-jj8ctr?file=/src/SurveyCreatorComponent.jsx

Test code

```
export class EnpsQuestionModel extends QuestionRatingModel {
  getType() {
    return CUSTOM_TYPE;
  }
}

Serializer.addClass(
  CUSTOM_TYPE,
  [],
  function () {
    return new EnpsQuestionModel("");
  },
  "question"
);

ElementFactory.Instance.registerElement(CUSTOM_TYPE, (name) => {
  return new EnpsQuestionModel(name);
});

ReactQuestionFactory.Instance.registerQuestion(CUSTOM_TYPE, (props) => {
  return React.createElement(SurveyQuestionRating, props);
});

```

### Specify your

* browser: Firefox 111.0.1
* editor version: 1.9.110

**Comment by JaneSjs** [comment]
Hello @kmhigashioka,
If you wish to create a copy of a Rating question but with some customized settings like name and title, you can use the `creator.toolbox.addItem` function. Consider this code:
```
creator.toolbox.addItem({
    name: "nps",
    title: "NPS",
    iconName: "icon-rating",
    isCopied: true,
    id: "npsQuestion",
    category: "General",
    json: {
      type: "rating",
      title: "How satisfied are you with your in-store experience today?",
      rateType: "stars"
    }
});
```
Please let me know if this option works for you.

P.S. Let me note that a SurveyJS Creator is available under a [commercial developer license](https://surveyjs.io/licensing).
