### ISSUE TITLE
Questions with same name but in different dynamic panel give errors

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-creator#4667]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
Questions with same name but in different dynamic panel give errors

### What is the expected behavior?
Questions with same name but in different dynamic panel should not give errors

### How would you reproduce the current behavior (if this is a bug)?
https://plnkr.co/edit/pRVcZHZfIUifuaOS

Copy the json from this Plunker into the Survey Creator and see the errors on the JSON Editor page.

### Specify your

* browser: Firefox
* editor version: latest

**Comment by andrewtelnov** [comment]
@Lionqueen94 A question name should be unique. You can drag out/in a question from/into panel or dynamic panel. The question name will be the same, it will not change and it could not.
Having several questions with the same name can lead to different issues.
We started to show these errors recently. If you need to have the same names in your response JSON, please use "valueName" question property. It doesn't need to be unique.

Thank you,
Andrew

**Comment by Lionqueen94** [comment]
Ah I see, indeed when moving them around it makes sense to be strict on the unique naming. I've added valueNames to my questions and updated the names, thanks for the quick reply!
