### ISSUE TITLE
Inconsistent logo size validation

### ISSUE THREAD

**Issue by kmhigashioka** [surveyjs/survey-creator#4675]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
There is no image size validation when uploading logo from survey header but there is when uploading from property. 
![image](https://github.com/surveyjs/survey-creator/assets/5535475/237d80f7-475d-44d0-a1a5-9431f8411019)

### What is the expected behavior?
Applies the 64KB file size validation on header as user can upload > 1MB which breaks the Translation when viewing/editing in Translation.

### How would you reproduce the current behavior (if this is a bug)?
1. Go to https://surveyjs.io/try/reactjs#try-creator.
2. On the survey header, upload a logo that is more than 64KB in size.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/try/reactjs#try-creator

Test code

```
your_code_here

```

### Specify your

* browser: Firefox 111.0.1
* editor version:

**Comment by JaneSjs** [comment]
Hello,
We decided to disable the uploaded file size validation. Now, there is no restriction to the size of uploaded images. Please upgrate your Survey Creator library to the most recent version. If you wish to limit the size of uploaded images, you can handle this using the [creator.onUploadFile](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onUploadFile) function.

Please feel free to reactivate this thread if you have any further questions.
