### ISSUE TITLE
Multi-Selection Matrix - Inputmask is reverted to its previous value in UI

### ISSUE THREAD

**Issue by ale-x-may** [surveyjs/survey-creator#4690]
Hello,

using the third-party Robin Herbots Inputmask plugin it is possible to mask input fields of text and multipletext questions. In addition to this, we also need that functionality for matrix questions, i.e. for columns ("matrixdropdowncolumn") of textual input. Since the inputMask property appears for all columns by default, but only works for textual inputs, I adapted the properties' visibleIf to the effect that inputMask is only shown for columns of cellType "text" and inputType "text" (see currency column below):

![matrix-inputMask](https://github.com/surveyjs/survey-creator/assets/126170045/57f13f5e-de3c-43e7-86d6-5f125929bb23)

Luckily it works all fine in the Preview:

![matrix-inputMask-input](https://github.com/surveyjs/survey-creator/assets/126170045/e00b4a97-577e-42ff-a162-ea44eebc9c57)

But the problem is that after refreshing the page the inputMask field in the Creator always shows the defaultValue ("none") instead of "currency" as stored in the JSON: 

![Screenshot 2023-10-05 114355](https://github.com/surveyjs/survey-creator/assets/126170045/26efd62a-0a45-42cd-bb42-298304d6b549)

![matrix-inputMask-json](https://github.com/surveyjs/survey-creator/assets/126170045/dc4e19d7-6672-41fa-8410-6cf03da6499b)

Regardless of that buggy behaviour the masking functionality in the Preview still works correctly. Perhaps the mapping of JSON value to the corresponding property does not work for matrixdropdowncolumn yet?

Thanks for your reply.

**Comment by JaneSjs** [comment]
Hello,
I created the following demo for your reference: [View CodeSandbox](https://codesandbox.io/s/still-thunder-7tp93y?file=/src/SurveyCreatorComponent.jsx). If you load a creator, you can see that the specified input mask is correctly applied.

Please let me know if this example helps.

**Comment by ale-x-may** [comment]
Thanks. I realized that I used an older version. Using a newer one solved that problem.

**Comment by ale-x-may** [comment]
Hello,
there is another problem: When changing the inputMask of a column from "currency" to an other inputMask type in the Creator UI, the JSON gets updated correctly, but after clicking around a few times in the GUI and then viewing the inputMask property again, the old value is displayed in the UI ("currency") instead of the updated one (as in the JSON).

Thanks in advance.

**Comment by ale-x-may** [comment]
Hello, 
now I encountered another problem: changing inputMask of Column 1, e.g. from "currency" to "datetime", leads to correctly updating the JSON but when afterwards clicking a few times around in the UI and then looking at the inputMask field in the Creator again, the old value is displayed ("currency") instead of the new one ("datetime"), although the JSON still holds the correct value ("inputMask": "datetime") and the bahavior in the Preview is also as expected. This also applies to your created demo.

I'm looking forward to your reply.

**Comment by JaneSjs** [comment]
Hello @ale-x-may,
Thank you for reporting this issue. I reproduced it on a CodeSandbox I recently shared. We will investigate this issue and update you as soon as we get any news to share.

https://github.com/surveyjs/survey-creator/assets/22372972/bb477059-3025-4af4-959a-6157cd2047cc


Thanks

**Comment by andrewtelnov** [comment]
@ale-x-may [This commit](https://github.com/surveyjs/custom-widgets/commit/ce6efe75c54e04d9a4e8307e973be4ad35491858) fix this issue. Properties are shown in the column object and not in the column list.

Thank you,
Andrew
