### ISSUE TITLE
UI Support to Edit Survey Background Settings

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4743]
A survey comes with its individual background settings, including [backgroundImage](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#backgroundImage) and [backgroundOpacity](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model). However, the Survey Creator currently lacks an option for modifying these survey background settings.

A survey has individual background settings: [backgroundImage](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#backgroundImage) and [backgroundOpacity](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model). However, a survey cretor doesn't currently have an option to modify these survey background settings.

Pleae introduce an option that allows users to edit survey background settings within the Survey Creator.
***
Additional Considerations:
Background settings are also accessible through the Theme Editor:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/5135849f-563b-4f90-b399-d5ef15f4e92e)

This implies that background settings may be defined within a theme that is currently applied to a survey. It's important to note that theme background settings take precedence over a survey's background settings. 

Nevertheless, it is necessary to provide users with the option to edit a survey's background settings.

**Comment by tsv2013** [comment]
Survey backgroungd image will be edited by means of theme builder.
