### ISSUE TITLE
How set 'title' of a custom property on Angular

### ISSUE THREAD

**Issue by GleytonLima** [surveyjs/survey-creator#482]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question

### What is the current behavior?

I'm trying to follow the example available at https://surveyjs.io/Examples/Builder/?id=questioneditor&theme=bootstrap but using Typescript and Angular. But the ISurveyQuestionEditorDefinition interface
 which is in /src/questionEditors/questionEditorDefinition.ts, accepts only three attributes ({name: string; category ?: string; tab ?: string}). Should not it have a "title" property in the properties of this interface?

### What is the expected behavior?

How do I set the 'title' of the custom property of an question in angular with typescript?

### How would you reproduce the current behavior (if this is a bug)?

n/a

### Specify your

* browser: chrome
* editor version: "surveyjs-editor": "^1.0.75"

**Comment by andrewtelnov** [comment]
@GleytonLima We do not have title here. Please use our localization mechanizm. Here is [some docs](https://surveyjs.io/Documentation/Builder/#localization) and here is the code:
```
// get the current locale strings object
var curStrings = SurveyEditor.editorLocalization.getLocale("");
//change the text for visible property in Property Grid
curStrings.p.visible = "Is visible";
//change the text for visible property in Modal Editor
curStrings.pe.visible = "Is element visible?";
//change the text for visible property in Modal Editor
curStrings.ed.jsonEditor = "Edit As Text";
```

Thank you,
Andrew

**Comment by GleytonLima** [comment]
@andrewtelnov exactly. But in the example of how customize question editor there is the follow:

```
//Add a tag property to all questions
Survey
    .JsonObject
    .metaData
    .addProperty("question", "tag");
// Change the order of name and title properties, remove the startWithNewLine property and add a tag property
SurveyEditor
    .SurveyQuestionEditorDefinition
    .definition["question"]
    .properties = [
        "title",
        "name", {
            name: "tag",
            title: "Tag"
        }, {
            name: "visible",
            category: "checks"
        }, {
            name: "isRequired",
            category: "checks"
        }
    ];
```
See the 'title' property there? It's works on the plnkr. But on angular i got the following message:

```
Type '{ "name": string; title: string; }' is not assignable to type 'string | { name: string; category?: string; tab?: string; }'.
```

**Comment by GleytonLima** [comment]
I closed the issue by accident, sorry.

**Comment by andrewtelnov** [comment]
@GleytonLima We support title attribute since some time ago. If you use the latest version, you will be fine.

Thank you,
Andrew
