### ISSUE TITLE
[Bug] Page craches when Logic for dynamic panel question configured in Survey Creator

### ISSUE THREAD

**Issue by YaroslavHapon** [surveyjs/survey-creator#4824]
### Are you requesting a feature, reporting a bug or ask a question?
I would like to report a bug

### What is the current behavior?
In the Survey Creator - Logic tab we want to set some logic
When we want to set the answer for a dynamic panel based on a dynamic panel question value,  app crashes

With such an error, here is the stack trace of the error

```tsx
TypeError
Cannot read properties of undefined (reading 'copyObject')
copyObject
https://vl4c2q.csb.app/node_modules/survey-creator-core/survey-creator-core.js:38703:18
copyCssClasses
https://vl4c2q.csb.app/node_modules/survey-creator-core/survey-creator-core.js:38715:9
assignDefaultV2Classes
https://vl4c2q.csb.app/node_modules/survey-creator-core/survey-creator-core.js:38720:5
```

### What is the expected behavior?
The page should not crash and the answer should be set to dynamic panel

### How would you reproduce the current behavior (if this is a bug)?
I tried to set the dynamic panel answer based on the dynamic panel question value in Survey Creator - Logic tab
Here is the video

https://github.com/surveyjs/survey-creator/assets/10761657/9318351b-eed6-43fa-926a-9204ace57f0f

#### Provide the test code and the tested page URL

Tested page URL:
[https://codesandbox.io/s/interesting-night-vl4c2q](https://codesandbox.io/s/interesting-night-vl4c2q)

### Specify your
* browser: Chrome
* editor version: Survey Creator 1.9.114

**Comment by YaroslavHapon** [comment]
Hello @andrewtelnov 

We don't want to implement anything special. The main issue is that the app can crash while setting logic for the surveys
That might confuse users and lead to a bad user experience

Could you provide a rough estimate of when that bug fix can be implemented?

Thank you,
Yaroslav

**Comment by andrewtelnov** [comment]
@YaroslavHapon Got it. We will try to fix it before releasing next version. We release weekly.

Thank you,
Andrew

**Comment by YaroslavHapon** [comment]
Thank you for the information! Have a good day!

**Comment by andrewtelnov** [comment]
@YaroslavHapon The PR above is green and it will be merged into master likely on Monday.

Thank you,
Andrew
