### ISSUE TITLE
Custom New Tool for Survey

### ISSUE THREAD

**Issue by msyler** [surveyjs/survey-creator#483]
### Are you requesting a feature, reporting a bug or ask a question?
Question, about creating a new custom tool in the toolbox.

### What is the current behavior?
I need to develop a new tool that does not exist

### What is the expected behavior?
I need to develop a new brand type of question for my survey.

This is, show an image of a human body, and select a joint (elbow, knee or neck) licking on it, and register the results as an answer for my survey:

Is this possible? 
Where should I start to build this new type of question?

I am using the 1.0.73 version of the Editor

Thanks in advance.

**Comment by andrewtelnov** [comment]
@msyler If you find the javascript widget that does what you need. You may intergrate it into our Survey.
Here is the [custom widget repo](https://github.com/surveyjs/widgets).
You will find the example of adding a new javascript widget in the end of the readme file.

Thank you,
Andrew

**Comment by msyler** [comment]
Sorry for the further question, I failed to find an example of the implementation of custom widgets with angular 2+, anyone could guide me to an example? 

And thanks for the quick response for my initial question!

**Comment by andrewtelnov** [comment]
@msyler I would recomend you to look for a jQuery or vanila widget. There is more chances to find them. It will be easy to intergrate them into our custom widget, because we were making them independent from angular, react, knockout or vue frameworks.

Thank you,
Andrew
