### ISSUE TITLE
Introduce an option to prevent logic rules from being removed on removing linked questions

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4839]
User Issue: T15308 - Related questions logic issue
https://surveyjs.answerdesk.io/internal/ticket/details/T15308
***
Currently, when a question is included in a logic rule, that logic rule is removed when the corresponding question is removed. A usage scenario requires preserving a logic rule regardless of whether or not a linked question has been removed.

**Comment by andrewtelnov** [comment]
Implemented in [this issue](https://github.com/surveyjs/survey-creator/issues/4851).

Thank you,
Andrew
