### ISSUE TITLE
Can't edit new fields in ranking question

### ISSUE THREAD

**Issue by kreanx** [surveyjs/survey-creator#4843]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
In a question with the "ranking" type, after adding a certain number of questions, the next added questions cannot be edited; the contenteditable property is set to false on them. The problem is solved if you re-enter the edit tab.
![image](https://github.com/surveyjs/survey-creator/assets/50743514/f37f4fec-6b0a-4eb4-99b1-59cc3284e6ff)
![image](https://github.com/surveyjs/survey-creator/assets/50743514/2dddd913-f97c-490f-93d1-7ea6e9f19c67)

### What is the expected behavior?
Contenteditable will always be true when creating a new question

### How would you reproduce the current behavior (if this is a bug)?
Create a question with the ranking type, start adding fields, check that they can all be edited.

### Specify your

* browser: google 118.0.5993.118
* editor version: 1.9.114

**Comment by JaneSjs** [comment]
Hello @kreanx,
I tried to reproduce the issue using our [Online Creator Demo](https://surveyjs.io/create-free-survey) (v1.9.115). However, I got no problem editing Ranking questions items. Please refer to my screencast:

https://github.com/surveyjs/survey-creator/assets/22372972/cfdc2616-71f4-4451-a16d-a1fed0232eca

Would you please clarify your JavaScript platform and share a screencast/exact steps to reproduce the problem? Also, please upgrade to the latest SurveyJS version (v1.9.115).

I look forward to your reply.

**Comment by JaneSjs** [comment]
Hello,
We fixed this issue: https://github.com/surveyjs/survey-creator/issues/4856.

The fix will be available with the next maintenance update this week.

Thanks
