### ISSUE TITLE
Unable to set a custom name

### ISSUE THREAD

**Issue by sudiptochoudhury** [surveyjs/survey-creator#485]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Unable to set a custom name to a question.

### What is the expected behavior?
Ability to set custom names for questions.

### How would you reproduce the current behavior (if this is a bug)?
1. Go to https://surveyjs.io/Survey/Builder/
2. Add a question (e.g., Single Input)
3.  Edit the question
4. The value for "Name" field is shown as "question1". Change it to "first_name"
5. Click ok
6. Edit the question again
7. The value for "Name" field still shows  "question1" instead of "first_name"

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Survey/Builder/

### Specify your

* browser: Google Chrome 72.0.3626.121 (Official Build) (64-bit) Windows 10 
* editor version:1.0.75

**Comment by andrewtelnov** [comment]
@sudiptochoudhury If you are changing the question.name in question directly, via in-place editing (using our adorners), then you are changing the question.title.
I have just tried to change question name via property grid and question editor, it works as expected.

Thank you,
Andrew

**Comment by tsv2013** [comment]
You can set [inplaceEditForValues](the https://surveyjs.io/Documentation/Builder/?id=surveyeditor#inplaceEditForValues) editor property in the `true` to turn on inplace editing for values.

**Comment by sudiptochoudhury** [comment]
@andrewtelnov. I am not sure but I am not trying to change the title. I will come to later on whether question.title or question.name. That concern is secondary for now. The main concern is "the change is not saving". The popup in the user interface that comes up when I click edit button shows a field whose label is shown as "Name". There is another field in that popup, whose label is shown as "Title". So, I think if the UI is not badly conceived, then it's pretty clear from the user interface labels, that one refers to "Name" and another refers to "Title". 
Let's forget about all these names. Issue is simpler. Here are the steps to reproduce in images:

![image](https://user-images.githubusercontent.com/809353/54842123-0a014800-4cf7-11e9-826b-66a1f34bf37f.png)
![image](https://user-images.githubusercontent.com/809353/54842132-12598300-4cf7-11e9-9261-1b420a7b1364.png)
![image](https://user-images.githubusercontent.com/809353/54842136-15ed0a00-4cf7-11e9-8931-7abc10f3c5d7.png)
![image](https://user-images.githubusercontent.com/809353/54842141-1a192780-4cf7-11e9-8491-d5799d359b02.png)
![image](https://user-images.githubusercontent.com/809353/54842144-1e454500-4cf7-11e9-9664-46bafe79e024.png)

**Comment by sudiptochoudhury** [comment]
@tsv2013 The current issue is not about editing in-place, nor about which variable stores it. I want to change value via the Edit popup and the value is not getting stored.

**Comment by andrewtelnov** [comment]
@sudiptochoudhury I have tried it with several browsers and it works fine in all of them.
Probably something wrong with local storage in your browser.
Could you please try [this example](https://plnkr.co/edit/V5DzQjEj8nuVHUpOSB12?p=preview)?

Thank you,
Andrew

**Comment by sudiptochoudhury** [comment]
@andrewtelnov The example you have just provided works correctly in the same browser.

**Comment by andrewtelnov** [comment]
@sudiptochoudhury It means that somehow the localstorage doesn't work correctly on your browser and it rollbacks the changes. I have no idea why. I am seeing this for the first time.
Could you please try to create a survey in our Service area (it is completely free, but you would have to register). It stores Survey JSON in azure database instead of local storage.


Thank you,
Andrew

**Comment by sudiptochoudhury** [comment]
@andrewtelnov You may be right. But I in my own implementation I am not using local storage or can not find any thing in the local storage. Not sure if SurveyJS automatically uses LocalStorage or not.
However, I did one more investigation. I tried `onPropertyValueChanging` event listener and in your example whenever I change the `name` it get this even triggered. But not triggering in my implementation. It is triggering for other items like for "is required" or "is visible" settings.

I need to mention one thing, my implementation uses

    ` editor = new SurveyEditor.SurveyEditor(null);`

and then render after defining event listeners:

    `editor.render("editorElement", editorOptions);`

Can it make the difference?

**Comment by andrewtelnov** [comment]
@sudiptochoudhury We use localstorage on our [web page](https://surveyjs.io/builder) and do not use it in our libraries.
It means that the problem in you code onPropertyValueChanging. This event allows to discard changes, for example. You may show your code on this event then.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@sudiptochoudhury As for your question. Here is the [updated plunker](https://plnkr.co/edit/V5DzQjEj8nuVHUpOSB12?p=preview) with render function.
You may try to recreate the problem in the plunker so we will be able to find out the reason of this behavior.

Thank you,
Andrew
