### ISSUE TITLE
Image Picker: When an image cannot fit the edit and delete icons, its apperance in the Designer tab becomes confusing

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#4862]
![image](https://github.com/surveyjs/survey-creator/assets/18551316/d9dffae2-ae50-41a2-b105-e3a3a28beb03)

Steps to reproduce:

1. Open the [Order Form](https://surveyjs.io/form-library/examples/order-form-template-free/) demo.
2. Click Edit in Survey Creator.

**Comment by mikeamelin** [comment]
Content width is wider than a question width.
![Cars](https://github.com/surveyjs/survey-creator/assets/17025812/fc97da66-7011-4c8e-be8e-af8f519a0a26)
![Flight](https://github.com/surveyjs/survey-creator/assets/17025812/b919a827-6f3c-49ea-909a-cea6416fd05b)
![Order 1](https://github.com/surveyjs/survey-creator/assets/17025812/2b720ca8-3a85-4bf5-9d7f-6d66536b8e92)
![Order 2](https://github.com/surveyjs/survey-creator/assets/17025812/b27b7b1f-3a41-45e5-a49f-4c651906c140)
![Patient 3](https://github.com/surveyjs/survey-creator/assets/17025812/a81a4fea-3f4c-42a8-9793-4baaa7efc789)

Text adaptivity
![Order 3](https://github.com/surveyjs/survey-creator/assets/17025812/c002f225-e667-43b1-937f-5f7e038d7ec0)
![Pets](https://github.com/surveyjs/survey-creator/assets/17025812/2422a369-c919-4b33-a831-60f056e7ad40)

Panel adaptivity
![Patient 1](https://github.com/surveyjs/survey-creator/assets/17025812/72cd5aa1-0332-4498-9b5c-26bfd80c587d)
![Patient 4](https://github.com/surveyjs/survey-creator/assets/17025812/c93a90ee-e5bd-415b-81e3-aabc1d9d4e82)
![Screenshot 2023-11-25 at 15 36 18](https://github.com/surveyjs/survey-creator/assets/17025812/5e24a008-beb6-48a6-947a-455854a4ff39)

Misc
![Restaurant](https://github.com/surveyjs/survey-creator/assets/17025812/b6058db0-cc48-4dc7-accf-2df2c8998c85)
![Sales](https://github.com/surveyjs/survey-creator/assets/17025812/e63f5689-722d-4a86-8cc9-5511ab39bf30)
![Patient 2](https://github.com/surveyjs/survey-creator/assets/17025812/06919d20-099c-4ebb-90c3-f7cf139f7920)

**Comment by mikeamelin** [comment]
Panels — https://www.figma.com/file/SSMZUWJve1zuMSeA5E5YpA/Creator-Preview?type=design&node-id=1827-51354&mode=design
