### ISSUE TITLE
Image Picker - The creator.onOpenFileChooser function arguments contain no information about the corresponding Image Picker item

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4868]
T15318 - Create a new option in the ImagePicker item
https://surveyjs.answerdesk.io/internal/ticket/details/T15318
***
The `creator.onOpenFileChooser` function doesn't contain any information about an Image Picker item for which the file dialog is being activated ([View CodeSandbox](https://codesandbox.io/s/silly-keller-fcm796?file=/src/SurveyCreatorComponent.jsx:602-603)).

Please consider adding the information about the clicked item to make it available within the `creator.onOpenFileChooser` function.

**Comment by JaneSjs** [comment]
**Usage scenario** 
When a user interacts with the image picker, they should be able to open a modal displaying all the images they've previously uploaded, select one of those images, and set it as a choice in the image picker for the survey. It is necessary to obtain additional information about the item being clicked to configure your page and associate the selected image with that specific item.

**Comment by tsv2013** [comment]
How the onOpenFileChooser event is passing additional context parameter:
```
context?: { question: Question; item?: ItemValue }
```
If context a survey: logo, background image etc then context is empty
