### ISSUE TITLE
Setting an overriding property on the survey logo property doesn't disable the logo upload in the editor

### ISSUE THREAD

**Issue by chamgda** [surveyjs/survey-creator#4881]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Setting an overriding property on the survey logo property doesn't disable the logo upload in the editor

### What is the expected behavior?
Setting an overriding property on the survey logo property disables the logo upload in the editor

### How would you reproduce the current behavior (if this is a bug)?
Add a property to the survey that overrides the logo property (see example linked below)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
https://codesandbox.io/s/surveyjs-angular-forked-n7c5qg

### Specify your

* browser: chrome 119.0.6045.124
* editor version: 1.9.114

**Comment by JaneSjs** [comment]
Hello @chamgda,
Thank you for sharing a demo. I will forward this issue to the team for further investigation. Please look forward to our updates.
