### ISSUE TITLE
`visibleIf` wizard produces incorrect logic string for `QuestionSelectBase` "other" values

### ISSUE THREAD

**Issue by ChopinDavid** [surveyjs/survey-creator#4884]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug.

### What is the current behavior?
Attempting to add a condition that checks the value of a QuestionSelectBase"other" value through the logic wizard creates an incorrect logic string.

For example, imagine you have 2 questions: questionA (a checkbox) and questionB (a text input). If you want to have questionB only visible if questionA's "other" value is selected and set to `"foo"`, you are unable to create this logic string correctly through the logic wizard and instead have to type it out manually.

The logic wizard (incorrectly) creates a logic string that looks like `"visibleIf": "{questionA} = ['foo']"`.

We see something similar with radio groups and drop-downs. The logic wizard creates logic that looks like `"visibleIf": "{questionA} = 'foo'"` on radio groups and drop-downs.

So elements that have a `visibleIf` condition dependent on the "other" value of `QuestionSelectBase` will never appear to the user if the aforementioned logic was added using the logic wizard.

### What is the expected behavior?
The correct logic string for checkboxes would be: `"visibleIf": "{questionA} = ['other'] and {questionA-Comment} = 'foo'"`.

The radio group and dropdown element types support only one answer rather than the list of answers that checkbox supports, so the logic string for this behavior would be `"visibleIf": "{questionA} = 'other' and {questionA-Comment} = 'foo'"`.

So elements that have a `visibleIf` condition dependent on the "other" value of `QuestionSelectBase` do appear to the user if the aforementioned logic was added using the logic wizard.

### How would you reproduce the current behavior (if this is a bug)?
https://github.com/surveyjs/survey-creator/assets/27712906/63cc3729-5563-4409-951d-910e2e68e8f2

### Specify your

* browser:
Safari/Chrome
* editor version:
?

**Comment by JaneSjs** [comment]
Hello @ChopinDavid,
Thank you for reporting this issue. I forwarded it to our developers for further research. 

Please look forward to our updates.

**Comment by andrewtelnov** [comment]
@ChopinDavid I agree that we have an issue with your scenario. How do you want to handle it? I think that we need to check for "other" value only, "{question1} = 'other'" for radiogroup and ignore "foo" at all. I doubt that somebody will need to check that a user enter the exact text into comment.

Thank you,
Andrew

**Comment by ChopinDavid** [comment]
@andrewtelnov I agree that it is a very edge case that somebody would have to check the user's exact text, but it is conceivable.

In my mind, it makes sense that checkboxes would generate something like `{question1} = ['other'] and {question1-Comment} = 'foo'`, while all other select base elements that do not support multiple values (dropdowns, radio groups, etc.) would generate something like `{question1} = 'other' and {question1-Comment} = 'foo'`. Let me know if this makes sense to you.

I was hoping to make a PR for this as it seems like it would be a quick fix, but haven't had time to since it is low priority for the team. I was more opening this issue in order to document it in case the problem is more relevant for somebody else.

Thanks!

**Comment by andrewtelnov** [comment]
@ChopinDavid Unfortunately, it is not that easy.
There are two ways of storing comments inside the select base question. It can be as you described or you can set [survey.storeOthersAsComment](https://surveyjs.io/form-library/documentation/api-reference/survey-data-model#storeOthersAsComment) = false; and the other value will be stored in the question value dirrectly: `question1: "foo"` or `question1: ["item1", "foo"]`.
For the second scenario, the current approach will work as expected.
For the general scenario, I would show "Other" without a comment area. In this case, we will serialize/deserialize in the expression the "other" value only. since checks as "{question1} = `other`" or "{question1} contains `other`" makes more sence to me. I can see real life scenarios for these expressions.
The following expressions: "{question1} = `other` and {question1-Comment} = 'foo'" doesn't make sense to me and you can always convert it into "{question1-Comment} = 'foo'" anyway.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Forgot to ask your opinion on this issue.

Thank you,
Andrew

**Comment by ChopinDavid** [comment]
@andrewtelnov So, it sounds like the generated logic string should technically change depending upon the value of the respective Survey's `storeOthersAsComment`? Is there a way for the wizard to know what this value is? It seems that the wizard currently assumes that `storeOthersAsComment` is always `false`, in which case there is never a `question1-Comment`.

If the wizard **is** capable of knowing the respective Survey's `storeOthersAsComment`, I would think the generated logic string would behave as follows:

- Element is checkbox and `storeOthersAsComment == false`: `{question1} = ['foo']`
- Element is not checkbox and `storeOthersAsComment == false`: `{question1} = 'foo'`
- Element is checkbox and `storeOthersAsComment == true`: `{question1} = ['other'] and {question1-Comment} = 'foo'`
- Element is not checkbox and `storeOthersAsComment == true`: `{question1} = 'other' and {question1-Comment} = 'foo'`

If the wizard **is not** capable of knowing the respective Survey's `storeOthersAsComment`, we might need to add a toggle to the wizard to generate the logic string as if `storeOthersAsComment == true`.

Does this sound right to you?

**Comment by ChopinDavid** [comment]
It is also worth noting that I am not yet considering behavior when "contains" is selected from the logic wizard. I am only considering when we have the element value equal `'other'` or `['other']`, exactly as displayed in the original video. There might be other considerations to be had if we want to support "contains" conditions in addition to "equals" conditions.

**Comment by andrewtelnov** [comment]
@ChopinDavid Wizard (Creator) knows about everything in SurveyJS Model and of course we can have a different behavior.
I am thinking having the behavior we have now if `storeOthersAsComment == false`
* Element is checkbox and storeOthersAsComment == false: {question1} = ['foo']
* Element is not checkbox and storeOthersAsComment == false: {question1} = 'foo'

However, for if `storeOthersAsComment == true`, then we will have not show comment area on choosing "other" and we will have the following:
Element is checkbox and storeOthersAsComment == true: {question1} = ['other']
Element is not checkbox and storeOthersAsComment == true: {question1} = 'other'

It makes sense for me and I think we are going to work on it in next weekly sprint that will start today.

Thank you,
Andrew

**Comment by ChopinDavid** [comment]
@andrewtelnov Awesome, thank you for prioritizing this! I agree that the behavior is the same when `storeOthersAsComment == false`, but is there a reason we wouldn't want to do the following?:
Element is checkbox and storeOthersAsComment == true: `{question1} = ['other'] and {question1-Comment} = 'foo'`
Element is not checkbox and storeOthersAsComment == true: `{question1} = 'other' and {question1-Comment} = 'foo'`

This way, the behavior is correct if we encounter the edge case of a survey creator actually wanting to add a condition **not only** on the fact that other was selected, **but also** on what the actual `other` value is, namely "foo"?

**Comment by andrewtelnov** [comment]
@ChopinDavid I have updated the unit test with 'storeOthersAsComment: false' and I think the current unit test covers all cases. 

Thank you,
Andrew
