### ISSUE TITLE
The creator.onDragDropAllow function description - Validate function arguments description

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4885]
Please run the demo shared in the following thread: 
T15492 - Dynamic Panels Being Treated as Panels in OnDragDropAllow
https://surveyjs.answerdesk.io/internal/ticket/details/T15492

Try to drag a Checkbox element and drop it within the Dynamic Panel element.

The options.source is the Checkbox - the element being dragged.
The options.target is a Panel - the element to which the source element is dragged.

However, according to [the API description](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onDragDropAllow), the options.target is not a drop target element, but the source dragged element.

* options.target: IElement
A survey element being dragged.
* options.source: IElement
A survey element from which target is being dragged. This parameter is null if target is being dragged from the [Toolbox](https://surveyjs.io/survey-creator/documentation/toolbox).

Please validate this.

**Comment by RomanTsukanov** [comment]
Waiting for https://github.com/surveyjs/survey-library/issues/7336
