### ISSUE TITLE
Add an option to expand and collapse panels on a design surface

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4895]
When building large forms, it may be required to organize questions within collapsible panels. To enhance user experience while creating forms in a form builder, it was suggested to have an option to collapse and expand panels in the design tab.

T15566 - Possibility to collapse/expand panels in SurveyCreator
https://surveyjs.answerdesk.io/internal/ticket/details/T15566

**Comment by JaneSjs** [comment]
+ 1

T15576 - Collapse panels in design view
https://surveyjs.answerdesk.io/internal/ticket/details/T15576

**Comment by mikeamelin** [comment]
Prototype — https://www.figma.com/file/SSMZUWJve1zuMSeA5E5YpA/Creator-Preview?type=design&node-id=1740-75273&mode=design

**Comment by JaneSjs** [comment]
T18718 - Re: Possibility to collapse/expand panels in SurveyCreator
https://surveyjs.answerdesk.io/internal/ticket/details/T18718
