### ISSUE TITLE
onOpenFileChooser not triggered

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#4915]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
The `onOpenFileChooser` event is not properly triggered when configuring an image question, if no image is configured yet.

### What is the expected behavior?
The event should for all ways the creator opens a file picker.

### How would you reproduce the current behavior (if this is a bug)?
- Go the link below
- Try setting another image for the first question, note you get a standard JS alert: **file chooser**
- Try setting an image on the second question, note you get the standard file picker dialog <<< BUG

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/p/sandbox/focused-sea-3p8cff

Test code

```
{
  elements: [
    {
      type: "image",
      name: "question1",
      description: "Clicking the icon in the top right works correctly",
      imageLink:
        "https://surveyjs.io/Content/Images/examples/image-picker/lion.jpg",
    },
    {
      type: "image",
      name: "question1",
    },
  ],
}

```

### Specify your

* browser: N/A
* editor version: latest

**Comment by JaneSjs** [comment]
The issue was fixed and no longer reproduced: https://github.com/surveyjs/survey-creator/issues/5124.

@SamMousa: for quicker responses, please feel free to contact us via [Help Desk](https://surveyjs.io/support).
