### ISSUE TITLE
Localized Survey Creator - The survey doesn't contain visible pages - The message appears is translated in design mode but untranslated in preview

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4923]
User Issue: T15707 - Missing localization for Preview tab text - no pages or questions
https://surveyjs.answerdesk.io/internal/ticket/details/T15707
***
When a survey is empty, it should use the same locale as it is defined for a Survey Creator. Otherwise, the 'a survey is empty' message appears untranslated:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/42860872-ffae-4c22-a2b3-156dc75c18dd)

**Comment by JaneSjs** [comment]
This message is defined within a Form Library localization: [emptySurvey](https://github.com/surveyjs/survey-library/blob/master/src/localization/english.ts#L19C3-L19C14). When a survey creator appears at design time, an empty survey content follows a survey creator localization and translates the empty survey message. However, when a user switches to the preview mode, a survey uses its own `locale` property value. 

You can handle a preview survey creation using the `creator.onSurveyInstanceCreated` event. If a survey is empty, change it's `locale` to the currently used creator locale.
```js
creator.locale = "fr";
creator.onSurveyInstanceCreated.add((sender, options) => {
    if (options.reason === "test" && options.survey.isEmpty) {
      options.survey.locale = creator.locale;
    }
});
```
[View CodeSandbox](https://codesandbox.io/p/sandbox/nostalgic-kilby-5hjs45?file=%2Fsrc%2FSurveyCreatorComponent.jsx%3A18%2C30&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpe0gyta0007356ijpzf4nhe%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpe0gyt90003356id19jfqf5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpe0gyt90004356iberomvrv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpe0gyt90006356iq89zjtx2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpe0gyt90003356id19jfqf5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpe0gyt90002356i9v5ezmgs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clpe0u90j0003356hyoyys23w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A18%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A18%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FSurveyCreatorComponent.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clpe0gyt90003356id19jfqf5%2522%252C%2522activeTabId%2522%253A%2522clpe0u90j0003356hyoyys23w%2522%257D%252C%2522clpe0gyt90006356iq89zjtx2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpe0gyt90005356iu08wkj56%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpe0gyt90006356iq89zjtx2%2522%252C%2522activeTabId%2522%253A%2522clpe0gyt90005356iu08wkj56%2522%257D%252C%2522clpe0gyt90004356iberomvrv%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpe0gyt90004356iberomvrv%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by andrewtelnov** [comment]
@JaneSjs Yes, the user should set the survey locale to the needed locale.

Thank you,
Andrew
