### ISSUE TITLE
Property Grid - Introduce an option to override the Empty Survey text for a property grid survey instance

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4932]
User Issue: T15752 - Hide empty property grid placeholder.
https://surveyjs.answerdesk.io/internal/ticket/details/T15752
***

The task is to modify the empty survey text which appears within an empty Property Grid. 
![image](https://github.com/surveyjs/survey-creator/assets/22372972/ea5307cd-6c94-432e-a40b-3713b03c2340)

Unfortunately, there is no option to directly modify the `emptySurveyText` property as it is read-only. The Empty Survey text is defined within a localization meaning that there is no option to override this text for a specific survey instance. Otherwise, I would do it like that:
```
 creator.onPropertyGridSurveyCreated.add((s, o) => {
    o.survey.emptySurveyText = "No settings";
});
```
Please consider an option to override the empty survey text at the level of a survey object.

**Comment by andrewtelnov** [comment]
@JaneSjs "survey.emptySurveyText" is writable now.

Thank you,
Andrew
