### ISSUE TITLE
Introduce "set" Property Editor for selecting several values from array

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#494]
Create a new type of property Editor that will allow to choose several items from the array.
Here is the example of property:
```
      Survey.JsonObject.metaData.addProperty("question", {
        name: "tagbox:set",
        choices: [1, 2, 3, 4, 5]
      });
```

The property Editor should allow to select several values, so it may have value as []/empty or [1, 3, 5]

**Comment by intellioption** [comment]
what version do i need to change it to in my package.json to get these changes. Please let me know.

**Comment by andrewtelnov** [comment]
@intellioption We have not released it yet. We will release it on the next week, mostly likely Tuesday-Wednesday. 
You may review [this example](https://plnkr.co/edit/XMcY8u1r2F6c4c9ERxP1?p=preview) with the latest developer sources and give us your feedback, so we will be able to fix/change something before the release.

Thank you,
Andrew

**Comment by hekin1** [comment]
Will it be possible to have a auto complete text field that is ajax fetching suggestions from backend? (if the set is too large to show them all at the same time) Like so:
![demo](https://raw.githubusercontent.com/yairEO/tagify/master/demo.gif)

**Comment by andrewtelnov** [comment]
By default it shows as checkbox with Select All option, but if tagbox class is registered (based on select2), then it will use tagbox.
Here is [the example of tagbox](https://surveyjs.io/Examples/Library/?id=custom-widget-select2-tagbox).

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
In fact, you will be able to override the tagbox custom widget and use your own. The Survey Creator will look for "tagbox" class, if it exists, use it and set the choices property before set the property value.

Thank you,
Andrew

**Comment by hekin1** [comment]
@andrewtelnov Thank you for the example, but I was refering to the survey editor.

**Comment by andrewtelnov** [comment]
@hekin1 I mean that if you add "tagbox" widget into your survey cretor page, it would be used.
And  I actually have the example :). However, it uses not released version yet.
Here is [the example](https://plnkr.co/edit/Xj2gyIOArqaeDtZFg7eN?p=preview).

Thank you,
Andrew

**Comment by hekin1** [comment]
@andrewtelnov Thank you Andrew, but I dont understand how I will be able to provide restful choices from your example.

**Comment by andrewtelnov** [comment]
@hekin1 You may define property as:
```
Survey.JsonObject.metaData.addProperty("question", {
  name: "tagbox:set",
  choices: function() {
      //Your code is here
      return [1, 2, 3, 5]
    }
});
```

Thank you,
Andrew

**Comment by hekin1** [comment]
@andrewtelnov This function is only called once. I need it to be called upon typing, I have too many tags to show them all at once

```
choices: function() {
      //Your code is here
      return [1, 2, 3, 5]
}
```

**Comment by andrewtelnov** [comment]
@hekin1 Then you may use isDynamicChoices property to retrieve choices everytime:

```
Survey.JsonObject.metaData.addProperty("question", {
  name: "tagbox:set",
  isDynamicChoices: true,
  choices: function() {
      //Your code is here
      return [1, 2, 3, 5]
    }
});
```

Thank you,
Andrew

**Comment by intellioption** [comment]
Can I add this in new tab instead of "General" tab? Please let me know.

Thanks


Saurabh Shah
Founder & CEO
IntelliOption LLC
Ph: (248) 565-7445
Fax: (248) 565-7445

**Comment by intellioption** [comment]
I have created new custom tab and I want to add this tagbox to that tab.
Please let me know how can i do that?


Saurabh Shah
Founder & CEO
IntelliOption LLC
Ph: (248) 565-7445
Fax: (248) 565-7445

**Comment by andrewtelnov** [comment]
@intellioption It shows in [this documentation](https://surveyjs.io/Documentation/Builder/?id=Survey-Builder-Overview#elementseditor).

```
//Add a new tab, that doesn't contains properties
editorDefinition.tabs.push({ name: "general_addition", title: "Additional Settings", index: 15 });
//Add three properties into this new tab. If tab is empty, then a property is shown in the first "general" tab.
editorDefinition.properties.push({ name: "otherErrorText", tab: "general_addition" });
editorDefinition.properties.push({ name: "indent", tab: "general_addition" });
editorDefinition.properties.push({ name: "width", tab: "general_addition" });
```

Thank you,
Andrew

**Comment by intellioption** [comment]
I did add the tab and it shows up fine but the question is how to add that
new "tagbox:set" in that tab.

[image: image.png]

As you can see above, I wanted PR Codes tagbox in "PR Codes" tab. Please
let me know.

Saurabh Shah
Founder & CEO
IntelliOption LLC
Ph: (248) 565-7445
Fax: (248) 565-7445

**Comment by andrewtelnov** [comment]
@intellioption Here is [the example](https://plnkr.co/edit/XMcY8u1r2F6c4c9ERxP1?p=preview)

Thank you,
Andrew

**Comment by intellioption** [comment]
Thank you. I got this to work but in your example and in mine, title does
not show up as "Tagbox". Tab title is there but title for that control is
not there.

[image: image.png]

Is there a different way to do that?

Thanks


Saurabh Shah
Founder & CEO
IntelliOption LLC
Ph: (248) 565-7445
Fax: (248) 565-7445

**Comment by andrewtelnov** [comment]
@intellioption If you add one property into this category/tab, then you will see the property title. Right now, it doesn't make sense, since the description for one property is in the tab. Let us know if it is not a case for you.

Thank you,
Andrew

**Comment by intellioption** [comment]
Hi there,

I could change lot of stylesheets but I am trying to figure out how to
change stylesheet for Panel and Inside Panel and so on. Can you please let
me know how to do that? Also within panel I want to have alternate
background color for each question. Can i do that? how?

[image: image.png]

Thank you.


Saurabh Shah
Founder & CEO
IntelliOption LLC
Ph: (248) 565-7445
Fax: (248) 565-7445
