### ISSUE TITLE
Change question menu incorrect for custom question type.

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#4940]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
I'm adding a question from a template (so the intention is for the end user to be able to customize it), the change menu shows 2 items highlighted. This seems to be incorrect.

### What is the expected behavior?
The change menu should not show duplicate entries.

### How would you reproduce the current behavior (if this is a bug)?
- Click the example link below
- Add a question of type `Country`
- Try changing the type via the adorner button

![image](https://github.com/surveyjs/survey-creator/assets/547021/2e939135-eb87-4969-8192-fb56cec64564)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  https://codesandbox.io/p/sandbox/mystifying-chaum-tlf79d

```
creator.toolbox.addItem({
  // A unique name; must use lowercase
  name: "country",
  // A display name used in the Toolbox
  title: "Country",
  // A JSON schema for the base question type (Dropdown in this case)
  json: {
    type: "dropdown",
    placeholder: "Select a country...",
    choicesByUrl: {
      url: "https://surveyjs.io/api/CountriesExample",
    },
  },
});
```

### Specify your

* browser: Ungoogled Chromium latest
* editor version: latest

**Comment by chancesmith** [comment]
I see the same thing on my end.
[https://codesandbox.io/p/sandbox/survey-js-custom-image-picker-ljglq3](https://codesandbox.io/p/sandbox/survey-js-custom-image-picker-ljglq3?file=%2Fsrc%2FSurveyCreatorComponent.jsx%3A45%2C5)

**Comment by JaneSjs** [comment]
Hi Everyone,
Thank you for reporting this issue. I forwarded it to our developers for further research.

Please stay tuned.
