### ISSUE TITLE
Trying to add tags to a question where tags are fetched from backend with ajax

### ISSUE THREAD

**Issue by hekin1** [surveyjs/survey-creator#495]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
I am trying to add "tags" property to a question in surveyjs editor/builder/creator. I am using the tagify widget from yaireo (yaireo/tagify). The idea is that tags are fetched from backend with ajax showing auto complete options to the user that is creating the survey.
However, there are some problems that occur.
1. When adding tags through the modal question editor, sometimes multiple tagify components occur:

![questiontags](https://user-images.githubusercontent.com/14329635/55721983-298db580-5a05-11e9-9f69-6adb5f61f5a8.png)

2. Tags on the right toolbar (property editor) doesnt sync with tags in the modal question editor. If I add tags in the modal editor, they dont appear in the right property toolbar:
![not_synced](https://user-images.githubusercontent.com/14329635/55722362-5abab580-5a06-11e9-959c-3b02b325562c.png)

### What is the expected behavior?
To be able to add tags to questions in survey builder , tags should be fetched from backend

### How would you reproduce the current behavior (if this is a bug)?
You can test my code at the provided sandbox.

#### Provide the test code and the tested page URL (if applicable)
https://codesandbox.io/s/4q39pn3rw

Tested page URL:

Test code

```
    SurveyKo.JsonObject.metaData.addProperty("question", {
        name: "questionTags",
        type: "tags",
        isRequired: true
    });

    var TagsEditor = {
      render: function (editor, htmlElement) {
        var input = document.createElement("input");
        input.type = "text";
        htmlElement.appendChild(input);


        input.value = editor.koValue() || "";
        var tagify = new Tagify(input, {whitelist:[]})

        editor.onValueUpdated = function (newValue) {
            input.value = editor.koValue() || "";
            if(editor.koValue())
                tagify.value = JSON.parse(editor.koValue());
        }

        // listen to any keystrokes which modify tagify's input
        tagify.on('input', function onInput( e ) {
            tagify.settings.whitelist.length = 0; // reset the whitelist

            //This is where I fetch tags from backend, faking it for now            
            tagify.settings.whitelist = ["abc", "def", "ghi", "jkl", "mno"];
            tagify.dropdown.show.call(tagify, e.detail); // render the suggestions dropdown
            
        })
        tagify.on('add', function(e, tagName){
                editor.koValue(JSON.stringify(tagify.value))
        });
        tagify.on('remove', function(e, tagName){
                editor.koValue(JSON.stringify(tagify.value))
        });
      }
    };

    SurveyEditor.SurveyPropertyEditorFactory.registerCustomEditor("tags", TagsEditor);
    SurveyEditor.SurveyQuestionEditorDefinition.definition.question.properties.push("questionTags");

```

### Specify your

* browser: FF 66.0.2 (x64)
* editor version: 1.0.74

**Comment by andrewtelnov** [comment]
@hekin1 We will have this functionality out of the box from the next minor update on this week.
Please review [this issue](https://github.com/surveyjs/survey-creator/issues/494).

Thank you,
Andrew
