### ISSUE TITLE
Browser compatibility question

### ISSUE THREAD

**Issue by iwollmann** [surveyjs/survey-creator#497]
### Are you requesting a feature, reporting a bug or ask a question?
Question

I didn't found any information about the supported browsers and versions by the builder. Wich browsers works with him? Wich versions? Last versions only?

**Comment by tsv2013** [comment]
Yes, we need to add supported browsers section on our site.
Chrome, Opera, Firefox, Edge, Safari - latest versions
IE >= 9.0

**Comment by tsv2013** [comment]
@iwollmann I need to admit that there are some issues with IE, that have not been fixed due to fix cost, e.g.  https://surveyjs.answerdesk.io/ticket/details/T1760
