### ISSUE TITLE
Logic tab incorrectly renders custom React questions under "set answer"

### ISSUE THREAD

**Issue by mgoetz-nerdery** [surveyjs/survey-creator#4983]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
Custom React question components render incorrectly when shown under "set answer" on the Logic tab.  See below.
<img width="420" alt="Screenshot 2023-12-13 at 9 12 14 AM" src="https://github.com/surveyjs/survey-creator/assets/32200555/40cc1c53-1974-403e-b9bc-878cb00548a1">

Note that this behavior occurs in the CodeSandbox provided by the SurveyJS documentation for custom question types.

### What is the expected behavior?
The component should have additional padding to the bottom and left to reflect the way it renders in the editor and in preview mode.

### How would you reproduce the current behavior (if this is a bug)?
- Set up a custom question with a React component within a survey
- Create a survey with one question that uses this custom type
- Go to the Logic tab on the editor
- Choose "Set Answer" as the action
- Select the question
- Observe that the question is rendered incorrectly

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/p/sandbox/amazing-rubin-ljwkd9?file=%2Fsrc%2Findex.js

### Specify your

* browser: Chrome 120
* editor version: Latest (1.9.121)

**Comment by andrewtelnov** [comment]
@mgoetz-nerdery Sorry, it took a while. Here is the [updated example](https://codesandbox.io/p/sandbox/amazing-aryabhata-6vp2k5?file=%2Fsrc%2FSurveyCreatorComponent.jsx%3A24%2C1).
You will need to add the following code:
```js
defaultV2Css[CUSTOM_TYPE] = {
  root: "",
};
```

Thank you,
Andrew

**Comment by mgoetz-nerdery** [comment]
Thanks for letting me know!  Would it make sense to update the documentation for custom questions to include this detail?

**Comment by andrewtelnov** [comment]
@mgoetz-nerdery You will not need this work-around for new version we will release shortly.

Thank you,
Andrew

**Comment by mgoetz-nerdery** [comment]
Thanks!  Let me know what the new version number is once it's ready.

**Comment by andrewtelnov** [comment]
@mgoetz-nerdery We have released it several hours ago.

Thank you,
Andrew
