### ISSUE TITLE
Compilation and Installation Issues with TypeScript in survey-creator-core

### ISSUE THREAD

**Issue by natilusky** [surveyjs/survey-creator#5000]
Environment:
Node.js Version: [18.18.2]
TypeScript Version: [4.2.2 (globally installed), 4.2.2 (project's package.json)]
NPM Version: [ 10.2.5]
Operating System: [Windows 11]

**Description:**
I am attempting to contribute to Survey.js by adding support for the Hebrew language. However, I am facing issues with installing dependencies and building the survey-creator-core package, particularly during TypeScript compilation.
My goal is to add Hebrew language support to Survey.js. I have forked the repository and am working on the survey-creator-core package.

**Issue 1: Installation Problem**
During the installation (npm install), I encountered dependency resolution issues, particularly related to TypeScript and Webpack versions. The error message was:
<img width="538" alt="image" src="https://github.com/surveyjs/survey-creator/assets/63637757/53eb0278-ba62-466b-9ade-d77b24d596dc">

I attempted to resolve this by clearing the npm cache, and reinstalling with --legacy-peer-deps.

**Issue 2: Compilation Errors:**
After resolving the installation issues, I ran into multiple TypeScript compilation errors when executing npm run build. The errors are related to properties not existing on certain types and issues importing the survey-core module. Here are some examples of the errors:

<img width="644" alt="image" src="https://github.com/surveyjs/survey-creator/assets/63637757/db9cc6e7-f052-480b-80bf-9bcdba5c6145">

I have ensured the global TypeScript version is aligned with the project's specified version, but the issue persists.

**Steps to Reproduce:**
Clone the Survey.js repository.
Navigate to survey-creator/packages/survey-creator-core.
Run npm install.
Run npm run build.
Expected Behavior:
The project should install dependencies without errors and build successfully, allowing me to proceed with adding Hebrew language support.

**Actual Behavior:**
Encountered dependency conflicts during installation and multiple TypeScript errors during build.

**Additional Context:**
Different Node.js and TypeScript versions were tested to resolve these issues.
The project's tsconfig.json and package.json files are as per the original repository.
Any assistance or guidance on resolving these issues to facilitate the addition of Hebrew language support to Survey.js would be greatly appreciated. Thank you.

**Comment by xiezunjin** [comment]
I had resolved the issue!  The reason of this  issue  is loss "survey-core/themes" , because the code  import * as LibraryThemes from "survey-core/themes" need the module "survey-core/themes", so you must build theme in the survey-core project first. Good Luck!!!

**Comment by JaneSjs** [comment]
A follow-up: To make the `survey-core/themes` build available, navigate to the `survey-library` folder and run the `npm run build_core` command to build the `survey-core/themes` module.
```
npm run build_core
```
