### ISSUE TITLE
React - move React dependencies to peerDependencies

### ISSUE THREAD

**Issue by nicduke38degrees** [surveyjs/survey-creator#5005]
User Issue: T15894 - Survey Creator and Survey Form Compatible with Preact?
https://surveyjs.answerdesk.io/internal/ticket/details/T15894

**Comment by nicduke38degrees** [comment]
https://github.com/surveyjs/survey-creator/pull/5006

**Comment by tsv2013** [comment]
It's a wrong file. This is the correct PR - https://github.com/surveyjs/survey-creator/pull/5007

**Comment by tsv2013** [comment]
@nicduke38degrees  Thank you for the contribution!
