### ISSUE TITLE
easy way to allow the creator to attach files

### ISSUE THREAD

**Issue by truezjz** [surveyjs/survey-creator#5014]
I am new to SurveyJS, is there a easy way to allow the creator to attach files eg. pdf (not image) to any type of the question, and the survey viewer (the person to answer the survey) to see the file download link, the user can click the link to download the file? prefer the file can be stored on the server as raw file.

Thanks in advance.

James

**Comment by andrewtelnov** [comment]
@truezjz Here is [the example](https://codesandbox.io/p/sandbox/unruffled-rain-9tfjpw) that does what you need.

Thank you,
Andrew
