### ISSUE TITLE
Cannot use "OK" and/or "Apply" in question "edit" popup

### ISSUE THREAD

**Issue by lukasmedia** [surveyjs/survey-creator#502]
### Are you requesting a feature, reporting a bug or ask a question?

Bug; i guess

### What is the current behavior?

Start a new questionnaire, drop a comment box inside page1. So far, so good.
Select the comment box en click "edit". Make changes yes/no, doesnt matter.
Press OK or Apply: nothing happens but if i check the console:

survey.ko.min.js:6 Uncaught TypeError: n.toLowerCase is not a function
    at t.questionHashesRemoved (survey.ko.min.js:6)
    at t.questionRenamed (survey.ko.min.js:6)
    at t.onNameChanged (survey.ko.min.js:6)
    at t.set [as name] (survey.ko.min.js:6)
    at e.apply (surveyeditor.min.js:12)
    at surveyeditor.min.js:12
    at e.performForAllProperties (surveyeditor.min.js:12)
    at e.apply (surveyeditor.min.js:12)
    at e.apply (surveyeditor.min.js:12)
    at e.apply (surveyeditor.min.js:12)

Currently i use 1.0.71, but the problem has always been there.
This happens with all questions. For now, we only use the inline edit.

### What is the expected behavior?

It closes the popup without JS error.

### How would you reproduce the current behavior (if this is a bug)?

See above.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: localhost, other dev machines, our test & production environment.

Test code

I could paste all the JS includes i have.

### Specify your

* browser: Chrome & Firefox
* editor version: 1.0.71

**Comment by andrewtelnov** [comment]
@lukasmedia I am not sure what does it mean
 "Select the comment box en click "edit". Make changes yes/no, doesnt matter." 

Could you please tell us more so we can fix the issue.

Thank you,
Andrew

**Comment by lukasmedia** [comment]
See image: https://snag.gy/RmWcQf.jpg
Pressing OK or Apply will result in the JS error. I cannot reproduce the error for example here: https://surveyjs.io/Survey/Builder 
So im almost sure it is something on my setup. But because it is on local, dev, test and production it is a include error maybe? Hard to reproduce on other environment(s).

**Comment by andrewtelnov** [comment]
@lukasmedia Could you create a plunker example with your code?
You may go to our [Survey Creator Examples](https://surveyjs.io/Examples/Builder/) look at HTML and JavaScript code or create a plunker example, by clicking "Edit in Plunker" button.

Thank you,
Andrew
