### ISSUE TITLE
Bug with "onValueChanged"

### ISSUE THREAD

**Issue by StanislavkoP** [surveyjs/survey-creator#503]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
When I added function "onValueChanged" this works only when first page has name "page1"

### What is the expected behavior?
If first page has any other name, "onValueChanged" doesn`t call

**Comment by andrewtelnov** [comment]
@StanislavkoP I could not reproduce this behavior. Could you please create a small example in plunker that demonstrate the issue?

Thank you,
Andrew
