### ISSUE TITLE
A custom column property value doesn't appear for the 'matrixdropdowncolumn' type

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5040]
User Issue: T16184 - Custom property for Dynamic Matrix Column
https://surveyjs.answerdesk.io/internal/ticket/details/T16184
***
[View Demo](https://codesandbox.io/p/sandbox/competent-water-k65hys?file=%2Fsrc%2FSurveyCreatorComponent.jsx)
If you register a custom property for a `matrixdropdowncolumn`, `question`, and `dropdown`, the custom property value doesn't appear for a matrix column.
![image](https://github.com/surveyjs/survey-creator/assets/22372972/472f6738-a37f-47d4-a274-1ef9b4b978af)
![image](https://github.com/surveyjs/survey-creator/assets/22372972/fc6ccaf7-8817-499e-bcaf-3a3da45348d2)

```
import { SurveyQuestionEditorDefinition } from "survey-creator-core";
import { surveyJson } from "./surveyJSON";

const customProp = {
  name: "customProp",
  category: "general",
};
Serializer.addProperty("matrixdropdowncolumn", customProp);
Serializer.addProperty("question", customProp);
Serializer.addProperty("dropdown", customProp);

SurveyQuestionEditorDefinition.definition[
  "matrixdropdowncolumn@default"
].properties.push(customProp);
```

Expected behavior: the custom property for matrix columns display values defined within a survey JSON.

**Comment by andrewtelnov** [comment]
Here is the correct code and the [working example](https://codesandbox.io/p/sandbox/magical-wilbur-hj9tr3?file=%2Fsrc%2FSurveyCreatorComponent.jsx):
```js
const customProp = {
  name: "customProp",
  category: "general"
};

const columnCustomProp = {
  name: customProp.name,
  category: customProp.category,
  onGetValue: function (obj) {
    return obj.templateQuestion[customProp.name];
  },
  onSetValue: function (obj, value) {
    obj.templateQuestion[customProp.name] = value;
  }
}

Serializer.addProperty("question", customProp);
Serializer.addProperty("matrixdropdowncolumn", columnCustomProp);

SurveyQuestionEditorDefinition.definition[
  "matrixdropdowncolumn@default"
].properties.push(customProp.name);

```
