### ISSUE TITLE
Ace Editor Version

### ISSUE THREAD

**Issue by huseyinbuyukdere** [surveyjs/survey-creator#506]
Hi, 

I 'm getting a error  in properties panel. When I changed combobox survey to page1  in properties panel, throws this error. 
![Error1](https://user-images.githubusercontent.com/39594189/56658132-7f6b8a00-66a2-11e9-9dfa-2e7890acf888.png)
After that it doesnt work.
Step 1
![error01](https://user-images.githubusercontent.com/39594189/56658370-294b1680-66a3-11e9-9b74-3985ee9a803f.png)
Step 2
![Screenshot_1](https://user-images.githubusercontent.com/39594189/56658492-66afa400-66a3-11e9-89db-5fbbd58cc9a2.png)
Step 3
![error02](https://user-images.githubusercontent.com/39594189/56658378-2e0fca80-66a3-11e9-8f95-f68ec5099376.png)
I think this problem is about the my react-ace library. I'm using react-ace library in another page in my project. Its version is "react-ace": "^6.4.0". How can I use react-ace package and survey-creator together  or which version of react-ace should I use or How can I disable ace editor in survey-creator.

**Comment by tsv2013** [comment]
Can you provide a sample illustrating the issue?

**Comment by huseyinbuyukdere** [comment]
![ScreenCapture_24-04-2019-16 21 18](https://user-images.githubusercontent.com/39594189/56662946-b5623b80-66ad-11e9-95a8-cc578a900ca6.gif)

**Comment by tsv2013** [comment]
It looks like these steps work ok in our online demo - https://surveyjs.io/create-survey/

**Comment by huseyinbuyukdere** [comment]
I did not say there is a bug or it doesn't work.  
I'm asking this.
![image](https://user-images.githubusercontent.com/39594189/56663431-bf386e80-66ae-11e9-93f5-587b2af9bb29.png)

**Comment by tsv2013** [comment]
I do understand your question. But I can't answer it without reproducing the behavior locally.

**Comment by huseyinbuyukdere** [comment]
You can try survey-creator with the react-ace (Ace Editor) package. You will see the problem.  I think this problem about the version. Survey-creator works without react-ace library very well. But latest version of react-ace is not suitable survey js ace editor package. If you can not do anything about it please give me advice for that what should I do.

**Comment by tsv2013** [comment]
Incompatibility can be caused by different factors from package versions to code specifics. If you can provide me with a sample illustrating the issue, I can check it.

**Comment by huseyinbuyukdere** [comment]
I tried in a sample project in this repo. 
[ https://github.com/huseyinbuyukdere/tryYourTest ](url)

I used default settings.

**Comment by tsv2013** [comment]
Thank you @huseyinbuyukdere , I'll check it.

**Comment by cakirlarc** [comment]
I think I may have solved this issue somehow.

Warning: This is a bit trial and error solution

I added `ace = require("ace-builds/src-min-noconflict/ace.js")` up in the tsx file after the imports, where the react component from the below sample is used
https://github.com/josdejong/jsoneditor/tree/master/examples/react_advanced_demo

I use jsoneditor in my project, it also uses ace like react-ace (never used it myself), I am not an expert in js but this require made the survey editor work without errors.

I will be happy if someone can explain why this worked.
