### ISSUE TITLE
The 'Cannot read properties of undefined reading 'name'' exception is thrown when removing all standard items except a custom toolbox item

### ISSUE THREAD

**Issue by chancesmith** [surveyjs/survey-creator#5067]
### Are you requesting a feature, reporting a bug or ask a question?
ask a question

### What is the current behavior?

I'm trying to add a new editable toolbox item with a panel containing an image and radiogroup.

I get an error when Creator user adds the question to the survey: `Cannot read properties of undefined reading 'name'` 

### What is the expected behavior?

I expect the customtype question to be added to the survey.

### How would you reproduce the current behavior (if this is a bug)?

Try adding a custom-named item with `creator.toolbox.addItemsaddItems()` that has any JSON you could get from the JSON Editor.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/p/sandbox/surveyjs-custom-toolbox-item-2x3y5d

Test code

```
creator.toolbox.addItems(
  [
    {
      name: CUSTOM_TYPE,
      isCopied: true,
      iconName: "icon-default",
      title: "Custom Type",
      category: "Custom",
      className: "svc-toolbox__custom-item",
      json: {
        type: "panel",
        name: "panel123",
        elements: [
          {
            type: "image",
            name: "question1",
            imageFit: "cover",
            imageHeight: "auto",
            imageWidth: "100%",
          },
          {
            type: "radiogroup",
            name: "question2",
            choices: ["Item 1"],
          },
        ],
        title: "Title of question",
      },
    },
  ],
  true
);

```

### Specify your

* browser: chrome 120.0.6099.71
* editor version: ^1.9.113

**Comment by JaneSjs** [comment]
Hello @chancesmith,
Please accept my apologies for the delayed reply. It seems that a SurveyJS Creator fails because all toolbox items except a custom one are removed. However, you custom item uses standard toolbox items inside.

 We will research this issue and update you shortly.
