### ISSUE TITLE
The creator.hasPendingThemeChanges is not listed in CreatorBase API

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5071]
T16243 - Save theme tab 
https://surveyjs.answerdesk.io/internal/ticket/details/T16243

https://github.com/surveyjs/survey-creator/blob/8f937bad8a0f2c92ee0a5736742aa3464bc07483/packages/survey-creator-core/src/creator-base.ts#L1264

The `creator.hasPendingThemeChanges` property is not available at https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator.

**Comment by tsv2013** [comment]
At this moment I believe that the `creator.hasPendingThemeChanges` flag is should be used for internal purposes only. I've re-chacked the the https://surveyjs.answerdesk.io/internal/ticket/details/T16243 ticket and looks for that customer is not actially need  in this property.
