### ISSUE TITLE
Logic Tab autosaves incorrect "setValue" after loading page

### ISSUE THREAD

**Issue by mgoetz-nerdery** [surveyjs/survey-creator#5083]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
If you load a survey with an existing "set answer" trigger in the logic tab, the autosave functionality will record an incorrect value for the setValue property of the trigger when the value is changed.

### What is the expected behavior?
The correct value should be passed in the autosave functionality.

### How would you reproduce the current behavior (if this is a bug)?
1. Visit the test case: https://codesandbox.io/p/sandbox/ecstatic-cherry-7zc9c6
2. Create a boolean question and a dropdown question
3. Add a logic rule: If the boolean question is "true", set the dropdown question to "Item 1"
4. Notice that autosave records the correct trigger: `{ "type": "setvalue", "expression": "{q1} = false", "setToName": "question1", "setValue": "Item 1" }`
5. Refresh the page so that the survey JSON is loaded from local storage
6. Switch to the logic tab and change the logic rule to If the boolean question is "true", set the dropdown question to "Item 2"
7. Notice that autosave now records an incorrect trigger.  It is still `{ "type": "setvalue", "expression": "{q1} = false", "setToName": "question1", "setValue": "Item 1" }`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/p/sandbox/ecstatic-cherry-7zc9c6?file=%2Fsrc%2FSurveyCreatorComponent.jsx

### Specify your

* browser: Chrome (120)
* editor version: Latest

**Comment by andrewtelnov** [comment]
@mgoetz-nerdery As soon as I change "Item 1" to "Item 2" then auto save is fired and it saved the data.
I can see that auto save is not fired on changing boolean question value. However, it is fired on clicking the "Done" button.
Do you experience the same behavior?

Thank you,
Andrew

**Comment by mgoetz-nerdery** [comment]
That does not quite line up with what I'm seeing.  On first load, I do experience the same behavior as you.  However, once I reload the page (which causes the survey JSON to be loaded from local storage), then I experience the bug listed above.  At that point, updating the dropdown in "set answer" will cause the originally saved value to be incorrectly saved, no matter what value I have selected.  See attached screenshot.

![Screenshot 2024-01-17 at 9 06 58 AM](https://github.com/surveyjs/survey-creator/assets/32200555/0b2f32bd-2e8c-4f3f-b3a6-396977300569)

**Comment by andrewtelnov** [comment]
@mgoetz-nerdery It is a weird issue, but I was able to reproduce it. I will take a look at it and comeback to you.

Andrew

**Comment by mgoetz-nerdery** [comment]
Thanks!  Glad you were able to find a resolution, and keep me posted on the progress!
