### ISSUE TITLE
Question choices counter behaviour

### ISSUE THREAD

**Issue by cs-salim** [surveyjs/survey-creator#5084]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question

### What is the current behavior?

Question choices are automatically created with an incremental counter: "Item 1", "Item 2", ...

My issue comes from the fact that this counter is specific to each question, so 2 questions can have the same "Item 1" value

I'd like to know if there is a way to make this counter global, so questions cannot share a choice with the same name (unless the user goes and manually edits it). So if I create a question1, the created choices will be "Item 1", Item 2", "Item 3", "Item 4", and if I then create a question2, the created choices will be "Item 5", "Item 6", ...

### Specify your

* browser: Chrome
* editor version: 1.9.120

Thanks!

**Comment by JaneSjs** [comment]
Hello @cs-salim,
You can override the text and value for newly created items using the [`creator.onItemValueAdded`](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onItemValueAdded) event. Please feel free to reopen this ticket if you have further questions.
