### ISSUE TITLE
Restrict nested panel

### ISSUE THREAD

**Issue by sumitlearnt** [surveyjs/survey-creator#509]
### Are you requesting a feature, reporting a bug or ask a question?
Feature

### What is the current behavior?
Nested panel is possible

### What is the expected behavior?
Nested panel need to be blocked.

### How would you reproduce the current behavior (if this is a bug)?
Create  two panels, drag one panel and drop it to another panel .  This will create nested panel , is it possible to trigger event to identify source and target   while doing drag and drop.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@sumitlearnt Please use the following code:
`SurveyCreator.DragDropHelper.nestedPanelDepth = 0;`
Unfortunately, it will work from the next minor version, that we are going to release tomorrow.

Thank you,
Andrew
