### ISSUE TITLE
Create a theme model that inherits from a base class with serialization information.

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#5094]
- [ ] Implementation of a method ToJson for saving cssVariables into one object. 

Need the following features for property grid:
- [x] #5161
- [x] #5162
- [x] #5163

![image](https://github.com/surveyjs/survey-creator/assets/14936841/56e51402-4150-489a-be83-dad648c1a975)

**Comment by tsv2013** [comment]
Waiting for property grid re-design
