### ISSUE TITLE
Removing properties before creator.onCanShowProperty() is called

### ISSUE THREAD

**Issue by joegalley** [surveyjs/survey-creator#510]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
When you use ```creator.onCanShowProperty()``` to hide some properties, the hidden properties will still be shown when you initially load the survey. They will only be hidden after `onCanShowProperty()` is called, which does not seem to happen during initial pageload.

### What is the expected behavior?
I would expect `onCanShowProperty()` to be called BEFORE the element is ever shown.

OR I would expect there exist a way to hide all properties on an element initially WITHOUT looping through all existing properties and calling 
```
Survey
    .JsonObject
    .metaData
    .removeProperty("survey", "<property name>");
```

### How would you reproduce the current behavior (if this is a bug)?
You can see this behavior here: https://plnkr.co/edit/hYN8hgGnh5y6icGLftvs?p=preview. All properties except `title` should be hidden on a `Survey`. But when you first load the page, all properties are shown for the Survey. Only after you click the dropdown on the right, select ".page1", then re-select "Survey" do you see the properties being hidden.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  https://plnkr.co/edit/hYN8hgGnh5y6icGLftvs?p=preview

### Specify your

* browser: Chrome
* editor version: 1.0.84

**Comment by andrewtelnov** [comment]
@joegalley I have forked [your example](https://next.plnkr.co/edit/xZcjeqWn4sSzqDEf?preview)
You have to create the Survey Creator, set it's properties/events and then render.

Thank you,
Andrew

**Comment by joegalley** [comment]
Awesome, that works! Thank you so much @andrewtelnov!
