### ISSUE TITLE
Survey properties are not same between right-hand side and in "Survey Settings" dialog

### ISSUE THREAD

**Issue by joegalley** [surveyjs/survey-creator#511]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question

### What is the current behavior?

When I hide or show specific properties on the Survey object, I see those properties on the right side of the screen, but I do not see them reflected when I press the "Survey Settings" button.

### What is the expected behavior?

I would expect the properties shown from the "Survey Settings" button would be the same as the settings shown on the right side of the screen.

### How would you reproduce the current behavior (if this is a bug)?

This is visible in this example: http://plnkr.co/edit/mZxBWtkmUU47cEmd9ZHl?p=preview. Notice how the right side has "title", "showQuestionNumbers", "showProgressBar", "locale", and "isSinglePage". Then press "Survey Settings" and notice how the properties shown are not the same.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: http://plnkr.co/edit/mZxBWtkmUU47cEmd9ZHl?p=preview

### Specify your

* browser: Chrome
* editor version: 1.0.17

**Comment by andrewtelnov** [comment]
@joegalley We have fixed this issue many times ago. The current version is v1.0.84. 
We released v1.0.17 on Apr 17, 2018, over a year ago.

Thank you,
Andrew

**Comment by joegalley** [comment]
Thanks @andrewtelnov, that works

**Comment by joegalley** [comment]
It doesn't seem to work with custom properties added to the `survey` object, e.g.: 

```
Survey
    .JsonObject
    .metaData
    .addProperty('survey', {
        type: 'dropdown',
        name: 'my-list',
        title: 'My list',
        isRequired: true,
        colCount: 0,
        choices: [
            'option 1',
            'option 2'
        ]
    });
```

The `my-list` dropdown doesn't show up when you click "Survey Settings" in this example: http://plnkr.co/edit/6teUMzuwXkeiLKMw9fZn?p=preview. But maybe that's because it doesn't seem to be in a "category" (e.g. "General", "Navigation", or "Question"?

**Comment by andrewtelnov** [comment]
@joegalley Please read the following [section](https://surveyjs.io/Documentation/Survey-Creator/#elementseditor) in docs. It shows how to add/remove a property into/from Editor.

Thank you,
Andrew

**Comment by joegalley** [comment]
Awesome, thank you @andrewtelnov 

For anyone else seeing this, here's a working example with the new tab on the Survey object and a custom property: http://plnkr.co/edit/7uv9gEYWEdnuVEZOL2SV?p=preview

**Comment by Wenzil** [comment]
`my-list` appears literally as "my-list" in the modal property editor. How to give it a title so that it appears as "My List"?
