### ISSUE TITLE
[Question] Can we customize the "headers" inside the translation tab?

### ISSUE THREAD

**Issue by xunilrj** [surveyjs/survey-creator#512]
### What is the current behavior?

When a question has a validator, for example, the validation text appears as "validator[0]" instead of something that makes sense to whoever is translating the survey. 

![image](https://user-images.githubusercontent.com/83425/57477919-a2e12800-7291-11e9-85e8-31113d9b061c.png)

### What is the desired behavior?

In my case, this validator was created using a question prototype, so I could easily name the validator for something like "InvalidUrlError". For example:

```
this.editor.toolbox.addItem({
            name: 'url',
            isCopied: true,
            iconName: 'icon-expression',
            title: I18n.t('template.builder.url'),
            json: {
                type: 'text',
                inputType: 'url',
                validators: [{
                    translationKey: 'InvalidUrlError'
                    type: 'regex',
                    text: 'Please enter a valid url.',
                    regex: '...',
                }],
            },
        });
```

**Comment by andrewtelnov** [comment]
@xunilrj What do you think, if we show it as:
Validator: [typeName], [text]
In your example, instead of Validators[0 ],it would be:
Validator: regex, Please enter a valid url. 

Thank you,
Andrew

**Comment by xunilrj** [comment]
It is fine by me. :)

**Comment by andrewtelnov** [comment]
@xunilrj I have added toString() functions into validator. After the next minor release I will use them in Survey Creator.

Thank you,
Andrew
