### ISSUE TITLE
Property Grid - The 'Type To Search...' label of a drop-down action cannot be translated

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5139]
User Issue: T16627 - Override Individual Translations in Survey Creator
https://surveyjs.answerdesk.io/internal/ticket/details/T16627
***
[View Demo](https://codesandbox.io/p/sandbox/dark-paper-3q6823?file=%2Fsrc%2FSurveyCreatorComponent.jsx%3A16%2C47)

It is unclear how to change / translate the 'Type To Search...' label. It appears within the search box of a property grid or within the Translation tab's property grid:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/ea455389-6810-4875-b44e-c99087b3f5f4)

**Comment by andrewtelnov** [comment]
"Type to search..." string is located in the survey. It shows in all list popups with the search editor.
You can change is as the following:
```js
const enStrings = Survey.surveyLocalization.getLocaleStrings("en");
enStrings.filterStringPlaceholder = "Type...";
```
However, it will be changed everywhere.
If you want to change this string for translation tab only then you can use the code from [this example](https://plnkr.co/edit/xquWSq14Ksbd6zdb).

```js
const enStrings = Survey.surveyLocalization.getLocaleStrings("en");
const typeToSearchStr = enStrings.filterStringPlaceholder;
```

```js
    creator.onActiveTabChanging.add((sender, options) => {
        if(options.tabName === "translation") {
            enStrings.filterStringPlaceholder = "Type..";
        } else {
            if(creator.activeTab === "translation") {
                debugger;
                enStrings.filterStringPlaceholder = typeToSearchStr;
            }
        }
    });
```
Thank you,
Andrew
