### ISSUE TITLE
Swapping pages in the property grid doesn't update inplace editor

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#5144]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
https://github.com/surveyjs/survey-creator/assets/547021/b9c2c931-9d75-4c54-bcb9-45e1657e3303

### What is the expected behavior?
The page titles should swap as well.

### How would you reproduce the current behavior (if this is a bug)?
See the video.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/create-free-survey

### Specify your

* browser: Tested on Firefox & Chromium

**Comment by SamMousa** [comment]
Is more information required for this issue?

**Comment by JaneSjs** [comment]
Hi @SamMousa,
Please accept my apologies for the delay. In your video, the `Page 1` and `Page 2` captions which appear on a design surface are actual placeholders. Placeholders reflect the actual order of pages within the pages array. Therefore, they are not updated when you reorder pages. You may define page's titles and observe that titles will be correctly updated if you reorder pages.

Drop me a line if you require further clarification.

P.S. SurveyJS Creator requires a [commercial developer license](https://surveyjs.io/licensing). For licensed users, please contact us via the [Help Desk](https://surveyjs.answerdesk.io/ticket/list?preset=mytickets) for faster assistance.

Thanks

**Comment by SamMousa** [comment]
I have a commercial license but as a developer I spent all of my time on github in lots of repositories and prefer to use that over some internal system, I'm okay with slower response times, usually the issues I create I create to help you improve your library (which benefits me as a consumer of that code).

By the way, you could set up a workflow like this one: https://github.com/srvaroa/labeler?tab=readme-ov-file#authors
To automatically add a label to issues created by paying customers, it'd simplify contributions by paying customers a lot!

**Comment by JaneSjs** [comment]
Hi @SamMousa,
Thank you for the confirmation. For licensed users, technical support is available via [Help Desk](https://surveyjs.answerdesk.io/ticket/list?preset=mytickets).

Thank you
