### ISSUE TITLE
Property Grid: Add a capability to change titles for editors within the Choices table

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#5146]
![image](https://github.com/surveyjs/survey-creator/assets/18551316/14e49e9a-d5a1-4d8c-9fa4-2f6f6a0be482)

**Comment by andrewtelnov** [comment]
@RomanTsukanov You can modify pe.itemvalue. For example:
```js
    itemvalue: {
      text: "Alt text",
      visibleIf: "visible if for itemvalue"
    },

```
Thank you,
Andrew
