### ISSUE TITLE
Property Grid: Add a capability to specify different category names based on the element type 

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#5148]
For example, "Layout" from the image below should be "Panel Layout" for panels and "Question Layout" for questions.

![image](https://github.com/surveyjs/survey-creator/assets/18551316/256da3cb-174a-4dbc-bb6d-73b4251b40ff)

**Comment by andrewtelnov** [comment]
@RomanTsukanov You will need to use it in the following way:
```js
      layout: {
        panel: "Panel Layout",
        question: "Question Layout",
        base: "Layout"
      },
```

Thank you,
Andrew
