### ISSUE TITLE
Property Grid: Add headers to matrix tables (choices, columns, rows, etc.)

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#5154]
Now the choice table, for example, doesn't have a header that would specify which column contains values and which - display texts.

![image](https://github.com/surveyjs/survey-creator/assets/18551316/66d7a9a9-e716-4601-98b7-4964cc0d7283)

We need to add a header similar to the one we have for an Image Picker question:

![image](https://github.com/surveyjs/survey-creator/assets/18551316/88a29bc1-365a-4f16-bec5-2d83cbd1c179)

**Comment by mikeamelin** [comment]
@andrewtelnov 

Sure, we can. I don't see a problem.
