### ISSUE TITLE
Localisation toolboxChoiceCategory in french 

### ISSUE THREAD

**Issue by souareas** [surveyjs/survey-creator#5155]
### Are you requesting a feature, reporting a bug or ask a question?

reporting a bug

### What is the current behavior?

toolboxChoiceCategory est traduit par "Qu**esit**ons à choix"

### What is the expected behavior?

toolboxChoiceCategory doit etre traduit par "Qu**esti**ons à choix"

### How would you reproduce the current behavior (if this is a bug)?

It's when we display the types of questions by category and we are in French

#### Provide the test code and the tested page URL (if applicable)

https://github.com/surveyjs/survey-creator/blob/v1.9.128/packages/survey-creator-core/src/localization/french.ts

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@souareas Fixed the [this commit](https://github.com/surveyjs/survey-creator/commit/7b50a16e98f9dc686b7b7218937e2356b88d6c77).

Thank you,
Andrew
