### ISSUE TITLE
Property Grid: Add a capability to render enums as checkboxes

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#5165]
We need to render the "Columns layout" button group from the image below as a "Traspose rows to columns" checkbox:

![image](https://github.com/surveyjs/survey-creator/assets/18551316/cb4f6510-ad68-4129-abae-4c06392ff3f1)

**Comment by andrewtelnov** [comment]
@RomanTsukanov You will need to set the "boolean" property type for this properties.
```js
    {
      name: "columnLayout:boolean",
      alternativeName: "columnsLocation",
      default: "horizontal",
      choices: ["horizontal", "vertical"],
    }
```
