### ISSUE TITLE
Property Grid: Add a capability to change property editor names for matrix columns

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#5166]
![image](https://github.com/surveyjs/survey-creator/assets/18551316/67c8fa66-4bc9-49ab-9efc-18994c2c8d47)

**Comment by andrewtelnov** [comment]
Please add the following code into "pe" section
```js
    matrixdropdowncolumn: {
      name: "Column name"
    },

```

Thank you,
Andrew
