### ISSUE TITLE
Change the ordering of the editor tabs.

### ISSUE THREAD

**Issue by robertomcampos** [surveyjs/survey-creator#517]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?
The tabs of the survey-creator are ordered as : 
![editortabs](https://user-images.githubusercontent.com/5176761/57715043-32992480-764c-11e9-983a-6646036c5757.PNG)

### What is the expected behavior?
I would like to change this ordering.

Is there a way to do this?

Thank you.

**Comment by tsv2013** [comment]
Here is the sample - https://plnkr.co/edit/yxjW9V1sexErKrNEDFDf?p=preview

```JS
var creatorOptions = {};
var creator = new SurveyCreator.SurveyCreator("creatorElement", creatorOptions);

// Reorder tab
var jsonTab = creator.tabs()[2];
creator.tabs.remove(jsonTab);
creator.tabs.splice(0, 0, jsonTab);

// Add custom tab
creator.tabs.push({
        name: "myTab",
        title: "My Tab Title",
        template: "se-tab-custom",
        data: creator,
        action: function() { creator.koViewType("myTab"); }
      });
```

**Comment by robertomcampos** [comment]
Morning,

Whenever I use the knockout "remove" function, I get lost the tab reference and this one stop to work.

Another problem is a bug between knockout function "splice" on IE11. the console shows a promise error.

![image](https://user-images.githubusercontent.com/5176761/57971082-c70eca00-795f-11e9-89eb-ef8945e8f507.png)

**Comment by tsv2013** [comment]
Can you try the `this.editor.tabs(surveyTabs)` ?
