### ISSUE TITLE
Auto-translation pop-up: Buttons overlap each other on small screens

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#5184]
![image](https://github.com/surveyjs/survey-creator/assets/18551316/e479bf65-39ed-4bd1-9ea6-23363ebdefba)

**Comment by mikeamelin** [comment]
https://www.figma.com/file/i6Lpc7zkjHtso2oXZV97fo/*-Components?type=design&node-id=20872-132588&mode=design&t=Qy2yZ5yBDN9OhKhh-4
