### ISSUE TITLE
Survey Description Property Editor allows entering new lines which are further eliminated in preview

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5185]
* T15725 - How to disabled design surface's description?
https://surveyjs.answerdesk.io/internal/ticket/details/T15725

_Because when I edit the description of the design surface, after unfocusing, it replaces the "\n" in the string with a space. I'm not sure if this is normal behavior, but to prevent it from happening, I would like to disable the description._

* T16617 - Page description line breaks lost
https://surveyjs.answerdesk.io/internal/ticket/details/T16617

_If you want to stick to a textarea support to display the entered linebreaks should be added! How should the user know that his entered linebreak is not supported for the displayed text? Everyone would call that a bug if there is no visible information that a linebreak is not supported._
***

**Issue**
A user enters a survey description within the property grid editor, which allows line breaks. 
![image](https://github.com/surveyjs/survey-creator/assets/22372972/39e7d2fd-be8f-4c81-a88c-0eec09ed6bed)

However, in preview or within the inplace editor, a description doesn't preserve line breaks.
![image](https://github.com/surveyjs/survey-creator/assets/22372972/bc802c69-0b04-4e69-bde4-58fc40991cd6)
![image](https://github.com/surveyjs/survey-creator/assets/22372972/2ce0096a-1700-4d3c-b6ce-c05117bdcdc5)

Possible options to handle this:
* Enable line breaks within the in-place editor.
* Change the long-text property grid editor to the single-line input editor for the Description field.
Use the following code to register a single-line input field for the Description property:
```
SurveyCreatorCore.PropertyGridEditorCollection.register({
    fit: function(prop) {
        return prop.name === "description";
    },
    getJSON: function(obj,  prop,options) {
        return { type: "text" }
    }
});
```

**Comment by novikov82** [comment]
spike - https://github.com/surveyjs/survey-creator/compare/issue/5185-Survey-Description-Property-Editor-allows-entering-new-lines-which-are-further-eliminated-in-preview?expand=1

**Comment by AndOne1974** [comment]
Good News:
1) Linebreaks can be entered.
2) They can be entered directly or in the right sidebar.
3) Pasted linebreaks are not removed.

Bad news: In the survey edit area linebreaks can only be entered via <shift><enter>. Normal <enter> removes the focus from the description field.
This is unusable, because <shift><enter> (Line break instead of paragraph) is not known to many users.
