### ISSUE TITLE
Add a dropdown question with the options on hidden mode.

### ISSUE THREAD

**Issue by robertomcampos** [surveyjs/survey-creator#520]
### Are you requesting a feature, reporting a bug or ask a question?
feature

### What is the current behavior?
Whenever I add a question of type dropdown, the option is displyed opened.

### What is the expected behavior?
I would like to decide if the options would displayed as hidden.

### How would you reproduce the current behavior (if this is a bug)?
![image](https://user-images.githubusercontent.com/5176761/57852520-bae90800-77b9-11e9-82ca-66816cd5b25e.png)

Thank you,

**Comment by tsv2013** [comment]
I've added the `SurveyEditor.selectItemsEditorAdorner.isExpanded` option. After the next minor update you ca use the following code:
```JS
SurveyEditor.selectItemsEditorAdorner.isExpanded = false;
```
