### ISSUE TITLE
The survey creator stopped showing up on my old project.

### ISSUE THREAD

**Issue by Nikunjwdv0106** [surveyjs/survey-creator#5201]
Is there any trial period or something?
It's been working fine with the same code and project for 15 days. 

It worked fine when I did the same setup with the same version. But It's not showing on the old project. I configured the license key, but it's not showing a yellow label on the bottom or anything else. It's showing on DOM but not on UI.

I am using the Angular version 15 and Survey Creator Version 1.9.126

**Comment by JaneSjs** [comment]
Hello @Nikunjwdv0106,
You can try our SurveyJS Creator in demo mode. Evaluate the SurveyJS Creator functionality to see how well it suits your need.
If you consider using the SurveyJS Creator in further development, consider purchasing a SurveyJS developer lincese. You'll be granted a personal developer key which you'll be using to add and activate your license within your Angular app and remove the trial banner.

For more information, please visit the following pages:
* [Product Licensing](https://surveyjs.io/licensing)
* [Pricing](https://surveyjs.io/pricing)

Please let me know if you have any further questions.
