### ISSUE TITLE
Advanced Header - The Header Background Color Update when changing a Theme

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5208]
* Enable the Advanced Header and specify the Custom header color:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/910e3d50-a8fe-481d-b43b-4c2b32da1206)
* Select Another Theme. For example, choose Borderless.
![image](https://github.com/surveyjs/survey-creator/assets/22372972/c496e990-16be-4429-abd9-d00242f414d7)
* According to the Property Grid, the Header background uses the Accent color defined within a custom theme. However, the header displays the Custom color which was defined previously.
![image](https://github.com/surveyjs/survey-creator/assets/22372972/814af9e4-289f-4eb0-8779-d74c3c7bcb55)

Questions:
* Should the Header Color be reset when changing a theme?
* Or, should a newly selected theme use the Custom color defined within the previously selected theme?

**Comment by tsv2013** [comment]
IMHO the only issue here is that property grid doesn't reflect actual state of things - header background color that should be kept between theme changes if theme doesn't contain header defintion: we need to keep header color entered by user if header is not defined in theme JSON.
But probably I'm wrong and it's a matter of discussion.
