### ISSUE TITLE
Long load times for large schemas - How to set a "loading page" for the survey editor _itself_?

### ISSUE THREAD

**Issue by oheydrew** [surveyjs/survey-creator#521]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behaviour?

Is there a "loading" element for the *editor* itself, while the *editor* loads it's schemas? (not the `loadingHTML` for the survey renderer, but for the editor itself)

Currently using the `surveyjs-editor` package with React for customization. We've got some pretty large JSON Schemas (multiple pages, lots of question panels, roughly ~80 questions per page).

We've got a reasonable amount of logic around customizing fields and editor options, looping through sections using events such as `onPropertyValueChanging` and `onCanShowProperty` etc.

Seeing particuarly slow loading time once the `surveyjs-editor` starts to load in the schema. At this stage, the window hangs, the browser is nonresponsive, depending on the system, for anywhere from a fraction of a second to multiple seconds. This is particuarly noticable in development environments, but not as bad in minified and packaged production.

### What is the expected behaviour?

We'd love a way to set a "loading" page, even if static, whilst the survey editor loads. 

At the moment I'm considering loading the editor with a blank schema with some kind of loading HTML inside of it, so it might at least display to the user that the editor is loading, but I'd prefer to see if there's a better way

### How would you reproduce the current behaviour (if this is a bug)?

N/A

* browser: Chrome
* editor version: `1.0.85`

**Comment by andrewtelnov** [comment]
@oheydrew Could you provide us with your survey JSON? We would love to play with it.
Do you want to increase the performance for Survey Creator or Survey Library or both?

Thank you,
Andrew
