### ISSUE TITLE
A drop-down adorner list for the subsequent question is not updated when removing a question

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5224]
T16685 - FR: Question -> move to
https://surveyjs.answerdesk.io/internal/ticket/details/T16685
***
The following demo creates a drop-down action list which allows users to move the question under the selected question: [View Demo](https://plnkr.co/edit/ZP7kbl4tDjUt0Rdj).
However, there is an issue.
* Remove Question 2;
* Check the drop-down question list for Question 1, Question 4 and 5. You'll see that Question 2 correctly disappears. However, for Question 3, the Question 2 persists:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/6227cd57-51b8-4330-8daa-762a9f40ae94)

**Comment by OlgaLarina** [comment]
@JaneSjs 
It is necessary to add a condition: 
`if(o.type == "ADDED_FROM_TOOLBOX" || o.type == "ADDED_FROM_PAGEBUTTON" || o.type == "OBJECT_DELETED" || (o.type === "PROPERTY_CHANGED" && (o.name === "name" ||  o.name === "elements")))`

Updated demo: https://plnkr.co/edit/itSsuKnkl78kXfqN
