### ISSUE TITLE
Themes tab: The "Yes, reset the theme" button appears beyond the popup window's boundaries

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5228]
T16898 - Theme Reset Button Text is cut off
https://surveyjs.answerdesk.io/internal/ticket/details/T16898
***
[View Demo](https://plnkr.co/edit/8sKPOBkgS7vD1gYk)

To reproduce the issue, activate the Theme tab and click the Reset button.
![image](https://github.com/surveyjs/survey-creator/assets/22372972/ac3d2c73-07b4-4dd5-afd4-4a195f4129b5)

**Comment by AndOne1974** [comment]
Btw. "Cancel" is wrong when the language is set to german. It should be "Abbrechen".

**Comment by dmitry-kurmanov** [comment]
> Btw. "Cancel" is wrong when the language is set to german. It should be "Abbrechen".

Thanks! We will fix it too.
