### ISSUE TITLE
Do survey designer support Chinese

### ISSUE THREAD

**Issue by w5688414** [surveyjs/survey-creator#523]
### Are you requesting a feature, reporting a bug or asking a question?
I want to change English language to Chinese language in the survey designer part, What should I do if I want to change it 

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Moved to the corresponding repo

**Comment by tsv2013** [comment]
Here are available localizations - https://github.com/surveyjs/survey-creator/blob/master/src/localization/simplified-chinese.ts and https://github.com/surveyjs/survey-creator/blob/master/src/localization/traditional-chinese.ts

Here is the live sample - https://surveyjs.io/Examples/Survey-Creator/?id=localization&theme=bootstrap

For traditional chinese you should use the following code:
```JS
SurveyCreator.localization.currentLocale = "zh-tw";
```
