### ISSUE TITLE
How can we put bold text inside question text and show the power of any number in the text? 

### ISSUE THREAD

**Issue by chaklasiyanikunj** [surveyjs/survey-creator#5231]
I need to show some words in bold in questions using Survey Creator. I checked the layout, but there is no option available there.
I also show the power of any number, like the image below.
![bold_and_power](https://github.com/surveyjs/survey-creator/assets/39697799/4c6f1d49-63fc-404f-9b92-e18d3d9fefa1)

Currently It's showing like below image.
![Survey_Creator_Output](https://github.com/surveyjs/survey-creator/assets/39697799/bc799dad-b382-47a9-aed5-12032970c827)

I think it's taking whole question as bold. Can we differentiate the word inside question text.

Can anyone suggest how I can perform this?

**Comment by andrewtelnov** [comment]
Hello,
You can use markdown functionality. You can modify surveys: designer and preview using approach shown in [this example](https://surveyjs.io/survey-creator/examples/modifysurveys) and [here is a markdown example in the library](https://surveyjs.io/form-library/examples/edit-survey-questions-markdown).

Thank you,
Andrew
