### ISSUE TITLE
Tab changed handler

### ISSUE THREAD

**Issue by robertomcampos** [surveyjs/survey-creator#524]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the expected behavior?

How can I know which tab is selected? For example, a test tab.

**Comment by tsv2013** [comment]
```JS
creator.koViewType.subscribe(function(newViewType) {
    if(newViewType === "test") {
    }
});
```

Other view types can be foud here - https://github.com/surveyjs/survey-creator/blob/master/src/editor.ts#L1535-L1573
