### ISSUE TITLE
Is there any way for redirecting to another paging using surveyJS

### ISSUE THREAD

**Issue by chaklasiyanikunj** [surveyjs/survey-creator#5249]
Is there any way to redirect second page or any specific question with clicking button or selecting option?

![pageRedirect](https://github.com/surveyjs/survey-creator/assets/39697799/2556cfe7-38ed-48bb-9c0c-a61b8198f245)

I refering this example https://surveyjs.io/form-library/examples/automatically-move-to-next-page-if-answer-selected/reactjs#content-code but here used the goNextPageAutomatic.
Is there any manually page navigating available in survey JS

**Comment by andrewtelnov** [comment]
Hello,
`creator.selectElement(yourPage)` will work.
to get the page by name you can use `creator.survey.getPageByName("yourPageName");`.

Thank you,
Andrew

**Comment by chaklasiyanikunj** [comment]
Thank you so much your great reply.
