### ISSUE TITLE
Matrix Dynamic has wrong layout in StartWithNewLine case

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-creator#525]
![image](https://user-images.githubusercontent.com/30930391/58338175-e0c47b80-7e4f-11e9-851f-d054d32a67ff.png)
![image](https://user-images.githubusercontent.com/30930391/58338186-e5892f80-7e4f-11e9-9555-6d928f3ebcf4.png)

{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "question1",
     "columns": [
      {
       "name": "col",
       "cellType": "dropdown"
      },
      {
       "name": "rad",
       "cellType": "radiogroup"
      },
      {
       "name": "com",
       "cellType": "comment"
      },
      {
       "name": "bol",
       "cellType": "boolean"
      }
     ],
     "choices": [
      "item1",
      "item2",
      "item3",
      "item4"
     ],
     "optionsCaption": "caption",
     "cellType": "comment",
     "columnColCount": 2,
     "rows": [
      "Row 1",
      "Row 2"
     ]
    },
    {
     "type": "matrixdynamic",
     "name": "question3",
     "columns": [
      {
       "name": "col",
       "cellType": "dropdown"
      },
      {
       "name": "rad",
       "cellType": "radiogroup"
      },
      {
       "name": "com",
       "cellType": "comment"
      },
      {
       "name": "bol",
       "cellType": "boolean"
      }
     ],
     "choices": [
      1,
      2,
      3,
      4,
      5
     ]
    },
    {
     "type": "matrixdropdown",
     "name": "question2",
     "startWithNewLine": false,
     "showHeader": false,
     "columns": [
      {
       "name": "Column 1"
      },
      {
       "name": "Column 2"
      },
      {
       "name": "Column 3"
      }
     ],
     "columnLayout": "vertical",
     "choices": [
      1,
      2,
      3,
      4,
      5
     ]
    }
   ]
  }
 ]
}

**Comment by d1vyanshu** [comment]
Hi I would like to work on this. Can you explain the problem a little bit for me and which file should I possibly look at? 
Thanks!

**Comment by gologames** [comment]
Seems fixed in latest version
