### ISSUE TITLE
Toolbox's left padding disappeared somewhere.

### ISSUE THREAD

**Issue by mikeamelin** [surveyjs/survey-creator#5251]
![Image](https://github.com/surveyjs/survey-creator/assets/17025812/c8c990e0-afc6-45bf-9e09-9b23f63f5d35)

**Comment by tsv2013** [comment]
It looks like the issue is related to Safari only that doesn't support the `scrollbar-gutter: stable both-edges` CSS rule. I've added fix for Safari, we'll check it after merge.
