### ISSUE TITLE
Disable lazy rendering of questions in Creator 

### ISSUE THREAD

**Issue by jburghardt** [surveyjs/survey-creator#5254]
### Are you requesting a feature, reporting a bug or ask a question?

feature/question

### What is the current behavior?

SurveyCreator does not show all questions when after initalizing it with a big json.
Somehow the amount of Rows shown is dependent on the height the container has ( i think? )

### What is the expected behavior?

SurveyCreator does render the Complete Survey loaded from JSON.
If the user want lazy rendering of questions, it should be passed as an option to the Creator

e.g  new SurveyCreator({ lazyRender: true })

### How would you reproduce the current behavior (if this is a bug)?

This codePen is taken from the Demo. The container in which the Survey is loaded has a height of 500px. 
SurveyCreator will only render a couple of questions first, lazy loading all others while scrolling. 

There is no way in the Creator to disable this

https://codepen.io/kcs-frontend/pen/KKELBBe

There are some issues around suggesting the LazyRowsRendering Options, but
A. they do not work!
B. If they did they should be part of the Options passed to the Creator !

Thanks and greetings!

**Comment by JaneSjs** [comment]
Hello @jburghardt,
SurveyJS Creator by default enables lazy loading/rendering of survey questions on a design surface. With this option, SurveyJS Creator can initialize a survey faster and progressively load questions as soon as users scroll a survey. This option is especially useful for large surveys.

If you are not satisfied with the behavior, you can disable lazy question rendering as Andrew mentioned.

Please feel free to reactivate this thread if you have any further questions.

Thanks
