### ISSUE TITLE
visibleIf for checkboxes only works with "contain" keyword and not the syntax added by default 

### ISSUE THREAD

**Issue by lady3bean** [surveyjs/survey-creator#526]
### Are you requesting a feature, reporting a bug or ask a question?

reporting a bug

### What is the current behavior?

When you are selecting VisibleIf's based on checkbox responses, using the drop down menu selection instead of the text area, if you select a few options, the default text added is like this:

`{question1} = ["item1","item2"]`

However, this does not work to make the question visible if any of those values are selecting.

It only works if you write it `{question1} contains "item1" or {question1} contains "item2"`

In previous issues, you have said that it must be written with "contains" like this - https://github.com/surveyjs/survey-library/issues/1081

But then adding the checkbox values through the menu should result in the right "contains" syntax being used.

### What is the expected behavior?
Either: The syntax `{question1} = ["item1","item2"]` works

Or: Adding visibleIf's through the menu defaults to the "contains" syntax that works instead

### How would you reproduce the current behavior (if this is a bug)?
believe this has been covered by 
https://github.com/surveyjs/survey-library/issues/565 which has an example. But I'm reporting something different, which is that your default behavior produces the wrong syntax, if "contains" is what we're supposed to use.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@lady3bean I beleive you are talking about adding "anyof" an d"allof" operators:
`{checkboxquestion} anyof ["value1", "value2", "valueN"]` - returns true if any of these values are selected
and
`{checkboxquestion} allof ["value1", "value2", "valueN"]` - returns true if all these values are selected.

Am I correct?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@lady3bean I have implemented [anyof and allof](https://github.com/surveyjs/survey-library/issues/1695)

Thank you,
Andrew

**Comment by lady3bean** [comment]
great, thanks so much for doing this so quickly. Anyof/allof works like a charm.

**Comment by lady3bean** [comment]
Sorry, I may have spoken too soon! When testing out the script in the "Test Survey" panel, using the anyof/allof works great. However, in the main survey (using the Survey model), questions set up with visibleIfs based on anyof/allof for checkboxes show all the time. Is there a chance that the survey library needs an update to correlate with the changes in the builder for this issue?

**Comment by andrewtelnov** [comment]
@lady3bean What do you mean? You should use the same version for SurveyJS Library and Creator and anyof/allof feature was added from v1.0.88 only. The previous versions will likely ignor the expression with anyof/allof.

Thank you,
Andrew
