### ISSUE TITLE
Is there any way to hide the question text using any field?

### ISSUE THREAD

**Issue by chaklasiyanikunj** [surveyjs/survey-creator#5267]
I need to hide only question text using Survey Creator.

I know this is possible with HTML. But I also need to do this with other controls.

![QuestionTextHidden](https://github.com/surveyjs/survey-creator/assets/39697799/4eeefda6-9873-4480-bafe-9885dfec9f96)

Is there any way to hide question text?

**Comment by JaneSjs** [comment]
Hello @chaklasiyanikunj,
From what I gather, you wish to hide the inplace editor for a question's title property. Unfortunately, there is no setting which would do so. However, you can achieve this by implementing a custom component. Refer to the corresponding guide for [Angular](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-angular)/[React](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-react)/[Vue 3](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-vue). For instance, override a default Text question and hide the title inplace editor.

Please feel free to contact us if you have further questions.

**Comment by chaklasiyanikunj** [comment]
Do you mean it possible using creating custom widget?
