### ISSUE TITLE
limiting the question types in the editor options does not remove types from the dropdown

### ISSUE THREAD

**Issue by lady3bean** [surveyjs/survey-creator#527]
### Are you requesting a feature, reporting a bug or ask a question?

could be either!

### What is the current behavior?

To limit what question types are available in the toolbox, it's suggested we limit them in the editor options - https://www.surveyjs.io/Documentation/Survey-Creator/#toolbox

I have done that, and indeed when I limit them, I see only the ones I chose in the toolbox.

However, that has not limited question types available in the dropdown on questions once they are added to the editor. This dropdown appears in the upper right corner of questions when you click on them in the editor.

![Screen Shot 2019-05-24 at 5 38 46 PM](https://user-images.githubusercontent.com/10011287/58357957-d5228600-7e4a-11e9-96f1-0d000d952ba6.png)

### What is the expected behavior?
That limiting the question types would limit them across the board, unless there is another place where we can limit what's available in this drop down.

So that's the potential question - is there a way to limit the options in this drop down? 

If not, and the only way to limit question types is in the options as I'd already done, I'd expect that those limits would carry across the board.

### How would you reproduce the current behavior (if this is a bug)?
surveyjs survey builder example

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@lady3bean That is different. You may disable complete this functionality, by using `surveyCreator.onElementAllowOperations` event.
We have undocumented `SurveyCreator.QuestionConverter` class, where you may add a new conversion from one type into another. We do not have ability to remove the convertion, we can add this functionality.
Another way, we may add a function to unregister the question type completely. In this case the `Survey.Serializer' will not be able to deserialize the JSON correctly if the type will be used in this JSON.

Thank you,
Andrew

**Comment by lady3bean** [comment]
thanks for the quick response - that's what I needed!
