### ISSUE TITLE
The `onMatrixColumnAdded` event is not raised when a new matrix column is added by pressing the Enter key on the design surface

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5274]
T17025 - MatrixColumnAdded event not working if we try to create new column from survey design surface using enter key
https://surveyjs.answerdesk.io/internal/ticket/details/T17025
***
[View Demo](https://plnkr.co/edit/rnGWVD8CyZTOSKij)

The `creator.onMatrixColumnAdded` event is correctly raised if you add columns via a property grid's column editor. However, this event is not invoked if you add columns by pressing Enter in a design surface.
![image](https://github.com/surveyjs/survey-creator/assets/22372972/e590d66c-ab15-4eda-bae2-f2a14969c83e)

**Comment by JaneSjs** [comment]
The issue: if you add columns via a property grid, the `options.columns` contains a newly added column object. However, if you add a column via the design surface, the `options.columns` array doesn't contain a newly added column.
https://plnkr.co/edit/R5cMOt2bhpjwghMg

**Comment by novikov82** [comment]
> the options.columns array doesn't contain a newly added column.
This is expected behaviour. See
https://github.com/surveyjs/survey-creator/blob/master/packages/survey-creator-core/src/creator-events-api.ts#L293-L296

**Comment by JaneSjs** [comment]
TODO: update
https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onMatrixColumnAdded
