### ISSUE TITLE
Validators are broken

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#528]
### Are you requesting a feature, reporting a bug or ask a question?
Bug, related to #237; possible regression.

### What is the current behavior?
Validators don't get stored properly. 

### What is the expected behavior?
It should work.

### How would you reproduce the current behavior (if this is a bug)?
1. Go here: https://surveyjs.io/create-survey/
2. Add a single input question
3. Click the question
4. Click edit
5. Expand the validators part
6. Click `+`, then `regex`.
7. Fill the fields.
8. Click `ok` or `apply`.
9. Confirm in the JSON that the fields are not actually saved.

**Comment by tsv2013** [comment]
It should be fixed via this commit - https://github.com/surveyjs/survey-creator/commit/78ab791ca2e99c5ec2ba73f0a479ed1e76b2f8bf

**Comment by tsv2013** [comment]
Can you check it on your side?

**Comment by SamMousa** [comment]
Will do first thing tomorrow! Thanks for quick turnaround!
