### ISSUE TITLE
The Not allowed to load local resource exception is thrown on an attempt to insert a script to a form's title

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5285]
T17063 - xss script in title
https://surveyjs.answerdesk.io/internal/ticket/details/T17063

![image](https://github.com/surveyjs/survey-creator/assets/22372972/bbda13a2-7145-40d3-bbe5-52321d39bd9c)

**Comment by srop** [comment]
@novikov82  ` >"><img src="x:x" onerror="alert(document.cookie)"> ` cloud you try to ctrl+v this script . Alert cookie is still found
![Screenshot 2567-03-04 at 07 59 08](https://github.com/surveyjs/survey-creator/assets/4023392/4cf9d89b-c2e5-4c33-97ca-44346e038a62)

**Comment by novikov82** [comment]
@srop 
issue is done and closed but not released yet
you need to wait for release 1.9.133 (in the middle of this week)

**Comment by JaneSjs** [comment]
+1 T17086 - xss in title is still alert cookie
https://surveyjs.answerdesk.io/internal/ticket/details/T17086

**Comment by novikov82** [comment]
@srop We updated our site with new version about 1 hour ago. Please try again.
