### ISSUE TITLE
CK Editor and translation issues

### ISSUE THREAD

**Issue by BobKatz** [surveyjs/survey-creator#529]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
I am having two problems with the translations since using the CK Editor when creating my survey. I am using the CK Editor as shown in this [example](https://www.surveyjs.io/Examples/Editor/?id=ckeditorpropertyeditor).

1. When using the "Export to CSV" button, the file contains carriage returns as well as `<br />` tags, obviously the carriage returns are causing problems when opening the CSV file, thinking it is a new row. Is there a way for to to strip out the carriage returns before the export?

2. The textarea elements are filled with html code and not using the CK Editor, I'm guessing this could be done but I have some large surveys and I presume the loading of 500 CK Editors will cause some issues, unless there is an event that fires when showing the input?

### What is the expected behavior?
1. Exporting the data without the carriage returns.

2. A way to use CK Editor on the translation tab.

### How would you reproduce the current behavior (if this is a bug)?
Use CK Editor and add a carriage return and export the data to CSV.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
Chrome 74.0.3729.169 (Official Build) (64-bit)
* editor version:
1.0.81

**Comment by tsv2013** [comment]
> When using the "Export to CSV" button, the file contains carriage returns as well as <br /> tags, obviously the carriage returns are causing problems when opening the CSV file, thinking it is a new row. Is there a way for to to strip out the carriage returns before the export?

How can we reproduce it? I've checked our code and haven't found any <br/> tags. We add carriage returns only after each row. User translations in some cases can contain other <br/> and csv-delimeter symbols that can break CSV format. And to be honest I don't see any general solution here.

> The textarea elements are filled with html code and not using the CK Editor, I'm guessing this could be done but I have some large surveys and I presume the loading of 500 CK Editors will cause some issues, unless there is an event that fires when showing the input?

The example of CKEditor usage you mentioned in your initial post is related to survey JSON properties only. And it isn't supposed to work in the translation tab. We haven't any editor customization options for translation tab text editors. And to create hundreeds of heavy weight editors is not an option IMO.

Probably the better solution is to prepare CSV or other formatted file with translations and import them into SurveyJS Creator. @andrewtelnov what do you think?

**Comment by BobKatz** [comment]
> How can we reproduce it? I've checked our code and haven't found any 
> tags. We add carriage returns only after each row. User translations in some cases can contain other 
> and csv-delimeter symbols that can break CSV format. And to be honest I don't see any general solution here.

Apologies, I realise I didn't mention that I used CK Editor to fill in the fields (so they are full of HTML) and then went to the translations page, then when I export the file it has carriage returns.

If I can find a way to get the export working I don't need to worry about the CK Editor showing on the actual translations page :)

**Comment by tsv2013** [comment]
I've added the following property:
```
SurveyCreator.Translation.newLineDelimiter
```
by default it contains "\n"
You can replace it with any custom string, even empty

Will it help?

**Comment by BobKatz** [comment]
That my friend would be perfect, thank you.

**Comment by tsv2013** [comment]
@BobKatz It most likely will be released in the today's update
