### ISSUE TITLE
creator.onQuestionAdded event is not fired on dragging an item from a toolbox

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#5291]
The event is fired on clicking the toolbox item and on clicking on Page/Panel buttons, but it is not fired on dragging.
Here is [the example](https://plnkr.co/edit/6DYHzPnNBhwTfwgL?preview).

**Comment by JaneSjs** [comment]
+1 
T17110 - `onQuestionAdded` not firing when adding question via drag and drop
https://surveyjs.answerdesk.io/internal/ticket/details/T17110
