### ISSUE TITLE
Get an error when progressBarType property from survey

### ISSUE THREAD

**Issue by chancesmith** [surveyjs/survey-creator#5296]
### Are you requesting a feature, reporting a bug or ask a question?
bug

### What is the current behavior?
When removing the survey `progressBarType` property, an error occurs.
`Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')`

<img width="390" alt="Screen Shot 2024-03-02 at 7 00 48 PM" src="https://github.com/surveyjs/survey-creator/assets/4466585/6963863a-062f-4302-90c2-66aa4424763d">

### What is the expected behavior?
I expect the Progress Bar Type property to be removed from the property grid.

### How would you reproduce the current behavior (if this is a bug)?

Call `Serializer.removeProperty("survey", "progressBarType");`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codepen.io/chancesmith/pen/dyLPdOY

Test code

```
Survey.Serializer.removeProperty("survey", "progressBarType");
function SurveyCreatorRenderComponent() {
    const options = {
        showLogicTab: true
    };
    const creator = new SurveyCreator.SurveyCreator(options);
    creator.JSON = {};
    return (<SurveyCreator.SurveyCreatorComponent creator={creator} />);
}

const root = ReactDOM.createRoot(document.getElementById("surveyCreatorContainer"));
root.render(<SurveyCreatorRenderComponent />);
```

### Specify your

* browser: Chrome Version 120.0.6099.216 (Official Build) (x86_64)
* editor version: 
```
    "survey-creator-react": "^1.9.113",
    "survey-react-ui": "^1.9.113",
```

**Comment by andrewtelnov** [comment]
@chancesmith It is more safe to hide the property instead of removing it. It is very likely that we don't check that this property may not exist in our code in Creator. Please use the following code:
```js
const prop = Survey.Serializer.findProperty("survey", "progressBarType");
prop.visible = false;
```

Thank you,
Andrew

**Comment by JaneSjs** [comment]
@chancesmith,
You can also use the [`creator.onShowingProperty`](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onShowingProperty) event to hide unwanted settings. For more information, please visit the following demo: [Hide a Category from the Property Grid](https://surveyjs.io/survey-creator/examples/hide-category-from-property-grid/reactjs).

Should you have any further questions, please feel free to reactivate this thread.

Thanks

**Comment by chancesmith** [comment]
This is not resolved
