### ISSUE TITLE
All panel labels are hidden after removing questionTitleLocation property from survey

### ISSUE THREAD

**Issue by chancesmith** [surveyjs/survey-creator#5297]
### Are you requesting a feature, reporting a bug or ask a question?
bug

### What is the current behavior?
When removing the survey `progressBarType` property, an error occurs.

<img width="511" alt="Screen Shot 2024-03-02 at 7 11 54 PM" src="https://github.com/surveyjs/survey-creator/assets/4466585/83c54e16-9413-43f6-a0ac-ec2ff8d81798">

### What is the expected behavior?
I expect the Progress Bar Type property to be removed from the property grid.

### How would you reproduce the current behavior (if this is a bug)?

Call `Serializer.removeProperty("survey", "questionTitleLocation");`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codepen.io/chancesmith/pen/vYMEdgX

Test code

```
Survey.Serializer.removeProperty("survey", "questionTitleLocation");
function SurveyCreatorRenderComponent() {
    const options = {
        showLogicTab: true
    };
    const creator = new SurveyCreator.SurveyCreator(options);
    creator.JSON = {};
    return (<SurveyCreator.SurveyCreatorComponent creator={creator} />);
}

const root = ReactDOM.createRoot(document.getElementById("surveyCreatorContainer"));
root.render(<SurveyCreatorRenderComponent />);
```

### Specify your

* browser: Chrome Version 120.0.6099.216 (Official Build) (x86_64)
* editor version: 
```
    "survey-creator-react": "^1.9.113",
    "survey-react-ui": "^1.9.113",
```

**Comment by andrewtelnov** [comment]
@chancesmith Please hide the property instead of removing it:
`Serializer.findProperty("survey", "questionTitleLocation").visible = false;`.

Thank you,
Andrew

**Comment by JaneSjs** [comment]
@chancesmith,
You can also use the [`creator.onShowingProperty`](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onShowingProperty) event to hide unwanted settings. For more information, please visit the following demo: [Hide a Category from the Property Grid](https://surveyjs.io/survey-creator/examples/hide-category-from-property-grid/reactjs).

Should you have any further questions, please feel free to reactivate this thread.

Thanks
