### ISSUE TITLE
JSON Editor validation at disabled question types

### ISSUE THREAD

**Issue by iwollmann** [surveyjs/survey-creator#530]
### Are you requesting a feature, reporting a bug or ask a question?
Question/Bug

### What is the current behavior?
When you copy a valid JSON with a disabled question type to the JSON Editor, the editor does not show any validation, he shows the validation only if we add a JSON with a question type that no exists.

### What is the expected behavior?
Should validation not only be on the types of questions enabled?

### How would you reproduce the current behavior (if this is a bug)?
I'm using this example [Plunker](https://plnkr.co/edit/?p=preview) to test.

JSON Validation **Working**:
`{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "abc",
     "name": "question1"
    }
   ]
  }
 ]
}`

![image](https://user-images.githubusercontent.com/997343/58555666-69e10700-81f0-11e9-8e2e-45368f9ad4a3.png)

JSON Validation **Not working**:

`{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "matrix",
     "name": "question1"
    }
   ]
  }
 ]
}`

![image](https://user-images.githubusercontent.com/997343/58555817-df4cd780-81f0-11e9-904d-f11a91c8d282.png)

The questions types enabled in this example are: "text", "checkbox", "radiogroup", "dropdown".

**Comment by andrewtelnov** [comment]
@iwollmann You did not save your plunker example.
We do not have the functionality to unregister the question type in our library yet.
You may may build your own library based on our source and remove some question types from webpack indeces, in this case these question types will not be available in the library and as result they would not be registered in QuestionFactory.
You are probably just removed question types from toolbox, it is completely a different story.

Thank you,
Andrew

**Comment by iwollmann** [comment]
Hi @andrewtelnov, thanks for the answer.
This sentence answered my question:
> We do not have the functionality to unregister the question type in our library yet.

Any expected date for this feature?

**Comment by andrewtelnov** [comment]
@iwollmann From the next minor version you may use:
'Survey.ElementFactory.Instance.unregisterElement("imagepicker", true);'
It should be called before creating a Survey Creator.

Thank you,
Andrew
