### ISSUE TITLE
Multiple text name attribute to be readonly always

### ISSUE THREAD

**Issue by prasadh13** [surveyjs/survey-creator#531]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
can edit name attribute in multiple text question type

### What is the expected behavior?
Disable or add read-only property to multiple question type

### How would you reproduce the current behavior (if this is a bug)?
Add multiple text question and check the items tab as below

* browser: Chrome
* editor version: 1.0.52
![Screen Shot 2019-06-03 at 1 47 36 PM](https://user-images.githubusercontent.com/8535194/58787517-97bab700-8607-11e9-8270-f2fdf58b7871.png)

I have already added this in my code and it works for names of questions - `Survey.JsonObject.metaData.findProperty('itemvalue', "value").readOnly = true;`

Is there anything similar for the items array?

**Comment by tsv2013** [comment]
You can use the following code:
```JS
Survey
    .JsonObject
    .metaData
    .findProperty("multipletextitem", "name").readOnly = true;
```

Here is the working sample - https://plnkr.co/edit/55Vk75imFcNZfzYN15SE?p=preview

**Comment by prasadh13** [comment]
Thanks. This works. Closing the ticket.
