### ISSUE TITLE
Disable the save button

### ISSUE THREAD

**Issue by robertomcampos** [surveyjs/survey-creator#533]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?
The Save button is aways enabled

### What is the expected behavior?
Decide to enabled or disabled mode

![image](https://user-images.githubusercontent.com/5176761/59029544-ebf6ae80-8834-11e9-9000-dcd340941aa5.png)

**Comment by tsv2013** [comment]
The "Save" button visibility is controlled by the following code:
```JS
public set saveSurveyFunc(value: any) {
    this.saveSurveyFuncValue = value;
    this.koShowSaveButton(value != null && !this.isAutoSave);
  }
```
E.g. to hide it you can set https://surveyjs.io/Documentation/Survey-Creator/?id=surveycreator#isAutoSave property to true

**Comment by robertomcampos** [comment]
In my scenario, the user can see this page , but can not save anything.

**Comment by tsv2013** [comment]
You can just assign undefined to `creator.saveSurveyFunc` - it will hide the button and disable save operation

**Comment by tsv2013** [comment]
BTW, SurveyJS Creator has the https://surveyjs.io/Documentation/Survey-Creator/?id=surveycreator#readOnly property

**Comment by robertomcampos** [comment]
> creator.saveSurveyFunc

Awesome! Thank you.
