### ISSUE TITLE
Show and hide properties based on values other property(ies) in Element Editor and Property Grid

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#534]
Let's say we want to add a dateFormat property into text question. However, it makes sense only when the question.inputType equals "date" or "datetime" or "datetime-local".
It would be nice to show dateFormat property only when these values are set into inputType in Question Editor.
Propose syntaxes:
` Serializer.addProperty("text", 
   {name: "dateFormat", dependsOn: ["inputType"],
     visibleIf: function(obj) { return obj.inputType == "date" 
            || obj.inputType == "datetime"obj.inputType == "datetime-local";} 
});`

Question Editor / Property Editor should check visibleIf function on changing inputType, and if the value is different hide/show dateFormat property.

As alternative dependsOn can be a string. It means that both: 
`dependsOn: ["inputType"]` and `dependsOn: "inputType"` are valid.

**Comment by SamMousa** [comment]
> As alternative dependsOn can be a string.

Personally I prefer not to have mixed types; they don't really help anyone and with IDEs the support is usually better if specific types can be inferred / annotated.
If the only advantage of allowing strings is that it saves you from writing `[]` I'd propose not supporting strings.

**Comment by andrewtelnov** [comment]
@SamMousa In most cases, like 90+% a property will depends on one property only. But we can do not support string for now. It is not a big deal to add it later if we see people by mistake set string instead of array.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Merged elementeditor_refactor branch.
Question/Panel/Page/Survey Editors creates a copy of the editing object and edit this copied element. On changing property the changes apply into copied element immediately. As result a property editor may get the correct/updated value of another property.
On pressing Apply/OK buttons changed properties of the copied objects applied into the origional object. On pressing Cancel just nothing happens.

Ready to work on the "Show/Hide properties based on value(s) of other property(ies)".

**Comment by andrewtelnov** [comment]
The functionality is implemented.

**Comment by andrewtelnov** [comment]
The [example](https://surveyjs.io/Examples/Survey-Creator/?id=dependsonproperties) is added.
