### ISSUE TITLE
Implement themes for SurveyJS Creator

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#5377]
- [ ] light restyling #5135 
- [ ] sevral themes (including high contrast)
- [ ] UI for theme selection
- [ ] #3652 
- [ ] #3754

**Comment by mikeamelin** [comment]
Button — https://www.figma.com/file/i6Lpc7zkjHtso2oXZV97fo/*-Components?type=design&node-id=2046-19865&mode=dev

[Variables.zip](https://github.com/surveyjs/survey-creator/files/14865443/Variables.zip)

**Comment by dmitry-kurmanov** [comment]
current tasks

- [ ] new pallet
- [ ] restyling

**Comment by dmitry-kurmanov** [comment]
- [ ] toolbox
- [ ] text editor (pg)
- [ ] checkbox (pg)
- [ ] page-navigator
- [ ] topbar: tabbed-menu
- [ ] topbar: buttons (toolbar)
