### ISSUE TITLE
Image Picker - Enhance UI to help users implement a Video Picker question

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5378]
Image Picker doesn't visualize videos. Please update the Choices property grid category.
![image](https://github.com/surveyjs/survey-creator/assets/22372972/23f89590-7eb6-406c-97a0-c7c7ce395946)

```
{
 "title": "'Asking' is a powerful tool—as long as it remains in your hands",
 "description": "Built to empower enterprises to choose full integration and security",
 "logo": "https://api.surveyjs.io/private/Surveys/files?name=bdf16c7e-fa1e-4e31-9d82-a6df1982c224",
 "logoWidth": 200,
 "logoHeight": 80,
 "logoFit": "cover",
 "logoPosition": "right",
 "pages": [
  {
   "name": "all",
   "elements": [
    {
     "type": "panel",
     "name": "panel2",
     "elements": [
      {
       "type": "image",
       "name": "surveyJS-integration-tutorial",
       "imageLink": "https://youtu.be/RAXo6pzOczQ",
       "contentMode": "youtube",
       "imageHeight": 450,
       "imageWidth": 800
      }
     ],
     "description": "Refer to the following YouTube video to learn how to embed surveys and forms in your JavaScript application in minutes."
    },
    {
     "type": "imagepicker",
     "name": "question1",
     "choices": [
      {
       "value": "Image 1",
       "imageLink": "https://youtu.be/RAXo6pzOczQ"
      },
      {
       "value": "Image 2",
       "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/giraffe.jpg"
      },
      {
       "value": "Image 3",
       "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/panda.jpg"
      },
      {
       "value": "Image 4",
       "imageLink": "https://surveyjs.io/Content/Images/examples/image-picker/camel.jpg"
      }
     ],
     "imageFit": "cover"
    }
   ],
   "title": "Full integration is simple"
  }
 ],
 "showNavigationButtons": "none",
 "widthMode": "static",
 "width": 900
}
```

**Comment by JaneSjs** [comment]
The uploaded video doesn't appear in an Image Picker:
https://plnkr.co/edit/M46XLx6FrFjkfLHM

![Image](https://github.com/surveyjs/survey-creator/assets/22372972/a67e67ff-75e3-4fd1-b95f-cef870aaafc7)

**Comment by JaneSjs** [comment]
![Image](https://github.com/surveyjs/survey-creator/assets/22372972/d4bf14af-70c0-40a2-bfaf-7eb93ba71cbe)

_By default, an image picker allows users to create image items. To implement a video selector, switch the Image Picker's Content Type to Video._

![Image](https://github.com/surveyjs/survey-creator/assets/22372972/c5e1f303-2ce5-4254-a473-113b3bfa2ae5)

**Comment by ElenaGorbatkova** [comment]
Please update the helper text for the Content mode property of the Image picker (under General). The Auto option ceased to exist.
Current version:
![image](https://github.com/surveyjs/survey-creator/assets/102306951/1c80ad48-f3de-407c-bedf-c884333749b0)


Choose between "Image" and "Video" to set the content mode of the file picker. If "Image" is selected, ensure that all options provided are image files. Similarly, if "Video" is selected, ensure that all options are **direct links** to video files. Please note that YouTube links are not supported for video options.

**Comment by ElenaGorbatkova** [comment]
@RomanTsukanov For the Image question, please add the following helper text to the Image or Video file URL:
![image](https://github.com/surveyjs/survey-creator/assets/102306951/3d422a0a-264c-4b5d-a1aa-dfb17d688b15)
A free survey can accept up to 64KB of files in total. If you wish to have an unlimited total size for all uploaded files, including images and videos, we recommend self-hosting [Survey Creator](https://surveyjs.io/survey-creator).

**Comment by ElenaGorbatkova** [comment]
@RomanTsukanov For the **Image picker question**, please add the following helper text to the Image or Video file URL option property:

![image](https://github.com/surveyjs/survey-creator/assets/102306951/397be411-3281-4574-8d68-c3b64a79c5de)

A free survey can accept up to 64KB of files in total. If you wish to have an unlimited total size for all uploaded files, including images and videos, we recommend self-hosting [Survey Creator](https://surveyjs.io/survey-creator).
