### ISSUE TITLE
Custom Question Type - How to register custom properties of an expression type

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5386]
T17578 - Custom Component not getting dynamic value on property
https://surveyjs.answerdesk.io/internal/ticket/details/T17578

**Comment by andrewtelnov** [comment]
@RomanTsukanov @JaneSjs It should be the following code added into constructor:
`this.addExpressionProperty("productIdExpression", (obj: Base, res: any) => {  this.productId = res; });`

Thank you,
Andrew

**Comment by JaneSjs** [comment]
I updated the Descriptive element demo and added a captionExpression property. It allows users to define an expression for the Caption property.
[View CodeSandbox](https://codesandbox.io/p/sandbox/xenodochial-roman-wzkpqw?file=%2Fsrc%2FSurveyCreatorComponent.jsx%3A1%2C1-190%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt5k80oq0006356h5431y192%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt5k80oq0002356h8fp2gz39%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt5k80oq0003356hbt7s8ayh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt5k80oq0005356hvp3t5296%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt5k80oq0002356h8fp2gz39%2522%253A%257B%2522id%2522%253A%2522clt5k80oq0002356h8fp2gz39%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluu0zpz00002356h21sezvgn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FSurveyCreatorComponent.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A190%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522activeTabId%2522%253A%2522cluu0zpz00002356h21sezvgn%2522%257D%252C%2522clt5k80oq0005356hvp3t5296%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt5k80oq0004356hmj0j3gcu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clt5k80oq0005356hvp3t5296%2522%252C%2522activeTabId%2522%253A%2522clt5k80oq0004356hmj0j3gcu%2522%257D%252C%2522clt5k80oq0003356hbt7s8ayh%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clt5k80oq0003356hbt7s8ayh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A0%257D)

**Comment by JaneSjs** [comment]
@RomanTsukanov suggested another option to update the documentation.
