### ISSUE TITLE
Update an empty survey and empty page placeholder on a mobile/tablet

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5398]
On a mobile/tablet no toolbox is available within SurveyJS Creator. Please update a placeholder which appears for an empty survey and empty page.
![image](https://github.com/surveyjs/survey-creator/assets/22372972/3b6d5b39-3dbd-44cf-b276-a2a73c18aedf)
![image](https://github.com/surveyjs/survey-creator/assets/22372972/5a4de311-6c46-47b2-acb0-9d9c3c3594dd)

**Comment by ElenaGorbatkova** [comment]
This form is currently empty.
Click the "Add Question" button below to start creating your form.

This page is currently empty.
Click the "Add Question" button below to add a new form element.
