### ISSUE TITLE
I take licensing of survey builder but in order to upload large file giving data into  base64

### ISSUE THREAD

**Issue by shahbaazaliSatschel** [surveyjs/survey-creator#5401]
I take licensing of survey builder but in order to upload large file giving data into  base64. 
How could get only url of instead of base64 and alos unable to view  pdf view.

```
import * as Survey from 'survey-react';
import { SURVEY_KEY } from 'constants/common';


Survey.setLicenseKey(SURVEY_KEY);
```

My setup

**Comment by andrewtelnov** [comment]
@shahbaazaliSatschel Please contact [our technical forum](https://surveyjs.answerdesk.io/) to get the help with the license key.

Thank you,
Andrew

**Comment by shahbaazaliSatschel** [comment]
Thanks @andrewtelnov .
