### ISSUE TITLE
Adorner actions appear differently (minimized or not) for questions 

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5411]
I reproduce the issue as follows:
* Add a Text entry field;
* Change the input type to Email. You can see that adorner actions are not minimized.
* Now, duplicate the entry field. A newly created question has minimized adorner actions.

https://github.com/surveyjs/survey-creator/assets/22372972/7cb5a1f6-8c87-4051-8e9d-6d503b142db8

**Comment by tsv2013** [comment]
Was trying to reproduce it in https://surveyjs.io/create-free-survey , but it works ok for me. Any special settings? Another framework?

**Comment by JaneSjs** [comment]
Cannot reproduce the issue with the latest version either.
