### ISSUE TITLE
Is it possible to auto-change dropdown choice values from creator?

### ISSUE THREAD

**Issue by mgoetz-nerdery** [surveyjs/survey-creator#5418]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question

### What is the current behavior?
When you update the choices in the center main creator view instead of the property grid menu, it only changes the name of the choice, not the value.

For instance, in this screenshot, the user has changed the first choice to "Name 1" in the main creator view; the name of the choice has changed, but the value has not.

Our users have found this confusing because it's much easier to change the main creator view.

<img width="1255" alt="6bc9387c-e49c-46df-a62b-649ca6181ae8" src="https://github.com/surveyjs/survey-creator/assets/32200555/8b233b7c-b37e-4c01-8d97-dfecbdbee52e">

### What is the expected behavior?

Is it possible to change or configure this behavior so that the value of the choice is also changed from the main creator view?

### Specify your

* browser: latest Chrome
* editor version: 1.9.136

**Comment by andrewtelnov** [comment]
@mgoetz-nerdery Sure you can use [creator.inplaceEditForValues](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#inplaceEditForValues) property.
`creator.inplaceEditForValues = true;`.

Thank you,
Andrew

**Comment by mgoetz-nerdery** [comment]
Thank you!  That addressed my issue.
