### ISSUE TITLE
showModalPropertyEditor in IPropertyGridEditor return value is not used

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#5420]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
I'm trying to add a custom property grid editor. For this I'm implementing `IPropertyGridEditor`, which is defined like this:
```ts
export interface IPropertyGridEditor {
    fit(prop: JsonObjectProperty, context?: string): boolean;
    isDefault?: () => boolean;
    getJSON(obj: Base, prop: JsonObjectProperty, options: ISurveyCreatorOptions, propGridDefinition?: ISurveyPropertyGridDefinition): any;
    showModalPropertyEditor?: (editor: IPropertyGridEditor, property: JsonObjectProperty, question: Question, options: ISurveyCreatorOptions) => IPropertyEditorSetup;
    onCreated?: (obj: Base, question: Question, prop: JsonObjectProperty, options: ISurveyCreatorOptions, propGridDefinition?: ISurveyPropertyGridDefinition) => void;
    onSetup?: (obj: Base, question: Question, prop: JsonObjectProperty, options: ISurveyCreatorOptions) => void;
    validateValue?: (obj: Base, question: Question, prop: JsonObjectProperty, val: any) => string;
    onAfterRenderQuestion?: (obj: Base, prop: JsonObjectProperty, evtOptions: any) => void;
    createPropertyEditorSetup?: (obj: Base, prop: JsonObjectProperty, question: Question, options: ISurveyCreatorOptions) => IPropertyEditorSetup;
    isPropertyEditorSetupEnabled?: (obj: Base, prop: JsonObjectProperty, question: Question, options: ISurveyCreatorOptions) => boolean;
    canClearPropertyValue?: (obj: Base, prop: JsonObjectProperty, question: Question, options: ISurveyCreatorOptions) => boolean;
    clearPropertyValue?: (obj: Base, prop: JsonObjectProperty, question: Question, options: ISurveyCreatorOptions) => void;
    onValueChanged?: (obj: Base, prop: JsonObjectProperty, question: Question) => void;
    onValueChanging?: (obj: Base, prop: JsonObjectProperty, question: Question, options: any) => void;
    onMasterValueChanged?: (obj: Base, prop: JsonObjectProperty, question: Question) => void;
    onAddIntoPropertyValue?: (obj: Base, prop: JsonObjectProperty, question: Question, options: ISurveyCreatorOptions) => void;
    onMatrixCellCreated?: (obj: Base, options: any) => void;
    onMatrixCellValueChanged?: (obj: Base, options: any) => void;
    onMatrixAllowRemoveRow?: (obj: Base, row: any) => boolean;
    onGetQuestionTitleActions?: (obj: Base, options: any, creator: ISurveyCreatorOptions) => void;
    onUpdateQuestionCssClasses?: (obj: Base, options: any) => void;
}
```

### What is the expected behavior?
The optional function `showModalPropertyEditor` has a return type specified of `IPropertyEditorSetup`. But the actual result is never used. The only times it seems to be used it when it is passed up the call stack in case of recursive calls.

The initial call sites are located here:
#### Call site 1
https://github.com/surveyjs/survey-creator/blob/master/packages/survey-creator-core/src/property-grid/index.ts#L437

Note that the definition of an action function in `IAction` is actually this: `action?: (context?: any) => void;`.

#### Call site 2
https://github.com/surveyjs/survey-creator/blob/d77511976d7692f3253ee61df854f926bb22f3a1/packages/survey-creator-core/src/property-grid/values.ts

Result is not used

**Comment by SamMousa** [comment]
Did it break something?

**Comment by andrewtelnov** [comment]
@SamMousa I merged your PR into master, but we have to revert it back. We need the return value for our Unit Tests.

Thank you,
Andrew

**Comment by SamMousa** [comment]
That seems like a code smell. If the return value is not used it should not matter for tests.
It is an implementation detail that you're testing... 
Could you remove the return type from the interface? Since you may change from void to something else according to LSP (but not the other way around).
You're not testing interfaces after all, you're testing concrete implementations.

**Comment by SamMousa** [comment]
https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgEJwM4oN4ChkHIDmEYAygPYC2pAFqEQBQCUAXMgG4XAAmuAvrlyhIsRCgCiAD0ggeEHsggyIcjGkw58hEuWp0GLdiACuVAEbQA3AKEIANpnUBhCiARRSKYFQAO9iBpwdXQsZDxCYlJKGjB6ECY2ZFMLaHDtSIJPMBMoEGQAVhtIwUEgA

**Comment by andrewtelnov** [comment]
@SamMousa It is a discussable opinion. I personally use TDD to write code and unit tests for me is the same code.

Thank you,
Andrew

**Comment by SamMousa** [comment]
Fair enough, but that is just for your concrete implementation.
You are forcing outside code that just wants to implement the minimum interface to use this as well.

My proposal is this:
- You specify in the interface what your production code needs
- You implement your concrete code with what your tests need
- Your tests may have extra requirements on your implementation.
```ts
interface Base {
    getSomething(): void
}

class Concrete implements Base {
    getSomething(): number {
        return 5;
    }
}
```

This would work fine right? You can test your `Concrete` class to see that it returns 5, but if I create my own implementation I don't have to make up a value.

**Comment by andrewtelnov** [comment]
@SamMousa I will take a look at it later. To be honest, it is not that much important. You can return undefined for your case.

Thank you,
Andrew

**Comment by SamMousa** [comment]
> You can return undefined for your case.

I know, but the whole point of Typescript is lost in this case. You define the interface and I want to implement it.
Now I have to look through the whole library code to know if I really have to implement it or not. Also, if you change your code in any release to no longer allow for `undefined` my code will break and there's no way for me to detect it.

By changing the interface to what it should be you solve this problem. If in the future you need a real return value and I don't have one my compilation will fail due to a Typescript error.

I'm happy to create a new PR that won't break your tests, but the way you're going about it now is just wrong and only works because you don't actually have typescript warnings enabled...
Just returning `undefined` is not allowed when you specify a return type.  

I hope you understand why it is a problem for integrators and contributors if the self-describing part of your code is not actually describing things properly.. I'm trying to contribute but there are enormous barriers that can be reduced by using the available tooling.

**Comment by andrewtelnov** [comment]
@SamMousa The problem that several visual regression tests fail as well. I can check, but I am afraid that we will see some functional tests fail as well if unit tests were passed. It is probably that survey-creator-* (react/angular/vue/knockout) packages are depends on this return value.

Thank you,
Andrew
