### ISSUE TITLE
choicesLazyLoadEnabled can't config in creator

### ISSUE THREAD

**Issue by AkaHanshan** [surveyjs/survey-creator#5439]
### Are you requesting a feature, reporting a bug or ask a question?
reporting a bug

### What is the current behavior?
can't config `choicesLazyLoadEnabled` in creator property grid

### What is the expected behavior?
can select choicesLazyLoadEnabled in property grid

### How would you reproduce the current behavior (if this is a bug)?
- create dropdown type question
- open property grid 
- select choicesByUrl
- didn't see choicesLazyLoadEnabled option

#### Provide the test code and the tested page URL (if applicable)

I try to manually add the property to grid but it also doesn't work:

```
  Serializer.addProperty("dropdown", {
    name: "choicesLazyLoadEnabled",
    type: "boolean",
    default: false,
    isRequired: false,
    category: "choicesByUrl",
    visibleIndex: 3,
    readOnly: false,
  });
```

![image](https://github.com/surveyjs/survey-creator/assets/48984202/2eb2f651-3788-4ee5-a459-1968eef4969f)

Tested page URL:

Test code
[code](https://codesandbox.io/p/sandbox/icy-wave-llw93k?file=%2Fsrc%2Fsurvey_json.js%3A16%2C1)

### Specify your

* browser: chrome
* editor version: 1.9.114

**Comment by andrewtelnov** [comment]
@AkaHanshan You have to add it into another class:
```js
  Serializer.addProperty("choicesByUrl", {
    name: "choicesLazyLoadEnabled",
    type: "boolean",
    visibleIndex: 3
  });
```
Your [updated example](https://codesandbox.io/p/sandbox/cocky-tree-kyj7n8?file=%2Fsrc%2FSurveyCreatorComponent.jsx%3A15%2C1-20%2C1).
Please note, that you have access to it as `question.choicesByUrl.choicesLazyLoadEnabled`.

Thank you,
Andrew

**Comment by AkaHanshan** [comment]
It works , Thanks @andrewtelnov
