### ISSUE TITLE
Newly created columns have blank name attribute

### ISSUE THREAD

**Issue by prasadh13** [surveyjs/survey-creator#544]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
When I create a new column, the name attribute is not filled as the default ones are.
The user control for editing the name has been disabled. So user cannot edit it and hence cannot move further. Is there a way to auto update the name field. Please see the attached image.
![WhatsApp Image 2019-06-14 at 2 23 06 PM](https://user-images.githubusercontent.com/8535194/59498588-52be3c80-8eb3-11e9-93a1-98b047e4165d.jpeg)

### How would you reproduce the current behavior (if this is a bug)?
Create a new multiple choice matrix question and add a new column

**Comment by andrewtelnov** [comment]
@prasadh13  We will write a code that will generate the next column name automatically. It will be "Column 4" in your case.

**Comment by prasadh13** [comment]
@andrewtelnov thank you for the prompt reply.

**Comment by andrewtelnov** [comment]
The functionality will be available in the next minor. We will release it on the next week.

Thank you,
Andrew
