### ISSUE TITLE
Extending Dropdown breaks the rendering in Logic tab

### ISSUE THREAD

**Issue by digiscapeuk** [surveyjs/survey-creator#5440]
I'm testing out Creator ahead of our Co making a purchase and think I've hit a bug.

I wanted to extend the dropdown question type to add a new property and some custom logic that would run in the question's onPropertyChanged event.

When I follow the samples to extend existing widgets the logic tab breaks as shown:

![image](https://github.com/surveyjs/survey-creator/assets/3006997/f17d914c-7c6c-4428-9873-a241f281ffa8)

There are no console errors reported - the dropdowns continue to work normally in Creator/Preview/Survey mode. The only place I observe a problem is the logic tab.

I'm using the code hosted on unpkgd so it will be the latest versions of all files.  I'm using the Knockout code bases.

**Comment by andrewtelnov** [comment]
@digiscapeuk Could you please create an example, for example in plunker with your code?
You can go to any our [Creator example](https://surveyjs.io/survey-creator/examples/free-nps-survey-template/reactjs), click on "Edit in Plunker" dropdown  and then select knockout.
After that you can modify the example and post it here.
It is impossible to tell what is going on by the picture.
I guess something wrong with dropdown styles in the logic tab. Why does it happen, I have no idea.

Thank you,
Andrew

**Comment by digiscapeuk** [comment]
Example can be viewed [here](https://plnkr.co/edit/6o0aoA1fMCjlak2L).  

If you add a dropdown question to the survey and preview you can see the dropdown behaves normally & the new property is showing up.

On the Logic tab if you add a new rule or edit existing conditions the dropdowns are not rendering correctly.

**Comment by andrewtelnov** [comment]
@digiscapeuk Yes, I see the issue. What is the final goal? I guess you want to override the dropdown rendering. Is it correct? There are many ways of doing it. This approach is the old one. You are modifying DOM elements after rendering.

Thank you,
Andrew

**Comment by digiscapeuk** [comment]
For some dropdowns I'm adding extra config properties that allow me to handle the value changed event to look up additional data for the selected item and map that data in to other questions.

E.g. I can use your item values to add a list of extra items to map.

In a perfect world I could pull these values from the cached look up list but it appears to me that the web service result is not retained, only a key values list. I've therefore added a call back on value changed to get a single row of data (similar to the code sample for getting the display name on a lazy load list).

![image](https://github.com/surveyjs/survey-creator/assets/3006997/11ea00a9-194e-4f9f-8566-ef295cfc70e4)

I've hacked this together by looking at the custom RTF widget editor on your site as I was learning my way through the API. 

I imagine I can achieve the same by just conditionally adding listeners to the property changed events for dropdowns that have my custom property values set.  I don't need to override the widget as in this example I'm not changing the dropdown markup.

**Comment by digiscapeuk** [comment]
OK - I've re-worked to avoid customising the dropdown widget and just add handlers to questions that have my extra config.

That restores the logic page to normal.

I'm happy to close this issue off if this since I can solve the issue another way.

**Comment by andrewtelnov** [comment]
You may want to put your code into a [component](https://surveyjs.io/form-library/documentation/customize-question-types/create-specialized-question-types). It has several callback function that you can handle. We can add an additional callback function if we see there is a need in it.

Thank you,
Andrew

**Comment by digiscapeuk** [comment]
Thanks - I'll take a look at the component approach to wrap up the customisations.
