### ISSUE TITLE
Theme Editor - Introduce an option to modify the error message appearance colors

### ISSUE THREAD

**Issue by SjsJane** [surveyjs/survey-creator#5450]
T17946 - Themes - settings for modifying error messages
https://surveyjs.answerdesk.io/internal/ticket/details/T17946
***
This may be useful when a survey has a specific background color and the error message becomes slightly to distinguish.
For instance: [View Demo](https://plnkr.co/edit/lujfeg2Qj5ET4iVN).
![image](https://github.com/surveyjs/survey-creator/assets/168413195/572d72f7-6983-4b98-b570-5c1a827d8646)

**Comment by mikeamelin** [comment]
https://www.figma.com/design/SSMZUWJve1zuMSeA5E5YpA/CTR--%3E-Creator-Preview?node-id=2379-20711
