### ISSUE TITLE
File and signature pad content in the result widget in the Test tab

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#5454]
The Base64 string looks bad in the result widget in the Test tab.
Here is the related issue in [SurveyJS technical forum](https://surveyjs.answerdesk.io/internal/ticket/details/T17965).

**Comment by SjsJane** [comment]
Couldn't reproduce the issue on the following demo: [View Demo](https://surveyjs.io/survey-creator/examples/survey-creator-interface-localization/jquery).
![image](https://github.com/surveyjs/survey-creator/assets/168413195/c410a24e-69b7-414d-a40c-6e277558924e)
