### ISSUE TITLE
SurveyJs Creator Scrolltop

### ISSUE THREAD

**Issue by albertoVieiraNeto** [surveyjs/survey-creator#546]
### Are you requesting a feature, reporting a bug or asking a question?
reporting a bug

### What is the current behavior?
when dragging one item from the toolbox into the page, for some reason the page scrolls to the top, 

### What is the expected behavior?
the scroll to stay in its current position, this should be configurable.

### How would you reproduce the current behavior (if this is a bug)?
go to https://surveyjs.io/Examples/Survey-Creator?id=localization&theme=darkblue
scroll to the bottom then drag the rating item into the page, the scroll will snap to the top of the page.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://surveyjs.io/Examples/Survey-Creator?id=localization&theme=darkblue
Test code
none
```
none

```

### Specify your

* browser: Edge Dev
* browser version: 76
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Transferred to the corresponding repo

**Comment by tsv2013** [comment]
I've opened this sample in a separate window (this is how the curvey creator will be used) and it works ok for me - https://surveyjs.io//Examples/CreatorSinglePage?id=localization&theme=darkblue

I followed the given steps. Do I miss something?

**Comment by albertoVieiraNeto** [comment]
the link you posted seems to be different then what i posted (notice the second backlash after surveyjs.io).I only noticed this behavior when using the component wrapped inside other components/divs like for example the survey js site where the scroll is significantly larger.

see the gif below for a example:
![surveyjs-creator-scrollbug](https://user-images.githubusercontent.com/25618042/59694633-57d70080-91bf-11e9-884e-33e63066e01b.gif)

**Comment by tsv2013** [comment]
Yes, I've used different link. But I shinked the window vertically to get vertical scroll. And then drop the item from toolbox. And it worked ok for me.

We'll check what can cause such a behaviour on our site.

**Comment by albertoVieiraNeto** [comment]
i used your site as an example but this also happens when the component is used inside a bootstrap modal or on a page with a large enough scroll, currently i'm testing this component inside a tab on a angular application.

**Comment by andrewtelnov** [comment]
[Duplicated](https://github.com/surveyjs/survey-creator/issues/601).

Thank you,
Andrew
