### ISSUE TITLE
Unhandled Runtime Error while drag and drop on mobile

### ISSUE THREAD

**Issue by AmirhoseinHesami** [surveyjs/survey-creator#5466]
### Are you requesting a feature, reporting a bug or ask a question?

 reporting a bug

### What is the current behavior?

I am using surveyjs in my latest Nextjs 14.2.3 app. on mobile devices when you add two or more questions and then if you try to use drag and drop to sort the questions the Unhandled Runtime Error occurs. the error is : "TypeError: Cannot read properties of undefined (reading 'setAttributeNS')"

https://github.com/surveyjs/survey-creator/assets/86534843/fb11f371-a44a-4a98-87e3-6c9732aeb5bf

* browser: android chrome (124.0.6367.113)
* library version: latets version of survey-react-ui (1.10.2)

**Comment by JaneSjs** [comment]
Hello @AmirhoseinHesami,
Thank you for reaching out. I tested a SurveyJS Creator v1.10.2 on Android, however, didn't reproduce the issue.
I would appreciate it if you test [this demo](https://plnkr.co/edit/37EHMofEnbUue5br) on your end and let me know whether the issue occurs on your end.

Thanks

**Comment by JaneSjs** [comment]
Hello @AmirhoseinHesami,
We placed the following PR to fix styling of a drag-drop question icon: https://github.com/surveyjs/survey-creator/pull/5492. Once the new maintenance update is available, I would recommend that you upgrade and check to see if the icon appears correctly and whether the `TypeError: Cannot read properties of undefined (reading 'setAttributeNS')` exception remains. Unfortunately, we couldn't reproduce this failure on our end, so we would appreciate if you let us know how it goes on your end after the upgrade.

Thanks

**Comment by JaneSjs** [comment]
Hello @AmirhoseinHesami,
Unfortuntely, we haven't heard for you in a while. If the issue persists or you have any further questions, please feel free to reopen this thread or submit a ticket at [help desk](https://surveyjs.answerdesk.io/ticket/list?preset=mytickets).

Thank you
