### ISSUE TITLE
Not working the delete button on dynamic matrix

### ISSUE THREAD

**Issue by riyaSatschel** [surveyjs/survey-creator#5483]
### Are you requesting a feature, reporting a bug or ask a question?
The user should be able to click on the Delete button in the Question of Dynamic matrix.

### What is the current behavior?
The user is not able to click on the Delete button in the Question of Dynamic matrix.
Please check: https://prnt.sc/Z3QhvjrQ0Gxi

### What is the expected behavior?
The user should be able to click on the Delete button in the Question of Dynamic matrix.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by JaneSjs** [comment]
Hello @riyaSatschel,
The Delete button isn't suppose to work within a design surface. The Delete button allows respondents to remove rows in preview/survey runner. At design time, you can add or remove rows using the corresponding Rows collection editor within a property grid.

Let me know if you have further questions.
