### ISSUE TITLE
Survey Creator White Label

### ISSUE THREAD

**Issue by marcio** [surveyjs/survey-creator#5494]
### Asking a question:

Hi there, I'm looking for examples and documentation on how to white-label the survey creator UI. This is not about showing or hiding tabs, like the logic tab, but more specific UI changes, like colours, padding, and dark mode at the survey creator.
Is it possible without overriding the CSS?

TIA.

**Comment by JaneSjs** [comment]
Hello @marcio,
If you wish to customize the SurveyJS creator's branding to match your brand identity, you can do so by customizing the creator CSS rules. Please refer to the following demo to learn how to enable the dark mode: [Custom Theme using CSS variables](https://surveyjs.io/survey-creator/examples/edit-user-interface-theme-with-custom-css/).

Should you have any further questions, please let us know.
