### ISSUE TITLE
US Zip Code Input Masking

### ISSUE THREAD

**Issue by RA-Work-A** [surveyjs/survey-creator#550]
### Are you requesting a feature, reporting a bug or ask a question?

Feature/Questoin

### What is the current behavior?
Lacking input masking for US Zip Codes (5 or 9 digit)

### What is the expected behavior?

using inputMask:zip allows for either a 5 or 9 digit us zip code to be masked. 

### How would you reproduce the current behavior (if this is a bug)?

attempt to mask an input field with "zip"

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here
{
                                "title": "Zip Code",
                                "name": "Addreess_Zip",
                                "inputType": "text",
                                "placeHolder": "xxxxx-xxxx",
                                "isRequired": true,
                                "inputMask" : "zip"
                            }

### Specify your

* browser:
* editor version:
1.0.93

**Comment by andrewtelnov** [comment]
@RA-Work-A We do not have out of the box, but we do have a mask custom widget (surveyjs plug-in for third-party widget libraries). Here is the [example](https://surveyjs.io/Examples/Library/?id=custom-widget-inputmask).

Thank you,
Andrew
