### ISSUE TITLE
Request - Mode that automatically updates "value" field of choice/question when "text" is updated (Survey Creator)

### ISSUE THREAD

**Issue by GregEPersonal** [surveyjs/survey-creator#5502]
### Are you requesting a feature, reporting a bug or ask a question?
This is a feature request to create a mode or ability to automatically update the value of a choice or question when the text is updated. Ideally, this would occur only if the value field had not been updated manually. 

Reasoning: For non-power users, the "Value" field is unintuitive and not helpful. They'd prefer to view the choice or question by the actual text they wrote in. "Item 1" and "Question9" aren't helpful or intuitive, especially when compared with the question text which is so descriptive.

### What is the current behavior?
When you update the text of a question or choice, the value stays at the default value ("Item 1" or Question 9")

### What is the expected behavior?
Ideally, when you update the text of a question or choice, the value would update to that text. Optionally, it could be truncated, or exclude certain characters. If the value is manually updated, it is no longer overridden.

**Comment by andrewtelnov** [comment]
@GregEPersonal It is already in the library.
1) set "inplaceEditForValues" Creator option attribute to `true`
2) hide text property for "itemvalue" class.
```js
    //Hide text property from editing in choices/rows/columns and etc.
    Survey.Serializer.findProperty("itemvalue", "text").visible = false;
    const options = {
        //Tells to edit value instead of text in inplace editing
        inplaceEditForValues: true,
        showLogicTab: true
    };
    const creator = new SurveyCreator.SurveyCreator(options);

```

Here is [the working example](https://plnkr.co/edit/VwpAtoEf608V4cNb).

Thank you,
Andrew

**Comment by GregEPersonal** [comment]
Amazing, thank you. That solves this.
