### ISSUE TITLE
VisibleIf and enableIf properties are not visible in popup editor

### ISSUE THREAD

**Issue by optonet** [surveyjs/survey-creator#551]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug with the last version 1.0.93.

### How would you reproduce the current behavior (if this is a bug)?

If I select a dropdown question and then go to "Choices" and press the "Edit" button of any of the choices, the program does not show the code conditions for "Visible If" anymore. The window has just disappeared, and I cannot access the conditions I introduced in the previous version of SurveyJS.

Please, see the image attached.

Thank you

![v1 0 93](https://user-images.githubusercontent.com/52077412/59929393-a7743100-9438-11e9-86ad-b2cb23b574d1.jpg)

**Comment by tsv2013** [comment]
Fix will be available in the nearest update
