### ISSUE TITLE
Cannot close Image Picker edit screen

### ISSUE THREAD

**Issue by Lordchapter** [surveyjs/survey-creator#552]
### Are you requesting a feature, reporting a bug or asking a question?
bug

### What is the current behavior?
Pressing cancel while editing an image picker will lock the screen and the "Name" value will change to:
function c(){if(0<arguments.length)return c.tb(c[E],arguments[0])&&(c.ga(),c[E]=arguments[0],c.fa()),this;a.l.oc(c);return c[E]}

### What is the expected behavior?
the edit window closes

### How would you reproduce the current behavior (if this is a bug)?
- Add an image picker in the creator
- Click on edit
- Click cancel
- Value of "Name" is changed to "function c(){if(0<arguments.length)return c.tb(c[E],arguments[0])&&(c.ga(),c[E]=arguments[0],c.fa()),this;a.l.oc(c);return c[E]}"

![image](https://user-images.githubusercontent.com/2069264/59975792-5bea9000-95bc-11e9-8b42-da1aadd1e1cb.png)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/Examples/Survey-Creator/

### Specify your

* browser: Chrome / Edge / Firefox
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): I think the creator uses knockout?
* surveyjs version:1.0.94

**Comment by tsv2013** [comment]
@andrewtelnov I've not managed to reproduce it right now. Probably it was related to the just fixed syntax error on editor example pages...

**Comment by tsv2013** [comment]
@andrewtelnov Reproduced. Need to click cancel or try close via cross sign in the top right corner.
```JS
public getLayoutType(): string {
    if (!!this.parent) return this.parent.getChildrenLayoutType(); // this.parent is an observable
    return "row";
  }
```

**Comment by andrewtelnov** [comment]
@tsv2013 Since after our refactoring in Elemenent/Question Editor when we are using the object copy, the reset is not needed. I have just remove it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@Lordchapter The issue is fixed. We will include the fix in the next minor update that we will release on this week.

Thank you,
Andrew

**Comment by Lordchapter** [comment]
Thank you for your quick response!
