### ISSUE TITLE
Problem with ckeditor using in vue

### ISSUE THREAD

**Issue by Noo10** [surveyjs/survey-creator#553]
### Are you requesting a feature, reporting a bug or ask a question?

Ask a question

### What is the current behavior?

Can`t use ckeditor as a custom widget in vue.

### What is the expected behavior?

Add ckeditor to toolbox.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

SurveyCreator.vue

<template>
  <div id="surveyCreatorContainer"></div>
</template>

<script>
import * as SurveyVue from "survey-vue";
import * as SurveyCreator from "survey-creator";
import * as SurveyKo from "survey-creator/node_modules/survey-knockout"
import "survey-creator/survey-creator.css";
import * as widgets from "surveyjs-widgets";
import "inputmask/dist/inputmask/phone-codes/phone.js";

widgets.ckeditor(SurveyKo);

export default {
  name: "survey-creator",
  data() {
    return {};
  },
  mounted() {
    let creatorOptions = {
      showEmbededSurveyTab: true,
      questionTypes: ["text", "checkbox", "radiogroup", "rating"]
    };
    this.surveyCreator = new SurveyCreator.SurveyCreator(
      "surveyCreatorContainer",
      creatorOptions
    );
    
    
    this.surveyCreator.saveSurveyFunc = function() {
      console.log(JSON.stringify(this.text));
    };
  }
};
</script>

index.vue
<template>
  <div id="app">
    <survey-creator></survey-creator>
  </div>
</template>

<script>
import * as SurveyVue from "survey-vue";
import SurveyCreator from "../../../components/SurveyCreator";
let Survey = SurveyVue.Survey;

import "bootstrap/dist/css/bootstrap.css";
Survey.cssType = "bootstrap";

import "inputmask/dist/inputmask/phone-codes/phone.js";

export default {
  name: "app",
  components: {
    Survey,
    SurveyCreator
  }
};
</script>



### Specify your

* browser:  Google Chrome | 75.0.3770.100
* editor version: 1.0.94

**Comment by andrewtelnov** [comment]
@Noo10 You have to include the ckeditor scripts and css files into your page.

Thank you,
Andrew

**Comment by Noo10** [comment]
After writing " import 'ckeditor'  " in SurveyCreator.vue , it threw an error : "Cannot set property 'dir' of undefined".

There are some of my dependencies:
"ckeditor": "^4.11.4",
"survey-creator": "^1.0.94",
"survey-knockout": "^1.0.94",
"survey-vue": "^1.0.94",
"surveyjs-editor": "^1.0.94",
"surveyjs-widgets": "^1.0.94",
"vue": "2.6.10",
"vue-router": "3.0.6",
"vuex": "3.1.0"

Please help.
Thank you for your reply!!!

**Comment by andrewtelnov** [comment]
@Noo10 You should remove "surveyjs-editor": "^1.0.94"  or "survey-creator": "^1.0.94" repositories.
It is better to stay with "survey-creator". We are going to make "surveyjs-editor" absolete.

Thank you,
Andrew

**Comment by Noo10** [comment]
I use CKEditor as a property editor to solve my problem!
nice frame!

Thank for you help
