### ISSUE TITLE
Advanced numbering

### ISSUE THREAD

**Issue by marc0n3** [surveyjs/survey-creator#554]
### Are you requesting a feature, reporting a bug or ask a question?

asking a question

### What is the current behavior?
I want to customize question numbering by adding a prop to each question that makes possible to skip that question in numbering.
I also want a property in the survey to make  numbering relative to panels.

Any hints on this?

**Comment by andrewtelnov** [comment]
@marc0n3 Do you want still to have the title for this question?
You may put question(s) into panel and make the titleLocation equals to hidden. In this case we want calculate the question in numbering.

survey has an option to number questions through the survey, or by pages or turn it off.

Thank you,
Andrew

**Comment by marc0n3** [comment]
Hi Andrew,
the thing I want to achieve is to keep the title and customize numbering.
I'll investigate further on how survey skip the hidden title question.
