### ISSUE TITLE
addPropery intemvalue and matrix multiple choices

### ISSUE THREAD

**Issue by marc0n3** [surveyjs/survey-creator#555]
### Are you requesting a feature, reporting a bug or ask a question?
reporting a bug, i think

### What is the current behavior?
adding a property to itemvalue
`jsonObject
					.metaData
					.addProperty("itemvalue", {
						
						name:"sid",
						title: "SID",
						
					});`
the value is visible for rows and col in matrix (single)
but only for rows for other types of matrix

### What is the expected behavior?
New prop is available also on other columns

Tested page URL:
https://plnkr.co/edit/IM3oH45cljaKulbT5MR6?p=preview

**Comment by andrewtelnov** [comment]
@marc0n3 We are using another object (object type) for matrix dropdown/dynamic columns: "matrixdropdowncolumn".
Here is the working [example](https://plnkr.co/edit/m208UQzIGmoT3InQBDVq?p=preview).

Thank you,
Andrew

**Comment by marc0n3** [comment]
It works!
Thank you @andrewtelnov
