### ISSUE TITLE
Using web-components on Survey Creator

### ISSUE THREAD

**Issue by kasar-NTT** [surveyjs/survey-creator#5580]
### Are you requesting a feature, reporting a bug or asking a question?

Question

Is it possible on SurveyJs to have totally  custom made web-components on the form creator?
For example, instead of having your dropdown to have a my web-component, e.g. <my-dropdown></my-dropdown> . That means, on the left side when Designing a new Survey, i could see my custom web-components. And the output of this survey, will produce a JSON where it will describe my custom web-components as well.

Best regards,
Kostas

**Comment by JaneSjs** [comment]
Hello @kasar-NTT,
Yes, it's totaly possible. You can register a custom question model, implement a React/Angular/Vue component, register this component as a question's renderer and use it within a SurveyJS Creator and Form Library. For more information, please refer to our documentation:
* [Integrate Third-Party Angular Components](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-angular)
* [Integrate Third-Party React Components](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-react)
* [Integrate Third-Party Vue 3 Components](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-vue)

Online demos are also available here:
* [Integrate a Third-Party Color Picker Component](https://surveyjs.io/survey-creator/examples/custom-colorpicker-property-editor/)
* [Integrate a Third-Party Rich Content Editor](https://surveyjs.io/survey-creator/examples/form-builder-with-integrated-rich-text-editor/)
* [Implement a Descriptive Text Element](https://surveyjs.io/survey-creator/examples/custom-descriptive-text-element/)

Drop me a line if you have more questions.

P.S. Note that SurveyJS Creator is a [commercial developer product](https://surveyjs.io/licensing).
