### ISSUE TITLE
Invisible Pages can be clicked within the preview's Page Navigator

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5592]
T18660 - Page not hiding when using logic
https://surveyjs.answerdesk.io/internal/ticket/details/T18660
***
In the following demo, Page 2 is initially invisible.
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "boolean",
     "name": "question1",
     "title": "Show Page"
    }
   ]
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "rating",
     "name": "question2"
    }
   ],
   "visibleIf": "{question1} = true"
  },
  {
   "name": "page3",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question3",
     "choices": [
      "Item 1",
      "Item 2",
      "Item 3"
     ]
    }
   ]
  }
 ]
}
```
[View Demo](https://plnkr.co/edit/edMVLfzRfNaP65T2)

Nevertheless, the page is available within a page navigator and a user can click the page:
![image](https://github.com/surveyjs/survey-creator/assets/22372972/abe9c5f3-901c-47fa-acac-1dab333b596e)

**Comment by mikeamelin** [comment]
Prototype — https://www.figma.com/design/SSMZUWJve1zuMSeA5E5YpA/CTR--%3E-Creator-Preview?node-id=2548-21127



![Image](https://github.com/surveyjs/survey-creator/assets/17025812/760f14ab-96e8-4d0a-b6c6-bb564252aa1d)

**Comment by mikeamelin** [comment]
- [ ] wrong color
- [ ] wrong indent



![Image](https://github.com/surveyjs/survey-creator/assets/17025812/3687a067-76f1-4600-9906-74e486b6dcb7)
