### ISSUE TITLE
Changing the default values for radio groups

### ISSUE THREAD

**Issue by benirose** [surveyjs/survey-creator#561]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
When I add a radiogroup question, it pre-populates the "choices" values with "item1", "item2", "item3"...

### What is the desired behavior?
I would like to change these pre-populated values to "a", "b", "c"...

### How would you reproduce the current behavior (if this is a bug)?
Create a new radiogroup question

Is there an api for the editor to change the default seed values for multiple choice questions?

**Comment by benirose** [comment]
To add to my question, I realize I can use `choices: ['A', 'B', 'C']` when I set up my question types. Is there any way to pass a value AND label this way, or is there an alternative api I can use to update the values and labels after it's been added?

**Comment by andrewtelnov** [comment]
@benirose You may use [creator.onQuestionAdd](https://surveyjs.io/Documentation/Survey-Creator/?id=surveycreator#onQuestionAdded) event.
```js
creator.onQuestionAdd.add(function(sender, options) {
  if(options.question.getType() == "checkbox") {
    question.title = "My title";
  }
});
```

Thank you,
Andrew

**Comment by benirose** [comment]
Thanks Andrew! Which property should I update on the question to set value and label properties? Is it an easy array setting or do I need to instantiate ItemValue objects?

**Comment by benirose** [comment]
Also, if I add an option via the adorner (I think that's what the inline question editor is called) how do I hook it in make sure it gets the right value and label?

**Comment by benirose** [comment]
I did find "onItemValueAdded" via the documentation, which says "Fires on clicking "Add New" button in the itemvalue Property Editor or on clicking a "+" button during inplace editing checkbox, dropdown and radigroup questions", however I'm only getting an event fired via the property editor and not the inplace editor.

**Comment by andrewtelnov** [comment]
@benirose It works fine for me. Here is [the example](https://plnkr.co/edit/4o58qjF7rknRdxlsPSHd?p=preview)

Thank you,
Andrew
