### ISSUE TITLE
Multiple Textboxes - Cannot override the default maxLength value for Multiple Textbox items

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5615]
T18786 - Multiple Textboxes - Set a default value for the character limit setting of individual items
https://surveyjs.answerdesk.io/internal/ticket/details/T18786
***
[View Demo](https://plnkr.co/edit/vYpJGKkbCJRSkNTa)

The following code doesn't work:
```
Survey.Serializer.getProperty('multipletextitem', 'maxLength').defaultValue = 50;
```
A Multiple Textboxes' items always have the `-1` value of the `maxLenth` property.
```
{
 "logoPosition": "right",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "multipletext",
     "name": "question1",
     "items": [
      {
       "name": "text1",
       "maxLength": -1
      },
      {
       "name": "text2",
       "maxLength": -1
      }
     ]
    }
   ]
  }
 ]
}
```

Additionally, the [`creator.onItemValueAdded`](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onItemValueAdded) event is not raised when a new Multiple Textboxes item is added.

**Comment by andrewtelnov** [comment]
@JaneSjs Currently you can set the default value for text and multiple text item using the following code:
`Survey.Serializer.findProperty('text', 'maxLength').defaultValue = 50;`

Thank you,
Andrew
