### ISSUE TITLE
bug: toolbox cannot scroll

### ISSUE THREAD

**Issue by momaekwudi** [surveyjs/survey-creator#5625]
* browser: Google Chrome
* browser version: 126.0.6478.127
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: 1.11.4
![8181719901875_ pic](https://github.com/surveyjs/survey-library/assets/19163778/114d3dd2-e7ad-4ec6-b971-0b2ab7692e17)

**Comment by JaneSjs** [comment]
Hi @momaekwudi,
A toolbox should be scrolled. Please ensure that you configured styles for a creator component:
```
<div style="position: fixed; top: 0; bottom: 0; right: 0; left: 0;">
    <survey-creator [model]="model"></survey-creator>
</div>
```
[View Demo](https://codesandbox.io/s/25jt3j)

Let me know how it goes.

**Comment by momaekwudi** [comment]
Hi @JaneSjs ,
I found some inconsistency between survey creator core. css in V1.11.4 and V1.11.2, which caused me to be unable to scroll through the toolbox after using V1.11.4
![8191719917797_ pic](https://github.com/surveyjs/survey-creator/assets/19163778/61ef28a1-a078-482b-8beb-bd4f64b806ad)
![8201719970849_ pic](https://github.com/surveyjs/survey-creator/assets/19163778/71922ac0-6ee0-4806-a2bc-a9dceadda97e)


> Hi @momaekwudi, A toolbox should be scrolled. Please ensure that you configured styles for a creator component:
> 
> ```
> <div style="position: fixed; top: 0; bottom: 0; right: 0; left: 0;">
>     <survey-creator [model]="model"></survey-creator>
> </div>
> ```
> 
> [View Demo](https://codesandbox.io/s/25jt3j)
> 
> Let me know how it goes.

**Comment by JaneSjs** [comment]
Hello @momaekwudi,
I didn't reproduce the issue in the [mentioned demo](https://codesandbox.io/s/25jt3j). If you require further assitance, please share a problematic demo for research.

**Comment by momaekwudi** [comment]
> Hello @momaekwudi, I didn't reproduce the issue in the [mentioned demo](https://codesandbox.io/s/25jt3j). If you require further assitance, please share a problematic demo for research.

Hello @JaneSjs,
I'm sorry, this is due to my local cache, and it's now working fine.
Thanks for your reply.

**Comment by JaneSjs** [comment]
Hello @momaekwudi,
Thank you for keeping me posted.
