### ISSUE TITLE
Ordering of questions for 'visible if' on deletion not in survey question order

### ISSUE THREAD

**Issue by andrewjamesford** [surveyjs/survey-creator#563]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
When moving/deleting questions in survey creator, the question name doesn't update based on order of questions. Say I have 5 questions, and I remove question 3. I'm left with questions 1, 2, 4 & 5. This is an issue when choosing 'visible if' questions to the user, causing confusion.

### What is the expected behavior?
I would expect the names to update to reflect the removal of question3. So question4 would be renamed to question3, and question5 to question4
Alternatively would it be possible to show the question titles in the drop down?

### How would you reproduce the current behavior (if this is a bug)?

1. Add a question to the editor, by default they get added as question1, question2, etc
2. When a question is deleted the naming does not get updated to reflect the changes.
![Screenshot](https://nc.lsd.co.nz/apps/files_sharing/publicpreview/KTaBRnMCgCkXT7S?x=1920&y=581&a=true&file=Screen%2520Shot%25202019-07-15%2520at%252011.32.19%2520AM.png&scalingup=0)
3. This is a problem when using the 'visible if' as the questions may not be in the survey questions order of 1,2,3,4 etc. Instead they are just in alphabetical order. In the screen shot question6 is in position one of the survey.

#### Provide the test code and the tested page URL (if applicable)
Only able to provide screenshots sorry.

### Specify your

* browser: Chrome or Firefox
* editor version: 1.0.79

**Comment by andrewtelnov** [comment]
@andrewjamesford It could be unexpected behavior for other users. Many people rename questions after they drop it into the desiger surface. If you want, you may rename other questions on deleting a question in your own version of creator. You may use [creator.onElementDeleting](https://surveyjs.io/Documentation/Survey-Creator/?id=surveycreator#onElementDeleting) event.

Thank you,
Andrew

**Comment by andrewjamesford** [comment]
@andrewtelnov do you have/know of an example to rename questions? 

Thanks very much,
Andrew

**Comment by andrewtelnov** [comment]
@andrewjamesford It is pretty strightforward: question.name = newName;
You may get all questions in survey as: survey.getAllQuestions() and if you working with creator:
creator.survey.getAllQuestions()  - it will return the array of all questions.

Thank you,
Andrew

**Comment by yifei3212** [comment]
@andrewtelnov Sorry to ask the question here. I have a similar issue, but I don't want to change the question.name field. Is it possible to customise the field used by the `Visible If => Select question...` dropdown?

**Comment by andrewtelnov** [comment]
@yifei3212 Sorry I did not get the question. Do you want to have a property editor  that shows all questions in a dropdown? In this case it will be:
Survey.Serializer.addProperty("survey", {name: "testProperty::question", category: "general"});
It will add a test property into general category for survey object that will allow to choose a question available in the survey.

Thank you,
Andrew
