### ISSUE TITLE
Could not close the popup window in v1.0.99

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#564]
The error on calling function for undefined object is raised.

**Comment by andrewtelnov** [comment]
@dmitrykurmanov @tsv2013 Lets release a new version ASAP and make the v1.0.99 depricated.
We have to add a test on closing window into our interagation tests. For some reason, we do not have it...

**Comment by gologames** [comment]
Fixed via new release. 1.1.0 marked as deprecated.
