### ISSUE TITLE
Preact: Creator: `survey-creator-js` package

### ISSUE THREAD

**Issue by dmitry-kurmanov** [surveyjs/survey-creator#5649]
https://codesandbox.io/p/sandbox/preact-creator-9dm4tm?file=%2Fpreact.config.js%3A6%2C47

https://stackblitz.com/edit/vitejs-vite-vbmze6?file=src%2Fapp.jsx - better

**Comment by tsv2013** [comment]
Closed via the https://github.com/surveyjs/survey-creator/pull/5771 PR
