### ISSUE TITLE
question title want to customize * using survey designer

### ISSUE THREAD

**Issue by KrishnaRaoGundavarapu** [surveyjs/survey-creator#568]
Add a span and class around required asterisk 
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
* is displayed for required fields

### What is the expected behavior?
I want to customize it to add span

### How would you reproduce the current behavior (if this is a bug)?
You can use the plunker here (https://www.surveyjs.io/Examples/Library/?id=survey-processtext&platform=Angular2). Change the  requiredText: "<b>(*)</b>", like this, In UI you can observe the issue

### Specify your

* browser: Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): Angular 2
* surveyjs version:

**Comment by andrewtelnov** [comment]
@KrishnaRaoGundavarapu The bug has been fixed during the [following refactoring](https://github.com/surveyjs/survey-library/issues/1771).

Thank you,
Andrew
