### ISSUE TITLE
Use pages as categories in property grid instead of panels

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#5693]
New property grid design (currently as optional).
It will show only one category at once and has the category placed vertically as list of icons.

**Comment by mikeamelin** [comment]
- [ ] no placeholder
https://www.figma.com/design/SSMZUWJve1zuMSeA5E5YpA/CTR--%3E-Creator-Preview?node-id=2696-77782&t=U0wTGvprgkApcpoC-4

- [ ] property grid title still has old design
https://www.figma.com/design/SSMZUWJve1zuMSeA5E5YpA/CTR--%3E-Creator-Preview?node-id=2696-78076&t=U0wTGvprgkApcpoC-4

- [ ] no hover

- [ ] cursor should be HAND

- [ ] property grid's group is not selected for added question

- [ ] collapsed grid should not have selected item and a group should be opened on click
https://www.figma.com/design/SSMZUWJve1zuMSeA5E5YpA/CTR--%3E-Creator-Preview?node-id=2696-79189&t=U0wTGvprgkApcpoC-4

- [ ] these icons should be on the one line
<img width="738" alt="Screenshot 2024-08-23 at 09 15 35" src="https://github.com/user-attachments/assets/e1a7bb12-beaa-4866-aec8-13e382edc9aa">

- [ ] wrong background
- [ ] double border

<img width="735" alt="Screenshot 2024-08-23 at 09 15 58" src="https://github.com/user-attachments/assets/45141c96-04aa-47fb-b1c0-8b2577d5ef84">

**Comment by JaneSjs** [comment]
- [ ] Theme Editor - Large gaps around property editors within the Appearance section
![image](https://github.com/user-attachments/assets/91955d81-bdab-4448-9880-63882f8053f0)

**Comment by mikeamelin** [comment]
- [ ] during the searching an icon should be changed
<img width="621" alt="Screenshot 2024-08-30 at 12 50 54" src="https://github.com/user-attachments/assets/1dd65a3c-610b-41f1-97e3-03f6080868e1">

- [ ] double border in the collapsed state
<img width="438" alt="Screenshot 2024-08-30 at 12 51 33" src="https://github.com/user-attachments/assets/c5ace191-36be-4eef-9f1d-73fa908e4d13">

- [ ] this background is not bad, but I care about right variable, and for that theme it should be another color (gray)

<img width="748" alt="Screenshot 2024-08-30 at 12 51 55" src="https://github.com/user-attachments/assets/036db0b4-ee48-457d-a892-2422e864fcb6">

- [ ] the icon is not swapped

https://github.com/user-attachments/assets/1b594ba5-19f6-4f56-a0c7-41ecc3e0376d

**Comment by RomanTsukanov** [comment]
Change the text in the empty property grid:

**Start configuring your form**
Click any category icon to explore survey settings. Additional settings will become available once you add a survey element to the design surface.
