### ISSUE TITLE
Allow hiding "Select All" option from adorner pane on adding quesiton

### ISSUE THREAD

**Issue by GregEPersonal** [surveyjs/survey-creator#5701]
### Are you requesting a feature, reporting a bug or ask a question?
Feature Request / Question Ask

### What is the current behavior?
When you set showSelectAllItem to false in the below, it hides it in the Property Grid, but not in the adorner pane. 

```
 creator.onShowingProperty.add(function (sender, options) {
       ... 
       // For "showSelectAllItem"
            options.canShow = false
        }
    });
```

### What is the expected behavior?
It'd be great if it hid it in both. Is there a property that does that already?

**Comment by andrewtelnov** [comment]
@GregEPersonal Please use `Serializer.findProperty("checkbox", "showSelectAllItem").visible = false;`.
Here is [the example](https://plnkr.co/edit/Uod2oYy73ShYo5sI).

Thank you,
Andrew

**Comment by GregEPersonal** [comment]
Thank you! That works. For future reference (for other readers), it looks like only that Serializer call is necessary to hide it in both question pane and property grid.

**Comment by JaneSjs** [comment]
Hello @GregEPersonal,
Thank you for the update. Note that you can also hide the Select All item from the design surface using the following code:
```
creator.onSurveyInstanceCreated.add(function(sender, options) {   
   if(options.area == "designer-tab") {
      options.survey.onShowingChoiceItem.add(function (sender, options){
         options.visible = options.item.id != "selectall";
      });
   }
});
```
Feel free to contact us if you require further assistance.
