### ISSUE TITLE
cant load survey-creator-core

### ISSUE THREAD

**Issue by bhavya0598** [surveyjs/survey-creator#5703]
### Are you requesting a feature, reporting a bug or ask a question?
reporting a bug

### What is the current behavior?
node_modules are not getting installed

### What is the expected behavior?
node_modules should get installed

### How would you reproduce the current behavior (if this is a bug)?
git clone https://github.com/surveyjs/survey-creator.git
cd survey-creator/packages/survey-creator-core
npm install

NPM version  9.6.7
Node version v18.17.0
OS Windows 11

**Comment by JaneSjs** [comment]
Hello @bhavya0598,
From what I gather, you submitted the following Help Desk inquiry: https://surveyjs.answerdesk.io/internal/ticket/details/T19035. If so, let's continue our conversation there.

Thank you
