### ISSUE TITLE
OnCanShowProperty not called

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-creator#571]
https://plnkr.co/edit/plIXf2eEitDzXF8bJEr8?p=preview

![image](https://user-images.githubusercontent.com/30930391/61726442-5084b300-ad7a-11e9-9068-09ef5e05d2db.png)

**Comment by andrewtelnov** [comment]
@gologames the options.obj.getType() equals to "text" in your example. That is the reason the code doesn't work.

Thank you,
Andrew

**Comment by gologames** [comment]
Sure!
