### ISSUE TITLE
Property Grid - Update the Question title alignment property name/hint to indicate that a description will be hidden as well

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5716]
T19086 - Hiding title also hides automatically description 
https://surveyjs.answerdesk.io/internal/ticket/details/T19086

![image](https://github.com/user-attachments/assets/fbe1ae62-a8f2-4edf-bbe3-c24deb008049)

**Comment by ElenaGorbatkova** [comment]
@RomanTsukanov please update the hints for **question title alignment** and **question description** to the following:

![image](https://github.com/user-attachments/assets/740b704b-096c-4d09-935e-d0bc34f897d6)

Question title alignment:

Overrides title alignment rules defined on a panel, page or survey level. The "Inherit" option applies any higher-level settings (if set) or survey-level setting ("Top" by default). When set to "Hidden", it also hides the Question description.

Question description: 

Type a question subtitle. The question description is not visible, if Question title alignment is set to "Hidden".
