### ISSUE TITLE
Feature / On blur name in question

### ISSUE THREAD

**Issue by ZaKull** [surveyjs/survey-creator#572]
### Are you requesting a feature, reporting a bug or ask a question?

Feature survey creator

### What is the current behavior?

no trigger event when blur question name

### What is the expected behavior?

function trigger when blur name.
i need this for change items in radio or checkbox when name is xxxx
![image](https://user-images.githubusercontent.com/2388373/61755702-bc6d1880-ad86-11e9-9c77-8a8c9fb72c5a.png)

**Comment by andrewtelnov** [comment]
Hello,
We have [creator.onModified event](https://surveyjs.io/Documentation/Survey-Creator/?id=surveycreator#onModified):
```js
creator.onModified.add(function(sender, options) {
  if(options.type == "PROPERTY_CHANGED" && options.name == "name") {
    //options.target - your object 
   //and options.oldValue and options.newValue can be used as well here
  }
});
```

Thank you,
Andrew

**Comment by ZaKull** [comment]
not work :( .... i need on blur to this field.  this code works only press apply or ok.

**Comment by andrewtelnov** [comment]
@ZaKull Unfortunately we do not have this functionality. Could you please describe your scenario in more details? We will discuss it.

Thank you,
Andrew

**Comment by ZaKull** [comment]
`Survey.JsonObject.metaData.classes.question.properties[0].setChoices([{'text':'p1','value':'p1'},{'text':'p2','value':'p2'}]);`

this code seg question name string whith choices values, in selector.

**Comment by andrewtelnov** [comment]
@ZaKull I am not sure I totally understand what you are trying to implement. However, probably the 'dependedOn' property attribute may solve your task. Here is [the example](https://surveyjs.io/Examples/Survey-Creator/?id=dependsonproperties).
Your property will depend on property `name`.

Thank you,
Andrew
