### ISSUE TITLE
Generate Domain Model Code Demo - TS Error:  Argument of type '{ activate: () => void; deactivate: () => boolean; }' is not assignable to parameter of type 'ICreatorPlugin'.

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5731]
T19111 - Adding a new tab
https://surveyjs.answerdesk.io/internal/ticket/details/T19111
***
If you copy the [Generate Domain Model Code](https://surveyjs.io/survey-creator/examples/create-domain-models/reactjs#content-code) code to a TypeScript application (e.g., a TSX component), the app won't compile:
```
TS2345: Argument of type '{ activate: () => void; deactivate: () => boolean; }' is not assignable to parameter of type 'ICreatorPlugin'.
  Property 'model' is missing in type '{ activate: () => void; deactivate: () => boolean; }' but required in type 'ICreatorPlugin'.
    88 | };
    89 | // Add the tab as a first tab to the Survey Creator
  > 90 | creator.addPluginTab("servercode", templatesPlugin, "Domain Model Code", "svc-tab-servercode", 0);
   ```

To fix this issue, it is necessary to do the following:
* Cast `templatesPlugin` to `ICreatorPlugin`
* However, `ICreatorPlugin` requires an additional `model` parameter. As Serge suggested at [t9067](https://surveyjs.answerdesk.io/internal/ticket/details/T9067), you can set model to a creator instance.

```
import { ICreatorPlugin } from "survey-creator-core";

const templatesPlugin: ICreatorPlugin = {
    activate: () => { },
    deactivate: () => { return true; },
    model: creator // An optional parameter
};
// Add the tab as a first tab to the Survey Creator
creator.addPluginTab("servercode", templatesPlugin, "Domain Model Code", "svc-tab-servercode", 0);
```
[domain-model-demo.zip](https://github.com/user-attachments/files/16373432/domain-model-demo.zip)

@RomanTsukanov please consider updating the demo code to avoid this TS error.

**Comment by RomanTsukanov** [comment]
Fixed https://github.com/surveyjs/service/commit/2342d4054bd38c571a464f9b741b5340c74c3838
