### ISSUE TITLE
How to hide pen icon on page?

### ISSUE THREAD

**Issue by artur0117** [surveyjs/survey-creator#5751]
![Screenshot_2](https://github.com/user-attachments/assets/f6ea7a26-0265-49b4-b282-761f16bac137)

I want to hide pen icon that highlighted in the screenshot I attached.

**Comment by andrewtelnov** [comment]
@artur0117 This code will make the trick:
```js
    creator.onSetPropertyEditorOptions.add((sender, options) => {
      options.editorOptions.allowBatchEdit = false;
    });
```
Here is [the example](https://plnkr.co/edit/MUUQQKomDR07LWSu).

Thank you,
Andrew

**Comment by artur0117** [comment]
Awesome! Thanks so much!
