### ISSUE TITLE
Need to set data by passing JSON 

### ISSUE THREAD

**Issue by VishalWaman** [surveyjs/survey-creator#579]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?
Need to set data by passign JSON 

### What is the expected behavior?
We set JSON that we have received by Builder and need to edit it using same JSON, so baically need to bind question from JSON

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code
NA
```
your_code_here
NA
```

### Specify your
Any browser
* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@VishalWaman Not sure that I am fully understand the question.  You may set your JSON as:
`creator.text = JSON.stringify(your_survey_JSON);` Here is [the doc](https://surveyjs.io/Documentation/Survey-Creator/#loadsavesurvey).

Thank you,
Andrew

**Comment by VishalWaman** [comment]
Hi @andrewtelnov , thanks for this help..
Basically we want to edit survey created in editor and need to bind same JSON that was generated from SurveyJS..  We need to set JSON to editor and have option to update questions 

We will look through doc shared.. Thanks again...
