### ISSUE TITLE
Is this PHP Script collects data from our databases?

### ISSUE THREAD

**Issue by sheikhrehman** [surveyjs/survey-creator#582]

**Comment by andrewtelnov** [comment]
@sheikhrehman What do you mean? Our libraries do not send any data anyware unless you tell SurveyJS Library widget to store the data in our cloud. Here is [the example](https://surveyjs.io/Examples/Library/?id=service-send).
It is an open source project you may see the code and build your own version of library.

Thank you,
Andrew

**Comment by tsv2013** [comment]
1. It's a client-side JavaScript library
2. It doesn't connected to any database at all
