### ISSUE TITLE
Is this editor supports arabic language?

### ISSUE THREAD

**Issue by bhumi0901** [surveyjs/survey-creator#584]
I need to use this survey js editor in the Arabic language. Is there any solution by which i can view all the editor text translations in the Arabic language?

**Comment by tsv2013** [comment]
Localization of this product is supported by cimmunity
All supported languages are listed here - https://github.com/surveyjs/survey-creator/tree/master/src/localization
You can add your own localization following the readme file on the page above

Also please check the product license before using - https://surveyjs.io/Licenses#BuildSurvey

**Comment by bhumi0901** [comment]
Can i know that how can i use it with react js.
I have used survey js editor as below:
`this.editor = new SurveyJSEditor.SurveyEditor(
        "surveyEditorContainer",
        editorOptions
      );`

**Comment by tsv2013** [comment]
@bhumi0901 Since this is another question I've answered in a corresponding thread - https://github.com/surveyjs/survey-creator/issues/585

**Comment by bhumi0901** [comment]
I have used that but I am not able to set default local language in the survey editor. Can you please help me with this?

**Comment by tsv2013** [comment]
You can check live examples on our site - https://surveyjs.io/Examples/Survey-Creator/?id=localization&theme=bootstrap

**Comment by bhumi0901** [comment]
That example is for SurveyCreator. I need it for `surveyjs-editor`

**Comment by tsv2013** [comment]
@bhumi0901 surveyjs-editor is deprecated. You should use survey-creator instead. It's the same package.
