### ISSUE TITLE
Unable to hide maskSettings items when creating a Specialized Question type

### ISSUE THREAD

**Issue by doelgonzo** [surveyjs/survey-creator#5843]
### Are you requesting a feature, reporting a bug or ask a question?
Bug/Question

### What is the current behavior?
The documentation [here](https://surveyjs.io/form-library/documentation/customize-question-types/create-specialized-question-types) indicates that `End users cannot break the functionality because the Property Grid hides the questionJSON object properties.`, but when I set some of these properties they still appear in the property grid (see test code). It's possible I'm doing something wrong, but I understand it that this should work this way. My gut says it's related to these being nested values, but I don't know how to get around it.

I also tried:
```
inheritBaseProps: ["maskSettings:max","maskSettings:min","maskSettings:decimalSeparator","maskSettings:thousandsSeparator", "maskSettings:allowNegativeValues"]
```
and it made no difference. Any guidance is welcome.
Also, the console.log below prints out base properties but none of the `maskSettings`-related ones... 

### What is the expected behavior?
They are hidden, or I have a programatic way to hide these properties.

#### Provide the test code and the tested page URL (if applicable)

Test code

```
export const registerNumberInput = () => {
   const existingQuestion = ComponentCollection.Instance.getCustomQuestionByName(
    CustomField.NumberInput
  );

  // Register the NumericInput model with the ElementFactory
  if (!existingQuestion) {
    ComponentCollection.Instance.add({
      name: CustomField.NumberInput,
      iconName: CustomField.NumberInput,
      title: "Number Input",
      questionJSON: {
        type: "text",
        inputType: "text",
        maskType: "numeric",
        maskSettings: {
          saveMaskedValue: false,
          precision: 0,
        },
      },
      inheritBaseProps: ["maskSettings"],
    });
  }

  console.log(
    ComponentCollection.Instance.getCustomQuestionByName(
      CustomField.NumberInput
    )
  );
};

```

### Specify your

* browser:
* editor version: 1.11.13

**Comment by JaneSjs** [comment]
Hello,
You set `inheritBaseProps: ["maskSettings"]`, therefore, Mask Settings appear in a property grid. If you wish to define mask settings but make them unavailable in a property grid, update your specialized question definition and remove the `inheritBaseProps` attribute.
```
 ComponentCollection.Instance.add({
      name: "custom-number-input",
      title: "Number Input",
      questionJSON: {
        type: "text",
        inputType: "text",
        maskType: "numeric",
        maskSettings: {
          saveMaskedValue: false,
          precision: 0,
        },
      }
});
```
Let me know if you have any questions.

**Comment by doelgonzo** [comment]
Is there a way to make `maskSettings.saveMaskedValue` or `maskSettings.precision` not appear on on the property grid but have the others within `maskSettings` still appear?

**Comment by JaneSjs** [comment]
Hello @doelgonzo,
Please accept my apologies for the delayed response. Use the [creator.onShowingProperty](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onShowingProperty) function to hide the `saveMaskedValue` and `precision` mask settings. Consider the following demo: [View Plunker](https://plnkr.co/edit/oZwhaH7LGk9H0r71).
```
import { ComponentCollection } from "survey-core";

ComponentCollection.Instance.add({
      name: "number-input",
      title: "Number Input",
      questionJSON: {
        type: "text",
        inputType: "text",
        maskType: "numeric",
        maskSettings: {
          saveMaskedValue: false,
        },
      },
      inheritBaseProps: ["maskSettings"],
});
const propertyStopList = [ "precision", "saveMaskedValue"];

creator.onShowingProperty.add((sender, options) => {
      if(options.obj.getType() === "numericmask" && !!options.parentObj && options.parentObj.getType() === "number-input" && propertyStopList.indexOf(options.property.name) >= 0){         
        options.canShow = false;
      }
});
```
Feel free to reactivate this thread if you require further assistance.
