### ISSUE TITLE
Validation with RegExp doesn't support case insensitive check

### ISSUE THREAD

**Issue by yanhuiyi** [surveyjs/survey-creator#5854]
### Are you requesting a feature, reporting a bug or ask a question?
A question

### What is the current behavior?
Validation with RegExp doesn't support case insensitive check

### What is the expected behavior?

Validation should support case insensitive check.

### How would you reproduce the current behavior (if this is a bug)?
1. Create an email input
2. In Validators panel, choose Regex
3. In Regular expression put rules like @.*\.edu$
4. Expect the validation can check any cases letters ending with .edu

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* editor version:  survey-creator-react "1.9.120"

**Comment by JaneSjs** [comment]
Hello @yanhuiyi,
Thank you for reaching out. I tested the provided regular expression and confirmed that it doesn't allow uppercase email addresses like `USER@DOMAIN.EDU`, while `user@domain.edu` is correctly accepted.
```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "text",
          "name": "question1",
          "validators": [
            {
              "type": "regex",
              "regex": "@.*.edu$"
            }
          ],
          "inputType": "email"
        }
      ]
    }
  ]
}
```
I will note down this inquiry and forward it to our developers for further investigation.

**Comment by JaneSjs** [comment]
Hello @yanhuiyi,
To achieve your goal, you can explicitly list both uppercase and lowercase letters in each part of the regex pattern. You can use character classes to achieve this.

Here's how you would list both uppercase and lowercase letters explicitly:
```
@[a-zA-Z0-9.-]+\.[eE][dD][uU]$
```
Consider the following survey configuration:
```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "text",
          "name": "question1",
          "validators": [
            {
              "type": "regex",
              "regex": "@[a-zA-Z0-9.-]+\\.[eE][dD][uU]$"
            }
          ],
          "inputType": "email"
        }
      ]
    }
  ]
}
```
Please let me know if this works for you.

**Comment by yanhuiyi** [comment]
Hi @JaneSjs, thank you so much. That's smart way! Where I can set 'insensitive' flag in SurveyJS UI (see screenshots below)? That's where the question come from. Sorry in advance, I'm not sure if the config should be made in the code level in your above example, I ask in a role of a user not the developer.

![SJ_regex](https://github.com/user-attachments/assets/b33231d9-4d79-4d26-89cd-7dc1ef652c91)

**Comment by yanhuiyi** [comment]
Hi @JaneSjs, seems JSON Editor is where I can write regexp directly. Another question is what the regexp flavor that SurveyJS support. Is it ECMAScript(JavaScript). When I paste the `@[a-zA-Z0-9.-]+\.edu(?:.[A-Z]{2,6})*$` into the UI, then open the JSON Editor the express converted to `@[a-zA-Z0-9.-]+\\.edu(?:.[A-Z]{2,6})*$`. The expression works in reg101.com but the doesn't in SurveyJS, see the attached screenshot.
![Uploading sj_exp.jpg…]()
