### ISSUE TITLE
Implement pages drag/drop on design surface

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#5873]
Add an option to collapse all pages on drag start and restore their state back on drag end

**Comment by tsv2013** [comment]
https://www.figma.com/design/SSMZUWJve1zuMSeA5E5YpA/CTR--%3E-Creator-Preview?node-id=2586-4780

**Comment by andrewtelnov** [comment]
1) Page title edtor is activated after dragging
2) When pages are collapsed, the state of pages should be restored after dragging

**Comment by mikeamelin** [comment]
- [ ] maybe same issue as for question, but looks a bit more unpleasure. Showing/hiding drag indicator makes unnecessary blinking. Also it is still weird that no ability to drop between items


https://github.com/user-attachments/assets/83b961fc-038b-4134-9cc0-fbf6527c5390

- [ ] agree with two points that Andrew mentioned
- [ ] sometimes drag indicator remains on the surface 
<img width="922" alt="Screenshot 2024-10-02 at 15 27 53" src="https://github.com/user-attachments/assets/a3ea60c8-4de5-4499-83a3-f8cc0cdff1f3">

- [ ] after a couple of actions a one page stops collapsing at all

- [ ] we forget to change appearance of dragging page on the surface as we do for question (change opacity)
<img width="909" alt="Screenshot 2024-10-02 at 15 47 30" src="https://github.com/user-attachments/assets/bb3b071f-3f6d-4c0c-b049-48b498432dcb">

**Comment by mikeamelin** [comment]
- [ ] keep current page collapsed if it was collapsed before dragging

**Comment by JaneSjs** [comment]
A page is blinking and is expanded automatically. Follow these steps:
[PagesDragDropCreatorDemo (1).zip](https://github.com/user-attachments/files/17312418/PagesDragDropCreatorDemo.1.zip)

0. Run index2.html.
1. Collapse All pages.
2. Drop 4th page at the 1st position.
3. Drop the 4th page under the 1st page.
4. Click outsite or wait for a second.
5. You'll see the 3rd question starts blinking.

https://github.com/user-attachments/assets/9c942a20-d100-4781-af3e-cb8c2e069c5d
