### ISSUE TITLE
Cannot hide Mask Settings using the creator.onShowingProperty function

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5874]
Based on [T19764 - How to change the title of a category in the property grid](https://surveyjs.answerdesk.io/internal/ticket/details/T19764)
***
Input mask settings cannot be hidden using the `creator.onShowingProperty` function.
[View Demo](https://plnkr.co/edit/wk49ppbwke8sRhrA)
```
creator.onShowingProperty.add((sender, options) => {      
      if(options.obj.getType() === "text" && options.property.name === "saveMaskedValue" || options.obj.getType() === "text" && options.property.name === "allowNegativeValues"){        
        console.log(options.property.name);
        options.canShow = false;        
      }    
});
```
![image](https://github.com/user-attachments/assets/5264db56-7d75-4774-8695-1fb30da38e76)

**Comment by OlgaLarina** [comment]
To hide property, you need to change the condition.

`  if(options.obj.getType() === "numericmask" && options.property.name === "saveMaskedValue" || options.obj.getType() === "numericmask" && options.property.name === "allowNegativeValues")`

**Comment by JaneSjs** [comment]
Thanks @OlgaLarina. The updated demo: [View Demo](https://plnkr.co/edit/BnY2rJtQthCrnNZM).
