### ISSUE TITLE
Custom question properties should automatically appear for Matrix Columns

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5877]
If you register a custom question property, it appears for regular questions. 
To make the custom property appear for matrix columns, it is necessary to add the property to a matrix column definition.

```
import { SurveyQuestionEditorDefinition } from "survey-creator-core";
import { Serializer } from "survey-core";

Survey.Serializer.addProperty('radiogroup', 
{
  name: 'customProp',
  category: "general"
});

SurveyQuestionEditorDefinition.definition["matrixdropdowncolumn@radiogroup"] = {
    properties: ["customProp"]
};
```
[View Demo](https://plnkr.co/edit/bwhuqx5p5vjZ3fr5)

Should we consider adding custom properties to corresponding matrix columns by default?

**Comment by RomanTsukanov** [comment]
`availableInMatrixColumn: true | false`
