### ISSUE TITLE
Question: Hide edit button from choices

### ISSUE THREAD

**Issue by Lordchapter** [surveyjs/survey-creator#589]
### Are you requesting a feature, reporting a bug or ask a question?
Question

Is it possible to hide the "Edit" buttons of the choices from dropdowns, checkboxes,...?
![image](https://user-images.githubusercontent.com/2069264/63210337-4e99df80-c0ed-11e9-98e0-f6efdb9634f3.png)

Thanks!

**Comment by andrewtelnov** [comment]
@Lordchapter Unfortunately we do not have this functionality yet. I will add this request into our TODO list.

Thank you,
Andrew

**Comment by Lordchapter** [comment]
@andrewtelnov Thanks!

**Comment by andrewtelnov** [comment]
@Lordchapter From the next version (v1.1.15) that we are going to release next Tuesday, you will be able to add the following code before calling SurveyCreator constructor:
```
SurveyCreator.SurveyQuestionEditorDefinition.definition[
        "itemvalue[]@choices"
      ].tabs = [{ name: "general", visible: false }];
```
This code will remove all tabs for choices item and SurveyCreator will not show "Edit" button if there is nothing to show.

Thank you,
Andrew

**Comment by Lordchapter** [comment]
@andrewtelnov Thank you so much!!
