### ISSUE TITLE
Remove question type from definition

### ISSUE THREAD

**Issue by mkopinsky** [surveyjs/survey-creator#590]
### Are you requesting a feature, reporting a bug or ask a question?

Asking a question

### What is the current behavior?

When user adds a multiple choice question type (radiogroup, dropdown, etc.) they can change it to an imagepicker, even though I removed imagepicker from the toolbox.

### What is the expected behavior?

There should be a way to remove it entirely, not just hide from the toolbox. This is similar to what was hinted at in #527 but I don't think that was implemented (or if it was, I can't find any documentation).

### Specify your

* browser: Chrome 75
* editor version: 1.1.2

**Comment by andrewtelnov** [comment]
@mkopinsky I have decided to implement this functinality since several developers have already complained about the current behavior.
We will include the fix into the next minor update v1.1.6, that we release most likely today.

Thank you,
Andrew

**Comment by mkopinsky** [comment]
Cool, thanks!
