### ISSUE TITLE
Alignment issue with nouislider

### ISSUE THREAD

**Issue by mkopinsky** [surveyjs/survey-creator#591]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

In my app, the slider for the nouislider is way off to the right (the value is 5/10, but it appears at what would be position 15/10). I haven't been able to put together an exact MVP reproduction, but in the repro at https://github.com/mkopinsky/surveyjs-creator-nouislider-repro the slider is slightly off to the right (the value is 5/10 but it appears at 6/10). This applies within the survey designer and test tab, but when I actually complete a survey (with survey-vue or survey-jquery) it appears fine.

#### Provide the test code and the tested page URL (if applicable)

Test code

```
git clone https://github.com/mkopinsky/surveyjs-creator-nouislider-repro
cd surveyjs-creator-nouislider-repro
yarn serve
```

Open browser to designated URL, add a nouislider question.

### Specify your

* browser: Chrome 75
* editor version: 1.1.5

**Comment by gologames** [comment]
Hello Michael,

Problem is that nouislider has styling breaking change in version 14 compared with version 10 which is using in SurveyJS Widgets package. 

You can add `nouislider.fix.css` file to `src` folder in your repo with following content:
`
.noUi-origin {
    width: 0%
}
`
(width equal 10% in new version of nouilider). And add
`import "../src/nouislider.fix.css";` line at the very bottom of imports in `surveyQuestionTypes.js` file in your repo.

Or you may use old version of nouislider and set `9.2.0` in `package.json` in your repo

Thanks, Alex
SurveyJS Team

**Comment by mkopinsky** [comment]
Thanks!
