### ISSUE TITLE
Choices are updated incorrectly after fixing the value duplication error

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5915]
T19983 - Question Choices, duplicate values getting through, choices being formatted as number/string inconsistently. 
https://surveyjs.answerdesk.io/internal/ticket/details/T19983
***
To reproduce the issue, please open https://surveyjs.io/create-free-survey, add Checkboxes, and follow the screencast.

https://github.com/user-attachments/assets/4c662272-c2f0-4a05-89c6-22a302cde6e8

The resultant survey JSON contains a duplicate `"1"` entries.
```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "checkbox",
          "name": "question1",
          "choices": [
            "1",
            "1",
            "3"
          ]
        }
      ]
    }
  ]
}
```
Expected behavior the choices have 2, 1, 3 values and their display texts are updated correspondintly.
```
 "choices": [
       2, 
       1,
       3
]
```

**Comment by snlacks** [comment]
In the resulting JSON, one of the 1s is a string and one is a number, which might be why it's making the error message disappear.

```
{
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "checkbox",
          "name": "question1",
          "choices": [
            1,
            "1",
            "3"
          ]
        }
      ]
    }
  ]
}
```
