### ISSUE TITLE
onPropertyValidationCustomError validating stale property values

### ISSUE THREAD

**Issue by mkopinsky** [surveyjs/survey-creator#592]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

onPropertyValidationCustomError gets called when the Save/Apply button is clicked and I'd expect it to validate based on the values that I entered in the question editor. However, it seems to be using stale values in the callback.

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/nTQ94NmbSod0rQCzmqso?p=preview
* Open dev tools
* Add a dropdown question
* Change one of the choices from item1 to item1asdf.
* Click save/apply
* Expected: It should console.log item1asdf, item2, item3.
* Actual: It console.logs item1, item2, item3.

### Specify your

* browser: Chrome 75
* editor version: 1.1.5

**Comment by andrewtelnov** [comment]
@mkopinsky I have just checked it and it works correctly, item1asdf is in the options.value.
Could you please check again?

Thank you,
Andrew

**Comment by mkopinsky** [comment]
Here's a gif illustrating what's happening to me on that plunkr:

![surveyjs validation](https://user-images.githubusercontent.com/591435/63344777-38736580-c31f-11e9-944f-9492fa0cf165.gif)

**Comment by andrewtelnov** [comment]
@mkopinsky Aga, I see. The value is not assigned yet. The event is called before assigning value into the object. Otherwise, there is no way to callback an incorrect value.
You have to use options.value property. Here is the [updated plunker](https://plnkr.co/edit/h6sULSOFNkhZHH6ABmmz).

Thank you,
Andrew

**Comment by mkopinsky** [comment]
OK, makes sense.

So right now I'm using this one `questionValidator` which is really validating 4 different properties - `options.obj.choices`, `options.obj.rows`, `options.obj.columns`, and `options.obj.name`. I guess I need to split that out into 4 separate validators, each of them essentially consisting of
```
if (options.name !== 'rows') return;
// check that none of the items in options.value are >= 60 chars
```
and only ever looking at `options.value` rather than `options.obj.whatever`?


My *real* goal with this validator is to make sure that when the question gets serialized into my database (we flatten it so the question ID becomes (in the case of a matrix dropdown) `question1/row1/column1/checkbox1`) will always fit into VARCHAR(255). So ideally, if this validator could also access `options.newObj` which is a temp copy of what the object will look like if it passes validation, I could add up the lengths rather than arbitrarily giving the items max lengths of 60 each. (But I understand this is probably a large and not really necessary change, so I can go ahead with the multiple validators approach I mentioned at the top of this comment.)

**Comment by andrewtelnov** [comment]
@mkopinsky The option with name maximum length would be the best solution. Unfortunately, we are busy with other things at the current moment. I think having these functions is the best solution right now.

Thank you,
Andrew

**Comment by mkopinsky** [comment]
Thanks for your help!!
