### ISSUE TITLE
Run expression triggers

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#593]
### Are you requesting a feature, reporting a bug or ask a question?
Question / bug

### What is the current behavior?
I can no longer set a value name as the target of the expression; instead I have to pick a question from the list.

### What is the expected behavior?
In a previous version I could enter a name that was not a question and it would be added to the result.

We use triggers for creating screenouts, if needs to be screenout we set the value `result` to screenout, then we trigger survey completion.
This is no longer possible via the creator (we can do it by editing the JSON).

**Comment by andrewtelnov** [comment]
@SamMousa We did it because the end-user do not get it and it confused them. We will think about replacing the standard selector with something that will allow to enter any value or pick-up a question from the dropdown.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SamMousa We are going to solve the issue differently. Right now, there is no a good way to define and use variable in the Creator. We will introduce calculated values/variables entity. The list of objects: unique name, expression and a boolean property includeIntoResult (false by default). You will be able to set it in Creator, for example as:
`{name: "var1", expression: "iif({question1} < 1, 5, {question2} * 5)"}`

Calculated values will be shown in dropdown together with question names in condition/expression property editor.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SamMousa Please follow [this issue](https://github.com/surveyjs/survey-library/issues/1810).

Thank you,
Andrew

**Comment by SamMousa** [comment]
Feel free to close this!
