### ISSUE TITLE
Drag and drop visually buggy

### ISSUE THREAD

**Issue by ryan-s-wilson** [surveyjs/survey-creator#5943]
### Are you requesting a feature, reporting a bug or ask a question?
reporting a bug

### What is the current behavior?

![2024-10-07_19-31_1](https://github.com/user-attachments/assets/28d9610e-192d-4070-a142-83fb5bafe37d)
In the image above when I am dragging item1 we can see it in the top right corner of the image instead of being dragged around. We can see that drag and drop works normally in other situations
![2024-10-07_19-31](https://github.com/user-attachments/assets/5eee6146-28cc-4c05-8a34-5c6223b08a44)

### What is the expected behavior?

Drag and drop looks visually correct

### How would you reproduce the current behavior (if this is a bug)?

This was done with all of our customizations disabled so quite possibly any install of surveyJS

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

Browser: chrome and brave
version: 1.12.4 (upgraded to verify presence)

**Comment by JaneSjs** [comment]
Hello @ryan-s-wilson,
Looking by your screenshot, I suppose that creator styles were imported incorrectly. A creator should appear as follows: [View SurveyJS Creator Demos](https://surveyjs.io/survey-creator/examples/free-nps-survey-template/). Please ensure that you followed a [get started guide](https://surveyjs.io/survey-creator/documentation/overview#get-started) and correctly imported the required styles.

Please let me know your results.
