### ISSUE TITLE
Can't set title to space character

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-creator#595]
Can't set title to space character in SurveyCreator JSON, but with SurveyJS library it works

https://plnkr.co/edit/WVaJVlq4DBVNaWfGC8UL?p=preview

![image](https://user-images.githubusercontent.com/30930391/64269993-81dccb00-cf43-11e9-960b-fb61a205a21f.png)

**Comment by umr55766** [comment]
Hey @gologames , what is the expected behavior for this ?

**Comment by andrewtelnov** [comment]
@gologames @umr55766 We are trimming the title value. If the value is empty then the question name is showing. If you want to hide the question title completely, then please set question.titleLocation to "hidden".

Thank you,
Andrew
