### ISSUE TITLE
Replace upload logo icon with a CTA button labeled 'Upload your logo'

### ISSUE THREAD

**Issue by hamidseta** [surveyjs/survey-creator#5958]
Currently, an icon is used for uploading a logo in the form. I would like to replace it with a CTA button labeled 'Upload your logo' in the survey form. Is this possible in SurveyJS? If it is possible then how to achieve it in React JS. Please refer to the attached image for reference.

![image](https://github.com/user-attachments/assets/78e77aa9-d6f6-4452-829f-17bf57815a21)

**Comment by JaneSjs** [comment]
Hello @hamidseta,
Yes, it's possible. You can replace the upload logo icon (`icon-logo`) with another icon from a built-in icon set. Or, register a custom icon. For more information on how to operate icons, please visit [UI Icons](https://surveyjs.io/form-library/documentation/icons).

In the following demo, I replaced the `icon-logo` with `icon-download`: [View CodeSandbox](https://codesandbox.io/p/sandbox/magical-engelbart-k792xy?file=%2Fsrc%2FSurveyCreatorComponent.jsx%3A31%2C5).

**ChooseFile.js**
```
export const chooseFileIcon = `<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<path d="M22 9V7C22 5.9 21.1 5 20 5H12L10 3H4C2.9 3 2 3.9 2 5V9V10V21H22L24 9H22ZM4 5H9.2L10.6 6.4L11.2 7H12H20V9H4V5ZM20.3 19H4V11H21.6L20.3 19Z"/>
</svg>`;
```
**SurveyCreatorComponent.jsx**
```
import { chooseFileIcon } from "./ChooseFile.js";

SvgRegistry.registerIconFromSvg("icon-logo", chooseFileIcon);
```
Please feel free to reactivate this thread if you require further assistance.
