### ISSUE TITLE
I want to add a custom attribute

### ISSUE THREAD

**Issue by momaekwudi** [surveyjs/survey-creator#5959]
hello, 
As the title suggests. I want to add a custom attribute that is the same as the one in the picture. But I'm not sure how to set the type. Look forward to your reply. 

<img width="1493" alt="image" src="https://github.com/user-attachments/assets/c74770cc-01db-4828-8ccb-dc9f0fbf9c08">

```
Serializer.addProperty('question', {
  name: 'popupLogic',
  displayName: 'popupLogic',
  category: 'general',
  categoryIndex: 900,
  type: '???',
});

```

**Comment by JaneSjs** [comment]
Hello @momaekwudi,
Wouldy you please clarify which particular property type you wish to register? Do you wish to register the property which would create a `completedHtmlOnCondition` array of objects? Please additionally elaborate on your usage scenario.

Thank you

**Comment by momaekwudi** [comment]
> Hello @momaekwudi, Wouldy you please clarify which particular property type you wish to register? Do you wish to register the property which would create a `completedHtmlOnCondition` array of objects? Please additionally elaborate on your usage scenario.
> 
> Thank you

Hello @JaneSjs 
I would like to register a custom property for the Question that is the same as the `completedHtmlOnCondition ` data structure, which is an object array. I will name it `popupLogic`. I hope to trigger the expression in the object array when the answer to each question changes, and take the first true `html` to display Pupup with `html`.
```
{
  "title": "<p>test</p>",
  "pages": [
    {
      "name": "page1",
      "elements": [
        {
          "type": "radiogroup",
          "name": "Q1",
          "popupLogic": [
            {
              "expression": "{Q1}=a",
              "html": "<p>some text</p>"
            },
            {
              "expression": "{Q1}=b",
              "html": "<p>ohter text</p>"
            }
          ],
          "choices": [
            {
              "value": "a",
              "text": "item1"
            },
            {
              "value": "b",
              "text": "item2"
            },
            {
              "value": "c",
              "text": "item3"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by JaneSjs** [comment]
Hello @momaekwudi,
Thank you for the clarification. You can register a custom property of `htmlconditions` type as follows: [View Demo](https://plnkr.co/edit/J1H6I1M9AtcvhE2C).
```
import { Serializer } from "survey-core";
import { editorLocalization } from "survey-creator-core";

Serializer.addProperty('question', {
    name: "popupLogic",
    type: "htmlconditions",
    className: "htmlconditionitem", 
    category: "popupLogic",
    categoryIndex: 1,
    isArray: true
});

const locale = editorLocalization.getLocale("");
locale.pe.tabs["popupLogic"] = "Popup Logic";
```
![image](https://github.com/user-attachments/assets/2c9e9be4-5b23-4265-a7c1-c875f5ee98f3)
