### ISSUE TITLE
`notShortCircuitAnd` does not work

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#5975]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
I was researching another bug (#5974) and came across this code.

```ts
export function notShortCircuitAnd(...args: Array<boolean>): boolean {
  return args.every((val) => val === true);
}
``` 

Based on the name of the function I'm imagining it is supposed to do some logical and without short circuiting, however it doesn't.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every
> If such an element is found, every() immediately returns false and stops iterating through the array.

**Comment by JaneSjs** [comment]
Hi Sam,

Thank you for your inquiry. The `notShortCircuitAnd` function is part of a private API and is used to ensure that every function in an array is executed, allowing the computed updater to gather all necessary dependencies (subscriptions). Its purpose isn’t focused on evaluating all elements internally but rather on guaranteeing that each dependency is called to avoid potential short-circuiting issues.

The function’s internal logic `(args.every((val) => val === true))` plays a secondary role here; the primary benefit is that by passing an array of functions, each function will be evaluated before the `notShortCircuitAnd` function processes them. This approach ensures that all dependencies are gathered properly, even if some return `false`.

I hope this clarifies things. Please feel free to reach out if you have further questions.

Best regards,
Jane

**Comment by SamMousa** [comment]
> guaranteeing that each dependency is called to avoid potential short-circuiting issues.

But it DOES NOT do this... I created the bug to let you know that the code (whether private or public API is not relevant) does not do what you think it does.

I even put the link to how `Array.every` works and quoted the relevant part.
