### ISSUE TITLE
Single Input question Custom Input Type

### ISSUE THREAD

**Issue by naresh-india-mumbai** [surveyjs/survey-creator#599]
Hi Team,

1) I just want to check as a survey creator can we customised Input Type for Single Input question. I only want below options for creator:-
date
email
number
text
URL

2) How Can we modify the tab name "Survey Designer" to "Designer"?

Please suggest on above points.

Regards,
Naresh.

**Comment by tsv2013** [comment]
```JS
Survey.Serializer.removeProperty("text", "inputType");

Survey.Serializer.addProperty("text", {
      name: "inputType",
      "default": "text",
      choices: [
        "date",
        "email",
        "number",
        "text",
        "url"
      ]
});

SurveyCreator.enStrings.ed.designer = "My Tab Designer";
```

Here is the live sample - https://plnkr.co/edit/PpOpCbcVfyVlP3KYuyR1?p=preview

**Comment by naresh-india-mumbai** [comment]
@tsv2013 Thank you for sharing the solution, will go through the live example too.

**Comment by naresh-india-mumbai** [comment]
@tsv2013 Its working, hence closing the issue (question).
