### ISSUE TITLE
Some default question types cannot be hidden with questionTypes option

### ISSUE THREAD

**Issue by indichen** [surveyjs/survey-creator#600]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
Several default question types still there, e.g. bar rating, date picker, etc., even only specify ["text"] in questionTypes option
![image](https://user-images.githubusercontent.com/11827451/65305447-c5773c00-dbb5-11e9-99a7-c7a2a929e11d.png)

### What is the expected behavior?
Only the Single Text question type available.

### How would you reproduce the current behavior (if this is a bug)?
1. Setup the questionTypes list with only ["text"] for creating the survey
2. Run the creator, and then check the Toolbox on left panel

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* editor version:

**Comment by tsv2013** [comment]
These questions are the custom widget ones. In order to remove them, just remove custom widget loading or initialization code.

**Comment by tsv2013** [comment]
Here is the live sample - https://plnkr.co/edit/fOiD9CTYl5tSAuPeD4I2?p=preview

**Comment by indichen** [comment]
Awesome. They are gone after removing the custom widgets related code. @tsv2013 Thank you very much. :)
Close the issue.
