### ISSUE TITLE
How can I give custom validation when fill form with required field?

### ISSUE THREAD

**Issue by bhp2810** [surveyjs/survey-creator#603]
### Are you requesting a feature, reporting a bug or ask a question?

How can I give custom validation when fill form with required field?

### What is the current behavior?

When save filled data with normal button external button required marked filled saved without any validation means it not ask as it required.

### What is the expected behavior?

when save using external button click need to validate message.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@bhp2810 Please use the followig property:
```
  /**
   * Returns true, if there is any error on the current page. For example, the required question is empty or a question validation is failed.
   * @see nextPage
   */
  public get isCurrentPageHasErrors(): boolean;

```

Thank you,
Andrew
