### ISSUE TITLE
CUSTOM question type category

### ISSUE THREAD

**Issue by hapiKzm** [surveyjs/survey-creator#6034]
Hi, I have some custom question type and i want  to put the in one element like Single-Line Input that open other option on hover 
![sil](https://github.com/user-attachments/assets/c86d731e-5015-46db-a220-51c9489dd522)

**Comment by JaneSjs** [comment]
Hello,
To add a custom question to a list of Single-Line question sub-items, use the [`addSubitem`](https://surveyjs.io/survey-creator/documentation/api-reference/questiontoolboxitem#addSubitem) function of a Text toolbox item. For more information, please refer to [Manage Toolbox Subitems](https://surveyjs.io/survey-creator/documentation/toolbox-customization#manage-toolbox-subitems).
