### ISSUE TITLE
Survey Designer > Image picker > select check box from the right drop down > select image picker again from the drop down > pictures will disappear

### ISSUE THREAD

**Issue by bhp2810** [surveyjs/survey-creator#604]
### What is the current behavior?

Survey Designer > Image picker > select check box from the right drop down > select image picker again from the drop down > pictures will disappear

### What is the expected behavior?

pictures should remain same as when we selected first time.

### How would you reproduce the current behavior (if this is a bug)?

https://surveyjs.io/create-survey/
Try to add Image picker from toolbox

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://surveyjs.io/create-survey/
Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
This is the exprected behavior

The checkbox question type doen't have the 'imageLink' property. Thus this property value is lost after conversion to dropdown. When you convert a dropdown back to an imagepicker - the 'imageLink' property of choices is empty (you have lost the pictures)

**Comment by tsv2013** [comment]
BTW you can use the Undo button to roll back your changes

**Comment by bhp2810** [comment]
so can we set 'imageLink' blank from starting when add image picker from toolbox

**Comment by tsv2013** [comment]
Yes, you can. You can use the https://surveyjs.io/Documentation/Survey-Creator/?id=surveycreator#onQuestionAdded event to customize added question

**Comment by tsv2013** [comment]
You can also set your custom choices. Here is the sample on our site - https://surveyjs.io/Examples/Survey-Creator/?id=toolboxcustomization&theme=bootstrap
