### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by Gusmonkey** [surveyjs/survey-creator#6053]
**Describe the bug**
The "Get Started" link for HTML/CSS/JavaScript returns a 404

https://github.com/surveyjs/survey-creator/blob/master/survey-creator/documentation/get-started-html-css-javascript

**Steps to reproduce**

1. Go to https://github.com/surveyjs/survey-creator?tab=readme-ov-file
2. Click on _Get Started > HTML/CSS/JavaScript_
3. See 404 error

**Expected behavior**
See a page describing how to use the repo using HTML, CSS & JavaScript, similar to https://surveyjs.io/survey-creator/documentation/get-started-vue

**Please complete the following information:**
- Browser: Firefox
- Device: PC

**Comment by RomanTsukanov** [comment]
Hi @Gusmonkey,

Thanks for the heads up! I've fixed the issue.
