### ISSUE TITLE
Wrong icon color

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#6061]
- [x] https://www.figma.com/design/SSMZUWJve1zuMSeA5E5YpA/CTR--%3E-Creator-Preview?node-id=2661-53886&t=Z3hatJzUrfmaZ6ov-4

![Image](https://github.com/user-attachments/assets/1ed505d9-8aa7-40a4-8fc8-e14437139091)

- [x] Border shouldn't be in check state here

https://www.figma.com/design/SSMZUWJve1zuMSeA5E5YpA/CTR--%3E-Creator-Preview?node-id=2663-25487&t=Z3hatJzUrfmaZ6ov-4

![image](https://github.com/user-attachments/assets/fd33b311-8b6c-45e7-9fc6-92695e13105f)

- [x] There are somehow too many pixels

https://www.figma.com/design/SSMZUWJve1zuMSeA5E5YpA/CTR--%3E-Creator-Preview?node-id=3759-32064&t=Z3hatJzUrfmaZ6ov-4

![image](https://github.com/user-attachments/assets/e5806cdd-a9e7-4ce5-9abc-65265cd1ee94)

- [x] flowers are drawn, this thing (indicator). I didn't find it in my project, maybe it was deleted somehow over time :) In general, I want to edit this.
![image](https://github.com/user-attachments/assets/b9bbd057-3d55-4899-90ea-f2a4499cdd45)

**Comment by mikeamelin** [comment]
I've added the ghost-elements to the project with necessary variables. I did it for each question (radiobuttons, checkboxes and ranking). But if you use only one set of variables for each of them, no problem. Anyway, their values are the same.

Radio — https://www.figma.com/design/i6Lpc7zkjHtso2oXZV97fo/Components?node-id=24052-122326&t=VlR2VaEmWjByZAer-4

Checkbox — https://www.figma.com/design/i6Lpc7zkjHtso2oXZV97fo/Components?node-id=24052-122345&t=VlR2VaEmWjByZAer-4

Ranking — https://www.figma.com/design/i6Lpc7zkjHtso2oXZV97fo/Components?node-id=24052-127159&t=VlR2VaEmWjByZAer-4
