### ISSUE TITLE
The creator.onModified event is not raised when updating a page title and/or description

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#6067]
T20676 - OnModified call back on page title chnage
https://surveyjs.answerdesk.io/internal/ticket/details/T20676

*****
To reproduce the issue, run [this demo](https://plnkr.co/edit/m52j9p6SqcqTYwAB) and follow these steps:
* Define a page title from a design surface. The `onModified` function is invoked.
* Update a page title or description. The `onModified` function is not invoked.

https://github.com/user-attachments/assets/765078e8-cb58-41fc-b757-766242c585e1

**Comment by andrewtelnov** [comment]
@JaneSjs I can't reproduce it with [my example](https://plnkr.co/edit/5iaPY8z2YLrznqfs).

Thank you,
Andrew
