### ISSUE TITLE
Prevent title of multipletext items from being edited from main screen

### ISSUE THREAD

**Issue by mkopinsky** [surveyjs/survey-creator#609]
### Are you requesting a feature, reporting a bug or ask a question?

Feature or question

### What is the current behavior?

I have a question question widget defined as follows:
```
    Survey.JsonObject.metaData.addClass(
      "bloodpressure", [
        {
          name: 'items',
          visible: false,
        },
      ],
      null,
      "multipletext"
    );
```
By setting `visible:false` the Items section doesn't show up in the modal question editor, but I can still click the pencil on the preview and edit the item title:
![image](https://user-images.githubusercontent.com/591435/66166752-25ce9a80-e606-11e9-8da7-33ddb7b7e67a.png)

### Specify your

* browser: Chrome 77
* editor version: 1.1.13

**Comment by tsv2013** [comment]
The item title editor adorner works with all available titles. For now you can't disable adorner for the specific question (or item). Do I understand you right that you created a question descendant and want to fix it's items, disable items editing in popup editor (that works ok) and disable adorner (in-place) editing for your custom question type?

**Comment by mkopinsky** [comment]
Yes, that is correct.
