### ISSUE TITLE
Show question based on language

### ISSUE THREAD

**Issue by Lordchapter** [surveyjs/survey-creator#611]
### Are you requesting a feature, reporting a bug or ask a question?
Question (or maybe feature request?)

I have a survey with multiple languages, is it possible to show / hide a question based on the chosen language?

In my case I have a survey in English and Hungarian and I want to add the question "Do you speak English? -> Yes/No" to the Hungarian version but not the English version.

Is this possible using only 1 survey? Or do I need to make 2 seperate surveys? 

Thanks!

**Comment by tsv2013** [comment]
Yes it's possible if you create several questions in your survey and add a "visibleIf" condition
In this condition you can use a custom function (https://surveyjs.io/Documentation/Library/#conditions-functions) lets's say "forLocale()": `visibleIf: "forLocale("de") == true"`

And this custom function would be defined like this (I've not tested it in real code, just as an idea):
```JS
function forLocale(params) {
  if (!params && params.length < 1) return false;
  return Survey.surveyLocalization.currentLocale === params[0] || 
             Survey.surveyLocalization.currentLocale === "" && params[0] === "en";
}
Survey.FunctionFactory.Instance.register("forLocale", forLocale);
```
