### ISSUE TITLE
how to custom UI 

### ISSUE THREAD

**Issue by annDipro** [surveyjs/survey-creator#6116]
How can I customize the interface, have a button to select a category -> click to display dynamic form. Then click a custom preview button to display the preview. Without having to depend on the available UI

**Comment by andrewtelnov** [comment]
@annDipro Please provide more information about your goals.
"Have a button to select a category" - what does it mean?
"Click to display dynamic form" - what does it mean? Where should be this action located?
To display the "preview" you can set [creator.activeTab](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#activeTab) property to "test".

Thank you,
Andrew
