### ISSUE TITLE
A question is not selected on a design surface if a user clicks a question's input field area

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#6138]
T20861 - Highlight the Question when click on input element like textbox or checkbox
https://surveyjs.answerdesk.io/internal/ticket/details/T20861
***
Issue: a question is selected only when clicking the question's area. If you click a question's input area, the question won't be selected.

https://github.com/user-attachments/assets/6b4c5c6d-7019-4fa5-9f01-d2e73e7b9b61

Expected behavior: a question is selected when a user clicks any part of a question's design area.

**Comment by dmitry-kurmanov** [comment]
https://stackoverflow.com/questions/3100319/event-on-a-disabled-input

**Comment by JaneSjs** [comment]
@dmitry-kurmanov, it does not work for Comment fields. Please refer to the following demo:

https://github.com/user-attachments/assets/4b22d80f-878e-4ca7-bd6a-bf917bbeec69
