### ISSUE TITLE
CK-Editor not applied in choices edit

### ISSUE THREAD

**Issue by yangxu698** [surveyjs/survey-creator#614]
### Are you requesting a feature, reporting a bug or asking a question?
question

### What is the current behavior?
I followed the documentation to integrate ck-editor into surveyJS.
Link: https://www.surveyjs.io/Examples/Editor/?id=ckeditorpropertyeditor
Now for each question, CK-editor is appied to edit in question title.

### What is the expected behavior?
I need to input some special characters or maybe equations in the choice. But currently the choice is allowed for pure text only.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here
  var CkEditor_ModalEditor = {
                afterRender: function (modalEditor, htmlElement) {
                    var editor = CKEDITOR.replace(htmlElement);
                    editor.on('change', function () {
                        modalEditor.editingValue = editor.getData();
                    });
                    editor.setData(modalEditor.editingValue);
                    modalEditor.onValueUpdated = function (newValue) {
                        editor.setData(newValue);
                    }
                },
                destroy: function (modalEditor, htmlElement) {
                    var instance = CKEDITOR.instances[htmlElement.id];
                    if (instance) {
                        instance.removeAllListeners();
                        CKEDITOR.remove(instance);
                    }
                }
            };
            SurveyCreator
                .SurveyPropertyModalEditor
                .registerCustomWidget("html", CkEditor_ModalEditor);
            SurveyCreator
                .SurveyPropertyModalEditor
                .registerCustomWidget("text", CkEditor_ModalEditor);


            var questionDef = SurveyCreator.SurveyQuestionEditorDefinition.definition.question;

            //Modify Question Editor. Remove title from general and add it as a tab.
            questionDef
                .tabs
                .push({name: "title", index: 1});
            SurveyCreator
                .defaultStrings
                .pe
                .tabs["title"] = "Title";
            var ind = questionDef
                .properties
                .indexOf("title");
            if (ind > -1)
                questionDef
                    .properties
                    .splice(ind, 1);

            //Create showdown mardown converter
            var converter = new showdown.Converter();
            function doMarkdown(survey, options) {
                //convert the mardown text to html
                var str = converter.makeHtml(options.text);
                if (str.indexOf("<p>") == 0) {
                    //remove root paragraphs<p></p>
                    str = str.substring(3);
                    str = str.substring(0, str.length - 4);
                }
                //set html
                options.html = str;
            }


            var creator = new SurveyCreator.SurveyCreator("creatorElement", creatorOptions);
            creator.undo();
            creator.redo();
            
                SurveyCreator
                    .StylesManager
                    .applyTheme("winter");

                creator.saveSurveyFunc = function () {
                    console;
                }

          creator
              .toolbarItems
              .push({
                  id: "Learning_Module_Submit",
                  visible: true,
                  title: "Submit Learning Module",
                  action: function () {
                  }
              });

            creator
                .survey
                .onTextMarkdown
                .add(doMarkdown);
            creator
                .onDesignerSurveyCreated
                .add(function (editor, options) {
                    options
                        .survey
                        .onTextMarkdown
                        .add(doMarkdown);
                });
            creator
                .onTestSurveyCreated
                .add(function (editor, options) {
                    options
                        .survey
                        .onTextMarkdown
                        .add(doMarkdown);
                });
```

### Specify your

* browser: Chrome
* browser version:  77.0.3865.90 
* surveyjs platform (angular or react or jquery or knockout or vue):jquery
* surveyjs version:1.1.15

**Comment by tsv2013** [comment]
Moved question to the corresponding repo

**Comment by tsv2013** [comment]
You've created a custom modal property editor. But you need to implement a non-modal custom property editor like in this sample https://www.surveyjs.io/Examples/Editor/?id=custompropertyeditor but with CKEditor

**Comment by tsv2013** [comment]
Here is the plunker with solution according how I've understood your scenario - https://plnkr.co/edit/rxkKmliHysdXnq9r4kEc?p=preview

![image](https://user-images.githubusercontent.com/3013415/67095260-29dde900-f1be-11e9-97b3-ebd813daba57.png)

Does it fit your needs?

**Comment by yangxu698** [comment]
Thanks for the reply. The CKEditor is integrated!

Sorry but I found several issues after integrating the CKeditor into the choice. 

issue1: after inputting the special characters and clicking OK, the text isn't displayed.
![Screenshot from 2019-10-18 11-04-43](https://user-images.githubusercontent.com/29738383/67105899-af01d780-f197-11e9-91e2-83e69658927a.png)
![Screenshot from 2019-10-18 11-10-52](https://user-images.githubusercontent.com/29738383/67106110-030cbc00-f198-11e9-9bf6-5fa228214230.png)

if we change the property to value, the text isn't displayed either.
Survey.Serializer.findProperty("itemvalue", "value").type = "cktext";

![Screenshot from 2019-10-18 11-15-12](https://user-images.githubusercontent.com/29738383/67106448-a8c02b00-f198-11e9-9034-30911e543a53.png)
![Screenshot from 2019-10-18 11-15-41](https://user-images.githubusercontent.com/29738383/67106453-ab228500-f198-11e9-9f49-a2abaf203979.png)

issue2: There is only one item of the choice property displayed and available to be edited, but by default there are three items of the choice property.

issue3: the add(green) and delete(red) choice buttons don't work after CKEditor intergration, even the words of the two buttons disappear.
![Screenshot from 2019-10-18 11-28-48](https://user-images.githubusercontent.com/29738383/67107453-816a5d80-f19a-11e9-94b6-a8836cbab2ad.png)

I'm thinking it might result from certain internal conflict between choice definition and CK Editor. Not sure how easy these issues can be fixed.

**Comment by yangxu698** [comment]
Hi,
Just a follow-up, is there any way to fix this, or do we need to check the source code and rewrite the choice part? Any tips would be much appreciated.

Thanks.

**Comment by yangxu698** [comment]
Hi, I figured out the code for CKeditor integration in the choice property. Please check the plunkr demo:
 https://plnkr.co/edit/qcZtltBPyJlAFNEhldZy?p=preview

There are two issues when using CKeditor inside choice property:
1: chrome doesn't parse the special character inside choice, but parsed the special characters in the question title correctly.
![Screenshot from 2019-10-24 17-18-24](https://user-images.githubusercontent.com/29738383/67526426-bb4bd000-f682-11e9-980f-c1c79fc3199e.png)
2: When I input into the choice text, I need to click the text area everytime I input one character, otherwise I won't be able to input anymore. Sounds there is still some conflict after CKeditor integration. It is the same if you test on plunkr.

Thanks!

**Comment by tsv2013** [comment]
I've check out plunker. It looks like we have an issue in our code. The custom widget is re-rendered unexpectedly during the `modalEditor.koValue(editor.getData());` operation. I'll investigate the issue further.

**Comment by tsv2013** [comment]
@yangxu698 It was an issue in our code - custom property editor made redundant re-drawings due to extra change subscription to koValue.

I've fixed it via the referenced commit. Fix will be available in the nearest minor update, most likely next tuesday.

**Comment by yangxu698** [comment]
Great! Looking forward to that.

**Comment by yangxu698** [comment]
Hello @tsv2013 , I updated the code on my own end, it seems that the problem is still there. 
Plunkr code is updated, now the version is 1.1.18 for survey.ko.js, survey-creator.js, survey.css, survey-creator.css.

Here is the link:
[https://next.plnkr.co/edit/qcZtltBPyJlAFNEhldZy?p=preview&preview](url)

I find it's getting slower when inputting in the choice text.

I double-checked on my end that no other changes, please let me know if any other change should be done before run surveyjs.

Thanks.

**Comment by tsv2013** [comment]
@yangxu698 You need to use the version > 1.1.19. Here is the working sample - https://next.plnkr.co/edit/0ezFW1HJHKSkIHbO?preview

P.S. Your plunker has a syntax error. Check the console.

**Comment by yangxu698** [comment]
Thanks, the version 1.1.19 works perfect!

Also thanks for the remind, I'll check it out.
