### ISSUE TITLE
Creator V2. Mobile toolbar

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#6161]
https://www.figma.com/design/SSMZUWJve1zuMSeA5E5YpA/CTR--%3E-Creator-Preview?node-id=2660-38565&m=dev

**Comment by mikeamelin** [comment]
- [ ] wrong hover
https://www.figma.com/design/i6Lpc7zkjHtso2oXZV97fo/Components?node-id=2018-25245&t=HQp60C3R6qMnEQDU-4

<img width="392" alt="Screenshot 2024-12-16 at 16 39 50" src="https://github.com/user-attachments/assets/43e3d099-33a2-4539-9d6b-767a5284a011" />


- [ ] wrong checked
https://www.figma.com/design/i6Lpc7zkjHtso2oXZV97fo/Components?node-id=2018-25243&t=HQp60C3R6qMnEQDU-4

<img width="415" alt="Screenshot 2024-12-16 at 16 33 43" src="https://github.com/user-attachments/assets/692b9be0-92c9-468f-9935-ca25a5cd2b4b" />
