### ISSUE TITLE
Conditions on the values of custom widgets in the form editor

### ISSUE THREAD

**Issue by musicpulpite** [surveyjs/survey-creator#618]
### Are you requesting a feature, reporting a bug or ask a question?
Asking a question that may become a feature request

### What is the current behavior?
In the question conditionals sections for each widget editor (Visible if, Enable if) you can conditionally display a widget based on the selected value of another widget. If that widget is a custom widget with dynamically generated question options we still want to be able to select one in the widget editor.

If a custom widget is selected as the conditional question, its custom htmlTemplate is rendered and then its afterRender function is called to append data to it.
```
    afterRender(question, el) {
      const $el = getElement(el);

      if (!question.isDesignMode) {
        const projects = this.getChoices(question.name);
...
```
However, there is no way to tell from this question object alone (class
 QuetionEmpty) which widget was selected and therefore what values to append to the htmlTemplate. (Note: just knowing which customWidgetValue to use is not enough because we also have to get metadata specific to that selected customWidget to determine which possible values were selected as options). Something like: 
```
    getChoices(questionName) {
...
      const currentQuestion = jsonFormData.pages[0].elements.find(
        field => field.name === questionName
      );
...
```
### What is the expected behavior?
The question object passed as an argument to afterRender has a name property with the value "question". Can we change it to the name of the question that was selected in the 'Visible if' dropdown (which we know will be unique)?

We get the correct questionName value here: 
https://github.com/surveyjs/survey-creator/blob/bffcbd3be00821d18251a40e7dcf095bc0a1de40/src/propertyEditors/propertyConditionEditor.ts#L181

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by gologames** [comment]
Hello,

You may use `onConditionValueSurveyCreated` event of SurveyCreator to set question name of new survey from `options.valueQuestionName` of event. Here is [live sample](https://plnkr.co/edit/zh1bPipYdLDf7E2lzwr5?p=preview) in plunker

Thanks, Alex
SurveyJS Team
