### ISSUE TITLE
CustomDesignerTab example - this.renderPages is not a function

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#6186]
T20982 - New Tab designer with PropertyGrid
https://surveyjs.answerdesk.io/internal/ticket/details/T20982
***
The following example of a custom designer tab doesn't work: https://github.com/surveyjs/survey-creator/blob/f7bc3f259af1c658e8fb8510c1d58d0de7be952b/packages/survey-creator-react/examples/custom-designer.js#L66-L102

[View Demo](https://codesandbox.io/p/sandbox/pensive-gwen-9r7m52?file=%2Fsrc%2FSurveyCreatorComponent.jsx%3A73%2C3)

`this.renderPages is not a function`

**Comment by tsv2013** [comment]
It needs to use:
```JS
{ReactElementFactory.Instance.createElement("svc-toolbox", {
            model: this.creator,
          })}
```
and
```JS
{this.getRenderedPages()}
```
