### ISSUE TITLE
Error running Survey Creator locally!

### ISSUE THREAD

**Issue by asemandeveloper** [surveyjs/survey-creator#6187]
I can't run the Survey Creator source code locally! Please help.

**Comment by tsv2013** [comment]
You can now find build instructions in README files distributed with our packages:

[Build the Survey Creator Model from Sources](https://github.com/surveyjs/survey-creator/tree/master/packages/survey-creator-core#build-the-survey-creator-model-from-sources)
[Build Survey Creator / Form Builder for Angular from Sources](https://github.com/surveyjs/survey-creator/tree/master/packages/survey-creator-angular#build-survey-creator--form-builder-for-angular-from-sources)
[Build Survey Creator / Form Builder for React from Sources](https://github.com/surveyjs/survey-creator/tree/master/packages/survey-creator-react#build-survey-creator--form-builder-for-react-from-sources)
[Build Survey Creator / Form Builder for Knockout from Sources](https://github.com/surveyjs/survey-creator/tree/master/packages/survey-creator-knockout#build-survey-creator--form-builder-for-knockout-from-sources)
