### ISSUE TITLE
OK click Handle

### ISSUE THREAD

**Issue by YahyaJamali** [surveyjs/survey-creator#619]
How to handle click issue of "OK" button of each question editor modal?

**Comment by tsv2013** [comment]
Could you describe your scenario in greater detail? Why do you need to handle OK click?

If you need to get notified about the certain properties have been changed, you can subscribe the https://surveyjs.io/Documentation/Survey-Creator/?id=surveycreator#onPropertyValueChanging event

**Comment by YahyaJamali** [comment]
> Could you describe your scenario in greater detail? Why do you need to handle OK click?
> 
> If you need to get notified about the certain properties have been changed, you can subscribe the https://surveyjs.io/Documentation/Survey-Creator/?id=surveycreator#onPropertyValueChanging event

I want to add validations on OK click of each editor modal
1) Make question title field required.
2) restrict user not to add negative value in ratevalues, timerquiz

**Comment by YahyaJamali** [comment]
I want to add validations on OK click of each editor modal

Make question title field required.
restrict user not to add negative value in ratevalues, timerquiz


________________________________

**Comment by tsv2013** [comment]
I believe in validation purposes you can use the https://surveyjs.io/Documentation/Survey-Creator/?id=surveycreator#onPropertyValidationCustomError event as discussed in this thread - https://github.com/surveyjs/survey-creator/issues/350

**Comment by andrewtelnov** [comment]
@YahyaJamali Additionally, you may find useful the [following topic](https://surveyjs.io/Documentation/Survey-Creator/?id=Survey-Creator-Overview#addproperties)
You may tell Survey Creator that property is requried:
Survey.Serializer.findProperty("question", "title").isRequired = true;
I have set minValue attribute to some property in the commit that you may see above, including the properties you have mentioned.

Thank you,
Andrew
