### ISSUE TITLE
Checkbox alignment in Property Grid

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#6197]
![Image](https://github.com/user-attachments/assets/a1499993-7e0e-4fe2-8ff0-494ce2795ef3)

**Comment by mikeamelin** [comment]
Font-size-unit for width and height.

https://www.figma.com/design/i6Lpc7zkjHtso2oXZV97fo/Components?node-id=21220-2186663&m=dev

**Comment by JaneSjs** [comment]
@OlgaLarina  please check

**Comment by OlgaLarina** [comment]
The theme has been updated and the problem has been fixed.
