### ISSUE TITLE
Parse CKEditor html element

### ISSUE THREAD

**Issue by yangxu698** [surveyjs/survey-creator#620]
### Are you requesting a feature, reporting a bug or ask a question?
Ask a question.

### What is the current behavior?
After creating the survey, saving it to local database, and loading it for revise. Under Survey Designer Tab, the CKeditor html element is not correctly parsed. 

Note: I renamed the Survey Designer Tab to Learning Module Designer Tab.
![Screenshot from 2019-10-18 11-43-29](https://user-images.githubusercontent.com/29738383/67108469-934d0000-f19c-11e9-886b-e6b40fc2aaad.png)

But in Test Learning Module Tab, the same html element is parsed correctly.
Note: I renamed the Test Survey Tab to Test Learning Module Tab.
![Screenshot from 2019-10-18 11-44-48](https://user-images.githubusercontent.com/29738383/67108527-bc6d9080-f19c-11e9-923d-e83cf68d54a0.png)

### What is the expected behavior?
The html element is parsed correctly in Survey Designer tab.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

      //Create showdown markdown converter
            var converter = new showdown.Converter();
            function doMarkdown(survey, options) {
                //convert the markdown text to html
                var str = converter.makeHtml(options.text);
                console.log(options.text);
                if (str.indexOf("<p>") == 0) {
                    //remove root paragraphs<p></p>
                    str = str.substring(3);
                    str = str.substring(0, str.length - 4);
                }
                //set html
                options.html = str;
            };

            var creator = new SurveyCreator.SurveyCreator("creatorElement", creatorOptions);
            creator.text = JSON.stringify(json);

            creator
                .survey
                .onTextMarkdown
                .add(doMarkdown);
            creator
                .onDesignerSurveyCreated
                .add(function (editor, options) {
                    options
                        .survey
                        .onTextMarkdown
                        .add(doMarkdown);
                });
            creator
                .onSurveyInstanceCreated
                .add(function (editor, options) {
                    options
                        .survey
                        .onTextMarkdown
                        .add(doMarkdown);
                });
            creator
                .onTestSurveyCreated
                .add(function (editor, options) {
                    options
                        .survey
                        .onTextMarkdown
                        .add(doMarkdown);
                });


```

### Specify your

* browser: Chrome Version 77.0.3865.90 
* editor version: SurveyJS version: 1.1.12

**Comment by andrewtelnov** [comment]
@yangxu698 Please move this line  ```creator.text = JSON.stringify(json);``` to the bottom.
Additionally better to use the following code:
```creator.JSON = json;```

Thank you,
Andrew

**Comment by yangxu698** [comment]
That works!
Also thanks for the advice. use 
`creator.JSON`
is much better!
