### ISSUE TITLE
OK Click Handler

### ISSUE THREAD

**Issue by YahyaJamali** [surveyjs/survey-creator#621]
I want to add validations on OK click of each editor modal

Make question title field required.
restrict user not to add negative value in ratevalues, timerquiz
![Capture](https://user-images.githubusercontent.com/36918343/67359048-b05a4800-f57b-11e9-85cf-c8c7858350dc.PNG)
![Capture2](https://user-images.githubusercontent.com/36918343/67359054-b2240b80-f57b-11e9-90ca-31b3ffb8cf7f.PNG)

**Comment by tsv2013** [comment]
Duplicate of the https://github.com/surveyjs/survey-creator/issues/619

Could you write in the original thread?
