### ISSUE TITLE
Arabic Localization

### ISSUE THREAD

**Issue by YahyaJamali** [surveyjs/survey-creator#624]
There is no option for Arabic translation for survey creator toolbox.
SurveyCreator.localization.currentLocale = "ar";  
**German, Persian, Spanish all working but there is no localization for Arabic**

**Comment by tsv2013** [comment]
Localization of SurveyJS Creator is provided by the community.
You can also follow the instructions from the https://github.com/surveyjs/survey-creator/tree/master/src/localization page to add your own localization file.
