### ISSUE TITLE
Show displayValue instead of values in expression in Logic tab

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#625]
When you have json:
```
{
    elements: [
      {
        type: "radiogroup",
        name: "q1", title: "Question 1", 
        choices: [{ value: 1, text: "one" }, { value: 2, text: "two" }]
      }
]
}
```
And showTitlesInExpressions is set in options, then the following expression:
``"{q1} = 1"``` should be displayed as ``{Question 1} = one``

**Comment by dmitrykurmanov** [comment]
We have additional round brackets (parentheses) in logic tab and failed tests (integration tests with the latest survey). After the investigation for the release 1.1.19 we changed unit tests. For example:

`((true and (5 <= 12)) or ! (5 > 2))`

and also after the https://github.com/surveyjs/survey-library/issues/1892 we have additional space after each unary operand. For example:

`! (5 > 2)`

Need to discuss it with the team.

**Comment by dmitrykurmanov** [comment]
We have additional round brackets (parentheses) in logic tab and failed tests (integration tests with the latest survey). After the investigation for the release 1.1.19 we changed unit tests. For example:

`((true and (5 <= 12)) or ! (5 > 2))`

and also after the https://github.com/surveyjs/survey-library/issues/1892 we have additional space after each unary operand. For example:

`! (5 > 2)`

Need to discuss it with the team.
