### ISSUE TITLE
Design surface: The left border of a selected page is cut off when `pageEditMode` is `"bypage"`

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-creator#6266]
[Plunker](https://plnkr.co/edit/FZoPtJGsESjPLbi0?preview)

![image](https://github.com/user-attachments/assets/1caf9189-a2db-4088-b1c3-0004d68937c7)

**Comment by JaneSjs** [comment]
[v1.12.15 OK](https://plnkr.co/edit/COc1lujvFjq9EkVp)
