### ISSUE TITLE
Question: Ability to customize the look and feel of Survey JS and Survey JS Creator

### ISSUE THREAD

**Issue by bleepzter** [surveyjs/survey-creator#627]
The current demo of Survey JS has UI with green accents and icons. While evaluating the creator on your site - I've come to realize it doesn't exactly match the look and feel that I'm looking for.

Is there limitations to changing the color theme, the look and feel of the controls, etc... with Survey JS and Survey JS Creator?

**Comment by tsv2013** [comment]
You can use different approaches for UI customization, Here are the samples on our site:
library:
https://surveyjs.io/Examples/Library/?id=survey-customcss&platform=jQuery&theme=default
https://surveyjs.io/Examples/Library/?id=survey-cssclasses&platform=jQuery&theme=default
https://surveyjs.io/Examples/Library/?id=custom-theme&platform=jQuery&theme=default
creator:
https://surveyjs.io/Examples/Survey-Creator/?id=editor-custom-theme&theme=bootstrap
