### ISSUE TITLE
Validating for maximum allowed image uploaded in Image picker

### ISSUE THREAD

**Issue by VishalWaman** [surveyjs/survey-creator#629]
### Are you requesting a feature, reporting a bug or ask a question?
Question 

### What is the current behavior?
When uploading 10 images in Image picker, as this is stored in LocalStorage maximun quota is acheived and app breaks 

### What is the expected behavior?
Can we validate max allowed image uploads ?

### How would you reproduce the current behavior (if this is a bug)?
Upload 20 images of medium size to Image Picker

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by VishalWaman** [comment]
@tsv2013 Thanks in Advance

**Comment by tsv2013** [comment]
You decide - where is your web app with SurveyCreator will store survey JSON or uploaded files. And you can control the allowed size of JSON of uploaded images.

**Comment by VishalWaman** [comment]
Can we set allowed size and number of allowed images to upload in creator settings? Like 10 images with 3 MB EACH

**Comment by gologames** [comment]
Hello,

LocalStorage is not part of SurveyJS, so max file size limitation out of SurveyJS responsibility

Thanks, Alex
SurveyJS Team
