### ISSUE TITLE
Please allow a single space in addRowText and removeRowText in the survey creator

### ISSUE THREAD

**Issue by Lionqueen94** [surveyjs/survey-creator#630]
### Requesting a feature/Reporting a bug
Please allow a single space in addRowText and removeRowText in the survey creator.

### What is the current behavior?
Now single spaces on those fields get removed and the default texts appear on the buttons and one has to manually edit the json generated by the creator. When the spaces are inputted and applied the buttons show no text, but on save the spaces get filtered out and the buttons go back to the default texts.

See https://github.com/surveyjs/survey-library/issues/1888

### What is the expected behavior?
A single space in the input fields should persist and leave the buttons empty. When adding icons in the css only the icons will appear on the buttons instead of the icons next to the default texts

* browser: Chrome/Firefox
* editor version: 1.1.19

**Comment by tsv2013** [comment]
You can set these strings to empty via global localization settings:
```JS
Survey.surveyLocalization.locales["en"].addRow = "";
Survey.surveyLocalization.locales["en"].removeRow = "";
```
Does it fit your needs?

**Comment by Lionqueen94** [comment]
@tsv2013 Aah this sure fits my needs! Thanks a lot!
