### ISSUE TITLE
Placeholder as Question Title

### ISSUE THREAD

**Issue by parmardhara** [surveyjs/survey-creator#639]
### Are you requesting a feature, reporting a bug or asking a question?
Question

### What is the current behavior?
Currently need to backspace the question title and then re-type the new question again

### What is the expected behavior?
Placeholder as question title and need not to backspace it (When creating survey questions, the placeholder text should be PLACEHOLDER text that is automatically overwritten when the user clicks in to edit the question title)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Crome 
* browser version: Version 78.0.3904.108 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): VueJS

**Comment by tsv2013** [comment]
Transferred to the corresponding repo

**Comment by tsv2013** [comment]
@parmardhara  How it should work if you just want to change a couple of letters?

**Comment by tsv2013** [comment]
@parmardhara  This is the ordinary expected behavior of the inplace editors. If you have other samples, please share them.

**Comment by parmardhara** [comment]
@tsv2013 Currently when I want to edit surveyjs creator question title, I need to backspace the name "question1" and then re-type the new question title I wish to add, Is there any way in which I do not need to backspace title and by clicking on question title inplace editing, the field should get clear

**Comment by tsv2013** [comment]
There is no option to change this behavior at this moment. Thank you for the suggestion. We'll take it in mind during future improvements.

**Comment by parmardhara** [comment]
@tsv2013  Thank you!
