### ISSUE TITLE
document problem: npm install surveyjs-creator should be npm install survey-creator

### ISSUE THREAD

**Issue by runtimeExceptionHandler** [surveyjs/survey-creator#640]
According to the document "
npm install surveyjs-creator", 404 appears during package installation. The document should be modified to "npm install survey-creator".

location: https://surveyjs.io/Documentation/Survey-Creator/?id=Add-Survey-Creator-into-your-Web-Page

**Comment by tsv2013** [comment]
I've fixed the issue. Site will be updated soon.
