### ISSUE TITLE
I cannot see text I am typing for Surveyjs creator Question title or for Choices

### ISSUE THREAD

**Issue by parmardhara** [surveyjs/survey-creator#641]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

When editing text, text runs off screen behind frame to the left / I cannot see text I am typing

### What is the expected behavior?

When editing text, text should not run off and I should be able to see what I am typing

### How would you reproduce the current behavior (if this is a bug)?

type the question title in survey js creator with letters more than 50

![issue](https://user-images.githubusercontent.com/51152178/70984331-49bb5b80-20e0-11ea-9d40-f0a5c9146545.png)

**Comment by tsv2013** [comment]
The current behavior on our site is the following: inpalce editor grows then you typing. It can stops for fixed columns count because otherwise it will brake layout.

**Comment by parmardhara** [comment]
@tsv2013 Is there any alternative suggestion for the issue I have posted?

**Comment by tsv2013** [comment]
The current behavior on our site is:
![image](https://user-images.githubusercontent.com/3013415/71068202-49c26680-2187-11ea-9e82-71e30bc3844e.png)
(input grows during typing)

If you have an issue with it, please provide us with the steps to reproduce

What version of SurveyJS Creator are you using?

**Comment by parmardhara** [comment]
@tsv2013 Currently I am using version 1.1.18 of SurveyJS Creator

**Comment by tsv2013** [comment]
The current version is the 1.1.24

**Comment by parmardhara** [comment]
@tsv2013 Alright, Thank you I will update my current version of surveyjs creator to the latest release version
