### ISSUE TITLE
hideAdvancedSettings do nothing

### ISSUE THREAD

**Issue by mgralikowski** [surveyjs/survey-creator#642]
I would to hide Advanced Setting tab on default so i try:

``` 
let options = {
    haveCommercialLicense: true,
    showTestSurveyTab: false,
    hideAdvancedSettings: false,
};

let surveyCreator = new SurveyCreator.SurveyCreator('survey-creator-container', options);
```

https://surveyjs.io/Documentation/Survey-Creator/?id=SurveyCreator#hideAdvancedSettings

But it doesn't work. No difference on true or false - is always open. Other option - showTestSurveyTab works well.

Btw, are you sure is logic correct. For me, TRUE value is more appropriate to hiding tab.

Version: v1.1.26

**Comment by mgralikowski** [comment]
Ok, i know the answer. I need to change it after creator init. But how to distinguish attributes which can be in options object, and another after init only?

**Comment by tsv2013** [comment]
All properties in documentation (https://surveyjs.io/Documentation/Library/?id=surveymodel) are the properties of a survey model instance. Some of them can be used as options.

Unfortunately this is not described in our documentation.
We need to update our documentation accordingly.

**Comment by mgralikowski** [comment]
Tag or sth would me nice.

Any difrrence between using config object or instance? Performance or sth?

**Comment by tsv2013** [comment]
Different semantics only. Probably options as an object will be useful for some cases. No performance differences or something else.

**Comment by mgralikowski** [comment]
For me, less code and more clear options object version.
