### ISSUE TITLE
The navigator buttons between tab pages doesn't work

### ISSUE THREAD

**Issue by mgralikowski** [surveyjs/survey-creator#643]
The navigator button between tab pages doesn't work. Nothing happens, no errors. Also in demo - https://surveyjs.io/create-survey/ 

v: 1.1.26

**Comment by tsv2013** [comment]
Could you specify - what do you mean under "the navigator button between tab pages"?

**Comment by tsv2013** [comment]
If you are talking about the browser navigation (back/forward) between SurveyJS Creator tabs - the creator doesn't have this feature out-of-the-box. It can be implemented via custom JavaScript code.

**Comment by mgralikowski** [comment]
![Screenshot_20191230-114105_Chrome](https://user-images.githubusercontent.com/17027876/71578720-9ac44a00-2af9-11ea-99b4-57bee378f518.jpg)
I mean this two buttons with arrows.

**Comment by tsv2013** [comment]
Thank you for the clarification. These are the scroller buttons, they scroll tabs when not all tabs are visible.

We can try to hide them in case of no scrolling.

**Comment by mgralikowski** [comment]
Yes, would be nice. On PC screen i need 13< pages to appear scroller , so for me it's rare case and it make some confusion.

**Comment by tsv2013** [comment]
I've implemented it via the https://github.com/surveyjs/survey-creator/commit/b498765e7e8f861087c6ccf4bdc68eeb7ddabfb8 commit.

Now nav buttons will be visible for the scrolled content only.
