### ISSUE TITLE
New values for surveyjs creator question choices for question type as "dropdown" doesn't gets reflected in surveyjs creator

### ISSUE THREAD

**Issue by parmardhara** [surveyjs/survey-creator#644]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?

Currently I am being able to set the choices value for question type as dropdown in surveyjs creator and current behavior is that the new values are not being reflected in the surveyjs creator

### What is the expected behavior?

New choice value should get reflected in surveyjs creator espically for question type such as "dropdown"

#### Provided is the test code :
Below is the screen for surveyjs creator issue where new values are not being reflected:

![creator](https://user-images.githubusercontent.com/51152178/71639944-fa138d00-2ca6-11ea-891c-de01d0fbd5f4.JPG)

Below is the screen for console where new values are being reflected:

![console](https://user-images.githubusercontent.com/51152178/71639954-2e874900-2ca7-11ea-89d3-b0b8b625643c.JPG)

```
var q = options.question
      var t = q.getType()
      if (q.choices) {
        let no = 1
        for (let ch in q.choices) {
          if (t === 'radiogroup' || t === 'checkbox' || t === 'dropdown') {
            q.choices[ch].value = 'answer' + no
            no++
          }
        }
      }

```

### Specify your

* browser: Google Crome 
* surveyjs creator version: 1.1.24

**Comment by tsv2013** [comment]
Can you provide us with a plunker (or any other live) sample illustrating the issue?

**Comment by parmardhara** [comment]
I tried using below piece of code and it fixed my issue: 

```
var creator = new SurveyCreator.SurveyCreator("creatorElement", creatorOptions);
//Add all countries question into toolbox
creator
    .toolbox
    .addItem({
        name: "countries",
        isCopied: true,
        iconName: "icon-default",
        title: "All countries",
        json: {
            "type": "dropdown",
            optionsCaption: "Select a country...",
            choicesByUrl: {
                url: "https://restcountries.eu/rest/v2/all"
            }
        }
    });

```
