### ISSUE TITLE
Multiline text

### ISSUE THREAD

**Issue by blevantovych** [surveyjs/survey-creator#646]
Is it possible to create a question in survey creator that spans multiple lines?

**Comment by tsv2013** [comment]
In case of editable lined you can use the [multipletext](https://surveyjs.io/Examples/Library/?id=questiontype-multipletext&platform=jQuery&theme=modern) question. By default input blocks will be one below one

**Comment by blevantovych** [comment]
Unfortunately, multiple text question is not an option.
I want something like this
![image](https://user-images.githubusercontent.com/7528319/72338879-16172580-36ce-11ea-9317-01879a603e36.png)

**Comment by tsv2013** [comment]
This question is rather related to the https://github.com/surveyjs/survey-library project.

There is no such a feature out-of the box

The easiest way IMHO to achieve this behavior is to use the https://surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderQuestion event to render additional markup. Here is the sample - https://surveyjs.io/Examples/Library/?id=survey-afterrender&platform=jQuery&theme=modern

After you implement this for survey-library you will need to subscribe the https://surveyjs.io/Documentation/Survey-Creator/?id=surveycreator#onSurveyInstanceCreated event of creator and this behavior will be supported in SurveyJS Creator

**Comment by blevantovych** [comment]
@tsv2013 Thank you for your response, but I would like this feature to be available on the UI of survey-creator (for example by pressing Shift+Enter) so that nontechnical users can use it.

**Comment by saouas** [comment]
Hello @tsv2013 ,

I am joining to the conversation because i would like just to add some break line in description field and it seems that does't work.
Is there a way to achieve this without add some additional markup for non-technical user of survey-creator ?

Thanks you,

**Comment by JaneSjs** [comment]
Enable the [Markdown text formatting](https://surveyjs.io/form-library/examples/edit-survey-questions-markdown/reactjs) and use the `<br>` tag to display the text on a new line. Consider the following demo: [View Plunker](https://plnkr.co/edit/kEGsJptfRcj88e8A).

![image](https://github.com/user-attachments/assets/51b8ddc5-b0e8-403c-8479-8dddffe275d4)
