### ISSUE TITLE
SurveyCreator is a component?

### ISSUE THREAD

**Issue by benoitgossetinnovhealth** [surveyjs/survey-creator#648]
Hello,
Can you use SurveyCreator like a component?
![codeSurvey](https://user-images.githubusercontent.com/57480992/72436618-28ae5f00-37a1-11ea-9a05-30df9c383b34.png)
![bug](https://user-images.githubusercontent.com/57480992/72436626-2d731300-37a1-11ea-9051-ff044268382a.png)

**Comment by tsv2013** [comment]
Yes. Here is the sample repo - https://github.com/surveyjs/surveyjs_react_quickstart

**Comment by benoitgossetinnovhealth** [comment]
It's surveyJs, no survey creator.
I don't understand my error, why "TypeError: this is undefined" ?

**Comment by tsv2013** [comment]
It's SurveyJS Creator as well.
Please check the https://github.com/surveyjs/surveyjs_react_quickstart/blob/master/src/SurveyCreator.js file and https://github.com/surveyjs/surveyjs_react_quickstart/blob/master/src/App.js#L362 string

Nobody reported this error before. Please provide us with a live sample illustrating the issue.
