### ISSUE TITLE
Bootstrap 4 + SurveyJS Creator Styling issues

### ISSUE THREAD

**Issue by BraedonWooding** [surveyjs/survey-creator#649]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

There are tons of styling issues (plunker provided) in relevant section.

- Closing a menu button is offset weirdly
- All buttons for logic flow (like adding triggers) are placed really weirdly

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/UC9rlGoPZbU7HP1BYg4Y?p=preview

### Specify your

* browser: chrome Version 79.0.3945.117 (Official Build) (64-bit)
* editor version: newest and occurs on all bootstrap 4 versions (tested newest and oldest and some inbetween)

**Comment by tsv2013** [comment]
This definitely is a bug.

Just to clarify.
Do you mean this
![image](https://user-images.githubusercontent.com/3013415/72814215-bb556f00-3c75-11ea-9ff6-2b2ae14ab292.png)
and this
![image](https://user-images.githubusercontent.com/3013415/72814286-da540100-3c75-11ea-9157-f62f866a23e0.png)
?

**Comment by BraedonWooding** [comment]
Those both seem a bit off but the following are much more severe.
![Screen Shot 2020-01-22 at 10 50 25 am](https://user-images.githubusercontent.com/22880786/72853280-0cf90a80-3d05-11ea-9ab9-f0f7c175e9f7.png)
The button should be to the right and the title should be left aligned.

And

![image](https://user-images.githubusercontent.com/22880786/72853327-2bf79c80-3d05-11ea-8185-2a15cdae16fd.png)

The X button is very weird looking and misaligned

**Comment by BraedonWooding** [comment]
Closing since these issues no longer exist on the latest build :)
