### ISSUE TITLE
Overlay disappears on mouse up

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#650]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
When selecting text on an overlay, for example question details, the overlay disappears.

### What is the expected behavior?
The overlay should only disappear when a click happens outside the popup.

### How would you reproduce the current behavior (if this is a bug)?
1. Go to question details
2. Mouse down in a text field (to start selecting text)
3. Move the mouse left until it is outside the details popup (this selects all text in the text field)
4. Release the mousebutton to make the selection final.

It seems to work on Firefox.

Short video of the issue here: https://drive.google.com/open?id=1YwtNMdvt9h68xSw-PW7skiwOHUwiV1Nb

#### Provide the test code and the tested page URL (if applicable)
Tested on the demo page: https://www.surveyjs.io/Survey/Builder/

### Specify your

* browser: Chrome Version 79.0.3945.117 (Official Build) (64-bit)
* editor version: 1.1.32

**Comment by gologames** [comment]
Hello,

We added `closeModalOutside` option to SurveyCreator object [via this commit](https://github.com/surveyjs/survey-creator/commit/359bcf3b6bc9bad51410f3b52f09bcd3f25488fa) with "off" (by default), "cancel", "apply" values and fix closing modal by not mousedown event

Thanks, Alex
SurveyJS Team
