### ISSUE TITLE
Custom Property number type doesn't support decimal?

### ISSUE THREAD

**Issue by broom9** [surveyjs/survey-creator#652]
### Are you requesting a feature, reporting a bug or ask a question?

Requesting a feature

### What is the current behavior?
If I add a custom property as "number" type like below, it doesn't allow demical input such as "1.99":
```
Survey.Serializer.addProperty("question", {
      name: "cost:number",
      default: 5,
      minValue: 0,
      maxValue: 100
    });
```
### What is the expected behavior?
Support the "step" attribute of knockout input component and allow decimal input.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@broom9 Do you want to introduce new attribute "step" in JsonProperty?
I have just checked in v1.5.1 and the following code works fine:
```js
Survey.Serializer.addProperty("question", {
      name: "cost:number",
      default: 5.5,
      minValue: 0.5,
      maxValue: 100.3
    });
```
