### ISSUE TITLE
Register custom validators

### ISSUE THREAD

**Issue by dsimoes** [surveyjs/survey-creator#653]
I've registered custom validators for my Survey.

Is It possible to register those custom validators on the Creator so that they can be sucessfuly tested on the Test Survey tab?

Thanks.

**Comment by gologames** [comment]
Hello,

You can use `onTestSurveyCreated` [event](https://surveyjs.io/Documentation/Survey-Creator/?id=surveycreator#onTestSurveyCreated) to register your validators in test survey instance

Thanks, Alex
SurveyJS Team

**Comment by dsimoes** [comment]
Hi @gologames 

It's not clear where I can register the validation functions.
On the library documentation [example](https://surveyjs.io/Examples/Library/?id=validators-custom&platform=jQuery&theme=modern) I need to execute the following:

Survey
    .FunctionFactory
    .Instance
    .register("MyTextValidator", MyTextValidator);

The event you mentioned has the SurveyCreator as parameter. Where in this structure can I do the same registration?

Thank you!

**Comment by gologames** [comment]
Hello,

Understood you. In case you are using Knockout version of SurveyModel you can just register custom validator as shown in your example above (here is [live sample in plunker](https://next.plnkr.co/edit/BLuFZsHdyuZcPZFo)). Otherwise you need to register custom validator to your instance of SurveyModel (React/Angluar/etc versions)

Thanks, Alex
SurveyJS Team

**Comment by dsimoes** [comment]
Hi,

I see. But I'm using the React version of Survey which is different from the Creator.
My packages are are:

    "survey-react": "^1.5.2",
    "survey-creator": "^1.5.1",

To register on the creator I had to reference the internal creator knockout implementation:

import * as SurveyCreator from "survey-creator";
import * as SurveyKo from "survey-creator/node_modules/survey-knockout";

 SurveyKo.FunctionFactory.Instance.register("MyFunc", MyFunc);

**This worked. Thanks for your help!**
