### ISSUE TITLE
Cannot drag and drop questions on iphone

### ISSUE THREAD

**Issue by MasafumiTokiwa** [surveyjs/survey-creator#656]
Hello!
On iphone, drag and drop was not possible when placing and sorting questions.
Isn't iphone supported?
I was able to drag and drop on ipad.

* ios version: 13.3
* device: iPhone XR
* survey-creator version: v1.5.5

![image](https://user-images.githubusercontent.com/9333050/73714180-7b9d8580-4753-11ea-9517-c5f5af6035a3.png)

**Comment by tsv2013** [comment]
Originally SurveyJS Creator wasn't designed to be used on mobile devices, especially phones. It definitely should support tablet formats as it does as you wrote.

**Comment by tsv2013** [comment]
We'll keep in mind this enhancement in future releases. We'll update this thread immediately as soon as it will be implemented.
