### ISSUE TITLE
Weird behavior for showPropertyGrid

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#657]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
There is a `showToolbox` property that is of type  `boolean` according to the docs. https://surveyjs.io/Documentation/Survey-Creator/?id=surveycreator#toolbox

The new example shows that the new property grid supports another value: 
```js
//Show toolbox in the right container. It is shown on the left by default
creator.showToolbox = "right";
```

But passing in the value `right` as part of the options leads to an error.

### What is the expected behavior?
The `showToolbox` property should have a clearly defined type and it should not matter whether it is passed via the options upon construction or set later.

### Specify your

* browser: Chrome, latest
* editor version: 1.5.5

**Comment by andrewtelnov** [comment]
@SamMousa It works fine to me. Here is [the example](https://plnkr.co/edit/0NEy3lMMSxhnlR2YUoPl?p=preview).

Thank you,
Andrew

**Comment by SamMousa** [comment]
Apologies, you're right. I meant another property: 'showPropertyGrid'.
```
survey-creator.min.js:12 Uncaught TypeError: this.koSelectedObject is not a function
    at e.get [as selectedElement] (survey-creator.min.js:12)
    at e.set [as showPropertyGrid] (survey-creator.min.js:12)
    at e.setOptions (survey-creator.min.js:12)
    at new e (survey-creator.min.js:12)
    at HTMLDocument.document.addEventListener.passive (build?id=21:566)
```

**Comment by tsv2013** [comment]
I've reproduced the issue

**Comment by tsv2013** [comment]
Fix will be available in the nearest update, most likely tomorrow.
