### ISSUE TITLE
Localization Add New button

### ISSUE THREAD

**Issue by gdet** [surveyjs/survey-creator#658]
Hello,

is it possible to translate button "Add new" and "Remove" when you add extra questions. It is translated in Italian for example but not in Greek, Swedish etc.

Thank you

**Comment by andrewtelnov** [comment]
@gdet Sure, please read [this doc section](https://surveyjs.io/Documentation/Survey-Creator/#localization) and [readme file](https://github.com/surveyjs/survey-creator/tree/master/src/localization)

Thank you,
Andrew

**Comment by gdet** [comment]
Thank you for your answer, but I have already seen this values. I cannot find the proper value to change. I am speaking about paneldynamic object and the "Add New" and "Remove" button it show if the user of the questionnaire wants to add a new object. If I use survey.completeText for example I can get the "Complete" value but I cannot find "Add New" value.

I tried 

       survey.addNew =''
       survey.panelAddText=''
       survey.panelRemoveText=''

nothing is working.

Thank you

**Comment by gdet** [comment]
The solution is: 

      "type": "paneldynamic",
      "panelAddText":   {
                "de": "Add",
                 "it": "Inserisci",
                "gr": "Εισαγωγή",                                                                                                                             
                "sv":"Lägg till",
                "cz":"Přidat"
            },


Thank you
