### ISSUE TITLE
Removing inherited properties from child classes does not work

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#660]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Removing inherited properties no longer works from child classes no longer works.

### What is the expected behavior?
```js
//remove a property to the page object. You can't set it in JSON as well
Survey
    .Serializer
    .removeProperty("page", "visibleIf");
```
This code should remove the `visibleIf` property, but it does not work. 
Using the browser console to execute `Survey.Serializer.findClass('page')`:
Shows that there are 3 properties on the `page` class, I'm assuming the rest is inherited.
Hiding one of these properties works as expected:
```js
//remove a property to the page object. You can't set it in JSON as well
Survey
    .Serializer
    .removeProperty("page", "maxTimeToFinish");
```

### How would you reproduce the current behavior (if this is a bug)?
The big is present in the demo: https://www.surveyjs.io/Examples/Builder/?id=removeproperties
Just confirm that pages have the `visibleIf` property, although they should not.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://www.surveyjs.io/Examples/Builder/?id=removeproperties

### Specify your

* browser: Chrome 
* editor version: 1.5.5

**Comment by tsv2013** [comment]
Probably this was the bad example. I've tested it down to v1.0.30 (~ July 2018) - https://plnkr.co/edit/VHTrA4m03Ir3Pz9ioMMG?p=preview - it didn't work for inherited properties.

It looks like this shouldn't work this way. The "visibleIf" property should be removed from the "panelbase" class and added to the "panel" class as a new one.

Support this scenario will require rather large amount of work to be implemented in spite of minimal result. And if you don't have any other arguments to discuss, I think we'll not support this behavior.

**Comment by SamMousa** [comment]
> Support this scenario will require rather large amount of work to be implemented in spite of minimal result. And if you don't have any other arguments to discuss, I think we'll not support this behavior.

Sounds good to me, in that case docs need to be updated though!
The work around of just hiding the properties in the editor via the callback is good enough for most cases anyway.

**Comment by tsv2013** [comment]
@SamMousa Thank you! I highly appreciate your understanding. We'll update the docs ASAP.

**Comment by inzi** [comment]
I'm trying to learn how to hide properties - so many can overwhelm the user.

Can you point me to where in the documentation I can get an idea on how to hide all properties for a widget that aren't necessary to show the user?
