### ISSUE TITLE
in survey setting not able to remove tabs

### ISSUE THREAD

**Issue by parthfaladuks** [surveyjs/survey-creator#663]
### Are you requesting a feature, reporting a bug or ask a question?
reporting a bug

### What is the current behavior?
not able to remove tabs from survey settings

### What is the expected behavior?
we can remove tabs from survey settings.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/bFpPjhEk7ncKufITGxuX?p=preview

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* editor version: 1.5.8

**Comment by tsv2013** [comment]
If you move tabs removal code before creator instantiated, it works ok for me - https://plnkr.co/edit/gEEY1or9xzfGZmjSGnhY?p=preview

**Comment by parthfaladuks** [comment]
yes like that it's working but as you can see it's generating new tab as **Others** . is there any way to remove that **Others** tab ?

Thank you for quick response.

**Comment by parthfaladuks** [comment]
@tsv2013  hello any updates ?

**Comment by tsv2013** [comment]
Sorry for the late response. Here is the working sample - https://next.plnkr.co/edit/gOOskVgrKOUSUeU4

Does it fit your needs?

**Comment by parthfaladuks** [comment]
@tsv2013  no i just want to show general tab and inside three properties Title, Description and Show/Hide toggle not any other properties.

Thank you for the replay

**Comment by andrewtelnov** [comment]
We missed this one. Here is [the working example](https://plnkr.co/edit/GKBKokd9HJLVRIl6).

Thank you,
Andrew
