### ISSUE TITLE
Collapse toolbox categories

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#669]
### Are you requesting a feature, reporting a bug or ask a question?
Feature

### What is the current behavior?
You can collapse categories by opening other categories, not by clicking on an already opened category.

### What is the expected behavior?
Often in accordeon type UIs clicking the header of an open category closes it.
Consider I have a generic category (with 50+ items) and a custom category with some items. I can set the editor to close all categories on loading, but when someone opens the generic category they have to scroll all the way down to open the custom category.

**Comment by andrewtelnov** [comment]
@SamMousa Please set to true ``toolbox.allowExpandMultipleCategories `` property: 
```js
creator.toolbox.allowExpandMultipleCategories = true;
```
Here is [the example](https://plnkr.co/edit/qazveo0JWcqjNmOcHRaB?p=preview).

Thank you,
Andrew

**Comment by SamMousa** [comment]
That's good enough for me, note that collapsing is not related to opening multiple.
Regardless of if I want to allow multiple categories to be open I'd want to be able to close by clicking the header.
Anyway, for my use case this is good enough!
