### ISSUE TITLE
Can't update survey attributes in modal mode

### ISSUE THREAD

**Issue by mgralikowski** [surveyjs/survey-creator#674]
There is fatal error on modify any survey attribute but only in "modal mode". I prefer modal than tab so it's critical for me.

`  Cannot set property pages of #<SurveyModel> which has only a getter`

Instruction:

1. Go to: https://surveyjs.io/Examples/Survey-Creator/?id=options&theme=bootstrap
2. Change mode to "Show toolbox in right container and hide property grid".
3. Open settings modal.
3. Change any survey attribute and click "Apply".

* browser: any.
* editor version: 1.5.10

**Comment by andrewtelnov** [comment]
@mgralikowski I have added a new Unit Test and fix the issue. It will be available in the next minor v15.11

Thank you,
Andrew

**Comment by mgralikowski** [comment]
Thanks for fast reply.

Btw, is modal mode abandoned or less preferable than tab with attributes? It was hard for me to find way to back to modal editor.

**Comment by andrewtelnov** [comment]
@mgralikowski Option ``showElementEditorAsPropertyGrid: false`` will turn on the old mode.
New UI allows to remove modal windows and make the property changing interactive. You can see the changes in the new property grid immediately you have made them.
Based on our talks with our customers from large enterprises, their end-users did not use the old property grid  and modal-less UI is more prefertable .

Thank you,
Andrew
