### ISSUE TITLE
Sample creator pages use wrong Knockout version

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#676]
### Are you requesting a feature, reporting a bug or ask a question?
Question

### What is the current behavior?
This page https://surveyjs.io/create-survey shows a survey creator.
Survey creator `1.5.10` depends on knockout `>3.5.1`, but the included version: `https://surveyjs.io/Scripts/knockout.js` does not satisfy that constraint.

### What is the expected behavior?
I expect to be able to use that page to (try to) reproduce bugs and to find out if it's my setup / code or yours that's causing issues.

**Comment by tsv2013** [comment]
We wanted to support KO 3.4 as well. We didn't expected backward incompatibilities here.
