### ISSUE TITLE
[Bug] Cursor getting displaced in the JSON Editor after indentation

### ISSUE THREAD

**Issue by starg09** [surveyjs/survey-creator#678]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug

### What is the current behavior?

When editing the json of my survey, I noticed the cursor placed further to the right compared to its actual position (making editing a bit more annoying, having to properly predict what text is being marked/deleted/where its being added)

### What is the expected behavior?

The cursor to work properly, including highlighting the correct area,

### How would you reproduce the current behavior (if this is a bug)?

It seems to happen after a certain amount of indentation, either with tabs or spaces. More specifically, every 4 spaces (which convert into a tab inside the editor, apparently?). Each set of 4 spaces increases the displacement by one character.

#### Provide the test code and the tested page URL (if applicable)

It seems to be code independent, tested on a blank survey with same results: [Here's a video showcasing the bug](https://streamable.com/a513p). 

### Specify your

* browser: Chrome Beta 81.0.4044.26 (Tested on stable chrome as well, 79.0.3945.130)
* editor version: 1.5.10 (the version on the web)

**Comment by tsv2013** [comment]
Do you have the Ace editor loaded on your page?

**Comment by tsv2013** [comment]
Unfortunately referenced video isn't available.

**Comment by starg09** [comment]
Video seems to load fine over here? (Even on incognito)

Here's a mirror on google drive, hopefully that works: https://drive.google.com/file/d/1Kp9Rlz9694kNYf323C6kprn4T28Ejodq/view?usp=sharing

**Comment by tsv2013** [comment]
Looks like fixed. See the https://surveyjs.answerdesk.io/ticket/details/t4069/json-editor-consistently-renders-caret-in-the-wrong-place thread for more details.
