### ISSUE TITLE
Can't render Survey Creator after loading

### ISSUE THREAD

**Issue by Platinate** [surveyjs/survey-creator#680]
Hello,

For one of my projects, I must store the json generated by Survey Creator in a database.
Everything working fine except at the moment I must render Survey Creator after the datas has been loaded.
I'm currently using React with Mobx.

Here is the code  
 ```
if(loadingInitial) return <LoadingComponent/>
  return (<PageCreator page={page}/>);
```
As you can see, I only render creator if the datas are loaded but if I do that It generate an error.
![image](https://user-images.githubusercontent.com/51859467/75318170-fbf26a80-5869-11ea-9681-31465f3c4e8c.png)

I don't have the problem if I render directly Survey Creator but then it render an empty Creator and after a few seconds rerendered it with the data/JSON who is not a expected behavior.

Have you an solution/idea on How I could implement this ?

Thank you

**Comment by tsv2013** [comment]
Can you provide us with a live sample illustrating the issue?

**Comment by Platinate** [comment]
I've found a workaround by loading and displaying the survey editor at the same time,I have no fatal errors anymore. But I see that the style theme "default" is lacking of some style compared tot the exemple on your website. I'm using actually material-ui for React. It is possible that there is some conflicts between the surveyJS editor theme style and material-ui ?
![image](https://user-images.githubusercontent.com/51859467/75418962-07f72e80-5935-11ea-86e6-53235e42c28e.png)

**Comment by andrewtelnov** [comment]
@Platinate It is possible there is a conflict, if material-ui overrides some styles. Could you do not render material-ui for the page where SurveyJS Creator is located?

Thank you,
ANdrew
