### ISSUE TITLE
survey Creator JSON editor not updating

### ISSUE THREAD

**Issue by shekharkc** [surveyjs/survey-creator#681]
### Are you requesting a feature, reporting a bug or ask a question?

Bug 
Question

### What is the current behavior?

We were testing out the features of the SurveyJS library and the Survey Creator to see if it meets our requirements. 

When we try to load (paste) a valid json into the json editor window, it doesn't update (the editor window remains blank). 

![image](https://user-images.githubusercontent.com/32909897/75389336-5d6b1580-590c-11ea-9333-3789441e82c1.png)

It however appears to be functioning just fine with a smaller json. 

The size of the json I am trying to load is as follows:

words - 3250
characters (without spaces) - 80,912 
characters (with spaces) - 84,161

I am not too sure if this behavior is due to the size of the JSON or due to a bug in the code.

### What is the expected behavior?

The editor is expected to update with the pasted text.

#### Provide the test code and the tested page URL (if applicable)

No code as we were trying to test the Survey Creator GUI.

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* editor version: v 1.5.10

**Comment by tsv2013** [comment]
You can ask your questions here or here - https://surveyjs.answerdesk.io/ticket/details/t3495/no-response-from-test-survey-survey-designer-and-other-tabs-after-pasting-a-long-json-in
