### ISSUE TITLE
No response from Test Survey, Survey Designer and Other Tabs after pasting a long JSON in the JSON editor

### ISSUE THREAD

**Issue by shekharkc** [surveyjs/survey-creator#682]
### Are you requesting a feature, reporting a bug or ask a question?

Bug 

### What is the current behavior?
This is a follow up to the lack of response from JSON editor question a little while ago.

I trimmed the size of the survey and was able to paste the JSON in the JSON Editor. It still is a long survey.

Now, there is no response from the Test Survey, Survey Designer and the other Tabs (you cannot edit or test run the survey).

I presume it again has something related to the size of the JSON or is it some other issue? Now, we are not too sure if the survey will actually run or not, if same is served to the front end and imported to surveyjs.

The JSON is valid.

JSON Size we were testing  is as below: 
Words - 487
Chars without spaces - 68018
chars with spaces - 68504

### What is the expected behavior?
Once the JSON is valid and pasted, the Test survey, Survey designer are expected to function normally.

#### Provide the test code and the tested page URL (if applicable)
No code as we were testing the Survey Creator GUI
Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* editor version: v 1.5.10

**Comment by tsv2013** [comment]
You can ask your questions here or here - https://surveyjs.answerdesk.io/ticket/details/t3495/no-response-from-test-survey-survey-designer-and-other-tabs-after-pasting-a-long-json-in
