### ISSUE TITLE
readOnly attribute on adding property has no effect

### ISSUE THREAD

**Issue by mgralikowski** [surveyjs/survey-creator#683]
### Are you requesting a feature, reporting a bug or ask a question?

Bug.

### What is the current behavior?

`readOnly` for question has no effect

### What is the expected behavior?

Make input disabled / not editable.

### How would you reproduce the current behavior (if this is a bug)?

```
Survey.Serializer.addProperty('question', {
    maxLength: 15, // it works
    readOnly: true, // it doesn't
    name: 'sourceTitle',
    category: 'general'
});
```

v: 1.5.10

**Comment by andrewtelnov** [comment]
@mgralikowski The bug is fixed via commit above. It should be included into today release v1.5.11

Thank you,
Andrew
