### ISSUE TITLE
Version 1.5.11 breaks reordering questions via DnD

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#684]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Drag & drop is broken in v1.5.11, you can't reorder questions

### How would you reproduce the current behavior (if this is a bug)?
- Go here: https://surveyjs.io/create-survey
- Try to swap 2 questions via DnD

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjs.io/create-survey

### Specify your

* browser: Chrome latest
* editor version: v1.5.11

**Comment by andrewtelnov** [comment]
@SamMousa New release is available. The issue is fixed.

Thank you,
Andrew
