### ISSUE TITLE
When set showJSONEditorTab = false , the question not showing in the editor

### ISSUE THREAD

**Issue by imadhussein** [surveyjs/survey-creator#688]
### Are you requesting a feature, reporting a bug or ask a question?

a bug

### What is the current behavior?
When set showJSONEditorTab = false 

The editor will not show the question

### What is the expected behavior?

The editor should show the question

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome 
* editor version: Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by tsv2013** [comment]
Could you describe - how we can reproduce it?
