### ISSUE TITLE
Toolbox customization. Possibility to add pre-filled page.

### ISSUE THREAD

**Issue by Platinate** [surveyjs/survey-creator#698]
Hello,

Is it possible for now to customize the toolbox in order to add pre constructed pages ?

For now, here it is what I am trying to do.

```
this.surveyCreator.toolbox.clearItems();
tools.forEach(([group, pages]) => {
      pages.forEach(page => {
        this.surveyCreator.toolbox.addItem({
          name: page.name,
          isCopied: false,
          iconName: "icon-default",
          title: page.name,
          category: `CUSTOM : ${group}`,
          json: {
            type: "page"
            // NOT VERY SURE OF WHAT  TO PUT THERE 
          }
        });
      });
    });
```

And here it's the sort of JSON I'm trying to insert

```
"{
   "name": "page1",
   "elements": [
      {
         "type": "checkbox",
         "name": "question1",
         "choices": [
            "item1",
            "item2",
            "item3"
         ]
      },
      {
         "type": "dropdown",
         "name": "question2",
         "visibleIf": "{question1} = ['item2']",
         "requiredIf": "{question1} = ['item2']",
         "choices": [
            "item1",
            "item2",
            "item3"
         ],
         "hideIfChoicesEmpty": true
      },
      {
         "type": "html",
         "name": "question3"
      }
   ]
}"
```

Thank you

**Comment by andrewtelnov** [comment]
@Platinate Here is [the example](https://surveyjs.io/Examples/Survey-Creator?id=toolboxcustomization) of toolbox customization and to set your json, you have to set creator JSON property: ```creator.JSON = yourJSON;```

Thank you,
Andrew

**Comment by Platinate** [comment]
Tank you for your quick response.
Maybe I didn't understand but I was more in this idea :

![image](https://user-images.githubusercontent.com/51859467/76076347-fcdc7800-5f9e-11ea-8782-f4c8820b6dc1.png)

So a the end, the survey should have 1 or more pages following the pages I've selected.
It is possible actually ? Or it will ask to rewrite the action ?

**Comment by andrewtelnov** [comment]
@Platinate You can't do this, you can insert a panel with a lot of questions or nested panel into a page, but you can't replace the whole survey by clicking an item on Toolbox. IMHO, it is a strange UIX decision.
Here is [the example](https://surveyjs.io/Examples/Survey-Creator?id=tabscustomization) that shows how to insert a tab that contains survey templates.

Thank you,
Andrew
