### ISSUE TITLE
Update page editor toolbar UI

### ISSUE THREAD

**Issue by BraedonWooding** [surveyjs/survey-creator#701]
### Are you requesting a feature, reporting a bug or ask a question?

Requesting a feature that I'm willing to implement.  The page editor toolbar (the list of pages and add page button at the top)

We are looking to implement this feature on our side but we wish to avoid having to manage a fork.  I believe the quality of such a toolbar is higher and would be beneficial to most.

### What is the current behavior?

![image](https://user-images.githubusercontent.com/22880786/76157475-525e8380-615d-11ea-8509-af55a1f8815f.png)

### What is the expected behavior?

We currently have a custom version that is similar in style to this;

![image](https://user-images.githubusercontent.com/22880786/76157455-1f1bf480-615d-11ea-92f9-50c3d3f82af9.png)

### Differences

- Dropping the user of the dropdown, it just confuses users (in our cases) and is much better represented through the list of pages.
  - I would be open to making this optional though
- Cleaning up the connection between the page editor and the page
- Moving the add page button and making it clearer (from our research we've found that users struggle to find the add page button)
- Swapping the gear for 3 vertical dots however I am more open to keeping this as a gear or using some kind of option to swap it.

**Comment by andrewtelnov** [comment]
@BraedonWooding I agree that we need an option for hiding the drop down element from the page bar. There are many scenarios, from single page survey (you can hide page bar and page object in the property grid), to surveys with 30+ pages, where there is a need in drop down.
About moving “Add new page” button and adding text. It looks reasonable to me. Probably we need to set a different font/color for it.
We will talk with our designer on next week and come back to you.

Thank you,
Andrew

**Comment by tsv2013** [comment]
Some improvements has been done via the https://github.com/surveyjs/survey-creator/commit/574b1f37dccbb7149441b7b266facd80672a10d5 commit to implelement the https://github.com/surveyjs/survey-creator/issues/714 

Add an option to hide dropdown page selector
Move the "Add new page" button closer to pages
Implement dynamic scrolling

![image](https://user-images.githubusercontent.com/3013415/77665998-74476b00-6f91-11ea-9d84-90ed70dcc8e4.png)

In order to hide dropdown page selector one need to set the following option:
```JS
  var options = {
    showDropdownPageSelector: false
  };
  var creator = new SurveyCreator.SurveyCreator("creatorElement", options);

**Comment by BraedonWooding** [comment]
Looks great :)

**Comment by petro-sam** [comment]
Looks like broken functionality
https://plnkr.co/edit/15F960kTZdOvxtAE

**Comment by andrewtelnov** [comment]
@petro-sam I have fixed the bug. Here is [the related GitHub issue](https://github.com/surveyjs/survey-creator/issues/1578).

Thank you,
Andrew
