### ISSUE TITLE
HTML Question on PropertyChanged

### ISSUE THREAD

**Issue by siddharthdeshmukh** [surveyjs/survey-creator#704]
### Are you requesting a feature, reporting a bug or ask a question?

Feature Request/ Question

### What is the current behavior?

onPropertyChanged is not called if the html property of HTML question is updated.

### What is the expected behavior?
onPropertyChanged or any event should be fired.

#### Why this is needed?
 We want to validate/sanitize  HTML (for Cross Site scripting attacks )before submitting to server. Server is validating, but we need to do it on editor also.

### Specify your

* browser: Chrome
* editor version: 1.5.15

**Comment by tsv2013** [comment]
Espesially for this scenario SurveyJS Creator has the https://surveyjs.io/Documentation/Survey-Creator?id=surveycreator#onPropertyValueChanging event.

Here is the working sample - https://plnkr.co/edit/WJCUiAYhElDoYIds

**Comment by siddnus** [comment]
Thanks a lot. This works for me.
