### ISSUE TITLE
Not showing a survey schema with preset locale

### ISSUE THREAD

**Issue by Enkosz** [surveyjs/survey-creator#706]
1) Open SurveyCreator
2) Add any question
3) Change the locale to another from default
4) Save the survey
5) Load the creator with the saved new JSON
???

Creator not showing anything if the survey json schema contains a locale (ex: IT)
![oie_3akh7dFjzSKO](https://user-images.githubusercontent.com/35410110/77155352-a6dafa80-6a9d-11ea-98e1-9f875422b71e.png)
![oie_jDrhkVgH9LYM](https://user-images.githubusercontent.com/35410110/77155361-a93d5480-6a9d-11ea-89b1-c900a861bd51.png)

**Comment by tsv2013** [comment]
This is the JSON created by given steps. I works ok for me. Can you share a problematic one?
```JSON
{
 "locale": "de",
 "title": {
  "de": "de-t",
  "default": "ttt"
 },
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question1",
     "choices": [
      "item1",
      "item2",
      "item3"
     ]
    },
    {
     "type": "text",
     "name": "question4",
     "validators": [
      {
       "type": "numeric"
      }
     ],
     "inputType": "number",
     "maxLength": 3
    }
   ]
  },
  {
   "name": "page2",
   "elements": [
    {
     "type": "checkbox",
     "name": "question2",
     "choices": [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  },
  {
   "name": "page3",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question3",
     "choices": [
      "item1",
      "item2",
      "item3"
     ]
    }
   ]
  }
 ]
}
```

**Comment by Enkosz** [comment]
> This is the JSON created by given steps. I works ok for me. Can you share a problematic one?
> 
> ```json
> {
>  "locale": "de",
>  "title": {
>   "de": "de-t",
>   "default": "ttt"
>  },
>  "pages": [
>   {
>    "name": "page1",
>    "elements": [
>     {
>      "type": "radiogroup",
>      "name": "question1",
>      "choices": [
>       "item1",
>       "item2",
>       "item3"
>      ]
>     },
>     {
>      "type": "text",
>      "name": "question4",
>      "validators": [
>       {
>        "type": "numeric"
>       }
>      ],
>      "inputType": "number",
>      "maxLength": 3
>     }
>    ]
>   },
>   {
>    "name": "page2",
>    "elements": [
>     {
>      "type": "checkbox",
>      "name": "question2",
>      "choices": [
>       "item1",
>       "item2",
>       "item3"
>      ]
>     }
>    ]
>   },
>   {
>    "name": "page3",
>    "elements": [
>     {
>      "type": "radiogroup",
>      "name": "question3",
>      "choices": [
>       "item1",
>       "item2",
>       "item3"
>      ]
>     }
>    ]
>   }
>  ]
> }
> ```

Yeah sure, the problem is not about the created JSON survey. The problem is when setting the SurveyCreator.JSON to the created JSON survey it simply does not display anything

**Comment by andrewtelnov** [comment]
@Enkosz It [works fine](https://plnkr.co/edit/ksqlQPHhayhJy7i6) to me, in case I did not miss anything.

Thank you,
Andrew

**Comment by elisazini** [comment]
Hello,
I have the same issue, I think it's a problem with the rendering of the tab "Survey Designer". 
The json is loaded correctly in the tab "Json Editor", but nothing shows in Survey Designer. 
Then, if I add for example a space in the Json Editor, the Survey Designer re-renders and everything reappears. 
I cannot understand why it doesn't load the Designer components when I first land on the page, and why it happens only with the survey locale property set to something different than the default.

Thank you,
Elisa

**Comment by andrewtelnov** [comment]
@Enkosz @elisazini Could you please provide your code so we can reproduce and fix the issue?

Thank you,
Andrew
