### ISSUE TITLE
"set" property editor doesn't support ajax request for getting choices

### ISSUE THREAD

**Issue by xxxKOTxxx** [surveyjs/survey-creator#720]
Hello!    

To begin with, I would like to thank you for creating an excellent library!    

So it’s my turn to add tags to the question.    
The most suitable in my situation, I consider the "set" property editor.

But I have two questions:    
1) How can I get choises from the backend?    
Unfortunately choicesCallback parameter is null instead of function in choises function callback. 
It also doesn't support promises as I understand. So can you propose some other way?    

2) My backend return objects because I need to support localizations, but as I can see it supports only string values? Any suggestions?

**Comment by andrewtelnov** [comment]
@xxxKOTxxx Sorry, I could not understand your task. Do you want to get the choices for a property from a service?

Thank you,
Andrew

**Comment by xxxKOTxxx** [comment]
> @xxxKOTxxx Sorry, I could not understand your task. Do you want to get the choices for a property from a service?

Yes, i need load tag entities list from backend and show them in new file widget property as multiselect. Currently I created custom editor using select2. But it will be much easier to use set with choicesCallback if You add it.

**Comment by andrewtelnov** [comment]
@xxxKOTxxx Do you refer to [the example](https://surveyjs.io/Documentation/Survey-Creator#addproperties) that shows how to get countries from rest service?

Thank you,
Andrew

**Comment by xxxKOTxxx** [comment]
> @xxxKOTxxx Do you refer to [the example](https://surveyjs.io/Documentation/Survey-Creator#addproperties) that shows how to get countries from rest service?

Yep! But I can't use it because of null in choicesCallback

**Comment by andrewtelnov** [comment]
@xxxKOTxxx When it happens? It works for me. Here is [the example](https://plnkr.co/edit/vUq0fwmVQHqn5rWX).

Thank you,
Andrew

**Comment by xxxKOTxxx** [comment]
> @xxxKOTxxx When it happens? It works for me. Here is [the example](https://plnkr.co/edit/vUq0fwmVQHqn5rWX).


Yes, it works. But look [here](https://plnkr.co/edit/xxGrgVsHmMyoUJao)    

I just changed type to "set" (I need multiselect) and it not works any more. I log in console choicesCallback and it's null.    

That's I told about.

**Comment by andrewtelnov** [comment]
@xxxKOTxxx Got it now. "set" is property editor type. I will take a look.

Thank you,
Andrew

**Comment by xxxKOTxxx** [comment]
> @xxxKOTxxx Got it now. "set" is property editor type. I will take a look. 

Thank you! One more question: have you any example, how to correct implement nonvalue custom widet like html widget?

**Comment by andrewtelnov** [comment]
@xxxKOTxxx I added support for callback function for set property editor by the commit above. New unit test was added. The fix will come with v1.5.19 that we will release next week.

Regarding your last question, please create a new issue that we can discuss in a new thread.

Thank you,
Andrew

**Comment by xxxKOTxxx** [comment]
> Regarding your last question, please create a new issue that we can discuss in a new thread.
Thank You! 

I added new [issue](https://github.com/surveyjs/survey-creator/issues/722).

So i need to transform backend option data objects to strings in callback or there is more easiest way that I missed out?

**Comment by andrewtelnov** [comment]
@xxxKOTxxx It can be a single value or a pair value/text. Here is the example for returned choices array:
``[1, "text 2", {value: 3, text: "My Text 3"}]``

Thank you,
Andrew
