### ISSUE TITLE
Expandable/Decreasable description text in survey

### ISSUE THREAD

**Issue by Nils-DE** [surveyjs/survey-creator#721]
### Are you requesting a feature, reporting a bug or ask a question?
Question:
Is it anyhow possible to limit the length of the displayed description of the question? 
E.g. Description Text length is 1000. I want to limit the visibility in survey to 250 plus a button to expand the text: 
1) Shown description in survey: Hello World, I need h... [Click to expand] 
2) click "Expand"
3) Shown description in survey: Hello World, I need help from you!

### What is the current behavior?
Full description is always visible in survey

### What is the expected behavior?
See above, decrease/expand button for description text

### Specify your

* browser: Google Chrome 80.0.3987.149
* editor version: v 1.5.18

**Comment by andrewtelnov** [comment]
@Nils-DE You have to set up the attribute for question title property. Here is the code:
``Survey.Serializer.findProperty("question", "title").maxLength = 250;``

Thank you,
Andrew
SurveyJS Team

**Comment by Nils-DE** [comment]
Can this attribute also be set up for the description and much more important: Is the length of input limited afterwards or is the expand/collapse function automtically appearing?

**Comment by andrewtelnov** [comment]
Yes, the code is the same:
``Survey.Serializer.findProperty("question", "description").maxLength = 250;``

> is the expand/collapse function automtically appearing?
Sorry, what do you mean?

Thank you,
Andrew

**Comment by Nils-DE** [comment]
> is the expand/collapse function automtically appearing?
> Sorry, what do you mean?

The main purpose is not to limit the maxLength of the Description.
The main purpose is to implement a "show rest" function.
E.g. user is able to see text 100 of 1000 letters description text, then only (...). By clicking the (...) the rest of the text should expand and the full 1000 letters should be now visible.

**Comment by andrewtelnov** [comment]
@Nils-DE Got you now. We do not have this functionality at the current moment. You can implement it by yourself using ``survey.onAfterRenderQuestion`` event by modifying DOM. Here is [the example](https://surveyjs.io/Examples/Library?id=survey-afterrender).

Thank you,
Andrew
