### ISSUE TITLE
Use the Survey Creator to edit Survey Templates

### ISSUE THREAD

**Issue by mark-ellul** [surveyjs/survey-creator#724]
### Are you requesting a feature, reporting a bug or ask a question?

Question

Is it possible to present a survey/form to the creator that only allows the properties to be edited? i.e. no more questions can be added from the toolbox and no existing questions can be removed

So effectively making a Survey as a Template and then showing the creator for that template with only the ability to change titles and other properties, add links (as resources probably with a custom widget), add videos (as resources with a custom widget).

Are there options in the Creator to allow for only editing properties only?

**Comment by tsv2013** [comment]
You can subscribe on some events to deny adding/deleting/dragging survey elements.

Here is the working sample - https://plnkr.co/edit/OkP6sjTJYUyhhDcg

You can also check the documentation on used events/properties - https://surveyjs.io/Documentation/Survey-Creator?id=surveycreator

**Comment by mark-ellul** [comment]
thanks @tsv2013

**Comment by mark-ellul** [comment]
@tsv2013 if I wanted to not allow editing of the title of a question would I be using a similar example to the "adorners" logic at the bottom of this page? 

https://surveyjs.io/Documentation/Survey-Creator?id=Survey-Creator-Overview#toolbox

**Comment by tsv2013** [comment]
You can use the following code:
```JS
SurveyCreator.removeAdorners(["title"]);
```

**Comment by mark-ellul** [comment]
@tsv2013 thanks for all of your help!
