### ISSUE TITLE
survey-creator dependency problem

### ISSUE THREAD

**Issue by kouhunzhe** [surveyjs/survey-creator#732]
### Are you requesting a feature, reporting a bug or ask a question?

 ask a question

### What is the current behavior?
survey-creator  Import survey-ko
How to change to dependency survey-vue

### What is the expected behavior?

Hope survey-creator depends on  survey-vue

Because we need to use "survey Vue" now, some of the components may need to be dealt with, such as the introduction of element UI (https://element.element.cn/) into component interface optimization. At this time, we may not need to use survey widgets to add question types

It's very nice of you to write code. I really like it

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

Thank you
Your fans

**Comment by tsv2013** [comment]
SurveyJS Creator is built using KnockoutJS and depends on the `survey-knockout` package

**Comment by kouhunzhe** [comment]
Is there any plan to build survey-creator with vuejs, and then survey-creator depends on survey-vue

**Comment by tsv2013** [comment]
It isn't planned to build SurveyJS Creator with VueJS. It's a lot of work. It means completely re-write creator.

**Comment by kouhunzhe** [comment]
We want to use vuejs to expand the topic more conveniently, because now many components of Vue are ready to use, rather than using survey-widgets to expand. We have expanded your project several times

**Comment by kouhunzhe** [comment]
Now we want to write a Vue version of survey-creator. Do you have any better suggestions

**Comment by tsv2013** [comment]
SurveyJS Library (for all frameworks) is under the MIT license. You can use SurveyJS Creator as-is under the commercial license or write your own one based on VueJS.

**Comment by kouhunzhe** [comment]
What we need is a Vue version of survey-creator. Unfortunately, there is no such version in your code. If there is one, we are willing to purchase a license
