### ISSUE TITLE
Strict Content-Security-Policy cannot be applied on pages. Survey js contains inline styles & scripts.

### ISSUE THREAD

**Issue by kaizenberg** [surveyjs/survey-creator#741]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a (Technical Debt) related to client security

### What is the current behavior?

- Unable to use Survey Library due to inline style sheets & inline scripts
- Happens when HTML page contains following meta tag for protection against XSS attacks
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'self';"/>
- Penetration Testing identifies these loop holes. For now we have changed meta tags to allow inline scripts & styles but this should be avoided.

Error Log:
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.

EvalError: Unable to parse bindings.
Bindings value: css: css.root, afterRender: koEventAfterRender
Message: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self'".

### What is the expected behavior?

- Inline style sheets & JavaScript should not be used. 
- Instead declare style sheet classes.
- Website who do not want any inline resources are forced to find a workaround.
- Affected files:
  * stylesmanager.ts
  * survey.jquery.js (must be in other files like angular & knockout versions)

### How would you reproduce the current behavior (if this is a bug)?

- Add this meta tag on html page of your examples 
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'self';"/>

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'self';"/>
<link type="text/css" rel="stylesheet" href="modern.css" />
<script type="text/javascript" src="jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="survey.jquery.js"></script>

```

### Specify your

* browser: Google Chrome (Version 80.0.3987.163 (Official Build) (64-bit))
* editor version: Survey Library 1.5.19

**Comment by tsv2013** [comment]
SurveyJS Creator is built using KnockouJS. That's why it contains inline styles & scripts. In order to make it CSP-compatible we need to re-write it or wait for Knockout 4 (AKA TKO) to be released.

You can check also this thread: https://github.com/surveyjs/survey-library/issues/877

**Comment by mattdeacon** [comment]
Why is this closed? It is still an issue ... even using the react component it is using inline styles!

**Comment by tsv2013** [comment]
We're using inline styles for some cases and don't think it's an issue. As for inline scripts - we're working on SurveyJS Creator V2 that will built upon KnockoutJS and ReactJS frameworks. In this case survey-creator-react will solve the "inline scripts" CSP issue.
