### ISSUE TITLE
Add ability to show the limited number of action types in logic type

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#748]
The origional question came to SurveyJS [support desk](https://surveyjs.answerdesk.io/ticket/details/T3830).
The customer wants to limit the number of logic types showing on adding a new action or changing the existing one.
Adding static ``SurveyCreator.SurveyLogic.visibleActions`` array should solve the issue.
When this array not empty, then use actions that are in this array. For example:
```js
  SurveyLogic.visibleActions = [
    "question_visibility",
    "question_require",
    "trigger_skip",
    "trigger_complete"
  ];
```
The following code makes available only four actions.

**Comment by sammartens-collibra** [comment]
Works fine, I am just missing panel_require
