### ISSUE TITLE
Missing translation on localization file

### ISSUE THREAD

**Issue by joseqavalue** [surveyjs/survey-creator#750]
Bug
https://github.com/surveyjs/survey-creator/blob/master/src/localization/english.ts

Its missing text "both" 
category : pv
name : both

I know this file is generated automatically , so probably are missing more.

### What is the current behavior?

On your base file , i cant see the "both" text or other ones idk

### What is the expected behavior?

Be possible to get all possible texts used on surveyjs

### How would you reproduce the current behavior (if this is a bug)?

You can direclty enter on file , published on surveyjs like 20 min ago , and you will not see the text

This is the property that is not available on this file 
![image](https://user-images.githubusercontent.com/63859990/79577083-0daefc00-80bc-11ea-8941-8734f08934d0.png)

**Comment by tsv2013** [comment]
Fix will be available in the nearest update, most likely tomorrow.
