### ISSUE TITLE
Help needed - Add Custom Property of type 'textitems' and 'triggers'

### ISSUE THREAD

**Issue by shekharkc** [surveyjs/survey-creator#751]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

We are looking to define some custom properties for our survey propertyType 'textitems' (an array of inputs) and 'triggers' (add a custom button and associate a  custom trigger with it - onClick action + add a function with that event e.g go back to page 'x'). Hav tried to follow the examples listed, however, could not find an example covering 'textItems' and adding a custom button + click handler + select one of the available handler)

### What is the expected behavior?
 Would be grateful if someone can point an example or alternately suggest how to go about it.

### How would you reproduce the current behavior (if this is a bug)?

Not applicable

#### Provide the test code and the tested page URL (if applicable)
 Not applicable
Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Version 81.0.4044.113 (Official Build) (64-bit)
* editor version: Latest

**Comment by tsv2013** [comment]
Here is the live sample on our site - how to add properties - https://surveyjs.io/Examples/Survey-Creator?id=addproperties&theme=bootstrap

**Comment by andrewtelnov** [comment]
@shekharkc If you are looking for class names to where add your properties, then you need "surveytrigger" for triggers and "multipletextitem" for item in multiple text.

Thank you,
Andrew
SurveyJS Team

**Comment by shekharkc** [comment]
Thank you for the response, Andrew.

I had taken a look at the example you provided already and tried adapting our use-case to the same.

Our use-case is this: 
1. We need to define a survey.
2. Categorise Pages of the survey - e.g Personal Details Related, Employer Details Related etc
3. Categorise Questions to different categories likewise.
Example in the survey creator covers so far.
4. Add an array of 4 to 5 keywords to each question input by the survey-creator.
Here is where I thought textitems can be the propertyType.
> texitems - items property of multiple text question has this type

When I tried with 
`Survey
.Serializer
.addProperty("question",{
    name: "keywords:textitems",
    type: "multipletext",
    items: [
        {
         "name": "keyword1",
         "title": "Enter keyword 1"
        },
        {
         "name": "keyword2",
         "title": "Enter keyword 2"
        },
        {
            "name": "keyword3",
            "title": "Enter keyword 3"
           },
           {
            "name": "keyword2",
            "title": "Enter keyword 4"
           }
       ],
    category: "My Category"
});`

The survey-creator displays a **dropdown list** of Questions _instead of an input element._

On the other hand, if we just replace 'multipletext' with 'text', we get an **input box** : 

If we remove,  'type' and 'items' info from above and do something like this:

`Survey
.Serializer
.addProperty("question",{
    name: "keywords:textitems",    
    category: "My Category"
});`

We get the Keyword Property displayed with **two blank buttons** - presumably to 'Add' and 'Remove' inputs as in a multitext Question type.

We would like to implement something like the last option, permitting the survey creator to add 'keywords' with each Question as multitext input, one after another.

PFA the screenshots of our attempt at this. 

I am certain we are missing something very basic here. 

Will be grateful if you can set us on the right path.

[Thanks]
![Slide1](https://user-images.githubusercontent.com/32909897/79752970-c1212600-8332-11ea-9130-5413e0ca4206.JPG)
![Slide2](https://user-images.githubusercontent.com/32909897/79752973-c2525300-8332-11ea-9f82-45388cd82325.JPG)
![Slide3](https://user-images.githubusercontent.com/32909897/79752974-c2eae980-8332-11ea-9b9e-bda2e267f13a.JPG)

**Comment by tsv2013** [comment]
The code
```JS
Survey.Serializer .addProperty("question", { name: "keywords:textitems" });
```
is equal to
```JS
Survey.Serializer .addProperty("question", { name: "keywords", type: "textitems" });
```

Property can't be of type "multipletext". "multipletext" is a question type name and can't be used for properties.

**Comment by shekharkc** [comment]
Thank you very much.

This brings me to the option3 I tried.
`Survey .Serializer .addProperty("question",{ name: "keywords:textitems", category: "My Category" });`

and 

`Survey .Serializer .addProperty("question",{ name: "keywords:textitems", items: [ { "name": "keyword1", "title": "Enter keyword 1" }, { "name": "keyword2", "title": "Enter keyword 2" }, { "name": "keyword3", "title": "Enter keyword 3" }, { "name": "keyword2", "title": "Enter keyword 4" } ], category: "My Category" });`

In the first case, I was expecting to be able to add 'keywords' using the buttons to add/ delete items & in the second case I was expecting to see the items listed with an ability to add/delete items using the buttons in the editor.

In both cases, the buttons do not function as expected & in the second case, I do not see the items listed (screenshot att).

Is this the expected behaviour? Or is that an issue with the library? Or in my definition?

Thanks
![Slide3](https://user-images.githubusercontent.com/32909897/79931668-24ad6f80-8469-11ea-96e1-fbdeb263b720.JPG)

**Comment by andrewtelnov** [comment]
@shekharkc There is no attribute items in the SurveyJS property and you likely need to use "itemvalue[]" type.
``Survey.Serializer .addProperty("question", { name: "keywords:itemvalue[]" });``
textitems is a property type for multiple text question.

It is hard to suggest anything without understanding what you are trying to achieve.

Thank you,
Andrew

**Comment by shekharkc** [comment]
@andrewtelnov,

Thank you very much. That helped. 
The use-case I had was to allow the Survey Creator add list of keywords as keyValue pairs ( [{keyword1ID,  keyword}, {keyword2ID,  keyword} .. and so on) with each Question.

Grateful to you for pointing me in the right direction.
