### ISSUE TITLE
CSV multi-line translation export

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#777]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Values in the CSV are not quoted, this leads to issues when strings have line endings in them.

### What is the expected behavior?
The values should be quoted if they contain special characters.

### How would you reproduce the current behavior (if this is a bug)?
Load this json:
```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "text",
     "name": "question1",
     "title": "<pre>multi\nline\n\nquestion\ntext</pre>"
    }
   ]
  }
 ]
}
```
Export the csv:
```
|default|es
survey.page1.question1.title|<pre>multi
line

question
text</pre>|
```

## Proposed solution
I'm not a fan of re-inventing the wheel. I've used the PapaParse CSV library a lot, and would suggest using that to do CSV parsing in both directions!

**Comment by SamMousa** [comment]
I'm creating a PR for this.

**Comment by andrewtelnov** [comment]
@SamMousa Let us discuss it internally. The library seems a tiny one, but some people can have issues in adding additional library into their projects.

Thank you,
Andrew

**Comment by SamMousa** [comment]
Sure, but to be fair, adding an additional library beats writing your own implementation (as is evidenced by the bugs related to escaping).

Anyway let me know what you decide, as far as I can tell the PR is ready to merge and covered by the updated tests as well.

**Comment by tsv2013** [comment]
@SamMousa Thank you for the contribution. I've merged the PR.
