### ISSUE TITLE
How to control the behavior of testService element on choices by url

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-creator#781]
### Are you requesting a feature, reporting a bug, or ask a question?

question

I want to control the URL that the test service dropdown on choicesbyUrl example:
when I click on dropdown I wanna do other request and add it to my dropdown, or maybe override completely the choices by completely different URL, is this possible ? 

### Specify your

* browser:
* editor version: 1.1.15

**Comment by tsv2013** [comment]
You can use the 
```JS
Survey.ChoicesRestfull.onBeforeSendRequest = function(sender /* ChoicesRestfull object */, options) {
    // options.request is the XMLHttpRequest to be sent
}
```
to override the requests i think
callback
