### ISSUE TITLE
Automated releases

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#782]
### Are you requesting a feature, reporting a bug or ask a question?
Feature for the process

### What is the current behavior?
Bugs get fixed and releases are created manually, often the changelog is hard to find.

### What is the expected behavior?
Fast releases and good changelogs 

### Proposal
For some open source packages I maintain I've recently set up fully automated releases using semantic-release (https://github.com/semantic-release/semantic-release). Combining this with commitlint (https://github.com/conventional-changelog/commitlint) which forces me to create correct commit messages everything is automated.

Based on my commit message it decides on a semantic version number, the release is tagged via a github action & a changelog is created automatically.

Take a look, for example at this package: https://github.com/SAM-IT/yii2-mariadb/releases
Note that it is a PHP package, but that's irrelevant.
The interesting part are the `devDependencies` in the `package.json`. In the JS world where NPM is already used you could even automate pre-commit hooks using husky.

I'm up for creating a PR to set this up if you'd like me to.
(note: this could be used for any of the repos not only the creator)

**Comment by tsv2013** [comment]
What's new about new releases of SurveyJS products is collected automatically and published on this page - https://surveyjs.io/WhatsNew

Does it if your vision of what's new page?


@andrewtelnov Could you please also read this proposal?

**Comment by SamMousa** [comment]
> Does it if your vision of what's new page?

That page is definitely really cool, (I asked about this before and was directed to the github compare page). I'd be even happier if you could add a link to that page to the github release pages:
https://github.com/surveyjs/survey-creator/releases/tag/v1.7.5

So the release-notes part might not be relevant for you :) -- the automatic release could still be very valuable for all users on the edge.
