### ISSUE TITLE
How to change the language of toolbox and window?

### ISSUE THREAD

**Issue by xrq360** [surveyjs/survey-creator#783]
### How to change the language of toolbox and window?
The library provides the option of language localization, but only partially. The language of toolbox and window still has no options to change. How can I change the language of these two parts? For example, I want to change it to simplified Chinese.

Thank you!

**Comment by tsv2013** [comment]
If you are asking about the toolbox, I think the question is related to the `survey-creator`.

Here is the live exmple how you can localize string and properties in SurveyJS Creator - https://surveyjs.io/Examples/Survey-Creator?id=localization&theme=bootstrap
