### ISSUE TITLE
Updating Navigation button text will not call `onModified` and `saveSurveyFunc`

### ISSUE THREAD

**Issue by amedve** [surveyjs/survey-creator#792]
### Are you requesting a feature, reporting a bug or ask a question?
Bug.

### What is the current behavior?
Updating survey Navigation properties ("Page previous button text", "Page next button text"...) not firing `onModified` and/or `saveSurveyFunc`.

### What is the expected behavior?
`onModified` and/or `saveSurveyFunc` called on updating Navigation properties.

### How would you reproduce the current behavior (if this is a bug)?
- Set Navigation button text properties ("Page previous button text", etc.).
- `onModified` and `saveSurveyFunc` will not be called.

### Specify your
* browser: Google Chrome 81.0.4044.138
* editor version: 1.7.6

**Comment by andrewtelnov** [comment]
I fixed the bug. We will include the fix into [v1.7.7](https://surveyjs.io/WhatsNew#v1.7.7).

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Here is [the commit](https://github.com/surveyjs/survey-library/commit/f82aa93b5dbd279852cf40e451a05760fd2bcfe3) with the fix.

**Comment by amedve** [comment]
Thank you!
