### ISSUE TITLE
Bug on layout tab(Data) property editor , bad alignment

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-creator#799]
### Are you requesting a feature, reporting a bug or ask a question?
There is a bad alignment on the property editor - matrix single choice question
![image](https://user-images.githubusercontent.com/30509391/82419381-3a1cb600-9a76-11ea-8904-81c5bf2ef20a.png) 

### What is the current behavior?

Bad alignment table

### How would you reproduce the current behavior (if this is a bug)?

I only add a question matrix single choice on surveyjs page, and appears the bug

### Specify your

* browser: 
* editor version:

**Comment by dmitrykurmanov** [comment]
reproduced

**Comment by dmitrykurmanov** [comment]
We've fixed the problem. Fix will be available in the next minor release.
