### ISSUE TITLE
I cant remove or hide logo property from survey object

### ISSUE THREAD

**Issue by jmar1998** [surveyjs/survey-creator#800]
### Are you requesting a feature, reporting a bug or ask a question?
Possible bug or question, maybe I'm doing something wrong

### What is the current behavior?
When I use the survey serializer to remove the logo property from the survey, it's still visible
If I upload an image and I see the survey seems the property is ignored as suppose but I think the behavior should be the same as other properties if you remove it, is invisible too

### What is the expected behavior?

Be invisible and ignored on any survey action

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/0evwN0pIUFLe0BwO?preview

Test code
		Survey
			.Serializer
			.removeProperty("survey", "logo");
		Survey
			.Serializer
			.removeProperty("survey", "logoWidth");
		Survey
			.Serializer
			.removeProperty("survey", "logoHeight");
		Survey
			.Serializer
			.removeProperty("survey", "logoFit");
		Survey
			.Serializer
			.removeProperty("survey", "logoPosition");

### Specify your

* browser:
* editor version: 1.7.7

**Comment by tsv2013** [comment]
In the next version 1.7.8 the `Survey.Serializer.removeProperty("survey", "logo");` string will remove the "Add logo" button in the top of the survey title block.

**Comment by agustinparamio** [comment]
Im currently using "survey-creator": "^1.7.4" on a React app.
How can I remove it?

**Comment by jmar1998** [comment]
@agustinparamio you have to upgrade your version, and use survey serializer to remove it.
Survey.Serializer.removeProperty("survey", "logo");
