### ISSUE TITLE
Access to the questions in Test Tab

### ISSUE THREAD

**Issue by Matwiing** [surveyjs/survey-creator#809]
### Are you requesting a feature, reporting a bug or ask a question?
A question

### What is the current behavior?
Since the last  version, I can't access to the SurveyLiveTester survey.
Before I did like this : "let survey = this.editor.surveyLiveTester.survey;" (with editor a SurveyEditor object).
Now I try to do this : "let survey = new SurveyCreator.SurveyLiveTester(this.editor).survey;" but I have nothing when I do "survey.getAllQuestions()".

### What is the expected behavior?
Access questions in the Test panel.

Did I miss something ? Thanks.

**Comment by tsv2013** [comment]
You can get the test survey instance in the https://surveyjs.io/Documentation/Survey-Creator?id=surveycreator#onTestSurveyCreated or in the https://surveyjs.io/Documentation/Survey-Creator?id=surveycreator#onSurveyInstanceCreated event handler

**Comment by Matwiing** [comment]
It works perfectly thanks :)
