### ISSUE TITLE
VisibleIf expression doesn't appear

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-creator#819]
1) Go to https://surveyjs.io/create-survey
2) Add two questions
3) Select second question
4) Go to Logic section in property grid
5) Expand VisibleIf tab
6) Choose first question in dropdown
7) Choose is not empty in second dropdown
8) Click on Edit button
9) Click back on Build button
10) Choose is empty in second dropdown
11) Wait a two seconds (important!)
12) Click on Edit button
13) ???
14) Expression displays old value until click a textarea

![image](https://user-images.githubusercontent.com/30930391/83501085-4e29d400-a4c8-11ea-9314-44d9834d3a00.png)

**Comment by tsv2013** [comment]
Ace editor ih hidden and doesn't update rendering. The corresponding issue - https://github.com/ajaxorg/ace/issues/2497#issuecomment-102633605
