### ISSUE TITLE
Survey creator not working after the build process

### ISSUE THREAD

**Issue by Enkosz** [surveyjs/survey-creator#828]
### Are you requesting a feature, reporting a bug or ask a question?

Possible bug

### What is the current behavior?

We are working to integrate the survey-js creator plugin into a Vue.js project with the default vue-cli.
The creator is working in the devel environment but is not in production. The default build process is made with the vue-cli build command. There aren't any further webpack configurations.
This is the error:
![dnQZYye](https://user-images.githubusercontent.com/35410110/84012184-75c0e680-a977-11ea-837b-a7d7feecbdc3.png)

### What is the expected behavior?

Survey creator should appear and work.

### Specify your

* browser: Version 81.0.4044.113 (Official Build) (64-bit)
* editor version: 
1. "survey-analytics": "^1.5.16"
2. "survey-creator": "^1.5.12"
3. "survey-knockout": "^1.5.12"
4.  "survey-pdf": "^1.5.17"
5. "survey-vue": "^1.5.12"
6. "vue": "^2.6.11",
7. ""@vue/cli-service": "^4.2.0"

**Comment by tsv2013** [comment]
Can you create a sample project illustrating the issue?
