### ISSUE TITLE
Bug in Custom Property Editor sample online

### ISSUE THREAD

**Issue by marcziss** [surveyjs/survey-creator#840]
The ckeditor seems to be rendering twice for each property that is being replaced in the online sample code. (Title, Description Html) https://surveyjs.io/Examples/Survey-Creator/?id=ckeditorpropertyeditor&theme=bootstrap

I didn't initially notice it, because I thought it was supposed to be the same field twice, but saw it in my code (based on the sample) and they are indeed duplicates.

Seems like it could be a knockout binding issue, but I don't have enough expertise in knockout to trace it down

Great job on Survey.js BTW. I am planning on buying a license next week.
Marc

**Comment by tsv2013** [comment]
I'll look into it

**Comment by tsv2013** [comment]
I've reproduced the issue on our site in the example you mentioned - https://surveyjs.io/Examples/Survey-Creator/?id=ckeditorpropertyeditor&theme=bootstrap

But unfortunately I can't reproduce it locally in the current codebase (with the same settings and script/styles loaded).

Let's wait for 1.7.13 and check it again. I'll mark it as "Can't reproduce for a while" but will check again on the next week.

**Comment by marcziss** [comment]
Hey tsv2013,
Thanks for looking into this, just checked the online sample, version 1.7.15 and it still has the same problem. The duplicate controls seem to be 2 uniquely bound instances because you can change the text in one editor and it doesn't effect the other, but they both effect the text in the actual survey.

**Comment by tsv2013** [comment]
@marcziss Thank you for the update. Yes, I see the issue. We'll fix it.

**Comment by dmitrykurmanov** [comment]
@marcziss  we've fixed the bug. Fix will be available in the next minor release. Thanks for the reporting!

**Comment by marcziss** [comment]
@tsv2013 + @dmitrykurmanov  Thx, you guys rock!
