### ISSUE TITLE
Can't select correctQuestions progress bar type

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-creator#848]
1) Go to https://surveyjs.io/create-survey
2) Open Navigation section in Survey properties
3) Select correctQuestions in Progress Bar Type dropdown
4) ???
5) Dropdown value is empty

P.S. If select correctQuestions again dropdown value will be correct
P.P.S. but seems correctQuestions bar type not works at all

![image](https://user-images.githubusercontent.com/30930391/85290947-8195c800-b4a2-11ea-839d-73f21218c939.png)

**Comment by andrewtelnov** [comment]
Fixed on introducing functionality described in [this issue](https://github.com/surveyjs/survey-library/issues/2377).

Thank you,
Andrew
