### ISSUE TITLE
Hide CommentText property editor if hasComment property is set to false

### ISSUE THREAD

**Issue by aanavaneeth** [surveyjs/survey-creator#854]
### Are you requesting a feature, reporting a bug or ask a question?
feature

### What is the current behavior?
comment field is visible even when has comment is disabled

### What is the expected behavior?
Hide Comment property editor if has comment property is set to false

**Comment by andrewtelnov** [comment]
@aanavaneeth I have implemented it via commits above.

Thank you,
Andrew
