### ISSUE TITLE
Allow to change the category for existing properties

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#863]
The following code should change the property "name" category from "general" to "data" and make this property first in the "Data" tab.
```js
var nameProperty = Survey.Serializer.findProperty("question", "name");
nameProperty.category = "data";
newProperty.visibleIndex = 0;
```
The code should be executed before SurveyJS Creator constructor.

**Comment by andrewtelnov** [comment]
@aanavaneeth you was looking for this functionality.

Thank you,
Andrew

**Comment by aanavaneeth** [comment]
yes! Thank you so much!
