### ISSUE TITLE
completedHtml HTML tags stripped

### ISSUE THREAD

**Issue by amedve** [surveyjs/survey-creator#867]
### Are you requesting a feature, reporting a bug or ask a question?
A bug.

### What is the current behavior?
HTML tags are stripped from `completedHtml` property when displaying survey completed page.
However, tags are **not** stripped in Survey Editor in "Test Survey" tab.

### What is the expected behavior?
HTML tags are **not** stripped from `completedHtml` property when displaying survey completed page.

### How would you reproduce the current behavior (if this is a bug)?
- Add any HTML content with HTML tags to `completedHtml`.
- Compare completed page in user-facing survey mode and Survey Editor "Test Survey".

### Specify your

* browser: Chrome 83.0.4103.116 (Official Build) (64-bit)
* editor version: 1.7.15

**Comment by tsv2013** [comment]
I've just checked our online creator demo https://surveyjs.io/create-survey with the following JSON:
```JSON
{
 "title": "qwe",
 "completedHtml": "<b>bold</b><a href=\"surveyjs.io\">aaa</a>",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "matrixdropdown",
     "name": "q1",
     "columns": [
      {
       "name": "Column1"
      },
      {
       "name": "Column2"
      },
      {
       "name": "Column3"
      }
     ],
     "choices": [
      1,
      2,
      3
     ],
     "rows": [
      "Row1",
      "Row2"
     ]
    }
   ]
  }
 ]
}
```

And it works ok for me - on the completed banner i see bold text and the link.

**Comment by amedve** [comment]
My bad, the issue was on my end. I did not html-encode JSON text on the page. 
Sorry for the false alarm!
