### ISSUE TITLE
Edit column properties button doesn't work for matrix dynamic

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#868]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Add matrix dynamic
Open columns
Click Edit button
Results:
edit area empty
impossible to return back

Tested page URL:
https://www.surveyjs.io/create-survey

**Comment by dmitrykurmanov** [comment]
We couldn't reproduce the problem now. If the bug will appear please feel free to reopen it.
