### ISSUE TITLE
onElementAllowOptions 'undefined' error

### ISSUE THREAD

**Issue by iamsid** [surveyjs/survey-creator#882]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
![image](https://user-images.githubusercontent.com/17705415/86608829-ac1a7180-bfc8-11ea-980b-476d97722d3e.png)

### How would you reproduce the current behavior (if this is a bug)?
I opened one of the samples in Plunker, and added code as below:
![image](https://user-images.githubusercontent.com/17705415/86608907-c6544f80-bfc8-11ea-98bc-2ea3402636df.png)

I can see the same error as above in console. (Above error is from my code where creator = surveryCreator)
I just copied the code as is from docs. I am not sure if this is the right way to do it, but I could not find any other documentation for the same.

Test code

```
surveyCreator.onElementAllowOptions.add(function (sender, options) {
        options.allowAddToToolbox = false;
    });
```

### Specify your

* browser: Chomre
* editor version: 1.7.18

**Comment by tsv2013** [comment]
This event is called onElementAllowOperations - https://surveyjs.io/Documentation/Survey-Creator?id=surveycreator#onElementAllowOperations

Here is the working plunker - https://plnkr.co/edit/dazzR7USmRqh9VB2

**Comment by iamsid** [comment]
Oh. Ok. The docs says Options.

https://surveyjs.io/Documentation/Survey-CreatorSinglePage?id=Survey-Creator-Overview#toolbox

![20200325_192527](https://user-images.githubusercontent.com/17705415/86612122-441a5a00-bfcd-11ea-81b9-7caf50005b92.jpg)

**Comment by tsv2013** [comment]
It's a type in the documentation. I've fised it via the referenced commit.
