### ISSUE TITLE
SurveyCreator Custom Field(Datepicker) in Editor - Angular

### ISSUE THREAD

**Issue by SaraaAwwad** [surveyjs/survey-creator#888]
### Are you requesting a feature, reporting a bug or ask a question?
question

### What is the current behavior?
I want to add a datepicker in the survey editor. So I add a widget to the surveycreator and use it but it results in the error: 
Uncaught Error: Unknown component 'svd-property-editor-custom'

### What is the expected behavior?
I tried the code below in a plunker and it worked fine. Don't know how to work it around in angular

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
Survey.Serializer.addProperty("survey", {
  name: "dateFormat:date",
  category: "general"
});

var propertyDateWidget = {
    render : function(editor, el) {
        var isSetValue = false;
        var input = document.createElement("input");
        input.className = "form-control svd_editor_control";
        input.type = "date";
        input.onchange = function() {
          isSetValue = true;
          editor.koValue(input.value);
          isSetValue = false;
        };
        el.appendChild(input);
    }
}

    SurveyCreator.Extentions.registerCustomPropertyEditor("date", propertyDateWidget);
```

### Specify your

* browser: chrome
* editor version:

**Comment by tsv2013** [comment]
SurveyCreator referenced the `survey-knockout` library. That's why in Angular application you need to register a custom property both in `survey-angular` and `survey-knockout` libraries:
```JS
SurveyKo.Serializer.addProperty("survey", {
  name: "dateFormat:date",
  category: "general"
});
```
as you can see in our SurveyJS+Angular demo repo - https://github.com/surveyjs/surveyjs_angular_cli

As for the 
> Uncaught Error: Unknown component 'svd-property-editor-custom'

As far as I remember similar error was fixed couple releases ago.
Could you try the latest version (1.7.18)?

**Comment by SaraaAwwad** [comment]
It worked by applying what you mentioned above, thanks. :)
