### ISSUE TITLE
Turkish locale instead of danish

### ISSUE THREAD

**Issue by SashaMalahov** [surveyjs/survey-creator#893]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?
When setting currentLocale to "da" Survey Creator elements translate to Turkish

### What is the expected behavior?
When setting currentLocale to "da" Survey Creator should translate to Danish

### How would you reproduce the current behavior (if this is a bug)?
SurveyCreator.localization.currentLocale = "da";

#### Provide the test code and the tested page URL (if applicable)
https://plnkr.co/edit/lYX67iAOC1MSP2Yj?preview

**Comment by andrewtelnov** [comment]
@SashaMalahov Sorry about that. There was a mistake in Turkish localization file. We did not make the translation and we missed the error. The wrong letters were using. I have corrected it.

Thank you,
Andrew

**Comment by SashaMalahov** [comment]
@andrewtelnov Thanks for extremely quick response and fix!
