### ISSUE TITLE
ERROR in multi (webpack)-dev-server/client?http://localhost:8080 build-dev

### ISSUE THREAD

**Issue by BabuBahir** [surveyjs/survey-creator#906]
### Are you requesting a feature, reporting a bug or ask a question?
bug

### What is the current behavior?
npm start build_dev 
throws 
ERROR in multi (webpack)-dev-server/client?http://localhost:8080 build-dev

### What is the expected behavior?
should build
![Capture](https://user-images.githubusercontent.com/22672829/87911407-3236bd80-ca89-11ea-99ea-6d766b07853e.PNG)

### How would you reproduce the current behavior (if this is a bug)?
git clone surveyjs..
npm install
npm start build_dev        <- error :(

![image](https://user-images.githubusercontent.com/22672829/87911449-47abe780-ca89-11ea-944a-0388eff73541.png)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
You're typing the wrong command. You should use the `npm start` to run local demos of `npm run build_dev` for dev build. Or run `npm run build_prod` for build in production environment.

**Comment by BabuBahir** [comment]
> You're typing the wrong command. You should use the `npm start` to run local demos of `npm run build_dev` for dev build. Or run `npm run build_prod` for build in production environment.

omg...let me check.....if that's the case  I am so ashamed... i would remove this issue once i check it now

**Comment by BabuBahir** [comment]
Please Delete this issue
