### ISSUE TITLE
Question: Bootstrap theme - inherit from app

### ISSUE THREAD

**Issue by scottadamsmith** [surveyjs/survey-creator#907]
Are you requesting a feature, reporting a bug or asking a question?
Asking a question.

What is the current behavior?
When choosing bootstrap, it appears the survey creator still overrides the color variables.

What is the expected behavior?
That if you choose bootstrap, the survey creator does not override your main apps variables and instead, inherits them.

How would you reproduce the current behavior (if this is a bug)?
Create a page with the out of the box bootstrap theme. Install the survey creator and see that the colors of primary buttons are not the default primary-color from bootstrap.

Provide the test code and the tested page URL (if applicable)
I can create a repro if need be, but I was thinking this might just be an issue where I need clarification as I a may be misunderstanding or doing something wrong.

### Specify your

* browser: Any
* editor version: Latest

**Comment by scottadamsmith** [comment]
I was able to get this to work by updating your color variables to point to the pre-existing variables. 

```
const defaultThemeColorsEditor = SurveyCreator
    .StylesManager
    .ThemeColors["default"];

defaultThemeColorsEditor["$primary-color"] = "var(--primary)";
defaultThemeColorsEditor["$secondary-color"] = "var(--secondary)";
defaultThemeColorsEditor["$primary-text-color"] = "var(--primary-text)";
defaultThemeColorsEditor["$secondary-text-color"] = "var(--secondary-text)";
defaultThemeColorsEditor["$inverted-text-color"] = "var(--inverted-text)";
defaultThemeColorsEditor["$primary-hover-color"] = "var(--primary-hover)";
defaultThemeColorsEditor["$selection-border-color"] = "var(--selection-border)";
defaultThemeColorsEditor["$primary-icon-color"] = "var(--primary-icon)";
defaultThemeColorsEditor["$primary-bg-color"] = "var(--primary-bg)";
defaultThemeColorsEditor["$secondary-bg-color"] = "var(--secondary-bg)";
defaultThemeColorsEditor["$primary-border-color"] = "var(--primary-border)";
defaultThemeColorsEditor["$secondary-border-color"] = "var(--secondary-border)";
defaultThemeColorsEditor["$error-color"] = "var(--error)";
```

Is this the recommended approach? It feels strange to me that if I choose the bootstrap option for survey creator, that it would not assume I have already setup my theme the way I want and instead choose to change the colors so that the survey-creator doesn't look like the rest of the app.

**Comment by tsv2013** [comment]
Yes, SurveyJS Creator uses highly customized Bootstrap theme. Unfortunately we haven't fit our design into Bootstrap components. You need to customize colors via the built-in StylesManager (as shown in this sample - https://surveyjs.io/Examples/Survey-Creator?id=editor-custom-theme) or override CSS classes manually.
