### ISSUE TITLE
Broken online Sample using CKEditor

### ISSUE THREAD

**Issue by marcziss** [surveyjs/survey-creator#908]
I am using a different editor than html ckeditor in my implementation, but it recently broke after upgrading to the latest survey-creator 1.7.20. I wanted to check if there was a breaking change to setup the custom editor in the new version, so I went to the online sample to check it out 

https://surveyjs.io/Examples/Survey-Creator?id=ckeditorpropertyeditor 

and it was broken too. I checked it in both Chrome + edge and it doesn't render in either
Marc

**Comment by marcziss** [comment]
Just saw the sample was fixed in the new release 1.7.23 and  it fixed my issue as well. You guys rock!

**Comment by marcziss** [comment]
I closed this issue yesterday, but had not tested in edge. Tried it now, and it did not work. 
It renders, but the editor is not functional. I had tried this before in the past and pretty sure it worked. 
I tested with an older version of edge Microsoft Edge 44.18362.449.0. If this is not a big deal to you , close the issue, but wanted to make you aware.
Thanks
Marc

**Comment by tsv2013** [comment]
It looks like it was an issue with CKEditor
I've found similar issues in the CKEditor repo - https://github.com/ckeditor/ckeditor4/issues/2035
I've bumped the version of used CKEditor to 4.14.1 and now it workd ok for me in the Edge browser
(But I've got another error in console thrown by CKEditor)
Can you check it on your side?

**Comment by marcziss** [comment]
The good news is that ckEditor seems to be fixed in the sample for the version of edge I tested with (although it jumps for when it gets focus, but not that noticeable)
The bad news is the issue I thought was fixed for the editor that I am using (https://premiumsoftware.net/cleditor/) was not fixed as I originally thought. 

In tracking it down it looks like:
1.7.12 works fine.
1.7.13 broke something so that the html editor doesn't replace regular textareas (even in chrome)  
1.7.14 the html editor now correctly replaces the textarea and allows the user to enter new text, BUT, when changing the focus to another question, existing question text does not populate the editor area. It looks like a binding issue of some kind. 

I know this is a little different than the original issue I posted, but it seemed the 2 issues were based on the same problem. I can stay at 1.7.12 for a while, but hope this issue can be resolved sometime, I can give you a code sample if it would be helpful.
Thanks
Marc

**Comment by tsv2013** [comment]
Could you tell what's wrong with the CKEditor sample in the current (1.7.23) version?

**Comment by marcziss** [comment]
I think it's fine in ckeditor it jumps sometime when entering the field, but it's completely acceptable. So I think it's okay to close this,  

I will need to come back to the other issue I described that stopped working with cleditor, but I will have to isolate why 1.7.13 broke my implementation as a separate issue, when I get a chance to go back and work on it
Thanks again
Marc
