### ISSUE TITLE
How to retrieve custom property from creator

### ISSUE THREAD

**Issue by SashaMalahov** [surveyjs/survey-creator#911]
### Are you requesting a feature, reporting a bug or ask a question?

Ask a question

### What is the current behavior?

Hello. I have angular app with survey creator inside. During the survey creator initialization I've added new custom property to the property tab:
```
import { Serializer } from 'survey-knockout';
.......
Serializer.addProperty('survey', { name: 'captcha:boolean',  displayName: 'Has Captcha', default: true, category: 'Captcha'});
```
This is the initialization of surveyCreator object
```
const options = { generateValidJSON: true, showLogicTab: true, showJSONEditorTab: false };
this.surveyCreator = new SurveyCreator('surveyCreatorContainer', options);
```

And I can see a new category of a checkbox type in Properties tab
![image](https://user-images.githubusercontent.com/18553469/88414208-26c6f780-cde5-11ea-8ae6-b12dd5989e73.png)

Now I want to check the value of this checkbox in onActiveTabChanged event.
```
        this.surveyCreator.onActiveTabChanged.add((sender, options) => {
             get value here
        });
```

sender - survey creator object but I can't see this added property.
I tried to find this property inside sender object, like sender.captcha / sender["captcha"]
Also i tried to create a survey model object to retrieve the value (without any results)
```
const surveyModel = new SurveyModel(sender.JSON);
surveyModel .captcha / surveyModel ["captcha"]
```

Can you please help me with getting this new property? Am I doing it in a right way?

### Specify your

* browser: Google Chrome 84.0.4147.89
* editor version: 1.7.2 (package version for Angular)

**Comment by tsv2013** [comment]
You can get the current survey instance is being designed fom the "creator.survey" property. In case of the event the "sender" object is the "creator" indeed. Thus you can use the "sender.survey.captcha" to access this property.

**Comment by SashaMalahov** [comment]
@tsv2013 Hello. Thanks for reply!
I wasn't able to access the property via sender.survey.captcha but I was able to do it through any property/function that returns SurveyForDesigner object.
