### ISSUE TITLE
Change default value for Rating question in Survey Creator

### ISSUE THREAD

**Issue by SashaMalahov** [surveyjs/survey-creator#917]
### Are you requesting a feature, reporting a bug or ask a question?
Ask a question

### What is the current behavior?
By default, rating question has minRate = 1, maxRate =5

### What is the expected behavior?
Is it possible to change default value for mixRate and maxRate during the SurveyCreator initialization?

### How would you reproduce the current behavior (if this is a bug)?
I'm using Angular 8 app. I was able to change default values within onQuestionAdded event like this:

```
this.surveyCreator.onQuestionAdded.add((sender, options) => {
     if (options.question.getType()=== 'rating') {
                    options.question.rateMin = 0;
                    options.question.rateMax = 10;
                }
})

```

But is there any way to change the default values for rating question during initialization of SurveyCreator object?
Example of initializing SurveyCreator object
```
const options = { generateValidJSON: true, showLogicTab: true, showJSONEditorTab: false };
        this.surveyCreator = new SurveyCreator('surveyCreatorContainer', options);
```
### Specify your

* browser: Google Chrome 84.0.4147.89
* editor version: 1.7.2

**Comment by andrewtelnov** [comment]
@SashaMalahov The easiest solution is to change the default value in the property definition.
``Survey.Serializer.findProperty("rating", "rateMax").defaultValue = 10;``

Thank you,
Andrew

**Comment by SashaMalahov** [comment]
Thank you @andrewtelnov !
