### ISSUE TITLE
Single input fields allow text entry in design mode

### ISSUE THREAD

**Issue by marcziss** [surveyjs/survey-creator#922]
Hey guys,
This seems like a bug. If you click to the right of the Title adorner  on a  single input text field it will put the focus on the textbox and allow you to edit it. The expected behavior is for the entire question element to gain focus and draw the focus frame, as it does when you click elsewhere on the question element. 
Marc

![Survey js editable](https://user-images.githubusercontent.com/65080578/89196052-ac7e3c00-d577-11ea-8eb2-0146b25878ac.gif)
.

**Comment by andrewtelnov** [comment]
@marcziss Yes, it is a none issue. We are working o [the fix](https://github.com/surveyjs/survey-creator/issues/919).

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
We've fixed the problem via the https://github.com/surveyjs/survey-library/commit/e65702ccfd428391cd471bd5cdcee0dd0f093c49. Fix will be available in the next minor update. Thanks.
