### ISSUE TITLE
SurveyCreator readonly not applied properly

### ISSUE THREAD

**Issue by zy-serguei** [surveyjs/survey-creator#924]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
If a new value is assigned to SurveyCreator's readonly property the change is applied only partially in the interface:
- Fields in the properties pane of the current element remain unchanged - editable or readonly depending on the previous state.
- Inline editing of the current page's title and description remains unchanged - enabled or disabled depending on the previous state.
- Inline editing of the Survey's title and description remains unchanged - enabled or disabled depending on the previous state, Once disabled it cannot be enabled anymore.

To see the interface reflect the new setting (enabled or disabled) the user must select a different element (i.e. select a different Page). Then the fields become editable or readonly as expected depending on the value of the setting.

### What is the expected behavior?
When `readonly` is set to `false` all editing must become enabled, also for the currently selected element. When `readonly` is set to `true` all editing must became disabled.

### How would you reproduce the current behavior (if this is a bug)?
Change the value of `readonly` and observe that the interface doesn't reflect the change.

#### Provide the test code and the tested page URL (if applicable)
Test code
`surveyCreator.readonly = true; // editing must become disabled`
`surveyCreator.readonly = false; // editing must become enabled`

### Specify your
* browser: Chrome 84.0.4147.89
* editor version: 1.7.18

**Comment by dmitrykurmanov** [comment]
@zy-serguei  thanks for the reporting. In fact we have only the `readOnly` property (lowerCamelCase) not a `readonly` one. And if you set it via the options I think it will work as expected : 

```js
var options = {
    readOnly: true,
  };
var creator = new SurveyCreator.SurveyCreator("editorElement", options);
```

you can try this approach to achieve you needs

but anyway it doesn't work via setting properties:
surveyCreator.readOnly= true; // editing must become disabled
surveyCreator.readOnly= false; // editing must become enabled
and it is not clear from the doc

**Comment by dmitrykurmanov** [comment]
We've fixed the bug. Fix'll be available in the next minor release.
