### ISSUE TITLE
Expression get truncated incorrectly

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#934]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

An expression typed into the editor gets truncated in certain scenarios.

### What is the expected behavior?

Valid expressions should not be broken

### How would you reproduce the current behavior (if this is a bug)?

1. Create survey with 2 checkbox questions.
2. Set the `choicesVisibleIf` property of the second question to `{question1} contains {item}`
3. Switch to JSON editor

Observe that the above expression is truncated to `{question1} contain`

### Specify your

Tested on the website in chrome

**Comment by andrewtelnov** [comment]
@SamMousa I could not reproduce it. I can write ``{question1} contains {item}`` in  "Edit" tab and it saved perfectly in JSON, you can modify it in JSON and come back.
We should not do anything, when you are changing expression in "Edit" tab and save as it is.

Thank you,
Andrew

**Comment by SamMousa** [comment]
I'll try and make a short screen recording. It was reported to me and I could then reproduce it, so I'm confident there is an issue somewhere .

**Comment by SamMousa** [comment]
![output](https://user-images.githubusercontent.com/547021/90227404-ca1f9100-de14-11ea-8e2b-2fe4ac6fdadc.gif)


Still getting it, used an incognito window to be sure it wasn't some browser state issue

**Comment by SamMousa** [comment]
I think it has to do with the autocomplete or something

**Comment by andrewtelnov** [comment]
@SamMousa Yes, I could it easily reproduce. I will work on the fix.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@SamMousa I believe I have fixed it. There was an error in console. I fixed it and it started to work.

Thank you,
Andrew
