### ISSUE TITLE
I am using modern theme for survey creator and in this elements are overlapping 

### ISSUE THREAD

**Issue by Sameedkhan25** [surveyjs/survey-creator#939]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

elements are overlapping in modern theme , working fine with other themes

### What is the expected behavior?

Elements should not overlap

### How would you reproduce the current behavior (if this is a bug)?

![issue survey modern theme](https://user-images.githubusercontent.com/22944289/90634633-70b6c800-e241-11ea-9d00-bbd32f92c243.PNG)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
I've checked live sample on our site - https://surveyjs.io/Examples/Survey-Creator?id=options&theme=modern
It works ok for me. Can you provide any sample and/or steps to reproduce?

**Comment by Sameedkhan25** [comment]
thank you so much for your response 
I have checked out your provided link and its showing like this 

![issue modern theme 2](https://user-images.githubusercontent.com/22944289/90637659-b8d7e980-e245-11ea-8ac4-3944108bfdbc.PNG)

is there any way I can stop them overlapping the

i am currently using this code 
https://codesandbox.io/s/52rvm96lol?file=/src/SurveyCreator.js

**Comment by Sameedkhan25** [comment]
one more thing 
https://surveyjs.io/Examples/Survey-Creator?id=editor-custom-theme&theme=modern
like this example, we can change the color of the theme 
is there any way we can change the other styling of theme 
or widgets

your help will be highly appreciated

**Comment by tsv2013** [comment]
In some cases context actions don't have enough space to be placed in one line. How do you suggest to layout them?

**Comment by tsv2013** [comment]
>is there any way we can change the other styling of theme

Write custom CSS rules.

**Comment by Sameedkhan25** [comment]
> In some cases context actions don't have enough space to be placed in one line. How do you suggest to layout them?

Okay sure I will work on it

**Comment by Sameedkhan25** [comment]
> > is there any way we can change the other styling of theme
> 
> Write custom CSS rules.

oky thank u so much
