### ISSUE TITLE
when page moved , the setModified of type "PAGE_MOVED" has not excute

### ISSUE THREAD

**Issue by zhangzhenling** [surveyjs/survey-creator#943]
when page moved , the setModified of type "PAGE_MOVED" has not excute

**Comment by zhangzhenling** [comment]
at page copy. `setModified({ type: "PAGE_ADDED", newValue: newPage })`  ,execute twice!

**Comment by andrewtelnov** [comment]
@zhangzhenling I will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@zhangzhenling I have fixed these issues.

Thank you,
Andrew
