### ISSUE TITLE
Editing Checkbox and Radiogroup Items with Long Texts Extends Over Page Edge

### ISSUE THREAD

**Issue by miwn-dd** [surveyjs/survey-creator#947]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
When entering very long text for a Checkbox or Radiogroup item, the text does not scroll but instead extends out over the bounds of the page endlessly.
![image](https://user-images.githubusercontent.com/18050381/92490275-1d58e980-f1f1-11ea-94da-7541353d96b9.png)

### What is the expected behavior?
When reaching the edge of the page, the text should start scrolling (behavior of other elements like question titles)

### How would you reproduce the current behavior (if this is a bug)?
see current behavior and screenshot

#### Provide the test code and the tested page URL (if applicable)
Tested page URL:
https://surveyjs.io/create-survey

### Specify your

* browser: Google Chrome Version 85.0.4183.83 (Official Build) (32-bit)
* editor version: v1.8.0

**Comment by dk981234** [comment]
Hello,

We've fixed the issue via the referenced commit. The fix will be available with the next minor update.

Thanks,
Dmitry
SurveyJS Team
