### ISSUE TITLE
Can't set category when adding new property via Serializer.addProperty

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-creator#952]
Here is [live sample in plunker](https://plnkr.co/edit/h5qweNvfgfGIbhIg). Can't set category via `Serializer.addProperty` method, but can via `Serializer.findProperty`

![image](https://user-images.githubusercontent.com/30930391/92941391-fac90980-f458-11ea-89f6-7bbdbcc5af1a.png)

**Comment by andrewtelnov** [comment]
@gologames I found the issue. Pdf library added "rerderAs" property already and as result you can't rewrite it by creating a new "renderAs" property.

Thank you,
Andrew

**Comment by gologames** [comment]
You are right @andrewtelnov . Got the situation now
