### ISSUE TITLE
How to get answers  in a export pdf in test survey in designer

### ISSUE THREAD

**Issue by binicr** [surveyjs/survey-creator#956]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
Could you describe in greater details what do you want to achieve in our customer portal - https://surveyjs.answerdesk.io/ ?

**Comment by binicr** [comment]
Hi @tsv2013  @andrewtelnov   actually in test survey already one export pdf option is available ,but that is not containing answers.
So I need answers as well as questions in export pdf option.
I am expecting your help

**Comment by tsv2013** [comment]
Sorry, but I still don't understand what do you want to achieve :-( Test survey tab of SurveyJS Creator doesn't have the "Export to PDF" button out- of - the - box. Can you share a screenshot or a link to our demos to illustrate your goal?

**Comment by tsv2013** [comment]
As a licensed customer you can post tickets in our answerdesk portal - https://surveyjs.answerdesk.io/
