### ISSUE TITLE
Changing of options.list instance from onConditionQuestionsGetList is ignored for T5191

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-creator#957]
Live [sample in plunker](https://plnkr.co/edit/88bsFqnvYk2QhfDo)

![image](https://user-images.githubusercontent.com/30930391/93093198-11fe3600-f6a9-11ea-9a54-0d4d5335ccc2.png)

**Comment by andrewtelnov** [comment]
Here is [the working plunker](https://plnkr.co/edit/u0NzoYmvQW71zV4n). You have to change the options.list content instead of it's instance. I have added a unit test and code that will allow to modify options.list instance as well.

Thank you,
Andrew
