### ISSUE TITLE
Change the list of simulator devices

### ISSUE THREAD

**Issue by dan-sc** [surveyjs/survey-creator#960]
In the list of devices for testing the survey, is it possible to change the list? Add new ones, remove them etc? We'd like to simplify the list and have portrait the default orientation.

The list is a variable here https://github.com/surveyjs/survey-creator/blob/6489166c784bf930e8ee018eaa5df63f0cd815a4/src/components/simulator.ts#L144 and I'm wondering if it can be overridden somewhere.

Thanks!

**Comment by andrewtelnov** [comment]
@dan-sc I have added ``simulatorDevices`` as export variable. You will be able to change it as:
```js
SurveyCreator.simulatorDevices = {
  desktop: {
    deviceType: "desktop",
    title: "Desktop",
  }, /*...*/
}
```
From the next minor version.

Thank you,
Andrew
