### ISSUE TITLE
Incorrect Rating "Rate step" HTML validation

### ISSUE THREAD

**Issue by amedve** [surveyjs/survey-creator#971]
### Are you requesting a feature, reporting a bug or ask a question?
A bug.

### What is the current behavior?
Rating "Rate step" HTML5 validation error on correct value.
![image](https://user-images.githubusercontent.com/23156422/94700368-5fb1aa00-0309-11eb-924e-4756c4711fac.png)

### What is the expected behavior?
No HTML5 validation errors.

### How would you reproduce the current behavior (if this is a bug)?
It happens when Survey Creator is embedded on a page and HTML5 form validation triggered.

### Specify your

* browser: Google Chrome 85.0.4183.121 (Official Build) (64-bit)
* editor version: 1.8.6

**Comment by andrewtelnov** [comment]
@amedve Could you please fork [this example](https://plnkr.co/edit/oPCFtVrtMqODhKY3) and add the validation that produce the issue.

Thank you,
Andrew

**Comment by amedve** [comment]
@andrewtelnov https://plnkr.co/edit/mTUpSczPooNnNS2d?preview

How to reproduce: 
1. Open "Rate Values" to make "Rate step" field visible.
2. Click "Trigger form validation" button.

![image](https://user-images.githubusercontent.com/23156422/95401697-e94e1280-08db-11eb-9439-150d29985a2d.png)

**Comment by andrewtelnov** [comment]
@amedve Thank you for the example. I have fixed the issue by the commit above.

Thank you,
Andrew
