### ISSUE TITLE
Option caption of dropdown not updates

### ISSUE THREAD

**Issue by gologames** [surveyjs/survey-creator#995]
1) Go to https://surveyjs.io/create-survey
2) Add dropdown question
3) Enter `Options caption` in property grid
4) ???
5) Caption isn't updated in designer

P.S. If remove or add any dropdown choice via adorner then caption will update

![image](https://user-images.githubusercontent.com/30930391/97322657-11001d00-1881-11eb-9545-9590c6118a8e.png)

**Comment by OlgaLarina** [comment]
fixed by https://github.com/surveyjs/survey-library/pull/4902
