### ISSUE TITLE
Can't get `.text` or `.JSON` to work on the survey creator. Need to be able to load an existing survey into the creator.

### ISSUE THREAD

**Issue by nathan-at-jisc** [surveyjs/survey-creator#997]
### Are you requesting a feature, reporting a bug or ask a question?
I think I'm experiencing a bug, or just doing something wrong.

I'm trying to get the `survey-creator` to load in JSON, as if a user is editing an existing survey.

I found: https://codesandbox.io/s/z5z9b?file=/SurveyCreatorComponent.jsx:515-581

Which showed the person just doing `surveyCreator.text` or `surveyCreator.json` (https://surveyjs.io/Examples/Survey-Creator?id=setsurvey&theme=bootstrap#content-js).

I can't seem to be able to do this:

```
let surveyCreator;

const SurveyCreator = ({ surveyId }) => {

    const saveSurvey = () => {
        // postSurvey(JSON.parse(surveyCreator.text).title, surveyCreator.text);
    };

    const init = async () => {
        const surveyResponse = await getSurveyById(surveyId);

        const options = {
            showEmbededSurveyTab: false,
            showPropertyGrid: 'right',
            showToolbox: 'right'
        };

        surveyCreator = new SurveyJSCreator.SurveyCreator('surveyCreatorContainer', options);

        surveyCreator.toolbox.changeCategories([
            {
                category: 'Panels',
                name: 'panel'
            },
            {
                category: 'Panels',
                name: 'paneldynamic'
            },
            {
                category: 'Matrix',
                name: 'matrix'
            },
            {
                category: 'Matrix',
                name: 'matrixdropdown'
            },
            {
                category: 'Matrix',
                name: 'matrixdynamic'
            }
        ]);

        surveyCreator.saveSurveyFunc = saveSurvey;

        SurveyCreator.text = JSON.stringify(surveyResponse.survey);
    };

    useEffect(() => {
        init();
    }, []);

    return <div id='surveyCreatorContainer' />;
};

export default SurveyCreator;
```

The survey loads normally (just empty), I have verified that `surveyResponse.survey` is valid (I pasted the JSON into the example above). I've tried this with `.text` and `.JSON`

**Comment by andrewtelnov** [comment]
@nathan-at-jisc Please check  your `surveyResponse.survey` in console. You can replace your line with this one:
`SurveyCreator.text = {elements: [{type:"text", name: "question1"}]};`

Thank you,
Andrew

**Comment by nathan-at-jisc** [comment]
Hi Andrew,

Thanks for this. It ended up working as described in the end. No idea how to replicate, I just restarted React a few times. If it pops up again I'll try to document what caused it, very likely me just being silly though!
