### ISSUE TITLE
Adding searchablity to questions and page dropdown properties

### ISSUE THREAD

**Issue by salehasadi** [surveyjs/survey-creator#998]
### What is the current behavior?
property dropdowns are not searchable.
![image](https://user-images.githubusercontent.com/14921568/97467178-2ba5c500-1959-11eb-9da0-3a5ed9ef5249.png)

### What is the expected behavior?
I need to add search functionality to them, I tried to do this by enabling select2 on those dropdowns using "onPropertyAfterRender" event, it add search ability to those dropdowns but after this it won't trigger any event and changes won't affect survey configuration json

![image](https://user-images.githubusercontent.com/14921568/97467579-9820c400-1959-11eb-96de-047c9de27b22.png)

### How would you reproduce the current behavior (if this is a bug)?
`editor.onPropertyAfterRender.add(function (sender, options) {
		$('.svd-toolbar-dropdown__select').select2();
	});`

**Comment by andrewtelnov** [comment]
@salehasadi Unfortunately, we do not have it out of the box. We are going to include this functionality into next major version we are working on right now.

Thank you,
Andrew

**Comment by salehasadi** [comment]
> @salehasadi Unfortunately, we do not have it out of the box. We are going to include this functionality into next major version we are working on right now.
> 
> Thank you,
> Andrew

Thanks @andrewtelnov, would be nice, I appreciate it.

**Comment by OlgaLarina** [comment]
Hi @salehasadi ,

Some time ago you contacted us regarding the functionality of our Dropdown question. We are happy to announce that a reworked Dropdown version is available in SurveyJS v1.9.40. The reworked Dropdown supports a search bar, customizable item templates, and other features requested by our customers. For example, the following live demo shows the Dropdown with enabled search; its items are configured in a separate React component: [CodeSandbox](https://codesandbox.io/s/dropdown-custome-item-react-3ucg1p?file=/src/SurveyComponent.jsx).

We would appreciate if you tell us what you think about the new functionality in the comments.

SurveyJS Team
